facebook/docusaurus

packages/docusaurus-theme-classic/src/theme/DocItem/index.js
website/docs/search.md

The `keywords` and `image` field in the front matter files were broken because we were still reading them from the `metadata` when they should be read from `frontMatter` instead.
Yes
Modifed `website/docs/search.md`'s front matter to add an `image` key.

fix(v2): fix reading front matter keywords and image fields

---

packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/simple-site/docs/ipsum.md
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/metadata.test.ts
packages/docusaurus-plugin-content-docs/src/metadata.ts

Allow per-doc hiding of edit url by setting it to `null`.
Fixes #2159 
Yes
Unit tests. Also tried setting to `null` manually in a doc and see that the edit link doesn't appear.

feat(v2): allow per-doc hiding of edit url

---

packages/docusaurus/src/client/docusaurus.js

Fix #2164 
In some cases, although we have annotaed webpack chunk name with certain chunkname comment,
webpack can be more aggressive and decide to build its more efficient webpack chunk. Eg: too small
For example
```js
// registry,js
export default {
'06a89c33': [() => import(/* webpackChunkName: '06a89c33' */ "@site/docs/getting-started/configuring.md"), "@site/docs/getting-started/configuring.md", require.resolveWeak("@site/docs/getting-started/configuring.md")],
'12a37b48': [() => import(/* webpackChunkName: '12a37b48' */ "@site/docs/contributing/prerequisites.md"), "@site/docs/contributing/prerequisites.md", require.resolveWeak("@site/docs/contributing/prerequisites.md")],
'17896441': [() => import(/* webpackChunkName: '17896441' */ "@theme/DocItem"), "@theme/DocItem", …
```

fix(v2): filter out invalid prefetch script without contenthash

---

website/docusaurus.config.js

Fixes Lighthouse audit issues about Netlify badge in footer:
- Image elements do not have [alt] attributes
- Links do not have a discernible name
Yes
Run Lighthouse on preview.

fix(v2): improve accessibility for Netlify badge

---

packages/docusaurus-theme-classic/src/theme/Footer/index.js

Fix last a11y issue:
- Lists do not contain only \<li\> elements and script supporting elements (\<script\> and \<template\>)
My bad actually :man_facepalming: 
No UI changes, since list-item is a block-level HTML element like a div
Yes
Run Audit Lighthouse on preview.

fix(v2): use proper tag for custom HTML in footer

---

website/docusaurus.config.js

Since we have a link to Blog and Netlify, it seems to me to rename the title of last item in the footer to something more general like "More".
Yes
See Netlify preview.

refactor(v2): change title of last footer column

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css

I thought to make a collapsible sidebar and put a button to hide the sidebar to menu, but this idea did not find approval, so I fix this bug with height after merge #2161
Yes
| ![image](https://user-images.githubusercontent.com/4408379/71643917-f72d9200-2cd0-11ea-8d23-f265f7d98368.png) | ![image](https://user-images.githubusercontent.com/4408379/71643919-fe54a000-2cd0-11ea-81d3-83fa43e246a6.png) |

fix(v2): make doc sidebar height equal viewport

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css

Make correct vertically centering of sidebar menu close icon on mobiles. 
Yes
| ![image](https://user-images.githubusercontent.com/4408379/71666549-60b1ad00-2d72-11ea-8dc6-fd2eac532e2b.png) | ![image](https://user-images.githubusercontent.com/4408379/71666568-7a52f480-2d72-11ea-9e08-98b7cd108a72.png) |

fix(v2): adjust sidebar menu close icon to center

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/algolia.css
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/styles.css

We should not lazy loading styles related to mobile devices (see test plan).
Yes
| ![image](https://user-images.githubusercontent.com/4408379/71668005-61e5d880-2d78-11ea-9602-93403d375f4d.png) | ![image](https://user-images.githubusercontent.com/4408379/71668356-9e660400-2d79-11ea-9726-38b1e0c085df.png) |

fix(v2): load Algolia styles for mobiles immediately

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css

Currently, the sidebar logo is positioned 2px lower than the navbar logo (see test plan).
Yes
With `z-index = -1` to `navbar`.
|   |  |
| Before | ![screencast-nimbus-capture-2020 01 03-00_14_13](https://user-images.githubusercontent.com/4408379/71693690-2968ed80-2dbe-11ea-9a45-d3c1cb05b0da.gif) |
| After | ![screencast-nimbus-capture-2020 01 03-00_13_29](https://user-images.githubusercontent.com/4408379/71693686-240ba300-2dbe-11ea-8e52-8f4334d7f90b.gif) |

fix(v2): make sidebar logo positioning relative navbar

---

website/src/pages/showcase/index.js

In general, initially on mobiles, I noticed that the elements lacked a margin bottom (see screenshot), and therefore wanted to fix it, but then looked around and realized that it is possible to simplify the markup with minimal changes in the UI of the page.
Yes
Click to Showcase page on preview and compare it with current version.

refactor(v2): simplify markup of Showcase page

---

packages/docusaurus-theme-classic/src/theme/hooks/useTheme.js

Fixes #2176 
Yes
1. Set `themeConfig.disableDarkTheme: true` in `docusaurus.config.js`
1. Run `localStorage.theme = 'dark'` in JS console. This simulates the scenario where a site previously had dark mode toggle and then it was disabled
1. Start the site locally
1. See that the site is not dark

fix(v2): don't read theme from localStorage if disableDarkMode is on

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

Fixes #2175 
Yes
1. Load Netlify preview (try on mobile too)
1. Click on the search bar
1. See that it doesn't lose focus

fix(v2): make search bar not lose focus after clicking on it after initial load

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
packages/docusaurus/src/client/exports/Link.js
packages/docusaurus/src/client/exports/utils.js

Close #2185 
Currently, not possible to add an item with an external link in the doc sidebar.
Yes
Add an item with an external link in sidebars.js file, eg:
```js
{
type: 'link',
label: 'Docusaurus',
href: 'https://v2.docusaurus.io',
},
```

fix(v2): allow external links in doc sidebar

---

packages/docusaurus-1.x/lib/core/renderMarkdown.js

The JSX highlighting is subtly broken:
Notice how plain text in JSX gets incorrectly highlighted.
This was fixed in https://github.com/PrismJS/prism/pull/1357 but I couldn't get the fix to work at all. Then I noticed we're not passing the [documented third argument](https://prismjs.com/extending.html) to Prism, so it doesn't actually use the JSX language for tokenization.
This PR fixes it.

fix(v1): fix JSX highlighting by passing language to Prism

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus-theme-classic/src/theme/hooks/useLockBodyScroll.js

Continuation of #2129 but for sidebar menu plus move logic of prevent scrolling into separate hook. 
Yes
1. Open preview website on mobile
1. Click to sidebar menu
1. Try scrolling the webpage

refactor(v2): disable scroll when sidebar menu is open

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

A continuation of #2178 and resolve #2175 
Fix for loss of focus in search input on all screens. Moreover, this PR fixes Algolia loading on screens up to 360px, currently the search on these screens did not work  :cry: 
Yes
1. Load Netlify preview (try on mobile too)
1. Click on the search bar
1. See that it doesn't lose focus

fix(v2): fix input losing focus on init

---

packages/docusaurus-init/templates/classic/docs/doc1.md

This is Python2 print syntax, and Python2 just reached end-of-life, so swapping it over to Python3 print syntax.
Minor change - no testing plan needed.

fix(v2): (docusaurus-init) remove deprecated Python statement

---

packages/docusaurus/src/client/templates/ssr.html.template.js

Finishing up a PR made by @endiliey. Improve performance by preloading scripts needed by the page which is only inserted at the bottom of the page. Gatsby does this too.
Yes
See the `index.html` of Netlify preview.

feat(v2): preload first page load script asap

---

website/src/pages/styles.module.css

Currently, on mobiles, when the logo (which is transparent always) is animated, then its background is overlays on upper part tagline.
Yes
Open preview on mobile and make sure there is no background during animation.

fix(v2): remove logo background

---

website/versioned_docs/version-2.0.0-alpha.40/using-plugins.md

copy/pasted comment referred to "blogs" not "docs".
I was reading the docs and got confused :) 
Yes
N/A
N/A

docs(v2): fix plugin-content-docs config comment typo

---

website/docs/theme-classic.md
website/versioned_docs/version-2.0.0-alpha.40/theme-classic.md

When you click on the link to view the available Prism themes, it points to as section in the README that does **not** list the themes. Instead, you must look at the `themes` directory. This PR updates that link to point to the right place :) 
Yes
N/A (link change - no test needed?)

docs(v2): update link to available prism themes

---

website-1.x/data/users.js

I went through the examples in https://docusaurus.io/en/users and found a couple that moved away from docusaurus. 
These were removed:
https://docs.nteract.io/
https://atalaya.io/
Yes.
Passed `yarn run test`. Nothing to write a test for here.
N/A

chore(v1): Updated users list, removing sites not using docusaurus

---

packages/docusaurus-plugin-content-pages/src/index.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus/src/webpack/base.ts

Most of our codebase is in Typescript. We want some dynamic documentation to where we can reference variables in Typescript files. It would be awesome to further support inline Typescript files as well.
This is a very simple change that enables a lot of possibilities.
Yes
Pretty straight forward!
- Try putting a `.ts` file in the pages folder (and a `.js` file for backwards compatibility) and test it compiles
- Try putting a `.ts` or a `.tsx` file somewhere in the project, then reference it in any `.md` or `.mdx` file and be amazed as it works
Let me know how we want this documented (a page or a footnote) and I'll add it to the PR.
Fixes #2120

feat(v2): allow for Typescript pages and components

---

packages/docusaurus/src/client/templates/ssr.html.template.js

This PR should fix the issue #2157 : yarn build is failing when there are special characters in markdown files.
Yes 😄 
- I've reproduced the issue by adding "< 8" in `website/versionned_docs/blog.md` title
- After investigation, I have changed the `ssr.html.template.js` file to escape the input HTML (cf EJS feature)[https://github.com/tj/ejs#features]
- I've launched again `yarn build` which has succeeded
- Finally, i've launched the build on a local server to check that the result was fine

chore(v2): handle pages which contain special chars

---

packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js

Currently, the correct syntax theme is not applied to live code blocks, if you go **not** through client navigation (for example, open a link directly). This PR fixes this.
Yes
Compare current version (https://v2.docusaurus.io/docs/markdown-features/) with preview one.

fix(v2): render correct theme for live code blocks on SSR

---

packages/docusaurus-mdx-loader/src/remark/rightToc/search.js

This PR resolves #2157.
Yes
See To Reproduce section in issue #2157.

fix(v2): escape link text in TOC

---

packages/docusaurus/src/server/__tests__/__snapshots__/routes.test.ts.snap
packages/docusaurus/src/server/__tests__/routes.test.ts
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/routes.ts

This PR resolves #2229.
Yes
See To Reproduce section in issue #2229.

fix(v2): include base url in 404 route

---

packages/docusaurus-theme-classic/src/theme/Heading/index.js
packages/docusaurus-theme-classic/src/theme/Heading/styles.css
packages/docusaurus-theme-classic/src/theme/Heading/styles.module.css
packages/docusaurus-theme-classic/src/theme/hooks/useHideableNavbar.js

First of all, remove large margin on all screens (see test plan) when following a link from anchor. Further, when you open the referenced link in the browser, the header is automatically hidden, similarly when switching to another anchor on this page.
Yes
Prerequisite: open link with anchor, eg https://v2.docusaurus.io/docs/installation#project-structure
| ![image](https://user-images.githubusercontent.com/4408379/71564768-223c9980-2ab7-11ea-93d9-4642c1280a70.png) |  ![image](https://user-images.githubusercontent.com/4408379/71564766-1ea91280-2ab7-11ea-8fec-16057e364410.png) |

fix(v2): unify anchor behavior

---

packages/docusaurus-theme-classic/src/theme/DocPage/index.js
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js

Since the router configures with case-insensitive paths (by default), we will display the page correctly if the path is written in a different case (`creating-Pages` -> `creating-pages` (proper path), and vice versa). _Although my personal opinion is that in this case you need to display a 404 error, because this is technically the wrong address, it means that we need to work it out correctly._
However, changing current behavior will result in breaking changes, which is best avoided, so let's leave it as it is. But as noted in issue #2190, in such cases the doc sidebar is not shown. This PR fixes this.
Yes
1. Change or create the id of front matter and filename of any doc page to case-sensitive, eg:
```diff
- id: docusaurus-core
+ id: Docusaurus-Core
```
Make the appropriate changes also …

fix(v2): show doc sidebar on pages with case-sensitive paths

---

packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-blog/src/markdownLoader.ts
packages/docusaurus-plugin-content-blog/src/types.ts
packages/docusaurus-theme-classic/src/theme/BlogListPage/index.js

Fix the bug reported on Canny - https://docusaurus.canny.io/admin/board/feature-requests/p/allow-no-truncate-on-blog-post
Yes
Check that the blog post without the `` marker does not display the Read more button on the blog lists page.

fix(v2): hide read more button on non-truncated posts

---

packages/docusaurus-theme-classic/src/theme/hooks/useHideableNavbar.js
packages/docusaurus-theme-classic/src/theme/hooks/useLocationHash.js

In PR #2162 I missed up one use case: when a user opens a web page with an anchor (hash). At the moment, in this case the navbar is **always hidden**, even if the page scrolls to the top.
To demonstrate this bug see GIF (target path - docs/introduction/#️-disclaimer):
The previous implementation with `document.activeElement` was wrong, because in fact we have no way via JS to determine the active (focused) anchor. (In CSS, this is possible through the pseudo-class `:target`). Therefore, in order to achieve the desired result, it was required to track the change in the hash location and then synchronize the changes in the hash URL (when switching (updating) the route).
As a result, there was more code, but the behavior of hideable navbar is what it should be.
Yes
1. Navigate to URL with …

fix(v2): adjust correct behavior of navbar when active anchor

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.js
packages/docusaurus-theme-classic/src/theme/Layout/index.js
website/src/pages/index.js

Resolves https://docusaurus.canny.io/admin/board/feature-requests/p/allow-browser-tab-title-to-have-a-prefix
Bcause this is the expected behavior (especially since it was in v1) - the site name is usually contained in the title itself and this is suitable for most websites (+ better for SEO).
The only thing I'm not sure about existing a tagline in the case when the title is not set, in v1 there was even a separate config parameter ([`disableTitleTagline`](https://docusaurus.io/docs/en/site-config#disabletitletagline-boolean)) that removes the tagline from the final meta title, but I do not think it is a good idea to implement it in v2.
https://github.com/facebook/docusaurus/blob/7e60a283f13d92d1edfaf9d5698a5ff721db29da/packages/docusaurus-1.x/lib/core/Site.js#L38-L42
Maybe then do not …

feat(v2): add site title to meta title

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus-theme-classic/src/theme/ThemeContext.js
packages/docusaurus-theme-classic/src/theme/ThemeProvider/index.js
packages/docusaurus-theme-classic/src/theme/hooks/useTheme.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js

A simple small refactoring in the `useTheme` hook, in order to avoid using of raw values ('' and 'dark') for the theme in the code base. It seems to me that it has become more understandable and easier.
Yes
Make sure theme switching works as before.

refactor(v2): avoid to use raw theme values

---

website/docs/sidebar.md

From discord:
> Hi there! First of all, thx for this amazing project!
I like the collapsible sidebar but the possibility to choose wish one have to be open by default could be a real plus.
Should I open a feature request? Or does it make sense?
I previously added the ability to expand all categories in the doc sidebar, as it was in D1 by default, but this was only documented in Migration from v1 to v2 guide, so new users (who did not use Docusaurus at all) did not know about this possibility. This PR documents this feature in the Sidebar page so that all users know about it
Yes
See Sidebar page.

docs(v2): collapsible categories in sidebar

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js
website/docs/theme-classic.md

Resolve https://docusaurus.canny.io/admin/board/feature-requests/p/customize-nav-logo-link
Yes
Specify `themeConfig.navbar.logo.link` property with any valid link (relative or external).

feat(v2): allow specify custom link for logo

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

PR #2188 brought an unpleasant side effect - when you hover over the search field, auto focus occurred on this field. 
Yes
Check the search input work - when hovering, when focus, also consider mobiles.

fix(v2): remove focus on search input when hovering over it

---

website/docs/markdown-features.mdx
website/docs/migrating-from-v1-to-v2.md
website/versioned_docs/version-2.0.0-alpha.38/markdown-features.mdx
website/versioned_docs/version-2.0.0-alpha.38/migrating-from-v1-to-v2.md
website/versioned_docs/version-2.0.0-alpha.39/markdown-features.mdx
website/versioned_docs/version-2.0.0-alpha.39/migrating-from-v1-to-v2.md
website/versioned_docs/version-2.0.0-alpha.40/markdown-features.mdx
website/versioned_docs/version-2.0.0-alpha.40/migrating-from-v1-to-v2.md

…ttributes in Docusaurus 2
Resolving #2252, add docs about v2 requiring use of JSX flavored style object syntax as opposed to style attributes in v1.
Yes.
Preview
NA

docs(v2): require using JSX flavored style objects in mdx

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js
website/docs/theme-classic.md

Resolving of https://docusaurus.canny.io/admin/board/feature-requests/p/specify-different-dark-mode-logo
Since we have dark mode enabled by default, it makes sense to give our users the ability to set a different logo for dark mode.
Yes
Specify `logo.darkSrc` filed and switch to dark mode to make sure the logo has changed.

feat(v2): allow to specify different logo for dark mode

---

docs/getting-started-installation.md

My node version is 8.9.4, npm version is 5.6.0.
When I run command docusaurus-init in my environment, there is no doc folder, and only package.json file in the website folder.
Close #2198
So, I update `getting stated` documentation compatible with current LTS version `(Node.js >= 10)`
👌 
- https://github.com/facebook/docusaurus/pull/2207

docs(v2): drop support for node <10.9

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.js
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
packages/docusaurus/src/client/exports/Link.js
packages/docusaurus/src/client/exports/utils.js

Adding basic feature to form plural word forms. This is of course a very simple util function, and when localization functionality appears, it needs to be improved, but at the moment it is doing its job perfectly
Yes
| ![image](https://user-images.githubusercontent.com/4408379/73599705-4e848380-4557-11ea-99d8-13a5ebe36ae1.png) | ![image](https://user-images.githubusercontent.com/4408379/73599706-5a704580-4557-11ea-92e4-bf75b03adc38.png) |

feat(v2): pluralize posts on tag's page

---

packages/docusaurus-init/templates/classic/docs/doc1.md
packages/docusaurus-init/templates/facebook/docs/doc1.md
packages/docusaurus-preset-classic/package.json
packages/docusaurus-preset-classic/src/index.js
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/index.js
website/docs/markdown-features.mdx
website/docs/presets.md

I wrote a remark plugin for admonitions ([`remark-admonitions`](https://github.com/elviswolcott/remark-admonitions)) and mentioned it over in https://github.com/facebook/docusaurus/issues/1238. @yangshun suggested I add it to `@docusaurus/preset-classic` so I did.
Yes
I tested it in two ways.
1. Creating a new site with the modified version of `@docusaurus/init` using both templates
1. Creating a new site from scratch using the modified version `@docusaurus/preset-classic`
I haven't added anything to the docs yet as I'm not sure where it would fall under. Right now I'm thinking any docs would go in https://v2.docusaurus.io/docs/markdown-features if admonitions need to be mentioned.

feat(v2): add remark-admonitions to @docusaurus/preset-classic

---

packages/docusaurus-theme-classic/src/theme/BlogListPage/index.js
packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.js
packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.js

Resolving of https://docusaurus.canny.io/admin/board/feature-requests/p/how-to-change-title-on-blog-only-mode (see also this [comment](https://docusaurus.canny.io/admin/board/feature-requests/p/how-to-change-title-on-blog-only-mode))
When using Docusaurus as a [blog-only mode](https://v2.docusaurus.io/docs/blog/#blog-only-mode), the title of the main page is just "Blog", although in this case it is expected to see the site title (specified in the config file).
In addition, as part of this PR, the title of other blog-related pages (tags lists and post tag pages) has been adjusted to make them more suitable for blog-only mode.
Yes
Enable blog-only mode and check meta titles. …

fix(v2): use site title if enabled blog-only mode

---

docs/getting-started-publishing.md
website/docs/deployment.md
website/versioned_docs/version-2.0.0-alpha.38/deployment.md
website/versioned_docs/version-2.0.0-alpha.39/deployment.md
website/versioned_docs/version-2.0.0-alpha.40/deployment.md

In #2258, it is described that the publish script fails on Windows. The problem is caused by a whiteline that is appended to the GIT_USER env variable on windows  when you run `cmd /C "set GIT_USER=<GIT_USER> && set CURRENT_BRANCH=master && set USE_SSH=true && yarn run publish-gh-pages"`. The same issue is also in v2, where the command is `cmd /C "set GIT_USER=<GITHUB_USERNAME> && yarn deploy"`.
We can fix the problem by using delayed expansion (surrounding `GIT_USER=<GIT_USER>` with quotation marks).
Yes
Tested locally on Windows by running the deploy command on both v1 and v2.

docs: update windows deploy command

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js

Fixes #2284 (copy button in CodeBlock ignores blank line in code block)
Yes!
- Click "Copy" button in CodeBlock with blank lines(ex: https://v2.docusaurus.io/docs/creating-pages#adding-a-new-page)
- Paste to editor
This is a PR to add "Copy" button https://github.com/facebook/docusaurus/pull/1643

fix(v2): fix codeblock copy button not including blank lines

---

packages/docusaurus-plugin-google-analytics/src/analytics.js
packages/docusaurus-plugin-google-gtag/src/gtag.js
packages/docusaurus/src/client/clientEntry.js
packages/docusaurus/src/client/exports/ExecutionEnvironment.js
packages/docusaurus/src/client/exports/Link.js
website/docs/docusaurus-core.md

Add a new client API to determine the current execution environment (whether on server or client). This helps to clean up some of our code where we do `typeof window !== 'undefined'`. Some users are facing SSR issues as well and this API could be used by them as well.
Also reorganized the client API docs and added categories.
Yes
Preview

feat(v2): add ExecutionEnvironment API

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js
website/docusaurus.config.js

Attempts to fix #2222 and as an alternative to #2243. I think this solution is better than in #2243 as it is a general solution and can be useful for other kinds of pages as well.
If approved, I'll add docs for this feature and add this new property to the templates.
Yes
Click on docs links in preview.

feat(v2): allow navbar links to show active style by specifiying a base path

---

docs/getting-started-publishing.md

additional space after GIT_USER=<GIT_USER> && was throwing errors on windows
I had an issue publishing to gh pages from windows. Created an issue and got a solution which I'm now passing on as a pr!
https://github.com/facebook/docusaurus/issues/2258
Fixes #2258 
Yes
I tried pushing a change to my gh-pages docs with the space "<GIT_USER> &&" it failed, when I tried without a space <GIT_USER>&&  it worked.

docs(v1): fix Windows instructions for GitHub Pages publishing

---

packages/docusaurus/src/webpack/utils.ts

With #2221 docusaurus v2 is able to detect `{ts,tsx}` pages and components, but as soon as babel hits TypeScript syntax it fails. While the docusaurus `babel.config.js` includes `@babel/preset-typescript`, `babel-loader` inside the Webpack config does not.
Yes
1. Add `typescript.tsx` to your pages directory
2. Add TypeScript syntax
```
export default () => {
let name: string = 'World';
return (
<h1>Hello {name}!</h1>
);
};
```
3. Run docusaurus
4. Check localhost:3000/typescript
#2221

chore(v2): Add @babel/preset-typescript to babel-loader

---

packages/docusaurus-theme-classic/src/theme/Footer/index.js
website/docs/docusaurus.config.js.md
website/docs/migrating-from-v1-to-v2.md

I have repeatedly heard in Discord how users needed to add a link to footer copyright, but to do this except via swizzling the `Footer` component, at the moment this is not possible.
I think we could add such a tiny but useful addition.
Yes
Add any valid HTML in `footer.copyright` field of config file.

feat(v2): add ability to use HTML in footer copyright

---

packages/docusaurus-1.x/examples/basics/pages/en/users.js
packages/docusaurus-1.x/examples/basics/siteConfig.js

- Fixes #2275 
- Minor fix in `siteConfig` to remove extra whitespace in code comment 
Yes.
I first reproduced the issue locally following the instructions in the issue. After that, I implemented the change they suggested in that local docusaurus project and it fixed the issue.
N/A

fix(v1): check repoUrl before using on users.js

---

packages/docusaurus-plugin-content-pages/src/__tests__/__fixtures__/website/src/pages/typescript.tsx
packages/docusaurus-plugin-content-pages/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts
website/docs/creating-pages.md

This was not a quick way to add support for pages in TypeScript - [one](https://github.com/facebook/docusaurus/pull/2221), [two](https://github.com/facebook/docusaurus/pull/222), and finally this third (and last) attempt for this! Now officially D2 supports the creation of pages in TS, woohoo!
Corresponding request on Canny - https://docusaurus.canny.io/admin/board/feature-requests/p/typescript-pages
Yes
1. Create a page in TS (eg `page.tsx`) with any valid contents, for example:
```tsx
import React, {useEffect} from 'react';
import Layout from '@theme/Layout';
function Page() {
let name: string = 'TypeScript';
return (
<Layout>
<div className="container margin-vert--xl">
<h1>Hello {name}!</h1>;
</div>
</Layout>
);
}
export default Page;
```
2. Start D2 and check it out new page by …

fix(v2): make proper path to pages in TS

---

packages/docusaurus-theme-classic/src/index.js
packages/docusaurus-theme-classic/src/theme/hooks/useTheme.js

Resolve #2295.
Yes
Go to preview and in the settings of your OS change the system theme to the opposite (dark -> light and vice versa). Make sure the theme and the toggle state in navbar change appropriately on the preview website.

fix(v2): switch a toggle when system theme changed

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js

Resolve #2308.
Yes
The same as for #2261 but in addition to build the website and see that the logos are displayed correctly.

fix(v2): properly set dark mode logo on build-time prerendering

---

website/docs/installation.md

Add information on how to update/upgrade the version of Docusaurus

docs(v2): guide on upgrading Docusaurus within a project

---

website/docs/deployment.md

Prevent users from experiencing 404's with pages that are named with underscores
Closes #2332 
Yes
N/A

docs(v2): mention about disabling Jekyll when using GitHub pages

---

website/docs/markdown-features.mdx
website/versioned_docs/version-2.0.0-alpha.43/markdown-features.mdx

Removing typo errors, making documentation more useful.
Not required.

docs(v2): fix typo in remark-admonitions example

---

packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/blog/draft.md
packages/docusaurus-plugin-content-blog/src/__tests__/__snapshots__/generateBlogFeed.test.ts.snap
packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
website/docs/blog.md

Resolve https://github.com/facebook/docusaurus/issues/2314
Yes
1. Create a new blog post with approximately the same contents:
```md
---
title: Draft post
draft: true
---
This post is in WIP state and should not be published!
```
2. Run local development server and make sure the new blog post is displayed.
3. Build website and make sure the new blog post is **not** in the posts list.

feat(v2): add draft feature to blog posts

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js
website/docs/theme-classic.md

Resolve #2339.
This is really useful if users are hosting a website with documentation in a subdirectory of the main site (baseUrl has been changed) and therefore the '/' link will lead to a 404 error (read comments of the issue).
Yes
1. Set the external link for the `navbar.logo.href` property, and set the `navbar.logo.target` property to "_self" - make sure that the external link opens in the current tab (thus, we override  the default value when the external link opens in a new tab). This use case is the main goal of PR.
2. In contrast to the first item, set the `navbar.logo.href` property to some internal link, and put "_blank" in the `navbar.logo.target` property, now the internal link should open in a new tab.
(If this PR adds or changes functionality, please take some time to …

feat(v2): allow specifying custom target for logo link

---

website/docs/using-plugins.md

docs: add an example value for the remarkPlugins config option for plugin-content-blog and plugin-content docs.
Initially I tried to use a string value with this config and got an esoteric error. Having an example of it's usage would help.
Yes
View the `using-plugins.md` file, and ensure an example value for the `remarkPlugins` config exists for both the `@docusaurus/plugin-content-docs` and `@docusaurus/plugin-content-blog` config docs.

docs(v2): add examples to plugin usage doc

---

website/docs/lifecycle-apis.md
website/versioned_docs/version-2.0.0-alpha.39/lifecycle-apis.md
website/versioned_docs/version-2.0.0-alpha.40/lifecycle-apis.md
website/versioned_docs/version-2.0.0-alpha.43/lifecycle-apis.md

Fix getPathsToWatch() example syntax issue
Fix issue in documentation.

docs(v2): fix getPathsToWatch() example syntax in lifecycle APIs

---

.stylelintrc.json
package.json
packages/docusaurus-init/templates/classic/src/css/custom.css
packages/docusaurus-init/templates/classic/src/pages/styles.module.css
packages/docusaurus-init/templates/facebook/.stylelintrc.json
packages/docusaurus-init/templates/facebook/package.json
packages/stylelint-copyright/README.md
packages/stylelint-copyright/_tests_/index.js
packages/stylelint-copyright/index.js
packages/stylelint-copyright/package.json
yarn.lock

1. Adds [stylelint](https://stylelint.io/)
2. Adds a custom stylelint plugin to check css files for a copyright header comment
3. Integrates stylelint into GitHub CI checks
4. Adds and integrates stylelint into FB template
Fixes #2321
Yes.
`yarn lint`
You can also remove the word "copyright" from an existing CSS file and check that `yarn lint` fails.
N/A

chore(v2): add stylelint

---

packages/docusaurus-theme-classic/src/theme/Layout/styles.css

Resolve #2364
Yes
No UI changes. Try it out on preview.

refactor(v2): increase CSS specificity on application container

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js

Resolve #2352
Yes
Suppose we have an indented code block:
````
```
--chart string                                   A helm chart to deploy (e.g. ./chart or stable/mysql)
--chart-repo string                              The helm chart repository url to use
--chart-version string                           The helm chart version to use
--component devspace list available-components   A predefined component to use (run devspace list available-components to see all available components)
--context string
--dockerfile string                              A dockerfile
-h, --help                                           help for deployment
--image string                                   A docker image to deploy (e.g. dscr.io/myuser/myrepo or dockeruser/repo:0.1 or mysql:latest)
--manifests string …

fix(v2): remove line break from end of code blocks

---

website/docs/configuration.md

There's information on a Blog-only mode but there's none for a Docs-only mode. The same principle applies, and are documented in this documentation addition.
Yes

docs(v2): add section for docs-only mode

---

packages/docusaurus/src/webpack/client.ts

Resolve #2311.
Server build uses the `WaitPlugin` plugin, which waits until a client bundle is created. This wait is infinite, so if the building of client bundle fails, the build process enters idle mode.
https://github.com/facebook/docusaurus/blob/32c1a92b17bdc347add828be97a49991c0611146/packages/docusaurus/src/webpack/server.ts#L49-L52
Yes
- In a MDX file try to import unresolvable dependency e.g.:
```md
---
id: mdx
title: MDX page
---
import Blah from 'Blah';
Heading...
```
Prior to this fix, the build process became idle and needed to be killed (for example, by pressing CTRL + C)
Now the build process in case of an error in the client bundle terminated immediately.
Results:
| Before (idle)  | After (forced terminated)    |
| …

fix(v2): force terminate building if client bundle failed

---

website/docs/configuration.md

The docs-only mode instructions didn't work, this change clarifies the instructions and adds an additional step for the index page.
Yes
N/A
https://github.com/facebook/docusaurus/pull/2378

docs(v2): clarify instructions on docs-only mode

---

packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts

Fixes #2404.
Currently `@docusaurus-utils.normalizeUrl` method misbehaves when the input contains a single forward slashes `/`, returning duplicated slashes `//`. This occurs when the `routeBasePath` is set to '/' in the docs plugin configuration for example.
Input: `[ '/metro/', '/', '2.0.0-alpha.43' ] `
Output: `/metro//2.0.0-alpha.43`
Expected output: `/metro/2.0.0-alpha.43`
Yes.
| Input       |  Normalized URL Path  |
| ------------- |-------------|
| [ '/metro/', '/', '2.0.0-alpha.43' ]    | /metro/2.0.0-alpha.43 |

fix(v2): properly dedupe forward slashes in the entire URL path

---

website/docs/search.md
website/versioned_docs/version-2.0.0-alpha.40/search.md
website/versioned_docs/version-2.0.0-alpha.43/search.md
website/versioned_docs/version-2.0.0-alpha.48/search.md

appId is needed for self-hosted Docsearch
Update Algolia information. The information is similar for v1: https://docusaurus.io/docs/en/site-config.html#algolia-object
Not yet
I used it on my personal site
None

docs(v2): include appId key for Algolia

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.js
packages/docusaurus-theme-classic/src/theme/Layout/index.js

```js 
// docusaurus.config.js
...
themeConfig: {
// Relative to your site's "static" directory.
// Cannot be SVGs. Can be external URLs too.
image: 'img/docusaurus.png',
...
},
}
```
https://github.com/facebook/docusaurus/blob/2b6e4409704fb20a39a9273b1b051065f0eb8079/website/docs/theme-classic.md#meta-image
Currently, when url is setted to `themeConfig.image`, this does not work as below.
`https://example.comhttps://example.com/img/foo.png`
This fixes it.
Yes
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to …

fix(v2): fix external URL for og:image tag

---

packages/docusaurus/src/commands/deploy.ts
website/docs/deployment.md

At the moment there can be some issues with using github pages from a non `.github.io` ending url. For example when using `.github.company.co`. We can resolve this by introducing an environment variable for selecting the deployment branch.
Yes
1. run `GIT_USER=user DEPLOYMENT_BRANCH=master yarn deploy`
2. Succesfully deploys to the master branch
related bug report https://github.com/facebook/docusaurus/issues/2362

feat(v2): can target deployment branch with environment variable

---

packages/docusaurus/src/client/exports/__tests__/isInternalUrl.ts
packages/docusaurus/src/client/exports/isInternalUrl.js

Make fixes as per comment https://github.com/facebook/docusaurus/pull/2420#issuecomment-600021996 from @38elements.
Yes
See tests.

fix(v2): make correct internal link check

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/deploy.ts
packages/docusaurus/src/server/index.ts
website/docs/cli.md

Resolves #2410
Docusaurus 2 added the ability to specify a `siteDir`, so it would be nice if the output directory of the build could be changed as well. I have been working in an nx workspace, and all builds end up in `dist` at the root with my docs website at `apps/website`. Currently, there is no way to place the build anywhere except for inside the `siteDir`.
Yes
I tested all these changes by running `npx @docusaurus/init@next init` to create a new repo. I built the packages and copied them over to the new repo. 
1. Ran `yarn build` to verify normal behavior
2. Ran `yarn build --outDir build/nested` to verify custom output directory
3. Created a nested version by copying all docusaurus related content into a nested folder called `nested`
4. Ran `yarn build nested` to verify normal …

feat(v2): allow custom output directory for build

---

.eslintignore
.eslintrc.js
jest-setup.js
jest.config.js
packages/stylelint-copyright/__tests__/index.js
packages/stylelint-copyright/package.json
yarn.lock

Fixes #2370 
Yes
`yarn lint && yarn test`

misc: improve stylelint rule 

---

packages/docusaurus-mdx-loader/package.json
packages/docusaurus-mdx-loader/src/index.js
packages/docusaurus-mdx-loader/src/remark/rightToc/__tests__/__snapshots__/index.test.js.snap
packages/docusaurus-mdx-loader/src/remark/rightToc/__tests__/index.test.js
packages/docusaurus-mdx-loader/src/remark/rightToc/search.js
packages/docusaurus-mdx-loader/src/remark/slug/__tests__/index.test.js
packages/docusaurus-mdx-loader/src/remark/slug/index.js

Resolve #2419
Currently, the use of HTML in headings is reflected in slug, see the example below:
Using this heading:
```md
```
will lead to slug of "_span-classname-faq-header-general_" instead of "_general_".
I made a kind of fork [remark-slug](https://github.com/remarkjs/remark-slug), because to solve this bug we need to change the way the slug is generated. To ensure that nothing broke, I adopted the tests from the underlying lib (rewritten to Jest) and added a new test that confirms the fix for this bug.
Yes
Try add heading which contains HTML (see Motivation section for sample).

fix(v2): remove HTML from heading slug

---

.gitignore

Jetbrains IDE generally generate a docusaurus.iml at the root of the project, which should rather not be commited by contributors.
As there's already ".idea" and ".vscode," I thought this one is just missing, and adding it will be welcome for contributors using Jetbrains
I'm using Intellij, and currently discussing with @JoelMarcey about contributing to this project. I thought this would be a nice small PR to get started :D
Yes
N/A
N/A

chore(v2): ignore jetbrains editors .iml files

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js

Resolve #2430
Yes
1. Specify path to logo for dark mode in `themeConfig.navbar.logo.srcDark` option.
2. Make sure that dark logo is displayed when dark mode is turned on

fix(v2): add support dark logo for sidebar logo

---

packages/docusaurus-theme-classic/src/theme/Layout/index.js

According to https://socialsharepreview.com/ and SEO recommendations need to use summary_large_image for Twitter card.
Yes.
Check it out at https://socialsharepreview.com/

fix(v2): update twitter:card to summary_large_image

---

packages/docusaurus/src/webpack/client.ts

Resolve #2390
This is really inconvenient during development (and therefore degrades DX) and should only be enabled at building.
Yes
- In a MDX file try to import unresolvable dependency e.g.:
```md
---
id: mdx
title: MDX page
---
import Blah from 'Blah';
Heading...
```
When executing the `yarn start` command, an error should be displayed and the process go to idle. But during the build (`yarn build` command), the process should force terminate along with the error display.

fix(v2): do not force terminate building if client bundle failed in development mode

---

packages/docusaurus/src/client/serverEntry.js
packages/docusaurus/src/client/templates/ssr.html.template.js

Often, the version is also indicated in the meta generator tag, for example, Wappalyzer can display it and it just helps us in future with feedback to users.
Yes
```diff
- <meta name="generator" content="Docusaurus">
+ <meta name="generator" content="Docusaurus v2.0.0-alpha.48">
```

feat(v2): add version to meta generator

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus-theme-classic/src/theme/hooks/useLogo.js

When the sticky navbar is turned off, the duplicating logo in the sidebar should be clickable, this is the expected behavior in this case.
Yes
Try clicking on the logo in doc sidebar.

feat(v2): make clickable sidebar logo

---

website/docs/resources.md

Add `docusaurus-plugin-sass` to the list of community plugins for those looking for Sass support.
Yes.

docs(v2): add docusaurus-plugin-sass to community plugins

---

website/docs/styling-layout.md

For those looking for Sass/SCSS support and to show how modular v2 is ;), I added a small section to the styling section on how to use Sass with docusaurus v2 via the unofficial plugin I created.
Yes.

docs(v2): add Sass/SCSS in docs under the styling section

---

packages/docusaurus/src/client/PendingNavigation.js
packages/docusaurus/src/client/__tests__/normalizeLocation.test.js
packages/docusaurus/src/client/normalizeLocation.js

Fixes #2392
Yes.
The `PendingNavigation` component now uses a `normalizeLocation` function. I added a single file for the new function to easily add unit tests and check the proper normalization of the pathname in the location object before it is passed to react-router's `Route` components for matching:
| Original Path       |  Normalized Path  |
| ------------- |-------------|
| /docs/introduction/index.html      | /docs/introduction |
| /docs/introduction    | /docs/introduction      | 
| /docs/introduction/foo.html    | /docs/introduction/foo.html        | 
| /index.html | /  |
| / | /  |

fix(v2): normalize location for route matching

---

packages/docusaurus-preset-classic/src/index.js

Resolves #2447
Currently it is impossible to pass options to the `remark-admonitions` plugin due to misconfiguration.
Yes
1. Create a new Docusaurus v2 site with `@docusaurus/init`
1. Add config from #2447
1. npm start
```js
presets: [
[
'@docusaurus/preset-classic',
{
docs: {
sidebarPath: require.resolve('./sidebars.js'),
editUrl:
'https://github.com/facebook/docusaurus/edit/master/website/',
admonitions: {
customTypes: {
kk: {
keyword: 'kk',
svg:
'<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 …
```

fix(v2): pass options to remark-admonitions

---

website/package.json
website/src/plugins/remark-npm2yarn.js

Docusaurus' previous NPM-Yarn code tab generation was very basic and missed many conversions. I extracted some of the logic into a new npm package (`npm-to-yarn`) and made the code more robust.
Yep
_(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)_
~~When serving on localhost, NPM to Yarn code tab generation works in almost all cases (though for some reason, it seems to fail, as did the last implementation, on one-line codeblocks? I think it's a problem with the Remark plugin)~~
Actually, the problems I observed previously aren't there any more. Conversions seem to be working perfectly
(If this PR adds or changes functionality, please take some time to update the …

polish(v2): use npm-to-yarn for the npm2yarn remark plugin

---

packages/docusaurus/src/commands/build.ts

Side-effect from https://github.com/facebook/docusaurus/pull/2443
We do not need to force terminate building if the `--bundle-analyzer` flag is passed.
Yes
`yarn build --bundle-analyzer`

fix(v2): do not force terminate building when bundle analyzer is on

---

packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/themes/__tests__/alias.test.ts
packages/docusaurus/src/server/themes/__tests__/index.ts
packages/docusaurus/src/server/themes/alias.ts
packages/docusaurus/src/server/themes/index.ts

Provide an alias for theme components so that they can be semi-swizzled. Meaning you swizzle a component but only to wrap things around it, possibly to call new lifecycle logic or have components above/below it.
For example, I can now do this
```jsx
import DocItemOriginal from '@theme-original/DocItem';
function DocItem(props) {
return (
<div>
<p>Wrapper</p>
<DocItemOriginal {...props} />
<p>Wrapper</p>
</div>
);
}
export default DocItem;
```
and get this
This is partially inspired by [VuePress](https://vuepress.vuejs.org/theme/inheritance.html#override-components) (although Endi and I already had this idea long ago when we were building themes). [Libra docs](https://developer.libra.com) is moving to v2 and wants this level of customization.
This …

feat(v2): add @theme-original alias to give access to pre-swizzled components

---

packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-blog/src/index.ts

Currently Lodash in this repository is quite freely used without much care of it's footprint on the bundles/packages sizes. This is the first PR in a series which aims to improve this aspect.
This PR replace `@docusaurus/plugin-content-blog` Lodash import with single method package `lodash.kebabcase` because only this method was used from the whole package across all files.
I would like to improve other packages but before I can do that I need an answer in which way you would like me to handle packages that are using multiple Lodash methods. There are two ways:
- instead of `lodash` include few, single method packages (like in example above)
- maintain `lodash` in the package but use cherry picking for the packages
> e.g.: `import flatten from 'lodash/flatten';`
Personally I would also …

refactor(v2): use single method package instead of whole Lodash package in blog plugin

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css
website/docs/markdown-features.mdx
website/docs/migrating-from-v1-to-v2.md

Add filename in CodeBlock which is mentioned in #2271 
If you write below markdown like below, it will create filename in CodeBlock.
> 
> \`\`\`js:src/pages/hello.js {2}
> console.log('hogehoge');
> \`\`\`
> 
**[dark mode]**
**[white mode]**
I like this markdown syntax to create "filename", but it depends on docusaurus team.
> 
> \`\`\`js:src/pages/hello.js {2}
> console.log('hogehoge');
> \`\`\`
> 
Yes!
Add CodeBlock with this syntax in your doc.
> \`\`\`js:src/pages/hello.js {2}
> console.log('hogehoge');
> \`\`\`
>

feat(v2): add filename in CodeBlock

---

website/docs/markdown-features.mdx

As discussed in #2249, we need to add the mdx plugin docs.
yes
1. `yarn start`
2. go to `docs/next/markdown-features#configuring-plugins`
#2249 
cc @yangshun

docs(v2): add setup of mdx plugins

---

packages/docusaurus/src/server/themes/alias.ts

I want to write swizzled theme components in TypeScript. (I'm not sure whether the maintainers of docusaurus want to eventually convert `@docusaurus/theme-classic` components into typescript.)
The infrastructure for typescript is already mostly setup in #2221 and #2310. This diff just adds support for recognizing typescript files for theme component.
Yes
1. Without this diff, change `packages/docusaurus-theme-classic/src/theme/Footer/index.js`'s extension to tsx. Try `yarn start`. It will fail by saying `@theme/Footer` cannot be resolved.
2. After I made these changes. Stop dev server and run `yarn start` again. Now `@theme/Footer` is correctly resolved and the page will load successfully. …

feat(v2): add TypeScript support for theme components

---

website/docs/blog.md
website/docs/cli.md
website/docs/configuration.md
website/docs/deployment.md
website/docs/docusaurus.config.js.md
website/docs/lifecycle-apis.md
website/docs/markdown-features.mdx
website/docs/migrating-from-v1-to-v2.md
website/docs/presets.md
website/docs/search.md
website/docs/sidebar.md
website/docs/static-assets.md
website/docs/styling-layout.md
website/docs/theme-classic.md
website/docs/using-plugins.md
website/docs/using-themes.md
website/versioned_docs/version-2.0.0-alpha.40/lifecycle-apis.md
website/versioned_docs/version-2.0.0-alpha.43/lifecycle-apis.md
website/versioned_docs/version-2.0.0-alpha.48/lifecycle-apis.md

Use the codeblock title syntax which is now a first-class feature
Yes
Netlify preview

docs(v2): use codeblock title syntax instead of comments

---

packages/docusaurus-preset-classic/package.json
packages/docusaurus-theme-classic/package.json
yarn.lock

Refers to #2403
Resolve error of "Element “div” not allowed as child of element “h5” in this context. (Suppressing further errors from this subtree.)"
See https://github.com/elviswolcott/remark-admonitions/pull/22 
Yes
Preview.
Make sure that for icons in headings of admonitions instead of `div` element used `span`. 

chore(v2): upgrade remark-admonitions for a11y fixes

---

website/docs/cli.md

It's a draft for resolve #2399, so feel free to edits it.
Yes
Preview.

docs(v2): mark that in dev server some features may not work

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.js

I noticed that OG title it is wrong for the doc page:
Yes
Preview - https://deploy-preview-2475--docusaurus-2.netlify.com/docs/theme-classic/

fix(v2): make correct Open Graph title for doc page

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js

Refers to #2403
This ensures that this scrollable region has keyboard access.
Yes
Preview.
1. In the web browser go to https://deploy-preview-2476--docusaurus-2.netlify.com/docs/markdown-features/
2. Press the `tab` button to jump to code block.

fix(v2): improve code block scroll accessibility

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/webpack/base.ts
packages/docusaurus/src/webpack/client.ts
packages/docusaurus/src/webpack/server.ts
website/docs/cli.md

Resolve https://docusaurus.canny.io/admin/board/feature-requests/p/minifying-option
Yes
Run `yarn build --no-minify` and make sure any JS bundle is not minified.

feat(v2): add ability to create unminimized bundles

---

packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css
website/src/components/BrowserWindow/index.js
website/src/components/BrowserWindow/styles.module.css
website/src/pages/index.js
website/src/pages/styles.module.css

Refers to #2403 
Another part of the changes to improve a11y:
- Use main element and h2 on main page
- Refactor browser window (replace input with div)
- Use div instead of pre for code blocks 
Yes
Preview.

fix(v2): various improvements for accessibility

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js

When sticky navbar is on, we don’t need to display the sidebar logo, which is shown when navbar hides when scrolling.
Yes
Preview.

fix(v2): do not render sidebar logo if used sticky navbar

---

packages/docusaurus-theme-classic/src/theme/Layout/index.js

The old `<meta http-equiv="X-UA-Compatible" content="ie=edge">` is not necessary anymore nowadays...
See https://stackoverflow.com/questions/6771258/what-does-meta-http-equiv-x-ua-compatible-content-ie-edge-do/6771584#6771584
Yes
Preview.

refactor(v2): remove unnecessary X-UA-Compatible meta tag

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js
website/docs/theme-classic.md
website/docusaurus.config.js
website/src/css/custom.css
website/src/pages/index.js

Fixes #2269
Allow specifying a nav dropdown from the theme config. This implementation is far from perfect and I'm kinda rushing it out for the release.
- Only allows one layer of dropdown, which is acceptable for now since Infima only supports that
- Doesn't allow collapsing in the mobile sidebar. I wanna try to reuse the menu components but it's not that easy
Yes
Preview

feat(v2): nav dropdown

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js
website/docusaurus.config.js
website/src/css/custom.css

- Fix warnings about props
- Add missed `li` element in dropdown
- Make non-clickable parent nav link of dropdown menu
- Fix highlight "Docs" menu item
Yes
Preview.

fix(v2): fix HTML issues nav dropdown and highlight docs item

---

jest.config.js
packages/docusaurus-plugin-content-docs/src/sidebars.ts
packages/docusaurus/package.json
packages/docusaurus/src/index.ts
yarn.lock

We already have Lodash installed, so we can use `flatMap` from this lib.
Yes
Preview.

fix(v2): use lodash instead of array-map-polyfill

---

packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts

Fix #2493
In blog-only mode, we will have URL components like this:
```js
[/* site baseUrl */ '/', /* blog routeRootUrl */ '/',  '/2020/01/01/foo-bar']
```
, which will be normalized to `//2020/01/01/foo-bar` by the old algorithm.
My fix adds a final pass that collapses all forward slashes at the beginning of the final string into 1 slash, so `//2020/01/01/foo-bar` will become `/2020/01/01/foo-bar`
Yes
- A test case has been added to test the new normalizing behavior for a URL of blog post in blog-only mode
- Repeat the repro plan in #2493 with this change, the problem no longer exists.
Now blog-only mode has …

fix(v2): unbreak blog-only mode routing by deplicating starting forward slashes

---

packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/deploy.ts

From Discord chat:
```
ted: Has anyone been able to successfully deploy with alpha.49?
ted: When I run the deploy command with alpha.49, it only builds
```
In PR #2443, we did not take into account that the building process is running during deploying, where the according command is already forced to terminate.
Yes
```
yarn deploy
```

fix(v2): do not force terminate building when running deploy command

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.js
website/docs/markdown-features.mdx
website/docs/migrating-from-v1-to-v2.md
website/docs/versioning.md

The Markdown Features page is getting really long and disorganized. It's time to categorize them better and reorganize the flow.
Yes

docs(v2): reorganize markdown features page

---

packages/docusaurus-theme-classic/src/theme/AnnouncementBar/index.js
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css
website/docusaurus.config.js

- Use local storage instead of session storage (because it is somewhat annoying to close the banner several times)
- Improve the view of small mobiles
- Make the background for the banner a little darker so it's better displayed in light mode.
Yes
Preview.

refactor(v2): improve announcement bar

---

website/docusaurus.config.js

Make it easier to discover the `master` version of docs.
Yes

docs(v2): add link to master docs

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js

Refers to  #2456 and #2480
I hope this is the last time we duplicate the changes in the live code block!
Yes
Preview.

fix(v2): synchronize code block components changes

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css

Fixes #2523. #2502 used theme-aware button color for the copy button but not everyone is using theme-aware code blocks.
The fix here is to hardcode the color for the code block regardless of theme.
Yes

fix(v2): make code block nicer again

---

packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/server/client-modules/index.ts
packages/docusaurus/src/server/html-tags/index.ts
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/plugins/init.ts
packages/docusaurus/src/server/presets/index.ts
packages/docusaurus/src/server/routes.ts

This is a reworked version of #2520 PR, same motivation like in previous PRs.
This is the initial step in getting rid of main `lodash` package in favour of single method ones in core v2 Docusaurus package. In this PR `_.assign`, `_.compact`, `_.flatten` and `_.isArray` methods has been replaced with their native counterparts.
After applying those changes only `has`, `isPlainObject` and `isString` lodash packages are needed in the core. 
Yes
Same test results before and after code refactor.
* #2460
* #2519 
* #2520

refactor(v2): replace few Lodash methods with native counterparts

---

packages/docusaurus-plugin-sitemap/src/index.ts

Fix #2516.
Without a synchronous write, the callback may never be invoked because it's killed by `process.exit` introduced in #2443.
Unbreak sitemap generation.
Yes
Since I wasn't able to produce a repro for the docusaurus repo but I was able to repro it on my repo (see #2516), so I made the test against my repo.
1. Run `yarn` to compile all files.
1. Copy generated `packages/docusaurus-plugin-sitemap/lib/index.js` into correct place in https://github.com/SamChou19815/website 's `node_modules`
1. Run `yarn workspace blog build` in https://github.com/SamChou19815/website, now the sitemap is correctly generated.
(If …

fix(v2): Use `writeFileSync` to write generated sitemap.xml to avoid early termination

---

packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-blog/src/types.ts
packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.js
website/docs/using-plugins.md
yarn.lock

Resolve #2467
As described in #2467, it's very common to see on blogs the estimated reading time of posts, so the purpose of this change is to add the estimated reading time of blog posts in docusaurus.
Yes
Go to the blog page and the estimated reading time will be there:
You can also set the prop `showReadingTime` to false on  the blog section of `docusaurus.config.js` and the reading time will not be shown anymore
- In order to calculate it, I used a library called `reading-time` which is used by [a similar plugin on gatsby](https://www.gatsbyjs.org/packages/gatsby-remark-reading-time/) to calculate the estimated reading time, but I think it can be calculated without a library :thinking:

feat(v2): add blog post estimated reading time

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-classic/src/theme/MDXComponents/styles.module.css
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css

The rounded corners in the code blocks must be set to non-scrollable containers of code blocks, otherwise they will not be visible when scrolling.
Yes
Preview.

fix(v2): add rounded corners in code blocks properly

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css

If there is only one line in the code block, the copy button is too low positioned. I suggest a little lift it.
In addition, I removed the redundant code left after #2533.
@yangshun open-ended question for discussion: do we really want to leave the background opacity? Actually, with long lines of code, this button becomes not so noticeable.
Yes
| ![image](https://user-images.githubusercontent.com/4408379/78470930-da708280-7735-11ea-848e-00dda5fb0ebc.png) | ![image](https://user-images.githubusercontent.com/4408379/78470932-e0666380-7735-11ea-9adc-80b1bae89e1e.png) |

refactor(v2): make better code blocks

---

package.json
packages/docusaurus-utils/package.json
packages/docusaurus-utils/src/index.ts

This is probably the last PR in Lodash series from me. This PR replaces `lodash` package in `docusaurus-utils` which also allows to remove `@types/lodash` from the workspace `package.json`.
There may by one more PR which cleans things up, but I need to fix my `yarn build` first.
`lodash` package cannot be remove from workspace `package.json` because V1 is still using it.
Yes
Same test results before and after code refactor.
#2460
#2519
#2520
#2529
#2535

refactor(v2): replace Lodash with single methods packages in utils

---

.prettierrc
packages/docusaurus-init/templates/facebook/.prettierrc

Update config Prettier so that it is consistent with the latest version of ESLint config Airbnb , where you now **always** need to write parentheses :cry: 
https://github.com/airbnb/javascript#arrows--one-arg-parens
Yes
N/A.

chore(v2): update Prettier config

---

website/docs/using-themes.md

Trying to be more explicit about swizzling process, particularly about to swizzle all components
`yarn start`

docs(v2): command for swizzling all components

---

package.json
packages/docusaurus-plugin-ideal-image/package.json
packages/docusaurus-plugin-ideal-image/src/index.ts
packages/lqip-loader/README.md
packages/lqip-loader/package.json
packages/lqip-loader/src/index.js
packages/lqip-loader/src/lqip.js
packages/lqip-loader/src/utils.js
yarn.lock

During discussion with @yangshun about my problems with Node 13 I was able to find that outdated `sharp` package in one of core dependencies is the root of my issues.
Fortunately it was [`@endiliey/lqip-loader`](https://github.com/endiliey/lqip-loader) package which is the fork of original `lqip-loader` especially created for the Docusaurus anyway. @yangshun asked me if I want to handle the import of this package into Docusaurus monorepo and this PR is the result of that.
It is just a init import, no tests (Endiliey package used old version of `mocha`), no TS, with the consent of @yangshun.
This PR also fixes:
* V2 build on Node 13 (fixed via `sharp` bump in `docusaurus-plugin-ideal-image` and switch to peer dependencies in `@docusaurus/lqip-loader`) - …

refactor(v2): import lqip-loader to monorepo, fix build on Node 13, fix lint-staged

---

lerna.json

Not very important, but noticed this deprecated attribute in lerna config that can be removed
https://github.com/lerna/lerna#legacy-fields

misc(v2): remove deprecated/useless lerna field

---

website/docs/team.md

As discussed in #2546, would it be nice have the team profiles, so this pr adds the images of the members.
I was thinking if isn't better create a component to render this, the visual that is applied for each member is equal, we can have a `.json` with the members info, like, the github, twitter, and a brief description about the person.
Yes
`yarn start` go to `/docs/next/team`

doc(v2): Add team photos

---

admin/extending-remarkable.md
docs/api-site-config.md
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/src/commands/deploy.ts
website-1.x/versioned_docs/version-1.10.x/api-site-config.md
website-1.x/versioned_docs/version-1.11.x/api-site-config.md
website-1.x/versioned_docs/version-1.13.0/api-site-config.md
website-1.x/versioned_docs/version-1.14.4/api-site-config.md
website-1.x/versioned_docs/version-1.9.x/api-site-config.md
website/docs/lifecycle-apis.md
website/versioned_docs/version-2.0.0-alpha.40/lifecycle-apis.md
website/versioned_docs/version-2.0.0-alpha.43/lifecycle-apis.md
website/versioned_docs/version-2.0.0-alpha.48/lifecycle-apis.md
website/versioned_docs/version-2.0.0-alpha.50/lifecycle-apis.md

The CLI had a few problems with grammar mistakes, some inconsistancies, and just some other stuff in general that I made better based on my trials of d2.  
I have contributed before, yet I should have read them.
Also I ran prettier on the docs (`yarn prettier-docs`) because my IDE (WebStorm) was complaining about it.  
I tried out the new CLI and I think its better.
None.
By opening this PR I understand and confirm that the work submitted is my own and have read and agreed to the Facebook contributor license agreement.

refactor(v2): enhance CLI experience

---

website/docs/blog.md

I copied and pasted that block for my project, and noticed that it was unused now because it has `author_url` (as can be seen earlier in the example) present.
Yes
I have verified that `authorURL` is no longer valid metadata
None.

doc(v2): remove legacy blog metadata

---

packages/docusaurus-1.x/lib/core/DocsSidebar.js
packages/lqip-loader/src/__tests__/index.test.ts
packages/lqip-loader/src/utils.js
website/docs/team.md

This small PR fixes few very minor lint issues/warnings and updates the `lqip-loader` utility method description to match the current state of the code.
Yes.
N/A
* #2561

chore(v2): fix lint, tweak lqip-loader utils comment

---

website/docs/deployment.md
website/docs/markdown-features.mdx

It seems to me that docs should not use constructs that contain "you should", this is somehow not entirely polite for our users.
Yes
Only for `master`-docs.

docs(v2): be more polite

---

website/docs/using-plugins.md
website/versioned_docs/version-2.0.0-alpha.50/using-plugins.md

The plugin config had a syntax error
Yes
View the  https://v2.docusaurus.io/docs/using-plugins/#docusaurusplugin-sitemap page

docs(v2): fix syntax error for plugin config

---

website/docs/using-plugins.md
website/versioned_docs/version-2.0.0-alpha.50/using-plugins.md

In reference to https://github.com/facebook/docusaurus/issues/2571
I attempted to use the `@docusaurus/plugin-ideal-image` plugin, and found it wasn't compressing images in a development enviroment. I needed to do a production build for it to compress images, so I wanted to add a note to the docs so other developers don't get confused like me.
yes
Check for spelling and grammar.

docs(v2): mention that `plugin-ideal-image` only perform compression on a production build

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.js
packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css

Resolve #2548
This PR solves the horizontal scroll issue not only for tablets in landscape orientation, but in general for all screens.
The bottom line is that we limit the width of the container with docs content on screens from 997px to 1320 px (this is the maximum width when scrolling appears), so this change does not affect large screens.
Yes
I tested on different generations of the iPad (6th, 7th) using BrowserStack and also some tablets on Android.  Basically, just go to the docs page with "large" content (https://v2.docusaurus.io/docs/next/markdown-features/) and through devtools manually change the page size - horizontal scrolling should not be.
Initial issue:
Before:
After: …

fix(v2): remove horizontal scroll on docs page

---

packages/docusaurus/src/client/exports/__tests__/isInternalUrl.ts
packages/docusaurus/src/client/exports/isInternalUrl.js

Resolve #2568
Yes
Use the similar elements as the item link in navbar and footer.
```js
{
label: 'Mailto link',
href: 'mailto:foo@bar.com',
position: 'right',
},
```
```js
{
label: 'Telephone link',
href: 'tel:+1234567890',
position: 'right',
},
```

fix(v2): treat mailto and tel links properly

---

packages/docusaurus/src/client/exports/Link.js

Resolve #2552
Anchor links that refer to sections in the current file should not be processed by the router, because otherwise the current URL is added to them (_"/docs/docs/#doc" instead of just "#doc"_), and this breaks them (in case of non-ASCII characters).
Yes
In any MD document, define new heading using non-ASCII characters. And then try to refer to
this section through a new link.
> The example below uses Russian characters, for example, but you can use Persian, as indicated in  #2552
```md
...
...
[Тест](#тест)
```

fix(v2): do not process anchor links by router

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus/src/client/exports/Link.js
website/docs/docusaurus-core.md

As mentioned in https://github.com/facebook/docusaurus/pull/2580#issuecomment-612387653, this will allow clean things up with nav links, in other words, it’s now clearer where we need to use the functionality of nav links, in their _original purpose_*.
> _\*_ A special version of the that will add styling attributes to the rendered element when it matches the current URL.
This basically removes unnecessary DOM attrs related with highlighting (via CSS) the current link (for our needs, this is only necessary for navbar and doc sidebar).
This is potentially BC change, although it seems unlikely that anyone used this functionality, especially since it would not work by default except in the navbar and doc sidebar (because the according CSS styles for the active menu item are defined only for …

refactor(v2): use nav link component only where needed

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.js

In accordance with recommendations for improving website performance, we should avoid a large number of nested elements. This tiny change removes the extra wrapper (util  `padding-vert--lg` class is now added to another container).
Yes
Preview.

refactor(v2): remove redundant container on docs page

---

packages/docusaurus/src/commands/deploy.ts

Found this issue while trying to make a site, so I fixed it
Yes
I tested it by creating a docusaurus site and I verified that the correct URLs are logged.  
This was in #2556 but @yangshun reverted it

fix(v2): properly link top-level github pages sites in deploy command

---

website/docs/markdown-features.mdx

In order to stay more consistent, the custom title could also be removed in its entirely. The next section is just about customizing admonition titles in general.

docs(v2): fix 1st custom admonition title example

---

packages/docusaurus-theme-classic/src/theme/BlogListPage/index.js
packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.js
packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.js
packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.js

I think it's better to unify margin top on the blog pages, that it was the same as on other pages (docs, pages)
Yes
Preview.

refactor(v2): make margin top on blog pages as on other pages

---

website/docs/installation.md

`package.json` was duplicated within the example file structure (line 50 & 60). I've removed the one on 50 so all directories are together and left the second.

docs(v2): remove duplicated package.json in installation directory structure

---

packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css

On a recently added project in Showcase I noticed that the announcement bar close icon is hard to see when using a dark color, see an example below
Yes
https://graphql-inspector.com/docs/index
Before:
After:

fix(v2): inherit color for announcement bar close icon

---

packages/docusaurus-theme-classic/src/index.js
website/docs/theme-classic.md

Resolve #2565 and corresponding request on Canny (https://docusaurus.canny.io/admin/board/feature-requests/p/default-to-dark-theme) 
Yes
1. Make sure that there is no saved proffered theme in local storage (`theme` key) and add the `themeConfig.forceDarkMode=true` option in the config file.
1. Now when you open the website, dark mode will be turned on (light mode can be selected via navbar toggle)

feat(v2): add ability set dark mode by default

---

packages/docusaurus-plugin-sitemap/src/__tests__/createSitemap.test.ts
packages/docusaurus-plugin-sitemap/src/createSitemap.ts

Fixes #2605
Yes
I added a test to Jest to make sure this works.
In addition, you can also look at the sitemap on v2.docusaurus.io vs the deploy preview.

fix(v2): don't include 404 page in sitemaps

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js

Fix #2623
Yes
Commented out the `themeConfig.links` field in `docusaurus.config.js` and see that the hamburger doesn't appear.

fix(v2): hide mobile navbar hamburger when there are no links

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js

Currently tabbing on hidden (collapsed) doc sidebar items is allowed, which makes it difficult to navigate from the keyboard (see video below).
Yes
Before:
After:

fix(v2): disable tab focus on collapsed doc sidebar items

---

packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css

Currently the border right of doc sidebar is not stretch to the full height of the column, this PR fixes this.
Yes
Preview.

fix(v2): make border right of doc sidebar equals doc page

---

packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css

It really came as a result of tiny refactoring #2595. 
Although I would still notice this bug before the new release, so no reason for concern :ok_hand:.
Yes
| ![image](https://user-images.githubusercontent.com/4408379/79703823-c80a5300-82b6-11ea-9037-8f3d454ce62a.png) | ![image](https://user-images.githubusercontent.com/4408379/79703830-d5bfd880-82b6-11ea-9d5c-d5ee123425d5.png) |

fix(v2): hide doc sidebar on mobiles

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/src/commands/start.ts
website/docs/cli.md

I've been working with a project that likes to have repos contain VS Code devcontainers so that you can simply open the repo in VS code, load up a configured Docker container and away you go. I have this working 99 % with our Docusaurus 2 repos but live reloading does not work use the `fsevents` and `inotify` methods used to watch for file changes in this case.  [Webpack Dev Server provides a polling alternative](https://webpack.js.org/configuration/watch/#watchoptionspoll) option for this and it is noted that this is recommended for such environments. 
Yes
-   Run this repository following the standard instruction set [here](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#installation).
-   Build the website with standard `yarn start` to check works with no flag …

feat(v2): add CLI option for polling

---

packages/docusaurus-init/templates/bootstrap/docusaurus.config.js
packages/docusaurus-init/templates/classic/docusaurus.config.js
packages/docusaurus-init/templates/facebook/docusaurus.config.js
website/docusaurus.config.js

It's now a legal requirement for Facebook's OSS sites to link to our [Privacy Policy](https://opensource.facebook.com/legal/privacy/) and [Terms of Use](https://opensource.facebook.com/legal/terms/).
Hence adding it to our website footer and our template. Will send follow-up PR to update V1 website.
P.S. Thanks @lex111 for allowing HTML for copyright field, came in really handy here.
Yes

chore(v2): add Privacy Policy and Terms of Use links to footer

---

packages/docusaurus-theme-classic/src/theme/hooks/useHideableNavbar.js
packages/docusaurus-theme-classic/src/theme/hooks/useScrollPosition.js

We definitely need a separate hook for scroll position, because in the future it will be used repeatedly.
FYI I'm trying to solve one bug right now, and seems needs a new scroll event there.
Yes
Preview.

refactor(v2): extract scroll position detection into separate hook

---

packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/sidebars/sidebars-category.js
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/sidebars/sidebars-collapsed-first-level.json
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/sidebars/sidebars-collapsed.json
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/sidebars.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/version.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/sidebars.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
website/docs/docs.md

This PR adds the ability to toggle sidebar categories open by default.
- update sidebar category to take collapsed prop 
- add extra sidebars collapsed test
- only mutate `item.collapsed` if necessary
- update docs for SidebarItemCategory
Fixes #2354 
Yes.
I wrote extensive notes on the issue: https://github.com/facebook/docusaurus/issues/2354
Here's how I tested my changes:
1. Built project: `yarn build`
2. Published to `verdaccio` locally: `yarn lerna publish --registry http://localhost:4873 --no-git-tag-version` 
3. Created a new website: 
```shell
npm set registry http://localhost:4873/
npm i -g @docusaurus/init
/Users/jprevite/.nvm/versions/node/v10.15.1/lib/node_modules/@docusaurus/init/bin/index.js init test-joe
```
4. Modified the `sidebars.js` file:
```js …
```

feat(v2): add option to toggle sidebar category open by default

---

packages/docusaurus-module-type-aliases/package.json
packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus/package.json
packages/docusaurus/src/client/types.d.ts

In #2578, I migrated all `@docusaurus/core` to TypeScript. During the migration, I have to declare modules to make TypeScript understand docusaurus-specific webpack aliases like `@generated` `@theme`. I put those declarations in a `types.d.ts` file inside `@docusaurus/core`.
In order to provide better TypeScript support for end-users, these aliases information also has to be available externally. TypeScript won't scan all `node_modules` to find this `types.d.ts`. Therefore, we need a way to tell to TypeScript to find the module declaration file.
My solution is to use the [`<reference types=... />` triple-slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-). I moved the module declaration to a new package …

refactor(v2): Expose docusaurus module type aliases to end-users

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js

Resolve #2647
Yes
_Test on v2 website_
1. In config file add a new new child item of nav that belongs to the same sidebar, for example:
```js
navbar: {
// ...
links: [
{
label: 'Docs',
items: [
{
label: 'First item',
to: 'docs/design-principles',
},
{
label: 'Second item',
to: 'docs/introduction',
},
```
1. Run dev server
1. Click alternately on the first and second items - the sidebar should close.

fix(v2): hide sidebar after click on child item

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js

After approving of #2625 we have a not very good side effect - when you click on any sidebar item, it gets focus and becomes visible accordingly. I think it is best to remove focus after click on sidebar item. Moreover, this does not affect a11y.
Yes
Preview.

refactor(v2): lose focus of active sidebar item after click on it

---

packages/docusaurus-1.x/package.json
packages/docusaurus-init-1.x/package.json
packages/docusaurus-init/package.json
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus/package.json
yarn.lock

Resolve #2648
Yes
Install Node.js v14.0.0 and run the `yarn start` command - there should be no any warnings in the console output.

chore: upgrade shelljs to 0.8.4

---

packages/docusaurus/src/client/exports/BrowserOnly.tsx
website/docs/docusaurus-core.md

Resolve #2573
Yes
1. Put any target content in `BrowserOnly` component (eg. on `index` page at `src/pages/index.js`):
```
<BrowserOnly fallback="Fallback content">
{() => (
<p>Target content</p>
)}
</BrowserOnly>
```
1. Build the website running `yarn build` command. Then find substring of "Fallback content" in generated file in which the `BrowserOnly` component was used (eg. `build/index.html`)
1. Serve website built via the npm [serve](https://www.npmjs.com/package/serve) package (`serve build`) to make sure that target content is displayed in the web browser.

feat(v2): add fallback to BrowserOnly component

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-live-codeblock/package.json
yarn.lock

Resolve #2655
I wrote an email to author of prism-react-renderer so that he could accept bunch a PRs and after a few hours he updated the lib, very fast! 
Yes
After that, Python decorator highlighting works fine (although this is not supported by all themes), and then  Palenight theme now has diff syntax support.

chore(v2): upgrade prism-react-renderer to latest version

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
yarn.lock

Upgrade to `infima@0.2.0-alpha.8` which brings about some typography changes and navbar caret.
Yes
See Netlify.

chore(v2): upgrade Infima

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js
website/docusaurus.config.js

After that, you can open dropdown (and navigate it) using the keyboard, this is good for accessibility.
In addition to that, in current PR, for consistency and easier code understanding, I changed the naming of some args and moved the custom CSS class to the end of the class list. This is a simple refactoring.
Yes
Preview.

fix(v2): add a11y support for dropdown

---

CONTRIBUTING.md

When testing my changes locally, I wasn't aware of the document Local Third Party Project Testing. I think we should tell people about it in the `CONTRIBUTING` document. 
Yes.
N/A - it's a markdown file. 
N/A

docs: update test plan in contributing

---

packages/docusaurus-module-type-aliases/src/index.d.ts

With these additions, all typescript red squiggly lines will be gone once user install `@docusaurus/module-type-aliases` and create a `types.d.ts` that references `@docusaurus/module-type-aliases`.
Yes
1. Add `types.d.ts` with content `/// <reference types="@docusaurus/module-type-aliases" />` to the root of `packages/docusaurus-theme-classic`.
2. Change some components' extension to tsx
3. Imports that contains `@docusaurus/...`, `styles.module.css` and `styles.css` no longer has red squiggly lines.

fix(v2): Add all webpack module aliases to type declaration file

---

packages/docusaurus-theme-classic/src/index.js

fix(v2): add default value for options in theme classic

---

packages/docusaurus-plugin-content-blog/src/index.ts

Fix dead link element of feed when [Blog-only mode](https://v2.docusaurus.io/docs/blog#blog-only-mode) is enabled.
yes
open `view-source:http://localhost:3000/`
nothing

fix(v2): add routeBasePath to feed link

---

packages/docusaurus-utils/src/index.ts

This request came from Discord chat, since import declarations might work without a trailing semicolon, you need to consider this when making excerpt.
Yes
The same as in Test plan for #2380, but in addition it will work even if a semicolon is not specified.
- Based on #2380

refactor(v2): make semicolon optional in imports for excerpt

---

packages/docusaurus/package.json
yarn.lock

`webpack-dev-server` fixed their dependency on `yargs-parser`, which had a vulnerability.  This PR bumps Docusaurus' webpack-dev-server dependency to 3.11.0, so it pulls in that vulnerability patch. https://github.com/webpack/webpack-dev-server/pull/2566
Yes
I verified `yarn test` and `yarn start` still work as expected.
https://github.com/webpack/webpack-dev-server/pull/2566

chore(v2): bump webpack-dev-server to 3.11.0 to address yargs vulnerability

---

website/docs/resources.md

Adds a link to a new community plugin that introduces support for environment variables managed in `.env` files.
For my particular use case of Docusaurus, I deploy several different versions of our site in various environments as well as some A/B testing. I make use of `.env` files in other React apps and wanted to Docusaurus site to behave similarly. 
Yes!
The steps to install and work with the plugin can be found in the linked Github. There are no changes to the core Docusaurus source code.

docs(v2): add new community plugin for dotenv support

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.js
packages/docusaurus-theme-classic/src/theme/Layout/index.js

Currently Docusaurus does not support canonical URLs. From a search engine standpoint, a canonical URL is an important piece of information and can help direct them to the correct content. 
Yes
* Visit any static page or doc page
* View source, search for `<link rel="canonical" href="<URL of the page you're currently viewing>" />`
This PR is a good first step to further implement https://github.com/facebook/docusaurus/issues/2603, as it introduces a good default value.

feat(v2): add canonical URL to <head>

---

packages/docusaurus-theme-classic/src/theme/Footer/index.js
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus/src/client/exports/useBaseUrl.ts
website/docs/theme-classic.md

Fixes #2745.
Yes
Add the following config to `themeConfig.navbar.links`:
```
{
href: 'https://www.facebook.com',
prependBaseUrlToHref: true,
label: 'FB',
position: 'left',
},
```
See that the baseUrl is added.

feat(v2): allow prepending of baseUrl to href in navbar and footer

---

packages/docusaurus-init/templates/bootstrap/src/pages/index.js
packages/docusaurus-init/templates/classic/src/pages/index.js
packages/docusaurus-init/templates/facebook/src/pages/index.js

If features is an empty array, a "0" is displayed instead of the feature list : 
This is because :
```
const features = []
features && features.length && 'anything' // will return "0"
```
Yes
I don't think it really needs a test plan, but feel free to correct me if you really want this tested

fix(v2): fix index page features.length when 0

---

packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/theme/hooks/useVersioning.ts
packages/docusaurus-theme-search-algolia/package.json
packages/docusaurus-theme-search-algolia/src/index.js
packages/docusaurus-theme-search-algolia/src/pages/search/index.js
packages/docusaurus-theme-search-algolia/src/pages/search/styles.module.css
packages/docusaurus-theme-search-algolia/src/templates/opensearch.js
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/start.ts
yarn.lock

I am pleased to present the fully fledged search page - awesomeness killer-feature!
As far as I know, none of the major static site generators that use Algolia have a "real" search page. But why?  It is so convenient especially  for docs websites, so I tried to solve that shortfall.
So now users will be able to see _all_ the search results for a specific query, and not just those five result items that were shown in navbar.
In addition, the search page supports selecting of a specific version to search, which may be useful to someone.
Last but not least, it is [OpenSearch support (aka Tab To Search)](https://www.chromium.org/tab-to-search)..yeah we can search by own documentation just by pressing the Tab button in your brower after that!
See all use cases in the screenshots below.
Yes …

feat(v2): add search page 🔎

---

packages/docusaurus-theme-classic/src/theme/Tabs/styles.module.css

Resolve #2738.
Yes
| ![image](https://user-images.githubusercontent.com/4408379/82137803-dbf89480-9823-11ea-8f9c-0e063daaa0a2.png) | ![image](https://user-images.githubusercontent.com/4408379/82137841-1feb9980-9824-11ea-97d8-e196e1769dce.png) |

fix(v2): remove extra top margin of tab item

---

packages/docusaurus-theme-classic/src/theme/Heading/index.js
packages/docusaurus-theme-classic/src/theme/Heading/styles.css

After changing the size of the header font in Infima, the anchor link of heading overlaps to it (and in the case of lower-level headings we can see that hash is too far from the heading).
Since hash link size is the same as its heading, obviously we need to calculate its own position for each heading. This is pretty time consuming using pure CSS. So I think a quick and easy fix for this behavior is to place the hash link on the right side of the headings (see test plan).
Yes
Before (currently improper behavior):
After

fix(v2): move anchor link to right of heading

---

packages/lqip-loader/src/index.js

Currently `url-loader` and `file-loader` have the option `esModule` is `true` by default. So `@docusaurus/lqip-loader` will always throw an exception unless you explicitly set `esModule` to `false`.
Yes
Use `@docusaurus/lqip-loader` alone or with `url-loader` or `file-loader` according to [README.md](https://github.com/facebook/docusaurus/blob/v2.0.0-alpha.54/packages/lqip-loader/README.md).
Nothing.

fix(v2): add support esModule to lqip-loader

---

website/docs/docs.md
website/sidebars.js

Rename the docs sidebar label, for me sounds weird the route `docs/docs` in  docs introduction
Yes
go to /docs/docs

refactor(v2): change the label for docs introduction

---

packages/docusaurus-theme-search-algolia/src/pages/search/index.js
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

- Do not open the search page if a suggestion from navbar was selected
- Set auto focus on the input of search page (usually this is not a good practice, but in this case I think it is necessary)
- Pluralize search results count
Yes
Preview.

refactor(v2): improve UX of search page

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

In #2756, I defined options for Algolia's autocomplete, but I didn’t take into account that [docsearch does not set default values for rest params](https://github.com/algolia/docsearch/blob/3268a6b227f5e486b59115419cfbea2d17ae0959/src/lib/DocSearch.js#L40-L44) (custom and default options usually merge).
As a result, on mobiles there was a strange thing after closing the search input:
This is because the `hint` option duplicates the search input :man_shrugging: 
Yes
Try using the search on preview from your mobile.

fix(v2): avoid duplication search input in navbar

---

packages/docusaurus/package.json
packages/docusaurus/src/webpack/base.ts
website/docs/static-assets.md
yarn.lock

As a React-centric static site generator, we should definitely enable the import of SVG images into React components. 
Currently when trying to import SVG there will be an expected error:
> Module parse failed: Unexpected token (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
This PR also resolve #2726. Note: I don’t think we need to support the CRA format for SVG (`import {ReactComponent as SVG}`), because this can be done in custom plugin by user itself.
Importing images of other extensions (jpg, png etc) is a rather difficult task due to the using of docusaurus-plugin-ideal-image plugin, although it may not be necessary right now. …

feat(v2): allow import SVG images

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js

From Rocket Validator:
> Attribute “position” not allowed on element “a” at this point. Found 600 times on this site.
Example:
> "ist-item"><a target="_blank" rel="noopener noreferrer" href="https://github.com/facebook/docusaurus" class="menu__link header-github-link" **position="right"** aria-label="GitHub repository"></a></"
Result of regression from #2487.
Yes
Check a11y on preview website.
- Initial fix #1974

fix(v2): remove invalid attr from mobile nav links

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js

In #2652, I actually added a new prop to define the active menu item manually, so this class is now duplicated.
https://github.com/facebook/docusaurus/blob/00a8e9e3654e49c502d4e6e21b978e36b1419fe9/packages/docusaurus-theme-classic/src/theme/DocPage/index.js#L58
https://github.com/facebook/docusaurus/blob/00a8e9e3654e49c502d4e6e21b978e36b1419fe9/packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js#L86
Yes
Preview.

refactor(v2): remove extra active CSS class for menu item links

---

packages/docusaurus-theme-live-codeblock/src/theme/Playground/styles.module.css

Currently the headings of live code blocks have the same styling for both modes, which doesn't look very good.
For example, in light mode the playground header background should not be so dark:
Yes
Before:
After:
| Light   | Dark    |
| ![image](https://user-images.githubusercontent.com/4408379/82163278-c8483f00-98b2-11ea-93bf-c8afa5e15b99.png) | ![image](https://user-images.githubusercontent.com/4408379/82163292-df872c80-98b2-11ea-8f91-9a0e7e0a916b.png) |

refactor(v2): add support for dark mode to live code blocks

---

website/docs/blog.md
website/docs/cli.md
website/docs/configuration.md
website/docs/creating-pages.md
website/docs/deployment.md
website/docs/docs.md
website/docs/docusaurus-core.md
website/docs/docusaurus.config.js.md
website/docs/installation.md
website/docs/introduction.md
website/docs/lifecycle-apis.md
website/docs/markdown-features.mdx
website/docs/migrating-from-v1-to-v2.md
website/docs/presets.md
website/docs/static-assets.md
website/docs/styling-layout.md
website/docs/theme-classic.md
website/docs/using-plugins.md
website/docs/using-themes.md
website/versioned_docs/version-2.0.0-alpha.54/blog.md

Basically, the changes relate to style, formatting, removal of inconsistencies.
Yes
Preview.

docs(v2): various improvements

---

packages/docusaurus-plugin-content-docs/src/index.ts

- Resolve #2776 (bring back to previous algorithm with `map`)
- Add supports for nested routes with slashes (`doc1/doc2/`)
Preview.
See https://github.com/facebook/docusaurus/pull/2652

fix(v2): check for docs homepage correctly

---

website/docusaurus.config.js

Fixes this bug on website v2:
Yes
Preview.

fix(v2): do not highlight root docs path in navbar

---

packages/docusaurus/src/client/exports/Link.tsx

This changes the Link component to open external URLs in new tabs. This includes links in markdown in the form of `[label](url)`, and also explicit use of the `Link` component.
You can override this behavior by passing `target: '_self'` as a prop when using `Link`.
Docusaurus is already opinionated about doing this, for example the Navbar and
Footer do this already for external links. This is making it consistent across the entire site.
Yes
`cd website; yarn start;`
* In browser navigate to http://localhost:3000/docs/design-principles and click on "Minimal Surface Area" - Verify it opens in new tab. Do the same on other pages.
* Verify anchor links continue to use the same tab.
* Verify internal links continue to use the same tab.
* Edit docs/design-principles.md to use Link instead of …

feat(v2): open external links in new tab by default

---

packages/docusaurus/src/client/exports/Link.tsx
website/docs/docusaurus-core.md

For security reasons, it is recommended that we add the optional `rel="noopener noreferrer"` attribute for external links.
Beside this, external links in navbar/footer have the same behavior.
Yes
See #2780

refactor(v2): make external links more secure

---

website/docs/resources.md

I saw resources page but there was no section for Articles. As I recently published my article so I added this section which will help users as well as publishers of docusaurus.

docs(v2): add articles section to resources page

---

packages/docusaurus-plugin-content-docs/src/index.ts

Closes #2784.
In fact, doc sidebar had to be redefined only for reserved docs home page route (i.e. `_index`) so that sidebar will be shown for this kind of document (which is not supposed to be defined in any sidebar).
I had not considered that there could be multiple sidebars, which caused the bug described in #2784.
However, I have now realized that it was counterintuitive to display the sidebar on the reserved docs home page route, so this whole mess was due to my overengineering, which I want to fix in this PR.
Yes
See #2784

fix(v2): do not show sidebar on reserved docs home page

---

packages/docusaurus/src/webpack/utils.ts

Issue #2576 shows that docusaurus v2 doesn't work with Yarn v2 with pnp enabled.
This diff doesn't try to resolve the issue of the plugin system caused by the incompatibility: it can be solved by using the [pnpLoose mode](https://yarnpkg.com/features/pnp#pnp-loose-mode) for now. Instead, it will fix some of the webpack plugin loading issue related to yarn pnp.
Inside the [webpack config file](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/src/webpack/utils.ts), it refers to presets and plugins by strings, like `'@babel/plugin-transform-runtime'`. This setup _happens to_ work with the traditional package managers' behavior on `node_modules`, which tries to hoist `@babel/plugin-transform-runtime` to the top-level `node_modules` if it can. However, it won't work under …

fix(v2): use `require.resolve` for all webpack presets and plugins

---

packages/docusaurus-preset-bootstrap/src/index.js
packages/docusaurus-preset-classic/src/index.js
website/docs/presets.md

This diff continues the progress of making docusaurus v2 work under yarn v2's pnp mode.
- In #2788, I ensured that all webpack presets and plugins can be correctly resolved by `@docusaurus/core`.
- In #2789, I ensured that all user defined plugins can be correctly resolved by `@docusaurus/core`.
It would almost resolve almost all module resolution issues with yarn v2 pnp, except for presets. Docusaurus's presets still use plain string to refer to modules, which will make pnp module resolution fail.
In this diff, I fixed all the presets to use `require.resolve` in this repo. I also updated the docs to educate preset writers to use `require.resolve` in their code.
Yes
Everything can still be properly loaded, and the preview site still works.
(If this PR adds or changes functionality, please …

fix(v2): Use require.resolve to resolve plugin path in presets

---

packages/docusaurus-theme-classic/src/index.js

This diff continues the progress of making docusaurus v2 work under yarn v2's pnp mode.
There is a tricky require inside `@docusaurus/theme-classic`:
```js
const ContextReplacementPlugin = require('webpack/lib/ContextReplacementPlugin');
```
`@docusaurus/theme-classic` also declares `webpack` as a peer dependency. Currently at runtime, `webpack` is _likely_ to be provided by `@docusaurus/core`, which declares it as a direct dependency. However, this setup is theoretically not guaranteed to work, and it will certainly break in Yarn v2 pnp's strict mode. To understand why it's the issue, let me draw an layout of the node_modules.
In a package manager doesn't implement any hoisting optimization, the layout will be like
```text
- node_modules
- @docusaurus/core
- node_modules
- webpack
- …
```

fix(v2): Ensure that theme classic require webpack provided by `@docusaurus/core`

---

.prettierignore
packages/docusaurus-init/templates/bootstrap/docs/doc1.md
packages/docusaurus-init/templates/classic/docs/doc1.md
packages/docusaurus-init/templates/facebook/docs/doc1.md

Just small improvement after #2786 -- we can use `.prettierignore` file to specify Prettier, what files we do not want to check.
It does not make much sense to format the init templates files, so I think it is quite acceptable to completely disable any style checks for these files. Moreover, the user may not use Prettier, and they will be confused by Prettier-specific comments, IMO.
Yes
Run ` yarn prettier-docs` and make sure that there are no changes.

style(v2): disable Prettier checks for Markdown files of init templates

---

packages/docusaurus-mdx-loader/src/index.js

I use a remark plugin that allows me to use variables in markdown, while it works great for the content, in the right-side TOC the variables don't get interpolated. I figured this was because custom markdown plugins get loaded after the `remark/rightToc` plugin. This swaps the order of the if the default plugins and the custom plugins for both `remark` and `rehype`.
Yes!
I have run the docusaurus website locally as described [here](https://github.com/facebook/docusaurus/blob/master/admin/testing-changes-on-Docusaurus-itself.md) and have verified that swapping the order of the plugins works with these changes.
Without the order swapped
With the order swapped
Please advise if more testing, automated, or manual is needed. 
👍  Thanks for a great project!

feat(v2): allow specifying of remark and rehype plugins before default plugins

---

packages/docusaurus/package.json
packages/docusaurus/src/webpack/base.ts
yarn.lock

According to the discussion in #2795, I think we should add `pnp-webpack-plugin` directly to docusaurus core to enable a zero-config experience for yarn pnp users. It adds very little space overhead to non-pnp users: adding this to an empty projects only creates a 20kb `node_modules`.
After testing it on a local project after manually apply my pnp fix changes, including this one, I found that we are still one or two diffs away from fully supporting Yarn pnp mode. Here are some problems I found so far:
- Some code in the docs and blog plugin still uses plain string to refer to plugins. (Fixed in #2797)
- There are some issues of requires with generated code.
- `client-modules.js` related issues fixed in #2797 
- `@mdx-js/react` issue (generated blog code has `import { mdx } from …

feat(v2): Use pnp-webpack-plugin to support pnp module resolution

---

packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-ideal-image/src/index.ts
packages/docusaurus-theme-bootstrap/src/index.js
packages/docusaurus-theme-classic/src/index.js

Continuing the effort in #2788, #2794, using `require.resolve` to resolve absolute paths for loaders and client modules to ensure it can work under yarn pnp.
Yes
The website can build, and preview can load.

fix(v2): Consistently use require.resolve in official plugins to resolve modules

---

packages/docusaurus-preset-bootstrap/package.json
packages/docusaurus-preset-classic/package.json
packages/docusaurus-theme-bootstrap/package.json
packages/docusaurus-theme-classic/package.json
website/package.json

If a package `a` declare a peerDependency  `b`, then package that depends on `a` should either declare `b` as a dependency or peerDependency. i.e. no implicit transitive peer dependencies. See https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0
- `theme-classic`, `theme-bootstrap` lists `react` and `react-dom` as peer dependencies, so their presets should also list `react` and `react-dom` as peer dependencies. This eliminates the following warnings:
```text
warning " > @docusaurus/preset-classic@2.0.0-alpha.55" has unmet peer dependency "react@^16.8.4".
warning " > @docusaurus/preset-classic@2.0.0-alpha.55" has unmet peer dependency "react-dom@^16.8.4".
warning " > @docusaurus/theme-bootstrap@2.0.0-alpha.55" has unmet peer dependency "react@^16.8.4".
warning " > …
```

fix(v2): Properly declare peerDependencies

---

website/docs/contributing.md
website/docs/markdown-features.mdx
website/docs/migrating-from-v1-to-v2.md

External links that contain a period in the last segment of the path (`.com` or `.js`) will now be considered as file links, and therefore they will not open in a new tab.
See https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-classic/src/theme/MDXComponents/index.js#L24
Yes
Preview.

docs(v2): add trailing slash to external links

---

packages/docusaurus-init/templates/bootstrap/docs/doc1.md
packages/docusaurus-init/templates/bootstrap/docs/doc2.md
packages/docusaurus-init/templates/bootstrap/docs/mdx.md
packages/docusaurus-init/templates/classic/docs/doc1.md
packages/docusaurus-init/templates/classic/docs/doc2.md
packages/docusaurus-init/templates/classic/docs/mdx.md
packages/docusaurus-init/templates/facebook/docs/doc1.md
packages/docusaurus-init/templates/facebook/docs/doc2.md
packages/docusaurus-init/templates/facebook/docs/mdx.md

- Fix external links (by analogy in https://github.com/facebook/docusaurus/pull/2801)
- Fix demo MDX example.
- Fix spelling of GitHub
:ok_hand: 

misc: minor improvements for init templates

---

packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css

According to Infima styles https://github.com/facebookincubator/infima/blob/master/packages/core/styles/content/markdown.css#L36-L41
Yes
| ![image](https://user-images.githubusercontent.com/4408379/82725193-e9aa9000-9ce3-11ea-86b9-0d5847f03b74.png) |  ![image](https://user-images.githubusercontent.com/4408379/82725197-f29b6180-9ce3-11ea-857a-d1bfb5777f7c.png) |

fix(v2): make proper h1 font size on mobiles

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/styles.module.css

See Test plan.
Yes
|  ![screenshot_7](https://user-images.githubusercontent.com/4408379/82995573-7028df80-a00c-11ea-98ea-2fa6cda61dcb.png) | ![screenshot_8](https://user-images.githubusercontent.com/4408379/82995542-643d1d80-a00c-11ea-97de-6aea0409e3d7.png) |

refactor(v2): align search icon to center on mobiles

---

website/docs/team.md
website/docusaurus.config.js
website/src/pages/styles.module.css
website/src/pages/versions.js
website/versioned_docs/version-2.0.0-alpha.55/team.md

- Hold the logo higher so that it is not below the baseline of heading
- Fix highlighting of active navbar items using regexps (required many custom rules, but we can't get desired correct behavior without them)
- Versions page improvements: title and smaller upper margin (like on other pages)
- Fix React warnings due to invalid `class` prop.
Yes
See preview.

refactor(v2): various tweaks to website

---

packages/docusaurus-theme-classic/src/theme/hooks/useLogo.js

This is a request from Discord chat, I think we should take care to add the base url to the logo link automatically, this is the expected behavior I suppose.
Yes
Set document id to `navbar.logo.href` and make sure base url has been added to it.
By default a slash (`/`) will be added (standard base url).
Nevertheless, this is BC, because previously users had to manually specify the base url (in the case of using non-standard base url)

feat(v2): automatically add base url to logo link

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/src/commands/deploy.ts
website/docs/cli.md

Resolve #2723.
Yes
1. Deploy with building website:
```
GIT_USER=%user% USE_SSH=true yarn deploy
```
1. Deploy without building website (before this action, you first need to run the command to build the site (`yarn build`), otherwise there will be an error):
```
GIT_USER=%user% USE_SSH=true yarn deploy --skip-build
```
Both scenarios should lead to the deployment of the website.

feat(v2): allow deploy without building website

---

.eslintignore
.gitignore
.prettierignore

When running `yarn test --coverage` it generates a code coverage report that should rather not be versioned

chore: ignore /coverage folder

---

packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/sidebars/sidebars-category.js
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/sidebars/sidebars-collapsed-first-level.json
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/sidebars/sidebars-collapsed.json
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/sidebars.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/version.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/sidebars.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
website/docs/docs.md
website/sidebars.js

This allows a user to toggle a category open by default.
Yes.
Thanks to the tip from @lex111 I tested this locally on the Docusaurus website by modifying website/versioned_sidebars/version-2.0.0-alpha.40-sidebars.json and the changes worked as expected.
**Updated**: only highlight the category if the category belongs to the current page being viewed
- Fixes #2354 
- Original PR: #2613 
- PR that reverted work (due to breaking change): #2644

feat(v2): expanded sidebar categories by default

---

packages/docusaurus/src/server/plugins/init.ts

Actually fix #2825. It seems like `createRequire` expects a path to a nodejs module instead of a folder where the `package.json` happens to live in. The module would be `docusaurus.config.js`, which is guaranteed to exist in the root docusaurus project folder.
Yes.
1. Create a new docusaurus project.
2. Install `@docusaurus/plugin-ideal-image`.
3. `yarn start`, it will fail with the error in #2825.
4. Edit `node_modules` and manually apply the fix in this PR.
5. `yarn start`, it will now succeed.

fix(v2): Fix plugin path resolution

---

packages/docusaurus-theme-classic/src/prism-include-languages.js
packages/docusaurus-theme-classic/src/theme/prism-include-languages.js
website/docs/markdown-features.mdx

Right now it's hard to include custom languages syntax highlighting support. It's almost impossible to do it in a simple config due to context replacement issue. Right now there are two alternatives that both have some issues:
1. Swizzle `CodeBlock` component. Issue: A local `CodeBlock` might eventually diverge from the CodeBlock in `theme-classic`.
2. Write a plugin. This is the approach I am currently using. See [(1)](https://github.com/SamChou19815/website/blob/master/packages/lib-docusaurus-plugin/index.ts) and [(2)](https://github.com/SamChou19815/website/blob/master/packages/lib-docusaurus-plugin/prism-include-languages.js). However, whether the `Prism` object used by `theme-classic` will be correctly patched is completely at the mercy of package manager's hoisting behavior:
Suppose …

feat(v2): Allow swizzling prism-include-languages in theme-classic

---

packages/docusaurus/package.json
yarn.lock

Finally resolve #2229 
I [fixed the bug  causing issue error in the `react-loadable-ssr-addon` lib](https://github.com/themgoncalves/react-loadable-ssr-addon/pull/20), although I did not establish the _exact_ reasons, but it doesn’t matter, the main thing is that the website building is now successful.
Actually, because we use the caret versions range, the `react-loadable-ssr-addon` dependency is already updated, but this PR explicitly bumps a new version to formally close the issue.
Yes
1. Checkout to [this branch](https://github.com/facebook/docusaurus/tree/repro-2244/website-build-fail)
1. Inside `website-build-fail` dir, run `yarn build`
1. Make sure the website was built successfully …

fix(v2): fix broken build when swizzled NotFound component exist

---

packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts

Just minor fixes to remove Markdown markup for cleaner excerpt
For example, this Markdown snippet
```
```
produces following excerpt:
```
!First Birthday Slash
```
Pay attention to the question mark at the beginning that string - it should not be there.
This is due to the incorrect order of replacements (first we need to strip images links, and then other (inline) links). The same applies to footnotes, I added tests for them.
I also added a test for blockquote, because we have not tested this case before.
Yes
See tests and preview. 

fix(v2): strip images and footnotes for excerpt correctly

---

packages/docusaurus-theme-classic/src/theme/BlogListPage/index.js
packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.js
packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.js
website/src/pages/feedback/index.js
website/src/pages/showcase/index.js
website/src/pages/versions.js

This PR adds missing `main` elements to fix a11y issue reported by Rocket Validator:
> Document must have one main landmark 
Yes
Preview.

refactor(v2): add missing main landmark for needed pages

---

packages/docusaurus-theme-classic/src/theme/BlogListPaginator/index.js
packages/docusaurus-theme-classic/src/theme/BlogPostPaginator/index.js
packages/docusaurus-theme-classic/src/theme/DocPaginator/index.js

This PR adds missing `arial-label` attributes to fix a11y issue reported by Rocket Validator:
> Ensures landmarks are unique
Since there can be more than one `nav` element on one page, for all others except the first one we need to add aria label.
Yes
Preview.

refactor(v2): add aria label to paginators

---

packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.js
packages/docusaurus-theme-classic/src/theme/DocItem/index.js
packages/docusaurus-theme-classic/src/theme/Footer/index.js
packages/docusaurus-theme-classic/src/theme/Layout/index.js
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus/src/client/exports/__tests__/useBaseUrl.ts
packages/docusaurus/src/client/exports/useBaseUrl.ts
website/docs/blog.md
website/docs/docusaurus-core.md

This is a feature request from our user in Discord chat.
This PR adds the ability to specify a meta image for blog posts. 
Also, in order to avoid duplicate the code, I refactored `useBaseUrl` - after that it is a more understandable and clean function. I used the options array instead of the individual arguments because it is a more flexible way to control the behavior of this hook.
Yes
See tests and preview.

feat(v2): allow specifying meta image for blog posts

---

packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js

To resolve #2827.
Yes.
- Linted (`yarn prettier && yarn lint`).
- Tested (`yarn test`)
- but target file did not have any tests.
- Replacing the changed file on my test site to ensure that the defect is fixed.

fix(v2): use base url to navigate to search page

---

packages/docusaurus-theme-classic/src/theme/DocPage/index.js

This PR adds missing `arial-role` attribute of sidebar to fix a11y issue reported by Rocket Validator:
>  All page content must be contained by landmarks
Yes
Preview.

refactor(v2): add aria role for doc sidebar

---

packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/sidebars/sidebars-category.js
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/sidebars.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/version.test.ts.snap
packages/docusaurus-plugin-content-docs/src/sidebars.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js

CC @jsjoeio @lex111 @yangshun , this is a fix for https://github.com/facebook/docusaurus/pull/2682#issuecomment-636631225
I investigated the reasons of the FOUC on the docs sidebar after adding the `category.collapsed = false`, but actually found multiple problems that lead me to this refactor (some of them existed before).
- Reading `window.location` to know which sidebar items are "active": that works only client-side after hydration, and was a reason of the FOUC. Replaced by `activePath` that's actually provided on both client and server (via ReactRouter <StaticRouter/>). Note it could have been possible to use `useLocation` from React-router as well.
- Bad normalization of the new category collapsed attribute. We want to ensure to always have a mandatory boolean for this setting in …

fix(v2): fix FOUC in doc sidebar and various improvements

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/index.ts
website/docs/docs.md

Resolve #2830.
When we set the docs home page, we have two duplicate pages, for example, in the case of https://v2.docusaurus.io/:
- https://v2.docusaurus.io/docs/
- https://v2.docusaurus.io/docs/introduction
These two pages contain the same content (document of "introduction"), this is not good for SEO. I missed this important thing and therefore did not define the canonical URL for the `/docs` URL. However, after discussing with one our user, [we decided it was best not to create a separate route for document at all](https://github.com/facebook/docusaurus/issues/2830#issuecomment-635965464), which serves as docs home page.
Yes, this is a BC, but I guess  we can recommend in release notes that our user add a redirect using our official plugin to inform search engines about this change. …

fix(v2): do not create route for document that serve as docs home page

---

packages/docusaurus-theme-classic/src/theme/MDXComponents/index.js

One of our users complained that inline code in raw HTML was not rendered correctly. I advised him to use Markdown syntax to define tables, to which he replied that in this case lists cannot be used. That's fair, raw HTML gives you more opportunities and flexibility,  so we should take this into account.
I mean, inline code in raw HTML should be rendered using regular HTML element, rather `CodeBlock` component (see screenshots below).
Yes
```
<table>
<tr>
<th>Argument</th>
</tr>
<tr>
<td><code>name</code></td>
</tr>
</table>
```
| ![Screenshot from 2020-06-01 13-35-52](https://user-images.githubusercontent.com/4408379/83401170-e9f60a00-a40c-11ea-9ce9-8fc341a41149.png) | ![image](https://user-images.githubusercontent.com/4408379/83401103-c0d57 …

fix(v2): treat inline code in raw HTML as native element

---

website/src/pages/index.js

When opening the initial page and clicking on the `Getting Started`  button, the link was broken. This is because we change the initial docs path recently.
[imgur](https://imgur.com/a/6fIZhbq)
yes
1. Open the docusaurus v2 initial page
2. Click on the getting started button and 
#2652

fix(v2): Getting Started URL

---

packages/docusaurus-theme-live-codeblock/package.json
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/ReactLiveScope/index.js
website/docs/markdown-features.mdx
website/src/theme/ReactLiveScope/components.js
website/src/theme/ReactLiveScope/index.js

Currently, the react-live scope only exposes the React exports, so we can use React, useState etc, but we can't import any other code easily.
If you build a react component library, and want to allow users to play with the components in a live editor, it's important to have a documented way to provide those components in the react-live scope.
See https://github.com/facebook/docusaurus/issues/2807
Dogfooding by using this feature on the Docusaurus website directly
Swizzling of the react-live scope object is not an ideal solution, as it's global and needs more work from the user, but I think it's good enough to solve the usecase for now.
When we'll have a way to wrap root component, users could use the MDXProvider to reuse the components of the MDX scope for react-live too, instead of …

feat(v2): allow adding components to react-live scope

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css

When `themeConfig.sidebarCollapsible = false` is set, the category link is still clickable (if you click on it, `#!` symbols will be added to the address bar of browser), besides this, the hover state works, which should not be.
Yes
Prerequisite: mouse over a category
| ![screenshot_21](https://user-images.githubusercontent.com/4408379/83749490-76523800-a66c-11ea-8925-2dc3045acdcf.png)|![screenshot_20](https://user-images.githubusercontent.com/4408379/83749481-72beb100-a66c-11ea-9e5d-638d80c1a9bd.png) |

fix(v2): render as regular text uncollapsible categories

---

website/docs/deployment.md
website/docs/static-assets.md

We should make this more obvious and also put it within the "static assets" page.
Yes
Netlify

docs(v2): make .nojekyll warning more obvious

---

packages/docusaurus-init/templates/bootstrap/docusaurus.config.js
packages/docusaurus-theme-bootstrap/README.md
packages/docusaurus-theme-bootstrap/src/theme/DocPage/index.js
packages/docusaurus-theme-bootstrap/src/theme/Navbar/index.js

When I was trying to load the doc page, from index page, the page was not loaded. I also fixed an error about active path in navbar.
Yes
open the bootstrap template, and go to `/docs`

fix(v2): bootstrap doc sidebar

---

website/docs/installation.md
website/versioned_docs/version-2.0.0-alpha.56/installation.md

Checking the docusaurus version should be done with
```
npx docusaurus --version
```
not 
```
npm docusaurus --version
```
otherwise it prints the version of `npm` instead of `docusaurus`.

docs(v2): fix typo in command on installation page

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.js
website/docs/markdown-features.mdx

Address #2885.
When a tab group choice is updated, the updated choice might not be available in some tab groups. In the current implementation, it will just appear that nothing is chosen, which might look confusing. This diff changes the behavior so that it will avoid updating a local tab choice when a tab group choice chooses an non-existing option.
Yes
See the added docs. When I select Linux which doesn't exist in the above two tab groups, those groups' tab choices don't change.

fix(v2): Do not automatically change tab when a non-existing option is selected

---

packages/docusaurus-theme-classic/src/theme/DocPage/index.js

Currently the canonical url for docs homepage refers to the original doc permalink, we need to adjust it. Since this affects the render of component, you need to change the canonical url in the DocPage component itself. 
```
<link data-react-helmet="true" rel="canonical" href="https://v2.docusaurus.io/docs/introduction">
```
Yes
On Preview (https://deploy-preview-2896--docusaurus-2.netlify.app/docs/):
```diff
- <link data-react-helmet="true" rel="canonical" href="https://v2.docusaurus.io/docs/introduction">
+ <link data-react-helmet="true" rel="canonical" href="https://v2.docusaurus.io/docs/">
```

fix(v2): set correct canonical url for docs home page

---

packages/docusaurus-init/templates/classic/package.json
packages/docusaurus-init/templates/classic/src/pages/index.js
packages/docusaurus-init/templates/facebook/package.json
packages/docusaurus-init/templates/facebook/src/pages/index.js
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.js
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-classic/src/theme/DocItem/index.js
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
packages/docusaurus-theme-classic/src/theme/Footer/index.js
packages/docusaurus-theme-classic/src/theme/Heading/index.js
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus-theme-classic/src/theme/Tabs/index.js
packages/docusaurus-theme-classic/src/theme/Toggle/index.js
packages/docusaurus-theme-live-codeblock/package.json
packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.js
packages/docusaurus-theme-search-algolia/package.json
packages/docusaurus-theme-search-algolia/src/pages/search/index.js
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
packages/docusaurus/package.json
website/docs/migrating-from-v1-to-v2.md
website/docusaurus.config.js
website/package.json
website/src/pages/feedback/index.js
website/src/pages/index.js
website/src/pages/showcase/index.js
yarn.lock

- Reducing bundle size
- Increasing performance
About [clsx](https://www.npmjs.com/package/clsx):
> A tiny (228B) utility for constructing className strings conditionally.
> **Also serves as a faster & smaller drop-in replacement for the `classnames` module.**
Yes
Preview.
All chunks size (parsed) for website v2.
| 4.21 MB | 4.1 MB |

chore(v2): replace classnames with clsx

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/package.json
yarn.lock

Actually there is no need to use the [Clipboard](https://www.npmjs.com/package/clipboard) package, we can do with a more lightweight alternative (https://www.npmjs.com/package/copy-text-to-clipboard)
Yes
Preview.
All chunks size (parsed) for website v2.
| 4.22 MB | 4.11 MB |

chore(v2): replace Clipboard with copy-text-to-clipboard

---

packages/docusaurus-1.x/lib/server/__tests__/utils.test.js
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/metadata.test.ts

For async tests, doing expectation in catch code is bad because if the promise resolves instead of rejecting, the test still pass, while it's expected to fail.

chore(v2): fix async tests

---

website/docs/deployment.md

It fixes a typo in documentation of version 2 with the GitHub action workflow.
The `run` attribute in the workflow should either be `- run: something` or with a name. It also handles the workflow if lockfile is absent. 
Yes
I tried it on repo and it worked well.
It is related to #2846

docs(v2):Fixed Github action workflow in Documentation

---

.eslintignore
.gitignore
.prettierignore
packages/docusaurus-plugin-debug/package.json
packages/docusaurus-plugin-debug/src/index.ts
packages/docusaurus-plugin-debug/src/theme/Debug/index.js
packages/docusaurus-plugin-debug/src/theme/Debug/styles.module.css
packages/docusaurus-plugin-debug/tsconfig.json
packages/docusaurus-preset-classic/src/index.js

This PR implements the docusaurus debug dashboard proposal in #2267.
It utilizes the generated files to produce some useful information. Currently, it only includes resolutions of aliased path and routes list, but we can do more fancy analysis in the future. In the future, we can also make `@docusaurus/core` to generate more files so that more useful debug information can be displayed.
I included it in the classic preset only in dev to reduce bundle size.
I will add it to the docs once the maintainers think this is a good start.
Yes
`yarn start` and goto http://localhost:3000/__docusaurus/debug
Check the preview url …

feat(v2): Implement proof-of-concept Docusaurus Debug Dashboard

---

website/docs/blog.md
website/docs/deployment.md
website/docs/using-plugins.md
website/versioned_docs/version-2.0.0-alpha.48/using-plugins.md
website/versioned_docs/version-2.0.0-alpha.50/using-plugins.md
website/versioned_docs/version-2.0.0-alpha.54/using-plugins.md
website/versioned_docs/version-2.0.0-alpha.55/using-plugins.md
website/versioned_docs/version-2.0.0-alpha.56/blog.md
website/versioned_docs/version-2.0.0-alpha.56/using-plugins.md

Add documentation about how to set up multiple blogs. 
This PR closes #2481. It also fixes a minor typo. 
Yes
The changes can be viewed on Netlify here: 
https://deploy-preview-2933--docusaurus-2.netlify.app/docs/blog/#multiple-blogs
As noted in #2883, the user needs to add `require.resolve(<plugin-name>)` to the plugin name, in addition to the instructions stated in the documentation.
But I have excluded this to maintain consistency with the [plugins documentation](https://v2.docusaurus.io/docs/using-plugins/).
Should I make another PR to add in `require.resolve` for all plugin names?

docs(v2): add documentation for multiple blogs

---

.github/workflows/e2e-test.yml

Test changes on a build with a simulated release and build, so that we can catch errors that are not detectable in a yarn workspace monorepo setup (See #2829 . In this way, we can prevent bad releases and avoid issues like #2883 in the future.
This CI job runs faster than the windows build job so it won't increase the total time for all CI checks to pass.
Yes
CI passes

chore(v2): Run E2E tests in CI

---

website/docs/theme-classic.md

A few people were having issues using theme information because they were trying to access it in the page component instead of in a component that is wrapped by the layout or theme provider component. The note I added to the docs will hopefully clarify this.
Yes
I added a note to the bottom which includes an example of how the component should be nested.
facebook/docusaurus#2912
facebook/docusaurus#2646

docs(v2): add useThemeContext note

---

packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/metadata.test.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/metadata.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.js

Add a badge that links older versions of documentation to the latest version of the documentation. This PR closes #2432.
Yes.
1. After visiting the netlify preview site, go to any older version of the documentation . Check that there is a badge that links to the latest version
1. Click on the link to the latest version. There should be no badge next to the version number, since we are now at the latest version
The automated tests has been updated accordingly.

feat(v2): add a banner that links to latest version of documentation

---

packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-sitemap/src/index.ts

I encounter same problem like #2539 in alpha.50 and discover its have been resolved. But the solution to fix is sync way. 
Yep
Build website and make sure that the `build/blog/atom.xml`, `build/blog/rss.xml` and `build/sitemap.xml` files are still work correct.

perf(v2): convert synchronous filewrite to asynchronous

---

CHANGELOG-2.x.md

The 2.0.0-alpha56 Change log does not make mention to the breaking change with plugin imports. The [GitHub release](https://github.com/facebook/docusaurus/releases/tag/v2.0.0-alpha.56) does. This has meant that dependabot has missed this change in it's pull requests (which seemed to use the changelog in some cases)
N/A Doc change

Update change log

---

packages/docusaurus-theme-classic/src/theme/Heading/styles.module.css

Resolve #2907
Yes
1. Disable `hideOnScroll` in the config file (if enabled)
2. Build a site
3. Go to direct link to anchor
4. Click on a link that leads to anchor on another page  (or simulate this behavior via this snippet `(document.getElementById('features')).scrollIntoView()`)

fix(v2): adjust anchor offset when routes switched

---

website/docs/using-plugins.md
website/versioned_docs/version-2.0.0-alpha.56/using-plugins.md

As per the breaking change in 2.0.0-alpha56 plugin call need to be wrapped in `require.resolve(...)`. Add this to the examples.
Yes

docs(v2): wrap all plugin imports in require.resolve()

---

website/versioned_docs/version-2.0.0-alpha.56/blog.md
website/versioned_docs/version-2.0.0-alpha.56/configuration.md
website/versioned_docs/version-2.0.0-alpha.56/presets.md
website/versioned_docs/version-2.0.0-alpha.56/styling-layout.md
website/versioned_docs/version-2.0.0-alpha.56/using-themes.md

Plugin imports on some pages are not wrapped in `require.resolve` yet.
This PR adds `require.resolve` to plugin imports on the remaining pages (for v2.0.0-alpha.56 docs).
Yes 
The changes can be viewed on Netlify here: 
https://deploy-preview-2946--docusaurus-2.netlify.app/
This PR is similar to #2941, but for the remaining pages.

docs(v2): add require.resolve to plugin imports on remaining pages

---

packages/docusaurus-plugin-content-blog/src/markdownLoader.ts
packages/docusaurus-plugin-content-docs/src/markdown/index.ts

The `export = function() {}` syntax is not really something std JS, afaik it existed in TS before ES imports

refactor(v2): legacy export = syntax

---

packages/docusaurus-preset-classic/package.json

Missed it in #2929. We should probably include `docusaurus start` in E2E test in the future to prevent this kind of bug.
Yes
Nothing breaks in CI

fix(v2): Declare @docusaurus-plugin-debug as dependency of preset classic

---

packages/docusaurus/src/babel/preset.ts
yarn.lock

These plugins are necessary since we introduced some nullish coalescing syntax in #2884. See #2950 for the rationale. This PR is also needed for #2950 to be merged without CI error.
Yes
```bash
./admin/scripts/test-release.sh
cd test-website
yarn start
```
Without this change, it will fail. With this change, website can correctly load.

fix(v2): Add optional-chaining and nullish-coalescing babel plugin

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus-theme-classic/src/theme/hooks/useWindowSize.js

Resolve #2750 
Yes
1. Change browser size to mobile (<=996px)
2. Open one of the nav bar or doc sidebar using the mobile toggling button
3. Resize to desktop width (> 996px)
4. Observe reset of mobile navigation

fix(v2): Add hooks to detect window resize, toggle off sidebar and navbar in desktop

---

website/docs/resources.md

I'm using [PostHog](https://posthog.com) to track my site's traffic. I need to send a `$pageview` event each time the URL changes. For this I need to hook into docusaurus - just adding posthog's JS snippet in the footer won't cut it.
Yes! I even signed the CLA.
No code change, just added a link to the docs.

docs: mention posthog-docusaurus plugin

---

website/versioned_docs/version-2.0.0-alpha.58/using-plugins.md

fixed grammar error in @docusaurus/plugin-content-pages example from 'blog' to 'page'
While reading through the docs I found a small grammar error here: [#docusaurusplugin-content-pages](https://v2.docusaurus.io/docs/using-plugins/#docusaurusplugin-content-pages)
I've concluded it to be a grammar error due to the fact that we see the exact same sentence in the blog example.
Yes, small change. 👍 

docs(v2): update grammar in plugin-content-pages example

---

.gitignore
admin/publish.md

publish doc update after alpha.58 release
cc @yangshun

doc(v2): publish doc update after alpha.58 release

---

website/docs/using-plugins.md
website/versioned_docs/version-2.0.0-alpha.58/using-plugins.md

In ref to #2966
Also addressed a similar typo in the [#docusaurusplugin-content-docs](https://v2.docusaurus.io/docs/using-plugins#docusaurusplugin-content-docs) section. (See screenshot below)
Yes.
Please confirm 'docs' is plural and not meant to be 'doc'.
#2966

docs(v2): fix typos in plugin-content examples

---

website/docs/using-plugins.md

I was reading the docs about creating a new plugin, and it referred to "docusaurus.config.js" as the file that contains the plugin code. I thought this was somewhat strange as it seems like the plugin code should just be an index.js or similar, so I modified the docs a little bit to help.
Yes
N/A
N/A

docs(v2): update docs about creating a new plugin

---

packages/docusaurus-theme-classic/src/theme/ThemeContext.js
packages/docusaurus-theme-classic/src/theme/UserPreferencesContext.js
packages/docusaurus-theme-classic/src/theme/hooks/useThemeContext.js
packages/docusaurus-theme-classic/src/theme/hooks/useUserPreferencesContext.js

Close #2912 to give user a clear direction.
I didn't create a docs pointer for the `useUserPreferencesContext` hook since it's more internal and unlike to be used by pages in top level.
Yes
Try to add `useThemeHook` `useUserPreferencesContext` to `website/src/pages/index.js` and see it crash.

feat(v2): Error when hooks depends on context is used outside of Layout

---

website/docs/using-plugins.md

Doc: the redirect plugin only works for the production build
Important note to add after feedback of @jknoxville here: https://github.com/facebook/docusaurus/pull/2969#issuecomment-646678413

docs(v2): add plugin redirects production build note

---

website/docs/markdown-features.mdx
website/versioned_docs/version-2.0.0-alpha.58/markdown-features.mdx

The code needed to be in npm syntax in order to work with npm2yarn

Fix typo in markdown-features

---

docs/api-site-config.md
docs/guides-versioning.md
packages/docusaurus-1.x/lib/server/readMetadata.js
packages/docusaurus-1.x/lib/server/versionFallback.js

Fixes an issue with v1 versioning fallback described in https://github.com/facebook/docusaurus/issues/2429 and https://github.com/facebook/docusaurus/issues/2123
This adds support for a `deletedDocs` option in `siteConfig`, which allows you to mark article IDs as being deleted beginning with a certain version. This circumvents version fallback and also removes the article from the versionless/next URL.
Example:
```js
{
deletedDocs: {
"2.0.0": new Set([
"tagging"
])
}
}
```
This is a backwards-compatible new feature for v1, but also essentially a "fix" for this issue that can be very serious when instructions that shouldn't be followed on later versions are still accessible in those versions.
Note that v2 uses a different approach to versioning that does not have this problem in the first …

Add deletedDocs config to fix unwanted versioning fallback

---

packages/docusaurus-theme-classic/package.json

It's annoying to see `Duplicate object key` warnings in vscode.
Yes
CI

chore(v2): Merge devDependencies in theme-classic

---

website/docs/lifecycle-apis.md
website/docs/typescript-support.md
website/sidebars.js
website/tsconfig.json

This PR documents recent additions to TypeScript support. It tells users on how to setup TS docusaurus project with good editor experience.
Yes
- Read the docs in preview site
- Run `yarn workspace docusaurus-2-website tsc` to validate that the recommended `tsconfig.json` content in the docs actually works.

docs(v2): Document TypeScript support

---

packages/docusaurus/package.json
packages/docusaurus/src/server/__tests__/__fixtures__/simple-site/docusaurus.config.js
packages/docusaurus/src/server/__tests__/__snapshots__/config.test.ts.snap
packages/docusaurus/src/server/__tests__/__snapshots__/configValidation.test.ts.snap
packages/docusaurus/src/server/__tests__/config.test.ts
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/config.ts
packages/docusaurus/src/server/configValidation.ts
website/docusaurus.config.js

More robust validation for config. Validating more fields and types. It fixes  #2978.
yes
I have added tests for validation and update old ones

chore(v2): use joi for  config validation

---

packages/docusaurus/package.json
yarn.lock

These two dependencies are added to #2951 to fix #2908. However, somehow I forget to add them to dependency list. It still passes the CI because they are devDependencies in the root package.json.
Yes
CI passes

fix(v2): Add two missing docusaurus core babel dependency

---

packages/docusaurus-plugin-client-redirects/src/__tests__/collectRedirects.test.ts
packages/docusaurus-plugin-client-redirects/src/__tests__/extensionRedirects.test.ts
packages/docusaurus-plugin-client-redirects/src/collectRedirects.ts
packages/docusaurus-plugin-client-redirects/src/extensionRedirects.ts
packages/docusaurus-plugin-client-redirects/src/index.ts
packages/docusaurus-plugin-client-redirects/src/types.ts
packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus/src/server/configValidation.ts
website/docusaurus.config.js

This PR makes client-redirect-plugin not baseUrl sensitive by using relative paths.
It also fixes a minor client-redirect issue in the Docusaurus website. 
This PR closes #2982.  
Yes
**Test client-redirect-plugins with baseUrl**
1. Follow the steps for reproducing #2982
2. The redirection is working now
**Test D2 website client-redirect**
1. Go to https://deploy-preview-3010--docusaurus-2.netlify.app/docs/introduction
2. You should be redirected to `/docs`

fix(v2): make client-redirect-plugin not baseUrl sensitive

---

packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus/src/client/exports/ComponentCreator.tsx
packages/docusaurus/src/server/__tests__/__snapshots__/routes.test.ts.snap
packages/docusaurus/src/server/routes.ts

See #2917
Fix potential weird merge behavior when a parent route and its child has the exact same path.
```js
addRoute({
path: "/docs", // <===
exact: false,
component: DocPage,
routes: [
{
path: "/docs", // <===
exact: true,
component: DocItem
}
]
});
```
To avoid potential conflicts, smallHash(route) is added at the end of the chunknames key.
Also refactors the routes.ts file by splitting a bit the logic and trying to make it more readable than before (inline code generation strings do not help for readability)
Yes
tests + preview

fix(v2): refactor routes.ts + add route hash for chunkNames key

---

website/docs/markdown-features.mdx
website/src/pages/versions.js
website/versioned_docs/version-2.0.0-alpha.50/markdown-features.mdx
website/versioned_docs/version-2.0.0-alpha.54/markdown-features.mdx
website/versioned_docs/version-2.0.0-alpha.55/markdown-features.mdx
website/versioned_docs/version-2.0.0-alpha.56/markdown-features.mdx
website/versioned_docs/version-2.0.0-alpha.58/markdown-features.mdx

This PR fixes broken links on https://v2.docusaurus.io/versions/, and closes #3016. 
It also fixes broken links to Remark and Rehype, as they have renamed their master branch.
Yes
1. Go to https://deploy-preview-3017--docusaurus-2.netlify.app/versions
2. The 'Documentation' links should work
3. Go to https://deploy-preview-3017--docusaurus-2.netlify.app/docs/markdown-features/#configuring-plugins
4. The links at the following line should work

fix(v2): fix broken links on versions page

---

packages/docusaurus-theme-classic/src/theme/BlogPostPaginator/index.tsx

This PR closes #2698. Originally, "Next Post" links to an older blog post and "Previous Post" links to a newer blog post. This PR changes the description to "Older Post" and "Newer Post" respectively to avoid confusion. 
I noticed that [blog list paginator](https://v2.docusaurus.io/blog) has "Older Entries" on the right hand side, so I kept the same ordering for blog page paginator.
Yes.
The changes can be viewed at https://deploy-preview-3029--docusaurus-2.netlify.app/blog/2018/12/14/Happy-First-Birthday-Slash

fix(v2): change description for blog post paginator

---

packages/docusaurus/src/client/exports/__tests__/useBaseUrl.ts
packages/docusaurus/src/client/exports/useBaseUrl.ts
website/docs/docusaurus-core.md

Sometimes you need to add the baseUrl to a list of urls, and `useBaseUrl()` is not good for that
Yes
tests
See comments to support for baseUrl in Algolia DocSearch pr here: https://github.com/facebook/docusaurus/pull/2815

feat(v2): add useBaseUrlUtils() hook

---

website/docs/blog.md
website/docs/docs.md
website/versioned_docs/version-2.0.0-alpha.58/docs.md

Instruct the user to remove `/src/pages/index.js` for docs-only mode to work correctly.
Also, the documentation for `blog-only-mode` has 2 admonitions with the same content, so I removed one of them.
This PR closes #3039.
Yes
1. Init a new docusaurus site with `npx @docusaurus/init@next init my-website classic`
2. Follow the instructions found here https://deploy-preview-3040--docusaurus-2.netlify.app/docs/docs-introduction/#docs-only-mode
3. docs-only mode works now

docs(v2): correct the documentation for docs-only mode

---

packages/docusaurus-plugin-content-pages/src/index.ts
website/src/pages/index.js

Migrating from v1 to v2 all the components are converted to Functional Component. It fixes #2925 
yes
I checked it manually props are passed perfectly

fix(v2):pass siteConfig as prop to pages

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-plugin-debug/src/theme/Debug/index.js
packages/docusaurus-plugin-debug/src/theme/Debug/styles.module.css
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/plugins/index.ts
packages/docusaurus/src/server/plugins/init.ts
packages/docusaurus/src/server/types.d.ts
packages/docusaurus/src/server/versions/__fixtures__/package.json
packages/docusaurus/src/server/versions/__tests/index.test.ts
packages/docusaurus/src/server/versions/index.ts

Implements the proposal in #3042.
`@docusaurus/core` will collect and generate all the plugin version at start time, and put them into `.docusaurus/site-metadata.json`. To find the version of the plugin, I choose to walked up the directory of the resolved path until it hits a directory with package.json.
The version information has 4 possible categories:
- `package`: plugin is external to the current docusaurus project, with will be attached with a version string if it can be found in package.json
- `project`: plugin is inside the same docusaurus project
- `local`: some random place on the filesystem that doesn't have any package.json in its ancestor directories.
- `synthetic`: only used to workaround the synthetic `docusaurus-bootstrap-plugin`: …

feat(v2): Collect plugin versions to allow them to be inspected in debug plugin

---

packages/docusaurus/bin/docusaurus.js
packages/docusaurus/package.json
yarn.lock

Notify the user when their @docusaurus/core version is outdated. 
The interval between notifications is set to one day so that it is not too naggy.
This PR closes #2199.
Yes
1. Run `yarn install` in the root directory 
2. Open `package.json` file in `/packages/docusaurus`, change line 4 to `"version": "2.0.0-alpha.56",` 
3. Go to the `/website` directory in your terminal, run `yarn start`. You should see a notification like the one below!
4. Run `yarn start` again, there should be no notification this time because the interval is set to one day
The notify method of update-notifier does not work directly with our docusaurus command, so the implementation needed to be modified.

feat(v2): notify users when docusaurus version is outdated

---

packages/docusaurus-plugin-pwa/src/index.js
packages/docusaurus/package.json
packages/docusaurus/src/babel/preset.ts
yarn.lock

Core JS 2 is deprecated. It would be good if we don't stick with it forever.
I also changed to `useBuiltIns` to be `entry` for the purpose of Yarn pnp. If we use `usage`, babel will inject imports of core-js in literally every JS file. It will trick Yarn to believe that every single JS module depends on core-js, and therefore every package depends on core-js. Since core-js is not declared as a dependency for every package, it will trigger a lot of require errors. To patch that, you need to declare it on every package you use, like [this](https://github.com/SamChou19815/website/blob/88d052290e9f67557cc5971e2c469a6f3f68347a/.yarnrc.yml#L2-L35), which doesn't scale.
Yes …

chore(v2): Adopt corejs 3 and only import at entry point

---

packages/docusaurus/src/client/exports/isInternalUrl.ts

Currently, only specific protocol links (http://, https://, tel: and mailto:) in the navbar and footer are treated as external - other protocols such as ssh://, sftp:// etc are treated as internal and get prepended with `baseUrl` which breaks the links.
It would be nice to be able to have other protocols in links as well. My suggested solution is to let the `isInternalUrl` test check for any protocol identifier rather than specific ones. 
Yes
Using the following navbar configuration in `docusaurus.config.js`
```javascript
navbar: {
hideOnScroll: true,
title: 'Docusaurus',
logo: {
alt: 'Docusaurus Logo',
src: 'img/docusaurus.svg',
srcDark: 'img/docusaurus_keytar.svg',
},
links: [
{
href: 'https://example.com',
label: 'https://example.com',
position: 'left',
},
{
href: 'tel:18005551042', …
```

fix(v2): classify link hrefs with protocol identifier as internal

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-plugin-debug/src/theme/Debug/index.js
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/client/App.tsx
packages/docusaurus/src/client/exports/context.ts
packages/docusaurus/src/client/exports/useDocusaurusContext.ts
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/plugins/init.ts
packages/docusaurus/src/server/versions/index.ts
website/docs/configuration.md
website/docs/docusaurus-core.md

Expose siteMetadata in `useDocusaurusContext()` hook
Algolia devs need access docusaurus version, and we should rather advise to use the hook instead of importing a static generated file (makes comp testing easier by using a provider)
See also:
- https://github.com/facebook/docusaurus/pull/3050
- https://github.com/facebook/docusaurus/issues/3042
---
@SamChou19815 I moved a bit the type declaration to match what we currently have for siteConfig type declaration and be uniform. 
Not totally sure yet what's the impact of declaring types in one or the other of `@docusaurus/types` vs `docusaurus-module-type-aliases`

feat(v2): useDocusaurusContext().siteMetadata

---

docs/api-doc-markdown.md
docs/guides-blog.md
docs/guides-navigation.md
docs/guides-translation.md
docs/guides-versioning.md

fixing a few typos in the documentation and enhancing clarity of a few sentences.
Yes
N/A
N/A

fixing few typos and enhancing few sentences clarity

---

docs/getting-started-publishing.md

Closes https://github.com/facebook/docusaurus/issues/1208
Adding azure pipelines CI guide.
Yes.

docs: Add azure-pipelines CI guide

---

packages/docusaurus-init/templates/bootstrap/package.json
packages/docusaurus-init/templates/classic/package.json
packages/docusaurus-init/templates/facebook/package.json
website/package.json

NPM users should be able to run commands such as `npm run docusaurus docs:version 1.1.0`, but it fails by default while it works in yarn
https://github.com/facebook/docusaurus/issues/3100#issuecomment-663099776

feat(v2): add docusaurus script for npm users

---

packages/docusaurus-plugin-content-docs/src/index.ts

prevents docs to work when not using the default docs path (website/docs)

fix(v2): fix docs instance path typo

---

packages/docusaurus/src/client/exports/__tests__/useBaseUrl.ts
packages/docusaurus/src/client/exports/useBaseUrl.ts

It never makes sense to add a base url to a local anchor url like `#site-configuration`
fixes https://github.com/facebook/docusaurus/issues/3110

fix(v2): baseUrl is wrongly appended to anchor links

---

packages/docusaurus-theme-classic/src/themeConfigSchema.js

The new validation is too strict and wouldn't allow a valid configuration where the parent dropdown item has no href/to attribute.
The config of this user, which is legit and works in former versions, wouldn't be accepted anymore:
https://github.com/facebook/docusaurus/issues/3067#issuecomment-661949863

fix(v2): dropdown navbar item: validation too strict

---

packages/docusaurus/src/server/brokenLinks.ts

In the broken links detection code, we try to see if a link match an existing fs file in the build folder. We should not consider folders in this algo, only files, as this part of the code is to avoid reporting errors when user link to a static file (broken SPA paths is handled in a different way without reading the FS)

fix(v2): broken links detector: ignore existing folders

---

.github/workflows/migration-cli-e2e-test.yml
.gitignore
package.json
packages/docusaurus-migrate/src/__tests__/frontMatter.test.ts
packages/docusaurus-migrate/src/frontMatter.ts
packages/docusaurus-migrate/src/index.ts
yarn.lock

We should have a dev workflow to easily test the migration cli against current code (ie with symlinks instead of using the latest npm release, which might not be compatible)

chore(v2): ability to test the migration cli easily

---

packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
packages/docusaurus-plugin-content-docs/src/pluginOptionSchema.ts
packages/docusaurus-theme-classic/src/themeConfigSchema.js
packages/docusaurus/src/server/configValidation.ts
yarn.lock

This PR modifies the config validation for the following fields:
1. navbar.title
2. rehypePlugins
3. routeBasePath
4. scripts 
5. stylesheets
It allows the following values for navbar.title: `''`, `null`, `undefined`. This fixes #3117. 
The schema for rehypePlugins has been modified. It now accepts an array, whose items are either:
- a function (because the rehypePlugins are of function type).
- an array of [function, object] in Babel style (See https://v2.docusaurus.io/docs/markdown-features/#configuring-plugin-options for an example)
This fixes #3125.
It accepts the empty string `''` now. This is useful for removing `/docs` from url while having a landing page. This fixes #3126. 
scripts accepts both defer and async now. 
stylesheets accepts unknown fields now.
This fixes #3128 
Yes
1. …

fix(v2): make config validation less strict

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

The Algolia search button doesn't contain text which fails lighthouse a11y tests + isn't nice for screen readers.
Yes
This has just been tested manually by checking the markup and running lighthouse.
After
Before
Markup
N/A

feat(v2): add accessible label for Algolia search button

---

packages/docusaurus-theme-classic/src/themeConfigSchema.js

Fix ability to provide link target for example https://github.com/facebook/docusaurus/issues/3139

fix(v2): navbar item links should allow unknown attributes

---

packages/docusaurus/src/client/exports/Link.tsx
website/docs/search.md
website/versioned_docs/version-2.0.0-alpha.59/search.md

Automatically append the baseUrl to links, but this time only the "safe/absolute ones": "/docs/xyz" => "/baseUrl/docs/xyz"
We should absolutely avoid transforming relative links to absolute ones.
useBaseUrl looks buggy to me and does this: "xyz" => "/baseUrl/xyz"
Related issue: https://github.com/facebook/docusaurus/issues/3136
This is a temporary workaround, we should rather use ReactRouter basename and deprecate useBaseUrl()
Yes
The broken links should fail CI. We now have some in /docs/search.md for dogfooding 
https://github.com/facebook/docusaurus/pull/3107
https://github.com/facebook/docusaurus/pull/3059
https://github.com/facebook/docusaurus/pull/3093

fix(v2): absolute Links should be automatically prefixed by baseurl

---

packages/docusaurus/src/client/exports/BrowserOnly.tsx

This is not something to do in React
https://github.com/facebook/docusaurus/issues/3144

fix(v2): BrowserOnly should not return undefined

---

website/docs/community/team.md
website/src/components/TeamProfileCard/index.js

docs(v2): add myself to /team page + add TeamProfileCard component

---

packages/docusaurus-plugin-content-blog/src/__tests__/__snapshots__/pluginOptionSchema.test.ts.snap
packages/docusaurus-plugin-content-blog/src/__tests__/pluginOptionSchema.test.ts
packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
packages/docusaurus-plugin-content-docs/src/__tests__/pluginOptionSchema.test.ts
packages/docusaurus/src/server/__tests__/__snapshots__/configValidation.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts

This PR adds tests for config validation, especially for the validation bugs that were fixed in PR #3120. This helps to make the Joi validation less prone to errors.
I've also allowed empty string for some fields so that the validation is not unnecessarily strict.
Yes
Automated tests
This is related to the validation bugs in #3120.

test(v2): add tests for config validation

---

packages/docusaurus-plugin-client-redirects/package.json
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-pages/package.json
packages/docusaurus-plugin-debug/package.json
packages/docusaurus-plugin-ideal-image/package.json
packages/docusaurus-plugin-sitemap/package.json
packages/docusaurus-preset-bootstrap/package.json
packages/docusaurus-preset-classic/package.json
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-search-algolia/package.json
packages/docusaurus/package.json

These changes allow users to pin their version of Docusaurus. If a users `package.json` had the following:
```
"dependencies": {
"@docusaurus/core": "2.0.0-alpha.59",
"@docusaurus/preset-classic": "2.0.0-alpha.59",
...
}
```
They'd expect the version of all `@docusaurus` packages to be `2.0.0-alpha.59`, but that's not the case because for example `packages/docusaurus/package.json` has `"@docusaurus/types": "^2.0.0-alpha.59"` and because of the caret version range `2.0.0-alpha.60` of `@docusaurus/types` is installed.
Yes
Closes #3161

fix(v2): inability for users to pin their docusaurus version

---

packages/docusaurus-mdx-loader/package.json
packages/docusaurus-mdx-loader/src/remark/transformImage/__tests__/__snapshots__/index.test.js.snap
packages/docusaurus-mdx-loader/src/remark/transformImage/index.js
packages/docusaurus/src/constants.ts
packages/docusaurus/src/webpack/utils.ts

Markdown images are converted to webpack requires, but to avoid conflicts when requiring images with the ideal-image plugin, we force an inline loader with the inline loader syntax directly in the require call.
Bug: we used URL loader instead of file loader, that always inline images as base64 in final documents.
We should ensure that our config for those inline loaders are "in sync" with the regular image loaders, so I colocated those.
This is not ideal but good enough, and I don't know to solve the loader conflict with ideal-image without introducing a breaking change somewhere.
Something to discuss: maybe all markdown image tags should go through the ideal image plugin? This is also a behavior change because currently, the user needs to use JSX explicitly to use ideal images.
Yes …

fix(v2): fix markdown images always using webpack url-loader

---

packages/docusaurus/src/commands/build.ts

We should always have a whitespace after the period when there is a following sentence.
Yes
See CI logs to confirm that the whitespace is there.

fix(v2): Add a missing whitespace before prompt to use `npm run serve`

---

packages/docusaurus/package.json

The dependency to `lodash.flatmap` was added in https://github.com/facebook/docusaurus/commit/300aecb8bc87b0f9114cb854b52b91a8004210b9#diff-42a2e682d62828c66fd6c3ed3d4e932e, but wasn't added to `package.json`.
This causes error in Yarn 2:
> Error: @docusaurus/core tried to access lodash.flatmap, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Yes
In the "Start test-website project" step of Yarn 2 E2E test, verify the following error is not printed:
> Error: @docusaurus/core tried to access lodash.flatmap, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
https://github.com/facebook/docusaurus/pull/3191/checks?check_run_id=939419200#step:7:7
Related issue: #3003

fix(v2): add missing `lodash.flatmap` dependency

---

packages/docusaurus-1.x/.eslintrc.js
packages/docusaurus-1.x/examples/basics/pages/en/users.js
packages/docusaurus-1.x/lib/start-server.js
packages/docusaurus-1.x/lib/write-translations.js

Fix https://github.com/facebook/docusaurus/issues/3199

fix(v1): fresh install failing due to <> syntax

---

README.md

Removed extra square brackets on the readme.md to make the resulting plain text uncluttered and readable.
Yes

docs: format reference links

---

packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus/src/commands/swizzle.ts

- Docs should allow swizzling with --typescript
- Improved swizzle suggestion messages
Yes
Manual cli testing
https://github.com/facebook/docusaurus/pull/3021

fix(v2): swizzle minor improvements

---

docs/api-pages.md

https://github.com/facebook/docusaurus/issues/3043
Yes
Change to `api-pages.md` Page Require Paths
As explained by https://github.com/facebook/docusaurus/pull/2464#issuecomment-603802459

docs(v2): clarify theme-original and theme-init

---

packages/docusaurus-init/templates/bootstrap/src/pages/index.js
packages/docusaurus-init/templates/classic/src/pages/index.js
packages/docusaurus-init/templates/facebook/src/pages/index.js

https://github.com/facebook/docusaurus/issues/3257#issuecomment-671877147
Avoid passing a fragment as image alt prop

fix(v2): fix template alt image prop

---

CONTRIBUTING.md

while going through this documentation I discovered few errors, though not conspicuous amazingly I spotted them out.
(I felt inspired to check through this documentation after seeing on twitter the Open Source Immersion Program from Facebook and also due to my love for Open Source I immediately jumped at it)
(Yes.)

docs(v2): docs typos

---

packages/docusaurus-plugin-content-blog/src/__tests__/pluginOptionSchema.test.ts
packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
packages/docusaurus-plugin-content-docs/src/__tests__/pluginOptionSchema.test.ts
packages/docusaurus-plugin-content-docs/src/pluginOptionSchema.ts
packages/docusaurus-utils-validation/src/validationSchemas.ts
packages/docusaurus/package.json

This PR makes some changes related to validation:
- modify validation schema of rehype/remark fields to accept object type. This fixes #3125. Previously, I assumed that remark/rehype plugins could only be function type (AKA [attachers](https://github.com/unifiedjs/unified#function-attacheroptions) in unified's lingo), but this is not exhaustive. It is also possible that rehype/remark plugins are object type.  Based on [unified's documentation](https://github.com/unifiedjs/unified#processoruseplugin-options) and [typescript types](https://github.com/unifiedjs/unified/blob/main/types/index.d.ts#L13), I believe that we have included all the possible types for rehype/remark plugins after adding object type.
- validate babel style user input
- add tests for the above
- remove a duplicate …

fix(v2): modify validation schema and tests for rehype/remark + remove duplicate dependency

---

website/versioned_docs/version-2.0.0-alpha.60/guides/migrating-from-v1-to-v2.md
website/versioned_docs/version-2.0.0-alpha.61/guides/migrating-from-v1-to-v2.md

The migration command is incorrect. This PR fixes the migration command for alpha.60 and alpha.61 docs.
Yes
The changes can be viewed on Netlify 
PR #3249 fixes the migration command for next version of docs.

docs(v2): fix migration command for earlier versions

---

.github/workflows/nodejs-windows.yml

Windows CI fails randomly when executing `yarn`, so let's try to add 2 additional retries and see if it fails less...
https://github.com/facebook/docusaurus/runs/970974830?check_suite_focus=true

chore(v2): windows, 3*yarn install attempts, to avoid timeout failures?

---

package.json
website/src/pages/index.js

Lint staged should call eslint and prettier, but only on modified files, not running on all the files.
This makes committing much faster, as we don't have to wait for 20seconds...

chore(v2): fix slow commits due to lint-staged

---

packages/docusaurus-plugin-content-docs/src/__tests__/slug.test.ts
packages/docusaurus-plugin-content-docs/src/slug.ts
packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts

Fixes https://github.com/facebook/docusaurus/issues/3223
tests

fix(v2): doc path special char (space or other) should lead to a valid slug

---

packages/docusaurus-plugin-google-gtag/src/gtag.js

Closes #3047 
Was following Facebook open-source immersion program, recently did my PR to the [Material UI](https://github.com/mui-org/material-ui) repo, So thought to give a try.
Yes
Followed the [Google Analytics document](https://developers.google.com/analytics/devguides/collection/gtagjs/pages) while implementing pageviews.
Demo site with this change: https://govardhan-srinivas.github.io/docusaurus-blog-mode/
Screenshot of pageviews in google analytics

fix(v2): update pageviews for Google Tag Manager

---

website/src/theme/NotFound.tsx

Closes #2828 
Yes
When accessed directly with a "deep link",  there should not be any hydration problem in feedback, 
`https://{host}/feedback/p/api-documentation-swagger`
Most render the feedback page accordingly.
Moreover, I added the metacharacter `\b` to the regex expression, so it renders the not found page when accessing an incorrect feedback page. This is the current behavior,
`https://v2.docusaurus.io/feedback1/p/api-documentation-swagger` renders,
Expected render,

fix: feedback page hydration

---

packages/docusaurus/package.json
yarn.lock

Upgrade terser-webpack-plugin to pick up serialize-javascript@^3.1.0 due to a new [CVE](https://github.com/advisories/GHSA-hxcc-f52p-wc94).
Yes
Code has passed lint and unit tests.

chore: upgrade terser-webpack-plugin

---

CHANGELOG.md
docs/api-site-config.md
website/docs/blog.md

(I am motivated for being a participant in the Facebook Open Source Immersion Program which encourage newbies, being aware that there are some writing mistakes that content creators commonly make which made me to cross-check some of the documentation of this project.)
(Yes)

docs: corrected some few typos in the docusaurus tech docs

---

packages/docusaurus/src/commands/swizzle.ts

fix(v2): allow swizzling of component even if case doesn't match

---

packages/docusaurus/src/commands/deploy.ts

Closes #3270 
Yes
* `yarn prettier && yarn lint`
* `yarn test`

fix: logic error while deciding deploymentBranch

---

website/docs/deployment.md
website/versioned_docs/version-2.0.0-alpha.61/deployment.md

One small typo fix for docusaurus, one giant leap towards perfectionism.
Yes

docs(v2): fix typo

---

README.md

The README could be explained more clearly with some minor grammatical changes.
Yes, I have read it.

docs: update README.md with some grammatical corrections

---

packages/docusaurus-mdx-loader/package.json
packages/docusaurus-mdx-loader/src/remark/transformImage/__tests__/__snapshots__/index.test.js.snap
packages/docusaurus-mdx-loader/src/remark/transformImage/__tests__/index.test.js
packages/docusaurus-mdx-loader/src/remark/transformImage/index.js
packages/docusaurus-plugin-content-pages/src/index.ts
website/src/pages/examples/markdownPageExample.md

Fixes #3278.
Yes
By adding tests and dog food.

fix(v2): pass images in static dir to webpack-loader

---

packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css
packages/docusaurus-theme-classic/src/theme/TOC/index.tsx
packages/docusaurus-theme-classic/src/theme/TOC/styles.module.css
website/docs/blog.md

As discussed in #2717 thought it would be nice to provide a TOC out of the box for blog posts like v1 did.
Yes
Start a development server and check out the existing blog posts where a TOC is applicable. The TOC can also be toggled off like with docs by adding `hide_table_of_contents` to the header.
N/A

feat(v2): add TOC to blog posts

---

packages/docusaurus-theme-search-algolia/package.json
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
yarn.lock

The Docusaurus navbar remounts at a certain screen resize. This creates new variable references for objects and functions passed to the `DocSearchModal` component, resulting in a rerender of DocSearch that then loses the previous state (because we listen to these reference changes in our component).
This PR keeps references of DocSearch options by using `useMemo` and `useRef`.
Yes.

fix(v2): keep DocSearch state on remounts

---

packages/docusaurus-plugin-client-redirects/src/createRedirectPageContent.ts
packages/docusaurus-theme-search-algolia/src/index.js
packages/docusaurus/src/client/serverEntry.js

ETA has a caching system but reading the doc, it's not totally clear if we leverage it correctly (+ current code did .trim() on each SSR page: useless work)
I just precompiled the templates lazily in a memoize call to see if it can improve build times.
cc @nebrelbug if you can review and tell me what you think. I'm not sure we leveraged Eta caching anyway (despite providing a template name), as the default cache option is not documented here: https://eta.js.org/docs/api/configuration
Do you think this PR has an impact?

refactor(v2): precompile ETA templates

---

packages/docusaurus-module-type-aliases/package.json
packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus/src/client/PendingNavigation.tsx
packages/docusaurus/src/client/exports/Link.tsx
tsconfig.json
website/docs/typescript-support.md
yarn.lock

Improve the TypeScript experience for an out of the box classic template 
Yes
I have a new v2 0.61 project, and this builds the template OOTB with no errors (assuming you merge with master's `packages/docusaurus-module-type-aliases/src/index.d.ts` anyway) - I'll leave notes inline.

chore(v2): tighten up the TypeScript onboarding

---

packages/docusaurus-1.x/lib/core/Head.js
packages/docusaurus/src/client/templates/index.html.template.ejs
packages/docusaurus/src/client/templates/ssr.html.template.js

When viewing my Docusaurus site (https://squirrelly.js.org) on a mobile device, it is correctly sized on first load. Almost immediately after that, however, it resizes so that it isn't the full width of the page (see below). Changing `<meta name="viewport" content="width=device-width">` to `<meta name="viewport" content="width=device-width, initial-scale=1.0">` solves the problem.
Strangely, I can't reproduce the issue on other Docusaurus sites. However, since I believe it's best practice to include `initial-scale=1`, I figured I'd submit the PR anyway.
Yes
Visually ensure that Docusaurus doesn't change its appearance.

fix(v1,v2): Add initial-scale=1.0 to all meta viewport tags

---

docs/guides-blog.md
packages/docusaurus-init/templates/bootstrap/blog/2019-05-28-hola.md
packages/docusaurus-init/templates/bootstrap/blog/2019-05-29-hello-world.md
packages/docusaurus-init/templates/bootstrap/blog/2019-05-30-welcome.md
packages/docusaurus-init/templates/classic/blog/2019-05-28-hola.md
packages/docusaurus-init/templates/classic/blog/2019-05-29-hello-world.md
packages/docusaurus-init/templates/classic/blog/2019-05-30-welcome.md
packages/docusaurus-init/templates/facebook/blog/2019-05-28-hola.md
packages/docusaurus-init/templates/facebook/blog/2019-05-29-hello-world.md
packages/docusaurus-init/templates/facebook/blog/2019-05-30-welcome.md
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/blog/complex-slug.md
packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/blog/simple-slug.md
packages/docusaurus-plugin-content-blog/src/__tests__/__snapshots__/generateBlogFeed.test.ts.snap
packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts

Solving the slug issue raised in issue #3230 
Yes
The code changes affected the interaction with blog post url slugs.
They now operate in the following manner:
- If a `slug` option is not passed:
* If the file name matches the pattern `YYYY-MM-DD-blog-name.md`, the blog will be accessible at  `/blog/YYYY/MM/DD/blog-name`
* Else, the slug is evaluated to be the file name. Example `test-blog.md`, is accessible at `/blog/test-blog`
- If a `slug` option is passed, the slug takes that value. Example `slug: 2020/08/14/test-blog` will be accessible at `/blog/2020/08/14/test-blog`
These changes and different situations were tested manually by using`yarn test:build:v2` which deployed the packages to a local verdaccio server, and created a test-website docusaurus project where I could run different …

feat(v2): blog slug frontmatter

---

packages/docusaurus/src/webpack/base.ts

Fix url-loader not found if the `docs` folder is outside siteDir. Fixes #2724.
Yes
Tested on react-native site migration repo

fix(v2): resolve webpack loaders from siteDir/node_modules

---

packages/docusaurus-mdx-loader/package.json
packages/docusaurus-mdx-loader/src/remark/rightToc/search.js
packages/docusaurus-mdx-loader/tsconfig.json
packages/docusaurus-plugin-content-blog/index.d.ts
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/TOC/index.tsx
packages/docusaurus-types/src/index.d.ts

Add typing for the `rightTOC` in `@docusaurus/types`, so that it can be reference by all plugins and themes.
After this diff, the blog plugin's theme API is fully typed, and we can now correctly type the `@theme/TOC` component. In a future diff, I plan to use the type for the theme API in docs plugin.
Yes
This PR only adds type annotations, so there should be no runtime change.
To test the accuracy of the type, I added types to `@docusaurus/mdx-loader` which first produces the TOC. Then I added the type annotation to `@theme/TOC` component. Both can pass the type checker.

chore(v2): Define type for markdown right table of contents

---

website/community/team.md

This PR adds anshul and myself to the Fellows section of the Team page! 🙂   
(drew and nisarag will probably make a separate PR later)
Yes
The changes can be viewed here: https://deploy-preview-3333--docusaurus-2.netlify.app

docs(v2): add anshul and teikjun to fellows section of team page

---

website/community/team.md

Just adding myself to the Fellows section on the teams page.
Do you think we should add a description for the section or add *MLH Fellows* to the title?

docs(v2): add Drew to Fellows section

---

website/community/team.md

- Re-organize the team pag profiles
- Add description for each section
See preview's /community/team page

docs(v2): update team profile

---

packages/docusaurus-1.x/lib/server/__tests__/utils.test.js
packages/docusaurus-1.x/lib/server/utils.js

When a markdown line starts with a code block (```) and the end of the code block is on the same line, asset images that follow after this line cannot be loaded in the next version of the documentation.
This PR fixes/improves the fenced block detection to consider this scenario.
Yes
- Added unit tests to cover the replaceAssetsLink function
* git clone docusaurus project
* yarn install
* add folder "assets" in /docs directory
* add any image to the assets folder (I copied getting-started-preparation-verify.png from /website-1.x/static/img/ folder)
* add the following text to any markdown file in /docs (line must start with 3 backticks): ```Example (break it)```
* after this line reference the image from the assets folder
* The image is not loaded after the ```Example (break it)``` line …
```

fix(v1): show images after one line code block 

---

packages/docusaurus-theme-classic/src/theme/hooks/useAnnouncementBar.ts
packages/docusaurus-theme-classic/src/validateThemeConfig.js

Fixes https://github.com/facebook/docusaurus/issues/3338

refactor(v2): announcement bar bad spelling + minor refactors

---

packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-docs/src/props.ts
packages/docusaurus-plugin-content-docs/src/slug.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts

Following #3267, this PR adds type definitions for docs plugin.
I moved some type definitions frin `docusaurus-plugin-content-docs/src/types.ts` into a type-exporting-only dummy module `@docusaurus/plugin-content-docs-types` in `docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts`, so that its types can be used by both code in the docs plugin and the module type declaration file. This also allows types defined in `@docusaurus/plugin-content-docs-types` to be used in theme-classic.
Yes
This PR contains no runtime changes. Check CI to see everything type checks.

feat(v2): Provide docs plugin theme typing

---

packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.js
packages/docusaurus-theme-classic/src/validateThemeConfig.js

See
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#Attributes
> Setting this attribute to an empty string (alt="") indicates that
> this image is not a key part of the content (it’s decoration or a
> tracking pixel), and that non-visual browsers may omit it from
> rendering.
Since the logo is indeed decorative and redundant with the actual
project name, an empty alt is fine.
We could also consider just making the attribute optional and defaulting to an empty string, since the logo is going to be redundant with `title` in the general case. I'm happy to update the PR to that, but since just allowing the empty string was the approach described in #3350, I went with that for now.
Fixes #3350.
Yes.
Run the unit tests. Set up a new project, set the alt property for the logo in …

fix(v2): Allow the alt for the logo to be empty

---

.eslintrc.js
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-pages/package.json
packages/docusaurus-plugin-ideal-image/package.json
packages/docusaurus-plugin-pwa/package.json
packages/docusaurus-theme-bootstrap/package.json
packages/docusaurus-theme-search-algolia/package.json
packages/docusaurus-types/src/index.d.ts

This PR adds missing dependencies to relevant package.json and change the eslint lint rule that checks this from warning to error so that we will never regress later.
Note that there is no change in yarn.lock, which shows that the change likely won't cause any node_modules's size increase. Any decent package manager would be able to dedupe all the webpack dependencies into a single on in common cases.
Yes
CI. Preview works.

fix(v2): Add missing dependencies to packages

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts

Continue the work from #3348 to provide type definitions for all remaining theme-classic components. After this PR, theme-classic is now fully typed and we can start recommending users to also include `/// <reference types="@docusaurus/theme-classic" />` in their website's `types.d.ts`, which I will do in another PR.
Yes
Everything type checks.

feat(v2): Provide type definitions for remaining theme-classic components

---

packages/docusaurus/src/commands/start.ts

Add https option in the dev server config, protocol is defined in the config file which can be http or https. Rather than directly checking from process.env we can check from the protocol.
After this change, one can start a dev server over https.
Fixes #3301 
Yes
Running `HTTPS=true yarn start` will start the server and load the website on `https://localhost:3000`

fix(v2): add https support in webpack devserver

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/options.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/versions.test.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-docs/src/props.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-plugin-content-docs/src/versions.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocVersionSuggestions/index.tsx
website/docs/using-plugins.md
website/docs/versioning.md
website/docusaurus.config.js
website/src/pages/versions.js

Implement some low hanging fruits of https://github.com/facebook/docusaurus/issues/3285
Yes
Unit tests 
Dogfooding in dev env and deploy previews with a special config, as it makes more sense to focus on "next version" in those contexts:
```
lastVersion: isDev || isDeployPreview ? 'current' : undefined,
versions: {
current: {
path: isDeployPreview ? 'next-pr' : undefined,
label: isDeployPreview ? 'Next (PR)' : 'Next',
},
},
```

feat(v2): docs version configuration: lastVersion, version.{path,label}

---

packages/docusaurus-plugin-content-docs/src/__tests__/versions.test.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-plugin-content-docs/src/versions.ts
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx
website/docs/using-plugins.md
website/docusaurus.config.js
yarn.lock

Ability to only build a subset of all available versions
It is also possible to include a single specific version, provided dynamically, a first step needed before creating the `docusaurus archive` cli (https://github.com/facebook/docusaurus/issues/3286)
Yes
Unit tests 
Dogfooding on dev/deploy previews, as it would improve DX/startup time + Netlify build time

feat(v2): docs options.onlyIncludeVersions

---

packages/docusaurus-plugin-client-redirects/package.json
packages/docusaurus-plugin-client-redirects/src/normalizePluginOptions.ts
packages/docusaurus-plugin-client-redirects/src/redirectValidation.ts
packages/docusaurus-plugin-content-blog/src/__tests__/pluginOptionSchema.test.ts
packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-pages/src/pluginOptionSchema.ts
packages/docusaurus-utils-validation/package.json
packages/docusaurus-utils-validation/src/validationSchemas.ts
website/docusaurus.config.js

Allowing '' leads to errors (because of https://github.com/facebook/docusaurus/issues/3374)
It is documented to use '/' for docs only, blog only modes, and '' should not be used anyway so I don't consider this to be a breaking change, as users are supposed to follow our recommendations.
I would rather only accept values starting with / (using the Joi PathnameSchema), but that would be a breaking change.
'' was allowed recently but I think it was a mistake:
https://github.com/facebook/docusaurus/pull/3120
https://github.com/facebook/docusaurus/issues/3126

fix(v2): reject routeBasePath: ''

---

website/docs/deployment.md
website/versioned_docs/version-2.0.0-alpha.54/deployment.md
website/versioned_docs/version-2.0.0-alpha.55/deployment.md
website/versioned_docs/version-2.0.0-alpha.56/deployment.md
website/versioned_docs/version-2.0.0-alpha.58/deployment.md
website/versioned_docs/version-2.0.0-alpha.60/deployment.md
website/versioned_docs/version-2.0.0-alpha.61/deployment.md

Hello from the Vercel team!
Just submitting an update to the [Deploy to Vercel](https://v2.docusaurus.io/docs/deployment#deploying-to-vercel) docs.
Will simple Doc fixes require signing a CLA?

Update Deploy to Vercel guide

---

packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts

See https://github.com/facebook/docusaurus/issues/3378
It should be possible to apply data attributes to the scripts tags
Yes
Tests

fix(v2): scripts should allow unknown values

---

packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.js
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/index.tsx
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css
packages/docusaurus-theme-classic/src/validateThemeConfig.js
website/docs/theme-classic.md

User not always should be able to close the announcement bar. The decision should be on the docs creator side.
This PR adds `isCloseable` property to the `theme-classic` announcement bar options, which defaults to `true`, to retain the previous behavior.
The documentation has been also updated within this PR.
I'm open to rename the property, this was the first, good idea which came to my mind. 🙂 
Yes
Change has been tested locally with Docusaurus V2 website. 
* facebook/react-native-website#2139

feat(v2): add isCloseable property for theme-classic announcement bar

---

docs/getting-started-publishing.md
website/versioned_docs/version-2.0.0-alpha.62/deployment.md

Hello from the Vercel team again!
I have added an additional update to the [Deploy to Vercel](https://v2.docusaurus.io/docs/deployment#deploying-to-vercel) docs — it looks like the latest version-2.0.0-alpha.62 is not getting the latest changes I made to previous versions of  Docusaurus 2 documentation. Is this process automated somewhere?
I have also added changes to related docs in the latest Docusaurus 1 documentation.
Yes!

docs(v1, v2): Update Deploy to Vercel guide

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/client/serverEntry.js
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/webpack/server.ts
website/docs/api/docusaurus.config.js.md

This PR adds a new property to `docusaurus.config.js` so the users can specify their own SSR HTML template:
`docusaurus.config.js`:
```javascript
...
ssrTemplate,
...
}
```
Where `ssrTemplate` is a string, such as:
```javascript
const ssrTemplate = `<!DOCTYPE html>
<html <%~ it.htmlAttributes %>>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=0.86, maximum-scale=3.0, minimum-scale=0.86">
<meta name="generator" content="Docusaurus v<%= it.version %>">
<%~ it.headTags %>
<% it.metaAttributes.forEach((metaAttribute) => { %>
<%~ metaAttribute %>
<% }); %>
</head>
<body <%~ it.bodyAttributes %>>
<%~ it.preBodyTags %>
<div id="__docusaurus main-wrapper">
<%~ it.appHtml %>
</div>
<%~ it.postBodyTags %>
</body>
</html>`;
```
This …

feat(v2): allow users to specify a custom ssr HTML template

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-docs/src/props.ts
packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
packages/docusaurus-theme-classic/src/theme/Layout/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
website/docusaurus.config.js

If we are v2 and release v3, using a version:v3 facet will not retrieve any result until the new version is indexed.
By using a constant alias like version:last, we should still be able to search v2 docs before v3 docs are indexed
Should fix https://github.com/facebook/docusaurus/issues/3391
Yes
Tests + deploy preview + next release

fix(v2): DocSearch should keep working after a new release

---

website/docusaurus.config.js

Enable the new versions:latest Algolia search facet after it has been indexed.
Waiting for Algolia indexation to happen.
Follow-up of PR https://github.com/facebook/docusaurus/pull/3393

fix(v2): DocSearch should keep working after a new release (part 2/2)

---

packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.js
packages/docusaurus-theme-classic/src/theme/Layout/index.tsx
packages/docusaurus-theme-classic/src/validateThemeConfig.js
website/docs/theme-classic.md
website/docusaurus.config.js

Generic way to add/override some theme metadatas without swizzling the layout
I particular, ability to override the default value we set for `twitter:card`
```
// ...
themeConfig: {
metadatas: [{name: 'twitter:card', content: 'summary'}],
// ...
},
};
```
fixes https://github.com/facebook/docusaurus/issues/3024
yes
preview

feat(v2): ability to add/override theme html metadatas

---

packages/docusaurus-theme-bootstrap/src/theme/DocPage/index.js
packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx

When rendering sidebar 1, and navigating to a page using sidebar 2, we should unmount/remount sidebar instead of trying to update it in place, or it can mess up with sidebar state.
Should fix https://github.com/facebook/docusaurus/issues/3414
Yes
preview

fix(v2): reset sidebar state on sidebar changes

---

website/src/pages/examples/markdownPageExample.md

Markdown import example in website/src/pages/examples/markdownPageExample.md imports the wrong chapter.
See this comment https://github.com/facebook/docusaurus/commit/f234c407f1f279a76ab388df2bab4f33e8eadf85#r42067403
(Yes)

docs(v2): minor typo fix

---

packages/docusaurus-plugin-sitemap/src/__tests__/createSitemap.test.ts
packages/docusaurus-plugin-sitemap/src/__tests__/pluginOptionSchema.test.ts
packages/docusaurus-plugin-sitemap/src/createSitemap.ts
packages/docusaurus-plugin-sitemap/src/pluginOptionSchema.ts
packages/docusaurus-plugin-sitemap/src/types.ts
website/docs/using-plugins.md

Depending on how the website is hosted, the current sitemap generated by the plugin might create URLs that respond with a `301`. This PR allows the user to generate the sitemap with trailing slashes, making sure that the sitemap will only contain links that respond with `200`.
Yes.
New test for the `trailingSlash` option.
N/A

feat(v2): add option to add trailing slash to urls in sitemap

---

website/versioned_docs/version-2.0.0-alpha.63/markdown-features.mdx

improve grammar about inline SVGs
YES

fix grammar

---

packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css

Refs #3388 
The theme-classic announcement bar CSS style in the media query has not been correctly updated in the mentioned above PR. This results in additional, unnecessary margin on some devices when `isCloseable` property was set to `false`.
Yes
Local run of Docusuaurs V2 website.
* #3388

fix(v2): fix theme-classic announcement bar closeable style

---

packages/docusaurus-plugin-pwa/src/index.js
website/docusaurus.config.js

Apologies, messed up here (#3431 - first attempt at a PR on GitHub) and thought it was best to re-submit.
To ensure that the service worker is correctly referenced on builds on Windows operating systems. I created an issue and described the problem more here - #3420
Added change to docusaurus.config.js as per @slorber's comment [here](https://github.com/facebook/docusaurus/pull/3431#issuecomment-690995916)
I don't think the posix path function in utils is going to strip the drive letter off the path if it was used, so the problem would persist because path.resolve() will always include it and the sw.js should always be relative to the root directory. The posix path function, at least to me, appear to be fixing directory separators.
Yes
Tested on Windows and MacOS.
`yarn start`
N/A

fix(v2): Correctly resolve sw.js path on windows

---

packages/docusaurus-mdx-loader/src/remark/transformLinks/__tests__/__snapshots__/index.test.js.snap
packages/docusaurus-mdx-loader/src/remark/transformLinks/index.js

Fix and improve existing error message when a markdown link is empty
https://github.com/facebook/docusaurus/issues/3309#issuecomment-689595523
After:

fix(v2): fix empty link error message

---

website/static/manifest.json

It currently does not work in deploy previews (while it should) as we moved under baseUrl the classic theme deployment.
I think the manifests paths should be relative instead (need https to test so deploy preview help to test this)
yes
Deploy preview

fix(v2): docusaurus 2 PWA should work under baseurl (deploy previews)

---

website/docs/theme-classic.md
website/versioned_docs/version-2.0.0-alpha.63/theme-classic.md
website/versioned_docs/version-2.0.0-alpha.64/theme-classic.md

Refs #3432
This PR fixes the theme classic navbar style docs. The section has been incorrectly added to the versioned docs instead of current ones (which make the section not visible in the current docs). 
The `alpha-63` changes has been reverted and the section has been added to `alpha-64` and `next` docs.
Yes
Local test run on Docuusuaurus V2 website.
* #3432

chore(v2): fix theme classic navbar style docs

---

website/docs/deployment.md
website/versioned_docs/version-2.0.0-alpha.63/deployment.md
website/versioned_docs/version-2.0.0-alpha.64/deployment.md

- Specified batch command is for cmd
- Added powershell as an option for deployment, changed outer quotes to single in deployment command
- This affects the following versioned docs:
- 2.0.0-alpha.63
- 2.0.0-alpha.64
- Next (Dev)
Refs: #3389
The documentation for deploying in a Windows environment may not be as specific as it needs to be, example issue: #3389. Because of this I have added a powershell command for Windows and have specified that one is for command prompt (title cmd) and the other is for PowerShell (title powershell). 
Yes
1. ran `yarn build`
2. `cd website`
3. `yarn start`
4. Implemented changes
5. Confirmed changes were made on versioned docs specified above
**Current (before changes):**
**Proposed (after changes):**
N/A
(If this PR adds or changes functionality, please …

docs(v2): adding and specifying powershell and cmd for deployment in windows section

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx

Comment above the code says that `We don't want to render a version dropdown with 0 or 1 item`. However, the check below also include the case when we have 2 versions. I believe that this is a bug since we still want to show dropdown when there are two versions.
Yes
Tested locally with only two versions left: current and alpha-64:

fix(v2): Show dropdown instead of a single button when there are two versions

---

packages/docusaurus-plugin-content-pages/src/plugin-content-pages.d.ts
packages/docusaurus-theme-classic/src/theme/Layout/index.tsx
packages/docusaurus-theme-classic/src/theme/MDXPage/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
website/src/pages/examples/markdownPageExample.md

Some custom pages may require different layout or additional customizations to the main page wrapper.
This small PR introduces an ability to specify an optional, custom `wrapperClassName` to the theme classic `Layout` component.
I have **NOT** updated the docs because I was not able to find the page which describes all other optional `Layout` props. ["Theme classic"](https://v2.docusaurus.io/docs/theme-classic) and ["Creating pages"](https://v2.docusaurus.io/docs/creating-pages) only briefly mention `Layout` usage. The most properties is used in the ["Migration guide"](https://v2.docusaurus.io/docs/migrating-from-v1-to-v2#pages) but still without a description.
I can add the note about this feature if you will be able to tell me where to put it. Alternatively, I can (in a later time) try …

feat(v2): add optional custom wrapper class name for pages based on theme classic Layout

---

packages/docusaurus/bin/docusaurus.js

Right now `docusaurus serve my-dir` doesn't work because it's not registered as an internal command, thus always forced to invoked w/ `path.resolve('.')`. This fixes that
Yes
Manually verified in formatjs

fix: add serve to internalCommand

---

website/docs/cli.md
website/docs/deployment.md
website/versioned_docs/version-2.0.0-alpha.60/cli.md
website/versioned_docs/version-2.0.0-alpha.60/deployment.md
website/versioned_docs/version-2.0.0-alpha.61/cli.md
website/versioned_docs/version-2.0.0-alpha.61/deployment.md
website/versioned_docs/version-2.0.0-alpha.62/cli.md
website/versioned_docs/version-2.0.0-alpha.62/deployment.md
website/versioned_docs/version-2.0.0-alpha.63/cli.md
website/versioned_docs/version-2.0.0-alpha.63/deployment.md
website/versioned_docs/version-2.0.0-alpha.64/cli.md
website/versioned_docs/version-2.0.0-alpha.64/deployment.md

There is a small typo in website/docs/cli.md, website/docs/deployment.md, website/versioned_docs/version-2.0.0-alpha.60/cli.md, website/versioned_docs/version-2.0.0-alpha.60/deployment.md, website/versioned_docs/version-2.0.0-alpha.61/cli.md, website/versioned_docs/version-2.0.0-alpha.61/deployment.md, website/versioned_docs/version-2.0.0-alpha.62/cli.md, website/versioned_docs/version-2.0.0-alpha.62/deployment.md, website/versioned_docs/version-2.0.0-alpha.63/cli.md, website/versioned_docs/version-2.0.0-alpha.63/deployment.md, website/versioned_docs/version-2.0.0-alpha.64/cli.md, website/versioned_docs/version-2.0.0-alpha.64/deployment.md.
Should read `locally` rather than `localy`.

docs: Fix simple typo, localy -> locally

---

packages/docusaurus/src/server/themes/index.ts

Swizzled components currently do not have access to `@theme-init` components as it has been introduced in PR[#2464](https://github.com/facebook/docusaurus/pull/2464) for Docusaurus components.
Having access to initial theme components allows overriding default components without having to rewrite the entire component.
This PR extend the initial PR for providing access to `@theme-init` components for custom components.
The point has been raised on the Discord channel [#docusaurus-2-dogfooding](https://discordapp.com/channels/398180168688074762/567414046073159701/718010716527001690).
Yes
Tested with a local instance and a custom code block:
```jsx 
import CodeBlock from '@theme-init/CodeBlock'; // access to initial theme Codeblock
const TryQueryLink = ({ gql, text …
```

feat(v2): Add @theme-init components to user theme

---

packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.js
packages/docusaurus-theme-classic/src/index.js
packages/docusaurus-theme-classic/src/validateThemeConfig.js
website/docs/configuration.md
website/docs/guides/migrating-from-v1-to-v2.md
website/docs/presets.md
website/docs/styling-layout.md
website/docusaurus.config.js

This small PR fixes the issue with server build when array of files was specified in `customCss` field in the theme classic preset configuration.
CC @slorber 
Yes
Successful server build of React Native website with multiple files in `customCss`.
* https://github.com/react-native-website-migration/react-native-website/issues/23

feat(v2): allow to use array of files in customCss field

---

packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-blog/src/types.ts
packages/docusaurus-plugin-content-docs/src/__tests__/options.test.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-plugin-content-pages/src/index.ts
packages/docusaurus-plugin-content-pages/src/pluginOptionSchema.ts
packages/docusaurus-plugin-content-pages/src/types.ts
website/docs/using-plugins.md

Closes #3437 
This PR fixes the use of the options `beforeDefaultRemarkPlugins ` and `beforeDefaultRehypePlugins` inside `plugin-content-docs` and `plugin-content-bloc` (the options were not loaded in the `@docusaurus/mdx-loader`).
It also adds these options for the plugin `plugin-content-pages`.
Yes
I would like some help on how to test if my code is working correctly.
Theoretically it should work but I would like to be able to test it with a real scenario.

feat(v2): add beforeDefaultRemarkPlugins/beforeDefaultRehypePlugins options to all md content plugins

---

packages/docusaurus/src/webpack/base.ts

Do not run Terser in parallel when using CircleCI or similar CI environments
to avoid "Error: Call retries were exceeded" errors. For more information
see https://github.com/webpack-contrib/terser-webpack-plugin#parallel
`CI=true` is true for:
- https://docs.gitlab.com/ee/ci/variables/#debug-logging
- https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables
- https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
- https://docs.travis-ci.com/user/environment-variables/
yes
None - hard to test because certain conditions need to be met and because it's not possible to replicate those easily without a published package.

feat(v2): env variable TERSER_PARALLEL to customize TerserPlugin.parallel

---

packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts

This PR fixes edge cases for the `normalizeUrl` util function like the ones introduced in the unit tests.
Yes
This PR fixes #3374 and undo #3377.
New unit tests added: 
```
{
input: ['/', ''],
output: '/',
},
{
input: ['', '/'],
output: '/',
},
{
input: ['/'],
output: '/',
},
{
input: [''],
output: '',
}
```
The thing was that for each part of our `rawUrls` (except for the last one)  we removed the `/` in:
```
component.replace(/[/]+$/, i < urls.length - 1 ? '' : ‘/‘)
```
I added a condition to check if the current element is a slash and if so we can continue the process.
Here is the **new logic inside our for loop**:
<p align="center">
</p>
Another workaround would be to add a condition to the returned string like: `return str === '' ? '/'  : str` as I think this change target only an …

fix(v2): normalizeUrl edge cases

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

Fix HTML error reported by Rocket Validator:
> Bad value “true” for attribute “crossorigin” on element “link”. Found 20 times on this site.
See https://webmasters.stackexchange.com/questions/89466/when-should-i-use-the-crossorigin-attribute-on-a-preconnect-link for more details.
Yes
Preview.

fix(v2): use valid value for crossorigin attribute

---

packages/docusaurus-utils-validation/src/__tests__/__snapshots__/validationSchemas.test.ts.snap
packages/docusaurus-utils-validation/src/__tests__/validationSchemas.test.ts
packages/docusaurus-utils-validation/src/validationSchemas.ts

Currently, **relative links** are invalid when configuring **navbar items**.
We currently run our documentation at a sub-path of our top level domain, `https://example.org/docs`. For the **logo**, it is valid to add a relative link up to our homepage:
```js
themeConfig: {
navbar: {
logo: {
href: "..",
target: "_top",
src: 'img/logo_black.svg',
srcDark: 'img/logo_white.svg',
}
...
```
This behaves well, linking up to the relative parent page and forcing a full page reload.
I would also like the following configuration to be valid, for navbar **items**:
```js
themeConfig: {
navbar: {
items: [{
href: "../sibling_path",
target: "_top",
label: "Sibling Application",
position: "right"
}]
...
```
This is currently not possible to achieve within …

fix(v2): allow relative URLs in URISchema

---

docs/api-pages.md
packages/docusaurus/src/server/themes/__tests__/alias.test.ts
packages/docusaurus/src/server/themes/alias.ts
packages/docusaurus/src/server/themes/index.ts
website/docs/using-themes.md

Write some doc for `@theme-original` and `@theme-init`.
Also remove the existing doc that was wrongly added to v1 here: https://github.com/facebook/docusaurus/pull/3111
Fixes #3043

docs(v2): add doc for wrapping theme components with @theme-original and @theme-init

---

packages/docusaurus/src/commands/deploy.ts

The user should be able to get the real env variable names to use from the error message, otherwise, it's confusing.

fix(v2): DX deploy error messages should print effective env variables names

---

website/docusaurus.config.js

By default, in prod, the "latest version" is the last release, not "next".
This lead to the editUrl targeting docs of a specific version, not upstream docs. 
This leads to maintainers asking to port the doc fixes to upstream docs, and sometimes merging by mistake to the versioned docs, so the doc fix would disappear.
Here is an example: https://github.com/facebook/docusaurus/pull/3428#issuecomment-700158389
By defaulting to the next version in prod, we nudge contributors and maintainers to contribute to upstream docs in priority.
The label `(unreleased)` can help make it obvious that it's the doc for an unreleased version, so that the user can switch if needed. 
But anyway, between one alpha to another, the docs do not change that much, so I think this new behavior is fine for the whole …

chore(v2): v2 website should make it easy to contribute to upstream docs

---

packages/docusaurus/src/webpack/base.ts

Without comma option `-prettier-svgo` is parsed as `'prettier-svgo': false`
Fix problems that svgo introduces when inlining SVG pictures.
yes
Pretty print options are consumed by `@svgr` directly in node_modules/ directory.

fix(v2): fixed props being passed to @svgr/webpack loader

---

.gitignore
package.json
website-1.x/languages.js
website-1.x/netlifyUtils.js
website-1.x/siteConfig.js
website/netlifyDeployPreview/_redirects
website/netlifyDeployPreview/index.html
website/package.json

A simple v1 deploy preview should be available to review v1 PRs.
As we have multiple deploy previews now we can more easily include v1.
With only English, and only a minimal amount of version it does not increase deploy preview time significantly

fix(v1): v1 deploy preview should be available

---

packages/docusaurus-plugin-content-pages/src/plugin-content-pages.d.ts
packages/docusaurus-theme-classic/src/theme/MDXPage/index.tsx
website/docs/guides/creating-pages.md

Add TOC feature parity to all markdown pages (docs, blog and pages)
Low hanging fruit, requested by @Simek for ReactNative website.

feat(v2): add TOC to markdown pages

---

website-1.x/docs/guides-search.md

(Fixing broken link in the docs so as to enable easy navigation and easy reading for others.)
(Fixing of dead links within the documentation)
(Yes)

docs(v1): Fix broken link in the documentation

---

package.json
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/commands/commandUtils.ts
packages/docusaurus/src/commands/serve.ts
packages/docusaurus/src/commands/start.ts
website/package.json

The command `serve` was not equipped to handle the value of port being `null`. 
Also there was a typing mismatch where `port` input from CLI (`string`) was type-casted as a `number`.   
Yes.
The expected behavior can be seen here. 
Fixes issue #3505 .

fix(v2): Fixes serve cli --port option

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/globalData.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-classic/src/validateThemeConfig.js
website/docs/theme-classic.md
website/docusaurus.config.js
website/sidebars.js
website/src/css/custom.css
website/versioned_sidebars/version-2.0.0-alpha.65-sidebars.json

Ability to link to a doc from the navbar, and have the link have a `doc-sidebar-active` class whenever that doc's  sidebar is active.
This makes it possible to have tab-like navigation, see  ReactNative  website:
Note, in v1 this feature existed already with a quite similar API:
fixed https://github.com/facebook/docusaurus/issues/3320
Note: should we use this on Docusaurus website? 
I've done so but maybe I should revert. 
We should think better about how to organize v2 docs.
yes
Tests, preview and dogfooding

feat(v2): doc navbar item type

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/client/client-lifecycles-dispatcher.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/server/index.ts
website/docs/api/docusaurus.config.js.md
website/docs/lifecycle-apis.md
website/docusaurus.config.js
website/dogfooding/clientModuleExample.ts

As of today, it's a bit boilerplaty to add some global JS to a site, as you need to create a local site plugin to implement getClientModules.
The following option makes it more idiomatic as you can directly pass the client modules as a config attribute:
`siteConfig.clientModules = [myGlobalJsPath, myGlobalCssPath]`
See also RN website PR: https://github.com/react-native-website-migration/react-native-website/pull/31/commits/b75a0e6ba1d82c53b6c0df054acb52e19324bd46#diff-20b869a62a5a74fb46c979edc17980f6R1-R19
Yes

feat(v2): site client modules

---

packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.js
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-classic/src/validateThemeConfig.js
packages/docusaurus/src/client/exports/Link.tsx
website/docs/theme-classic.md
website/docusaurus.config.js

Our own site navbar is becoming crowded.
Nesting the "All Versions" link inside the dropdown permits to remove more easily a useless navbar element.
I also see this as a possible way to link to older archived versions that are not in Docusaurus site anymore. 
For example, the RN website has 64+ versions, but it's not manageable to keep so much versions, so we can only keep recent versions in Docusaurus, but still be able to link to older ones (published as standalone immutable sites).
cc @lex111 @Simek 
Yes
Preview + dogfooding

feat(v2): version dropdown before/after items + move site "All Versions" link

---

website/docusaurus.config.js

If you visit any page other than the home page, for example https://v2.docusaurus.io/docs/, then you can see the following error in the console:
> Failed to load resource: the server responded with a status of 404 ()   manifest.json
Or something like this:
> Manifest: Line: 1, column: 1, Syntax error.
Yes
Preview (see motivation section).

fix(v2): use absolute path to manifest file

---

website/package.json
website/src/pages/examples/_myComponent.js
website/src/pages/examples/markdownPageExample.md
yarn.lock

Demonstrate the ability to do so, as @JoelMarcey asked me if it was possible.
Demo here: https://deploy-preview-3558--docusaurus-2.netlify.app/classic/examples/markdownpageexample/#import-code-block-from-source-code-file

docs(v2): embedding real source code in MDX as a code block

---

website-1.x/core/Showcase.js
website-1.x/data/users.js
website/src/data/users.js

Ensure we never accept a remote url as showcase image on Docusaurus sites, as remote URLs are likely to break over time.
(example: https://github.com/facebook/docusaurus/pull/3556#pullrequestreview-504664603)

feat(v2): prevent using remote image urls in showcase

---

packages/docusaurus-theme-classic/src/__tests__/utils.test.js
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx
packages/docusaurus-theme-classic/src/utils/index.ts

Currently on mobiles we have a dropdown menu always in an open state, which is a bit strange.
I suggest to make dropdown collapsed by default (expected behavior by analogy as desktop), and also always auto expanded when browsing active URL from dropdown items.
Yes
| ![image](https://user-images.githubusercontent.com/4408379/95390241-c16fa680-08fd-11eb-9139-5e20148c53aa.png) | ![image](https://user-images.githubusercontent.com/4408379/95390208-b74da800-08fd-11eb-9f24-a5495b4be59e.png) |

 feat(v2): make dropdown menu collapsible on mobiles

---

packages/docusaurus/src/server/__tests__/__snapshots__/brokenLinks.test.ts.snap
packages/docusaurus/src/server/__tests__/brokenLinks.test.ts
packages/docusaurus/src/server/brokenLinks.ts

Not the first time it happens but users think this broken link feature is a bug, and don't know what to do about it.
They also miss the ability to disable this broken links detection feature at the bottom of the error.
Adding more instructions at the beginning should fix it.
See also https://github.com/facebook/docusaurus/issues/3567

refactor(v2): improve broken links error message

---

website/docs/deployment.md

Fixes #3189
Fix #3189 - clarify the necessary 'scope' required on the personal access token for deploying to GitHub pages through both Travis CI and Azure Pipelines
Yes!
Because this is a documentation-only change, I haven't done any testing on the software itself. However, I performed manual testing to ensure the documentation change listed here is correct. The testing included:  
* Creating a test Docusaurus repository
* Creating a personal access token
* Testing using different 'scopes' on the personal access token
* Noted the minimum 'scope' required to successfully deploy
* Deploying successfully to GitHub pages
N/A

docs(v2): deployment, add required Github token scope infos

---

packages/docusaurus-plugin-content-blog/index.d.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
packages/docusaurus-plugin-content-blog/src/types.ts
packages/docusaurus-theme-bootstrap/src/theme/BlogListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogListPage/index.tsx
website/docs/blog.md
website/docs/using-plugins.md

Fixing the issue raised within #3542
Yes
- run `yarn start`
- navigate to 'blog' page
- check the title has been updated with `blog title` rather than previous `blog`
- stop project from running
- change the blog title within the blog config
- restart docusarus
- navigate to 'blog' page
- check blog title has changed
#3542

feat(v2): add option for blog meta title

---

website/src/pages/versions.js

refactor(v2): clarify versions page

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
website/docs/markdown-features.mdx
website/src/css/custom.css

Currently `Tabs` are manually added by the users to the docs pages, but the customization (without introducing additional wrapper) is limited to the "block" and "non-block" appearance. 
This simple PR adds the ability to pass `className` prop to Tabs, which if present, will be added at the end of class chain providing the users simple, unique CSS hook to customize the styling of selected Tabs block.
I have also added a small section about this feature to the docs on the Markdown Features page. It includes a brief description and an example usage (which required to add CSS to the `custom.css` file), here's the preview:
Yes
Docusuaurs V2 website running locally with the added in example on the Markdown Feature page.
N/A

feat(v2): allow to define custom CSS class for Tabs component

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx

I suggest changing the behavior of navbar dropdowns to make it more predictable and standardized.
- First, we always make a non-clickable link that opens the dropdown itself.
- Secondly, when accessing from the keyboard, dropdown is opened **only** when we press the _Enter_ button. This is consistent with the recommendations of [a11y](https://www.w3.org/WAI/tutorials/menus/flyout/), and it's just convenient because we don't have to go through all the child items in dropdown to get to the next navbar item.
FYI, Bootstrap dropdowns works in a similar way, you can look at the Doctrine website (for example) - https://www.doctrine-project.org/
BTW, this PR fixes the annoying bug where we cannot navigate back to the previous navbar items using the keyboard.
Yes
Current behavior (dropdown opens …

refactor(v2): apply common behavior to dropdowns

---

package.json
yarn.lock

Don't know what's happening exactly but can't get TS to work locally anymore due to React types.
Had a weird undesired yarn lock update in a former PR merged recently.
Upgraded the React types, as it's harmless, seems to work and fixes my problem

chore(v2): fix/upgrade react types

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
website/docusaurus.config.js

Enable contextual search (https://github.com/facebook/docusaurus/pull/3550) on our own website.
Done in 2 phases because we need to wait for Algolia crawlers to run

chore(v2): enable new contextual search feature

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css

Currently, code blocks are indicated as interactive elements (using `tabIndex="0"`), which is wrong and completely unnecessary. Instead that, we need to make the copy code button accessible from keyboard (see test plan).
Yes
| ![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/4408379/96041768-04d59200-0e75-11eb-82bb-65d1f922ebea.gif) | ![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/4408379/96041817-1880f880-0e75-11eb-8412-f5f5e1996a5d.gif) |

refactor(v2): make accessible copy code button from keyboard

---

packages/docusaurus-theme-classic/src/__tests__/utils.test.js
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx
packages/docusaurus/src/client/templates/ssr.html.template.js
website-1.x/data/users.js
website/docs/api/docusaurus.config.js.md
website/docs/lifecycle-apis.md
website/docs/theme-classic.md
website/src/data/users.js
website/static/manifest.json

refactor(v2): various fixes

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.js
packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-classic/src/validateThemeConfig.js
yarn.lock

- Fix code style
- Drop `use-onclickoutside` dep in favor of own realization
- Fix bug with opening/closing dropdown menu by pressing Enter key (follow-up #3578)
- Remove invalid attr `position` from final markup (similar to #2765)
Yes
Preview.

refactor(v2): various dropdown improvements

---

packages/docusaurus-theme-bootstrap/src/theme/Tabs/index.tsx
packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx

The following warning is currently displayed in the console when using tabs:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function. in Tabs (created by MDXCreateElement)
```
To get rid of this error we need to remove the event listeners.
Yes
Preview.

fix(v2): remove event listeners on Tabs component unmount

---

packages/docusaurus-plugin-content-blog/index.d.ts
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-blog/src/__tests__/pluginOptionSchema.test.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
packages/docusaurus-plugin-content-blog/src/types.ts
packages/docusaurus-theme-classic/src/theme/BlogListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogSidebar/styles.module.css
packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.tsx
website/docs/using-plugins.md
website/docusaurus.config.js

Feature parity with Docusaurus v1.
https://docusaurus.io/docs/en/adding-blog#changing-how-many-blog-posts-show-on-sidebar
Needed for RN migration, cc @Simek 
yes
tests + preview + dogfooding

feat(v2): blog sidebar

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx
packages/docusaurus/src/client/exports/Link.tsx

Currently, the versions dropdown link on mobiles lacks the required attribute  `href`, about this HTML error reported Rocket Validator:
> Element “a” is missing required attribute “href”.
> `...ollapsed"><a target="_blank" rel="noopener noreferrer" class="menu__link menu__link--sublist">Versions`
To get rid of this error, we need to set ARIA role on the link.
Also in this PR I fixed adding redundant attributes (`target="_blank" rel="noopener noreferrer"`) if `to`/`href` prop not passed.
Yes
Preview.

fix(v2): fix error with required href attr of link in mobiles

---

packages/docusaurus/src/client/serverEntry.js

Put bad markup in a MDX file:
On build, you get this kind of unactionable error:
To make this error more actionable, we should log the page path for which we couldn't render:
yes
local test

refactor(v2): Improve SSR error message: log page path

---

website/community/resources.md

Add a community plugin of [@easyops-cn/docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local).
This plugin is originally forked from cmfcmf/docusaurus-search-local, but later fully rewritten to reach our goal: up to date, maintainable, robustness, pretty look, and mostly language of Chinese supported.
We have already using it in our production, hope it will help others.
Yes.
N/A.
No.

docs(v2): add a community plugin

---

packages/docusaurus-theme-classic/src/theme/hooks/useLogo.ts
packages/docusaurus-theme-classic/src/validateThemeConfig.js

Fix #3610.
Yes
Comment out the `logo` field in docusaurus website's docusaurus.config.js, like:
```js
// ...
navbar: {
hideOnScroll: true,
title: 'Docusaurus',
/* logo: {
alt: 'Docusaurus Logo',
src: 'img/docusaurus.svg',
srcDark: 'img/docusaurus_keytar.svg',
},
*/
// ...
}
```
Without this change, site will crash:
With this change, site will load as usual, without the logo:
N/A

fix(v2): Added back support for optional logo field in theme-classic navbarConfig

---

packages/docusaurus/src/client/serverEntry.js

Help users find the issue/workaround for a weird temporary Yarn monorepo/workspace dependency resolution issue.
This way, we have less support to do until it's fixed
https://github.com/facebook/docusaurus/issues/3515

refactor(v2): add better error message for yarn workspace/monorepo/terser issue 

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css
packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx

Currently, in Infima we have height transition CSS property, but it won't work unless the element's height is explicitly specified.
This PR sets the dropdown height at click time so that the CSS transition can work as expected.
The desktop implementation looks trickier because we can have nested dropdowns, so the final height can be dynamic (depending on whether the nested dropdown is expanded or collapsed).
Yes
Preview.
| Desktop   | Mobile    |
| ![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/4408379/96322374-73efe980-1021-11eb-8db7-97714b24586c.gif) | ![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/4408379/96322376-77837080-1021-11eb-9f3e-6cc4802ba67f.gif) |
(If this PR adds or changes functionality, please take some …

fix(v2): animate dropdown properly

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/server/__tests__/__snapshots__/config.test.ts.snap
packages/docusaurus/src/server/config.ts
website/docs/cli.md

Fixes https://github.com/facebook/docusaurus/issues/3620
`docusaurus start --poll 500` should accept 500 as poll interval value
Also we should use polling for both webpack dev server and chokidar file watchers
Also improve the error message in such weird case so that user can understand we try to load the config from `500/docusaurus.config.js`  and that 500 is interpreted as the cli siteDir arg.
yes
Local test and checking the correct args are forwarded to Webpack config
```
yarn start:v2
yarn start:v2 --poll
yarn start:v2 --poll 500
```

fix(v2): docusaurus start --poll 500 should work + better config load failure error

---

website/docs/using-plugins.md
website/docs/versioning.md
website/versioned_docs/version-2.0.0-alpha.66/using-plugins.md
website/versioned_docs/version-2.0.0-alpha.66/versioning.md

Fixed some misspellings in documentation.
Participation in documentation due to Hacktoberfest.
I'll check out the Contributing Guidelines.

docs(v2): fix some misspellings

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css

Currently code blocks with scrollbars are cut off on print. They should be wrapped instead.
Fixes #3633. 
Yes
Preview
Before:
After:

fix(v2): wrap code blocks on print

---

admin/scripts/test-release.sh

Currently, in test release script Docker container never stops due to Bash error:
> KEEP_CONTAINER: unbound variable
> error Command failed with exit code 1.
Yes
- `yarn test:build:v2` - Docker container will stop
- `KEEP_CONTAINER=true yarn test:build:v2` - Docker container won't stop

misc: fix unbound env variable in test release script

---

packages/docusaurus-theme-classic/src/theme/Layout/index.tsx
packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx
packages/docusaurus-theme-classic/src/theme/SkipToContent/styles.module.css

Improve keyboard users experience by adding a shortcut to navigate to main content.
This feature is described in more detail here https://www.w3.org/TR/WCAG20-TECHS/G1.html and here https://webaim.org/techniques/skipnav/
Yes
- Go to the preview website.
- Hit the tab key
- Press the tab key again to make sure the focus is on main content.
Demo:

feat(v2): add skip to content link

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css

When the doc sidebar is hidden, we shouldn't be able to navigate through the menu items from the keyboard (by pressing Tab key).
Follow-up of #3615 
Yes
Preview.

fix(v2): disable tabbing on hidden doc sidebar

---

packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.js

PR #3604 broke the infinite scroll pagination functionality on the search page, because the page is always 0. To fix it we first need set facet refinements, and then query, page, etc.
Yes
Preview.

fix(v2): restore infinite scroll pagination on search page

---

website/docs/lifecycle-apis.md

Update documentation for migrating hapi/joi to joi. reference https://github.com/facebook/docusaurus/pull/3638.
Yes.

docs(v2): update the link of joi

---

packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx

In #3640 I added skip to content link, but did not validate this feature from a11y point of view. Using Rocket Validator, I found out the following related issue:
> All page content must be contained by landmarks
> `<button type="button" tabindex="0" class="skipToContent_3oI8">Skip to main content</button>`
Yes
Preview.

fix(v2): add landmark for skip to content link

---

website-1.x/docs/tutorial-version.md

The file generated when you run `npm run examples versions` is a versions.json file and not a version.js file

docs(v1): fix typo on Add Versions doc page

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx

Follow-up of #3603.
Fix HTML issue reported by Rocket Validator (_CSS: “height”: Too many values or values are not recognized_)
> `rsions</a><ul class="menu__list" style="height:undefinedpx"><li cl`
Explanation: this happens because during the build website currently calculate mobile dropdown  height for work of CSS transition, but the element does not exist on prerendering, so we get `undefined`.
Yes
Preview (see source code)

fix(v2): do not set height for mobile dropdown during build

---

packages/docusaurus-theme-classic/src/validateThemeConfig.js

Since the footer link item can only consist of raw HTML code, it makes sense to remove the required title for a footer column.
For example, the Gulp.js website [uses that feature](https://github.com/gulpjs/gulpjs.github.io/blob/source/docusaurus.config.js#L69-L75) to add a logo, but they can't update to the latest Docusaurus because the footer title is required to specify (more precisely, this is one reason why it is impossible to upgrade, see [the comment](https://github.com/gulpjs/gulpjs.github.io/issues/123#issuecomment-718696325) for more details).
Yes
Remove title from footer link item, and make sure that the site start without validation errors.
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to …

fix(v2): make optional title for footer links column

---

packages/docusaurus-init/templates/bootstrap/docusaurus.config.js
packages/docusaurus-init/templates/classic/docusaurus.config.js
packages/docusaurus-init/templates/facebook/docusaurus.config.js
packages/docusaurus-migrate/src/__tests__/__fixtures__/expectedSiteConfig.js
packages/docusaurus-migrate/src/index.ts
packages/docusaurus-migrate/src/types.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus-utils/package.json
packages/docusaurus-utils/src/index.ts
packages/docusaurus/src/server/__tests__/__snapshots__/config.test.ts.snap
packages/docusaurus/src/server/brokenLinks.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/server/duplicateRoutes.ts
packages/docusaurus/src/server/utils.ts
website/docs/api/docusaurus.config.js.md
website/docusaurus.config-blog-only.js
website/docusaurus.config.js
website/versioned_docs/version-2.0.0-alpha.66/api/docusaurus.config.js.md

Fixing issue #3652 
We have a website which uses Docusaurus v2, and recently, we are letting people to contribute to the project and translate existing pages to their own language in separate folders; This means relative markdown links are still there in newly translated pages while those pages might not exist in the language's folder (as I mentioned, those links are relatively written there)
An example of this behaviour would be this: [Click Here](https://wiki.open.mp/docs/translations/tr/scripting/functions/AddMenuItem#i%CC%87lgili-fonksiyonlar), and first item of that list does not exist. This was just an example that leads to printing only one error to stdout, for the real issue please refer to #3652
And at the end, there was a comment there saying this: …

feat(v2): onBrokenMarkdownLinks config

---

packages/docusaurus-theme-classic/src/theme/BlogSidebar/styles.module.css

Closes #3628.
Makes the blog sidebar scrollbar the same as the docs sidebar scrollbar.
Yes.
Preview:
<br>
No related PRs.

fix(v2): make scrollbar styles consistent

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx

Sort+quick code
Yes
I create simple benchmark:
```js
const str = 'something include title="...."';
const oldRegex = /title=".*"/;
const newRegex = /(?<=title=").*(?=")/;
const old = (str) => str.match(oldRegex)[0].split('title=')[1].replace(/"+/g, '');
const newF = (str) => str.match(newRegex)[0];
```
result: two function return same value
- sort `str`:
- `old` x 2,411,252 ops/sec ±0.38% (90 runs sampled)
- `newF` x 12,002,531 ops/sec ±0.44% (92 runs sampled)
- long `str`:
- `old` x 1,569,985 ops/sec ±0.44% (92 runs sampled)
- `newF` x 3,442,088 ops/sec ±0.43% (91 runs sampled)

refactor(v2):regex match title

---

.github/workflows/e2e-test.yml

Test for #3324.
~I'm not sure this is worth testing in the e2e test.~
Yes
Check GitHub Actions pass.
N/A

test(e2e): dogfood Yarn with enableGlobalCache

---

packages/docusaurus-mdx-loader/package.json
packages/docusaurus-plugin-google-analytics/package.json
packages/docusaurus-plugin-google-gtag/package.json
packages/docusaurus-plugin-sitemap/package.json

- `mdx-loader`, `plugin-google-analytics`, `plugin-google-gtag`, and `docusaurus-plugin-sitemap` depends on `@docusaurus/core`, which peer-depends on `react` and `react-dom` (`@mdx-js/react` peer-depends on `react@^16.13.1`)
- `mdx-loader` depends on `file-loader` and `url-loader`, which peer-depends on `webpack`
so they should be listed as peer dependencies.
Note other packages also list them as peer dependencies: https://github.com/facebook/docusaurus/blob/32425497f7f6251ad34ca9ca56db1eed9e7a97d7/packages/docusaurus-plugin-debug/package.json#L25-L28
Yes
Check following warnings are not shown in Yarn 2 E2E test (https://github.com/facebook/docusaurus/pull/3675/checks?check_run_id=1343372025#step:6:308):
```
➤ YN0002: │ …
```

fix(v2): add missing 'react' and 'webpack' peer dependencies

---

packages/docusaurus-theme-classic/src/theme/BlogListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.tsx

Additional wrapper class name, specific only to the blog related pages, should make easier for developers to introduce the CSS tweaks that should only be related to the Blog pages.
Yes
I have tested this change using Docusaurus V2 website locally:
None?

feat(v2): add additional wrapper class to blog pages

---

packages/docusaurus-theme-classic/src/__tests__/utils.test.js
packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx
packages/docusaurus-theme-classic/src/utils/index.ts

According to the docs, you can create a [dropdown](https://v2.docusaurus.io/docs/2.0.0-alpha.66/theme-classic/#navbar-dropdown) in the Navbar. With alpha.66 this fails because there's a path normalizer, which doesn't handle undefined if Navbar item is dropdown instead of a link which has a path.
Yes and already contributed once.
I've written a test:
```js
test('should not fail if path is "undefined" when it is absent in case of dropdown in Navbar ', () => {
expect(isSamePath(undefined, undefined)).toBeTruthy();
});
```
Before my fix:
After my fix:
This fix actually makes docs relevant as currently, dropdown wouldn't work.

fix(v2): navbar dropdown crash when item.to is undefined

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx

Reverts facebook/docusaurus#3671
Fixes #3680 (see https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group for more details)

Revert "refactor(v2): improve regex matching code-block title"

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx

#3671 can't work with Safari, this PR to fix it(still quickly+sort code)
Yes
Tested with Safari
#3671

refactor(v2): improve regex matching code-block title

---

website/package.json
yarn.lock

V2 website scripts in current form do not work on Windows:
This PR fixes that problem by utilizing the [`cross-env`](https://github.com/kentcdodds/cross-env) package.
Yes.
Changes has been tested on Windows and macOS device.
No.

fix(v2): fix website scripts on Windows by using cross-env

---

website/docs/cli.md
website/docs/configuration.md
website/docs/deployment.mdx
website/docs/installation.md
website/versioned_docs/version-2.0.0-alpha.63/cli.md
website/versioned_docs/version-2.0.0-alpha.63/configuration.md
website/versioned_docs/version-2.0.0-alpha.63/deployment.mdx
website/versioned_docs/version-2.0.0-alpha.63/installation.md
website/versioned_docs/version-2.0.0-alpha.64/cli.md
website/versioned_docs/version-2.0.0-alpha.64/configuration.md
website/versioned_docs/version-2.0.0-alpha.64/deployment.mdx
website/versioned_docs/version-2.0.0-alpha.64/installation.md
website/versioned_docs/version-2.0.0-alpha.65/cli.md
website/versioned_docs/version-2.0.0-alpha.65/configuration.md
website/versioned_docs/version-2.0.0-alpha.65/deployment.mdx
website/versioned_docs/version-2.0.0-alpha.65/installation.md
website/versioned_docs/version-2.0.0-alpha.66/cli.md
website/versioned_docs/version-2.0.0-alpha.66/configuration.md
website/versioned_docs/version-2.0.0-alpha.66/deployment.mdx
website/versioned_docs/version-2.0.0-alpha.66/installation.md

- it uses `<Tabs/>`
- Prettier does not format correctly .md extensions containing too much JSX
- IDE syntax highlighting is broken
- My i18n PR fails due to Crowdin doing weird interpretations of this markup
I prefer to change it in upstream branch to avoid conflicts later.
yes
preview

docs(v2): deployment should use mdx extension

---

website/src/pages/showcase/index.js
website/src/pages/showcase/styles.module.css

Currently on the V2 showcase page website preview images height is not restricted in any way which in some cases results in stretching preview cards too much. 
This PR add small CSS tweak to the card image wrapper so it won't exceed height of `175px`. The height was chosen arbitrary based on the current available images in the showcase directory. Image still can have smaller height that decaled and it will not affect the presentation.
The changeset also includes a removal of unused hook from the showcase page file.
Yes.
Changes has been tested on the Docusuaurs V2 website locally.
No.

docs(v2): normalize showcase preview images height

---

packages/docusaurus/src/webpack/base.ts

Fix #3689.
Yes
Have verified changes on my own site, and scope of changes is small.

fix(v2): use SVGO in webpack SVGR loader

---

website/src/pages/showcase/styles.module.css

Actually applies the changes in #3696 from @Simek (because it doesn't work now).
Do not forget: since we are using CSS modules, we need to use `:global` to actually override the regular CSS classes.
Yes
Preview.

fix(v2): limit images height on showcase page

---

packages/docusaurus-remark-plugin-npm2yarn/README.md
packages/docusaurus-remark-plugin-npm2yarn/src/index.js
website/docusaurus.config.js

Add support for tab choices synchronization to npm/yarn tabs (see https://v2.docusaurus.io/docs/markdown-features/#syncing-tab-choices for more details).
I did it via option to make the plugin behavior more flexible.
Yes
Preview.

feat(v2): add support for sync to npm2yarn tabs

---

packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts

Fixes #3700 (follow-up ##2380).
Also in this PR I refactored the logic of creating excerpt, make it much simpler and faster (because we no longer remove all the imports/exports).
Yes
Unit tests.

fix(v2): ignore export declarations in excerpt

---

packages/docusaurus-init/templates/classic/package.json
packages/docusaurus-init/templates/facebook/package.json
website/docs/guides/migrating-from-v1-to-v2.md
website/package.json

- Use defaults setting for [Browserlist](https://github.com/browserslist/browserslist) (0.5% instead of 0.2%). This will avoid transforming CSS vars to static representation, as the support for this feature is pretty good https://caniuse.com/css-variables
- Adding missing command to clean the build in npm scripts
- Relevant documentation updates
Yes
Preview.

chore(v2): adjust website npm package

---

packages/docusaurus-theme-classic/src/theme/TabItem/index.tsx
packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
website/docs/markdown-features.mdx

I think we need to render all tab panels immediately during mounting Tabs component, because currently different side effects observer when navigating between tabs.
For example, if the tab content contains embedded code, then it will reload _every time_ we switch tabs, see the GIF on the React Native website example:
In addition, filtering rendering (as now) leads to additional overhead costs, this is especially noticeable on mobile devices (you can see the delay when switching tabs)
Yes
Preview.

refactor(v2): render all tab panels at once

---

packages/docusaurus-1.x/lib/server/__tests__/__snapshots__/utils.test.js.snap
yarn.lock

When I start website v2, I get the following notice in the console:
```
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
```
In that regard, I think we'd better update the Browserslist database (running by `npx browserslist@latest --update-db`) so we don't see this again.
Yes
N/A.

chore(v2): update Browserslist

---

packages/docusaurus-theme-classic/src/theme/TOC/index.tsx

In #3712 I made a mistake and put CSS class for thin scrollbar on the wrong of TOC element.
Yes
Preview.

fix(v2): add thin scrollbar to proper element in TOC

---

packages/docusaurus/src/commands/swizzle.ts

Fixes #3408, but also does some minor refactoring of command body to improve the comprehensibility/readability of the code (mostly, using return early pattern and using `console.warn` together with `process.exit` instead of throwing an exception so as not to display unnecessary/long stack trace).
Yes
Try to execute `swizzle` command with different cases (with empty/wrong arguments, with `--danger` and `--typescript` flags).

fix(v2): fix inconsistent error output in swizzle command

---

packages/docusaurus-theme-classic/src/theme/hooks/useHideableNavbar.ts
packages/docusaurus/src/client/PendingNavigation.tsx

Fixes #2901
Also, improving the work of the hideable header when changing the anchor (hash) - the header was not _always_ hidden for some reason so it is fixes #2907.
Yes
See https://github.com/facebook/docusaurus/issues/2901#issuecomment-641217860

fix(v2): add support for non-ASCII chars in anchor link scroll

---

packages/docusaurus-theme-search-algolia/src/index.js
packages/docusaurus-utils/package.json
packages/docusaurus-utils/src/index.ts
website/docs/using-themes.md

In PR #3280 it was allowed to swizzle `SearchPage` component, but newly swizzled component was not taken into account when building site.
This PR fixes #3379, after that if the search page component has been changed it will be used instead of initial one.
Yes
Try swizzling the component, making changes to it, starting the site, and making sure the swizzled component is actually being used.
```
yarn swizzle @docusaurus/theme-search-algolia SearchPage
```

fix(v2): use swizzled SearchPage component if any

---

package.json

Currently the `rimraf` portion of the `clear` script from the main package.json is not working correctly.
More information: https://www.npmjs.com/package/@lerna/exec
The forwarding dashes (`--`) has been removed due to warning appearing on run:
Yes.
Successful run of `clear` command from main `package.json` file:
No.

fix(internal): fix clear script from the main package.json

---

packages/docusaurus/package.json

As a result #3727 there was one regression - broken import from PWA plugin. This was not noticed right away, because the site was built without any errors (CI passes), but in [the deploy logs](https://app.netlify.com/sites/docusaurus-2/deploys/5fac6095a6917d00083ff9fb) I saw following:
```
1:12:43 AM: (undefined) ../packages/docusaurus-plugin-pwa/src/renderReloadPopup.js 6:554-564
1:12:43 AM: Critical dependency: the request of a dependency is an expression
```
Strangely enough, this is not a fatal error, but just a warning (why?). Anyway, this error was caused by an update of the `babel-plugin-dynamic-import-node` dependency, so I roll it back to the previous version.
@slorber however, I wonder why this error/warning is raised, perhaps we are using dynamic import incorrectly? (see …

chore(v2): downgrade babel-plugin-dynamic-import-node to 2.3.0

---

website/docs/markdown-features.mdx
website/src/css/custom.css

Currently Inline SVGs section in docs is a stub. This PR adds the example usage, which shows how user can override the single color, or even many colors of inlined SVG image, based on the currently selected theme by user. 
At the beginning I want to utilize the `class` in the CSS selector, but it requires editing a SVG file and the class name is processed (`belly` became `docusaurus_svg__belly`), so I have decided to just use `fill` as selector (for the simplicity, instead of `[class*='belly']`).
You
No.

docs(v2): add Inline SVG color override example

---

website/docs/typescript-support.md

Make the "TypeScript Support" doc page for V2 consistent in providing both npm and yarn command examples.
Yes.

docs(v2): add npm2yarn to typescript install command

---

.github/workflows/build-size.yml

Feature for #3521 
Yes
A comment is added to the PR with changes in the size of key built files

Add build size bot

---

.github/workflows/build-size.yml

This PR fixes the CI on merge by removing the build size check from push pipeline.
Yes.
Successful CI on merge of this PR.
* Refs #3744

chore(internal): fix CI on merge after build size addition

---

packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.tsx
packages/docusaurus-theme-classic/src/theme/NotFound.tsx
packages/docusaurus/src/client/baseUrlSuggestionWarning/BaseUrlSuggestionWarning.tsx
website/docs/markdown-features.mdx
website/src/components/TeamProfileCard/index.js
website/src/theme/NotFound.tsx

Fix small HTML issues which reported by RocketValidator.
Yes
Preview.

refactor(v2): various markup improvements

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx

Fixes #3746
Yes
Try to put the following MDX snippet into the document and make sure it renders correctly.
```
import CodeBlock from '@theme/CodeBlock';
| Markdown | Less      | Pretty     |
| -------- | --------- | ---------- |
| _Still_  | `renders` | **nicely** |
| 1        | 2         | <CodeBlock>sum(rate(grpc_client_msg_received_total{component="tsbd", grpc_type="server_stream"}[30s])) by (cluster_name)</CodeBlock>|
```

fix(v2): add support for interleaving Markdown in code blocks

---

packages/docusaurus-theme-classic/src/theme/Heading/index.tsx
packages/docusaurus-theme-classic/src/theme/Heading/styles.css

After examining other docs, I realized that anchor links to headings should be accessible for keyboard navigation.
Yes
Preview (use `tab` key)

refactor(v2): make accessible anchor links from keyboard

---

package.json
packages/docusaurus-mdx-loader/package.json
packages/docusaurus-migrate/package.json
packages/lqip-loader/package.json
yarn.lock

Just fix various npm warnings about peer dependencies. 
Yes
Logs
Diff changes:
```diff
warning " > eslint-config-airbnb@18.1.0" has incorrect peer dependency "eslint@^5.16.0 || ^6.8.0".
warning " > eslint-config-airbnb@18.1.0" has incorrect peer dependency "eslint-plugin-react-hooks@^2.5.0 || ^1.7.0".
warning "eslint-config-airbnb > eslint-config-airbnb-base@14.1.0" has incorrect peer dependency "eslint@^5.16.0 || ^6.8.0".
warning " > eslint-plugin-jsx-a11y@6.2.3" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6".
warning "eslint-plugin-jsx-a11y > axobject-query@2.1.1" has incorrect peer dependency "eslint@^5 || ^6".
- warning " > workspace-aggregator-64c1ce2e-ccc2-4213-bcef-41c7767f9714@" has incorrect peer dependency "stylelint-copyright@^2.0.0".
- warning " > …
```

chore(v2): fix several npm warnings

---

packages/docusaurus/package.json
packages/docusaurus/src/webpack/plugins/WaitPlugin.js
yarn.lock

I couldn't figure out the reason why [`wait-on`](https://www.npmjs.com/package/wait-on) was not originally used, but we can probably safely replace [`wait-file`](https://www.npmjs.com/package/wait-file) with it (these libs has same interface). This way we will reduce the number of npm warnings on install deps (because `wait-file` is using hapi/joi, which was moved to another place):
```diff
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
- npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
- npm WARN …
```

chore(v2): replace wait-file with wait-on to reduce npm warnings

---

website/src/css/custom.css
website/src/pages/styles.module.css

This PR introduces small design changes to the V2 website:
* fixes the users statements background (previously used CSS variable do not exist anymore in Infima)
* fixes the CSS warnings according to usage of `rgb` with a transparency channel
* updates the "dark" footer background to match the color used for the homepage hero section (the shade change is subtle)
Yes.
Changes have been testes locally, by running the Docusuaurs V2 website.
No.

docs(v2): fix statements background, update footer background

---

packages/docusaurus-theme-classic/src/theme/hooks/useHideableNavbar.ts
packages/docusaurus-theme-classic/src/theme/hooks/useScrollPosition.ts

Another attempt to get the hideable navbar to work well and in a predictable way.
Earlier, I did not take into account the initial (zero) position of the scroll, because of which navbar was not hidden the first time when it was expected. Technically, replacing `useState` with `useRef` fix this use case.
Fixes #2907
Yes
Preview

fix(v2): increase stability of hideable navbar

---

packages/docusaurus-theme-classic/src/theme/Toggle/styles.module.css

As with Algolia search, we'd better personalize the dark mode switcher using the primary site color (i.e. `--ifm-color-primary`).
Also as part of this PR I also removed some unused/unnecessary CSS declarations.
Yes
Try clicking on the dark mode toggle, its outline should be change to the primary color.

refactor(v2): adjust dark mode toggle to site style

---

packages/docusaurus-cssnano-preset/index.js
packages/docusaurus/src/webpack/utils.ts

Probably at this stage we cannot remove duplicate CSS properties, since this breaks the work of the third-party deps, particularly Algolia search.
Yes
Preview. 

fix(v2): do not remove duplicate CSS properties in during minification

---

website/docs/cli.md
website/docs/installation.md
website/versioned_docs/version-2.0.0-alpha.62/installation.md
website/versioned_docs/version-2.0.0-alpha.63/installation.md
website/versioned_docs/version-2.0.0-alpha.64/installation.md
website/versioned_docs/version-2.0.0-alpha.65/installation.md
website/versioned_docs/version-2.0.0-alpha.66/installation.md
website/versioned_docs/version-2.0.0-alpha.68/installation.md

We don't need to install `@docusaurus/x@next` anymore because the `next` npm tag has been removed from v2 packages, to make things less confusing.
This is only  removing the usage from docs (+ other  minor docs changes)
Fixes:
- https://github.com/facebook/docusaurus/issues/3780
- https://github.com/facebook/docusaurus/issues/3756
- https://github.com/facebook/docusaurus/issues/3755

docs(v2): remove @next tags needed to install v2 packages

---

packages/docusaurus-theme-classic/src/theme/Logo/index.tsx

During the work on the `Logo` component the fallback for `darkSrc` was removed (https://github.com/facebook/docusaurus/pull/3745/commits/f49c56c8578bdbeacd9c1edd82cfed5c241f8800). 
This do not affect the Docusaurus V2 website, but have caused an issue for sites using only `src` field in logo config.
Yes.
Changes has been tested locally using Docusaurus V2 website with `darkSrc` removed from the config 😉 
* #3745

fix(v2): fix missing logo in dark theme when darkSrc was not set

---

__tests__/validate-package-json.test.ts

Tests to ensure that all our packages starting with @ will have the required `publishConfig.access: "public"` in package.json, otherwise these packages will fail to publish on `lerna publish`, and lead to restarting the release on a new version.

chore(v2): ensure publishConfig.access presence with tests

---

website-1.x/pages/en/index.js
website-1.x/static/css/custom.css
website/docs/guides/migrating-from-v1-to-v2.md
website/docs/introduction.md
website/versioned_docs/version-2.0.0-alpha.68/guides/migrating-from-v1-to-v2.md
website/versioned_docs/version-2.0.0-alpha.68/introduction.md

It has been reported that some parts of the doc let people think versioning is not supported yet.
Versioning is working fine now, and i18n is coming soon.
We should now drive more users to start on v2 than v1, despite v2 still being in alpha (not for long), even if they need i18n support.
Note: most users are already using v2 anyway:

docs(v2): recommend Docusaurus 2 usage

---

package.json
packages/docusaurus-1.x/package.json
packages/docusaurus-init/package.json
packages/docusaurus-mdx-loader/package.json
packages/docusaurus-migrate/package.json
packages/docusaurus-plugin-client-redirects/package.json
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-ideal-image/package.json
packages/docusaurus-plugin-sitemap/package.json
packages/docusaurus-utils/package.json
packages/docusaurus/package.json
yarn.lock

Currently many different version of `fs-extra` package are used in the Docusuaurs workspace. The Version list ranges from `8.1.0`, through `9.0.0` and ends at latest `9.0.1`. This PR normalizes that by bumping all none-latest `fs-extra` references in the `package.json` files. 
I have also bumped the `@types/fs-extra` package in the main `package.json` to the latest version and I have removed the redundant entry in the migration package `devDependencies`.
Yes.
Build and dev run of Docusuaurs V2 website locally.
No.

chore: match fs-extra version across the workspace

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus/package.json
yarn.lock

Currently the lock has been pointing to the correct version of `react-router-dom`, while in the `package.json` files there was a mismatch between versions of `react-router` and `react-router-dom`. Those packages are complementary and should be kept in sync - https://github.com/ReactTraining/react-router/commit/21a62e55c0d6196002bd4ab5b3350514976928cf.
Yes.
Local run of Docusaurus V2 website.
* #3727 (https://github.com/facebook/docusaurus/pull/3727/files#diff-358cd23f806686eb2ec4d0a9a516f32d9c08f7d8c7bf6905dde0d907902f2454R94)

chore(v2): ensure that the react-router and *-dom version matches

---

package.json

The dep stayed on older version alpha 66 after this change: https://github.com/facebook/docusaurus/pull/3766#discussion_r527910313
But it seems declaring the peer deps here is not required, so maybe we can just remove it?

chore(v2): remove useless stylelint-copyright peerDependency

---

website/docs/installation.md
website/versioned_docs/version-2.0.0-alpha.62/installation.md
website/versioned_docs/version-2.0.0-alpha.63/installation.md
website/versioned_docs/version-2.0.0-alpha.64/installation.md
website/versioned_docs/version-2.0.0-alpha.65/installation.md
website/versioned_docs/version-2.0.0-alpha.66/installation.md
website/versioned_docs/version-2.0.0-alpha.68/installation.md

`npx @docusaurus/init` seems to fail on some older Node versions, as npx tries to run a local `init` binary (the part after the /).
See also the output of `npx @docusaurus/echo test` on holder node here:
As we  don't  plan to require newer node versions, we now document to use `npx @docusaurus/init@latest` instead, as it seems to work fine even in older node versions.
Note: previously we installed with the `@next` tag (which we removed), so now we are just changing the dist tag from next to latest.
Related to https://github.com/facebook/docusaurus/issues/3799

docs(v2): fix docusaurus init issue when not using @latest

---

packages/docusaurus/src/server/presets/__tests__/index.test.ts
packages/docusaurus/src/server/presets/index.ts

Cf https://github.com/facebook/docusaurus/issues/2576#issuecomment-731586715
Yep
Made the changes locally, things worked. Would be difficult for me to automate the test, as it's usually very infra-specific (for instance I'd install the project with Yarn 2, but it would require to make that possible in the test framework, and that's outside of my scope).
https://github.com/facebook/docusaurus/pull/2789 added the same thing for plugins, but forgot presets (or perhaps they didn't exist at the time), cc @SamChou19815

Adds createRequire for preset resolution

---

packages/docusaurus-theme-search-algolia/src/__tests__/validateThemeConfig.test.js
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
packages/docusaurus-theme-search-algolia/src/theme/hooks/useAlgoliaContextualFacetFilters.js
packages/docusaurus-theme-search-algolia/src/validateThemeConfig.js
website/docs/search.md

Merge contextual search facetFilters with config-provided facetFilters.
Remove security: not a big deal because users will notice easily if their search is broken due to an extra useless config filter.
Fixes https://github.com/facebook/docusaurus/issues/3790 
preview + locally
https://github.com/facebook/docusaurus/pull/3550

fix(v2): Algolia: allow contextualSearch + facetFilters

---

packages/docusaurus-theme-classic/src/theme/Heading/index.tsx

Fixes a11y error of "ARIA hidden element must not contain focusable elements".
Yes
Preview.

fix(v2): remove aria-hidden attr from anchor link of heading

---

packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.js
packages/docusaurus-theme-classic/src/validateThemeConfig.js

Enable the footer logo to have an empty `alt=""` attribute. Basically, the same that https://github.com/facebook/docusaurus/pull/3352 did for the navbar logo but now for the footer.
See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#Attributes
> Setting this attribute to an empty string (alt="") indicates that this image is not a key part of the content (it’s decoration or a tracking pixel), and that non-visual browsers may omit it from rendering.
Since the logo normally is decorative an empty alt is fine.
Fixes #3816 
Yes
1. Run unit tests.
2. Create a new project and set the` footer.logo.alt` option in the Docusaurus config file to `''` (`alt: ''`)
3. `yarn start` and check that Docusaurus doesn't complain about `footer.logo.alt` being empty.

fix(v2): Allow footer logo at attribute to be empty

---

packages/docusaurus-theme-search-algolia/package.json
yarn.lock

This updates the DocSearch version that includes a few fixes and new features:
- Update underlying Autocomplete Core library
- Fix CSS inconsistencies
- Fix TypeScript types
- Fix vertical height modal on mobile (algolia/docsearch#984)
- Hide DocSearch keys until we know the user OS (algolia/docsearch#983)
- Preselect query when coming from a selection search
This version displays are React development warning when using React 16 about the `enterKeyHint` property that's officially supported from React 17: facebook/react#18634.
> Warning: React does not recognize the `enterKeyHint` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `enterkeyhint` instead. If you accidentally passed it from a parent component, remove it from …

feat(search): update DocSearch to alpha.31

---

packages/docusaurus-init/templates/README.MD
packages/docusaurus/bin/docusaurus.js

We are not using the @next npm dist tag anymore.
Fix https://github.com/facebook/docusaurus/issues/3821

fix(v2): update notifier dist tag

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx

fix(v2): support rendering of singular tabs

---

.github/workflows/lighthouseCI.yml
.github/workflows/lighthousesrc.json

Added Lighthouse CI to integrate finally and create a complete Build bot to analyse stats changed with every new pull request.
Yes.
A new comment action is added.
#3744

feat(v2): Added Lighthouse CI to PR checks

---

packages/docusaurus-theme-search-algolia/src/theme/hooks/useAlgoliaContextualFacetFilters.js

Fixes #3826
If i18n is not used, `locale` will be `undefined` then, so we shouldn't include it in Algolia's facet filters.
Yes
Preview.

fix(v2): restore Algolia search

---

website/package.json

External PRs like [these](https://github.com/facebook/docusaurus/pull/3832) are blocked due to not accessing the env variable for security reasons
This temporarily disable crowdin to make external PRs pass checks

fix(v2): temporary: disable crowdin until PR env variable permission fixed

---

packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.js

Currently there is not possible to customize the `SearchPage` styling without swizzling the component.
This PR adds the custom wrapper class name to the `SearchPage`, so it will be possible to add custom styles which only apply to this page.
Yes.
Local run of Docusaurus V2 website.
No.

feat(V2): add custom wrapper class to SearchPage, fix title

---

packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.js
packages/docusaurus-theme-search-algolia/src/theme/SearchPage/styles.module.css

Currently `SearchPage` styling feels a bit plain and in addition to that inputs and separator lines do not change appearance between the modes.
This PR updates the `SearchPage` component and introduces the following changes:
* more CSS variable used from Infima and Docsearch itself
* inputs borrows few styling properties the search input style from the modal
* chevron sign (breadcrumbs splitter) received it's own class to make customizing the style (or even changing it via `content`)  possible through CSS
Yes.
The changes have been tested using Docusaurus V2 website locally.
* #3834

fix(v2): update SearchPage styling, fix appearance in dark mode

---

website/docs/docusaurus-core.md

This PR updates the `Docusaurus Client API` page and includes following changes:
* consistent usage of `const` instead of `function`,
* detailed method definitions moved from headings to the code blocks for `usePluginData` and `useAllPluginInstancesData` hooks, this improves the readability of ToC
* added and updated line highlighting in examples.
Yes.
Changes have been tested on Docusuaurs V2 website locally.
No.

docs(v2): update Client API docs page

---

packages/docusaurus-theme-bootstrap/package.json
packages/docusaurus-theme-bootstrap/src/theme/DebugLayout/index.tsx
packages/docusaurus-theme-bootstrap/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/LayoutHead/index.tsx
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/generalUtils.ts
packages/docusaurus-theme-search-algolia/package.json
packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.js

Currently the same function, same formatter is used in various packages to format the `siteTitle`.
This PR extracts the formatter function to stand alone hook (`useTitleFormatter`) and moves it to `theme-common` package. 
@slorber My only concern is that after refactor I had to add `@docusaurus/theme-common` also to `docusaurus-theme-search-algolia` dependencies. In theory this is the expected that `theme-search` can be depended on `theme-common`, but due to the way in `theme-common` dependencies have been declared, this will mean that Algolia plugin now will fetch all content plugins (https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-common/package.json#L20). 
Not sure how big problem it is in the general scope of Docusuasaurs, since this package should not be …

feat(v2): extract site title formatter to theme-common util

---

.github/workflows/build-size.yml
.github/workflows/lighthouseCI.yml

A PR opened from a fork will trigger CI but the CI workflows can't comment on the original PR, due to security reasons.
This change should fix it.
Refs:
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
https://github.community/t/github-actions-are-severely-limited-on-prs/18179/19

chore(v2): fix PRs not able to add lighthouse/buildsize comment from works

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/sidebars.ts

On reading the output that gets printed when there are inexistent IDs, I noticed an additional backtick getting printed after the list  of IDs. So, I thought of proposing a change that removes it.
Yes.
Facing issues with testing the change locally. Hopefully, it should work properly. I'll update once I'm able to test this locally.
N/A

fix(v2): remove unnecessary backtick in output

---

website/docs/docs.md

Fixed typo in section about the hideable sidebar. 'hided' is used instead of 'hidden'.
Recently started familiarizing myself with Docusaurus. I was reading the documentation and noticed the typo. 
Yes
Simple type fix.

docs(v2): Fixed Typo: Hided => Hidden

---

website/package.json

Crowdin makes deploy previews slower for little additional value
+ Crowdin has a weird way to handle concurrency, and it seems you can only download from one process at a time...

chore(v2): disable Crowdin for deploy previews

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

This fixes the keyboard navigation integration with Docusaurus following breaking changes in the Autocomplete API (which is an underlying library of DocSearch).
You'll now be able to hit <kbd>Enter</kbd> to be redirected to the link, as you were before.
Yes.
N/A.
- #3819

fix(v2): fix DocSearch keyboard navigator

---

.eslintignore
.prettierignore

It looks like it `.yarn` directory should also be added to the `.eslintignore` and `.prettierignore`, because currently some of build commands includes formatting steps, and some unnecessary files are being reformatted.
Yes.
Local test run of Docuausurs workspace using Yarn v2.
* https://github.com/facebook/docusaurus/commit/3e101f86b784d9c34648a67bb32c706afe3884f5#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947R9 (https://github.com/facebook/docusaurus/pull/3849)

chore: add Yarn v2 cache directory to ignores

---

.github/workflows/e2e-test.yml
.github/workflows/lighthouseCI.yml

As @slorber noticed the increased number of jobs cause the CI to choke a bit, so I was advice to reduce the job count (at least for now). 
This PR removes Node 14 from `yarn-v1 E2E` job and Node 10 from `yarn-v2 E2E` to retain at least one job on both version of Node.
Additionally I have removed the Node, `install` and `build` steps, since it looks like that they are redundant.
Yes.
Run the CI.
* #3849

chore(ci): reduce number of jobs, remove build from lighthouse pipeline

---

.github/workflows/build-size.yml
.github/workflows/lighthouseCI.yml
.github/workflows/migration-cli-e2e-test.yml
.github/workflows/nodejs-windows.yml
package.json

This PR is an attempt to optimize CI workflows a bit more to improve the time required to check every PR.
I have utilized the [`@dorny/paths-filter`](https://github.com/dorny/paths-filter) action to add check based on the modified files in the PR so now:
* V1 build won't be running on Windows Pipeline until `packages/docusuaurs-1.x` or `packages/docusuaurs-init-1.x` files have been changed.
* Migration CLI job won't run until `packages/docusuaurs-migration` includes the changes.
This is the first time I have used this action, so the initial version might be not correct. Any tips and ideas for further optimizations are welcome!
Yes.
Run the CI! 😉 
* #3861

chore(ci): run V1 Build and Migration CLI tests conditionally on CI

---

.eslintignore
.gitignore
.prettierignore

@slorber reported that after latest changes to ignores two generated files from v1 build are marked as `unversioned`. This PR fix that issue by adding the files to ignores.
Earlier they were part of removed `.gitignore` from v1 package.
Yes.
V1 build locally and run of `git ls-files . --exclude-standard --others`, `yarn prettier` and `yarn lint`.
* #3865

chore: add missing v1 generated files to ignores

---

website/docs/migration/migration-automated.md

I am trying Docusaurus migrate of my website built with v1. I think that **docusaurus-migrate** is an old package, I've copy-pasted this `npx` command but it not works, I think that it could be **@docusaurus/migrate** package

docs(v2): From docusaurus-migrate to @docusaurus/migrate

---

packages/docusaurus/bin/docusaurus.js

https://github.com/facebook/docusaurus/blame/master/packages/docusaurus/src/commands/external.ts#L12 changed the exported method to an async function, but the CLI loader was not updated to also run async, breaking things such as `npm run docusaurus docs:version <version>`.

fix(v2): load plugin commands async to fix broken plugin CLI commands `docs:version`

---

packages/docusaurus-theme-classic/src/theme/hooks/useTheme.ts

Dynamic automatic dark mode detection is disabled when the manual switch is hidden. But I want to enjoy the benefits of automatic dark-mode switching without showing the manual toggle.
See details in #3876 
close #3876 
Yes
With the following config:
```
colorMode: {
defaultMode: 'light',
disableSwitch: true, // Don't show manual switch
respectPrefersColorScheme: true, // But respect user preference!
},
```
[🎥 before this fix](https://files.hmil.fr/cloud/docusaurus_dark-mode_toggle-off.webm)  
[🎥 after this fix](https://files.hmil.fr/cloud/docusaurus_dark-mode_toggle-off_fixed.webm)
Not shown in the screencasts: Currently, the correct color theme gets applied but only if you do a hard reload of the page. The difference that this fix makes is that you don't have to reload the page anymore. …

fix(v2): dynamic dark mode detection without toggle widget

---

.github/workflows/lighthouseCI.yml

Currently Lighthouse CI test fails of on the initial PR deploy because build take more than 5 minutes:
> Build time: 7m 58s. Total deploy time: 8m 21s
This PR increased this time to `600` seconds, so 10 minutes. 
Unfortunately this is not the best way to solve the issue, but it is the best what can be achieved right now.
The other problem with the Lighthouse check is that pushing another commit to the PR will cause Lighthouse check to run immediately on the site deployed from the previous build, because it only depends on 200 response from the content located under deploy URL and deploy URL do not change between commits (do not include commit hash).
To fix this properly the website deployment should be a part of GitHub workflows, and lighthouse check should depends on that. Then the …

chore(ci): increase Lighthouse CI max_timeout

---

packages/docusaurus-theme-classic/src/theme/Footer/index.tsx
packages/docusaurus-theme-classic/src/theme/Footer/styles.module.css

This PR includes few small improvements to the `theme-classic` Footer component:
* add distinctive `className`s for copyright element and bottom content wrapper to allow easier Footer customization
* do not render empty copyright element when there is no `copyright` specified
* use default values from Infima for logo transition delay and function
Yes.
Local build and run of v2 website.
No.

fix(v2): improve Footer structure, add class names, use Infima transition

---

website/docs/deployment.mdx

Yesterday I reported #3889 because I believed that a bug in Docusaurus was erasing my custom domain from the repository settings on each deploy. Turns out the issue was as simple as the fact that I forgot to add a CNAME file, I for some reason completely missed the section telling to add CNAME at the root of the `static/` directory. That being said, I believe the issue could have been avoided if this section was put more in evidence, hence the idea of wrapping the section in an `:::info` block.
Yes
#3889

docs(v2): Wrap section about custom domains in :::info

---

packages/docusaurus-theme-classic/src/theme/BlogListPaginator/index.tsx

The `pagination-nav__label` CSS class must be used with a `div`, not an `h4`. Otherwise, it leads to the adding of extra margins (see Test plan).
Yes
Before:
After:

fix(v2): use proper element for pagination nav label

---

packages/docusaurus/src/webpack/utils.ts

Fixes #3836
This disables the `removeUnusedAtRules` option in [advanced CSS minifier](https://github.com/jakubpawlowicz/clean-css#level-2-optimizations) as it does not work correctly for us.
Yes
Tested on https://github.com/semoal/docusaurus-css-minifier-bug (after that, the building of site goes without fatal errors).

fix(v2): do not treat at-rules during CSS minification

---

packages/docusaurus-theme-bootstrap/src/theme/DebugLayout/index.tsx
packages/docusaurus-theme-bootstrap/src/theme/DocItem/index.tsx
packages/docusaurus-theme-bootstrap/src/theme/Layout/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/LayoutHead/index.tsx

The Open Graph protocol format is the following:
```
<meta property="og:image" content="https://example.com/image.png />
```
Twitter metas, however, are structured in a different format:
```
<meta name="twitter:image" content="https://example.com/image.png />
```
They are similar but not identical, I think this led to confusion and
the typo we have in the codebase.

fix(v2): correct typo in metas generated for Twitter cards

---

packages/docusaurus-plugin-content-docs/src/__tests__/sidebars.test.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-docs/src/props.ts
packages/docusaurus-plugin-content-docs/src/sidebars.ts
packages/docusaurus-plugin-content-docs/src/types.ts
website/docs/docs.md

-I want to pass in custom props for consumption by my swizzled DocSidebar component
Yes
I modified a test within `docusaurus-plugin-content/src/__tests__/sidebars.test.ts`
https://github.com/facebook/docusaurus/issues/3868

feat(v2): add custom props for consumption by swizzled sidebar

---

.github/workflows/canary-releases.yml

Avoid useless publication of canary releases
yes
CI
Inspired by https://github.com/facebook/docusaurus/pull/3884

chore(ci): only publish @canary release if packages/** has changed

---

website/netlifyDeployPreview/index.html
website/package.json

Bootstrap theme deploy preview is a burden currently, so let's disable it until we have time to invest in it and make it production ready

chore(ci): temporarily disable bootstrap deploy preview

---

packages/docusaurus/src/webpack/__tests__/base.test.ts
packages/docusaurus/src/webpack/__tests__/utils.test.ts
packages/docusaurus/src/webpack/base.ts
packages/docusaurus/src/webpack/utils.ts

Fix #3901 
Yes
See instructions in #3901.
**svgo** has plugin **removeViewBox** that enabled by default.

fix(v2): don't remove viewBox from svg

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-theme-classic/src/theme/NavbarItem/LocaleDropdownNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-classic/src/validateThemeConfig.js
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/client/exports/Link.tsx
packages/docusaurus/src/server/__tests__/__snapshots__/config.test.ts.snap
packages/docusaurus/src/server/__tests__/i18n.test.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/server/i18n.ts
website/docusaurus.config.js

Needed for i18n support in Jest.
Will be documented and refactored a bit later, after the i18n dogfooding phase

feat(v2): Add localeDropdown navbar item type + i18n localeConfigs field

---

packages/docusaurus/src/server/translations/__tests__/translationsExtractor.test.ts
packages/docusaurus/src/server/translations/translationsExtractor.ts

Jest has this JSX content that would not be extracted properly by the i18n translation extractor:
```
<Translate>
{`Find out what's new with Jest.
- Follow[Jest](https://twitter.com/fbjest) on Twitter.
- Subscribe to the[Jest blog](/blog/).
- Look at the[changelog](https://github.com/facebook/jest/blob/master/CHANGELOG.md).`}
</Translate>
```
This is become Babel AST parses this as 3 childrens: `[empty text node, JSX expression, empty text node]` 
In such case we'll filter out the empty text nodes to focus mainly on the important node containing the translations
yes
unit tests

fix(v2): i18n translation extractor should handle JSX formatting edge cases better

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx
packages/docusaurus/src/server/themes/alias.ts

Fix weird theme alias issue on Windows:
https://github.com/facebook/docusaurus/runs/1552317907
On Windows, the aliases are created in a different order and can shadow each others:
yes
CI

fix(v2): fix navbar items issue on Windows?

---

website/docs/blog.md

Added ***docs: false,*** to the config for blog-only mode because we do not want any documents if we're in blog-only mode otherwise, we probably wouldn't use blog-only mode.
To setup only a blog with Docusaurs v2.
Yes

docs(v2): blog.md with docs: false, for blog-only mode

---

packages/docusaurus/src/client/App.tsx
packages/docusaurus/src/client/theme-fallback/Root/index.js
website/docs/using-themes.md

Fixes https://github.com/facebook/docusaurus/issues/3919
We need a way to add state components (often providers) at the very top of the tree, and avoid unmount/remount when navigating.
This `<Root>` theme component is at the very top of the app, even above the `<Layout>` component, and unlike the layout (that is applied on a per-page basic), the Root component is rendered consistently, never unmounts, and can hold stateful logic.
Example: put this in `website/src/theme/Root.js`
```js
function StatefulButton() {
const [value, setValue] = React.useState(false);
return (
<div style={{padding: 50, border: 'solid'}}>
<button onClick={() => setValue((v) => !v)}>
Value = {value ? 'true' : 'false'}
</button>
</div>
);
}
function Root({children}) {
return (
<> …
```

feat(v2): Add <Root> theme element

---

packages/docusaurus-theme-classic/src/__tests__/translations.test.ts
packages/docusaurus-theme-classic/src/translations.ts
packages/docusaurus-theme-common/src/utils/useThemeConfig.ts

Fix https://github.com/facebook/docusaurus/issues/3936
Theme code should not crash if there is no footer in themeConfig
yes
unit

fix(v2): i18n should not crash theme without footer

---

packages/docusaurus/src/commands/build.ts

We shouldn't print "run npm serve" more than once:

fix(v2): fix i18n build logging. 

---

packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts

Ignoring style imports when generating excerpt, since this use case was not considered previously.
I noticed that the [Infima website is importing a style file](https://github.com/facebookincubator/infima/blob/master/website/docs/layout/grid.mdx
), and as a result, the meta description is incorrect.
I also increased the precision of the regex to only consider whitespace characters when checking import/export declarations.
Yes
Tests.

fix(v2): ignore style imports in excerpt

---

packages/docusaurus/src/webpack/utils.ts

Fixes  #3942
See https://github.com/jakubpawlowicz/clean-css/issues/914 and https://github.com/jakubpawlowicz/clean-css#inlining-options for more details.
Yes
See To Reproduce section in #3942 issue.

fix(v2): disables all inlining in CleanCSS

---

website/docs/api/plugins/plugin-content-docs.md

Hello everyone! This is my first contribution here :) 
I added this small information because I spent some hours seeking how to display just docs without things like blogs & pages. 
The biggest obstacle for me was, how to configure  `routeBasePath` to follow my assumptions. As the value `''` not works, and the current documentation mention `*DO NOT* include a trailing slash` didn't know what should I do.
I've started cloning the docs plugin and hacking it locally, then I found:
https://github.com/facebook/docusaurus/blob/69bf68a/packages/docusaurus-plugin-content-docs/src/options.ts#L54-L57
I followed that [link](https://github.com/facebook/docusaurus/issues/3374) and read:
> I think this is the reason why blog/docs option routeBasePath: '' fail, while routeBasePath: '/' works.
So, now I …

Added information about setting `/` in routeBasePath

---

packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/versioned-site/docusaurus.config.js
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/versioned-site/i18n/en/docusaurus-plugin-content-docs/version-1.0.0/hello.md
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/versioned-site/i18n/fr/docusaurus-plugin-content-docs/version-1.0.0/hello.md
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/options.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/versions.test.ts
packages/docusaurus-plugin-content-docs/src/docs.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-plugin-content-docs/src/versions.ts
website/docs/api/plugins/plugin-content-docs.md
website/docusaurus.config.js

```js
/**
* When docs are versioned, the edit url will link to the doc
* in current version, instead of the versioned doc.
* Useful if you don't want users to submit doc pull-requests to older versions.
*/
editCurrentVersion: false,
/**
* When docs are localized, the edit url will target the localized doc,
* instead of the original unlocalized doc.
* Useful if you commit localized docs to git, instead of using a translation service.
*/
editLocalizedDocs: false,
```
With Docusaurus v1, even with versioning enabled, the edit button always targeted the "upstream" docs (ie the ./docs folder), not the versioned folders.
With Docusaurus v2, this behavior has changed, and this can be annoying because users end up submitting docs pull requests to the "last version" (the version of your last …

feat(v2): new docs edit options: editCurrentVersion + editLocalizedDocs

---

packages/docusaurus-theme-live-codeblock/src/custom-buble.js
packages/docusaurus-theme-live-codeblock/src/index.js

So.. as proposed by #3053, we are using a live code editor using `react-live`, and since transpiling javascript on the fly could easily turned into a heavy job, this library uses `https://github.com/bublejs/buble` for it, which relatively has a bundle size as mentioned in https://github.com/FormidableLabs/react-live#what-bundle-size-can-i-expect.
However, to further reduce the bundle size, @endiliey decided to use [@philpl/buble](http://npm.im/@philpl/buble) which discards some codes on ESNext transpilation, resulting in a notably smaller bundle size.
However this introduced some problem, which I encountered while using docusaurus@v2 and is well-explained by #3053: the live code editor cannot run the code that contains `async` or `await` keywords.
Therefore, the simplest fix would be …

fix(v2): allow async/await in live code editor

---

packages/docusaurus-plugin-client-redirects/src/__tests__/__snapshots__/writeRedirectFiles.test.ts.snap
packages/docusaurus-plugin-client-redirects/src/__tests__/writeRedirectFiles.test.ts
packages/docusaurus-plugin-client-redirects/src/writeRedirectFiles.ts

@docusaurs-plugin-client-redirects fails on windows because windows is special and uses \ in path instead of /.
Replacing \ with / before url encoding resolves this issue.
Resolves #3886 
Yes

fix(v2): fix redirect toUrl (windows + trailing slash)

---

website/docs/migration/migration-overview.md

Clarify the migration process regarding ./docs folder location difference between v1/v2
Fixes https://github.com/facebook/docusaurus/issues/3956

docs(v2): Add migration info doc regarding docs folder location

---

packages/docusaurus-theme-classic/src/theme/hooks/useDocs.ts
website/docusaurus.config-blog-only.js

Search feature assumes the docs plugin is available, which is not always the case.
This is a quickfix so that the Algolia search can be used in blog-only mode without any problem.
(better solution to be found)
Fixes https://github.com/facebook/docusaurus/issues/3947
blog only preview with search can build

fix(v2): fix blog only contextual search

---

website/src/data/users.js
website/src/pages/showcase/index.js

It's not so easy for users to add their site.
This PR:
- Add a "Add your site!" button
- Add better instructions to add a Docusaurus site to showcase
- ignore prettier formatting errors (as edits are often done through Github interface)

docs(v2): nudge users to add site to showcase

---

website/docs/api/themes/theme-configuration.md
website/docs/guides/docs/docs-multi-instance.mdx
website/docs/using-plugins.md
website/sidebars.js

Add missing documentation for docs multi-instance support
Fixes https://github.com/facebook/docusaurus/issues/3299
preview
https://github.com/facebook/docusaurus/pull/3204

docs(v2): Add documentation for docs multi-instance support

---

packages/docusaurus/src/server/__tests__/__snapshots__/configValidation.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/server/plugins/init.ts

As reported by #3934, passing an invalid type of plugin is ignored silently.
1. To resolve that issue, this PR adds some lines of code to throw error when invalid type of plugin is detected.
2. This PR also improves tests on validating plugins based on `ConfigSchema` and the typing of `PluginSchema` itself to an `ordered` one. Any type of plugin that has a wrong signature but somehow bypasses the check in #1 should be detected by schema validation.
yes
Tested locally by manually injecting a function into `plugins` like so:
```ts
const plugins: InitPlugin[] = [...pluginConfigs, function() {}]
.map((pluginItem) => {
...
```
It would give an error:
Also tested without invalid plugin. No errors. It actually should be proven by checks passing on this PR.
Will close #3934 if merged

feat(v2): better error message for invalid plugin config

---

packages/docusaurus-init/bin/index.js
packages/docusaurus-init/src/index.ts
packages/docusaurus-migrate/src/__tests__/__fixtures__/expectedSiteConfig.js
website/docs/installation.md

Originally from #3450, support to skip install for project scaffolding. 
Yes
Not required
None

feat(v2): skip dependency install on docusaurus init

---

packages/docusaurus-migrate/src/__tests__/__fixtures__/expectedSiteConfig.js

Test is sensitive to current year: make it insensitive.
Porting code of @9oelM in closed PR https://github.com/facebook/docusaurus/pull/3984/files#diff-1fcecbf1a624edb15aef11f316e17b2deed40b10719340d05f208217b3c236ae

chore(v2): fix date-sensitive test fixture

---

website/docs/styling-layout.md

When I wanted to change the css variables used in dark mode I struggle a bit to figure out how.
yep
I ran:
`yarn test`
`yarn test:build:v2`
Closes #3985

docs(v2): add overwriting css variables for dark mode

---

crowdin-v2.yaml
website/package.json

- Use latest version
- Use new "hide hidden files" setting
- Download/unzip from official github releases instead of self hosted => simpler to upgrade/document

chore(v2): Upgrade crowdin

---

packages/docusaurus-plugin-sitemap/src/createSitemap.ts

Fix issue where when `trailingSlash` option is enabled, routes that already end in a `/` are shown with double slash at the end.
Some of my routes show in sitemap.xml without a trailing slash, so I use `trailingSlash` to make them all consistent. However, some of my paths (e.g. /docs/ created by getting_started.md) already have a trailing slash. Currently /docs/ will be rendered as `/docs//` in the sitemap which isn't correct. This fix prevents that trailing double slash when the `trailingSlash` option is enabled.
Yes
1. Update your docusaurus.config.js to enable sitemap's `trailingSlash` option
```
plugins: [
[
'@docusaurus/plugin-sitemap',
{
id: 'plugin-sitemap-default',
trailingSlash: true,
},
],
],
```
2. Create a page in `/docs` with `slug: /`
3. Generate the sitemap by creating an …

fix(v2): Fix double trailingSlash in sitemap.xml

---

website/docs/search.md

The motivation of this PR is to help more users use the built-in Algolia search feature of Docusaurus since many users may not be eligible for the free, hosted version of DocSearch. It also helps these users keep their DocSearch config up to date by linking to the Docusaurus 2 config file. Hopefully this will help users avoid issues with the /search page as discussed in https://github.com/facebook/docusaurus/issues/3996. 
Yes.
None.
Not applicable.

docs(v2): Add how to run your own DocSearch

---

.devcontainer/devcontainer.json

Dev container for GitHub codespaces
Yes
Not Required
None

chore: add DevContainer config for GitHub codespaces

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/webpack/utils.ts
website/docs/lifecycle-apis.md

I need to use one of these stats in my own plugin, so it was `patch-package`, or do this, which gives plugins a LOT more options for post-processing and other capabilities.  
Yes
My test plugin worked against the branch.
n/a

feat(v2): Allow plugins to consume webpack stats

---

.circleci/config.yml
crowdin-v1.yml
website-1.x/netlify.toml
website-1.x/package.json

As we are moving v1 site to http://v1.docusaurus.io/, probably using a Netlify deployment, it's a good time to upgrade the Crowdin cli (v2 installed as deb on CircleCI) to v3/npm package that can easily run on Netlify

chore(v1): upgrade v1 Crowdin cli + CI config

---

website-1.x/pages/en/versions.js
website-1.x/siteConfig.js

Because some users might think Docusaurus 1 site `/next` is actually v2, we should clarify.
https://github.com/facebook/docusaurus/issues/4042#issuecomment-760272003
https://docusaurus.io/docs/en/next/docker
The above site is not V2 but is a bit misleading

docs(v1): version page should recommend v2

---

website-1.x/pages/en/versions.js
website-1.x/siteConfig.js

follow-up of https://github.com/facebook/docusaurus/pull/4047
(one commit was missing 😅 )

docs(v1): version page should recommend v2 (bis)

---

website-1.x/docs/getting-started-docker.md

Currently this part of the docs doesn't remind the user to use the --host flag. If the user doesn't use it, then the website will not be accessible outside of the docker container. This is what the user ultimately wants, to avoid using node and ruby and develop/productivize his website in a container.
A clarification in the documentation is missing..
Yes
Related issue: https://github.com/facebook/docusaurus/issues/4042

docs(v1): Docker: remind the user to use the --host flag

---

admin/new.docusaurus.io/README.md
admin/new.docusaurus.io/_redirects

Update the codesandbox url, as we have an official template now: https://github.com/codesandbox/codesandbox-client/pull/5136

chore(v2): update codesandbox redirect

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/question.md
README.md

The CodeSandbox should be used for:
- people that want to assess Docusaurus easily
- people that want to submit good bug reports

docs(v2): Include new.docusaurus.io CodeSandbox in issue templates + README

---

README.md
website/docs/installation.md
website/docs/introduction.md
website/src/pages/index.js
website/src/pages/styles.module.css

Made this pull request to make known CodeSandbox support for Docusaurus
Yes
I only added a tip admonition referencing Codesandbox support for Docusaurus. The admonition was added to the introduction docs and also the installation docs
It is related to this PR #3717

docs(v2): Add codesandbox integration

---

examples/bootstrap/docusaurus.config.js
examples/bootstrap/package.json
examples/bootstrap/sandbox.config.json
examples/bootstrap/yarn.lock
examples/classic/docusaurus.config.js
examples/classic/package.json
examples/classic/sandbox.config.json
examples/classic/yarn.lock
examples/facebook/docusaurus.config.js
examples/facebook/package.json
examples/facebook/sandbox.config.json
examples/facebook/yarn.lock
generateExamples.js

Templates should use alpha 70.
Also changed the template from "node" to "docusaurus"
We have some problems on the CodeSandbox integration apparently, like if the "master" template was stateful and shared between all users (https://github.com/codesandbox/codesandbox-client/pull/5136). Hope this eventually fixes it.

chore(v2): Regen codesandbox templates + add template: "docusaurus"

---

website/docs/api/docusaurus.config.js.md

Wanted to see how I can get the hideable sidebar that Docusaurus has on their website.
Yes

docs(v2): add hideableSidebar option to config demo

---

yarn.lock

yarn.lock is modified after a yarn install on master, after merging PR https://github.com/facebook/docusaurus/pull/4066
It breaks canary release publishing: https://github.com/facebook/docusaurus/runs/1734821890?check_suite_focus=true

chore(v2): fix unstable master yarn.lock

---

website/docs/configuration.md

We shouldn't manually write inline tocs but rather use the new TOCInline component for that.
(+ the manually written toc was including unwanted items)

docs(v2): Use the TOCInline component in config doc

---

website/community/resources.md

Article link was 404ing because of a title change, so this pull request updates the broken link
Yes
N/a
N/a

docs: update broken link on resources page

---

examples/bootstrap/docusaurus.config.js
examples/classic/docusaurus.config.js
examples/facebook/docusaurus.config.js
packages/docusaurus-init/templates/bootstrap/docusaurus.config.js
packages/docusaurus-init/templates/classic/docusaurus.config.js
packages/docusaurus-init/templates/facebook/docusaurus.config.js

Better type hints and smart complement for `docusaurus.config.js` using jsdoc.
Yes
Worked nice in vscode!
https://user-images.githubusercontent.com/13063376/105655860-e9f6cd00-5efb-11eb-8234-c9356b443614.mp4
NONE

feat(v2): improve templates, use JSDoc type annotation, improve `docusaurus.config.js` autocompletion

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx

I like the classic theme and would like to theme the Tabs component. The Tabs component's wrapper div doesn't have a class name on it and that would be useful. 
This PR adds a classname. No CSS is added.
Yes
Ensure there is no side effect: the class name isn't used in the repo

style(v2): add className to tab container

---

packages/docusaurus-theme-classic/src/theme/LayoutHead/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts

According to the W3C's [keywords meta tag spec](https://www.w3.org/wiki/HTML/Elements/meta%20?iframe=true&width=100%&height=100%#Example_A), it accepts a string type content. Most developers are already familiar with the `string` type content. So for better DX, we can provide both `string` and `array` types for the value of the Layout's keywords props.
Yes.
- Add the feature to `packages/docusaurus-theme-classic/src/theme/LayoutHead/index.tsx`.
- `cd packages/docusaurus-theme-classic` then `yarn link`
- `cd website`, link the package then `yarn start`
- Ensure both `string` and `array` values are work for the Layout's keywords props

feat(v2): supports string type for the Layout's keywords props

---

packages/docusaurus-theme-classic/src/theme/LayoutHead/index.tsx
website/src/pages/feedback/index.js
website/src/pages/index.js
website/src/pages/versions.js

You shouldn't use `<Layout permalink=""/>` for your homepage (like we currently had for Docusaurus 2 website), the canonical URL should rather be inferred from site URL + current page path.
This works better particularly for canonical URLs on translated pages (the french homepage canonical URL is `/fr` not `/`
yes
this should fix an SEO /  i18n issue reported by https://technicalseo.com/tools/hreflang/ due to having bad canonical URLs on localized site homepage

feat(v2): default canonical urls

---

website/docs/migration/migration-manual.md

It's better to not use the permalink props on theme Layout component.
We compute a canonical URL by default already, so it's not needed.
Related to https://github.com/facebook/docusaurus/pull/4109

docs(v2): Do not encourage using the permalink prop

---

packages/docusaurus-plugin-pwa/package.json
packages/docusaurus-plugin-pwa/src/registerSw.js
packages/docusaurus-plugin-pwa/src/sw.js
yarn.lock

Its an update, updates are usually cool
Yes
Looks to work just fine
n/a

chore(v2): Update workbox to v6

---

packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
packages/docusaurus-plugin-content-blog/src/types.ts
packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/options.test.ts
packages/docusaurus-plugin-content-docs/src/docs.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-plugin-content-docs/src/versions.ts
website/docs/api/plugins/plugin-content-blog.md
website/docs/api/plugins/plugin-content-docs.md
website/docs/i18n/i18n-crowdin.mdx
website/docs/i18n/i18n-git.md
website/docusaurus.config.js

https://github.com/facebook/docusaurus/issues/3152
Some users are assembling Docusaurus sites from docs coming from multiple places, and the url to edit the doc in the upstream doc referential is not necessarily an url that docusaurus is able to compute based on the files it sees on the filesystem.
Also, we need the ability to customize the editUrl per locale. This allows to link to a specific translation system (like Crowdin) for a subset of locales for example, or having one git repo per locale and using git submodules for assembling the final localized site etc...
A functional form of editUrl gives full power to the user
yes
tests + dogfooding

feat(v2): editUrl function for advanced use-cases

---

packages/docusaurus/src/client/baseUrlIssueBanner/BaseUrlIssueBanner.tsx
packages/docusaurus/src/client/baseUrlIssueBanner/styles.module.css

https://github.com/facebook/docusaurus/issues/4028
The help banner that is visible when the site baseUrl is badly configured gets indexed by Google by mistake (despite being made invisible on sites correctly configured, thanks to critical CSS)
This PR changes the way this banner is rendered:
- The banner is not server-rendered anymore (not in static HTML files)
- The banner is rendered on the client, using critical inlined JS
This should theoretically ensure Google will not index that string (can't be 100% sure)
Yes
Production

fix(v2): baseUrl help banner should not be indexed by Google / SEO

---

packages/docusaurus/src/server/plugins/index.ts
website/docs/docusaurus-core.md
website/docs/migration/migration-manual.md

The `useBaseUrl` hook should not be used very often, because:
- the base url is added to all React/Markdown absolute links by default
- webpack asset loaders that handle the baseurl automatically
The use-cases for `useBaseUrl` are now quite limited (but we still need it, mostly to implement the themes)
Related: https://github.com/facebook/docusaurus/issues/4119

docs(v2): do not recommend using useBaseUrl() hook in most cases

---

website/docs/i18n/i18n-introduction.md

Fixing a typo of word **sentence**  in i18n documentation
Yes

docs(v2): typo in i18n docs

---

website/docs/installation.md

Removing this extra curly brace from documentation
Yes

docs(v2): remove unnecessary brace from installation doc

---

website/docs/migration/migration-manual.md

Simple Typo Fix for word **Process** in migrations Documentation
Yes

docs(v2): typo fix in Migration Docs

---

packages/docusaurus/src/client/baseUrlIssueBanner/BaseUrlIssueBanner.tsx

Hotfix.
There was an error in #4125, as a result of which when we try to click on any internal link from the homepage, we get a blank page with errors in the console:
Yes
Preview.

fix(v2): fix navigation from homepage

---

website/docs/using-themes.md
website/versioned_docs/version-2.0.0-alpha.70/using-themes.md

- I wanted to inject <script/> tag to put Google Adsense
- I followed [this guide](https://v2.docusaurus.io/docs/using-themes#wrapper-your-site-with-root) to wrap my site, it's not working as I wished.
(try to put code into `website/src/theme/Root.js`)
- turns out, it worked putting code into `src/theme/Root.js`
- this wrong contents of guide makes me waste several hours
- let me share [my docusaurus blog code](https://github.com/geoseong/geoseong.github.io/tree/docusaurus-blog) with corrected content
```
I am "version-2.0.0-alpha.70" user, so I updated the contents of "version-2.0.0-alpha.70" and after.
```
**YES**
**Before**
**After**
I think there's no relation with it

docs(v2): Fix file path in "Wrapper your site with `<Root>`" (website/docs/using-themes.md)
