facebook/docusaurus

website/pages/en/index.js
Let me know if double having is intentional
=> without having having to worry about site design.

docusaurus-init/README.md
=> Fix Broken Link To Installation Docs

lib/server/readMetadata.js, lib/server/server.js, lib/server/translation.js, lib/start-server.js, lib/write-translations.js
I agree with the points stated in #207. It got a bit too messy.
N/A (ping me if I'm wrong tho)
N/A
<hr />
Closes #207.
=> Cleanup startup logs

docusaurus-init/README.md, examples/basics/core/Footer.js, examples/basics/pages/en/index.js, lib/core/nav/HeaderNav.js
Improve Docusaurus.
They are pretty tiny changes and I tested them using my local copy.
**Broken link:** I clicked on the link and checked that it loaded the intended website.
**Support no users:** I loaded the page with and without users and checked the intended behaviour.
**Support no logo:** I loaded the page with and without logo and checked the intended behaviour.
=> A bunch of tiny little fixes for issues I found while setting up docusaurus

lib/start-server.js
Currently any exceptions thrown during server startup cause the process to silently exit.  This makes tracking down bugs in config files super frustrating.
Add this, see an error with a stack trace for my broken config.
=> Rethrow promise errors

lib/static/css/main.css
Fix this issue: https://github.com/facebook/Docusaurus/issues/274
Ensure any blog posts, pages, appear the same as previous version.
=> Ensured that any H1 elements in content appear correct size

admin/testing-changes-on-Docusaurus-itself.md, lib/server/readMetadata.js, website/languages.js, website/package.json
I wanted to get it working locally and ran into a couple of difficulties
Ensure the new package.json file works on Mac, Windows and Linux
Ensure that the included documentation works on the above platforms also.
=> Fixes to testing guide (for Windows only)

CONTRIBUTING.md
This PR fixes the incorrect documentation link in contributing.md file
=> Fixes documentation link in contributing.md

docs/api-doc-markdown.md
=> Fix typo in docs (form of it’s)

docs/api-site-config.md
=> add docs for wrapPagesHTML

.gitignore, README.md
Fix the wrong link
This is not related to code, not testing required. Only correct the link.
None
#340
=> Fix wrong link to Contributing Guide

website/core/Footer.js
if a project has no icon and if it's possible to hide it in the header then I also want to hide it in the footer.
=> Allow hiding footer icon

docs/getting-started-preparation.md
Type less & do the same
None, plain Yarn/Npm default behavior
=> Remove uneeded run in syntax to run local server

lib/server/translate.js
Need this because of https://github.com/facebook/Docusaurus/pull/316
We never had a case where we may not have had a language set until #316. So we need to make sure we handle that for translating strings.
Tested locally on docusaurus.io, React Native, Reason React
#316
=> Check English translation if language doesn't exist

CHANGELOG.md, package-lock.json, package.json
Publishing v1.0.4 to npm and a release to GitHub
Tested commits that make up this release
N/A
=> Publish Docusaurus v1.0.4

.circleci/config.yml
Use our `docusaurus-bot` for publishing instead of the generic `facebook-bot`.
doitlive
N/A
=> Use docusaurus-bot for publishing

CHANGELOG.md, package-lock.json, package.json
Publish a new version of Docusaurus.
Tested commits contained in this version.
See the [CHANGELOG](https://github.com/facebook/Docusaurus/blob/master/CHANGELOG.md).
=> Publish Docusaurus v1.0.5

docs/getting-started-installation.md
Change 
> Docusaurus was designed from the ground up to be easily installed and used to get your website up **an** running quickly.
to
> Docusaurus was designed from the ground up to be easily installed and used to get your website up **and** running quickly.
To correct a simple typo in Docusaurus Installation Guide
No code was changed.
No changes to functionality.
=> Correct typo in getting-started-installation.md

docs/api-site-config.md, examples/basics/siteConfig.js
Add some more details on configurable fonts
Local testing on the Docusaurus site
N/A
=> Add more details on configurable fonts

CONTRIBUTING.md, README.md, website/pages/en/help.js
We now have an additional support structure.
Checked help page locally
N/A
=> Add links to Discord channels

CONTRIBUTING.md, README.md, website/pages/en/help.js
Instead of random Discord URL, we now have a Docusaurus specific one.
Ran site locally
N/A
=> Use Discord vanity URL

lib/server/sitemap.js
I removed three variables which are not used.
```
const blogFolder = path.resolve('../blog/');
const blogRootURL = siteConfig.url + '/blog';
const jestImage = siteConfig.url + siteConfig.headerIcon;
```
#429 
Thank you. :)
=> Remove dead code in sitemap.js

docs/getting-started-publishing.md
Clarify publishing based on comments in #253 
Closes #253
Visual
N/A
=> Clarify publishing to a user or organization page

docs/api-site-config.md
I have alphabetically changed the order of the fields in the site-config section of the api docs.
Controlled it by manually reading and checking the order of initial letters.
It does not effect functionality.
=> Organize siteConfig.js options documentation page better #436

docs/api-doc-markdown.md
=> removed superfluous apostrophes from "it's" (2 places)

CHANGELOG.md, package-lock.json, package.json
Hotfix release. Fixes versioning. 
Adds mobile header link scrolling and doc fix.
Tested locally
N/A
=> Publish Docusaurus v1.0.7

website/siteConfig.js
Cause we're using `Docusaurus` as well
=> Add Goby to user list

lib/publish-gh-pages.js
Environment variables should have precedent over configuration file. Fix #374
=> Fix #374 environment variables have precedent over conf

CHANGELOG.md, package-lock.json, package.json
More features and fixes.
Yes
Tested all the PRs and commits included in this release
N/A
=> Publish Docusaurus v1.0.8

lib/server/server.js
This should be either 
`'versioned_docs/' + metadata.source` 
or 
`'versioned_docs', metadata.source`
=> Fix wrong versioned_docs file path

CHANGELOG.md, package-lock.json, package.json
Hotfix release to fix versioned_docs path issue
Yes
local testing
https://github.com/facebook/Docusaurus/pull/499
=> Publish Docusaurus v1.0.9

admin/testing-changes-on-Docusaurus-itself.md, lib/server/sitemap.js
Just fix two typos
Yes
no code change, just a doc improvement.
=> Fix two typos

docs/api-site-config.md, examples/basics/siteConfig.js
e.g., 
- make `organizationName` required.
- correct some issues with the example config
Yes
Locally
N/A
=> Update siteConfig example and docs

website/languages.js, website/package.json, website/pages/en/about-slash.js, website/pages/en/help.js, website/pages/en/index.js, website/pages/en/users.js
Let's enable the translation feature for the main Docusaurus website!
There are some translations for Spanish for Docusaurus -- not complete, but still a good start to enable for our site.
I figure it is time to enable all the crucial features that the project provides for its main site, huh? 😄 
Yes
Local
N/A
=> Enable Translations for docusaurus.io

website/blog/2017-12-14-introducing-docusaurus.md
=> Small sentence change in blog post

CHANGELOG.md, package-lock.json, package.json
Ship fixes and additions
Yes
Current commits already tested
N/A
=> Publish Docusaurus v1.0.11

lib/static/css/main.css
=> Fix body height by changing CSS height property to min-height

website/languages.js
Spanish translations were causing issues. Turning it off first.
Yes
Load page locally and see that the links work.
=> Switch off Espanol translations

docs/getting-started-site-creation.md
Fixes #459
Yes
Local site testing
N/A
=> Add docs for docs-based landing page

website/siteConfig.js, website/static/img/rejoiner.svg
Show that more users are using Docusaurus! These projects are by Google (or Google-affiliated) and it's nice to see that Google is using Facebook's Open Source projects for documentation.
cc @JoelMarcey Is it ok to add users without their consent? Do we need to seek their approval? If so, I can create an issue in their repo to ask for it.
Yes
NA
=> Add rejoiner project as a user

docs/getting-started-publishing.md
Came across issue with SSH and added the link to help other beginners who may have the same issue.
Helping people struggling with setup.
yes.
Looked at it locally on my GitHub fork.
=> Update documentation, add link for  SSH key

lib/static/css/main.css
Resolving the issues reported on IE11
Yes
This is a PR affecting UI so it needs to be tested on IE and other browsers.
https://github.com/facebook/Docusaurus/issues/585
=> Fix collapse of main content on "Users" page on IE11

lib/static/css/main.css
Resolving this issue https://github.com/facebook/Docusaurus/issues/647
Yes
https://github.com/facebook/Docusaurus/issues/647
=> Fix misalignment of the sidebar and the content

lib/static/css/main.css
Fixing the issue introduce when attempting to fix overlapping content caused by IE11
Yes
Test on IE11 and other browsers
=> Fix collapse of sidebar caused by #646

docs/api-commands.md
With more options in the commands, it becomes hard to read and not scalable when we add even more options. The hash link will also change everytime we do so. This PR extracts them out and puts them into a table.
I also cleaned the arguments and options up for other commands
Yes
NA. Verify in preview.
NA
=> Make CLI docs futureproof

website/data/users.json
textlint is a docusaurus user.
YES
Ran site locally.
none
=> Add textlint to users

website/data/users.json
Thanks for your hard work creating this framework!
=> Add Open Power Quality as a docusaurus site.

docs/getting-started-installation.md, docs/getting-started-preparation.md
Update the printed directory tree in the docs with the one actually shown.
Yes
Load preview site.
NA
=> Update directory tree

lib/start-server.js, package-lock.json, package.json, yarn.lock
When restart a site Docusaurus opens the site in a new tab even if it's already open. There is no functionality in `opn` to change the behavior, but `openBrowser` from `react-dev-utils/openBrowser` works fine by default.
Yes.
Start a project, wait until it opens localhost in a browser, stop the project, start again.
=> Don't open a site in a new tab if it's already open

website/data/users.json
Just adding [pnpm](https://pnpm.js.org/) to the users page
=> Add pnpm as Docusaurus user

examples/basics/gitignore
https://docusaurus.io/docs/en/next/translation.html#manual-file-sync
Docusaurus also ignore it
https://github.com/facebook/Docusaurus/blob/master/.gitignore
Yes
```
docusaurus-init
cd website
```
i18n/en.json is ignored
=> Update gitignore for docusaurus-init

crowdin.yaml, website/languages.js
We believe we sorted out some string issues we had on Crowdin. We are going to see if this works.
I also turned it on for versioned docs as well.
Fixes #564 
Yes
Local site testing
N/A
=> Reenable translations

lib/server/readMetadata.js, lib/server/utils.js
Fix code comment typo from #705 
Yes
=> fix typo on code comment

.circleci/config.yml
To hopefully resolve error 137 (memory issues)
Yes
PR will test this when Circle runs.
N/A
=> Large resource class for Circle

website/data/users.js
Add StreamPipes to the users list
Yes
See Netlify.
NA
=> Add streampipes to users

docs/getting-started-installation.md
for details see https://github.com/facebook/Docusaurus/issues/759
https://github.com/facebook/Docusaurus/issues/759#issuecomment-397022325
yes
=> [docs] add note about babel cache to upgrade guide

website/data/users.js
Adding my project to the users list! 😄
=> Add rest-hapi to users.js

docusaurus-init/README.md, docusaurus-init/package-lock.json, docusaurus-init/package.json
Modified README.md and updated package-lock.json
Fixes https://github.com/facebook/Docusaurus/issues/781
Modified README.md and updated package-lock.json
Yes
Local
N/A
=> Bump docusaurus-init to 1.0.2

lib/static/css/main.css, website/siteConfig.js
Fixes #808 
Yes
Load nav bar with both logo and non-logo:
=> Fix styles for headerTitle

lib/static/css/main.css
=> Fix edit button

website/data/users.js
=> Adds single-spa to users

docs/guides-search.md, website/siteConfig.js
Follow up from https://github.com/algolia/docsearch-scraper/pull/387#issuecomment-405884203
Yes
TBD
=> Search correct language and version for Docusaurus

README.md
Our readme first impression is too full of text. This is a very slight improvement 😄 
Yes
**Before**
**After**
https://github.com/endiliey/Docusaurus/tree/readme
=> Better readme :)

CHANGELOG.md, package.json, yarn.lock
Update jest.
For the extra config change in package.json, see https://github.com/facebook/jest/issues/6769
Yes
CI Test is passing without error
=> chore: update jest to v23

admin/prerelease.md, scripts/prerelease.sh
Successor of #876 
1. Fix small bug of only commiting changes on `website` directory
1. Create new version branch only if it doesn't exist
1. Force push to forked new version branch
Yes
=> chore: update prerelease.sh & prerelease.md

docs/getting-started-installation.md
This PR clarifies a few installation points that we ran into when installing Docusaurus for https://docs.nteract.io
Contributing back to a project that we find very useful and hope it helps future users.
Yes
=> Update installation doc

website/data/users.js
As suggested by @yangshun in PR #888, I've submitted the nteract project as a user.
We :heart: Docusaurus.
Yes.
=> Add nteract project as a user

docs/guides-navigation.md
* The phrase "It has no inherit meaning" should probably be "It has no inherent meaning".
Minor phrasing issue in the docs. I created an issue for it. Close #944 
Yes, I have, and I couldn't find any issue referencing this specific case.
Just a minor documentation change. 
None. 
=> Fix minor documentation wording issue

README.md
Removes links which are not required from Sponsors section.
Fixes https://github.com/facebook/Docusaurus/issues/950
Sometimes the browser shows a broken image icon. Removing the links would fix this.
=> Update Sponsor image issue(#950)

website/core/Footer.js
Fixes #906
Fix FB like button text at the footer
Yes
NA
=> Use dark mode color scheme for footer like button

CONTRIBUTING.md
Recommend `semantic commit messages` for commit style
Yes
=> docs: recommend semantic commit messages style

v1/website/data/users.js
Skip is now a user!
Yes
Local
N/A
=> Add Skip to users

v2/lib/theme/Footer/index.js, v2/lib/theme/Footer/styles.css
There's still lots of work to do to make it complete but at least there's a decent looking footer now.
=> style(v2): add static footer component

v2/.eslintrc.js, v2/lib/load/docs/metadata.js, v2/lib/load/docs/order.js, v2/lib/theme/Sidebar/index.js, v2/lib/theme/Sidebar/styles.css, v2/package.json, v2/test/load/docs/order.test.js, v2/website/sidebars.json, v2/yarn.lock
Enable subcategories in v2.
Yes
https://deploy-preview-1021--munseo-preview.netlify.com/docs/docusaurus
=> feat(v2): enable subcategories

docs/api-commands.md
=> docs: document process.env.BROWSER

v2/lib/theme/Docs/index.js, v2/lib/theme/Docs/styles.css, v2/lib/theme/DocsPaginator/index.js, v2/lib/theme/DocsPaginator/styles.css, v2/lib/theme/Sidebar/styles.css
Skin the page navigation components
=> feat(v2): skin paginator component

package.json, v1/package.json, v1/yarn.lock, v2/package.json, yarn.lock
Introduce finer-grain Prettier commands so that we can run Prettier only on the projects we are working on. 
Yes.
Run the commands `yarn prettier` in v1, v2 and root.
=> chore: finer-grain per-project Prettier commands

v1/website/data/users.js
Added Stackery to users.js as requested by @JoelMarcey 
Yes
It just works!
None
=> Added Stackery logo and site

v1/website/pages/en/users.js
The previous link led to a 404 page.
Yes
=> fix: users edit link

v2/lib/webpack/base.js, v2/lib/webpack/loader/markdown.js
Prioritize node_modules so React or other pkg can resolve outside node module
Yes
Locally works. No `can't resolve React outside blablabla`
=> fix(v2): prioritize node_modules resolve

v2/lib/commands/start.js, v2/lib/load/docs/sidebars.js
#981 
**Disclaimer: This will only works in v2**
Yes
See this GIF
Might not close #981 since its not yet solved in v1
=> feat(v2): live reload sidebars.json

scripts/prerelease.sh, v1/babel.config.js, v1/jest.transform.js, v1/lib/__tests__/build-files.test.js, v1/lib/server/__tests__/__fixtures__/metadata-subcategories.js, v1/lib/server/__tests__/__fixtures__/metadata.js, v1/lib/server/__tests__/__fixtures__/sidebar-subcategories.js, v1/website/data/users.js, v1/website/static/css/code-blocks-buttons.css, v1/website/static/js/code-blocks-buttons.js
Fix Internal Task T35568553 - facebook/Docusaurus is failing open source requirements.
Yes
CI.
NA
=> chore(v1): add Facebook copyright headers

v1/lib/server/__tests__/__snapshots__/utils.test.js.snap, v2/lib/load/routes.js, v2/website/pages/index.js
https://medium.com/webpack/link-rel-prefetch-preload-in-webpack-51a52358f84c
Prefetch on idle time so that there will be better User Experience instead of seeing loading screen everytime
In addition, i modified the pages/index.js to prevent memory leak due to unresolved setInterval
Yes
Better UX on production. Less loading screen
https://deploy-preview-1071--munseo-preview.netlify.com/
=> feat(v2): webpack prefetch for better UX

v2/.eslintrc.js, v2/package.json, v2/website/pages/index.js, v2/yarn.lock
Use the latest and greatest features in React - [Hooks](https://reactjs.org/docs/hooks-intro.html)!
Yes
Load locally. Verified working on SSR also.
NA
=> refactor(v2): use React hooks!

docs/getting-started-preparation.md
fixing #1082
Documenting undocumented stuff.
Of course.
I just changed documentation, it's valid English and markdown. 
No.
=> docs: mention about website directory naming

v1/website/data/users.js
Added smash.gg with logo to the list of users for Docusaurus
=> docs: add smash.gg to users

v1/website/data/users.js
My motivation is simple **GulpJS** uses **Docusaurus** for its website enough said
Yes
No Tests Yet
=> docs: add Gulp to users

v1/website/data/users.js
@yangshun 
I add Node SerialPort with reference to #1080
=> docs: showcase user Node SerialPort

README.md, v2/website/blog/2018-04-30-How-I-Converted-Profilo-To-Docusaurus.md
I missed a couple things in #1224 :(
=> Remove more references to code.facebook.com

v1/website/data/users.js
=> docs: add Polymath to users

v2/lib/load/config.js, v2/lib/theme/Navbar/index.js, v2/lib/theme/Navbar/styles.module.css
Initially wanted to fix v2 header css but changed my mind since we will be undergoing a css revamp later on. So just minor nits logic update
Yes
Locally and netlify
=> chore(v2): update header logic

v1/website/static/css/custom.css
Fix the white bar below the announcement.
Yes
See Netlify preview.
#1290
=> fix: empty white bar on landing page

packages/docusaurus-1.x/examples/versions/pages/en/versions.js
=> fix: autogenerated versions.js should not be confusing

website/pages/index.js, website/pages/styles.module.css
Modify v2 home page to be similar to v1 a little bit. Just copy paste 👍 
Yes
Before
After
=> chore(v2): modify docusaurus-2 homepage

packages/docusaurus/bin/docusaurus.js, packages/docusaurus/lib/commands/build.js, packages/docusaurus/lib/load/docs/index.js, packages/docusaurus/lib/load/index.js, packages/docusaurus/test/load/docs/index.test.js
Small refactoring after #1292 on v2
Yes
CI and locally
=> refactor(v2): cli and loads

CONTRIBUTING.md, website-1.x/versioned_docs/version-1.0.x/guides-blog.md, website-1.x/versioned_docs/version-1.2.x/guides-blog.md, website-1.x/versioned_docs/version-1.3.x/guides-blog.md, website-1.x/versioned_docs/version-1.5.x/getting-started-publishing.md, website-1.x/versioned_docs/version-1.6.x/getting-started-publishing.md, website-1.x/versioned_docs/version-1.7.3/getting-started-publishing.md
Make v1 versioned docs MDX-compatible so that we can use it to test versions implementation on v2.
Yes
Netlify.
=> misc: make v1 versioned docs MDX-compatible

packages/docusaurus/lib/core/clientEntry.js, packages/docusaurus/lib/core/index.html.template.ejs
Make the app root ID unique so that it's easier hook into if we have a need to. A side effect of this is that it's easier to tell whether a site is using Docusaurus. 
Yes
Netlify
=> feat(v2): use __docusaurus as app root id

packages/docusaurus/lib/webpack/server.js
Fix the annoying warning in #1322 
Yes
Netlify
=> fix(v2): webpack ejs warning during build

website-1.x/data/users.js
https://graphql-compose.github.io/
=> add graphql-compose to users.js

packages/docusaurus/lib/core/serverEntry.js, packages/docusaurus/lib/webpack/base.js, packages/docusaurus/lib/webpack/client.js, packages/docusaurus/lib/webpack/server.js, packages/docusaurus/package.json, yarn.lock
- Simplifying stuff by just using one manifest plugin. Save extra dependencies and reduce lines of code ...
- No need to bundle node_modules on server with https://www.npmjs.com/package/webpack-node-externals
- Upgrade webpack
Yes
- Locally nothing changes in production and development😄 
- Netlify
=> refactor(v2): simplify + optimize server

packages/docusaurus/lib/commands/start.js, packages/docusaurus/lib/webpack/client.js
Separate runtime chunk from main. Gatsby, CRA and many other tool do this too
Yes
=> feat(v2): separate runtimechunk

packages/docusaurus-1.x/examples/basics/siteConfig.js, packages/docusaurus-1.x/lib/copy-examples.js
Fixes #1269 
Yes.
I wasn't sure how to locally test changes to ```copy-examples.js```, so below is the process I used to confirm my changes were working as expected:
1. Created empty directory ```testSite``` in my Docusaurus directory and initialized docusaurus
2. Deleted ```siteConfig.js``` and then manually run ```packages/docusaurus-1.x/lib/copy-examples.js``` (which is where I made my changes), and check if the color values would change in the newly created ```siteConfig.js```
=> feat: random color scheme in siteConfig

README.md
I noticed that the badges on your [README.md](https://github.com/facebook/Docusaurus/blob/master/README.md) are not consistent. I have made a slight change to make them consistent. 
Before:
<a href="https://github.com/prettier/prettier"><img alt="code style: prettier" src="https://img.shields.io/badge/code_style-prettier-ff69b4.svg?style=flat-square"></a>
After:
<a href="https://github.com/prettier/prettier"><img alt="code style: prettier" src="https://img.shields.io/badge/code_style-prettier-ff69b4.svg"></a>
[Here](https://github.com/Alan-Cha/Docusaurus/blob/master/README.md) is how the badges look on my fork. 
Yes, I have read the contribution guidelines. 
Not applicable. This is just a slight change to the documentation. No source code has been changed. 
This pull request does not add …
=> docs: consistent badge style

packages/docusaurus-plugin-content-blog/src/index.js, packages/docusaurus-plugin-content-docs/src/index.js, packages/docusaurus-plugin-content-pages/src/index.js, packages/docusaurus/lib/server/load/routes.js
Enable exact for addRoute API
Yes
- Locally seems OK
- Production (Netlify)
=> feat(v2): enable exact for addRoute API

packages/docusaurus/lib/default-theme/DocBody/index.js, packages/docusaurus/lib/default-theme/Post/index.js, website/docusaurus.config.js
- Fix sitemap
- Add `<header>` and `<article>` so that algolia crawler can index the correct content
Yes
- Locally nothing breaks.
- Netlify
cc @s-pace
=> chore(v2): make site algolia compliant

docs/getting-started-installation.md
Just saw a need and thought I'd help make the docs reflect what's been installed.
yes
This was a doc only change.
None
=> docs: docs-examples-from-docusaurus is now installed as doc

packages/docusaurus-plugin-content-docs/src/index.js, packages/docusaurus/lib/default-theme/Doc/index.js, packages/docusaurus/lib/default-theme/DocBody/index.js, website/docs/introduction.md, website/docusaurus.config.js, website/sidebars-legacy.json, website/sidebars.json
Display v1 docs temporarily and start showing v2 docs
yes
=> chore(v2): add tbd v2 docs

packages/docusaurus-1.x/lib/static/css/main.css
Fixes #1405 : Due to un-specified background colour in the body tag, in few browser(Steam) the background colour was black. Now background colour is set to white as default.
Yes !
Testing in steam browser to check the background colour.
=> fix: make body background white

packages/docusaurus-plugin-content-blog/src/index.js
Minor refactoring for consistency especially on windows
Yes
Everything still works locally
Netlify (TBD)
=> chore(v2): use normalizeUrl instead of path.join

packages/docusaurus-mdx-loader/package.json, packages/docusaurus-mdx-loader/src/rightToc/__tests__/index.test.js, packages/docusaurus-plugin-content-blog/package.json, packages/docusaurus-plugin-content-docs/package.json, packages/docusaurus-plugin-content-docs/src/__tests__/metadata.test.js, packages/docusaurus-plugin-content-pages/package.json, packages/docusaurus-plugin-sitemap/package.json, packages/docusaurus-preset-classic/package.json, packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-search-algolia/package.json, packages/docusaurus/package.json, packages/docusaurus/src/server/load/__tests__/presets.test.js, packages/docusaurus/src/server/load/loadSetup.js, packages/docusaurus/src/webpack/__tests__/utils.test.js, yarn.lock
Fix problem found in alpha.14. Will release alpha.15 soon
Yes
=>  fix(v2): fix wrong dependency problem

docs/tutorial-create-pages.md
Make it clear to new users where unfamiliar files are.
:+1: 
No changes to the code; just clarified where a file lives.
In #1468 we clarify where the `docs` folder is. 
Here, in this PR, we make it clear where `sidebars.json` is.
=> docs: clarify location of sidebars.json

packages/docusaurus-1.x/lib/server/generate.js, packages/docusaurus-1.x/lib/server/readMetadata.js
Fix missing CLI commands due to skipNextRelease flag swallowing all other cli commands argv
Close #1427 
See https://github.com/facebook/Docusaurus/pull/1292#discussion_r267671269 for more context.
Yes
Before
yarn start --help
After
yarn build --help
Yarn start --help
=> fix: missing cli commands

packages/docusaurus-theme-classic/src/theme/Navbar/index.js, packages/docusaurus/CHANGES.md, packages/docusaurus/src/server/load/__tests__/__fixtures__/custom-site/docusaurus.config.js, packages/docusaurus/src/server/load/__tests__/__fixtures__/simple-site/docusaurus.config.js, packages/docusaurus/src/server/load/__tests__/config.test.js, packages/docusaurus/src/server/load/config.js, website/docusaurus.config.js
`headerLinks` is dead, long live `navbar`!
Yes
See Netlify.
=> feat(v2): move navbar config into themeConfig

packages/docusaurus/bin/docusaurus.js, packages/docusaurus/src/commands/start.js, website/docs/cli.md
Yes
- Netlify works
- Locally works
=> chore: remove noWatch cli options because you cant disable watch in wds

website-1.x/data/users.js
=> docs: remove pin non-fb-project

website/docs/introduction.md
Add docs for introduction and comparison with other tools. Please help to improve it
cc @wgao19 as well
Yes
- Local Development
- Netlify
https://deploy-preview-1501--docusaurus-2.netlify.com/docs/introduction
=> docs(v2): introduction

packages/docusaurus-1.x/examples/basics/core/Footer.js
make the web more secure!
YEP
https://stackoverflow.com/questions/tagged/ - works
=> misc: https link to stackoverflow.com in v1 example

docs/guides-custom-pages.md
=> docs: fix typo in website/pages folder structure

packages/docusaurus-plugin-content-blog/src/theme/BlogListPaginator/index.js, packages/docusaurus-plugin-content-blog/src/theme/BlogPostPaginator/index.js, packages/docusaurus-plugin-content-docs/src/theme/DocPaginator/index.js
Make the pagination buttons nicer.
Yes.
=> feat(v2): use new pagination nav CSS

packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/Navbar/index.js, packages/docusaurus-theme-classic/src/theme/Navbar/styles.css, yarn.lock
persistent & responsive dark mode toggle
Yes
https://deploy-preview-1521--docusaurus-2.netlify.com/
P.S: Open for improvement and collaboration
=> feat(v2): persistent & responsive dark mode toggle

packages/docusaurus-1.x/lib/static/css/main.css
This PR fixes formatting issues in main.css
Yes
Local Testing
None
=> style: fixes formatting issues in main.css

docs/tutorial-create-pages.md
Some of the wording was a bit clunky, so wanted to clean it up a bit and put relevant related information together.
Yes
None, only proposing minor changes to the docs.
=> docs: clarify wording/grammar for create pages tutorial

docs/tutorial-create-new-site.md
Some of the wording was a bit clunky, so wanted to clean it up a bit and put relevant related information together.
Yes
None, only proposing minor changes to the docs.
#1536
=> docs: clean up language in create new site tutorial

packages/docusaurus/src/server/index.ts
Minor refactoring to avoid await blocking other code running
yes
Nothing wrong with development. Still works
=> fix(v2): dont block nodejs loop with await randomly

website/docs/configuration.md, website/docs/docusaurus.config.js.md, website/sidebars.js
Add v2 configuration docs
Yes
NA
NA
=> docs(v2): Configuration

packages/docusaurus/src/commands/start.ts, packages/docusaurus/src/server/config.ts, packages/docusaurus/src/server/index.ts, packages/docusaurus/src/server/plugins/index.ts, packages/docusaurus/src/server/presets/index.ts, packages/docusaurus/src/server/themes/alias.ts, packages/docusaurus/src/server/themes/index.ts
Better typing ftw! With this PR, the server-side code should be mostly covered.
So that we can move fast and don't break things 🔥 
Yes
Site builds. No errors.
NA
=> misc(v2): add more typing for server code

packages/docusaurus/src/server/routes.ts, packages/docusaurus/src/webpack/base.ts, packages/docusaurus/src/webpack/utils.ts
#1518 change `Boolean` to `boolean`, but he doesn't change all
yes
N/A ()
#1518
=> chore(v2): use `boolean`  instead of `Boolean` for type

docs/guides-blog.md
Found typo in guides-blog.md
Yes
NA, just docs.
NA
=> docs: typo in guides-blog.md

packages/docusaurus/src/client/App.js, packages/docusaurus/src/server/client-modules/__tests__/__fixtures__/plugin-empty.js, packages/docusaurus/src/server/client-modules/__tests__/__fixtures__/plugin-foo-bar.js, packages/docusaurus/src/server/client-modules/__tests__/__fixtures__/plugin-hello-world.js, packages/docusaurus/src/server/client-modules/__tests__/index.test.ts, packages/docusaurus/src/server/client-modules/index.ts, packages/docusaurus/src/server/index.ts, packages/docusaurus/src/server/plugins/index.ts, website/docs/plugins-api.md
Implement client modules API for plugins to define what modules they want to import on the client.
Yes
Unit tests. I tested locally with some client modules but didn't commit it. Next step is to import Infima as a client module.
NA.
=> feat(v2): implement client modules API

packages/docusaurus/package.json, packages/docusaurus/src/client/docusaurus.js, packages/docusaurus/src/webpack/base.ts, yarn.lock
Minify css with https://github.com/NMFR/optimize-css-assets-webpack-plugin
Under the hood it uses cssnano
extra:
minor refactoring on prefetch preload logic to increase web performance. Prefetch < preload
yes
before
after
=> feat(v2): minify css

packages/docusaurus-theme-classic/package.json, website/components/BrowserWindow/index.js, yarn.lock
Preparing for 2.0.0-alpha.19 release.
Yes
Preview.
=> chore(v2): upgrade Infima to 0.2.0-alpha.2

website/components/BrowserWindow/index.js, website/components/BrowserWindow/styles.module.css
Fix browser window styles on smaller screen.
Yes.
NA
=> fix(v2): browser window styles on smaller screen

website/docs/configuration.md, website/docs/writing-docs.mdx
- minor revisions on live coding docs
Yes
NA
NA
=> docs(v2): minor revisions on live coding docs

website/docs/introduction.md
Revise docs introduction
Yes
NA
NA
=> docs(v2): revise introduction

package.json, yarn.lock
=> chore(v2): upgrade typescript deps

packages/docusaurus/templates/classic/docs/doc1.md, packages/docusaurus/templates/classic/docs/exampledoc4.md, website/docs/installation.md
Refine installation doc
- generated site to match what is described in the doc
- minor changes in the installation page
- title generated doc1 to "Style Guide" to tell users what purpose it serves
Yes
NA
NA
=> chore(v2): tweak installation doc

packages/docusaurus/src/commands/init.ts
- Eliminate code redundancy.
- Format code as per prettier standards.
=> chore: minor refactor and prettify code

website/docs/plugins.md, website/docs/using-plugins.md
=> docs(v2): plugins

website/docs/styling-layout.md
Add docs on styling.
@yangshun, at this point, is it OK to doc about using Infima?
Yes
NA
NA
=> docs(v2): initialize doc on styling

packages/docusaurus-utils/src/index.ts
An attempt made to introduces a couple of refactoring, so as to have a more concise code-base.
Follow up of #1631
=> misc(v2): refactor utils code to be slightly more concise

website/docs/deployment.md
CNAME config is supported in V1 but has no mention in V2.
Yes.
=> docs(v2): add docs about CNAME support in deployment

website/docs/static-assets.md
part of #1640  Guides / Docs / Static Assets
yes
netlify tbd
https://deploy-preview-1648--docusaurus-2.netlify.com/docs/static-assets
=> docs(v2): add docs on static assets

packages/docusaurus-theme-classic/src/theme/Layout/index.js, website/docusaurus.config.js, website/src/pages/index.js
Add more essential meta tags especially viewport 
<meta charset="utf-8"> Sets character encoding to utf-8 which is going to work for most cases. Can be changed to different character set as needed.
yes
Verify on discord and twitter with netlify preview
tbd
=> feat(v2): add more essential meta tags

website-1.x/data/users.js, website-1.x/static/img/users/almond.svg
I created PR almond-sh/almond#362
and they accepted
yes
Image in preview
=> docs: showcase user Almond

packages/docusaurus/CHANGELOG.md, packages/docusaurus/src/webpack/base.ts
=> fix(v2): fix babel-loader not transpiling docusaurus package

packages/docusaurus-1.x/lib/core/DocsLayout.js
Fix #1066
yes
n/a cos this basically revert regression introduced in https://github.com/facebook/Docusaurus/pull/1054
=> fix: dont render html for meta description

packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js, packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js, website/docs/markdown-features.mdx, yarn.lock
Allow user to customize the syntax highlighting theme easily. See test plan
yes
See gif below
Test it ?
```js
// docusaurus.config.js
themeConfig: {
prismTheme: require('prism-react-renderer/themes/vsDark')
}
};
```
=> feat(v2): allow custom syntax highlighting theme

packages/docusaurus-plugin-content-blog/src/index.js
https://v2.docusaurus.io/feedback/p/blog-support-id-field
yes
Local test with different id for blog, can access by the id
NO
=> feat(v2): add support for front matter id in blog

CHANGELOG-2.x.md, packages/docusaurus-init/templates/classic/blog/2019-05-28-hola.md, packages/docusaurus-init/templates/classic/blog/2019-05-29-hello-world.md, packages/docusaurus-init/templates/classic/blog/2019-05-30-welcome.md
- Move v2 CHANGELOG to repo root for better discoverability
- Update classic blog template
Yes
Tested classic template locally.
=> chore(v2): shift v2 CHANGELOG and update classic template

packages/docusaurus-1.x/lib/static/css/main.css
Fix the layout issue that occurs on IE11.
Fixes #985.
Yes.
Visual test on Windows machine running IE11.
N.A.
=> fix: content aligning breaks at IE11

CHANGELOG-2.x.md, package.json, packages/docusaurus/src/webpack/base.ts, yarn.lock
https://webpack.js.org/guides/caching/
https://github.com/webpack/webpack.js.org/issues/2096
yes
-yarn build works. consistent hash
- ci
=> feat(v2): use contenthash instead of chunkhash for longterm caching

website/docs/contributing.md
Addressing #1640, add docs for contributing for v2.
Copied over CONTRIBUTING.md from root and reorganized for v2.
Yes
NA
#1640
=> docs(v2): contributing for v2

docs/tutorial-setup.md
Add a `cd` step before clone in **[Setting Up](https://docusaurus.io/docs/en/next/tutorial-setup)**, add examples of `cd` in steps 5 and 7, and edit other steps.
=> docs: add a cd step before clone in "Setting Up"

docs/tutorial-create-pages.md
A few extra details to help noobs.
=> docs: say that a page is a text file and link to editors

docs/tutorial-create-new-site.md
=> docs: fix the step numbering in "Scaffold the Site"

website/docs/analytics.md
Fix a typo in v2 docs
Yes
NA
NA
=> chore(v2): typos

website/docs/search.md
#1640 
Search section
yes
Netlify
=> docs(v2): search - algolia and custom

packages/docusaurus-1.x/lib/static/css/main.css
=> fix: footer links margin

packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.js
https://github.com/facebook/docusaurus/issues/1669
/blog/tags will crash if tags contain cjk
yes
Add a cjk tag in blog
n/a
=> feat(v2): blog tags support cjk

yarn.lock
Fix some security vulnerabilities:
Package name: mixin-deep
Affected versions: < 1.3.2
Fixed in version: 1.3.2
Severity: HIGH
Package name: set-value
Affected versions: < 2.0.1
Fixed in version: 2.0.1
Severity: CRITICAL
Package name: remarkable
Affected versions: <= 1.7.1
Fixed in version: 1.7.4
Severity: HIGH
Package name: lodash
Affected versions: < 4.17.13
Fixed in version: 4.17.13
Severity: HIGH
Package name: lodash.merge
Affected versions: < 4.6.2
Fixed in version: 4.6.2
Severity: HIGH
Yes
Netlify
-
=> chore(v1): upgrade deps

CHANGELOG-2.x.md, packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.js, packages/docusaurus-theme-classic/src/theme/BlogPostItem/styles.module.css, packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.js
Make blog title just a bit larger. I'd change it to be 3rem if you're ok with it Endilie.
P.S. I'm surprised how little custom styles we needed to write for the blog components.
Yes
See Netlify, just CSS changes.
=> misc(v2): change blog title size

website/docs/static-assets.md
Saw a typo at the start of the docs and started editing it, ended up changing more than what I originally intended to.
Yes
See the static assets page
=> docs(v2): improve static assets docs

packages/docusaurus-theme-classic/src/theme/DocItem/index.js
Improve the UI a little bit. Feel free to close/ reject if it doesnt look nice
yes
before
after
=> styles(v2): improve 'Edit this page' UI

CONTRIBUTING.md
As I was following the contribution guidelines I've noticed that the installation instructions are wrong. This PR is hopefully fixing it 🤞
=> docs: improve installation instructions in contribution guidelines

packages/docusaurus-types/src/index.d.ts, packages/docusaurus/bin/docusaurus.js, packages/docusaurus/src/commands/build.ts, packages/docusaurus/src/commands/start.ts, packages/docusaurus/src/server/index.ts, packages/docusaurus/src/server/presets/index.ts, packages/docusaurus/src/webpack/base.ts, website/docs/advanced-plugins.md
Refactoring
- Fix typo in docs
- Improve and fix typing
- Remove dead code   
yes
- yarn tsc compile
- Local dev server still work :)
- Netlify
- CI
=> refactor(v2): fix and improve typing

website/docs/migrating-from-v1-to-v2.md
This change is regarding an issue opened at here 
Fix #1841 
Helps users in migrating from v1 to v2 of docusaurus.
yes
=> docs(v2): update sidebar migration from v1 to v2 guide

CHANGELOG-2.x.md, packages/docusaurus/package.json, packages/docusaurus/src/webpack/utils.ts, website/docs/migrating-from-v1-to-v2.md, yarn.lock
HOTFIX for alpha.28
yes
yarn workspace docusaurus-2-classic-template build
Before
After
=> fix(v2): fix missing deps and wrong babel config

CHANGELOG-2.x.md, packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/Navbar/index.js, packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js, yarn.lock
Close #1878 #1887 
Update infima and fix the breaking css class. Hopefully those who swizzled can fix their broken site
yes
<a href="https://ibb.co/18bkx4Q"><img src="https://i.ibb.co/MM9mLJS/1.png" alt="1" border="0"></a>
<a href="https://ibb.co/vwfgCWL"><img src="https://i.ibb.co/j6qB9Y3/2.png" alt="2" border="0"></a>
=> styles(v2): update infima and fix styles

website-1.x/data/users.js
Remove Vasern because the site is no longer available (Broken Link).
Ensuring that users can find out who is using Docusaurus.
Yes
=> docs(v1): remove broken link for user Vasern

README.md
Fix Broken Link.
Change _https://docusaurus.io/docs/en/blog.html_ to _https://docusaurus.io/blog/_
Ensuring that users can visit blogs correctly.
Yes
=> misc: update URLs to non-HTML versions

CHANGELOG-2.x.md, packages/docusaurus-theme-search-algolia/src/theme/SearchBar/styles.css
Fix #1851 
yes
Search for 'cool' in docusaurus
Before
<a href="https://ibb.co/1Jz2xQJ"><img src="https://i.ibb.co/mFNz7TF/before2.png" alt="before2" border="0"></a>
After
<a href="https://ibb.co/8953qY2"><img src="https://i.ibb.co/jDMKmJG/after2.png" alt="after2" border="0"></a>
Using this algolia key
```js
algolia: {
apiKey: '062377f2ac2d588380929aafb76a76ab',
indexName: 'react-isomorphic-data',
algoliaOptions: {},
},
```
Type "with" or "use" into the searchbar.
Before:
<a href="https://ibb.co/xgNmyxY"><img src="https://i.ibb.co/PWdTRqM/before.png" alt="before" border="0"></a>
After:
<a href="https://ibb.co/x7m3SSH"><img src="https://i.ibb.co/1msbff6/after.png" alt="after" border="0"></a> …
=> fix(v2): missing/hidden algolia search suggestion result

website/docs/advanced-plugins.md
=> docs(v2): fix typo

website/docs/installation.md, website/docs/presets.md
Fix minor typos in the docs.
Yes
=> docs(v2): fix typos

CHANGELOG.md
Fix broken links in CHANGELOG
Yes
1. Click on the two fixed links in the Markdown rich preview.
None
=> docs(v1): fix links in CHANGELOG

packages/docusaurus-1.x/examples/basics/Dockerfile
This is much stable and more performant
=> misc(v1): use Node.js lts version

website/docs/styling-layout.md
Change Infima website to the WIP component site
Yes
Preview
=> fix(v2): update Infima website URL

website/docs/lifecycle-apis.md
Fix incorrect API documentation from #1960.
Yes
N/A
None
=> docs(v2): update configureWebpack utility functions

packages/docusaurus-theme-classic/src/theme/DocItem/index.js, packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css
A continuation of #1964.
Yes
See HTML markup.
=> fix(v2): use tag time for showing last update of doc item

package.json, packages/docusaurus-1.x/package.json, packages/docusaurus-mdx-loader/package.json, packages/docusaurus-plugin-ideal-image/package.json, website-1.x/package.json, yarn.lock
bump & remove unused deps
yes
All CI pass
=> chore: bump & remove unused deps

packages/docusaurus/src/webpack/__tests__/base.test.ts, packages/docusaurus/src/webpack/base.ts
Sort of related to #1868
Adding tests to prevent regression
yes
- Netlify
- Newly added test passes
=> test(v2): babel exclude transpilation logic to prevent regression

website/src/plugins/remark-npm2yarn.js
Just the correct spelling of Yarn. 
@endiliey awesome idea with this tabs :clap: 
Yes
See markup.
=> fix(v2): make proper spelling of Yarn in tabs

website/docs/installation.md, website/versioned_docs/version-2.0.0-alpha.36/installation.md
=> docs(v2): make proper spelling of Stack Overflow

website/src/pages/versions.js
For SEO purposes, it’s important that there is h1 on any page.
Yes
=> fix(v2): add h1 to versions page

website/docs/contributing.md, website/docs/introduction.md, website/docs/sidebar.md, website/docs/static-assets.md, website/docs/styling-layout.md
Quick proofread & minimal docs update
yes
=> docs(v2): quick proofread docs

packages/docusaurus-plugin-content-blog/src/index.ts, packages/docusaurus-plugin-content-blog/src/types.ts
Fix typing, no logic change. So everything can autocomplete and blog plugin can meet our plugin types
yes
- Locally no compile error
- Build ok
- Dev ok
Just waiting CI
=> refactor(v2): stronger typing for blog plugin

packages/docusaurus-mdx-loader/README.md
=> misc(v2): update mdx loader plugin README

packages/docusaurus/src/client/exports/ComponentCreator.js
Minor code refactoring. Reuse https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/src/client/flat.js function in componentcreator which has test https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/src/client/__tests__/flat.test.js
Since the flat function is also used in `docusaurus.js`.
For readability purpose. 
yes
Nothing broke
=> refactor(v2): minor code refactoring on component creator

packages/docusaurus-1.x/examples/basics/README.md, packages/docusaurus-1.x/lib/server/__tests__/readMetadata.test.js
=> docs(v1): fix path to sidebars.json in generated readme

website/src/pages/styles.module.css
I can’t pass by and not fix this annoying flaw! (just kidding :smiley: ).
Yes
| ![image](https://user-images.githubusercontent.com/4408379/70736520-92aa9300-1d21-11ea-97be-fa8a6379e161.png) | ![image](https://user-images.githubusercontent.com/4408379/70736658-d8675b80-1d21-11ea-97e3-a64a5c848ea8.png) |
=> fix(v2): align GH button in vertical center

packages/docusaurus-init/templates/facebook/.prettierignore, packages/docusaurus-init/templates/facebook/.prettierrc, packages/docusaurus-init/templates/facebook/package.json
Add Prettier to Facebook template
Yes
```
yarn ci
```
=> feat(v2): add Prettier to Facebook template

packages/docusaurus-theme-classic/src/theme/hooks/useHideableNavbar.js
Oops, overlooked this.
Yes
No changes.
=> refactor(v2): make proper import of react-router-dom

packages/docusaurus-init/templates/classic/blog/2019-05-30-welcome.md, packages/docusaurus-init/templates/facebook/blog/2019-05-30-welcome.md
Spotted a minor typo on the generated template files, so this is a simple fix!
Yup!
Don't think I need to write a test plan for this since it is a simple change in vocabulary.
N/A
=> fix(v2): change 'Simple' to 'Simply' on template blog entries

.github/CODEOWNERS, website/docs/migrating-from-v1-to-v2.md, website/versioned_docs/version-2.0.0-alpha.38/migrating-from-v1-to-v2.md, website/versioned_docs/version-2.0.0-alpha.39/migrating-from-v1-to-v2.md, website/versioned_docs/version-2.0.0-alpha.40/migrating-from-v1-to-v2.md
Let's not disturb Endi unnecessarily.
Yes
NA.
=> misc: do not disturb Endi

packages/docusaurus-1.x/lib/core/BlogPostLayout.js
Resolves #2203 
Yes
Generated site locally using a built version of docusaurus from this code
=> fix(v1): update blog href value to match navbar href

.gitpod.yml, README.md
Hi! :slightly_smiling_face:
This PR simplifies code contributions by automating the dev setup with Gitpod(A free online VS Code like IDE), with a single click it will launch a ready to code workspace with all the dependencies being pre-installed and the build & dev scripts in process, so that anyone interested in contributing can start straight away.
It seems to work well. You can give it a try on my fork of the repo via the link below:
=> feat: add Gitpod config for Docusaurus 2 

packages/docusaurus/src/client/templates/ssr.html.template.js
Reverts facebook/docusaurus#2214
=> Revert "chore(v2): handle pages which contain special chars"

.eslintrc.js, packages/docusaurus-theme-classic/src/theme/DocItem/index.js, packages/docusaurus/src/client/PendingNavigation.js
As mentioned in the PR https://github.com/facebook/docusaurus/pull/2224#discussion_r370132163 I decided that it was worth adding the corresponding rule to ESLint.
Yes
Check code style.
=> chore(eslint): require curly brackets on all blocks

website-1.x/data/users.js
Add Jafar to users
https://yahoo.github.io/jafar/
=> docs(v1): showcase user Jafar

website/src/pages/feedback/index.js
The page should contain a meaningful title.
Yes
Check meta title on Feedback page.
=> fix(v2): add title for Feedback page

packages/docusaurus-theme-classic/package.json, yarn.lock
Bump Infima version to 0.2.0-alpha.4 which contains a fix for https://github.com/facebook/create-react-app/issues/8400 and https://github.com/reduxjs/redux/issues/3688
Yes
Preview. Ran site locally on Safari, no high CPU usage.
=> chore(v2): update Infima to 0.2.0-alpha.4

website/docs/using-plugins.md
The example is using invalid syntax.
=> Make blog plugin config example valid

.github/ISSUE_TEMPLATE/bug.md
This will allow us to get more reproducible bug reports.
Yes.
Preview MD file.
=> chore: add section about env to bug issue template

website/docs/markdown-features.mdx, website/versioned_docs/version-2.0.0-alpha.39/markdown-features.mdx, website/versioned_docs/version-2.0.0-alpha.40/markdown-features.mdx, website/versioned_docs/version-2.0.0-alpha.43/markdown-features.mdx
Fix broken link
Yes
Clicking the link to see if it redirects
=> docs(v2): fix broken 'more syntax' url

CONTRIBUTING.md
Use `yarn` consistently in `CONTRIBUTING.md`
Yes
N/A
N/A
=> docs: update use of npm/yarn in contributing.md

packages/docusaurus-types/src/index.d.ts, packages/docusaurus/src/client/theme-fallback/Layout/index.js, packages/docusaurus/src/server/__tests__/config.test.ts, packages/docusaurus/src/server/config.ts, website/docs/docusaurus.config.js.md
Resolve #1969
Yes
Remove `tagline` field and try build website.
=> chore(v2): mark tagline field as optional

CONTRIBUTING.md
We often encounter some misunderstanding of versioned docs by contributors - they document new changes in versioned docs and/or fix typos only in versioned docs. It seems to me that I need to somehow clarify this.
Yes
GitHub.
=> misc: add note about edits in versioned docs

README.md
The main website https://docusaurus.io/ has a mention of v2, so it is make sense to do something similar in the `README` file. _This is draft text, so feel free to change it._
Yes
GitHub.
=> misc: mention about v2 in README file

packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/Layout/styles.css, packages/docusaurus-theme-classic/src/theme/Navbar/index.js, packages/docusaurus-theme-search-algolia/src/theme/SearchBar/algolia.css, yarn.lock
- Upgrade remark-admonitions to better support dark mode
- Migrate to sticky-positioned navbar for ease work on #2330
- Close #2121
Yes
Preview.
=> chore(v2): upgrade Infima and remark-admonitions

packages/docusaurus/package.json
=> fix(v2): add missing preset-typescript dependency

package.json
Fix tests and linting.
Yes
N/A.
=> fix(v2): specify proper version for stylelint-copyright

CHANGELOG-2.x.md
=> chore(v2): v2.0.0 alpha.47

packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/SearchBar.js
Bug fixes for new release of v2.0.0-alpha.48.
Yes
=> fix(v2): fix missing dependency and Noop component

website/docs/installation.md, website/docs/migrating-from-v1-to-v2.md, website/versioned_docs/version-2.0.0-alpha.40/migrating-from-v1-to-v2.md, website/versioned_docs/version-2.0.0-alpha.43/migrating-from-v1-to-v2.md, website/versioned_docs/version-2.0.0-alpha.48/installation.md, website/versioned_docs/version-2.0.0-alpha.48/migrating-from-v1-to-v2.md
Update alpha version on the documents to the current version alpha.48
Yes 
Not required
=> docs(v2):update alpha version to current version

website/docs/resources.md, website/sidebars.js
Resources page to guide people to related Docusaurus resources. There's nothing much here now but hopefully it expands soon!
Yes
Preview
=> docs(v2): add resources page

website/docs/deployment.md
Docs-only: warns people to disable Netlify `Pretty URLs`
=> docs:(v2): add Netlify configuration warning

CONTRIBUTING.md, README.md
=> misc: update Gitpod description

website/docusaurus.config.js
Just use dogfooding practice.
Yes
Make sure that a different logo is displayed in dark mode (Slash with keyboard).
=> polish(v2): add logo for dark mode

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js, packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js, packages/docusaurus-theme-classic/src/theme/Navbar/index.js, packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js, website/src/components/ColorGenerator/index.js
Fix most of the errors reported in PR #2403  (except that it refers to the styles).
Errors related to the pagination links will be fixed with an update Infima (in separate PR).
Yes
- Locally website still works
- Netlify builds
=> fix(v2): various improvements for accessibility

packages/docusaurus/package.json, packages/docusaurus/src/commands/start.ts, yarn.lock
Resolve #2454
Yes
Locally nothing wrong.
=> chore(v2): upgrade react-dev-utils

packages/docusaurus-init/templates/classic/docs/doc1.md, packages/docusaurus-init/templates/facebook/docs/doc1.md, website/docs/deployment.md
Closes #2452 and fixes the templates used by `@docusaurus/init`
Yes
* Created a new project using `@docusaurus/init` using the fixed template.
* Previed updated docs
* Ran `prettier-docs` and confirmed the admonitions formatting was not changed
=> fix(v2): expand broken admonitions

website/versioned_docs/version-2.0.0-alpha.48/deployment.md
Was reading Documentation and find this typo.
No
=> docs(v2): fix typo in deployment docs

packages/docusaurus-mdx-loader/package.json, packages/docusaurus-theme-classic/package.json, yarn.lock
This resolves #2441
Yes
Make sure that code blocks should render as usual on preview.
=> chore(v2): upgrade MDX to 1.5.8

packages/docusaurus-theme-classic/src/theme/BlogPostPaginator/index.js, packages/docusaurus-theme-classic/src/theme/DocPaginator/index.js
Refers to #2403 
Yes
No UI changes (this has already been changed in the new version of Infima).
=> refactor(v2): update HTML markup of pagination for better a11y

packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.js
Need to update blog styling due to Infima updates
Yes
Space between avatar and title shows up now
=> fix(v2): blog item styling

packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css, packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css
Make the code block title and copy button look nicer.
Yes
=> fix(v2): make code block nicer

packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css, website/docusaurus.config.js
Make the announcement more prominent.
Yes
=> fix(v2): tweak colors for announcement bar

website-1.x/data/users.js, website-1.x/static/img/users/lisan.svg
This adds my recently published i18n project [https://lisanjs.com](https://lisanjs.com) to the users page. 
Yup :)
=> docs(v1): add LisanJS to users

admin/publish.md
Add notes to avoid mistakes  when releasing new versions (which new contributors will make).
Yes
N/A.
=> misc: improve instructions about new release

website/docs/theme-classic.md
Resolve https://docusaurus.canny.io/feature-requests/p/expose-callback-for-dark-or-light-mode-enabled
Yes
Preview.
=> docs(v2): useThemeContext hook

website/docs/blog.md, website/docs/configuration.md, website/docs/creating-pages.md, website/docs/deployment.md, website/docs/docs.md, website/docs/installation.md, website/docs/markdown-features.mdx, website/docs/migrating-from-v1-to-v2.md, website/docs/presets.md, website/docs/search.md, website/docs/styling-layout.md, website/docs/theme-classic.md, website/docs/using-plugins.md, website/docs/using-themes.md
Misc proofreading. Use some of our new features:
- Code block title
- Inline code block highlighting
Yes
Preview
=> docs(v2): proofread docs

website/docs/team.md
This is probably a copyover from https://reactjs.org/community/team.html
Fix typo.
Yes
👀 
=> docs(v2): Fix typo in team page

packages/lqip-loader/README.md
This small PR fixes example code highlight in `lqip-loader` README file.
Yes
N/A
* #2544
=> chore(v2): fix lqip-loader README code highlight

website/docs/cli.md, website/docs/configuration.md, website/docs/markdown-features.mdx, website/docs/versioning.md
Right now, v2's docs are a bit hard to understand.  This starts to improve them.
Yup
Ran `prettier-docs`.
n/a
=> docs(v2): improve grammar

packages/docusaurus-theme-bootstrap/src/theme/BlogListPage/index.js, packages/docusaurus-theme-bootstrap/src/theme/BlogListPaginator/index.js, packages/docusaurus-theme-bootstrap/src/theme/BlogPostPage/index.js, packages/docusaurus-theme-bootstrap/src/theme/BlogPostPaginator/index.js
Add the pagination for a blog post page
yes
=> feat(v2): bootstrap blog post paginator

packages/docusaurus-init/templates/bootstrap/docusaurus.config.js, packages/docusaurus-theme-bootstrap/src/theme/BlogListPage/index.js, packages/docusaurus-theme-bootstrap/src/theme/BlogPostItem/index.js, packages/docusaurus-theme-bootstrap/src/theme/BlogTagsListPage/index.js, packages/docusaurus-theme-bootstrap/src/theme/Footer/index.js
I would like to add the footer component, right now, I only put the support for the light theme, eventually I'll do the toggle setup to ability the dark theme.
yup!
=> feat(v2): bootstrap layout footer

website/docusaurus.config.js
Fix this bug
Yes
Check the preview site to see whether the year is fixed.
=> fix(v2): Fix copyright footer

admin/scripts/test-release.sh
Just an improvement in the test release script.
Yes
N/A.
=> misc: simplify test release script

website/docs/search.md, website/versioned_docs/version-2.0.0-alpha.48/search.md, website/versioned_docs/version-2.0.0-alpha.50/search.md
Update documentation related to DocSearch (I am part of the team behind it)
Yes
=> fix(docs): mention that appID is optional

packages/docusaurus-theme-classic/src/index.js
Due to #2529
Yes
Remove from config file `theme.customCss` and build website. 
=> fix(v2): allow build website without custom css

website/docs/cli.md
I had trouble understanding the CLI for swizzling components. After a few attempts, I figured it out. To make it easier for folks, I wanted to add an example.
Yes
N/A - doc change.
N/A
=> docs: add swizzle example

packages/docusaurus-init/templates/bootstrap/docusaurus.config.js, packages/docusaurus-theme-bootstrap/src/theme/BlogListPage/index.js, packages/docusaurus-theme-bootstrap/src/theme/BlogListPaginator/index.js, packages/docusaurus-theme-bootstrap/src/theme/BlogPostPage/index.js, packages/docusaurus-theme-bootstrap/src/theme/BlogPostPaginator/index.js
For some unknown reason the files of this pr #2611 are lost, so I'm adding again.
Yes
See the test plan of #2611 
#2611
=> feat(v2): bootstrap pagination

website/docs/docusaurus-core.md, website/versioned_docs/version-2.0.0-alpha.43/docusaurus-core.md, website/versioned_docs/version-2.0.0-alpha.48/docusaurus-core.md, website/versioned_docs/version-2.0.0-alpha.50/docusaurus-core.md, website/versioned_docs/version-2.0.0-alpha.54/docusaurus-core.md
=> docs(v2): replace word append with prepend to describe useBaseUrl hook

CHANGELOG-2.x.md, packages/docusaurus-theme-bootstrap/src/theme/BlogListPaginator/index.js, packages/docusaurus-theme-bootstrap/src/theme/BlogPostPaginator/index.js, packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/BlogListPaginator/index.js, packages/docusaurus-theme-classic/src/theme/BlogPostPaginator/index.js, packages/docusaurus-theme-classic/src/theme/DocPaginator/index.js, packages/docusaurus-theme-classic/src/theme/Tabs/index.js, yarn.lock
The latest version of Infima has been extensively refactoring, so we need to update it.
For the test, I generated a website built of Redux (https://goofy-murdock-b8f04d.netlify.app/) - everything looks fine (except for pagination links, but this is OK because, because I just replaced the CSS file according latest version of Infima).
Yes
View pages of preview and Redux site with new version of Infima (https://goofy-murdock-b8f04d.netlify.app/)
=> chore(v2): upgrade Infima to 0.2.0-alpha.10

docs/getting-started-publishing.md
Fixed grammatical and typographical errors in `docs/getting-started-publishing.md`.
Yes.
View the `getting-started-publishing.md` file in `docs` and compare with the previous version of file.
=> docs: fixed getting-started-publishing.md

website/docs/deployment.md
=> docs(v2): fix typo in deployment

website/docs/team.md
Change my description
yes
go to /docs/next/team
=> docs(v2): change fanny's description

packages/docusaurus-theme-classic/src/theme/DocItem/index.js
Close #2744
Yes
See https://github.com/facebook/docusaurus/pull/2012
=> fix(v2): restore hiding of docs toc

packages/docusaurus-theme-bootstrap/package.json, packages/docusaurus-theme-bootstrap/src/theme/BlogPostItem/index.js, packages/docusaurus-theme-bootstrap/src/theme/CodeBlock/index.js, packages/docusaurus-theme-bootstrap/src/theme/MDXComponents/index.js, yarn.lock
=> feat(v2): bootstrap MDX Components

packages/docusaurus-init/templates/bootstrap/docusaurus.config.js, packages/docusaurus-init/templates/bootstrap/src/pages/index.js, packages/docusaurus-init/templates/classic/docusaurus.config.js, packages/docusaurus-init/templates/classic/src/pages/index.js, packages/docusaurus-init/templates/facebook/docusaurus.config.js, packages/docusaurus-init/templates/facebook/src/pages/index.js, website/docusaurus.config.js
As requested in https://github.com/facebook/docusaurus/pull/2652#issuecomment-629781310
Yes
N/A.
=> chore(v2): mention about docs home page in init templates

packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/DocItem/index.js, packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css, yarn.lock
Resolve #2742
Resolve #2752
Yes
Preview
=> chore(v2): upgrade Infima to 0.2.0-alpha.11

admin/testing-changes-on-Docusaurus-itself.md
Adding instructions that work to debug docusaurus locally
Updating local VSCode debug docs for docusaurus
Yes
I have run this debug configuration locally on the latest version of nodejs and vscode
N/A
=> misc: update debug config for Docusaurus v2 in VS Code

packages/docusaurus/src/server/plugins/init.ts
This diff tries to address the plugin loading issue in #2576. Even after this diff, docusaurus v2 still won't be completely compatible with Yarn v2's strict pnp mode, nevertheless it's a good step to start.
The current plugin resolution system basically does `require(whateverStringUserGiveInPlugins)`. This strategy will work in normal settings where `node_modules` are laid out by package managers like this:
```text
- website
- node_modules
- @docusaurus/core
- index.js
- docusaurus-plugin-abc
- index.js
- package.json
{ dependencies: ['@docusaurus/core', 'docusaurus-plugin-abc' }
```
In this case, when code in `@docusaurus/core/index.js` runs `require('docusaurus-plugin-abc'')`, it can be correctly resolved to `docusaurus-plugin-abc/index.js` due to how node module resolution algorithm …
=> fix(v2): Resolve plugins relative to siteDir

packages/docusaurus-init/templates/bootstrap/docs/doc1.md, packages/docusaurus-init/templates/classic/docs/doc1.md, packages/docusaurus-init/templates/facebook/docs/doc1.md
This PR fixes the templates used by `@docusaurus/init`.
Yes
* Created a new project using `@docusaurus/init` using the fixed templates.
* Previewed updated docs.
=> fix(v2): change docs for markdown features

docs/guides-search.md
…r own
Make sure v1 and v2 are synchronized
Yes
=> docs(v2): add mention on DocSearch when you run the crawler on your own

packages/docusaurus-theme-classic/package.json, yarn.lock
=> chore(v2): upgrade Infima to 0.2.0-alpha.12

packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.js, packages/docusaurus-theme-live-codeblock/src/theme/Playground/styles.module.css
Fix an unexpected regression due to https://github.com/facebookincubator/infima/commit/dfb1da40453000460287ba3dfa2430e9d5bc20c2 
Yes
| ![screenshot_21](https://user-images.githubusercontent.com/4408379/83246966-84571300-a1ab-11ea-808f-36aeb7a3fab6.png) | ![screenshot_20](https://user-images.githubusercontent.com/4408379/83246982-8b7e2100-a1ab-11ea-9417-7b6c92dae8f7.png) |
=> fix(v2): set proper font for live editor

website/docs/deployment.md
Fix #2834 
`ZEIT Now` was updated to `Vercel`. So we need to update the document.
Yes
=> docs(v2): Update ZEIT to Vercel

.runme/Dockerfile.runme, .runme/config.yaml, README.md
This PR adds Runme button-label [![Runme](https://svc.runme.io/static/button.svg)](https://runme.io/run?app_id=...) to run the project from latest commit with one click.
**How it works:**
1. Runme clones the repository and builds a docker image for latest commit;
2. deploys docker image to k8s cluster;
3. creates domain with SSL certificate;
4. shows web application;
5. destroys app instance after 10 minutes.
You can find detailed information on how this works [here](https://runme.io/how-it-works). The small demo you can find [here](https://www.youtube.com/channel/UCEysV237wo321JatUTC6Rlg).
**Why do you need this?**
- Runme is perfect solution to demonstrate current state of code/repository, anybody can just click the button and see the state;
- Runme totally free, we love open source …
=> misc: add v2 runme demo to README

README.md
Because `README` file should be as short and concise as possible.
Yes
See preview.
=> misc: move runme demo in block quote about v2

website/docs/docs.md
=> docs(v2): _index docs page does not show a sidebar

website-1.x/pages/en/index.js, website/src/pages/index.js
Update the banner in solidarity
Yes
Local and Netlify
N/A
=> Updated banner in solidarity

website/docs/blog.md
Document the missing header option.
Yes
Preview
=> docs(v2): description field in frontmatter of blog post

packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css
Fix a regression after https://github.com/facebook/docusaurus/pull/2645
Yes
| ![screenshot_23](https://user-images.githubusercontent.com/4408379/83871472-c696cc00-a738-11ea-9ca7-dac7d1148755.png) |  ![screenshot_22](https://user-images.githubusercontent.com/4408379/83871483-cb5b8000-a738-11ea-9cbe-7b4bae4efbda.png)|
=> fix(v2): restore styles for menu scrollbar

website/src/plugins/remark-npm2yarn.js
In order to follow dogfooding approach on our website v2.
Yes
Preview.
=> refactor(v2): synchronize yarn/npm command on site

website/docs/docusaurus-core.md
A few people were unaware that the `@docusaurus/router` supported all the features that come with React Router as it is a re-export. 
Yes
I added a note clarifying the implementation and features of the router.
resolves #2562
=> docs(v2): Add router implementation note

CONTRIBUTING.md
Issue #3077 
Previous hyperlink was dead, generated a new link to the channel that doesn't expire or have any limits.
Yes
Generated a link that never expires which links to the specific channel.
=> Updated link for #docusaurus-2-dev discord

website/docs/deployment.md
Closes https://github.com/facebook/docusaurus/issues/1208
Adding Azure Pipelines CI guide for v2.
Yes.
https://github.com/facebook/docusaurus/pull/3098
See it in action here https://dev.azure.com/ab16u10143/docusaurus-test/_build/results?buildId=37&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9
=> docs(v2):Add azure-pipelines CI guide

admin/publish.md, admin/scripts/test-release.sh, package.json, yarn.lock
=> chore(v2): docs updates after release

CHANGELOG-2.x.md, admin/publish.md
=> docs(v2): prettier docs

packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx, packages/docusaurus-theme-classic/src/theme/Tabs/styles.module.css
> #3150
Yes
>Before: 
>
> ![image](https://user-images.githubusercontent.com/42090492/88945558-c3890980-d2ab-11ea-9b73-344b0c7092d9.png)
>After:
> 
> ![image](https://user-images.githubusercontent.com/42090492/88945665-e5828c00-d2ab-11ea-8bc4-47b70350db13.png)
=> fix(v2): tab label showing outline & background when clicked

packages/docusaurus-theme-search-algolia/package.json, packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js, yarn.lock
This improves the Algolia search accessibility by including #3138 in DocSearch itself, and introducing support for typing a query when the search button is focused.
Yes.
(See keys pressed.)
- #3138
=> feat(v2): improve Algolia search accessibility

CHANGELOG.md
changelog formatting is bad in my v1.14.5 release
=> docs(v1): formatting changelog

website/docs/guides/creating-pages.md, website/versioned_docs/version-2.0.0-alpha.61/guides/creating-pages.md
duplicate text found in "Using React" section of creating-pages doc. very tiny fix.
as its very small, perhaps expand this section or remove entirely and put these sentences elsewhere?
yep 👍
=> docs(v2): removed duplicate text under "Using React" section

packages/docusaurus/src/webpack/utils.ts, website/docs/markdown-features.mdx
Fix issue https://github.com/facebook/docusaurus/issues/3179
Yes
By adding dogfood
=> fix(v2): fix svg loader

packages/docusaurus/package.json, yarn.lock
Details https://github.com/facebook/docusaurus/issues/3003
Superseed PRs where CI refuses to run:
https://github.com/facebook/docusaurus/pull/3220
https://github.com/facebook/docusaurus/pull/3206
=> fix(v2): update react-loadable-ssr-addon to solve yarn2 error

README.md
yes
Not Required 
https://img.shields.io/twitter/follow/docusaurus.svg
with Readme file people can check current 1.8k followers and follow @docusaurus
=> Added twitter badge and modified discord Badges

website/docs/guides/migrating-from-v1-to-v2.md
Fix incorrect command.
Yes.
Go to https://v2.docusaurus.io/docs/migrating-from-v1-to-v2/#migration-command.
This section contains incorrect command.
=> docs(v2): fix migration command

packages/docusaurus-theme-search-algolia/src/pages/search/index.js
Apparently it's a bad SEO practice
See https://github.com/facebook/docusaurus/pull/3233
Yes
Preview
See https://github.com/facebook/docusaurus/pull/3233
=> fix(v2): do not index search pages

packages/docusaurus/package.json, packages/docusaurus/src/commands/build.ts, yarn.lock
Dependency vulnerability
https://github.com/facebook/docusaurus/issues/3268
yarn audit
=> chore(v2): fix javascript-serialize vulnerability

website/community/team.md
Just adding myself to the Fellows section on the teams page.
=> docs(v2): add Nisarag to Fellows section

packages/docusaurus-migrate/src/__tests__/__fixtures__/expectedSiteConfig.js, packages/docusaurus-migrate/src/__tests__/__fixtures__/sourceSiteConfig.js, packages/docusaurus-migrate/src/__tests__/migrationConfig.test.js
docusaurus-migrate doesn't contains assertions.
I've copied config from simple_website and make unit test, that checks createConfigFile works correct.
Yes.
=> test(v2): Add unit test for migration of config file

docs/guides-blog.md
* `draft` was added but not mentioned in docs. 
* Fixes #3305 
* Yes
* Didn't change any code.
=> docs(v2): add draft doc

packages/docusaurus-plugin-content-pages/package.json, packages/docusaurus-plugin-content-pages/src/plugin-content-pages.d.ts, packages/docusaurus-theme-classic/src/theme/MDXPage/index.tsx, packages/docusaurus-theme-classic/src/types.d.ts
Continue the work from #3348 and add typing to MDXPage component expected by page plugin.
Yes
CI. Everything type checks.
=> feat(v2): Provide type definitions for MDXPage from page plugin

packages/docusaurus-migrate/src/index.ts
Fixes https://github.com/facebook/docusaurus/issues/3239
Superseed https://github.com/facebook/docusaurus/pull/3319
=> fix(v2): fix migrate cli paths (sidebars/customcss)

website/docs/introduction.md
improve grammar and clarity on a sentence in Introduction page
YES
=> docs(v2): fix grammar on introduction page

packages/docusaurus-plugin-debug/src/theme/DebugLayout/styles.module.css
Fixes https://github.com/facebook/docusaurus/issues/3402
Yes
Preview
=> fix(v2): fix debug plugin unscoped inline code global css

website/docs/api/docusaurus.config.js.md
Follow up on #3387, mention Eta's templating language in documentation.
Yes
N/A
#3387
=> docs(v2): mention Eta in ssrTemplate section

website-1.x/pages/en/index.js, website-1.x/static/css/custom.css, website/src/pages/index.js
Go back to the default ux for the Docusaurus website
Yes
Local site running
N/A
=> misc: default Docusaurus Website UX

website/docs/deployment.md
Added support for drone.io
Yes
=> docs(v2): Added drone.io publish docs #3491

website/docs/markdown-features.mdx
Backport to current version grammar fix (https://github.com/facebook/docusaurus/pull/3428)
=> docs(v2): grammar fix

packages/docusaurus-init/templates/classic/README.md
https://github.com/markdownlint/markdownlint
=> fix(v2): Fix markdownlint rules on template init/README

packages/docusaurus-theme-classic/package.json, yarn.lock
Upgrade to new version Infima (minor bug fixes)
Yes
Preview
=> chore(v2): upgrade Infima to 0.2.0-alpha.13

website/static/manifest.json
Should fix the PWA installed app to start on manifest json, see https://github.com/facebook/docusaurus/issues/3447
=> fix(v2): fix Docusaurus 2 website PWA manifest

.github/CODEOWNERS
Updating the CODEOWNERS file to reflect current state of things. @lex111 you might want to update this too now that you're back.
Yes
N/A
=> misc: update CODEOWNERS

website-1.x/docs/guides-search.md, website/docs/api/docusaurus.config.js.md, website/docs/deployment.md
(Fixing broken link in the docs so as to enable easy navigation and easy reading for others.)
(Yes)
=> docs(v2): Fix url bugs in v2 docs

website-1.x/docs/getting-started-publishing.md, website-1.x/versioned_docs/version-1.14.5/getting-started-publishing.md
Add drone support for 1.0
Yes
https://github.com/facebook/docusaurus/pull/3492
=> docs(v1): added drone for 1.0 #3491

website/versioned_docs/version-2.0.0-alpha.64/guides/migrating-from-v1-to-v2.md
The example command was using a wrong package.
Yes.
This is a change in the docs so none is needed.
None.
=> docs(v2): change package name in example script

packages/docusaurus/src/commands/start.ts
Closes #3275 
Instead of trying to modify the output from WDS, adding a separate console output with the URL of the Docusaurus website.
Yes
Ran all tests.
=> feat(v2): Add console output with complete URL including the baseUrl

packages/docusaurus-mdx-loader/package.json
Remove unused dependency newly added in https://github.com/facebook/docusaurus/pull/3469#discussion_r505644245
Yes
=> chore(v2): Remove unused deps from docusaurus-mdx-loader

packages/docusaurus-theme-classic/src/theme/hooks/useTOCHighlight.ts
Bug reported by RN website migration: https://github.com/react-native-website-migration/react-native-website/issues/21
TOC indicator have currently several issues:
* the TOC items are not highlighted on page enter
* user need to interact with the page (scroll it) to see the indicator
* indicator behaves randomly, not always changing on scroll which can be seen on the screen cap below (this usually happens on the shorter pages)
=> fix(v2): fix table-of-content scroll highlighting issues

website/docs/using-plugins.md
I was reading the docs and found this little wording issue.
No.
Just a wording change.
n/a
=> docs(v2): removed obsolete "you" identifier

packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx
Implementation of changes as per comment https://github.com/facebook/docusaurus/pull/3578#issuecomment-710157002
Follow-up of #3578.
Yes.
Preview.
=> fix(v2): make dropdown button clickable with mouse

packages/docusaurus-remark-plugin-npm2yarn/README.md
Fixing typo in remark-plugin-npm2yarn documentation
Yes
N/A
None
=> Fix typo in remark-plugin-npm2yarn documentation

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
Just some small improvements:
- Remove using of non-existent CSS class
- Trying to fix `ts-ignore`.
Yes
Preview.
=> refactor(v2): clean up code blocks

packages/docusaurus/src/client/baseUrlSuggestionWarning/BaseUrlSuggestionWarning.tsx
=> fix(v2): Fix typo in BaseUrlSuggestionWarning

packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css, packages/docusaurus-theme-search-algolia/src/theme/SearchBar/styles.css, website/src/css/custom.css, yarn.lock
Upgrade to new version Infima and make minor improvements related with this update.
Yes
Preview.
=> chore(v2): upgrade Infima to v0.2.0-alpha.14

packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/BlogSidebar/index.tsx, packages/docusaurus-theme-classic/src/theme/BlogSidebar/styles.module.css, packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx, packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css, packages/docusaurus-theme-classic/src/theme/Layout/styles.css, packages/docusaurus-theme-classic/src/theme/TOC/index.tsx, packages/docusaurus-theme-classic/src/theme/TOC/styles.module.css, yarn.lock
See https://github.com/facebookincubator/infima/pull/47
Yes
Preview.
=> chore(v2): upgrade Infima to v0.2.0-alpha.15

packages/docusaurus/src/commands/deploy.ts
=> chore(v2): fix prettier formatting

packages/docusaurus-mdx-loader/package.json
In all other packages, we have React version 16.8.4 specified.
Yes
N/A.
=> chore(v2): fix mismatch peer dependency in MDX loader

packages/docusaurus-mdx-loader/src/remark/transformImage/__tests__/__snapshots__/index.test.js.snap, packages/docusaurus-mdx-loader/src/remark/transformImage/__tests__/fixtures/img.md, packages/docusaurus-mdx-loader/src/remark/transformImage/index.js
=> fix(v2): escape alt text in img tag

packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx, yarn.lock
Upgrade to new version Infima and make thin scrollbar in code blocks (it is available since this update).
Yes
Preview.
=> chore(v2): upgrade Infima to v0.2.0-alpha.17

website/docs/markdown-features.mdx
Just noticed a potential typo when reading the document. So, I thought of fixing it.
Yes
N/A
N/A
=> docs(v2): potential typo in the doc

website/docs/installation.md
=> docs(v2): rename zeit to vercel

packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx, yarn.lock
Upgrade to new version Infima to remove reduced-motion feature.
Yes
Preview.
=> chore(v2): upgrade Infima to v0.2.0-alpha.18

packages/docusaurus-theme-classic/src/theme/hooks/useContextualSearchFilters.ts, packages/docusaurus-theme-search-algolia/src/theme/hooks/useAlgoliaContextualFacetFilters.js
Fix search issue https://github.com/facebook/docusaurus/issues/3826
=> fix(v2): fix search

website/docs/deployment.mdx
The flow for creating static sites in the Render dashboard was recently simplified, as reflected in these changes. See https://render.com/docs/deploy-docusaurus.
Yes.
=> docs(v2): render deployment doc

website/package.json
=> chore(v2): fix CI typo

website/package.json
The translations extracted from code are currently not sent to Crowdin
=> chore(v2): i18n CI: add write-translations call

website/community/resources.md
=> Add: docusaurus-plugin-moesif to community plugins

website/docs/migration/migration-manual.md
MDX comp does not render due to missing mdx import
=> docs(v2): missing <ColorGenerator/> mdx import

packages/docusaurus/src/commands/deploy.ts
When deploy command fails due to bad configuration (like bad organizationName leading to bad github clone URL), user should be able to figure out the problem himself more easily.
Printing more logs can help.
Related to https://github.com/facebook/docusaurus/issues/3875
=> polish(v2): improve docusaurus deploy logs

website/docs/installation.md
That was written 2 times, I removed one "that"
=> docs(v2): typo

.github/workflows/canary-releases.yml
This PR does not work after merge: https://github.com/facebook/docusaurus/pull/3905
=> chore(ci): fix canary release filtering

packages/docusaurus-theme-classic/src/theme/NavbarItem/LocaleDropdownNavbarItem.tsx
Fix console log commited by mistake
=> fix(v2): remove useless console log

website/docs/configuration.md
There was an extra closing parenthesis.
Yes
Preview.
=> docs(v2): Removed unnecessary closing parenthesis

packages/docusaurus-plugin-debug/src/theme/DebugLayout/index.js, packages/docusaurus-theme-classic/src/theme/IconEdit/index.tsx
Fix small some errors revealed Rocket Validator:
-  svg elements with an img role have an alternative text Found 91 times on this site
- Consider adding a “lang” attribute to the “html” start tag to declare the language of this document. Found 2 times on this site
- Element “title” must not be empty. Found 2 times on this site.
Yes
Preview.
=> refactor(v2): minor a11y tweaks

packages/docusaurus-plugin-debug/src/index.ts
=> refactor(v2): fix debug plugin name

website/src/pages/versions.js
=> fix(v2): remove duplicate section on Versions page

packages/docusaurus/src/webpack/__tests__/utils.test.ts, packages/docusaurus/src/webpack/utils.ts
Fixes SVG used in CSS
fix https://github.com/facebook/docusaurus/issues/3964
yes
preview
=> fix(v2): fix svg loader for CSS files

website/versioned_docs/version-2.0.0-alpha.70/sidebar.md
Fix https://github.com/facebook/docusaurus/issues/3971
=> docs(v2): doc typo on sidebar admonition

packages/docusaurus/src/webpack/base.ts
=> feat(v2): Cache hashed assets to dedicated folders

website/docs/guides/docs/sidebar.md
To fix a typo present in the documentation.
Yes
N/A
N/A
=> docs: fix typo from 'dissapear' to 'disappear'

examples/facebook/docusaurus.config.js, packages/docusaurus-init/templates/facebook/docusaurus.config.js, website-1.x/core/Footer.js, website/docusaurus.config.js
Adding new required privacy and policy links to Docusaurus
Yes
Netlify
N/A
=> feat: add new policy links to Docusaurus site and FB template

packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx, packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
Closes #4010
Fix #4010
Yes
Used Accessibility Insights for Web Chrome extension to test for any accessibility issues
=> fix(v2): fix accessibility issue with IconArrow

README.md
Your Meercode integration was successful! Attached in this PR is a badge and build monitor page URL to monitor GitHub Actions in your README.
=> chore: Add GitHub Actions CI score badge

website-1.x/docs/getting-started-installation.md
Suggest to use Docusaurus 2 even for non-FB websites
(Also because I need to trigger CircleCI to get the v1 site deployed for an unrelated reason)
=> docs(v1): suggest to use Docusaurus 2 even for non-FB websites

admin/new.docusaurus.io/README.md, admin/new.docusaurus.io/_redirects
Create an easy-to-remember alias to the official up-to-date CodeSandbox template.
=> feat(v2): new.docusaurus.io -> CodeSandbox

packages/docusaurus/src/commands/start.ts
Fix #4050 issue.
Yes
I've run: `npm start` and checked that running fast save changes was just running the last one.
=> fix(v2): chokidar reloading debounced

packages/docusaurus-theme-classic/src/__tests__/__snapshots__/translations.test.ts.snap, packages/docusaurus-theme-classic/src/__tests__/translations.test.ts, packages/docusaurus-theme-classic/src/translations.ts
Fix i18n bug reported here:
https://github.com/facebook/docusaurus/issues/3317#issuecomment-754853247
yes
tests
=> fix(v2): navbar dropdown subitems should be translated properly

website/community/resources.md
Typo fix for word **behavior** in community docs
Yes
=> docs(v2): community docs typo fix

packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx
Based on https://github.com/facebook/docusaurus/pull/4162#issuecomment-772716353
Yes
Preview.
=> refactor(v2): remove delay after skip link pressed

website/community/resources.md
I made a plugin
I also reorganized the list into sub-categories
Yes
=> docs(v2): Add docusaurus-plugin-remote-content to resources list

packages/docusaurus-theme-classic/src/theme/Navbar/styles.module.css
Relates to https://github.com/facebook/docusaurus/pull/4194#issuecomment-775239769
Yes
Preview.
=> fix(v2): restore hamburger menu

packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts, packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx, packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx, packages/docusaurus-theme-classic/src/theme/LayoutHead/index.tsx, packages/docusaurus-theme-classic/src/theme/Seo/index.tsx
Avoid a bit of code duplication by creating new general component for adding various SEO things (only for use inside our codebase for now).
Yes
Preview.
=> refactor(v2): introduce Seo component for internal using

README.md
Badge is using an older Netlify deployment
=> docs: update Netlify deploy status badge

packages/docusaurus/package.json, yarn.lock
Should fix #4319
Yes
See #4319
=> chore(v2): bump clean-css to 5.1.1

packages/docusaurus-theme-classic/codeTranslations/ja.json
Add a translation of the string added in #4304 for Japanese users.
Yes.
Nothing...
- #4303
- #4304
=> polish(v2): add japanese translation for #4304

website/docs/api/docusaurus.config.js.md, website/docs/api/plugins/plugin-content-docs.md, website/docs/api/plugins/plugin-pwa.md, website/docs/api/themes/theme-configuration.md, website/docs/blog.md, website/docs/guides/markdown-features/markdown-features-headings.mdx, website/docs/i18n/i18n-crowdin.mdx, website/docs/i18n/i18n-git.md, website/docs/i18n/i18n-introduction.md, website/docs/i18n/i18n-tutorial.md, website/docs/installation.md, website/docs/introduction.md, website/docs/migration/migration-manual.md, website/docs/styling-layout.md
Just minor fixes before new release.
Yes
Preview.
=> docs(v2): various improvements

website-1.x/blog/2021-03-09-releasing-docusaurus-i18n.md
need to change a v1 file to trigger the CI deploy...
Follow-up of https://github.com/facebook/docusaurus/pull/4396
=> chore(v1): trigger v1 site deploy through CI

.circleci/config.yml, packages/docusaurus-1.x/lib/publish-gh-pages.js, website-1.x/blog/2021-03-09-releasing-docusaurus-i18n.md
Follow up of https://github.com/facebook/docusaurus/issues/4394
=> chore(v1): fix CircleCI v1 site deploy

packages/docusaurus-theme-classic/codeTranslations/zh-Hant.json
Love this project and want to make my first contribution.
Yes
N/A
Improves #4356
=> polish(v2): Updated theme label translations for Traditional Chinese

packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-classic/src/theme/Navbar/styles.module.css, yarn.lock
Also fixes #4423.
Yes
Preview.
=> chore(v2): upgrade Infima to v0.2.0-alpha.21

.eslintrc.js, __tests__/validate-package-json.test.ts, packages/docusaurus-mdx-loader/package.json, packages/docusaurus-mdx-loader/src/index.d.ts, packages/docusaurus-mdx-loader/src/remark/toc/search.js, packages/docusaurus-migrate/src/index.ts, packages/docusaurus-migrate/src/types.ts, packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts, packages/docusaurus-plugin-content-blog/src/types.ts, packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts, packages/docusaurus-plugin-content-docs/src/cli.ts, packages/docusaurus-plugin-content-docs/src/client/docsClientUtils.ts, packages/docusaurus-plugin-content-docs/src/sidebars.ts, packages/docusaurus-plugin-content-docs/src/types.ts, packages/docusaurus-plugin-content-pages/src/types.ts, packages/docusaurus-theme-classic/src/index.ts, packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx, packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx, packages/docusaurus-theme-classic/src/theme/hooks/useTOCHighlight.ts, packages/docusaurus-theme-classic/update-code-translations.js, packages/docusaurus-types/src/index.d.ts, packages/docusaurus-utils-validation/src/__tests__/__snapshots__/validationSchemas.test.ts.snap, packages/docusaurus-utils-validation/src/validationSchemas.ts, packages/docusaurus-utils/src/index.ts, packages/docusaurus/src/server/duplicateRoutes.ts, packages/docusaurus/src/server/utils.ts, packages/docusaurus/src/webpack/utils.ts
Fix more linter warnings.
152 warnings -> 51 warnings.
Yes
Most of the changes are type-only, so check CI status.
For slight regex tweaks, I commented below on how they are already covered by existing tests.
=> chore(v2): Fix more linter warnings

website/docusaurus.config.js
Render ko and ja locales on the staging i18n deployment: https://docusaurus-i18n-staging.netlify.app/
=> chore(v2): enable staging locales: ko ja

website/docs/guides/docs/sidebar.md, website/versioned_docs/version-2.0.0-alpha.71/guides/docs/sidebar.md, website/versioned_docs/version-2.0.0-alpha.72/guides/docs/sidebar.md
Corrected the use of delimiters in example, replaced `;` with `,`
Yes
=> docs(v2): corrected the use of delimiters

website/docusaurus.config.js, website/src/pages/index.js
Make sure v1 users can still find v1 doc easily
=> docs(v2): add more links to v1: announcementBar, versionDropdown, homepage

README.md
Fixes duplicate line on v1 docs
Yes
N/A
N/A
=> docs(v2): remove duplicate line on v1 docs

website/docs/deployment.mdx
fix typo deployment.mdx
yes
Nope
Nope
=> docs(v2): fix typo deployment.mdx

examples/bootstrap/README.md, examples/facebook/README.md, packages/docusaurus-init/templates/bootstrap/README.md, packages/docusaurus-init/templates/classic/README.md, packages/docusaurus-init/templates/facebook/README.md, website-1.x/docs/getting-started-publishing.md, website-1.x/versioned_docs/version-1.14.5/getting-started-publishing.md, website-1.x/versioned_docs/version-1.14.7/getting-started-publishing.md, website/versioned_docs/version-2.0.0-alpha.71/deployment.mdx, website/versioned_docs/version-2.0.0-alpha.72/deployment.mdx
=> docs(v2): fixed typos

website/docs/docusaurus-core.md, website/docs/i18n/i18n-crowdin.mdx, website/docs/i18n/i18n-git.md, website/docs/i18n/i18n-tutorial.md, website/versioned_docs/version-2.0.0-alpha.71/docusaurus-core.md, website/versioned_docs/version-2.0.0-alpha.71/i18n/i18n-crowdin.mdx, website/versioned_docs/version-2.0.0-alpha.71/i18n/i18n-git.md, website/versioned_docs/version-2.0.0-alpha.71/i18n/i18n-tutorial.md, website/versioned_docs/version-2.0.0-alpha.72/docusaurus-core.md, website/versioned_docs/version-2.0.0-alpha.72/i18n/i18n-crowdin.mdx, website/versioned_docs/version-2.0.0-alpha.72/i18n/i18n-git.md, website/versioned_docs/version-2.0.0-alpha.72/i18n/i18n-tutorial.md
Fixed the directory of index.js at various places
In those examples the file directory should be `src/pages/index.js`, but currently it's `src/index.js`
Yes
=> docs(v2): fixed the directory of index.js

website/docs/api/themes/theme-configuration.md
We are in the footer section, I think it's a bad copy and paste
Fix typo
Yes
Nope
Nope
=> docs(v2): fix typo theme-configuration.md

packages/docusaurus-theme-classic/src/theme/Heading/styles.module.css
Resolves #4513
Slightly adding a little space for heading anchors to improve the design.
Yes
| ![image](https://user-images.githubusercontent.com/4408379/114325421-bdd10c80-9b38-11eb-9723-e7f5a5e889eb.png) | ![image](https://user-images.githubusercontent.com/4408379/114325406-a85be280-9b38-11eb-8984-5a05c5ed2ca8.png) |
=> refactor(v2): increase heading anchor offset

website/docs/using-themes.md
Fix grammatical error in tip
yes
N/A
N/A
=> docs(v2): add clarity to tip in using-themes page

website/versioned_docs/version-2.0.0-alpha.71/using-themes.md, website/versioned_docs/version-2.0.0-alpha.72/using-themes.md
Fix grammatical error in tip for versioned docs
yes
N/A
#4604
=> docs(v2): add clarity to tip in versioned using-themes page

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
Fix small bug caused by merge #4617.
Yes
Try to close responsive sidebar.
=> fix(v2): restore toggle responsive sidebar button

website/community/2-resources.md
Adding three additional community plugins for Docusaurus v2
Yep.
N/A
N/A
=> docs(v2): Adding new community plugins

packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
Fixes #4512
Yes
See To Reproduce section in the issue above.
=> fix(v2): center align content if no sidebar exists

packages/docusaurus-theme-classic/package.json, yarn.lock
Upgrade Infima:
- fix https://github.com/facebookincubator/infima/pull/107
- fix https://github.com/facebook/docusaurus/issues/4565
yes
preview
=> chore(v2): update Infima to alpha.22

website/docs/installation.md
My father was killed by a rogue typo
Nope
=> docs(v2): Fix typo in installation.md

website/docs/deployment.mdx
this PR update links in `deployment.md,`,  i think this links doesn't make sense to redirect another page because it's an example URL.!
no redirect to another page.
=> docs(v2): Fix urls in deployment.md

packages/docusaurus-theme-classic/package.json, yarn.lock
Fixes https://github.com/facebook/docusaurus/issues/4671 with https://github.com/facebookincubator/infima/pull/112
yes
preview
=> chore(v2): update infima to alpha 23

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
=> docs(v2): fix doc lint

website/src/data/users.js
=> docs(v2): fix Jest showcase screenshot

examples/bootstrap/package.json, examples/bootstrap/src/pages/index.js, examples/bootstrap/yarn.lock, examples/classic/package.json, examples/classic/yarn.lock, examples/facebook/package.json, examples/facebook/yarn.lock
Examples and CodeSandbox shoud use the new beta
=> chore: regenerate examples on 2.0.0-beta.0

CHANGELOG.md, website-1.x/blog/2021-05-12-announcing-docusaurus-two-beta.md
=> docs(v2): beta blog post edits

packages/docusaurus/bin/docusaurus.js
Should fix https://github.com/facebook/docusaurus/issues/4782
=> fix(v2): update notifier should never suggest to downgrade

website/src/data/users.js
I have updated my blog with the latest version of docusaurus supporting i18n and have also translated all documents. Primary motivation is to keep your website updated as well!
Yes
N/A
Follow up of #4786
=> docs(v2): Add i18n tag and fix typo

packages/docusaurus-plugin-ideal-image/package.json, packages/lqip-loader/package.json, yarn.lock
Resolves #4805
Yes
According to the sharp's author, this should fix the problem, but can't check it myself.
=> chore(v2): update sharp to 0.28.2

packages/docusaurus-theme-classic/codeTranslations/he.json
Follow up on https://github.com/facebook/docusaurus/pull/4811
Fixing some of the translations based on the Hebrew Academy.
yes
local test
https://github.com/facebook/docusaurus/pull/4811
https://github.com/facebook/docusaurus/pull/4587
=> fix(v2): Amend Hebrew translations

packages/docusaurus-theme-classic/package.json, packages/docusaurus-theme-common/package.json, packages/docusaurus-theme-live-codeblock/package.json, yarn.lock
=> fix(v2): pin prism-react-renderer version to 1.1.1
