facebook/docusaurus

lib/core/Site.js

Google Chrome guesses the language if this is not present. Large quantities of source code can confuse it and lead to it selecting completely the wrong language.
When I loaded the example docs before this change, google chrome offered to translate the page from Latin. After this change, it did not offer to translate

Include a `lang` property on html node

---

examples/basics/pages/en/index.js

I was using Docusaurus to create website for one of my projects to try out. I find customizing index page took me a bit more time, mainly because of the pretty big, nested, render() method. Splitting into small components as React always recommended would help users to customize the page easier.
I tried to move those small components into a common place so potentially could be shared but failed. I think it is because the way template generation works. Inside index.js file is still an improvement, but if there is a better place please do that and close this request.
BTW, this PR also fixed the showcase links `key` issue on this page.
I tested by creating a new website and copy the changed files over then manual test the site.
(If this PR adds or changes functionality, please take some time …

Index page composition

---

lib/static/css/main.css

Fix the issue. In mobile mode, instead of `display: none`, do `display: flex; flex-direction: column` on sitemap. Also added margin
Tested in local build

Issue 245 fix

---

docs/api-commands.md
docs/getting-started-publishing.md
docs/guides-custom-pages.md
docs/guides-versioning.md

Some links are 404 or 301 redirected.
This PR fixed this.
I've found these broken link by [textlint](https://github.com/textlint/textlint/tree/master/packages/textlint "textlint") and [textlint-rule-no-dead-link](https://github.com/textlint-rule/textlint-rule-no-dead-link-fork "textlint-rule-no-dead-link").
- Test branch: <https://github.com/facebook/Docusaurus/compare/master...azu:textlint?expand=1>
Installation:
```shell-session
yarn add textlint @textlint-rule/textlint-rule-no-dead-link --dev
yarn textlint --init
yarn textlint docs/
```
Add `.textlintrc` setting:
```json
{
"filters": {},
"rules": {
"@textlint-rule/no-dead-link": {
"checkRelative": true
}
}
}
```
```shell-session
$ yarn textlint docs
yarn run v1.3.2
$ /Users/azu/.ghq/github.com/facebook/Docusaurus/node_modules/.bin/textl …
```

Fix broken or redirected links

---

website/pages/en/users.js
website/siteConfig.js

Facebook Open Source projects are shown at the top.
We introduce a new boolean to ensure we can pin non-FB projects to the frontpage.
Showcase:
Homepage:

Split showcase

---

examples/basics/core/Footer.js
examples/basics/pages/en/index.js
lib/core/nav/HeaderNav.js
lib/server/env.js
lib/server/generate.js
lib/server/readMetadata.js
lib/server/server.js

This is to fix https://github.com/facebook/Docusaurus/issues/305
The root cause of the problem is using 'en' as default language regardless of translation enabled or not.
However 'en' and no translation are two different cases. The fix has two major parts:
1) Components. Basically use empty `language` property as an indication of no translation.
2) Template generation. Basically handle the case of no translation.
For readability I've created a new file `env.js` which encapsulate simple translation and versioning logic. So other places can just call `env.translation.enabled` to check.
I try to keep the changes minimal but sill has to modify quite a few files.
I've tested run server and generate locally. …

Fixing Issue 305 - broken links because of language

---

.circleci/config.yml
lib/publish-gh-pages.js
package.json
yarn.lock

This removes the need to install rsync natively in CI.
Otherwise, clients will need to ensure their build systems have rsync installed.
```
$ node ../lib/publish-gh-pages.js
```
Confirm `Docusaurus-gh-pages` is created and dot files are preserved.

Switch to rsync package

---

lib/server/server.js

If a document states a `layout` in its header but `layouts` doesn't exist in `siteConfig.js` the doc would not render.
I tested by having a `layout` entry in a doc header and no `layouts` entry in `siteConfig.js`, made sure the document loaded.

Guard against lack of `layouts` in siteConfig.js

---

lib/server/generate.js
lib/server/server.js

This is a rough draft to get a sense of how we feel about this change. Built to fix https://github.com/facebook/Docusaurus/issues/247.
Problem:
Some languages have auto-generation of documentation as HTML snippets. (JS, OCaml, Java, etc. all of this functionality to varying degrees). The ability to co-locate documentation and code is powerful, so I don't want to give up this ability. I'd also like to be able to insert this code into a Docusaurus site and keep the header/footer styles.
Solution:
This PR makes it so that all .html files found in /pages are treated as html snippets and wrapped with the appropriate header/footer. Technically I don't think this would have to be behind a flag since you always have the ability to output raw HTML to /static, but for correctness sake I think the …

add wrapPagesHTML which renders html snippets in pages inside of a header + footer

---

lib/core/Head.js

Remove the unneeded chromeframe tag, it has long since been retired by Google and was only ever needed for very old IE (would render the page in Chrome within IE).
REF: http://www.chromium.org/developers/how-tos/chrome-frame-getting-started

No need for chromeframe tag

---

lib/core/nav/HeaderNav.js
website/siteConfig.js

Closes #309
Many people thought the current message was too cryptic. I agree. And it could be misleading.
Tested locally on the Docusaurus site (which has translations) and the testsite that comes with the initialization script (which does not have versioning or translations).
None

Better error when parsing headerLinks.doc fields

---

lib/core/nav/HeaderNav.js
lib/server/readMetadata.js
lib/server/versionFallback.js

Ref: ff117979c69e7bbe8c0c3286c15970a1a0854bba and a5e963dba134bf0f6a83908d49cd59ce06704cb3
Versioning ids should be based on whether translation is enabled. 
Tested locally on:
Docusaurus
Relay (which has versioning)
Test site from `npm run examples`
Ref: ff117979c69e7bbe8c0c3286c15970a1a0854bba and a5e963dba134bf0f6a83908d49cd59ce06704cb3

Versioning ids should be based on whether translation is enabled

---

lib/core/Site.js

Do not want 
```
<html lang=''>
```
`docusaurus-init` test site and React Native did not have `lang` attribute
docusaurus.io and Reason-React did
Stemming from the changes made in #316

Do not set html lang attribute if there is no language set

---

docs/api-commands.md
docs/getting-started-publishing.md

Better docs for publishing:
- Some environment variables can be set by the CircleCI build itself
- Document `USE_SSH`
Ran site locally
N/A

Update publishing docs and API information

---

docs/api-site-config.md

To get started contributing to Docusaurus, I guess? :)
Build the website to see the changes. (Pretty self-evident what they are.)
This documents the new config field that introduced by #206 and closes the issue #212.
Side note: also added the links that help people find all the themes and languages that are supported by Highlight.js

document changes from PR #206 (as per issue #212)

---

lib/server/generate.js
lib/server/server.js

I've fixed the build errors on Windows on my local instance, but I've been waiting for #360 to be merged so I can use this package on a build server. As I see that it may be further delayed because of the huge amount of changes I created a small PR with the Windows build fixes which may be merged in a bugfix release.
`yarn test` tests passed on Windows.

Fix build on Windows

---

lib/publish-gh-pages.js

The symptom was that if we had a user or org page (e.g., https://JoelMarcey.github.io), we would try to copy files to a directory within a directory, getting errors like:
```
Error: Copying build assets failed with error 'Error: Cannot copy '/Users/joelm/dev/JoelMarcey.github.io/website/build' to a subdirectory of itself, '/Users/joelm/dev/JoelMarcey.github.io/website/build/JoelMarcey.github.io-master'.'
```
This is because we were setting the end of `fromPath` to empty if we were using an org or user page.
But we don't need to do that. The `PROJECT_NAME` (set in `siteConfig.js` as `projectName`) is the user or org repo
e.g., https://github.com/JoelMarcey/JoelMarcey.github.io/ has a `projectName` of `JoelMarcey.github.io` with an `organizationName` of `JoelMarcey`.
So now the `fromPath` …

Always use PROJECT_NAME, even for user and org pages

---

lib/rename-version.js

This trivial PR 'enames' the ename typo displayed when running docusaurus-rename-version.

ename typo

---

docs/guides-navigation.md

Closes #240
This needed documentation
Testing live
https://github.com/facebook/Docusaurus/pull/366

Add section on referencing documents

---

lib/server/feed.js

(https://docusaurus.io/blog/feed.xml)
```diff
-<url>https://docusaurus.ioimg/docusaurus.svg</url>
+<url>https://docusaurus.io/img/docusaurus.svg</url>
```
See generated `feed.xml` and `atom.xml`.
none

fix(feed): add missing slash for image url

---

lib/core/GridBlock.js
lib/static/css/main.css

@cyan33 found this bug and submitted it to the Jest repo, I thought I'd put in a quick fix
Closes https://github.com/facebook/jest/issues/5299
Closes https://github.com/facebook/Docusaurus/issues/397
Tested using the `website/` within this project
Before: 
After:

Fix margin for right-aligned images

---

lib/server/server.js

Also simplified the logic a bit to reduce duplication
Closes #404
To fix error raised by @mitchellurgero in #404 
Local testing on Docusaurus site
N/A

Send status code to server response for redirects

---

lib/server/readMetadata.js

Previously the regex was in greedy mode which would cause a bug.
For example, if the file path looks like
`/translated_docs/zh-CN/version-0.52/alert.md`
then the matched part would be `zh-CN/version-0.52` which is obviously wrong for language detection.

Fix regex for non english versioned docs

---

lib/core/Site.js

If the site is versioned, and the latest version is displayed, the URL will not change. We need to let Algolia know this is the case.
This change assumes that sites have configured DocSearch to consider the 'current' tag as one matching the latest version of the site. You can see this is the case with React Native's [own config](https://github.com/algolia/docsearch-configs/blob/dd8bd78c306e0929f2285409bdfaff5af9544c77/configs/react-native-versions.json). 
The logic goes:
If a version is specified via props and it does not match the latest version, we'll use that version with DocSearch.
If a version is specified via props and it matches the latest version, we'll use 'current' instead.
If no version is specified via props, assume 'current'.
On …

[DocSearch] Treat latest version as current version

---

lib/build-files.js
lib/start-server.js
package-lock.json
package.json
yarn.lock

Writing react components with both these syntaxes.
Even though it's not ECMAScript yet (although I guess object rest spread was moved to ES2018 today haha) react docs and the CRA preset uses this so I guess this would be ok to do: https://github.com/facebook/create-react-app/blob/5348d6eecf208a6298e48072314157804282002e/packages/babel-preset-react-app/index.js#L90-L92
> Was porting over the REPL for https://github.com/babel/website/pull/1521

Also transform class properties and object rest spread

---

docs/api-site-config.md
docs/guides-custom-pages.md

Mention `wrapPagesHTML` in the section about adding static pages.
Visual
N/A

Add some more information around wrapPagesHTML

---

lib/core/Head.js

I was adding a google font through `siteConfig.stylesheets` and noticed the following error:
```
Starting Docusaurus server on port 3000...
Open http://localhost:3000/
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Head`. See https://fb.me/react-warning-keys for more information.
in link (created by Head)
in Head (created by Site)
in html (created by Site)
in Site (created by DocsLayout)
in DocsLayout
```
This fixes that by adding the key prop. Following the same style as used for `siteConfig.scripts`
- ran `npm run prettier`
- `npm run test` pass
- verified with npm link that error message was gone with this patch applied

 Add key to stylesheet links in Head.js

---

lib/server/feed.js

The root URL was missing the baseURL portion. This is fine when a site is hosted on a custom URL such as docusaurus.io, because the generated URL will be valid (docusaurus.io/blog), but it breaks when the site is hosted on GitHub Pages (the React Native feed was using facebook.github.io/blog as the rootURL).
The [current React Native feed](http://facebook.github.io/react-native/blog/atom.xml) looks like this (truncated):
```
<feed xmlns="http://www.w3.org/2005/Atom">
<id>https://facebook.github.io/blog</id>
<title>React Native Blog</title>
<updated>2018-01-18T06:00:00Z</updated>
<generator>Feed for Node.js</generator>
<link rel="alternate" href="https://facebook.github.io/blog"/>
<subtitle>
The best place to stay up-to-date with the latest React Native news and events.
</subtitle> …
```

Fix links in blog Atom feed

---

docs/guides-blog.md
lib/core/BlogSidebar.js
lib/server/readMetadata.js

I wanted to allow showing all blog posts not just recent 5.
Also, inadvertently, solved a problem where post order on 'Recent Posts' was not sorted by time.
1) Add 'blogSidebarCount' setting to siteConfig of a site with a blog an at least 6 posts.
2) Set 'blogSidebarCount' value to 3.
3) Run local server.
4) Observe that only 3 most recent posts show on sidebar.
5) Set 'blogSidebarCount' value to 'ALL'.
6) Run local server.
7) Observe that _all_ posts show on sidebar and title changes to "All Blog Posts"

Allow controlling number of blog posts in Recent Blogs sidebar.

---

lib/core/Remarkable.js
lib/core/renderMarkdown.js
lib/server/feed.js

Fix bug detailed in issue #370 
Closes #370 
The test docusaurus website has a blog post with a description containing HTML. 
1. Manually check that blog posts/documentation pages still correctly render markdown as HTML.
1. Manually check the rss and atom feeds (`http://localhost:3000/blog/feed.xml` and `http://localhost:3000/blog/atom.xml`) now have the description in HTML rather than markdown.
None

Blog feed fixes #370

---

lib/static/css/main.css

Fixes #441 
1. Add many dummy entries into the `siteConfig.js`.
2. Use the Chrome devtools' ["Toggle Device Mode"](https://developers.google.com/web/tools/chrome-devtools/device-mode/) to simulate various responsive sizes. Note: Just make sure you refresh the page once when you switch to mobile mode. This guarantees that the page is loaded in the simulated mobile mode and any old CSS effects from the desktop mode are not into play.
cc @JoelMarcey

Adding scrollbar to header when it overflows

---

docs/api-doc-markdown.md
lib/core/Doc.js

Some of the Markdown docs are generated and therefore should not be edited. Instead contributors should edit the source data files (e.g. `.json` or `.yaml` or otherwise) which are used to generate the final Markdown docs.
Documentation has been updated to reflect usage.
Example:
```markdown
---
id: options
title: Options
sidebar_label: Options
edit_url: https://github.com/unibeautify/unibeautify/edit/master/src/options.ts
---
```
Notice the Edit Button in the following screenshot does not have a link in the conventional `editUrl` format. In this screenshot my cursor is hovering over the Edit Button and its URL is shown in the bottom left corner.
Live demos from Pull Request: https://github.com/Unibeautify/website/pull/39/files
- https://deploy-preview-39--unibeautify.netlify.com/docs/optio …

Allow edit URL to be customized with doc metadata

---

docs/getting-started-installation.md
docs/getting-started-preparation.md

The verifying installation section on site preparation is not in the right place 
and I think maybe this should be in the installation section.
In (https://github.com/facebook/Docusaurus/issues/431) @JoelMarcey mentions about the first paragraph that will need to be updated but I didn't know what should be updated in there.

Move Verifying Installation section to Installation doc

---

CHANGELOG.md
package-lock.json
package.json

Publish a new npm package
Previous commits already tested
N/A

Publish Docusaurus v1.0.6

---

lib/static/css/main.css

Fixes #441. This has a different implementation than #444 in order to avoid #445. Only in the case of when screen size is lesser than `735px`, we need a scrollbar.
1. Add many dummy entries into the `siteConfig.js`.
2. Use the Chrome devtools' ["Toggle Device Mode"](https://developers.google.com/web/tools/chrome-devtools/device-mode/) to simulate various responsive sizes. Note: Just make sure you refresh the page once when you switch to mobile mode. This guarantees that the page is loaded in the simulated mobile mode and any old CSS effects from the desktop mode are not into play.
3. Also, test the search in every mode so that #445 doesn't come back.
cc @JoelMarcey

Adding scrollbar to header, only on mobile

---

lib/server/versionFallback.js
lib/version.js

Instead of throwing, return `null` because that means we have a
new doc in our versioning sequence
(Also, cleaned up a bit of code as I researched this)
Fixes #450
We had a showstopping bug where versioning would not work if you tried to add a new file to the documentation set.
Versioned a set of docs as 1.0.0
Added a new doc to the master set
Ran
```
npm run version 2.0.0
```
The new doc was part of version 2.0.0
N/A

Don't throw if a doc hasn't been versioned yet

---

docs/guides-custom-pages.md

On https://docusaurus.io/docs/en/custom-pages.html the $wrapPagesHTML site config link is referencing https://docusaurus.io/docs/en/site-config.md#optional-fields. It appears that it should reference https://docusaurus.io/docs/en/site-config.html#optional-fields
Visual - replaced "md" with "html" 
https://docusaurus.io/docs/en/site-config.md#optional-fields
https://docusaurus.io/docs/en/site-config.html#optional-fields
https://github.com/facebook/Docusaurus/pull/426/commits/b1ecd989d45d99f110392e2753063cc72d0c4bfb

Fix broken link to site-config

---

lib/server/versionFallback.js

Fixes #450 
Right now we were assuming that there would be no `-` in a version.
That was breaking things.
This allows more flexibility for versions like:
1.0.0-beta.2
Was able to successfully build versions that contained multiple dashes
Ref #455

Allow multiple `-` in a version string

---

lib/server/server.js

See https://github.com/facebook/Docusaurus/blob/master/lib/server/generate.js#L148
Since `generate.js` and `server.js` share a lot of codes, someone should definitely rewrite these two modules.

Fix wrong latestVersion in server.js

---

lib/core/getTOC.js

Adresses #344.
I separated this into two PRs. This one only adds the function to extract a table of contents out of a markdown document's header tags. The table of content only has two levels at most. By default h2 tags are used for top level headings and h3 for subheadings. This can be customized, and the idea is to allow users to choose the tags to be used as top level and sub headings from siteConfig. More info about that in the other PR.
This function is pretty self-contained and should work from anywhere. Document markdown in => table of contents out.
#475

Add function to generate TOC from document headings

---

docs/api-site-config.md

This is a config option. It should be in the config docs.
Yes
local
N/A

Add `blogSidebarCount` to the site config Docs

---

lib/core/DocsLayout.js
lib/core/Site.js
lib/core/getTOC.js
lib/core/nav/OnPageNav.js
lib/static/css/main.css

This is how the table of contents generated from the document's headers can be displayed as a separate sticky sidebar on the right side of the document. I can write the corresponding docs when we finalize on all the ways the navigation can be displayed through the option `onPageNav`. This is currently using `'separate'`. The other possible values could be `false` for no on-page navigation, or `'inline'` to have it show up underneath the current item's link in the existing sidebar similar to #349.
As for the heading tags used to generate the TOC the default is same as this:
```
onPageNavHeadings: {topLevel: "h2", sub: "h3"}
```
`topLevel` and `sub` can be strings like above or arrays of strings. `sub` can also be a falsy value or empty array to indicate the user only needs top level …

Add separate on-page navigation sidebar

---

lib/core/nav/HeaderNav.js

Hello and thank you for this project!
I have noticed that the link to go to the "main" page in the navigation header (the one in the upper-left corner, with the header icon) was always targeting the page in the default—`en`—language, even if localization is enabled and another language was selected (e.f. `fr`).
I think this is something that has been forgotten as I expected the link to take the currently selected language into account.
Yes.
As this is a very small modification, I quickly tried to set up a local working environment to be able to run "prettier" and "Jest tests", but could not get it working within a 2 mn time box so I admit I skipped those steps.
I made sure the line was still < 80 characters (which was not before I read the Contributing Guidelines) and had the right number …

Add missing i18n support in header link

---

lib/core/nav/SideNav.js

Hello, I have noticed another (as in yesterday's PR #477) place where internationalization support seemed to be missing and submit this PR to hopefully help fixing gaps.
When in a configuration where screen width is limited (e.g. small smartphone), a breadcrumb appears to help the user know where s·he is.
The breadcrumb simply was not taking selected language into account—in the case where localization was enabled and an additional language added.
This PR is here to localize the breadcrumb label, leveraging a local existing function for this purpose.
Yes; the file went through prettier, which should conform to expected format and please the CI checker.
Manual tests were done.
1. Have a project with localization enabled, additional language supported and a content leading to multiple …

Add missing i18n support in side nav breadcrumb

---

lib/core/Site.js

Allow user to add their own appId into algolia configuration.
See the issue [465](https://github.com/facebook/Docusaurus/issues/465)
yes
- Do not change siteConfig.js
- Run yarnpkg start from ../website
- Make sure search work as before
- Add appId into algolia config in siteConfig.js, 
- Run yarnpkg start from ../website
- Make sure search work and effectively use given appId (note i it did my own set of apiKey/appId for this test)
Note i did also ran yarn jest and yarn prettier.
Not related to any pr.

feat(): add appId into algoliaConfig 

---

docs/guides-navigation.md
lib/core/BlogPageLayout.js
lib/core/BlogPostLayout.js
lib/core/DocsLayout.js
lib/core/Site.js
lib/core/nav/HeaderNav.js
lib/server/generate.js
lib/server/server.js
lib/static/css/main.css

Fixes #178 
Read the doc change at guides-navigation.md to see how it works.
For the main styles ( and thus the docusaurus site) I only added the active classes to the already existing hover and focus rules.
I tested docs with two sidebars, blog posts, and `.js` and `.html` user pages with `wrapPagesHTML`.
For testing versioned and translated docs I manually copied some files instead of setting up crowdin.
I read this part of the new PR template after having already included the doc changes in this one :smile:. Let me know if I should move them to a separate PR.

Add active link classes to site navigation menu

---

docs/api-site-config.md

Open Graph images are very nice to have when sharing the site on social media. This config is already supported by docusaurus, it's just needs be documented.
Yes.
Looks awesome on a local build :)
N/A

Add `ogImage` to site-config docs

---

examples/basics/pages/en/users.js

Fixes Issue #402 caused by removing optional users array from siteConfig file. Users array is now validated before using its properties.
Wanted to make an Open Source first contribution
Yes
1. Use the examples script to copy over users.js and index.js (where the error occurs)
$ npm run examples
2. Comment the users array of siteConfig
3. Run build to generate the known error
$ npm run build
4. Implement changes for users validation to allow for optional users array
5. Run build to build fix
$ npm run build
6. Start test site
$ npm start

support optional siteConfig.users

---

admin/extending-remarkable.md
examples/versions/pages/en/versions.js
lib/core/Header.js
lib/core/renderMarkdown.js

Hey 👋
This is a small PR to use the `id` HTML attribute instead of `name` for in-page anchors. The `name` HTML attribute for anchors is obsolete since HTML5 (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a).
On top of that, I also removed redundant anchor elements.

use id html attribute instead of name for in page anchors

---

docs/getting-started-publishing.md

To fix issue https://github.com/facebook/Docusaurus/issues/483 – updating documentation to use CircleCI 2.0.
Changes made:
- Make it explicit that the example is for Circle CI 2.0
- Add a sample YAML text for people to copy into their `.circleci/config.yml`. I find this useful as someone who isn't very familiar with CircleCI because the previous documentation wasn't very explicit as to how the whole file should look like, so it would be nice to be able to copy and paste a sample / default config file.
Let me know if this looks right!
Yes
N/A. No code changes, only documentation.
N/A

Updating documentation for CircleCI 2.0

---

lib/server/generate.js
lib/server/server.js

Fixes #468
We want to be more robust in our path string handling in order to not fail on various platforms.
Yes
Local Docusaurus site testing
N/A

Use Path module functions and properties in server and generate

---

docs/api-site-config.md
examples/basics/siteConfig.js
website/siteConfig.js

Adds documentation for `onPageNav`, which enables secondary, page-specific navigation.
And enable this option for docusaurus.io
Yes
Local site testing
https://github.com/facebook/Docusaurus/pull/475/

Add  documentation for `onPageNav`

---

lib/static/css/main.css

This fixes a css bug that caused the on-page nav to scroll up higher than necessary when the nav is too short.
Yes
Old behaviour: https://deploy-preview-1603--babel-new.netlify.com/docs/en/index.html
Click the last item "Compact" there and see the nav "disappear".
With this fix: https://deploy-preview-1604--babel-new.netlify.com/docs/en/index.html
Clicking "Compact" still keeps the nav in the visible area.
https://github.com/babel/website/pull/1604

Fix on-page nav height css bug

---

docs/api-site-config.md
lib/core/Site.js

This PR adds a new configuration option to set the ID of a Facebook Pixel to track page views.
Using the Facebook Pixel to track page views in the generated docs site.
Yes.
- Create a [Facebook Pixel](https://www.facebook.com/business/a/facebook-pixel) (or get the ID of an existing one.)
- Update your Docusaurus' siteConfig.js file and add a new field named `facebookPixelId` to the exported object `siteConfig`. The value should be the ID of the pixel referenced in the previous step.
- Example `facebookAppId: '352490515235776',`
- Launch your docs site generated by Docusaurus by running `npm start` in the `website` folder.
- Navigate to the home page e.g. `http://localhost:3000/`
- Verify the pixel is firing `Page View` events. These are some of the options:
- Using the [Pixel …

Add Facebook Pixel ID setting

---

examples/basics/core/Footer.js
examples/basics/pages/en/help.js
examples/basics/pages/en/users.js

As outlined in #488, several sections in the Example pages were hard-coded.
Namely, the ``copyright`` inside ``footer.js`, the **edit** link inside ``users.js`` as well as the ``Learn more`` link inside ``help.js``.
This PR seeks to alleviate this behavior by utilizing properties found inside ``siteConfig.js``.
Yes
1. Initialize a new Example page by running ``docusaurus-init``, renaming ``blog-examples-from-docusaurus`` and ``docs-examples-from-docusaurus`` (as outlined in the [Getting started guide](https://docusaurus.io/docs/en/installation.html)) and, finally, running the local web server inside ``website`` via ``npm start`` or ``yarn start``.
2. Inside your browser, navigate to  http://localhost:3000.
3. Check the copyright notice inside the footer. It should look as follows.
4. …

Example Pages: Replace hard-coded values with siteConfig properties

---

lib/static/css/main.css

Fixes: https://github.com/facebook/Docusaurus/issues/485
This had been claimed 5 days ago, but there had been no response so I decided to submit a PR. This is my first one, so let me know if I made any errors, I'll make sure to take care of them.
Preview:

Make sure the sitemap in footer is left aligned

---

lib/static/css/main.css

@JoelMarcey okay, so I investigated a little and realized that the original page didn't actually have as substantial a scrollbar problem as it did once my change was pushed (maybe even not at all).
So I found out that I had incorrectly set the width to `100%` without keeping in mind the margin of `2em`, and it wasn't too difficult to realize that the white space to the right was exactly as big as the margin so I just went ahead and changed the width from `100%` to `calc(100% - 4em)` to account for a `2em` margin on each side. Needless to say, it works perfectly now.
**`calc()` usage**: https://caniuse.com/#feat=calc
**Screenshot**:

Fix problems with a horizontal scrollbar

---

lib/core/Site.js

Fixes a minor bug introduced with the changes for the on-page nav feature. When `<Site>` was being called without a `className` prop, the string `"undefined"` would get added to the body element as a superfluous class name.
Yes
Can be seen in the help page or the blog listing page for example.

Fix body class

---

docs/api-pages.md
examples/basics/pages/en/index.js
examples/basics/pages/en/users.js
lib/core/BlogPost.js
lib/core/GridBlock.js
lib/core/nav/HeaderNav.js
website/blog/2017-12-14-introducing-docusaurus.md
website/pages/en/about-slash.js
website/pages/en/index.js
website/pages/en/users.js

- Resolve part of https://github.com/facebook/Docusaurus/issues/462 
- Improve a11y of Docusaurus
yes
Ran `pa11y http://localhost:3000/` and confirmed no results for `Error: Img element missing an alt attribute. Use the alt attribute to specify a short text alternative` from the [original gist](https://gist.github.com/JoelMarcey/d08263d2acf1819e07538f0a0c5ded93).
N/A
- Add imageAlt to GridBlock
- Set alt equal to `user.caption` for mapped users
- Set alt equal to `post.author` for blog posts
- Update documentation

Add alt tags to images for a11y

---

examples/basics/core/Footer.js
lib/core/BlogPost.js
lib/core/Doc.js
lib/core/nav/HeaderNav.js
website/core/Footer.js

Fix a lesser-known but common security vulnerability in websites.
`rel="noopener noreferrer"` should be added to links containing `target="_blank"` as a precaution against reverse tabnabbing. Since it's common for documentation websites to link to external sites, this should be added by default to the example code (as well as the whole code base).
For more information, please refer to the following article:
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
Yes
Run the website and click on affected links
None

Add rel="noreferrer noopener" to <a> with target="_blank"

---

examples/basics/gitignore
lib/copy-examples.js

This puts `.gitignore` in the root instead of the `website` directory. If one exists, we create an example file to be used and copied from
Fixes #415
Yes
Local testing with and without an existing `.gitignore` file.
N/A

Fix .gitignore placement when running example script or docusaurus-init

---

docs/api-pages.md

In [#docusaurus-users](https://discordapp.com/channels/398180168688074762/398180168688074765), ludeed was asking about changing the image size for a particular `GridBlock` instance. Upon digging into the code, I found that it is possible as `GridBlock` takes in a `className` prop. Unfortunately, that prop is not documented and hence not very discoverable. This PR adds it to the documentation.
Yes
Load page locally.
None

Document className prop of GridBlock

---

CHANGELOG.md
package-lock.json
package.json

Get some bug fixes released.
Yes
Commits have been tested already
N/A

Publish Docusaurus v1.0.10

---

lib/core/nav/HeaderNav.js

Resolves part of: https://github.com/facebook/Docusaurus/issues/462
Yes
Run `pa11y localhost:3000` before and after this change to confirm that the below error was solved.
```
• Error: This form field should be labelled in some way. Use the label element (either with a "for" attribute or wrapped around the form field), or "title", "aria-label" or "aria-labelledby" attributes as appropriate.
├── WCAG2AA.Principle1.Guideline1_3.1_3_1.F68
├── #search_input_react
└── <input type="text" id="search_input_react" placeholder="Search" class="aa-input" autocomplete="off" spellcheck="false" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-labelledby="search_input_react" aria-owns="algolia-autocomplete...
```
N/A

Add form field title for a11y

---

.gitignore
lib/start-server.js
package.json

Revert the incorrect addition of `yarn prettier` to `yarn ci-check` in #516 and run Prettier on the code base.
Yes
Let CI run
#516

Revert yarn prettier addition in yarn ci-check

---

docs/guides-versioning.md

Was copy editing while investigating https://github.com/facebook/Docusaurus/issues/433. 
Yes!
N/A - copy edits.
N/A
***
👋 @JoelMarcey @yangshun, after digging into https://github.com/facebook/Docusaurus/issues/433 it seemed like a docs change to `guides-versioning.md` or `guides-search.md` was not needed? 
I want to check with you if I'm missing something... feel free to ping me here or on the Discord if easier to chat in real time!
The one suggestion I thought was we could present the info in `docs/guides-versioning.md` in a table similar to the Test Plan on https://github.com/facebook/Docusaurus/pull/418 to make it easier to understand the docs? Could do that in this PR if seems like an improvement.
For example:
| Version | Tag | URL
| --- | --- | -- |
| 0.52 | 0.52 | …

Cleanup code markdown

---

lib/server/readMetadata.js

Unsupported header fields might mess up the creation of metadata.js (e.g.: next).
Skip unknown header fields and log a warn about them.
I believe these are all the supported fields at the moment?

Ignore and warn about unsupported header fields

---

.circleci/config.yml

Forgot to do this after enabling translations
Need this otherwise the translation strings will not be uploaded to Crowdin and translations downloaded back to GitHub Pages
Yes
doitlive
#548

Add translations to Circle config

---

lib/core/nav/HeaderNav.js

Even if we were on Spanish pages, it still showed English in the Header nav.
This makes it so that the Header nav shows the currently selected language.
Yes
Local testing - header nav shows the right language
N/A

Fix header nav display for current language

---

lib/server/readMetadata.js

Nuclide treats files with `@generated` as read-only. This can fix that.
Yes
Local site
N/A

Split out @generated string

---

docs/getting-started-publishing.md
website/static/css/custom.css

To create a patch to help resolve this change request: #436
Yes
Tested by re-running server to confirm page is still rendered properly and that the page is still being correctly served. I then ran 'yarn test' and that passed all test cases.
https://github.com/facebook/Docusaurus/pull/508
All Yarn tests passed locally up to most recent commit
For #436, only Markdown code was changed to support HTML5 table elements, and some basic CSS3 styling. No other components were modified or changed.
Do any existing requirements in the baseline conflict with the proposed change?
No.
Do any other pending requirements changes conflict with the proposed change?
No.
What are the business or technical consequences of not making a change?
A less ideal UX (user experience).
Will the proposed change adversely …

Added HTML tables to documentation page to improve UX.

---

docs/api-pages.md

Since #514 has been landed, there's an easy way of making code in table block elements now. 
Yes
#514

Use code block for CompLibrary props

---

lib/server/generate.js
lib/server/renderUtils.js
lib/server/server.js

All modern HTML pages should be served with `<doctype HTML>` in order to trigger standards mode in browsers.
Yes
1. Loaded the website locally (that's how I found out we needed to serve `main.css` with the proper `content-type`.
2. Built the website into static files and loaded the page via a local Python webserver.
Based on #382 by @tonours.

Add <doctype HTML> to HTML pages

---

lib/static/css/main.css

Fixes #571. Shorten search bar by 10% on mobile since it doesn't really make too big of a visual difference being shorter.
This is just a quick fix and the nav bar CSS could probably be improved. There's no need for a `min-device-width` in the media query as the search bar should probably be shortenened for devices below the `min-device-width` as well.
This fix shouldn't affect existing users as shortening the search bar should be a backward-compatible change.
Yes
Tested on latest device resolutions in Chrome Devtools. This width works well on all of the devices available, even iPhone 5S, which is only 320px wide.
The following screenshots were taken on Pixel 2.

Fix search bar width for mobile nav

---

lib/static/css/main.css

Realized that the CSS of the site was using `device-width` media queries, which is [deprecated](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/device-width). Use of `device-width` is not encouraged because it uses the hardware width rather than the viewport width.
This [Stack Overflow thread](https://stackoverflow.com/questions/15276218/css-media-queries-min-width-and-min-device-width-conflicting) explains well why it's a bad idea:
> If your resolution is large enough to get you in one break point, but the width of the browser is small enough to get you in another one, you'll end up with an odd combination of both.
In fact, the site is already suffering from this bug, for example, for the mobile web version of the [installation …

Improve CSS media queries

---

docs/guides-versioning.md

I think that this issue can resolve and close https://github.com/facebook/Docusaurus/issues/433.
Yes!
IS:
WAS:
Follow on to https://github.com/facebook/Docusaurus/pull/545.
cc @yangshun @JoelMarcey  
(1) I considered deleting "Documents from version `1.0.0` will use the url `docs/1.0.0/doc1.html` while `2.0.0` will use `docs/doc1.html`" since seems redundant now, but wanted to run this change by you first. 
(2) I wasn't sure about bumping the version but did so to check my work, can drop the commit if incorrect!

Add table to clarify versioning documentation

---

docs/api-site-config.md
lib/core/Head.js
website/siteConfig.js

Fixes #578
> `og:Image` should work according to https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started, but it looks like it is not.
Yes
local
N/A

Add `twitterImage` to siteConfig options

---

docs/guides-blog.md
lib/core/BlogPost.js

@yangshun and I discussed this issue at our Week 2 meeting. Let me know what you think!
Yes!
First I verified that this functionality already existed by changing Joel's image to Daria. 
//
Then I updated the docs. I thought it made sense to rename `authorImage` to `authorImageURL`, which matches existing `authorURL` and is more self-documenting.
IS:
WAS:
N/A

Allow customizing of blog author image URL documentation

---

docs/api-site-config.md
lib/core/Head.js
lib/core/Site.js

Add customize highlight.theme custom path support. Fixes #428 
eg:
```js
highlight: {
theme: '/somepath/solarized-dark.min.css',
},
separateCss: ['solarized-dark'],
```
Yes
Test success on local
N/A

Add customize highlight.theme custom path support

---

lib/start-server.js

The behavior was changed in #516. With this change, both the command line argument and environment variable will work.

Restore the ability to use the --port command line argument

---

lib/server/server.js

Fixes #237. I'm not entirely sure if this is the best fix as it can be quite an expensive operation if there are many blog posts. IMO a better way would be to watch the blog files and only regenerate when it changes, but both ways has it pros and cons. Feel free to close this if you prefer the file watching method.
Yes
1. Load /blog
1. Change some text in the top blog post
1. Reload /blog
1. Text update is reflected
NA

Regenerate blog metadata on request to blog

---

README.md

There was two times the same link, none of which was pointing to the correct npm package.
Yes
Click on the link and see that the correct npm package is shown

Fix documentation link issue

---

docs/getting-started-installation.md

After going through installation steps for first time, I had thoughts on some changes that could further simplify new users.
- Since `docusaurus-init` is run seldomly, `npx` keeps it simpler, and subsequent runs will be using the latest version.
- `outdated` command provides more meaningful view of current and latest version
- Moved file and directory example down into _Verifying Installation_ section as it is not an actual step to installation, but merely for verifying.
Yes
None
None

Simplify installation steps

---

lib/build-files.js

This adds information to the console log with the full path to the build folder to help aid when deploying a site within a container where folder paths are not absolute or known before hand.

Output the full path to build folder to aid when deploying site.

---

docs/getting-started-publishing.md
docs/guides-blog.md

This PR documents:
* how to use Docusaurus to run in Blog-Only mode by removing the landing page
* how to deploy to Netlify

Documents `Blog Only` Mode and Netlify Hosting

---

website/pages/en/versions.js

- The releases page was incorrectly pointing to Relay's releases page.
- Add missing key to `render`.
- General formatting improvements.
Yes
Load versions page locally and clicked around.
NA

Fix incorrect version links

---

lib/server/readMetadata.js

Receiving header field 'custom_edit_url' is not supported in terminal
Yes
* Add custom_edit_url to any `.md' file
* Start server and verify you receive the not supported message
* Add custom_edit_url into readMetadata.js
* Start server again and verify that that message is no longer reported in terminal
* Regress
None

Do not ignore 'custom_edit_url'

---

examples/basics/siteConfig.js

The user image in the example site is broken due to a wrongly configured path.
Yes
Before
After
NA

Fix example site's user image path

---

lib/static/css/main.css

Fix #356. General changes made:
- Don't uppercase heading cells. This is usually unwanted and should not be a default.
- Switch the stripe background to be on even cells to prevent tables with one row from appearing just gray.
- Make the stripe background color a bit lighter. It was a little too dark.
- Remove some of the unnecessary CSS and selector nesting. 
In general, these changes should be an improvement for existing users unless they have heavily customized the table styling, then it might conflict.
Yes.
Before
After
NA.

Improve <table> appearance

---

docs/getting-started-installation.md
docs/getting-started-preparation.md
docs/getting-started-site-creation.md
docs/guides-custom-pages.md
website/blog/2017-12-14-introducing-docusaurus.md

Improve appearance of directory tree (make it look more like a directory tree).
Yes
Before
After
NA

Improve directory file tree

---

website/core/Footer.js

Noticed this while working on another task on this repo
Yes
IS:
WAS:
N/A
---
cc @yangshun

Update deprecated GitHub Buttons data-count-api

---

lib/static/css/main.css

Make the sidebar look cleaner (less Chrome, more whitespace). I feel that this is nicer and closer to the other documentation sites. Sites that I referenced:
- https://redux.js.org
- https://vuejs.org
- http://docs.vulcanjs.org
- http://graphql.org/learn/
I plan to clean up the CSS and overall theme in subsequent PRs.
Yes
Before
After
Mobile
NA.

Sidebar revamp

---

website/siteConfig.js

This adds Home Assistant as a user of Docusaurus. Based on the previous entry, we want to refer to the logo from another domain, so I linked it from our Docusaurus website.
Screenshot:

Add Home Assistant to users

---

docs/api-site-config.md
lib/core/Head.js
lib/core/Site.js

The code now uses the new gtag script to track the website on google analytics.
The migration is explained [here](https://developers.google.com/analytics/devguides/collection/gtagjs/migration).
This will help to solve issues such as #375.
As indicated at https://support.google.com/analytics/answer/1008080
the analytics code must be placed in the head tag, so it is moved there.
I need to link my website to google search console so, I need the google analytics code to be setup properly
No :)
The new code is on the <head> now, instead of the body. There were no test for this before and I added none
None

Allow Google Analytics to use gtag.js

---

docs/getting-started-publishing.md

I tried following the guide to publish my website on Netlify (on April 29, 2018), however it did not work until I changed the path to include "website/".
I skimmed it briefly after seeing this question.

Incorrect file path for netlify publishing

---

docs/guides-search.md

Hello, Tim from Algolia here. I'm one of the maintainers of DocSearch, and by reading the DocSearch/Docusaurus documentation I thought it could be simplified by slightly rewording the current version.
Here are the main points:
- I explained a bit more how DocSearch works (trying to explain that it's an external service that requires the website to be online)
- I removed mentions to the _search_ API key as in that case, it's always a _search_ (as opposed to _admin_) API key that is used
- I removed the part about faceting on the version. I thought it was confusing as without a specific UI to display the faceting, this part alone won't do much. I might submit a PR later to specifically handle faceting by version, including the required layout changes, but as it was today I think it would …

Simplifying DocSearch documentation

---

lib/core/nav/HeaderNav.js
lib/static/css/main.css

Resolves: https://github.com/facebook/Docusaurus/issues/613
yes
IS with this PR:
Mobile:
Tablet (no change):
Desktop (no change):
***
WAS:
Mobile:
Tablet (no change):
Desktop (no change):
It didn't seem like a docs update was necessary?
cc @yangshun @JoelMarcey

On mobile, hide title if logo exists

---

lib/server/env.js

Implemented the solution provided [here](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/) to allow the footer to stick downward no matter how much content the page contain.
Have a footer hanging above with a space below when not enough content is added is something that bothers everyone. Implementing that behavior on desktop is simple and progressively enhance the look of the website on new browsers.
Yes
This is a UI change affecting only the main stylesheet. I have tested the solution on the latest versions of the modern browsers (Firefox, Chrome, Safari, Edge) and IE11
Before:
After:
There were actually 2 issues when I was implementing that behavior:
1. The lack of stylesheet methodology to be followed. I have added my modifications to the end of the file.
2. For …

Implement sticky footer using flexbox

---

lib/server/env.js
lib/static/css/main.css

Cross browser compatibility sets good example in open source project. There are few issues happening in Internet Explorer 11 that blocks the usage of the website for its users.
Yes
This PR will mostly be about UI changes that would affect CSS only. Plans for testing would be testing the UI on IE11 and another major browser (like Chrome) to ensure the updates doesn't break the new browsers as well as testing on mobile device.
https://github.com/facebook/Docusaurus/issues/585

[WIP] Fixes for Internet Explorer 11

---

lib/static/css/main.css

This is an issue on IE11, it cannot pick the correct system font because the font `-apple-system` makes the value invalid and hence making the whole declaration invalid.
A good solution is to split the shorthand version into separate properties/values and it will work.
Part of fixing issues on IE11 https://github.com/facebook/Docusaurus/issues/585
Yes
This is a UI issue, testing on IE11 and other browsers will be sufficient to prove it is working

Fix font rendering on IE11

---

lib/static/css/main.css

This is a known issue on IE11 caused by the fact that IE add the padding value to the `flex-basis` leading to increase in the size of the column beyond intended. The block behave as if has `box-sizing` set to `content-box` even if it is set correctly.
Reference: https://github.com/philipwalton/flexbugs#flexbug-7
Part of fixing issues on IE11 https://github.com/facebook/Docusaurus/issues/585
Yes

Fix flex children's width not calculated correctly

---

package-lock.json
yarn.lock

A package used by a number of packages we depend on has a vulnerability. Consumers shouldn't be affected since they are doing fresh installs and version ranges will prevent it from being an issue. However due to lock files we'll keep installing that locally.
This change simply wipes out node_modules, yarn.lock, package-lock.json then installs (with npm and then yarn) to regenerate lock files.

Regenerate package lock files

---

lib/core/BlogPost.js

Deprecate `authorImage`. We now use `authorImageURL`. 
yes
N/A, addressed in https://github.com/facebook/Docusaurus/pull/577.
`authorImage` was replaced by `authorImageURL` in https://github.com/facebook/Docusaurus/pull/577.
`authorImage` was then removed from react-native-website in https://github.com/facebook/react-native-website/pull/314. So now `authorImage` can be removed from Docusaurus.
`authorImage` was undocumented to begin with, so no docs changes.

Remove authorImage

---

docs/getting-started-publishing.md

Docusaurus publishing doc might be confusing, it should be https://facebook.github.io/Docusaurus when referring to GitHub Pages URL, not the custom domain at https://docusaurus.io/
Yes
```
cd website
npm run build
npm run start
```
Check the latest version documentation at http://localhost:3000/docs/en/next/publishing.html
Not applicable
Might need to change all the previous version of documentation as well. Documentation for v1.0.15 and below will still use https://docusaurus.io/ instead of https://facebook.github.io/Docusaurus

Improve publishing guide on Github Pages

---

lib/copy-examples.js
package.json
yarn.lock

cc @yangshun This might be way off...wondering if there is anything wrong at first glance.
I `rm -rf website/` in Docusaurus. 
I tried replacing an existing `console.log` with new text.
When I run `docusaurus-init`, the old text appears, even though it's been deleted from the codebase. Is the repo reading `docusaurus-init` from npm or something and not from local `copy-examples.js`?

Print out directory tree during docusaurus-init

---

docs/api-site-config.md
lib/core/Site.js
lib/static/css/main.css
website/core/Footer.js
website/siteConfig.js

This feature/enhancement was requested in #218 .
Yes
```
cd website
npm run start
```
Test 4 cases by tweaking siteConfig.js:
1. With facebook & twitter (facebookAppId & twitterId exist)
2. No facebook & twitter (facebookAppId & twitterId does not exist)
3. No facebook (facebookAppId does not exist & twitterId exist)
4.. No twitter (facebookAppId exist & twitterId does not exist)
Check updated docs for api siteconfig
1. Remove `docs` from .npmignore
2. Run the website
```
cd website
npm run start
```
3. Latest doc at http://localhost:3000/docs/en/next/site-config.html
Run test in root folder
```
npm test
```
#625 Facebook share dialog won't work if app is not set to public

Enhance footer with Facebook and Twitter buttons

---

lib/server/generate.js

I tried to add a custom page to Docosaurus
Build the static files
```
cd website
yarn build
```
But got an error `en is not defined`
This is because of a typo
https://github.com/facebook/Docusaurus/blob/b66045f28478e05a7de701bb644412c1898fc0af/lib/server/generate.js#L533
It should be
```writeFileAndCreateFolder(targetFile.replace(sep + 'en' + sep, sep), str);```
Yes
```
cd website
yarn build
```
Run test in root folder
```
yarn test
```
#490

Fix undefined variable error when adding custom page

---

lib/version.js

As discussed in #369, we have to give better error message if `version.js` file is missing in `pages/en` directory.
The solution was to add warning console if someone ran the version script before creating the `versions.js` page
Yes
Warning console example if `version.js` file is not found
Success example if `version.js` file is found
Run `yarn test` and it pass all unit test
No

Show warning console if version.js file is missing

---

package-lock.json
package.json
yarn.lock

Fixes a bug where `opn` is not installed by default because it's in `devDepenencies` of `package.json`.
Yes
`npm start` and see that website still opens.

Shift opn to dependencies

---

lib/static/css/main.css

adding supports ((position: -webkit-sticky) to support Safari

onPageNav not showing on Safari #686

---

docs/getting-started-installation.md

Documentation on how to launch the development server behind a corporate proxy.
Fixes #603

Add documentation to launch development server behind a proxy #603

---

lib/server/server.js

Noticed high CPU usage when start a project. When printed out [a list of files to be watched](https://github.com/shama/gaze/blob/master/lib/gaze.js#L189) saw 12k files from `node_modules`. And since `gaze` [supports the negate pattern](https://github.com/shama/gaze/blob/master/test/patterns_test.js#L27) I'd like to add `!node_modules/**/*`.
Related issue https://github.com/facebook/Docusaurus/issues/699
Yes, I did.
https://github.com/facebook/Docusaurus/issues/699

Don't watch node_modules dir in dev server mode

---

docs/getting-started-publishing.md

Fix typo error on `Tips & Tricks`

---

lib/write-translations.js

I found wrong logic on `lib/write-translation.js`
```javascript
const path = require('path');
...
if (fs.existsSync(path)) {  // wrong code. `path` is NodeJs module
currentTranslations = JSON.parse(
fs.readFileSync(CWD + '/i18n/en.json', 'utf8')
);
}
```
As a result, `currentTranslations` is always empty.
Because, the contents of `i18n/en.json` are always lost.
It's correct code
```javascript
if (fs.existsSync(CWD + '/i18n/en.json')) {
currentTranslations = JSON.parse(
fs.readFileSync(CWD + '/i18n/en.json', 'utf8')
);
}
```
Yes

Wrong logic on `write-translation.js`

---

lib/static/css/main.css

Extra padding in quote block makes all the text not vertically aligned. Looks weird.
Yes
Linking to a page in the netlify preview deploy that shows the padding removed.
None

Disable the padding of the p tag inside the blockquote tag

---

lib/server/generate.js
lib/server/server.js
website/pages/en/about-slash.js
website/pages/en/help.js
website/pages/en/users.js
website/pages/en/versions.js

Fixes #478 and https://github.com/prettier/prettier/issues/4062
When user write custom pages like `users.js`, they cannot set their own title in the browser. It is defaulted to general title of the website. This simple PR fix this issue.
Yes
```
cd website
yarn start
```
http://localhost:3000/en/users.html
Not providing title in `pages/en/user.js`
```js
class Users extends React.Component {
render() {
// ... some code
}
}
module.exports = Users;
```
Providing title in `pages/en/user.js`
```js
class Users extends React.Component {
render() {
// ... some code
}
}
Users.title = 'Who is using this';
module.exports = Users;
```
http://localhost:5000/en/users.html
Not providing title in `pages/en/user.js`
Providing title in `pages/en/user.js` …

Enable setting of title for custom pages

---

docs/api-pages.md

Follow-up PR #704 
Yes
http://localhost:3000/docs/en/next/api-pages.html
https://deploy-preview-712--docusaurus-preview.netlify.com/docs/en/next/api-pages.html

Add custom title for page documentation

---

lib/publish-gh-pages.js

I actually wanted something else of the publish script, and was looking into submitting another PR.
Then I found this bug.
In the publish script, shelljs' command output that parses the current branch wasn't unwrapped nor trimmed.
This means that when checking if the deployment branch is the same as the current branch, it would be comparing `master` to `{ stdout: 'master\n', stderr: '', ...etc }`. Which is `false`, of course -- so the script would continue and cause #406.
Skimmed through it (it's 2am in Sydney now 😴), I expect it to be the same as most other OSS projects
Try publishing to an user/org site while you're on the `master` branch. Or to a project site when you're on `gh-pages`...
**The boom 💥**
_Have you read any cryptic error messages today?_
**The fix 🤕**
Ah, clear error …

Fail properly when current branch is the same as the deployment one

---

docs/api-site-config.md
docs/getting-started-publishing.md
examples/basics/siteConfig.js
lib/publish-gh-pages.js

In attempting to use Docusaurus for internal documentation in my employer's Github Enterprise server, I discovered that publish-gh-pages script assumes github.com.
Yes.  I found no issue even matching 'enterprise', which I would expect if others had tried this.
I verified by actually publishing to my company's Github Enterprise server. 
I updated the appropriate docs files in the `master` branch: 
- docs/api-site-config.md
- examples/basics/siteConfig.js
I assume that your CI process uses docs in master and runs a `publish-gh-pages`; and thus there is no need for a separate PR for docs? 
Let me know,  I'm happy to include a separate PR …

Support for Docusaurus gh-pages on Github Enterprise

---

lib/server/env.js
lib/start-server.js
lib/version.js

This prevents user to start the server when `versions.js` is missing but versioning is enabled
#betterengineering
Closes #228 based on https://github.com/facebook/Docusaurus/issues/228#issuecomment-368748690
Related to #297 #369 
Yes
```
cd website
yarn start
```
```
cd website
yarn start
```

Don't start server if versions.js is missing but versioning is enabled

---

lib/core/nav/HeaderNav.js

Fixes #732  
Yes
```
cd website
yarn start
```
**Before this PR**
Choosing language will reset to homepage and default version.
**After this PR**
Choosing language will only change the language of the URL. Does not reset version / go back to homepage
Note that the demo cannot find the file because when we preview on localhost, we have not gone through the Crowdin upload and download processes yet like we will when we publish via Circle (see our circle.yml file).

Choosing another language doesn't reset version & url

---

lib/server/server.js

I unintentionally put ^ on docs & blogs regex for development server routing on previous PR #677.
I'm reverting it because if `baseUrl` is not `/`, it won't handle the request
Yes
Use non `/` baseUrl (e.g: `/test/`)
```
cd website
yarn start
```
http://localhost:3000/test/blog works
http://localhost:3000/test/blog
#677

Fix Express.js regex for docs & blog

---

website/pages/en/versions.js

Current versions page always point to english docs despite being in another language.
Check https://docusaurus.io/ro/versions.html links and you'll see that links points to `/en/`
Yes
http://localhost:3000/ro/versions.html links point to `/ro/` docs
http://localhost:3000/en/versions.html links point to `/en/` docs

Fix Docusaurus versions page to links to correct language

---

lib/core/nav/SideNav.js
lib/static/css/main.css

This PR adds support for onPageNav for mobile and tablet devices
This PR closes #662 
Yes
For tablets I've decided to show onPageNav instead of sideNav. The sideNav is accessible through breadcrumbs menu like on mobile devices.

Show onPageNav on mobile devices

---

docs/api-site-config.md

@endiliey shipped a feature to allow doc nesting. This PR removes the outdated restriction in siteConfig regarding docs nesting.
Yes
NA. Doc change.
#705

Remove outdated restriction regarding docs nesting

---

lib/core/nav/HeaderNav.js

Remove hardcoded `.html` extension from HeaderNav.js
Missed this one out from #677 
Yes
**Before**
Still use `.html` extension when `cleanUrl` is true. Although the page without `.html` version is also accessible.
**After**
Don't use `.html` extension when `cleanUrl` is true

Fix HeaderNav linking to versions page to depends on cleanUrl

---

docs/api-pages.md
lib/core/Head.js
lib/server/generate.js
lib/server/server.js

1. Fixes #751
2. Enable user to set their own description (Inspired from #704)
`<meta name="description" content="" /> `
Search engines show the meta description in search results mostly when the searched for phrase is contained in the description. Optimizing the meta description is a very important aspect of on-page SEO 
`<meta property="og:description" content="" />`
This is used for Open Graph description meta. Usually used by crawler of social media like Facebook / Twitter
Yes
Previously, all custom pages description will always be `tagline` because we never pass `description` props.
https://github.com/facebook/Docusaurus/blob/18c01327a3082962165263c37b4a49d5426fbf53/lib/core/Site.js#L31
Adding custom description for your custom pages is as simple as adding description class property …

Enable custom meta description for custom pages

---

lib/core/Head.js

This hopefully fixes a bug reported in jest:
https://github.com/facebook/jest/issues/6418
Yes
I considered adding a test for this, but there didn't appear to be any for this file.  I can add them if you would like.  For the time being, all I did was use the following as a smoke test:
- view-source:https://facebook.github.io/jest/blog/
- confirm `og:image` url works: https://facebook.github.io/jest/img/opengraph.png
- confirm `atom.xml` url is incorrect: https://facebook.github.io/blog/atom.xml
- after this pr, it *should* match: https://facebook.github.io/jest/blog/atom.xml

Adding baseUrl to feed links.

---

docs/guides-search.md

I added back information about extra search options for Algolia. A previous commit removed the section about extra search options, but it appears the information might actually be useful.
Fixes #743 

Add back information about extra search options

---

lib/rename-version.js

Fixes #227 (edited by Endiliey)
To fix the sidebars.json rename-version bug reported here: [Bug 227](https://github.com/facebook/Docusaurus/issues/227)
Yes
The issue was with sidebar file not being renamed on using rename-version command
To test it you can follow this:
1) Checkout the master branch of Docusaurus
2) Use this command to create a new version: `yarn run version 1.2.3`
3) Rename the version using this command: `yarn run rename-version 1.2.3 1.2.4`
4) Notice the file in versioned_sidebars, it won't have been renamed
5) Clear all the changes and checkout the branch in this PR
6) Repeat steps 2 and 3 and notice that the file will be renamed

fix sidebar file name issue in rename-version

---

lib/server/sitemap.js

If you have `cleanUrl` enabled, make the sitemap have no `.html` extension at the end too. Otherwise keep the `.html` extension.
Ref: https://github.com/facebook/Docusaurus/pull/744#issuecomment-396492849
Yes.
https://github.com/facebook/Docusaurus/pull/744

Configure sitemap depending on whether clean URLs enabled

---

docs/getting-started-publishing.md
lib/publish-gh-pages.js

I'm maintaining the [express-validator org](https://github.com/express-validator), and I like keeping docs close to the source, so that external contributors and I can submit PRs that contain the complete change.
👍 
1. Have your source docs in one repo (say `foo/foo`), and point `siteConfig.js` to another (e.g. set `projectName` to `foo.github.io`);
2. Make sure you're on the `master` branch;
3. Run the `publish-gh-pages` script;
4. Note how the script doesn't complain about publishing from `master` and to `master`. `foo.github.io` should now have been updated with the latest version of your awesome docs written with Docusaurus;
5. Make a change, repeat, profit!
1. Point `siteConfig.js` to the repo the docs are going to be hosted on -- e.g. set `organizationName` to `foo` and …

Cross repo publishing

---

docs/api-commands.md
lib/server/server.js
lib/start-server.js

I ran into an issue where the live reload (specifically file watching) was causing CPU pegging when used with Docker on Mac (https://github.com/docker/for-mac/issues/1759). Disabling live reload fixes the issue and doesn't make the laptop fan go at full blast.
Yes
I could not think of a graceful way to test this in the automated test suite.
This pr adds a `--live` option to `docusaurus-start` that defaults to true, so does not change the default behavior. If you do `--no-live` it won't run the live reload server.

Add option to disable live reload server during development

---

docs/api-site-config.md
docs/guides-blog.md
lib/core/BlogPostLayout.js
lib/core/BlogSidebar.js

This seems like one of the only (or the only) pieces of copy that I couldn't configure myself. I wanted to change the casing of the sidebar title.
Yes.
Config:
Preview in UI:
https://github.com/facebook/Docusaurus/pull/432

Add config option for setting title of the blog sidebar

---

lib/core/__tests__/anchors.test.js
lib/core/anchors.js

Found a bug because one of our Markdown docs contained an empty heading
```md
##
Notice the empty Heading 2, makes the anchors `toSlug()` crash because of the internal `toString()` usage
```
Here's part of the stacktrace:
```sh
TypeError: Cannot read property 'toString' of undefined
at module.exports (/[...]/node_modules/docusaurus/lib/core/toSlug.js:41:6)
at Object.md.renderer.rules.heading_open (/[...]/node_modules/docusaurus/lib/core/anchors.js:16:20)
at Renderer.render (/[...]/node_modules/remarkable/lib/renderer.js:71:39)
at Remarkable.render (/[...]/node_modules/remarkable/lib/index.js:152:24)
[...]
```
Yes
I added a test to specifically check for these cases.

Fix anchors erroring when heading is empty

---

lib/core/nav/SideNav.js

1.) Go to website/siteConfig and set onPageNav to false or anything other than 'separate'.
2.) go to the web app and click on the docs page then shrink the screen down to mobile size.
RESULT: the three dot menu should not display.

Hide TOC menu when onPageNav is not separate

---

lib/core/DocsLayout.js
lib/core/Site.js

- Fixes #780 & https://github.com/babel/website/issues/1693
Our docs prev/next button is build with relative path in mind. But relative path is really `relative`
If our current url is https://babeljs.io/docs/en/babel-plugin-transform-runtime
`<a href='babel-register'/>` will translate to https://babeljs.io/docs/en/babel-register
If our current url is https://babeljs.io/docs/en/babel-plugin-transform-runtime/
`<a href='babel-register'/>` will translate to https://babeljs.io/docs/en/babel-plugin-transform-runtime/babel-register which is wrong
The fix is to use absolute url 😄 
Yes
Before
Go to https://docusaurus.io/docs/en/installation/ (notice the ending slash `/`) and click `previous/next` button, 404 page
After
Go to http://localhost:3000/docs/en/installation/ (notice the ending slash …

Use absoluteURL instead of relativeURL for next/prev links

---

lib/core/Head.js
lib/core/Site.js

https://github.com/algolia/docsearch-configs/pull/454#issuecomment-396883396
In order to help algolia docsearch scrape our docs better, we will provide Docsearch metadata.
cc @s-pace
Provide docsearch metadata on head. Example:
```
<meta name="docsearch:version" content='1.2.1'>
<meta name="docsearch:language" content='en'>
```
Yes
Before
After

Add language & version meta for algolia docsearch

---

docs/api-doc-markdown.md
docs/guides-blog.md
examples/basics/pages/en/help.js
lib/core/BlogPageLayout.js
lib/core/BlogPost.js
lib/core/BlogPostLayout.js
lib/core/Doc.js
lib/core/DocsLayout.js
lib/core/Site.js
lib/core/nav/SideNav.js
lib/server/generate.js
lib/server/server.js
lib/static/css/main.css
website/core/Footer.js
website/pages/en/help.js
website/pages/en/index.js
website/pages/en/users.js
website/sidebars.json

I removed a lot of Docusaurus base CSS and use styles from GitHub's markdown styles. Also took the chance to remove some unreferenced CSS and cleaned up some implementations. The site should look nicer now (IMO) 😄 
Some changes
- Improved typography - paddings and margins are more consistent now
- Removed unnecessary styling in GridBlock
- Footer is now darker shade of black for better contrast
- Change background color to #fff 
- Headers are now black by default (from primaryColor) and have bolder font weight
- Blockquotes are changed to yellow (from pink)
- Left sidebar is sticky by default on supported browsers
Yes.
Load preview site on laptop and mobile and click on all pages. I did a pretty thorough comparison of the live site and the development site.
NA.

CSS revamp - Improve typography and overall styling

---

lib/core/Site.js

As per https://docusaurus.io/docs/en/search#extra-search-options
> Any occurrences of "VERSION" or "LANGUAGE" will be replaced by the version or language of the current page, respectively. 
However, the current implementation is currently broken, while algolia docsearch expect something like '1.3.0', we provide 'current' as the version if we are currently in the latest stable version. 
https://github.com/facebook/Docusaurus/blob/c5661b0e1e131803709852adc2283fb4894aabcc/lib/core/Site.js#L36-L43
https://github.com/facebook/Docusaurus/blob/c5661b0e1e131803709852adc2283fb4894aabcc/lib/core/Site.js#L130-L134
Docusaurus.io docsearch is working fine because we don't search according to current version.
Yes
Use this algolia index for testing and use version facetfilters
```
algolia: {
apiKey: …
```

Fix bug unable to search docs according to its version

---

lib/copy-examples.js
package-lock.json
package.json
yarn.lock

Fixes #790. Also adds a try/catch around the tree printing so that it fails gracefully. The tree printing is a secondary action that doesn't affect the directory scaffolding.
Yes.
Ran `tree-node-cli` command on hhast locally and excluded `vendor` directory. The directory was printed successfully.
```
$ tree . -I "vendor"
hhast
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── bin
│   ├── hhast-inspect
│   ├── hhast-lint
│   ├── hhast-migrate
│   ├── update-codegen
│   └── update-schema
├── codegen
...
```
NA

Exclude vendor dir from directory tree printing

---

lib/core/__tests__/routing.test.js
lib/core/routing.js
lib/server/server.js

This fix a bug on our express.js routing classifying `blog` docs as blog pages. 
Consider this scenario, user create a `blog.md` in docs folder
```
---
id: blog
title: blog
---
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupi
```
What happen when we access `/docs/en/next/blog` ?
It is misclassified as blog pages due to express.js routing defined at
https://github.com/facebook/Docusaurus/blob/c5661b0e1e131803709852adc2283fb4894aabcc/lib/server/server.js#L278
This PR ensure more …

Fix bad routing regex for docs & blogs

---

lib/static/css/main.css

Fixes #793 
Yes
Normal height page
Short height page
#757

Show scrollbar only when sidebar is too long

---

lib/core/nav/HeaderNav.js

Prevent the page scrolling to the top when you click the Languages button on the header
Yes
```bash
cd /path/to/docusaurus-repo
yarn
cd website
npm run start
```
Scroll down the page a bit, click the languages button on the header and ensure it doesn't scroll back to the top

Prevent page scrolling to top when clicking languages button on header

---

lib/server/sitemap.js

https://github.com/facebook/Docusaurus/pull/799#issuecomment-399825501
Our sitemap url for blog is always wrong due to wrong logic. 
Consider this
Yes
Before
After
#765

Fix wrong sitemap for blog

---

website/blog/2017-12-14-introducing-docusaurus.md
website/data/users.js

Updating the Jest URL for the new site.
Yes
Verify the Jest URL has been update on the [home](https://deploy-preview-807--docusaurus-preview.netlify.com/en/) page users section, [users](https://deploy-preview-807--docusaurus-preview.netlify.com/en/users) page and the [Introducing Docusaurus](https://deploy-preview-807--docusaurus-preview.netlify.com/blog/2017/12/14/introducing-docusaurus#acknowledgements) blog post.
See facebook/jest#6549

Switch Jest URL to jestjs.io

---

lib/build-files.js

Fix #805 
Yes
Try with https://github.com/facebook/react-native-website, delete versioned_docs/version-0.5/removing-default-permissions.md from master.
Run docusaurus build
Before
After
Try with Docusaurus, delete first doc from versioned_docs version-1.0.11 and `yarn build`
Before
After

Handle build-files promise error & exit properly

---

lib/core/__tests__/routing.test.js
lib/core/routing.js
lib/server/server.js

Changes
- Fix `sitemap.xml` routing to be properly on it's correct place.
Example: when baseUrl is `/jest/`, it should only be accessible at `/jest/sitemap.xml` and not at `/sitemap.xml`
- Fix `blog/atom.xml` and `blog/feed.xml` routing to be properly in it's correct place
- Fix wrong logic/ bug where `blog/test.xml` or any `blog/*.xml` will send `blog/feed.xml`
- Fix wrong logic at blog routing in which if file does not exist, we properly exit (not send wrong file) & use `next` middleware function
- Fix page routing regex, previously all `.html` files will hit this path, we should ignore it if it's `docs` or `blog` pages. 100% more efficient
- Add a lot of tests with jest to catch regression & routing regex are refactored to `lib/core/routing.js` so that our routing is still true in v2
- …

Fix & refactor server routing + add tests

---

lib/core/BlogPostLayout.js
lib/static/css/main.css

Fix #814 
It should be
```js
className="fb-like"
```
According to https://developers.facebook.com/docs/plugins/like-button/
Instead of
```js
className="fbLike"
```
Yes
#757 renamed "fb-like" to "fbLike"

Fix missing fblike button in blog

---

lib/start-server.js

#799 make the routing stricter to properly use baseUrl to prevent routing bugs.
However, currently local dev will always load `localhost:port` regardless of baseUrl. We should always load the correct baseUrl.
Fix #818 
Yes
use `/reason/` as baseUrl
```
cd website
yarn start
```
use `/` as baseUrl
```
cd website
yarn start
```

Open browser with correct baseurl

---

lib/publish-gh-pages.js

Current implementation of publish-gh-pages is slightly misleading. 
Consider this latest commit on `master` branch
https://github.com/facebook/Docusaurus/commit/8d45669f924a38e628d01066b6fc855eaff7e8d7
When this got pushed, our circleci run `publish-gh-pages` and deploy the website at `gh-pages` branch
https://github.com/facebook/Docusaurus/commit/85ff1544384b0ecab344b19a72393790e50acd73
If we look carefully, the commit message is
```
Deploy website version based on 1e6aa2b
```
And commit 1e6aa2b is actually just the previous commit on `gh-pages`
This is *WRONG*, we should display the commit that triggers the publish. Like this
```
Deploy website version based on 8d45669
```
This is caused by calling `git rev-parse HEAD` on the wrong branch. 
Before this PR, we try to `git checkout …

Publish-gh-pages should display the correct commit that triggers it

---

lib/core/__tests__/utils.test.js
lib/core/utils.js
lib/server/generate.js
lib/server/server.js
lib/server/sitemap.js

#765 missed the implementation for langUrl, so the sitemap url is wrong for alternate url
In addition, I refactored few places to use `getPath` function instead of using `replace(/\.html$/, '')` just for reusability. Added tests also for regression on the function
Yes
Test all url seems to work locally
And sitemap is now correct on alternate
#765

Fix wrong sitemap for alternate url

---

lib/core/renderMarkdown.js

Fix wrong CSS language prefix for fenced blocks

---

lib/static/css/main.css

Fix #822
Yes
Change first word of `getting-started-installation.md` to
```markdown
*Docusaurus*
```
#757

Fix phrase emphasis not italicized

---

docs/api-site-config.md

Slight edit to the documentation as suggested in https://github.com/facebook/Docusaurus/issues/857#issuecomment-406515613

Improve baseUrl documentation with an example

---

lib/server/__tests__/__fixtures__/test.css
lib/server/__tests__/__snapshots__/utils.test.js.snap
lib/server/__tests__/utils.test.js
lib/server/generate.js
lib/server/utils.js
package.json
yarn.lock

Add [autoprefixer](https://github.com/postcss/autoprefixer) as a final build step in the CSS pipeline.
Fix #784 
Suggestion from #784 to add autoprefixing to the CSS pipeline. 
Yes
- Added `autoprefix css` unit test in `utils.test.js`, modeled after the `minify css` test.
- Updated `test.css` to include css rule that triggers autoprefixer. Updated snapshots of the `minify css` test to include the new css rule. 
None.

Add autoprefixing to CSS pipeline

---

lib/server/__tests__/__fixtures__/2018-08-17-docusaurus.md
lib/server/__tests__/__snapshots__/blog.test.js.snap
lib/server/__tests__/blog.test.js
lib/server/blog.js
lib/server/docs.js
lib/server/generate.js
lib/server/readMetadata.js
lib/server/server.js

Mostly refactoring into reusable functions and add small test for it
1. Refactor duplicate/ similar logic in `server.js` and `generate.js` and `readMetadata.js` to `getMetadata` in `blog.js` 
https://github.com/facebook/Docusaurus/blob/9f718a5097dfa7f549690a711fb151ea82a335a8/lib/server/generate.js#L156-L164
https://github.com/facebook/Docusaurus/blob/9f718a5097dfa7f549690a711fb151ea82a335a8/lib/server/server.js#L255-L267
https://github.com/facebook/Docusaurus/blob/9f718a5097dfa7f549690a711fb151ea82a335a8/lib/server/readMetadata.js#L326-L335
1. Refactor duplicate in `server.js` and `generate.js` to `getPages` in `blog.js`
https://github.com/facebook/Docusaurus/blob/9f718a5097dfa7f549690a711fb151ea82a335a8/lib/server/server.js#L202-L224 …

Refactor(server): share logic between server.js & generate.js

---

lib/core/renderMarkdown.js
lib/static/css/prism.css

CSS class for Prism.js still look to be incorrect - this prevents using existing Prism.js themes out of the box.
See: https://github.com/PrismJS/prism/blob/master/themes/prism-coy.css
Yes - and signed CLA.
No tests required.
#735 #842

Correct Prism CSS class for code blocks

---

lib/core/renderMarkdown.js

Close #874 
Currently, [highlight.js supported languages](https://github.com/highlightjs/highlight.js/tree/master/src/languages) and [prism.js supported languages](https://github.com/PrismJS/prism/tree/master/components) does not support `text` language
Our current logic for unsupported prism.js / highlight.js language is that we try to detect the language automatically with this code below:
https://github.com/facebook/Docusaurus/blob/75538395beb3bcd7591f586877d5971c51d4f5db/lib/core/renderMarkdown.js#L57-L59
Hence, there is no way for user to remove any highlighting for code block defined like this
It will be detected as JavaScript although it has been tagged as 'text' by user
This PR enables user to have `code block style without any highlighting` by using `text` language
Yes
````text …
```

feat(markdown): support `text` language for code block style without any highlighting

---

admin/prerelease.md
scripts/prerelease.sh

Simplify maintainer process before releasing new version
Yes
Click this asciinema preview
https://asciinema.org/a/hZ7NNJPcgtdvzm5tMLLfHflMD
[![asciicast](https://asciinema.org/a/hZ7NNJPcgtdvzm5tMLLfHflMD.png)](https://asciinema.org/a/hZ7NNJPcgtdvzm5tMLLfHflMD)

chore: add prerelease script

---

CHANGELOG.md
lib/server/generate.js

Fix #701 
There is no error handling on https://github.com/facebook/Docusaurus/blob/ef80581e8ef950a0865fc7851407c672c4bbd510/lib/server/generate.js#L255-L264
If the image compression fails, it will cause the image to be missing.
Example: 
https://circleci.com/gh/facebook/Docusaurus/2846
The build succeed but along the line there is an unhandled promise. Causing `christopher-chedeau.jpg` and `ricky-vetter.jpg` to be missing.
This PR add a fallback functionality to copy the image as it is if the image compression fail
Yes
https://deploy-preview-887--docusaurus-preview.netlify.com/
#654

fix: copy static image as it is if image compression fail

---

lib/server/__tests__/docs.test.js
lib/server/docs.js
lib/server/env.js

Fix https://github.com/facebook/react-native-website/issues/505
If we set `defaultVersionShown` in Docusaurus
```js
const siteConfig = {
defaultVersionShown: '1.3.1',
// .....
};
```
When we go to http://localhost:3000/docs/en/1.3.1/site-preparation the docs linking is wrong, it became http://localhost:3000/docs/en/installation instead of http://localhost:3000/docs/en/1.3.1/installation
Yes
After this PR the docs linking is now correct

Fix: correct docs linking for custom `defaultVersionShown`

---

lib/server/sitemap.js

Fix #901. Currently the URLs in sitemap are incorrect when `baseUrl` != `/`. This PR fixes the bug.
yes
It works locally.
When baseUrl = `/`

add baseUrl to sitemap URLs

---

docs/getting-started-installation.md

Use of word Github is very confusing. When starting, most of devs wont have an existing github repo. And normally not everyone will be using Github. Since devs will be following this step by step: we need to stress on telling them to create a new or use existing local project folder which may or may not be a github repo.
Installation is foremost step to begin with this framework and this PR makes its more intuitive. 
Yes
No code changed. Only textual change for now
This PR updates the doc

Updating step 2 to be more intuitive: "Avoiding use of the word github"

---

lib/core/nav/SideNav.js

Fixes #908 
Yes.
Run site - no errors :)
None.

Fix console error when onPageNav !== 'separate'

---

lib/server/server.js

When using `docusaurus-start` a server [treats any request that ends with `main.css`](https://github.com/facebook/Docusaurus/blob/e79e67ad2b765e0f4124a4325ad3d4e555a763c3/lib/server/server.js#L310) as one to serve `css/main.css`. That could break some custom assets in `static` dir that also have `main.css` name.
Yes.
1. `css/main.css` is served:
- run `docusarus-start` 
- ensured a home page loads `css/main.css`
1. `css/main.css` and custom main.css are served:
- added `api/main.css` to `static` dir
- updated `siteConfig.js` with `separateCss: ["static/api"]`
- run `docusarus-start`
- ensured both `css/main.css` and `api/main.css` are served
None.

Fixed css/main.css route

---

lib/core/__tests__/utils.test.js
lib/core/utils.js

Fix #922 and https://github.com/babel/website/issues/1780
cc @hzoo 
- Pretty/cleanUrl should only remove html extension and not other extension
- Stronger test for the `getPath` function that transform url to clean url.
- cleanUrl of `/react/index.html` should be `/react/` and not `/react`
yes
```md
//2018-08-27-7.0.0.md
---
layout: post
title:  "Babel 7 Released"
author: Henry Zhu
authorURL: https://twitter.com/left_pad
date:   2018-08-27 18:00:00
categories: announcements
share_text: "Babel 7 Released"
---
After almost 2 years, 4k commits, over 50 pre-releases, and a lot of help we are excited to announce the release of Babel 7. It's been almost [3 years](https://babeljs.io/blog/2015/10/29/6.0.0) since the release of Babel 6! There's a lot of moving parts so please bear with us in the …
```

fix: transformation of url to cleanUrl / pretty url

---

docs/guides-translation.md
lib/core/DocsLayout.js
lib/core/Redirect.js
lib/core/Site.js
lib/core/nav/HeaderNav.js
lib/core/nav/SideNav.js
lib/core/utils.js
lib/server/readMetadata.js
lib/write-translations.js
package.json
website/data/custom-translation-strings.json
yarn.lock

Fixes #916
Fixes #324
Initially experienced at https://github.com/babel/website/pull/1770#issuecomment-416014039, later worked along with @endiliey on Discord room to find the issues and work on a fix. The main issues are explained in #916.
Yes I did
Tested on [sample repo](https://github.com/notlmn-dump/doc-test), to work as expected as explained in #916
This PR changes the way customized localization strings are handled. Existing setups should not break that bad, but the new translations are to be used as explained in the docs.

Fix conflicting strings issue in translations

---

lib/core/nav/HeaderNav.js

Since at build we created `blog/index.html`, just to be consistent let's link it as `blog/` instead of `blog`
For GitHub Pages, the behavior is as below:
`blog/` -> try `blog/index.html`
`blog` -> try `blog.html`, if 404 then `blog/index.html`
Yes
Everything still works

fix: headerNav should link to 'blog/', not 'blog' for consistency

---

examples/basics/README.md

Fixes #925
First pass at a basic README.md for new websites.
I checked the PRs for documentation websites built with Docusaurus, and it seemed that most PRs were related to adding/editing content, and less about configuring layouts/siteConfig. That's why I added instructions for the popular use cases in the README.md, each with a link to the relevant part of the docs website for further reading. 
Yes
Check that running docusaurus-init copies the new README.md to the website folder
N/A

Added new README.md for new Docusaurus projects

---

lib/core/DocsLayout.js
lib/static/css/main.css
package-lock.json

Fixes #918 
Yes
1) Visit any doc page where lengthy text on the previous and next buttons caused the buttons to wrap and stack with no space in between (eg https://docusaurus.io/docs/en/navigation)
2) Check that it no longer stacks when the window is <735px. There should be ample space in between and the both buttons should float left.
It should look like this:

Fixed button wrapping behavior on mobile

---

docs/api-site-config.md
lib/core/Head.js

Github issue: #848 
Enable pass attributes to script tag and link tag.
Yes
I have tested this locally, it will apply the attributes to script and link.
nope

Enable pass attributes to script and link

---

docs/getting-started-docker.md
examples/basics/Dockerfile
examples/basics/docker-compose.yml
examples/basics/dockerignore
lib/copy-examples.js
lib/write-translations.js
website/sidebars.json

Github issue: #926 
Add docker support in basic example file and doc.
Yes
No break change, need someone to try the document. I have tested it locally.
nope

Add docker support

---

lib/core/DocsLayout.js
lib/static/css/main.css

Fix #911
Fix the Nav in the docs page to take the full width so that when scrolled it does not scroll the main container
Yes
1. Run the website
2. Put the devtools to be slightly above the nav (so that we can scroll on it)
3. Try to scroll slightly outside the nav text
4. It should scroll the nav instead of the main container
No

Fix nav to take full width in the docs page

---

lib/server/generate.js

Fix #940 
If a user uses something like `storybook` which generates a `static` folder as well, `docusaurus-build` can break.
While this is no longer an issue in v2 implementation, we should still fix this in the current version
Yes
Try the reproducible demo of #940 
Use this PR's change
cc @dakmoR

fix: nested static in static breaks build

---

lib/publish-gh-pages.js

Fix #764
Fix cross repo publishing
Yes
Visual
#764

Use older command to get remote origin

---

.circleci/config.yml
CONTRIBUTING.md
README.md
package.json
v1/package.json
v2/package.json

Per title.
Yes
CI results.
NA.

Update CI for v1

---

.circleci/config.yml

Add CI workflow for v2.
Yes
See CI section of PR.
#968

Update CI for v2

---

package.json
v2/lib/core/clientEntry.js
v2/lib/core/preload.js
v2/lib/core/serverEntry.js

- Fix linting precommit
- Use native react-loadable `preloadReady` on client
- Rename `prerender` to `preload` since that is what is it actually doing (to avoid bunch of loading screens on first page)
Yes
Before
After
For the website, still works normally

refactor(v2): better page `preloading`

---

README.md

The main header image in the readme has been broken for a while since the repo was reorganized into v1 and v2 folders.  I don't know if you're going to keep reorganizing things, in which case you might want to fix this issue differently, but this one-liner just uses the image from the v1 folder.  So feel free to take or leave this PR ! :)
Yes
N/A
N/A

docs: fix broken header image link in readme

---

v1/lib/static/css/main.css

Wanted to make this already awesome project a lil better! 🍺
Yes!
1. Open the application in chrome/firefox and reduce the browser width
2. Type anything in the search bar
3. Resize to smaller sizes and test 
GIFs:
*Tablet sizes*
Before:
After:
*Mobile sizes*
Before:
After:

style: UI improvements to searchbar

---

v2/lib/commands/start.js
v2/lib/load/index.js
v2/lib/load/pages.js
v2/lib/load/routes.js
v2/lib/load/theme.js
v2/lib/theme/Docs/index.js
v2/lib/theme/Layout/index.js
v2/lib/theme/Pages/index.js
v2/lib/webpack/server.js
v2/test/__fixtures__/simple-site/pages/hello/world.js
v2/test/__fixtures__/simple-site/pages/index.js
v2/test/__fixtures__/translated-site/pages/hello/world.js
v2/test/__fixtures__/translated-site/pages/index.js
v2/test/__fixtures__/transversioned-site/pages/hello/world.js
v2/test/__fixtures__/transversioned-site/pages/index.js
v2/test/__fixtures__/versioned-site/pages/hello/world.js
v2/test/__fixtures__/versioned-site/pages/index.js
v2/test/load/__fixtures__/simple-pages/bar/baz.js
v2/test/load/__fixtures__/simple-pages/foo.js
v2/test/load/__fixtures__/simple-pages/foo/index.js
v2/test/load/__fixtures__/simple-pages/index.js
v2/test/load/pages.test.js
v2/website/pages/index.js
v2/website/pages/tictactoe.js
v2/website/pages/youtube.js

Custom pages core functionality
- Support pages theming in `themes/Pages`
- Pages can work in translation/versioning/transversioning/simple context (like v1)
e.g: in translation site with 'en' and 'ko' language. File `pages/index.js` is now available at `/` `/en/` and `/ko/`
-Add strong test for pages
-Every custom pages receive props component, including metadata
Basically, this is porting core functionality of v1 to v2
Yes
Test locally and added tests pass
No problem in https://deploy-preview-994--munseo-preview.netlify.com/

feat(v2): custom pages

---

docs/getting-started-installation.md

I am setting up Docusaurus on a repo and noticed a minor copy edit. 
Yes
N/A
N/A

Fix typo in Getting Started docs

---

v2/.babelrc
v2/babel.config.js
v2/jest.transform.js
v2/lib/theme/Markdown/anchors.js
v2/lib/webpack/base.js
v2/package.json
v2/test/jest.config.js
v2/test/load/docs/index.test.js
v2/test/load/docs/metadata.test.js
v2/test/loadSetup.js
v2/test/webpack/utils.test.js
v2/yarn.lock

#984 
Yes
1. Go to v2 folder
2. Run yarn && yarn test
None

chore(v2): upgrade to Babel 7

---

v1/lib/core/Site.js

This PR adds a keyboard shortcut `/` for focusing the search input.
Was browsing the `draft-js` docs and found myself wishing this VIM keyboard shortcut existed since it is becoming more common across various websites. Not sure if where I've put this is the most appropriate place though.
Yep!
* Tested locally running `yarn start` from `v1/`
* Would love some suggestions on where/how to add unit tests
I don't believe this PR is related to any others.

feat: add keyboard shortcut to focus search

---

docs/api-site-config.md

set the `setConfig` fields to `h4` instead of `li`, will create some spacing and make the docs less clustered.
yes

docs: reorganize siteConfig entry (#436)

---

v1/lib/publish-gh-pages.js

fix: throw error when forgot to pass in GIT_USER

---

v1/lib/core/__tests__/utils.test.js
v1/lib/core/utils.js

Fix #1015 
Yes
1. run `git log --follow --summary [some file relative path]
2. see the result and capture the last date where commit is about content change not rename / move
3. Run the localhost for v1 (`cd v1 && yarn start`), check in the site
No

Fix last updated time misleading, only show when file content change or otherwise when it first created

---

v1/README.md

After moving v1 source into a v1 folder, the README is no longer showing on our npmjs package page - https://www.npmjs.com/package/docusaurus because the README remained in the root of the folder.
I copied the parts where I felt was relevant into the v1's README - basically stuff that's less engineering related and more about how to contact us, so that they can come to the main repo.
Suggestions welcome.
🤔 
NA

chore: add README to v1

---

v1/lib/core/DocsLayout.js
v1/lib/core/utils.js
v1/lib/static/css/main.css

1. Rename some variables
1. Extract inline styles into CSS
1. Add try/catch around shell commands
Yes
1. Test with valid updated time
1. Throw error within function and see that it's gracefully handled

fix: improve last updated time feature

---

docs/getting-started-publishing.md

Updated publishing docs to resolve #1029
I had trouble publishing my first Docusaurus built site to GitHub pages (as detailed in #1029) and this PR has the updates to the documentation that were needed in order for me to publish my site.
Yes
Only docs were changed. Run the site an ensure formatting is correct

docs: update siteConfig documentation for publishing with GitHub Pages

---

CHANGELOG.md

http://skiplang.org -> http://skiplang.com

Fix link to Skiplang in Changelog

---

docs/api-site-config.md
v1/examples/basics/siteConfig.js
v1/lib/core/DocsLayout.js
v1/lib/core/Head.js
v1/lib/core/__tests__/utils.test.js
v1/lib/core/utils.js
v1/lib/static/css/main.css
v1/website/siteConfig.js

Create Contributor List for each documents (#858)
Yes
Run yarn build on the website -- it will update the author list in the metadata
None

feat: add last contributor to each document

---

v2/lib/core/serverEntry.js
v2/lib/webpack/base.js
v2/lib/webpack/client.js

If we go to https://munseo-preview.netlify.com/, with 'JavaScript disabled' will break CSS due to SSR code splitting.
Even if javascript is enabled. You might see a flickering/flash due to css not rendered on server side before hand.
See https://github.com/jaredpalmer/after.js/issues/118 for super similar case
Yes
Accessing deploy preview on netlify with 'JavaScript disabled' does not break CSS

fix(v2): map loaded modules to bundles

---

v2/lib/load/docs/order.js
v2/lib/load/docs/sidebars.js
v2/lib/theme/Sidebar/SidebarCategory.js
v2/lib/theme/Sidebar/SidebarLink.js
v2/lib/theme/Sidebar/index.js
v2/lib/theme/Sidebar/styles.css
v2/test/load/docs/__snapshots__/sidebars.test.js.snap
v2/test/load/docs/order.test.js

This PR implements #827, #868 (v1 PR pending)
This PR will improve sidebar to support:
* new categories array syntax like in #1026 (but I've changed `ids` to `items`)
* links to docs from other sidebars
* links to other docusaurus non-docs pages
* links to external resources
* possibility to easily add new sidebar items types with any custom options
Yes
I have added some examples in `sidebar.json`. It looks like this:
```json
{
"docs": {
"Category 1": [
{
"type": "link",
"label": "Github",
"href": "http://github.com"
},
{
"type": "category",
"label": "Subcategory 1",
"items": [
"foo/bar",
"foo/baz"
]
},
{
"type": "category",
"label": "Subcategory 2",
"items": [
{
"type": "ref",
"id": "intro"
},
"hello",
{
"type": "link",
"label": "Google",
"href": "http://google.com"
}
]
}
],
"Category …
```

feat(v2): support external links & linking to docs from other sidebars

---

v1/lib/core/DocsLayout.js

Fixes #1078.
The problem was that the path to get the right title wasn't right : `['localized-strings', metadata.previous_id]` was always undefined.
Yep

fix: Previous / next page buttons label

---

v2/lib/webpack/base.js
v2/package.json
v2/yarn.lock

Currently, we use uglify via uglifyjs-webpack-plugin. 
Some history:
* `uglifyjs-webpack-plugin` < v1.0 used the minifier `uglify-js`
* however `uglify-js` does not support ES6, which resulted in a fork
called `uglify-es` that was developed in the `uglify-js` repository,
but under the `harmony` branch
* `uglifyjs-webpack-plugin` v1.x switched to `uglify-es` for ES6 support
* however `uglify-es` stopped being maintained:
mishoo/UglifyJS2#3156 (comment)
* which led to a fork called `terser` that has incorporated all of
the unmerged PRs and will be where all new development occurs:
https://github.com/fabiosantoscode/terser
* `terser-webpack-plugin` was created, which is the `terser` equivalent
of `uglifyjs-webpack-plugin`:
https://github.com/webpack-contrib/terser-webpack-plugin
* …

chore(v2): switch from uglifyjs-webpack-plugin to terser-webpack-plugin

---

v2/lib/core/clientEntry.js

`Loadable.preloadReady` wasn't able to handle nested react-router config. So after #1092, we can see flashing screen on first page load. Better to use own custom preload function like in serverEntry
See test plan for clearer *before* and *after*
Yes
**Before**
Notice the flashing screen whereby it is still in Loading state
**After**
Notice how natural is first page reload

feat(v2): better UX to avoid first page load flashing screen

---

docs/getting-started-preparation.md

Add description of how to set a custom `../docs` folder name to docs at [getting-started-preparation.md](https://github.com/facebook/Docusaurus/blob/master/docs/getting-started-preparation.md).
Yes
Checked relevant doc file on local branch to see that new text was included and formatted.
Resolves Issue #1082

docs: add info about setting custom ../docs folder name

---

v1/lib/server/liveReloadServer.js

Fixes LiveReload on second try (#1091), due to local variable defining livereload url losing its value during reload.
Fix #1091 
Yes!
`yarn start`, then edited `v1/website/pages/index.js` multiple times. Ensured that live reload now works.

Fix: Fix livereload on second try

---

v1/lib/core/renderMarkdown.js

Fixes #1076 
Yes
The stacktrace errors thrown by prismjs for unsupported languages (eg: `toml`) are now logged only as a warning message instead of logging the entire stack trace. This can be tested by doing the following changes:
1. Set `usePrism:true` in `siteConfig.js`.
2. Modify docs/api-doc-markdown.md to render a language not supported by prismjs.
Eg: (toml)
```toml
title = "TOML Example"
[dog]
name = "Lucky"
breed = "Labrador"
[cat]
name = "Fluffy"
breed = "Siamese"
```
3. 
```bash
cd website
yarn start
```
A warning message similar to the screenshot below would be logged in the console.

fix: warn unsupported languages by prismjs 

---

docs/api-doc-markdown.md

#1108 
Yes
N.A. -> Addition of markdown flavor support in docs. No functionality change.
Null

docs: specify markdown flavor support

---

v1/lib/core/DocsSidebar.js

Fix #1112 
This is caused due to `languages` will always be set as `en`
Yes
Create fake translated docs in `v1/website/translated_docs/api-commands.md`
The left TOC is now correctly shown
#892

fix: translated pages missing left TOC

---

docs/api-doc-markdown.md
v1/lib/core/DocsLayout.js

feat: use 'sidebar_label' instead of 'title' in prev/next buttons

---

v1/lib/version.js

Fix #1115 
Yes
```
{
"docs": {
"Welcome": [
"index"
],
"Ecosystem": [
"ecosystem/ecosystem-overview",
"ecosystem/ecosystem-cloud-native",
"ecosystem/ecosystem-versioning",
"ecosystem/ecosystem-upgrading",
"ecosystem/ecosystem-examples",
"ecosystem/ecosystem-sqa"
],
"ORY Hydra": [
"hydra/hydra-index",
{
"type": "subcategory",
"label": "Getting Started",
"ids": [
"hydra/hydra-5min-tutorial"
]
},
{
"type": "subcategory",
"label": "Guides",
"ids": [
"hydra/hydra-oauth2",
"hydra/hydra-jwks",
"hydra/hydra-configure-deploy",
"hydra/hydra-advanced",
"hydra/hydra-debugging",
"hydra/hydra-production",
"hydra/hydra-integration"
]
},
{
"type": "subcategory",
"label": "SDK",
"ids": [
"hydra/sdk/hydra-sdk-index",
"hydra/sdk/hydra-sdk-api",
"hydra/sdk/hydra-sdk-go",
"hydra/sdk/hydra-sdk-js"
]
},
{ …
```

fix: docusaurus-version should work with subcategory

---

v1/lib/server/versionFallback.js
v1/lib/version.js

Fix #1113 
Yes
Created two files `ecosystem/bar.md` with id: bar and `hydra/bar.md` with id: bar
First, cut version 1.0.0 and a versioned docs is created
After that, cut version 2.0.0 again
Note that I added some debugging console.log for easy purpose
**Before**
Note that the versioning command is confused with id `bar` since it is not namespaced according to subdirectory.
It incorrectly creates an extra version-2.0.0 file when there is no doc changes
**After**
Since there is no change, no new files created

fix: docusaurus-version should allow duplicate id in different subfolder

---

docs/api-site-config.md
v1/lib/server/docs.js

Show a warning message in the console that outputs a log when an internal link inside the documentation is broken. 
Fix #1111 
Yes.
It can happen to have brokens links in the documentation that are caused by a change in the file id/path (e.g. a file is renamed, moved or simply there's a typo in the link) and then forgetting to update the link that points to it.
It's very hard discovering where they are in the docs and fix it.
It would be nice to introduce a check (maybe flaggable in the options) when running ```docusaurus start``` or ```docusaurus build``` that shows a warning message if a link in the markdown has an unresolved path.

feat: show a warning message when md links are broken

---

v1/lib/server/__tests__/blog.test.js
v1/lib/server/__tests__/docs.test.js
v1/lib/server/blog.js
v1/lib/server/docs.js
v1/lib/server/utils.js

Fix broken build
Fixes https://github.com/facebook/Docusaurus/issues/1149
Yes, I helped write them.
Local Testing
https://github.com/facebook/Docusaurus/pull/1143

fix: do not hardcode siteConfig path

---

v1/lib/static/css/main.css

I wanted to resolve #1152. The problem was caused by "momentum" style scrolling on some mobile devices. Fixed by addition of `translate3d(0,0,0)` in order to enable GPU during the scrolling animation.
Yes.
Tested on iPhone 7 and iPhone XS.
The first tab is before(with the white gap), the second one is after the changes(no gap at all).

Fix gap on mobile devices when scrolling

---

v1/lib/publish-gh-pages.js

The --skip-image-compression flag is passed thru to the build command

fix: pass docusaurus-publish cli args to build command

---

v1/lib/core/GridBlock.js

Fix #1184. The default value for the `alignImage` key was not applied. 
Yes.
The screenshots below show the content of a GridBlock content component with the `alignImage` key omitted before/after the fix.
Before (image missing):
After (image in left position):

fix: missing default value for grid block content objects

---

docs/getting-started-publishing.md

Fix #1189. Fix inconsistency between documentation and sample site config.
Yes.

docs: add missing trailing slash to sample site config base url

---

v1/lib/static/css/main.css

Before:
After:
Yes
See motivation
N/A

fix: add margin-bottom: 0 to blog post author

---

v1/lib/core/Site.js
v1/lib/static/css/main.css

Fix #1187. Padding for certain components assumed that there will always be two rows in the nav bar in mobile view. Here we handle the case where the nav bar only has a single row on mobile devices.
I'm not 100% certain if `Site.js` is the best place to check whether the mobile nav bar occupies a single row, or if I'm applying the `singleRowMobileNav` class at the most suitable place. Please do let me know if there is a better way to achieve this!
Yes.
We test for the cases where there are two rows in the mobile nav bar (at least 1 doc/blog/page/href/language link) and when there is one row in the mobile nav bar (no doc/blog/page/href/language link).

fix: wrong padding for single row mobile nav

---

v1/lib/static/css/main.css

When the sidebar is collapsible, a horizontal scrollbar can be seen, e.g.:
https://docusaurus.io/docs/en/installation - https://i.imgur.com/IkrkLrp.png
This is caused by the arrow being rendered outside of the sidebar box.
Fix an overflow bug in sidebar.
Yes.
The issue is visible in the official documentation. Fix should be visible in the PR preview.

Fix horizontal overflow in sidebar

---

v1/lib/server/docs.js
v1/lib/server/generate.js

Fix #1177 and #1203. Generated asset links were not following the `docsUrl` attribute specified in `siteConfig.js`. Docs assets were also placed into the `docs` folder in the build directory instead of following the specified `docsUrl`. This PR should fix these issues. 
Yes.
Set `docsUrl` in `siteConfig.js` to `hello` and start local server. Asset links in docs should point to `/hello/assets/ASSET_NAME`. Docs assets should be served from `/hello/assets/ASSET_NAME`. Images should be displayed on the test site.
Set `docsUrl` in `siteConfig.js` to `hello` and build the site. Asset links in docs should point to `/hello/assets/ASSET_NAME`. Docs assets should be served from `/hello/assets/ASSET_NAME`. Images should be displayed on the test site. (See …

fix: docs asset links should follow specified docsUrl

---

v1/lib/core/nav/SideNav.js
v1/lib/static/css/main.css

Unicode rendering is font-dependent which is then system dependent. Changing it to an SVG to make it more consistent across devices.
Fixes #1207.
Yes
NA

fix: change sidebar chevron icon to use svg

---

CONTRIBUTING.md
v1/examples/basics/core/Footer.js
v1/website/blog/2018-04-30-How-I-Converted-Profilo-To-Docusaurus.md
v1/website/core/Footer.js
v1/website/pages/en/users.js

This site mostly doesn't exist anymore, so we should just link to the new
locations. The exception is that the CLA is still there.

Update code.facebook.com links to appropriate new destination

---

docs/getting-started-publishing.md

Fixes #1226 
Yes
See Netlify preview

docs: mention about CNAME option in publishing docs

---

package.json
yarn.lock

Upgrade husky 0.14.3 to 1.3.1
I upgraded husky & its hook. Because, husky 1.x need to upgrade existing hooks. 
Please see [official upgrading document](https://github.com/typicode/husky#upgrading-from-014).
Yes.
I confirmed run husky when pre-commit like below.
```sh
husky > pre-commit (node v10.13.0)
25lRunning tasks for v1/**/*.js [started]
Running tasks for v2/**/*.js [started]
Running tasks for v1/**/*.js [skipped]
→ No staged files match v1/**/*.js
Running tasks for v2/**/*.js [skipped]
→ No staged files match v2/**/*.js
```
Nothing.

chore: upgrade husky to 1.3.1

---

v1/lib/core/Site.js

Fix #1233.
Yes.
Set `cleanUrl` to `true` in `siteConfig.js`. Check the `og:url` meta tag. The value should be the clean url.

Use clean url for og:url when cleanUrl is true

---

v1/lib/static/css/main.css

fix: css break when hover algolia logo

---

v1/lib/core/Doc.js

- The reason for this bug that the previous Codeblock implementation separates
the tabs, the markdown before tabs, and the markdown after tabs into
separate Remarkable component, thus they don't share information
regarding the reference link
- To solve this, change the Doc implementation so that one Doc
have only one Remarkable component by transforming the codeblock
into html string and add it as part of the markdown, letting the
Remarkable take care of the html string
- However, this approach made us need to ensure that there is no
newline in the codetab, otherwise, the formatting inside the
code will be broken. Thus, I replace every newline inside the
code tag with a br tag
Fix #1215 
Yes
Create a referenced link with the reference located separately (one above the Codeblock tab, one …

fix: make referenced links work with code block tabs

---

v1/lib/write-translations.js

Fix #1259 
Yes
Use this reproducible demo https://github.com/amimas/docusaurus-1259
Use this PR patch
Go to  `/docs/`.
Note that the v1.0.0 docs file is like this:
```md
---
id: version-1.0.0-index
title: This is main page
sidebar_label: Main page
original_id: index
---
Mauris vestibulum ullamcorper nibh, ut semper purus pulvinar ut. Donec volutpat orci sit amet mauris malesuada, non pulvinar augue aliquam. Vestibulum ultricies at urna ut suscipit. Morbi iaculis, erat at imperdiet semper, ipsum nulla sodales erat, eget tincidunt justo dui quis justo. Pellentesque dictum bibendum diam at aliquet. Sed pulvinar, dolor quis finibus ornare, eros odio facilisis erat, eu rhoncus nunc dui sed ex. Nunc gravida dui massa, sed ornare arcu tincidunt sit amet. Maecenas efficitur sapien neque, a …
```

fix: wrong sidebar_label and title on versioned_docs

---

v2/lib/core/sitemap.js
v2/lib/load/index.js
v2/lib/load/routes.js
v2/lib/webpack/server.js
v2/test/load/routes.test.js

We can determine all available routes/urls when building the react-router config. So let's do that
Yes
Locally debug the routesPaths value and add small test

refactor(v2): determine all available routes/url

---

docs/api-pages.md

docs: describe where users can find default styles in api-pages.md documentation file
Yes.

docs: update api-pages.md to document about overriding default styles

---

v1/package.json
v1/website/core/Showcase.js
v1/yarn.lock
v2/package.json
v2/yarn.lock

Received an internal task T40933962 from FB OSS tools team:
```
GitHub has detected that a package defined in a dependency file (package.json / Gemfile / etc) of the facebook/Docusaurus repository contains a security vulnerability.
Package name: merge
Affected versions: < 1.2.1
Fixed in version: 1.2.1
CVE: CVE-2018-16469
Reference: https://nvd.nist.gov/vuln/detail/CVE-2018-16469
```
Yes
CI.
NA

fix: upgrade jest to remove security vulnerability

---

v2-website/docusaurus.config.js
v2/.eslintrc.js
v2/lib/commands/start.js
v2/lib/core/App.js
v2/lib/load/index.js
v2/plugins/docusaurus-plugin-content-blog.js

Reduce hardcoding of certain paths and add a method to plugins to allow them to specify which paths it wants the Docusaurus runtime to watch for changes so that we can rebuild those parts if there are updates.
Yes.
- Include the paths to watch -> Update blog post -> Page refreshes
- Do not include the paths to watch -> Update blog post -> Page doesn't refresh
NA.

feat(v2): allow plugins to specify paths to watch

---

v1/lib/server/docs.js
v1/lib/version.js

Fix #1271 
Yes
Follow this repo https://github.com/parthpp/Docusaurus-Broken-Links
Before:
After:
Also strictly enforce docusaurus-version to use X.Y.Z format like Semver, does not allow `/`

fix: relative path markdown linking on versioned docs

---

v1/lib/core/CodeTabsMarkdownBlock.js

- Closes #1255 
I thought the issue was a blocker for my project so I fixed it instead of waiting for the assignee,  but it seems to be just a warning - sorry @oneuptim! Feel free to review/modify - I might have missed something!

fix(codetabs): fix key warning

---

v1/website/pages/en/index.js
v1/website/static/css/custom.css

More widely announce v2 and its roadmap.
Yes
NA

docs: add v2 roadmap to landing page

---

v2/lib/load/config.js
v2/lib/load/index.js
v2/plugins/README.md

- **Wrote some documentation 😄** 
https://github.com/endiliey/Docusaurus/blob/plugin/v2/plugins/README.md
- Add extra plugin API to install from local path
Example
```js
plugins: [
{
path: `/path/to/docusaurus-local-plugin`,
},
],
}
```
- Also resolve plugins from official docusaurus plugin directory and/or npm dependency
Yes
```md
plugins: [
{
name: 'docusaurus-plugin-content-blog',
options: {
include: ['*.md', '*.mdx'],
path: '../v1/website/blog',
},
},
{
name: 'docusaurus-plugin-content-pages',
},
],
};
```
No error
```js
plugins: [
{
path: require.resolve('../v2/plugins/docusaurus-plugin-content-pages')
},
],
}
```
No error
```js
plugins: [
{
name: 'docusaurus-nothing',
},
],
}
```
Error case:

feat(v2): local plugin path resolve

---

packages/docusaurus-plugin-content-blog/index.js
packages/docusaurus-plugin-content-pages/__tests__/index.test.js
packages/docusaurus-plugin-content-pages/index.js
packages/docusaurus/lib/commands/build.js
packages/docusaurus/lib/commands/start.js
packages/docusaurus/lib/load/index.js
packages/docusaurus/lib/load/plugins.js
packages/docusaurus/lib/theme/BlogPage/index.js
packages/docusaurus/lib/theme/Footer/index.js
packages/docusaurus/plugins/README.md

Changes
- Do not inject global metadata to context yet. Example: blogMetadata
- Refactor plugins loading process to `load/plugins`
- Simplify/ change the plugin lifecycles a bit.
- Add configureWebpack plugin lifecycle
See below:
```js
// A JavaScript class
class DocusaurusPlugin {
constructor(options, context) {
// Initialization hook
// options are the plugin options set on config file
this.options = {...options};
// context are provided from docusaurus. Example: siteConfig can be accessed from context
this.context = context;
}
getName() {
// plugin name identifier
}
async loadContent()) {
// The loadContent hook is executed after siteConfig and env has been loaded
// You can return a JavaScript object 'content' that will be passed to contentLoaded hook
}
async contentLoaded({content, …
```

refactor(v2): plugins lifecycle

---

.eslintignore
.eslintrc.js
package.json
packages/docusaurus-1.x/.eslintignore
packages/docusaurus/lib/load/docs/metadata.js
yarn.lock

Internally the Open Source Eng teams has built tools to check for certain violations in FB OSS projects. Missing copyright headers in files is an example of a violation.
This ESLint rule I'm adding should help reduce cases of this happening again. We will need to find add a similar rule for CSS (probably using Stylelint) if we and when have more CSS in future.
Also removed the `.eslintignore` within `packages/docusaurus-1.x` as [ESLint only uses one `.eslintignore`](https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories) and it'll be the root one.
Yes
Netlify.

misc: add ESLint rule to check for Facebook copyright headers in JS files

---

packages/docusaurus/lib/commands/start.js

Fix error caused by `plugins.map(plugin => plugin.getPathsToWatch())`
What if plugin does not have a path to watch ??
Locally

fix(v2): enable plugin not having pathsToWatch

---

packages/docusaurus/lib/webpack/base.js
packages/docusaurus/lib/webpack/server.js
website/docusaurus.config.js

We're only running webpack server compilation in production to generate static html files (with static-site-generator-plugin). So the bundle is in fact no need to be minimized.
https://webpack.js.org/configuration/optimization/#optimizationminimize
This makes the production build even faster because we skip uglifying part (which usually takes long) on server-bundle.js
No impact on user other than faster build.
Yes
Before
Usually server and client should have the same compilation time
After
~60% faster time on server build

feat(v2): faster production server build

---

.circleci/config.yml
docs/getting-started-installation.md

- Smarter CI to skip deploying v1 static website if there is no related changes.
Example scenario:
If we're modifying README.md, it doesn't make much sense to burden the CI to actually run the whole publish-gh-pages script
- We already have netlify build for v1 and v2, why do we need to build static website build of v1 and v2 on our CI
Yes
Proof of concept with various test commits to check if bash logic is working

chore: optimize continuous integration

---

packages/docusaurus-plugin-content-blog/components/BlogPage/index.js
packages/docusaurus-plugin-content-blog/components/BlogPost/index.js
packages/docusaurus-plugin-content-blog/components/BlogPost/styles.module.css
packages/docusaurus-plugin-content-blog/components/Post/index.js
packages/docusaurus-plugin-content-blog/components/Post/styles.module.css
packages/docusaurus-plugin-content-blog/index.js
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-utils/index.js
packages/docusaurus/lib/load/index.js
packages/docusaurus/lib/load/theme.js
yarn.lock

Improve @docusaurus/plugin-content-blog plugin to be more like v1. There are some room for improvements (sidebar, CSS, etc). Maybe future PR will improve that.
Others:
- Components should be part of plugin package. Not in docusaurus own package
- Fix some minor bugs
Yes
- `/blog` now display truncated content only with readmore button
Before
After
- BlogPost
- https://deploy-preview-1311--docusaurus-2.netlify.com/blog

feat(v2): improve @docusaurus/plugin-content-blog

---

docs/api-commands.md
packages/docusaurus-1.x/lib/__tests__/build-files.test.js
packages/docusaurus-1.x/lib/server/__tests__/start.test.js
packages/docusaurus-1.x/lib/server/readMetadata.js
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/lib/commands/build.js
packages/docusaurus/lib/load/docs/index.js
packages/docusaurus/lib/load/index.js
packages/docusaurus/test/load/docs/index.test.js

This patch resolves #1243. Docusaurus CLI command for building `HTML` files from `MarkDown` is `docusaurus-build`.  After deploying the static website as a result of this build, the documentation for the next release can be accessed by visiting `**/next*`. This is ideal for open source projects because it enables transperancy and encourages contribution. However, a closed source project will appreciate an option to skip building and deploying the next version documents. The proposed feature adds an option to `docusaurus-build` command to skip the build for documents of the next release. Thus, when `docusaurus-build --skip-next-release` is executed, the resulting `HTML` files are only for the already released version.
Yes
I have added test case for the build option. In addition to that, I …

Add --skip-next-release option to yarn build

---

package.json
packages/docusaurus-utils/index.js
packages/docusaurus-utils/package.json
packages/docusaurus-utils/test/index.test.js
packages/docusaurus/lib/load/routes.js
packages/docusaurus/lib/webpack/base.js
yarn.lock

- Optimize webpack chunks splitting by adding vendors (for node_modules) and common (for code that is reused) cacheGroups
- Add webpackChunkNaming so that generated modules file names is easier to read. It's not a good idea to see "1.js", "2.js", "3.js". It will be better to see "component--theme-BlogPost.js", "module-blog-introducing-docusaurus.js" and/or "docs--installation.js"
I recommend checking the netlify and use your Network Tab to better understand the situation
Yes

feat(v2): webpack chunk naming & splitting

---

packages/docusaurus/lib/webpack/base.js
packages/docusaurus/package.json

I use [Windows Subsystem for Linux](https://msdn.microsoft.com/commandline/wsl/about).
Running `docusaurus build` for v2 always hang due to Terser-webpack-plugin bug of not being able to run in parallel (see https://github.com/webpack-contrib/terser-webpack-plugin/issues/21 - only on WSL)
Usually, I always manually set `parallel: false` to run `docusaurus build` in v2.
This PR attempt to disable parallel uglifying through terser (only disable in WSL) until that issue is fixed upstream
Yes
```bash
cd website
yarn build
```
Works on WSL. No longer hangs

fix(v2): don't run terser in parallel for WSL

---

packages/docusaurus/lib/core/serverEntry.js

There is some regression due to some webpack optimization that I did on #1323 . Some common chunks is not included in the statically rendered html. 
Example: 
Yes
Disable javascript, head over to /feedback/
#1323

fix(v2): missing scripts/css on statically rendered  html

---

packages/docusaurus-plugin-content-docs/__tests__/index.test.js
packages/docusaurus-plugin-content-docs/__tests__/sidebars.test.js
packages/docusaurus-plugin-content-docs/index.js
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-docs/src/sidebars.js
packages/docusaurus/CHANGES.md
packages/docusaurus/lib/commands/start.js
packages/docusaurus/test/__fixtures__/custom-site/docusaurus.config.js
packages/docusaurus/test/__fixtures__/simple-site/docusaurus.config.js
packages/docusaurus/test/__fixtures__/translated-site/docusaurus.config.js
packages/docusaurus/test/__fixtures__/transversioned-site/docusaurus.config.js
packages/docusaurus/test/__fixtures__/versioned-site/docusaurus.config.js
packages/docusaurus/test/load/config.test.js
website/docusaurus.config.js
yarn.lock

Reduce hidden magic by requiring a sidebars file to be passed into the docs plugin.
Yes.
Updated Jest tests.
#1327

refactor(v2): load sidebars from docs plugin

---

packages/docusaurus/lib/core/clientEntry.js
packages/docusaurus/lib/core/preload.js

ReactDOM.render is slower than ReactDOM.hydrate. Since we already server render in production, we can just try to hydrate the existing container without rerendering it completely client-side.
References:
https://reactjs.org/docs/react-dom-server.html#rendertostring
> If you call ReactDOM.hydrate() on a node that already has this server-rendered markup, React will preserve it and only attach event handlers, allowing you to have a very performant first-load experience.
https://reactjs.org/docs/react-dom.html#render
> Using ReactDOM.render() to hydrate a server-rendered container is deprecated and will be removed in React 17. Use hydrate() instead.
Yes
1. Locally development still works
2. Locally production build also works. No HTML mismatch

refactor(v2): hydrate on server existing markup instead of full rerender

---

packages/docusaurus-plugin-content-docs/src/__tests__/index.test.js
packages/docusaurus-plugin-content-docs/src/index.js
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/lib/commands/build.js
packages/docusaurus/lib/commands/start.js
packages/docusaurus/lib/load/index.js
packages/docusaurus/package.json
yarn.lock

I think it's a good cliOptions for user to enable them analyze their bundle size especially in production.
https://github.com/webpack-contrib/webpack-bundle-analyzer - Over 1.4 million downloads on NPM /week
I personally like it to make my debugging/ web performance optimizing life easier
Other Changes:
1. Move skipNextRelease to be part of the docs plugin, instead of docusaurus-core cli
2. Remove ensureDirSync seen generate command already have an inbuilt async `fs.ensureDir`
Yes
```
cd website
yarn build --bundle-analyzer
```

feat(v2): enable user to analyze production bundle size

---

.gitignore
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/lib/commands/start.js
packages/docusaurus/lib/load/index.js
packages/docusaurus/lib/webpack/base.js
packages/docusaurus/package.json
yarn.lock

Add https://github.com/webpack-contrib/cache-loader/ by default especially on expensive loader like babel-loader.
Also add `--no-cache-loader` cli option if user don't want it.
How it works:
**Caches the result of following loaders on disk**
See test plan for benefits
yes
With cache-loader. Subsequent build is faster due to reuse of cache
Without cache loader, roughly similar performance
With cache-loader
Without cache-loader
Lot of possibility for improvement in the future. Just adding it for now

feat(v2): add cache-loader by default especially on babel-loader

---

packages/docusaurus-plugin-content-blog/index.js
packages/docusaurus-plugin-content-docs/src/index.js
packages/docusaurus-plugin-content-pages/src/index.js
packages/docusaurus/lib/commands/start.js

We should use glob pattern for the paths to watch in plugins. It's also more performant to watch the correct extension files, see https://github.com/facebook/Docusaurus/pull/1327#discussion_r270658141
Yes
**Before**
It doesn't trigger load() due to wrong glob pattern
**After**
It triggers load() after this PR.

fix(v2): plugins not watching the correct files

---

packages/docusaurus-plugin-content-docs/src/index.js
packages/docusaurus/lib/commands/build.js
packages/docusaurus/lib/commands/start.js
packages/docusaurus/lib/webpack/base.js
packages/docusaurus/lib/webpack/client.js
packages/docusaurus/lib/webpack/server.js
packages/docusaurus/lib/webpack/utils.js
packages/docusaurus/package.json
packages/docusaurus/test/webpack/base.test.js
packages/docusaurus/test/webpack/client.test.js
packages/docusaurus/test/webpack/server.test.js
packages/docusaurus/test/webpack/utils.test.js
yarn.lock

- Remove webpack-chain API because it can be confusing to have 2 API to configure webpack.
- Simplify all webpack config generation with the 'usual' and 'popular' way
- Refactoring stuff, so things like reusing loader is possible.
Yes
Locally development still works OK + hot reload
Production also OK, no build error.
Webpack config expert please help ! 😄

refactor(v2): simplify webpack stuff

---

packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-blog/src/index.js
packages/docusaurus-plugin-content-blog/src/markdownLoader.js
packages/docusaurus-plugin-content-docs/src/index.js
packages/docusaurus/lib/load/routes.js
packages/docusaurus/lib/theme/BlogPage/index.js
packages/docusaurus/lib/webpack/base.js
packages/docusaurus/lib/webpack/utils.js
packages/docusaurus/package.json

Something to ponder: How do we apply different loaders for files with same extension?
Scenario
- I want to load 'blog-xxxx.md' but only want the content summary
- I want to load 'blog-xxxx.md', all of the content
The goal is to conditionally transform resources as needed just by appending a query parameter to the import statement. 
Example:
`import('blog/2018-09-11-Towards-Docusaurus-2.md?truncated=true')`
Previously, our addRoute API looks like this
```js
addRoute({
// .....
component: 'the/path/component/' // Only accepts string
})
```
Now we allow
```js
addRoute({
// .....
component: {
path: // the import path
query: {
// the query
}
}
})
```
Changes:
- Blog plugin now no longer generates truncated version of blog (reduce bundle size). 
- Some code refactoring for readability (in …

feat(v2): upgrade addRoutes API to introduce query

---

packages/docusaurus-1.x/lib/static/css/main.css
website-1.x/blog/2018-09-11-Towards-Docusaurus-2.md

Fixes #1220 
I've created a custom scrollbar that appears in the table of contents if there are too many items.
Yes.
Tested across multiple browsers. 
There's a little problem. My solution is not working in Firefox or IE/Edge because these browsers do not support custom scrollbars. I could try to implement custom scrollbars using JS but I'm not sure if this is a good idea or not.

fix: make scrollbar visible in inner page navigation

---

packages/docusaurus-utils/src/__tests__/index.test.js
packages/docusaurus-utils/src/index.js
packages/docusaurus/lib/server/load/plugins.js
packages/docusaurus/lib/server/load/routes.js

Fix #1350
The problem
`import XXXXX from '@generated\this-is\my\path' is incorrect`
`import XXXXX from '@generated/this-is/my/path' is correct`
We need to escape `backslashes` for windows path.
Yes
Before
After
Windows
Linux

fix(v2): windows compatibility

---

packages/docusaurus/lib/client/exports/Head.js
packages/docusaurus/lib/client/serverEntry.js
packages/docusaurus/lib/default-theme/Doc/index.js
packages/docusaurus/lib/default-theme/DocBody/index.js
packages/docusaurus/package.json
yarn.lock

Problem
Wrong title in static html if javascript disabled
Others:
- Upgrade react-helmet to v6 beta. We need this because of potential critical bug https://github.com/nfl/react-helmet/issues/373 issue surfacing
Yes
Correct meta tag on static html (even with JavaScript disabled)

fix(v2): wrong head meta and title

---

packages/docusaurus/lib/webpack/base.js
website/package.json

Fix stuff that prevents v2 being installed as a package
Yes
Before
After
Can use it as 3rd party package

fix(v2): fix js-loader not transpiling own library

---

docs/api-site-config.md
website-1.x/versioned_docs/version-1.5.x/api-site-config.md
website-1.x/versioned_docs/version-1.6.x/api-site-config.md
website-1.x/versioned_docs/version-1.7.3/api-site-config.md

The parameter type was wrong, as explained in [this issue](https://github.com/facebook/Docusaurus/issues/1357). yangshun accepted the solution and asked me to create the pull request. 😊
Yes
No test plan required for a docs change (I think)
n/a

docs: change parameter type for separateCss from string to array

---

packages/docusaurus-utils/package.json
packages/docusaurus-utils/src/__tests__/index.test.js
packages/docusaurus-utils/src/index.js
packages/docusaurus/lib/client/serverEntry.js
packages/docusaurus/lib/commands/start.js
packages/docusaurus/lib/server/load/index.js
packages/docusaurus/lib/server/load/plugins.js
packages/docusaurus/lib/server/load/routes.js
packages/docusaurus/lib/webpack/client.js
packages/docusaurus/test/load/routes.test.js
yarn.lock

See http://www.evernote.com/l/AqrzyoEn5d5BZ6z4HbV0YVcaulCnOF0blOk/ for initial idea
Initially I wanted to code-split it such that we have component.js as well for each route
Example:
For /blog/2017/12/14/introducing-docusaurus, we will create 3 new files
- .docusaurus/blog-2017-12-14-introducing-docusaurus-8d2/component.js
- .docusaurus/blog-2017-12-14-introducing-docusaurus-8d2/metadata.json
- .docusaurus/blog-2017-12-14-introducing-docusaurus-8d2/modules.json
But after implementing it, I found that it makes us having to generate a lot of files and the bundle size actually become bigger due to module concatenation, files overhead, etc. Turns out that having one big single routes.js file is better than having small routes.js file + a lot of component.js file
So instead of that,
What I did …

feat(v2): code-split metadata out of routes

---

packages/docusaurus/lib/commands/build.js
packages/docusaurus/package.json

https://webpack.js.org/api/node/#custom-file-systems
Don't output server.bundle.js to disk. Use memory temporarily instead when running.
Yes
No more server.bundle.js in my build folder

feat(v2): don't output server.bundle.js to disk

---

packages/docusaurus-plugin-sitemap/src/index.js
packages/docusaurus/lib/client/serverEntry.js
packages/docusaurus/lib/commands/build.js
packages/docusaurus/lib/webpack/client.js
packages/docusaurus/lib/webpack/plugins/WaitPlugin.js
packages/docusaurus/lib/webpack/server.js
packages/docusaurus/package.json
yarn.lock

Try to run in one instance
Edit: The idea here is to wait at **`make`** webpack compilation hook (https://webpack.js.org/api/compiler-hooks/#make) which is done before finishing the compilation.
This is roughly before static-site-generator-webpack-plugin begins to execute its function. 
Note that we cannot do `import manifest from XXXXX` because at that time, the manifest still doesn't exist until client bundle finish serving.
We can however, do fs.existSync first at webpack level using our newly created `WaitPlugin` and then fs.readFileSync(manifest) later on.
Either way, it feels nicer to see the client and server bundle being run together
Others:
- Fix sitemap plugin to remove annoying callback deprecation warning
Yes
**Before**
**After**
The performance gain is not so much actually …

feat(v2): webpack multicompile client & server

---

.eslintrc.js
packages/docusaurus-plugin-content-blog/src/index.js
packages/docusaurus-plugin-content-docs/src/index.js
packages/docusaurus-plugin-content-pages/src/index.js
packages/docusaurus-utils/src/__tests__/index.test.js
packages/docusaurus-utils/src/index.js
packages/docusaurus/lib/client/exports/ComponentCreator.js
packages/docusaurus/lib/client/exports/ContentRenderer.js
packages/docusaurus/lib/default-theme/BlogPage/index.js
packages/docusaurus/lib/default-theme/BlogPost/index.js
packages/docusaurus/lib/default-theme/DocBody/index.js
packages/docusaurus/lib/default-theme/Pages/index.js
packages/docusaurus/lib/server/load/index.js
packages/docusaurus/lib/server/load/plugins.js
packages/docusaurus/lib/server/load/routes.js

Add a `ContentRenderer` component that will help a component fetch the modules it needs based on the path provided.
- Generate two files: `registry.js` and `routesAsyncModules.json`.
- `registry.js` is simply a mapping of chunk names to their import statements.
- `routesAsyncModules.json` is a mapping of routes to the chunks it needs, with the added benefit of having a shape 
- How `ContentRenderer` works:
- In each component, (e.g. `BlogPost` or `BlogPage`), pass `ContentRenderer` the current path.
- Look up `routesAsyncModules` with that path to get the chunks that are needed
- Use React Loadable to load the chunks in parallel and pass them back to the component.
- Cleaner and smaller routes file. The route files no longer have the import statements for modules. TODO: Make metadata use …

feat(v2): implement ContentRenderer

---

packages/docusaurus/lib/client/exports/ComponentCreator.js

Sometimes hot reload not working because we alter the modules object. 
Try to deep clone the object with json clone trick. Lodash cloneDeep would do the job but lodash cloneDeep can make our bundle size bigger :| and according to https://github.com/lodash/lodash/issues/1984#issue-133070711 it is also slower than simple JSON clone trick.
Yes
```bash
yarn start --hot-only
```
Hot reload working
#1366 #1367

fix(v2): fix hot reload sometimes not working due to altered modules

---

packages/docusaurus/lib/client/docusaurus.js
packages/docusaurus/lib/client/exports/Link.js

- If intersection observer is supported:
Once the current page has loaded, looks for all links on **the viewport**, and for each starts prefetching the page that the link points to.
- If IO is not supported.
Once the current page has loaded, looks for all links on **the page**, and for each starts prefetching the page that the link points to.
Make our site blazingly fast like gatsby
https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ
Yes

feat(v2): prefetch links on viewport with intersection observer

---

packages/docusaurus/lib/client/App.js
packages/docusaurus/lib/default-theme/Layout/index.js

Temporary solution to persist infima css. Put the link on root App
Yes
No more FOUC in local and css not keep getting fetched
Before
After

chore(v2): temporary hack to persist infima CSS

---

packages/docusaurus/lib/client/clientEntry.js
packages/docusaurus/lib/client/docusaurus.js
packages/docusaurus/lib/client/exports/Link.js
packages/docusaurus/lib/client/flat.js
packages/docusaurus/test/client/flat.test.js
website/pages/index.js

- Separate flat function in `client/docusaurus.js` to `client/flat.js` and add test for it.
The logic was previously wrong for array. But it is now fixed (thank you unit test !)
- Rename `window.__docusaurus` to `window.docusaurus` because TIL element id `__docusaurus` is also included as `window.__docusaurus`
Thank you @radekmie for pointing this out. Hope you'll help us in the future again (as contributor ? 😉 )
https://github.com/facebook/Docusaurus/pull/1373#discussion_r277135550
Yes
Prefetching still work

fix(v2): flat function & window.docusaurus rename

---

packages/docusaurus/lib/client/docusaurus.js

While developing I've noticed a lot of errors (counted in hundreds) coming from the `flat` function. It turned out that the prefetching was trying to load some non-existing pages (some docs page in my case). It's _rather_ not possible to encounter it in a finished and working page, but having fewer errors during development is always better.
Yes.
Add a non-prefetchable link on your site (e.g. non-existing yet docs site). With this change, it should not throw an error while prefetching it.

fix(v2): prefetch only existing chunks

---

packages/docusaurus-mdx-loader/src/index.js
packages/docusaurus-mdx-loader/src/linkHeadings.js
packages/docusaurus/lib/default-theme/DocBody/index.js
packages/docusaurus/lib/default-theme/DocBody/styles.css

An option to quickly copy a section link is essential!
Yes.
Check if headings have `#` anchors with correct `id` set. Check if clicking right side TOC redirects correctly. Check if navbar is not covering the section after redirection from TOC.

feat(v2): headings anchors

---

packages/docusaurus/lib/webpack/plugins/WaitPlugin.js
packages/docusaurus/lib/webpack/server.js
packages/docusaurus/package.json
yarn.lock

Optimize implementation of `WaitPlugin`. It is better to use fs event system to wait for a file rather than using hacky polling timeout implementation with a timeout. Also, no need to wait for `chunk-map.json` because it is 100% guaranteed that `client-manifest.json` will be generated after `chunk-map.json` in client. So if manifest exist, chunk map will exist.
**This is an attempt to fix error due to timeout like below** 
```bash
> docs@ build ROOT/uniforms-2/website
> docusaurus build
Creating an optimized production build...
Compiling
● Client █████████████████████████ chunk asset optimization (92%) TerserPlugin 
● Server █████████████████████████ building (70%) 107/107 modules 0 active
ROOT/uniforms-2/website/node_modules/@docusaurus/core/lib/webpack/plugins/WaitPlugin.js:34
throw …
```

fix(v2): use fswatch instead of timeout polling to wait for client manifest

---

packages/docusaurus/lib/default-theme/DocBody/styles.css
packages/docusaurus/lib/webpack/plugins/WaitPlugin.js
packages/docusaurus/lib/webpack/server.js
packages/docusaurus/package.json
yarn.lock

Currently, the hash-link is so hard to click.
See this gif or try it out at https://docusaurus-2.netlify.com/docs/installation/#launching-the-server-behind-a-proxy
Before I can click the hash, it already disappears
Yes
Before
After
#1385

fix(v2): fix hash-link css

---

packages/docusaurus/bin/docusaurus.js

Closes #1398 
Shows up a suitable message if the user fires in unknown commands:-
> docusaurus run
```bash
Usage: docusaurus <command> [options]
Options:
-V, --version              output the version number
-h, --help                 output usage information
Commands:
build [options] [siteDir]  Build website
eject [siteDir]            copy the default theme into website folder for customization.
init [projectDir]          Initialize website
deploy [siteDir]           deploy website
start [options] [siteDir]  Start development server
Unknown command run.
```

Warn the user if unknown arguments are provided

---

packages/docusaurus-utils/src/index.js

Minor refactoring. Instead of comparing old file string and new file string when deciding whether to `writeFile`, we can save the hash of old file and compare it to the hash of new file. While `md5` is not a 100% perfect hash, its still almost impossible to get a collision and this is more of to optimize our fs operation. 
Yes
- Locally still OK. No problem in development.

refactor(v2): use hash to compare generated content

---

packages/docusaurus-1.x/lib/core/nav/SideNav.js
packages/docusaurus-1.x/lib/static/css/main.css

Fix #1230 , to change icon for navToggle to a more traditional one.
Yes
Changed the navToggle icon. This is before:
This is after:

fix: change icon for navToggle

---

docs/guides-blog.md

The property is part of `website/siteConfig.js` and the example looks like a sentence.
Yes
Not need it.
No PRs related

fix: blog docs example as object property

---

packages/docusaurus/lib/server/load/routes.js
packages/docusaurus/test/load/routes.test.js

No need to render https://docusaurus-2.netlify.com/docs/
Bug reported in https://docusaurus-2.netlify.com/feedback/p/intuitive-base-url
Yes
Netlify doesnt render that

fix(v2): don't render docs baseroute because its empty

---

yarn.lock

Fixes  #1368. Debug, js-yaml and underscore.string had security vulnerabilities in the version which were using in our codebase. The mentioned dependencies are upgraded to their latest version to resolve security issues.
Yes !
None

fix: upgrade underscore.string to 3.3.5

---

packages/docusaurus/lib/commands/start.js
packages/docusaurus/lib/webpack/server.js

Make sure non default baseUrl works (super high priority)
Yes
- Set `/test` as baseUrl in `docusaurus.config.js` 
- Local development and production build is now in the correct structure

fix(v2): make sure non default baseUrl works on build & dev

---

packages/docusaurus/lib/client/exports/useDocusaurusContext.js
packages/docusaurus/lib/default-theme/BlogPage/index.js
packages/docusaurus/lib/default-theme/BlogPost/index.js
packages/docusaurus/lib/default-theme/Doc/index.js
packages/docusaurus/lib/default-theme/Markdown/index.js
packages/docusaurus/lib/default-theme/Navbar/index.js
packages/docusaurus/lib/default-theme/Pages/index.js

Create a wrapper context function that allows access to context easily. It's quite troublesome now to have to import `useContext` and `@docusaurus/context`. Bundle them together as `useDocusaurusContext`.
Yes.
Site still builds and can navigate each page.

feat(v2): create useDocusaurusContext

---

packages/docusaurus/lib/client/serverEntry.js
packages/docusaurus/lib/webpack/server.js

Fix SSR mismatch location for non default baseurl.
Yes
Set `baseUrl` to `/test` on `docusaurus.config.js`
```bash
cd website
yarn build
```
Notice that the `index.html` generated is Page Not Found
After this PR, the `index.html` generated is now correct.
#1414

fix(v2): fix SSR mismatch location for non default baseurl

---

packages/docusaurus/bin/docusaurus.js
packages/docusaurus/package.json

Added a dedicated command which will print debugging information about the local environment.
`docusaurus info` results in :-
```bash
Environment Info:
System:
OS: Linux 4.18 Ubuntu 18.10 (Cosmic Cuttlefish)
CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
Binaries:
Node: 8.11.4 - /usr/bin/node
Yarn: 1.16.0-0 - /usr/local/bin/yarn
npm: 6.9.0 - /usr/local/bin/npm
Browsers:
Chrome: 74.0.3729.108
Firefox: 63.0
npmGlobalPackages:
@docusaurus: 1.8.3
```

feat(cli v2): Added new environment info command

---

docs/tutorial-create-pages.md

Mentioning F8 in the tutorial feels weird without context. Removing it to make it more general.
Yes
Netlify.

doc: remove references to F8 in tutorial

---

packages/docusaurus/bin/docusaurus.js

This small change makes sure that a host parameter can be passed to the webpack dev server.
All the underlying code exists, only the host option is not passed correctly, which is fixed in this PR.
Yes
Manually tested that the host parameter is passed to the start command when `-h <address>` is used.
No

fix: pass the missing host option to start

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
packages/docusaurus/CHANGES.md
packages/docusaurus/lib/server/load/__tests__/__fixtures__/custom-site/docusaurus.config.js
packages/docusaurus/lib/server/load/__tests__/__fixtures__/simple-site/docusaurus.config.js
packages/docusaurus/lib/server/load/__tests__/config.test.js
packages/docusaurus/lib/server/load/config.js
website/docusaurus.config.js

Move headerLinks as themeConfig stuff. 
Remove old and dead code
Yes
- Locally headerlinks still work
- Netlify

refactor(v2): move headerLinks -> themeConfig & rm dead code

---

.eslintrc.js
packages/docusaurus/src/client/App.js
packages/docusaurus/src/client/clientEntry.js
packages/docusaurus/src/client/docusaurus.js
packages/docusaurus/src/client/serverEntry.js
packages/docusaurus/src/client/theme-fallback/Layout/index.js
website/pages/index.js

- Remove all `eslint-disable-lines` due to no import resolve on webpack alias.
- Tweak eslintrc a little bit
- Improve a11y
Yes
- Locally website still works
- Netlify builds

chore(v2): improve a11y & tweak eslint

---

packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-blog/src/index.js
packages/docusaurus-plugin-content-blog/src/markdownLoader.js
packages/docusaurus-plugin-content-blog/src/theme/BlogListPage/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogPostPage/index.js
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/website/docs/foo/bar.md
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.js
packages/docusaurus-plugin-content-docs/src/__tests__/metadata.test.js
packages/docusaurus-plugin-content-docs/src/markdown/index.js
packages/docusaurus-plugin-content-docs/src/metadata.js
packages/docusaurus-plugin-content-docs/src/theme/DocPage/index.js
packages/docusaurus-plugin-content-docs/src/theme/DocSidebar/index.js
packages/docusaurus-theme-classic/src/theme/Layout/index.js
packages/docusaurus-utils/package.json
packages/docusaurus-utils/src/index.js
packages/docusaurus/package.json
packages/docusaurus/src/client/App.js
packages/docusaurus/src/client/theme-fallback/Layout/index.js
website/pages/index.js
yarn.lock

Enable frontmatter to specify description. If it's not defined, we'll take the first content of the markdown as description. This will then add `<meta description>` to head. Similar to how v1 behave. This is good for SEO
Also
- Fix lighthouse audit -> meta description
- Fix lighthouse audit -> non descriptive link text
- Remove fontawesome css, make our site slow
Yes
/docs/installation
Home page

feat(v2): meta description

---

packages/docusaurus-mdx-loader/package.json
packages/docusaurus-mdx-loader/src/index.js
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-blog/src/index.js
packages/docusaurus-plugin-content-blog/src/markdownLoader.js
packages/docusaurus-plugin-content-blog/src/theme/BlogListPage/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogPostPage/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogPostPaginator/index.js
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-docs/src/markdown/index.js
packages/docusaurus-plugin-content-docs/src/metadata.js
website-1.x/blog/2018-12-14-Happy-First-Birthday-Slash.md

Patch #1450 
Before
309 additions and 121 deletions. to master
After
263 additions and 114 deletions. to master
- More general purpose mdx-loader that exports frontMatter as an object. Why is this good ?
Allow `js` files to do
```js
import Content, {frontMatter} from 'blablabla.mdx'
```
- Frontmatter should be something that's not related to plugin. Anything that involves plugin should be named "metadata" instead of "frontmatter"
- We no longer need to create file for `frontMatter`, saving writing disk overhead because `frontMatter` can be accessed in the content itself. 
Yes
- Locally seems ok
- Netlify

feat(v2): export frontMatter as an object within MDX file

---

packages/docusaurus-mdx-loader/package.json
packages/docusaurus-mdx-loader/src/index.js
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-blog/src/index.js
packages/docusaurus-plugin-content-blog/src/markdownLoader.js
packages/docusaurus-plugin-content-blog/src/theme/BlogListPage/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogListPaginator/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogPostItem/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogPostPage/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogPostPaginator/index.js
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-docs/src/markdown/index.js
packages/docusaurus-plugin-content-docs/src/metadata.js
packages/docusaurus-utils/src/index.js
packages/docusaurus/src/client/exports/ComponentCreator.js
packages/docusaurus/src/server/load/routes.js
website-1.x/blog/2018-12-14-Happy-First-Birthday-Slash.md
website/docusaurus.config.js

Make blogs great again
- Clean up blog data props structure by splitting metadata and front matter into two separate props. This is helpful in letting users add whatever they want to the front matter and have it being referenced in blog posts. Metadata is something that is controlled by the plugin. There will not be collisions if we split it up. For blog list pages, I've also cleaned them up a bit and reused the blog item metadata and front matter. It was being duplicated in the list's metadata and the entries 😓 
- Remove use of `isBlogPage` and distinguish between blog list and blog posts.
- Add prev/next for blog list pages (new `BlogListPaginator` component)
- Add prev/next for blog item pages (new `BlogItemPaginator` component)
The blog plugin code is a little harder to read now, but …

refactor(v2): blog data revamp

---

packages/docusaurus/src/client/PendingNavigation.js
packages/docusaurus/src/webpack/base.js
website-1.x/blog/2018-09-11-Towards-Docusaurus-2.md

- Fix weird window scrolling behavior. It shouldn't scroll to top until page is already loaded
Others:
- Webpack javascript rule should also transpile file that use `docusaurus` as its name. This is to make sure that shipped theme packages can be babel transformed
- Remove mdx incompatibility inside one of our blog
Yes
Throttle internet
Before (window already scroll to top even before loading is finished)
After

fix(v2): window scrolling behavior

---

packages/docusaurus/src/client/theme-fallback/Loading/index.js

Improve error message
Yes
Try to simulate an error
Before
After

chore(v2): better error message style

---

packages/docusaurus-plugin-content-blog/src/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogTagsListPage/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogTagsPage/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogTagsPostsPage/index.js
website-1.x/blog/2017-12-14-introducing-docusaurus.md
website-1.x/blog/2018-04-30-How-I-Converted-Profilo-To-Docusaurus.md
website-1.x/blog/2018-09-11-Towards-Docusaurus-2.md
website-1.x/blog/2018-12-14-Happy-First-Birthday-Slash.md

Allow adding of tags to pages and dedicated pages for
- Displaying those tags
- Displaying a list of posts belonging to that tag
Yes.
See Netlify preview. Go to `/blog/tags`.
NA.

feat(v2): blog tags

---

docs/api-commands.md
packages/docusaurus-1.x/lib/core/toc.js

Fix #1457. See that issue for more description.
Yes
```md
```
Before
Wrong TOC
After

fix: right TOC should not strip special chars

---

packages/docusaurus-plugin-content-blog/src/index.js
packages/docusaurus-plugin-content-docs/src/__tests__/sidebars.test.js
packages/docusaurus-plugin-content-docs/src/index.js
packages/docusaurus-plugin-content-docs/src/sidebars.js
packages/docusaurus-plugin-content-pages/src/index.js

handle non existent blog, docs, pages
Yes
Before (bunch of errors)
After
No error even if pages/docs/blog is empty

 fix(v2): handle non existent blog, docs, pages

---

packages/docusaurus-plugin-content-blog/src/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogPostItem/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogPostPage/index.js
packages/docusaurus-plugin-content-blog/src/theme/BlogTagsPostsPage/index.js
website-1.x/blog/2017-12-14-introducing-docusaurus.md

Display tags on blog posts to increase discovery.
Yes
See Netlify, tags show on the posts now and link between them.
NA

feat(v2): list blog tags on posts

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/Footer/index.js
packages/docusaurus/src/server/load/config.js
website/docusaurus.config.js

Allow footer to be configured from `docusaurus.config`, similar to navbar. You could publish a new version and add this to your technical preview blog post :)
Yes
See Netlify.
NA

feat(v2): theme config for Footer

---

docs/tutorial-create-pages.md

I'm afraid it was not clear, to the beginner user—who this tutorial [is for][1]—where the `docs` folder was . 
The only reason I know this is because I'm a beginner user and I tried for too many minutes to find the `docs` folder inside the `website` folder. :sweat_smile: 
I had this assumption because the [previous example][2] is offered under the assumption that you're in the `website` folder.
[1]: https://docusaurus.io/docs/en/next/tutorial-setup
[2]: https://docusaurus.io/docs/en/next/tutorial-create-pages#creating-a-regular-page
Feel free to change the wording, I just want to make it clear where you should be looking, if you're new.
I'm new to Docusaurus and I want to make the tutorial clear for new users.
I haven't... and now I have. Sorry about my commit not matching the style. I'm …

docs: make it clear in the tutorial where the `docs` folder is

---

docs/tutorial-create-new-site.md

In this tutorial we assume that the user may or may not have used Node.js. It would follow then, based on how long it takes the "Linking dependencies" step to complete—243.61s for me—that we give them a hint that it might take a minute.
Support users new to Node.js by assuring them that the "Linking dependencies" step takes time, and that the program has not frozen.
:+1: 
Just added a hint to the tutorial. No change in code.
:no_good_man:

docs: add hint for linking dependencies time

---

docs/tutorial-setup.md

Since we're instructing the user to create a new repository, it might be a safe bet to assume that they don't have their SSH keys set up. HTTPS might be a better option in this context.
The motivation is to make the tutorial stop-free for new users. If the user hasn't set up their SSH keys, this part of the tutorial presents a road block. If I understand correctly, using HTTPS instead, here, removes that possible road block.
Indeed.
I tried using cloning with HTTPS on my Windows 7 Git Bash and it worked, when an SSH clone did not.
This is related to issue #1469

doc: change tutorial git to suggest HTTPS

---

docs/getting-started-docker.md
docs/getting-started-installation.md
docs/tutorial-create-pages.md
docs/tutorial-publish-site.md
website-1.x/versioned_docs/version-1.0.x/getting-started-installation.md
website-1.x/versioned_docs/version-1.1.x/getting-started-installation.md
website-1.x/versioned_docs/version-1.2.x/getting-started-installation.md
website-1.x/versioned_docs/version-1.3.x/getting-started-installation.md
website-1.x/versioned_docs/version-1.4.x/getting-started-docker.md
website-1.x/versioned_docs/version-1.5.x/getting-started-installation.md
website-1.x/versioned_docs/version-1.8.0/getting-started-installation.md
website-1.x/versioned_docs/version-1.9.0/getting-started-installation.md
website-1.x/versioned_docs/version-1.9.0/tutorial-create-pages.md
website-1.x/versioned_docs/version-1.9.0/tutorial-publish-site.md

I found **webserver vs web server**, and I saw all of them use *web server* instead of *webserver*
Example: https://en.wikipedia.org/wiki/Web_server
Yes

docs: normalized spelling of `web server`

---

website/docs/cli.md

docs(v2): CLI docs

---

packages/docusaurus/src/commands/build.js

should be able to build even if static folder doesnt exist
Yes

fix(v2): should be able to build even if static folder doesnt exist

---

packages/docusaurus-1.x/lib/core/nav/SideNav.js

we are adding click listener on ".toc-headings" and removing toActive class if the target is "A" tag, Where in case of this issue the target is actually Code tag. 
Look at the below code.
```html
<li><a href="#docusaurus-build"><code>docusaurus-build</code></a></li>
```
Because of this "toActive" class is not getting removed.
Yes
I have done Yarn test, and every test cases passed. 
For verification of the code, I tried the following URL  https://docusaurus.io/docs/en/commands/#docusaurus-build
and it's working as per expectation.
Close #1254
Close #1485

fix: h3 topics with Markdown formatting causes a glitch on mobile

---

packages/docusaurus-1.x/lib/core/DocsLayout.js

Resolved #1344
Yes
- I clone https://github.com/reduxjs/redux and install all dependencies
- Use this commit for `node_modules/docusaurus`
- Run `yarn start`
- Go to `http://localhost:3000/faq`
- Go to the bottom of the page and click on "General" and it goes to `http://localhost:3000/faq/general`
- Go to the bottom of the page and click on "FAQ Index" and it goes to `http://localhost:3000/faq` (it goes to `http://localhost:3000/` without this commit)
You can see the preview in https://hongarc.github.io/redux/faq

fix: wrong `relativeHref` in next/prev button

---

packages/docusaurus-1.x/lib/server/blog.js

- `/\/index.html$/` is wrong, it should be `/\/index\.html$/`
- Group `/\/index\.html$/` and `/\.html$/` to `/(\/index)?\.html$/`
- Don't need changing `new RegExp('/', 'g')` but I think change it to same other RegExp
- `.replace('-', '/')` was called thrice, maybe he want to replace all so I change it to /-/g (I'm wrong here)
| Input           | /(\/index)?\.html$/ | /\/index.html$/ | /\.html$/ |
|-----------------|---------------------|-----------------|-----------|
| home/index.html | home.md             | home.md         |           |
| home/indexahtml | home/indexahtml     | home.md         |           |
| home.html       | home.md             |                 | home.md   |

chore(v1): improve blog use replace method

---

packages/docusaurus-1.x/lib/server/readMetadata.js

- `path.basename` return `string`, don't need using `toString`
- I think `path.parse` is better(don't sure)
Yes
| file                  | path.basename(file, path.extname(file)) | path.parse(file).name |
|-----------------------|-----------------------------------------|-----------------------|
| /path/to/filename.ext | filename                                | filename              |
| /path/to/filename2    | filename2                               | filename2             |
`path.basename` return string so I think we don't need to check `'somestring'.toString()` (actually, I tested this change and one more PR for Redux's website and I didn't any error)

fix: change regex to match index.html

---

packages/docusaurus-1.x/lib/core/nav/SideNav.js

Fixed #1338
Yes
Test with `testing-library`'s website.
Live preview in https://hongarc.github.io/testing-library-docs/
- Go to https://hongarc.github.io/testing-library-docs/
- View page as mobile (chrome dev tools)
- Click`docs` in nav-site
- Click `toggle of nav` click one item in `DOM Testing Library`
Before:
After:
It shows subcategory's title if it is a subcategory
and keep `category`'s title if it is a category

fix: show `subcategory` if it is exist for title of nav

---

packages/docusaurus-1.x/package.json
packages/docusaurus-init-1.x/package.json
packages/docusaurus/package.json
yarn.lock

`shelljs` version in `docusaurus-init` is very old. That version is released 2 years ago, I suspect https://github.com/facebook/Docusaurus/issues/1330#issuecomment-494286733 is happening because of shelljs
There are lot of bug fixes done in the newer version https://github.com/shelljs/shelljs/blob/master/CHANGELOG.md
Yes
- Locally both development server v1 and v2 still works
- Netlify for both version

chore: upgrade shelljs version

---

packages/docusaurus/package.json
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/constants.ts
yarn.lock

Refactor the "static" files copying into using https://github.com/webpack-contrib/copy-webpack-plugin.
This has several advantages:
- We have less codes in `commands/build.ts`
- User can modify the copy behavior or even remove the copywebpackplugin behavior itself with `configureWebpack`
- We can use all the features from copy-webpack-plugin like transforming the copied files.
Disadvantage
- Tied to webpack
Yes
Local build

refactor(v2): use copy webpack plugin instead of manual copy

---

packages/docusaurus/src/commands/build.ts

Static files was copied to wrong place.
It was copied to https://docusaurus-2.netlify.com/static/img/docusaurus_keytar.svg
but not https://docusaurus-2.netlify.com/img/docusaurus_keytar.svg
Yes
Build locally and test it with python http server

fix(v2): wrong copy static files target directory

---

packages/docusaurus/src/server/index.ts

When we try to build the app on a windows pc, the modules path were wrong. Now with this tiny fix, the build run smoothly.
yes
When we "yarn start" the app build is successful.
Nothing change, just a fix

fix(v2): wrong modules path on windows

---

packages/docusaurus/src/server/__tests__/__snapshots__/routes.test.ts.snap
packages/docusaurus/src/server/__tests__/routes.test.ts
packages/docusaurus/src/server/routes.ts

- Add static typing (Typescript definition) for `server/routes.ts`
- Add stronger test for `server/routes.ts` so that it is less prune to errors
- Some refactoring
Yes
- Development still works
- Netlify works

refactor(v2): add test & static typing for routes.ts

---

packages/docusaurus/src/commands/init.ts

According to [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html), using `Boolean` is bad. Looking at the code, I don't think it requires the `Boolean` wrapper type.
Yes
N/A
N/A

fix: replace Boolean with boolean in typescript type annotation

---

packages/docusaurus-1.x/lib/core/DocsLayout.js
packages/docusaurus-1.x/lib/core/DocsSidebar.js
packages/docusaurus-1.x/lib/core/nav/SideNav.js

Addresses issue on RN website where collapsible sidebar also appears on the Blog:
> I just noticed that this also collapses the sidebar in the blog section. Is it possible to always expand it there?
Yes
Docs show collapsing but blog doesn't.
https://github.com/facebook/react-native-website/pull/934

fix: don't collapse the blog navigation even if collapsible is true

---

packages/docusaurus/src/commands/build.ts

Regression from https://github.com/facebook/Docusaurus/commit/e4de7c3ed43b839cc69dca6560d7c912aeba2cdd
That kinda reverted the static dir fix from
https://github.com/facebook/Docusaurus/commit/05ba7d835dc316b8f981e137e3935a51128ad2e4
Although there is no build error now, it just output some warning
Yes

fix(v2): check static dir exist before copying

---

packages/docusaurus/package.json
packages/docusaurus/src/webpack/plugins/WaitPlugin.js
yarn.lock

Update dependencies so that it can point the npm version instead of my GitHub
Because in some cases, it can error out to install from GitHub
Yes

chore(v2): update dependencies

---

package.json
packages/docusaurus-1.x/package.json
packages/docusaurus-init-1.x/package.json
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-pages/package.json
packages/docusaurus/package.json
yarn.lock

`@types/globby@9.1.0` and `@types/chalk@2.2.0` are two stub types definition, so I removed them in `package.json`.
By the way, I updated `globby` and `chalk` (`chalk@2.1` don't have `index.d.ts`).
Yes
You can see `index.d.ts`:
- [chalk's `index.d.ts`](https://github.com/chalk/chalk/blob/master/index.d.ts)
- [globby's `index.d.ts`](https://github.com/sindresorhus/globby/blob/master/index.d.ts)

 chore: remove `@types/chalk` and `@types/globby`

---

packages/docusaurus-plugin-content-pages/src/index.js

Old way:
- Convert each element to `Promise` (`['elem1', 'elem2']` => `Promise {<resolved>: 'elem1'}`, `Promise {<resolved>: 'elem2'}`, )
- Use `Promise.all` convert all of that `Promise` to one `Promise` return array have all element (`Promise {<resolved>: 'elem1'}`, `Promise {<resolved>: 'elem2'}` => `Promise {<resolved>: ['elem1', 'elem2']}`)
My way:
- Just return that array (inside `async` function, we can return value instead of `Promise`)
Yes
[Small test](https://repl.it/@Hongarc/async):
- value of them is the same
- this change is simple and faster

refactor(v2): return value instead of Promise in async

---

packages/docusaurus/templates/classic/package.json
website/package.json

Not having browserslist means that anything not all browsers don't support will end up getting compiled by Babel. Which translates to literally every single feature that Babel supports.
This isn't a good practice, according to https://babeljs.io/docs/en/babel-preset-env#browserslist-integration. 
The browesrslist is taken from CRA
Especially on development, webpack-dev-server itself only guarantee supporting limited number of browsers, so it makes sense to add sensible default browserlist.
Note that this does not mean we lock user to these certain browser only, user of docusaurus can always override the browserlist in their package.json or creating a browserlistrc. It's just that we generate this sensible default on official template
yes
- Local development still works
- Netlify preview …

chore(v2): add sensible default browserlist

---

packages/docusaurus-plugin-content-docs/src/theme/DocItem/index.js
packages/docusaurus-plugin-content-docs/src/theme/DocItem/styles.module.css

if you open https://v2.docusaurus.io/, the right table of content is not sticky/ does not follow viewport like v1. 
Check, https://reasonml.github.io/docs/en/what-and-why in desktop, try to scroll and see that the right toc is following viewport
Go to https://v2.docusaurus.io/docs/introduction, try to scroll and see that the right toc is not sticky
P.S: The right toc still need a lot of kwork, especially on mobile. But this Pr only aim to solve the sticky position on large viewport
yes

 fix(v2): right toc should be sticky

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/infima.js
packages/docusaurus-theme-classic/src/theme/Layout/styles.css
packages/docusaurus/src/client/App.js
packages/docusaurus/src/server/index.ts
website/docusaurus.config.js
website/pages/styles.module.css
website/plugins/plugin-infima-overrides/index.js
website/plugins/plugin-infima-overrides/infima-overrides.js
website/plugins/plugin-infima-overrides/infima-variables.css
yarn.lock

Use the proper abstractions and engineer it right:
- Install Infima from npm (I just published `0.2.0-alpha.1`)
- Import Infima CSS from theme-classic.
- Move Infima variables override into `website` folder via a client module.
After this lands, we should publish new version asap and help existing users migrate asap. Loading Infima CSS from trunk is a ticking time bomb waiting to explode.
Yes
Site looks the same!
NA

fix(v2): use Infima from npm instead of trunk CDN

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/components/CodeBlock/index.js
website/docs/writing-documentation.md
yarn.lock

Live playground makes the TTI (time to interactive) slower and reduce our lighthouse performance score. Most of the time ppl dont need playground. We should lazy load the playground component
Live playground is not small in size, lazy load it is better. This does not effect normal syntax highlighting (not playground)
note that reacjs org is kinda doing a similar stuff ??
also added docs for the feature
yes
real world test in production (its almost unnoticeable)
try it here: https://deploy-preview-1557--docusaurus-2.netlify.com/docs/writing-documentation/ and scroll down to bottom

feat(v2): live playground should be lazily loaded on visibility

---

packages/docusaurus-theme-classic/src/theme/components/CodeBlock/index.js

There is a trailing newline in each code block passed to prism react renderer. This fix trims the string before passing them down.
Yes
Before
After

fix(v2): Trim code block before passing to prism react renderer

---

packages/docusaurus-plugin-content-docs/src/theme/DocItem/index.js
packages/docusaurus-plugin-content-docs/src/theme/DocItem/styles.module.css
packages/docusaurus-plugin-content-docs/src/theme/DocPage/index.js
packages/docusaurus-plugin-content-docs/src/theme/DocPage/styles.css
packages/docusaurus-plugin-content-docs/src/theme/DocSidebar/styles.css

This PR removes the hardcoded `width:20rem` value in the sidebar css in D2. 
Also, it was brought up in [#1530](https://github.com/facebook/Docusaurus/issues/1530)
Yes
Local Testing.
- #### Before removing sidebar width
- #### After removing sidebar width
None

fix(v2): removes hardcoded sidebar width

---

packages/docusaurus-preset-classic/src/index.js
packages/docusaurus/CHANGELOG.md
packages/docusaurus/src/server/__tests__/__fixtures__/custom-site/docusaurus.config.js
packages/docusaurus/src/server/__tests__/__fixtures__/simple-site/docusaurus.config.js
packages/docusaurus/src/server/plugins/index.ts
packages/docusaurus/src/server/presets/__tests__/__fixtures__/preset-bar.js
packages/docusaurus/src/server/presets/__tests__/__fixtures__/preset-foo.js
packages/docusaurus/src/server/presets/__tests__/__fixtures__/preset-qux.js
packages/docusaurus/src/server/presets/__tests__/index.test.ts
packages/docusaurus/src/server/presets/index.ts
website/docs/plugins-api.md

…e like presets
One consistent format for declaring plugins, themes and presets.
Yes
Site builds. Tests pass.

refactor(v2): change plugin format within `docusaurus.config.js` to be like plugins

---

packages/docusaurus-1.x/lib/static/js/scrollSpy.js

fix #1569
Yes
Just add:
```md
```
You should see something like this:

fix: add support for non-latin characters in scrollSpy ToC highlighter

---

packages/docusaurus/src/client/PendingNavigation.js
website/docs/configuration.md

In-page hash anchors are behaving weirdly. Clicking on them first time will go to the top of the page, the second time will go to the anchor scroll location. Try the four links on the second section of [this page](https://deploy-preview-1539--docusaurus-2.netlify.com/docs/configuration)
See this
yes
Locally
Netlify test

fix(v2): fix scrolling problem for location with hash

---

website/docs/configuration.md

These links in Configurations doc look like partial TOC but they link to another page. This is annoying. Thanks @endiliey for the inspiration from the other PR!
Yes.
NA
NA

docs(v2): remove links to other page that looks like partial toc

---

packages/docusaurus-theme-classic/src/theme/BlogListPaginator/index.js
packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css
website/css/custom.css

Make the site fit eyes better 
- Sets `max-width` to content block (consider moving to `article` or `main` selector in styling library)
- Adds a border right to sidebar, matching navbar border bottom, and toc border left
Yes
(check preview)
NA

feat(v2): doc page layout changes

---

packages/docusaurus/src/client/PendingNavigation.js

To better prepare for implementing `onRouteUpdate` and `onRouteUpdateDelayed` browser APIs, here are a few improvements to `PendingNavigation`:
- Don't trick React into rendering the same location just to preserve the current route. Use `shouldComponentUpdate` for those purposes. With this, `render()` is only called once - when it's ready to transition
- Save previous location on `this` since it doesn't affect the rendering
- Make it very clear where to call `onRouteUpdate` and `onRouteUpdateDelayed`
Yes
Test with slow 3G throttling in Netlify preview.
To get around the `prefetch`, replace `preload` with this locally:
```
export default function preload(routes, pathname) {
const matches = matchRoutes(routes, pathname);
return Promise.all(
[...matches.map(match => {
const {component} = …
```

refactor(v2): improve PendingNavigation to not use componentWillReceiveProps

---

packages/docusaurus/src/client/exports/context.ts
packages/docusaurus/src/client/exports/useDocusaurusContext.ts
packages/docusaurus/src/client/types.ts
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/deploy.ts
packages/docusaurus/src/commands/init.ts
packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/commands/swizzle.ts
packages/docusaurus/src/server/client-modules/index.ts
packages/docusaurus/src/server/config.ts
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/loadSetup.ts
packages/docusaurus/src/server/plugins/index.ts
packages/docusaurus/src/server/presets/index.ts
packages/docusaurus/src/server/routes.ts
packages/docusaurus/src/server/themes/alias.ts
packages/docusaurus/src/server/themes/index.ts
packages/docusaurus/src/server/types.ts
packages/docusaurus/src/webpack/base.ts
packages/docusaurus/src/webpack/client.ts
packages/docusaurus/src/webpack/server.ts

Just moving interfaces to a dedicated types file. it's not a good idea to keep interfaces on the real code as it make the code very intimidating to the reader. Having `types.ts`  also makes it clear that it is a typescript types.
yes
Nothing broke
Netlify and CI should pass

refactor(v2): move typing to types.ts

---

packages/docusaurus-theme-classic/src/theme/MDXComponents/index.js

Fix #1581
We should only pass our codeblock component if it's content is a string.
Note that this bug is because MDX turns `<div>` or react component to real react element.
yes
```md
import BrowserWindow from '../components/BrowserWindow';
<pre><code>
<BrowserWindow url="http://localhost:3000" >
Lol bro
</BrowserWindow>
</code></pre>
```
**Before**
**After**

fix(v2): handle case when <code> children is not a string

---

docs/api-site-config.md

I wanted to enable superscript and subscripting to a v1 site. It wasn't quite clear how to do it. @yangshun helped me figure it out. So I thought I would document it.
Yes
Local
https://github.com/facebook/Docusaurus/pull/974

docs: add more clarity about markdown fields

---

packages/docusaurus-1.x/lib/core/BlogSidebar.js
packages/docusaurus-1.x/lib/core/DocsSidebar.js

In this case, the `docsNavContainer` does not pick up any styles or attributes from the `container` component it is wrapped in.
It does however pick up the pesky `.container` className, which when paired with bootstrap, messes up the styling of the top navigation in mobile.
This change is completely non-destructive, but helps enable the use of bootstrap on top of Docusaurus.

fix: remove the `Container` component from the `docsNavContainer`

---

packages/docusaurus-1.x/lib/build-files.js
packages/docusaurus-1.x/lib/start-server.js
packages/docusaurus-1.x/lib/version.js
packages/docusaurus-1.x/lib/write-translations.js

FIX #1574 
1. Follow the reproducing steps of #1574
2. Check that docusaurus builds
This is a fix, it shouldn't require any updates in the documentation.

fix: require babel dependencies directly

---

packages/docusaurus-1.x/lib/core/BlogPageLayout.js
packages/docusaurus-1.x/lib/core/BlogSidebar.js
packages/docusaurus-1.x/lib/core/__tests__/__fixtures__/blog-post-with-draft.md
packages/docusaurus-1.x/lib/core/__tests__/__fixtures__/blog-post-with-unlisted.md
packages/docusaurus-1.x/lib/server/feed.js

Previously, the blog sidebar listed the most recent blog posts sorted by
their publish date. This commit adds the ability to hide a specific blog
post from the sidebar and the feed of all blog posts by adding the
`unlisted: true` header option.
Fixes #1393.
The motivation for this feature is to make it possible to change dates of published posts without breaking the old URL (which might be widely shared).
Concrete example, we published a blog post two weeks ago that is dated for 2020 (https://scalameta.org/metals/blog/2020/04/12/mercury.html). We have closed three PRs fixing the date (https://github.com/scalameta/metals/pull/683, https://github.com/scalameta/metals/pull/670, https://github.com/scalameta/metals/pull/656) but they have all been closed because changing the date of the post …

feat: add "unlisted" front matter option for blog posts

---

docs/getting-started-publishing.md

I believe the reference to step 3 should actually be to step 5.
No. I don't think it would be necessary for such a small change.
None needed. Just need an authorized maintainer to confirm that the step should be 5.

docs: fix reference to publishing steps

---

docs/guides-blog.md

Make sentences easier to read and understand.
For Docusaurus, no. For React, yes.
Let maintainer look at the text changes.

docs: minor grammar fix in blog guide

---

README.md

It seems the circleCI setup is no longer active, probably in favour of using netlify.
Therefore I removed the badge from the README
Sure
Only README update, no testing required
N/A

misc: CircleCI badge in README

---

packages/docusaurus-1.x/lib/static/css/main.css

Currently the items in table of contents are highlighted as bold based on items being
viewed on the screen or as the user scrolls up/down on a page. Added the `primaryColor`
of the site's configuration to make the current section being viewed standout more
in the table of content.
closes #1608
I can easily apply necessary changes so that items in table of contents are highlighted using the primary colour, but I think this is something others may find useful also.
Yes
Before the `css` change:
After the `css` change:

feat: use primary color for highlighted items in table of contents

---

packages/docusaurus-1.x/examples/basics/core/Footer.js

fix #1644 
the bootstrapped footer code doesnt include social links
wrong (outdated?) component is being created during bootstrapping.
yes

fix: wrong bootstrapped footer social links

---

packages/docusaurus-1.x/examples/basics/siteConfig.js

Collapsible categories are pretty useful and should be included in the basic siteConfig.js 
https://github.com/facebook/docusaurus/blob/master/docs/guides-navigation.md#collapsible-categories
Yes

docs(v1): Add information for docsSideNavCollapsible in siteConfig.js

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-live-codeblock/package.json
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css
yarn.lock

Hi there. The motivation behind this was so many websites that don't have the copy button.
The design was pretty much eyeballed but is open for suggestions. I chose not to go with an icon here.
Attempts to close #1587 
Yes
- bootstrap the dependencies with
- ```sh
yarn
```
- Start the project with
- ```sh
yarn start
```
- Navigate to any codeblock, i.e. `http://localhost:3000/docs/installation`
- Hover the codeblock
- Click the copy button
I've only wrapped the `pre` element with a `div` that acts as a wrapper and use it for anchoring the position of the copy button.
I've used the `clipboard` package for copying because I saw it elsewhere in the repo
Edit:
I also noticed that `packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css` and …

feat(v2): CodeBlock copy button

---

packages/docusaurus/src/server/__tests__/__snapshots__/routes.test.ts.snap
packages/docusaurus/src/server/routes.ts

Generate/ Render 404 html page as well. This opens up possibility for user to override `theme/NotFound` page and create ez redirect in the future.
https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-classic/src/theme/NotFound.js
Currently, https://v2.docusaurus.io/nothing yields
yes
Local build(not dev)
localhost::5000/nothing
https://deploy-preview-1652--docusaurus-2.netlify.com/nothing

feat(v2): render 404 html page

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js

- Shouldnt clicking the logo in navbar points to home? Currently it closes navbar ![](https://i.imgur.com/J6ytQFF.png)
yes

fix(v2): clicking logo on mobile sidebar should go to homepage

---

packages/docusaurus-1.x/lib/server/utils.js

The warning is produced on `cssnano` call. See below:
> Without `from` option PostCSS could generate wrong source map and will not find Browserslist config. Set it to CSS file path or to `undefined` to prevent this warning.
I think the warning makes users confusing.
Yes.
The warning is produced already. See the [build log](https://circleci.com/gh/facebook/docusaurus/8313):
Also, you can reproduce on your shell terminal. Run the following commands:
```shell
mkdir work
cd work
npx docusaurus-init
cd website
yarn install
yarn run build
```
None.

fix: fix PostCSS warning on `build` command

---

website/docs/sidebar.md

Addressing #1640, add doc section on subcategories
Yes

docs(v2): subcategories

---

packages/docusaurus-theme-classic/src/theme/Layout/index.js
packages/docusaurus/src/client/templates/index.html.template.ejs
packages/docusaurus/src/client/templates/ssr.html.template.js

- remove unwanted initial-scale viewport meta tag
- use twitter summary tag https://stackoverflow.com/questions/47578130/twitter-card-summary-vs-summary-large-image
yes
https://cards-dev.twitter.com/validator
Previously
Now

feat(v2): better twitter preview meta tag

---

packages/docusaurus-plugin-ideal-image/package.json
packages/docusaurus-plugin-ideal-image/src/index.js
packages/docusaurus/package.json
yarn.lock

I forked https://github.com/zouhir/lqip-loader to https://github.com/endiliey/lqip-loader because the original version uses jimp, which is an image processing library that is so much slower than sharp
Check this benchmark for jimp vs sharp
https://sharp.pixelplumbing.com/en/stable/performance/
yes
- even in dev 1s is gained
before
after
- no changes in placeholder generation. check netlify

refactor(v2): use forked lqip-loader for performance

---

packages/docusaurus-theme-live-codeblock/package.json
packages/docusaurus-theme-live-codeblock/src/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js
packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/webpack/base.ts
yarn.lock

Wohooo this PR is self-explanatory
So i went to read nextjs, gatsbyjs, and many other ssg static site generators webpack config. Read lot of webpack articles on splitchunks and optimized our splitchunks plugin configuration to fit best web performance practices
Before this PR ~total 1.47mb 
and u can see that if we go to https://v2.docusaurus.io/, we also load vendors.js that contains react-live
This is bad, react-live shouldnt be loaded at all for landing page. 
So here's some summary changes
- Don't try to create a vendors chunk, which includes code from node_modules in the whole application.
- Don't assume http/2 (max, min request infinity), use webpack default value  maxAsyncRequests: 5,
maxInitialRequests: 3.
- Use forked buble for react-live which is smaller in size
- Remove …

feat(v2): ⚡️ faster and lighter bundle size (optimization)

---

CHANGELOG-2.x.md
packages/docusaurus/src/server/__tests__/__snapshots__/routes.test.ts.snap
packages/docusaurus/src/server/__tests__/routes.test.ts
packages/docusaurus/src/server/routes.ts

fix an error where empty string path is not valid
this makes some site cannot use `routebasepath` : '' and baseurl '/'
example: https://github.com/react-knowledgeable/notes/
yes

fix(v2): docusaurus route config generation for empty path

---

docs/getting-started-publishing.md
website-1.x/versioned_docs/version-1.10.x/getting-started-publishing.md
website-1.x/versioned_docs/version-1.12.0/getting-started-publishing.md
website-1.x/versioned_docs/version-1.9.x/getting-started-publishing.md

Me and @rauchg recently had a great call with @yangshun and @wgao19 about how [ZEIT Now](https://zeit.co/now) can deploy any Docusaurus project **without any configuration**.
We concluded that it would be a good idea to have users of Docusaurus take advantage of this right out of the box, so we added it to the docs.
It's basically as easy as this:
```
npx docusaurus-init
npx now                     # will prompt for login
```
Yes.
I described the usage in the section above. It's really simple.
No related PRs. I will soon create a new PR for Docusaurus 2.0, however.

docs: suggest ZEIT Now for quick deployment

---

docs/getting-started-publishing.md
website-1.x/versioned_docs/version-1.10.x/getting-started-publishing.md
website-1.x/versioned_docs/version-1.12.0/getting-started-publishing.md
website-1.x/versioned_docs/version-1.9.x/getting-started-publishing.md
website/docs/deployment.md

Me and @rauchg recently had a great call with @yangshun and @wgao19 about how [ZEIT Now](https://zeit.co/now) can deploy any Docusaurus project **without any configuration**.
We concluded that it would be a good idea to have users of Docusaurus take advantage of this right out of the box, so we added it to the docs.
It's basically as easy as this:
```
npx @docusaurus/init@next init my-website classic
npx now my-website                                            # will prompt for login
```
Yes.
I described the usage in the section above. It's really simple.
The PR is a follow-up to this: https://github.com/facebook/docusaurus/pull/1690.

docs: suggest ZEIT Now for quick deployment of 2.0

---

CHANGELOG-2.x.md
packages/docusaurus-plugin-content-pages/src/__tests__/index.test.js
packages/docusaurus-plugin-content-pages/src/index.js

Minor refactoring on pages plugin. Make use of `@site` alias so that we dont need to expose whole absolute path and potentially make the chunk name shorter
before this pr, the component naming is component-opt-build-website-blablabla.
yes
shorter now. it become site-blablabla
the pages metadata is like this after this pr
```js
{
"permalink": "/",
"source": "@site/src/pages/index.js"
}
```

feat(v2): shorter chunk naming for pages

---

CHANGELOG-2.x.md
packages/docusaurus-plugin-content-blog/src/index.js
packages/docusaurus-plugin-content-docs-legacy/src/__tests__/index.test.js
packages/docusaurus-plugin-content-docs-legacy/src/__tests__/metadata.test.js
packages/docusaurus-plugin-content-docs-legacy/src/index.js
packages/docusaurus-plugin-content-docs-legacy/src/markdown/index.js
packages/docusaurus-plugin-content-docs-legacy/src/metadata.js
packages/docusaurus-plugin-content-pages/src/index.js
website/docs/installation.md

In the current implementation, the `source` field in the metadata of docs, blog and pages are the absolute path of the file in the machine. This is a potential security vulnerability (albeit not a huge one) because we're exposing the directory structure of the host machine.
Since we already have a `@site` alias in webpack, we can replace all the path segments outside the website to be `@site` (which @endiliey did in #1688). This has the following benefits:
- Shorter module names
- Smaller metadata size (shorter paths)
- Hides the device directory structure and makes the build environment-agnostic - different devices with different setup running the build command will produce the same file contents, filename and MD5 hash for files. This results in better cachability
Yes
Tests pass, site …

fix(v2): do not reveal environment file path

---

CHANGELOG-2.x.md
packages/docusaurus-plugin-content-pages/src/index.js

Metadata for pages is too small and is actually unused. from lighthouae audit, it just create extra request. lets remove it
the metadata is like this
```json
{
"permalink": "/feedback/",
"source": "@site/src/pages/feedback/index.js"
}
```
yyes
- ci
- netlify preview

refactor(v2): remove unused metadata for pages

---

website/src/theme/NotFound.js

try going to any feedback page directly
https://v2.docusaurus.io/feedback/p/hamburger
it will be 404. user have to go to feedback page directly and click on the page
this pr swizzle our 404 page so that it wont 404 when going to feedback page
yes
- directly go to feedback page

chore(v2): make feedback page accessible, not 404

---

docs/tutorial-setup.md

Please add an **Install Git** section to the **[Setting Up](https://docusaurus.io/docs/en/next/tutorial-setup)** page with its "detailed instructions on how to go from zero." To me "zero" means only the operating system.

docs: add "Install Git" to the "Setting Up" page

---

docs/tutorial-setup.md

The `cd` step seems like the first step of "Install the Docusaurus init command," instead of the last step of "Create a GitHub repository and local clone."

docs: move a cd step to the start of the init task

---

docs/tutorial-setup.md

The description of `npm` fits better in the opening paragraph than in a numbered step. The note about version 8 fits better in the Check section than the Install section.

docs: rearrange the info for install and check Node.js

---

docs/tutorial-create-new-site.md

The step "`cd` to the directory of your local repository" was moved from **[Install the Docusaurus init command](https://docusaurus.io/docs/en/next/tutorial-setup#install-the-docusaurus-init-command)**. See the previous pull request.

add "cd to the repository" to "Scaffold the Site"

---

docs/tutorial-setup.md

The folder isn't important for the command `npm install --global docusaurus-init`. 
However, it is important to run `docusaurus-init` in the repository folder. The next pull request moves the step to **[Scaffold the Site](https://docusaurus.io/docs/en/next/tutorial-create-new-site#scaffold-the-site).**

move "cd to the repository" to "Scaffold the Site"

---

docs/tutorial-create-new-site.md

Change the link from `http://localhost:3000` to `http://localhost:3000/docusaurus-tutorial/` in **[Scaffold the Site](https://docusaurus.io/docs/en/next/tutorial-create-new-site#scaffold-the-site)**.

docs: add the repository name to the localhost:3000 link

---

website/docs/deployment.md

Addresses #1640, add docs for deployment to Netlify
Yes
NA

docs(v2): deploy to netlify

---

docs/tutorial-create-new-site.md

@yangshun You're right. I removed `docusaurus-tutorial/` from the links. 
Reverts facebook/docusaurus#1715

docs: revert a link to localhost:3000

---

docs/tutorial-setup.md

I changed the `cd` example so it wouldn't say USERNAME like cloning example, which might mislead a new user.

docs: change example so USERNAME is only for GitHub

---

docs/api-site-config.md

The correct property, referenced on the "Custom Pages" docs page, is `separateCss`.  Using `separateCSS` has no effect.

Change separateCSS to separateCss in api-site-config

---

docs/tutorial-publish-site.md

I moved step 1 to step 2 so the terminal steps would be together. I added Git Bash, because `publish-gh-pages` worked for me in Git Bash but didn't work at the Windows command prompt. 
I added HTTPS to step 4 because, on my system, HTTPS worked for me but SSH didn't work. I changed <GIT_USER> to USERNAME and deleted the $ prompt, to be consistent with other examples in the tutorial.

docs: add an HTTPS example for publish-gh-pages

---

docs/tutorial-setup.md

I think the tutorial should tell Windows users to use Git Bash. Later in the tutorial is a command that worked in Git Bash, `publish-gh-pages`, but didn't work for me at the Windows command prompt.

docs: refer to Terminal and Git Bash

---

docs/tutorial-create-pages.md

Fix two links on **[Create Pages](https://docusaurus.io/docs/en/next/tutorial-create-pages)**.

docs: change the ID of the new documentation page

---

docs/tutorial-version.md

I changed "we" to "you" like the other sections of the tutorial.
I removed yarn from the code because `yarn version` didn't run on my Windows 10 system (see issue [1743](https://github.com/facebook/docusaurus/issues/1743)). 
I added headings for the current version, next version, and past versions.

docs: add past versions to the tutorial

---

CHANGELOG-2.x.md
packages/docusaurus/src/client/templates/ssr.html.template.js

The attributes of html element and body element are escaped during SSR.
Yes
Open the rendered HTML document.

fix(v2): do not escape html and body attributes

---

docs/api-site-config.md

The documented type was wrong, I think.
Well, I have now.
I must admit I haven't verified it because it's so trivial, but build the docs and visit /docs/en/site-config#cleanurl-string.
\-

docs: fix documented type for the `cleanUrl` option

---

.eslintignore
.gitignore
.prettierignore
jest.config.js
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-blog/src/markdownLoader.ts
packages/docusaurus-plugin-content-blog/src/types.ts
packages/docusaurus-plugin-content-blog/src/typesDocusaurus.ts
packages/docusaurus-plugin-content-blog/tsconfig.json
packages/docusaurus/src/server/plugins/index.ts
packages/docusaurus/src/server/presets/index.ts

https://github.com/facebook/docusaurus/issues/1698
I want to contribute to this issue.
Before that, I want to convert plugin code to TypeScript.
I want many opinions.
And I think we need a common type definition module that includes `DocusaurusConfig, LoadContext, PluginContent`, and so on.
So, I have collected these definitions in `typesDocusaurus.ts`.
Yes
Convert test codes to TypeScript also.
None

refactor(v2): convert `@docusaurus/plugin-content-blog` to TypeScript

---

CHANGELOG.md

Hi, I noticed these issues on the [v1.13.0 release](https://github.com/facebook/docusaurus/releases/tag/v1.13.0). When clicking the links, users will see the Not Found page.
Yes.
No plan. This PR fixes just documentation issues.
None.

docs: fix broken PR links

---

package.json

I found a missing configuration of `lint-staged` on `pacakge.json`
Yes
No
#1785

fix(v2): add `ts,tsx` to `lint-staged`

---

website-1.x/data/users.js

After changing my account name, the old link no longer works:
https://github.com/facebook/docusaurus/pull/1174#issuecomment-536184353

docs: update TypeGraphQL showcase url

---

website/src/css/custom.css

Sidebar currently has a consistent appearance on menu items on different levels. This makes it look a bit messy on the 2nd nested items:
This PR makes it looks like this:
Yes
NA

docs(v2): make double nested sidebar entry thinner and smaller

---

website/docs/migration-from-v1-to-v2.md
website/docs/migration.md
website/sidebars.js

Migration guide without having to init new site and also include all v1 siteConfig field -> v2 config equivalent. Feel free to edit. 
yes
Try it on netlify
https://deploy-preview-1809--docusaurus-2.netlify.com/docs/migration

docs(v2): simple migration guide from v1-v2

---

CHANGELOG-2.x.md
packages/docusaurus-plugin-content-docs-legacy/src/__tests__/__fixtures__/website/sidebars-category.js
packages/docusaurus-plugin-content-docs-legacy/src/__tests__/__snapshots__/sidebars.test.ts.snap
packages/docusaurus-plugin-content-docs-legacy/src/__tests__/sidebars.test.ts
packages/docusaurus-plugin-content-docs-legacy/src/sidebars.ts
website/docs/markdown-features.mdx
website/docs/sidebar.md

continuation from #1811 
Expect more PR on docs plugin probably this week as I try to make docs metadata more efficient later on. 
fix #827 #868 #1182 
- Support more than one level deep of nested sidebar.
- Add more detailed documentation of sidebar. 
https://deploy-preview-1812--docusaurus-2.netlify.com/docs/sidebar
(We actually already allow external href, etc its just undocumented because i forgot)
- Add test
yes
Try with docu v2 site
```js
// sidebars.js
docs: [
{
type: 'category',
label: 'level 1',
items: [
'introduction',
{
type: 'category',
label: 'level 2',
items: [
'contributing',
{
type: 'category',
label: 'level 3',
items: [
'design-principles',
{
type: 'category',
label: 'level 4',
items: [
'installation',
{
type: 'category',
label: 'deeper more more', …
```

feat(v2): allow infinitely nested sidebar

---

website/docs/advanced-plugins.md
website/docs/advanced-themes.md
website/docs/lifecycle-apis.md

Addressing #1640, refine docs to lifecycle APIs. Might combine to refine docs on advanced guides on plugins as well.
Yes
NA
NA

docs(v2): document plugins and lifecycle APIs

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/DocLegacyPage/index.js
packages/docusaurus-theme-classic/src/theme/DocLegacySidebar/index.js
website/src/css/custom.css

For docs with a long menu (like Docusaurus and CRA), collapsing the sidebars by default will be more helpful. Thanks to the awesome sidebar metadata refactoring by @endiliey, this is now possible.
Features:
- Highlight the recursive parent categories of the current menu item
- When you navigate to a page where the parent category is currently collapsed, that category will open up (I think there is still some buggy behavior but this is good enough for now).
I also removed displaying a smaller + different color link on the level 3, I think we don't need that differentiation now that we have the chevron.
Yes
Load the Netlify preview and click around!
#1815

feat(v2): make sidebar collapsible

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/DocLegacyItem/index.js
packages/docusaurus-theme-classic/src/theme/DocLegacyItem/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocLegacyPage/index.js
packages/docusaurus-theme-classic/src/theme/DocLegacyPage/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocLegacySidebar/index.js
packages/docusaurus-theme-classic/src/theme/DocLegacySidebar/styles.module.css

- Make doc page title larger like RN and React docs. I think it looks better because there's more emphasis on the title.
- Rewrite the sidebar container CSS to not use the grid system which wasn't the right thing to use
Yes

misc(v2): improve docs styles

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-classic/src/theme/MDXComponents/index.js
packages/docusaurus-theme-classic/src/theme/MDXComponents/styles.module.css
packages/docusaurus-theme-live-codeblock/package.json
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.js
packages/docusaurus-theme-live-codeblock/src/theme/Playground/styles.module.css
website/docs/markdown-features.mdx
yarn.lock

- Make the playground appearance more aligned with the website theme and look more like https://reactjs.org/
- Change default to Prism theme to Palenight. The Night Owl theme is quite niche and is not the best default. I'd use Oceanic Next as the default but it doesn't highlight symbols well (bug?). So I chose Palenight in the end.
Our CSS needs quite a bit of cleaning up, there are quite a lot of things that we should standardize by trying to use Infima variables and fallback to normal CSS values if Infima is not present on the page. I'll do that in a later PR.
One question I had is why are there two code block theme components? Are we using both?
Yes
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to …

misc(v2): make playground nicer

---

CHANGELOG-2.x.md
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-docs/src/__tests__/lastUpdate.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/metadata.test.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/lastUpdate.ts
packages/docusaurus-plugin-content-docs/src/metadata.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.js
website/docs/advanced-plugins.md
website/docs/migration-from-v1-to-v2.md
website/docusaurus.config.js

Implement the last update timestamp and author features from v1 reusing the code by @fiennyangeln. It was pretty to port over thanks to it being written as pure functions. Thanks Fienny!
I changed the timestamp data to pass in the number and only convert to locale display in the React component so that the date will be rendered according to the viewer's locale.
Yes

feat(v2): docs last update timestamp and author

---

packages/docusaurus-plugin-content-docs/src/lastUpdate.ts

Only show the Git requirement message for the docs last update feature once so that we don't spam users with `console.log()`s when they have many docs.
Yes
Mocked the condition to pass and see that we only print that message once.
```
> @ start /Users/yangshun/Developer/docusaurus_users/docusaurus
> yarn tsc && yarn start:v2
yarn run v1.16.0
$ lerna run tsc --no-private
lerna notice cli v3.14.1
lerna info Executing command in 6 packages: "yarn run tsc"
lerna info run Ran npm script 'tsc' in '@docusaurus/init' in 2.7s:
$ tsc
lerna info run Ran npm script 'tsc' in '@docusaurus/utils' in 2.7s:
$ tsc
lerna info run Ran npm script 'tsc' in '@docusaurus/plugin-content-blog' in 3.6s:
$ tsc
lerna info run Ran npm script 'tsc' in '@docusaurus/plugin-content-pages' in 3.6s:
$ tsc
lerna info run Ran …
```

fix(v2): only show the Git requirement message for the docs last update feature once

---

package.json
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-docs/src/__tests__/lastUpdate.test.ts
packages/docusaurus-plugin-content-docs/src/lastUpdate.ts
packages/docusaurus-plugin-content-docs/src/metadata.ts
yarn.lock

The last updated time took too long. It took ~250ms for one doc.
For docusaurus own docs, it took 7-8s while webpack compilation is only 9s
Improvement:
- Use cross-spawn (faster than shelljs)
- No need to make the last updated logic too complex (just find last commit like vuepress)
- Disable it in dev (use fake timestamp instead) since production is the one who really need this feature
yes
Much faster now ~100ms
Netlify still have last updated info

refactor(v2): simplify & faster last updated logic for docs

---

CHANGELOG-2.x.md
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/client/App.js
packages/docusaurus/src/server/config.ts
website/docs/docusaurus.config.js.md
website/docs/migration-from-v1-to-v2.md

Add `scripts` and `stylesheets` field to docusaurus.config. for v1 parity and enable user to use external resources script or stylesheets
yes
Add random scripts and stylesheets into config
```js
scripts: [
'https://docusaurus.io/slash.js',
{
src:
'https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.0/clipboard.min.js',
async: true,
},
],
stylesheets: [
'https://docusaurus.io/style.css',
{
href: 'http://css.link',
type: 'text/css',
},
],
```

feat(v2): add scripts and stylesheets field to config

---

website/docusaurus.config.js
website/src/pages/help.js

- Create a help page that's similar to v1's [Help page](https://docusaurus.io/en/help)
- So that users doing #1834 have a v2 implementation to refer to. Many FB websites have that Help page
Yes

feat(v2): add help page

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/TabItem/index.js
packages/docusaurus-theme-classic/src/theme/Tabs/index.js
website/docs/markdown-features.mdx
website/docs/migrating-from-v1-to-v2.md

Backward-compatibility for multi-language code support. I implemented a very low-level tabs component so that it can be reused for other scenarios (e.g. different OS platform).
It's quite verbose to use now but I think users can implement their own higher level abstractions that is customized for their use case (e.g. fixed languages).
In future I'm thinking we could create a wrapper provider that syncs the value across all instances of that kind of tabs and switching the value on one would switch for the other tabs. This is inspired by [Google Cloud docs](https://cloud.google.com/functions/docs/tutorials/http#functions-prepare-environment-nodejs).
Yes
Try it on https://deploy-preview-1836--docusaurus-2.netlify.com/docs/markdown-features#multi-language-support-code-blocks
(If this PR adds …

feat(v2): add tabs component for multi-language code

---

CHANGELOG-2.x.md
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/website/docs/lorem.md
packages/docusaurus-plugin-content-docs/src/__tests__/metadata.test.ts
packages/docusaurus-plugin-content-docs/src/metadata.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.js
website/docs/markdown-features.mdx

- add 'custom_edit_url' and 'hide_title' markdown header feature to achieve v1 full markdown header parity
- add documentation of it
- add new test
yes
- Newly added test works
- Try locally with new field and it works

feat(v2): add 'custom_edit_url' and 'hide_title' markdown header feature

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/DocItem/index.js
packages/docusaurus-theme-classic/src/theme/Layout/index.js
website/docs/introduction.md
website/docs/markdown-features.mdx
website/docs/migrating-from-v1-to-v2.md
website/docs/seo.md

Keywords seo in https://v2.docusaurus.io/docs/seo#keywords is not working
- Add more documentation on markdown frontmatter
P.S: I think we can remove https://v2.docusaurus.io/docs/seo docs in the future because it kinda duplicates with markdown-features
yes
```md
---
id: introduction
title: Introduction
description: Docusaurus was designed from the ground up to be easily installed and used to get your website up and running quickly.
keywords:
- test 
- wkwk
---
```

fix(v2): keywords frontmatter should work properly

---

CHANGELOG-2.x.md
packages/docusaurus-types/package.json
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/src/commands/external.ts
packages/docusaurus/src/commands/unknown.ts
packages/docusaurus/src/index.ts
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/plugins/index.ts
packages/docusaurus/src/server/plugins/init.ts
website/docs/lifecycle-apis.md

Register an extra command to enhance the CLI of docusaurus. `cli` is [commander](https://www.npmjs.com/package/commander) object..
Need this before working on docs versioning
yes
Modify any plugin and add an experimental command `roll` through `extendCli`
```js
extendCli(cli) {
cli
.command('roll')
.description('Roll a random number between 1 and 1000')
.action(() => {
console.log(Math.floor(Math.random() * 1000 + 1));
});
},
```

feat(v2): allow plugin to extendCli

---

CHANGELOG-2.x.md
package.json
packages/docusaurus-1.x/examples/basics/core/Footer.js
packages/docusaurus-1.x/examples/versions/pages/en/versions.js
packages/docusaurus-1.x/lib/core/BlogPost.js
packages/docusaurus-1.x/lib/core/Doc.js
packages/docusaurus-1.x/lib/core/Head.js
packages/docusaurus-1.x/lib/core/Site.js
packages/docusaurus-1.x/lib/core/anchors.js
packages/docusaurus-1.x/lib/core/nav/HeaderNav.js
packages/docusaurus-1.x/lib/server/feed.js
packages/docusaurus-1.x/lib/server/readMetadata.js
packages/docusaurus-1.x/lib/server/versionFallback.js
packages/docusaurus-init/bin/index.js
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/src/commands/swizzle.ts
packages/docusaurus/src/server/plugins/init.ts
website-1.x/core/Footer.js
website-1.x/pages/en/index.js
website-1.x/pages/en/versions.js
website/docs/migrating-from-v1-to-v2.md
yarn.lock

Swizzle should receive correct load context. Previously it was just passed `siteDir`.
Others
-upgrade typescript
-upgrade prettier
- update docs on migration
yes
- 

fix(v2): swizzle should receive correct load context

---

CHANGELOG-2.x.md
packages/docusaurus/src/commands/swizzle.ts

Minor bug found from https://v2.docusaurus.io/docs/search/#using-your-own-search and discord report
yes
Before
After

fix(v2): swizzle should be able to handle single js file

---

docs/getting-started-installation.md

Added a note that Docker files were not needed, and they may be deleted.
fix #1110 
Clarify that some files may be deleted.
Yes.

docs: document docker is optional

---

docs/api-site-config.md

Added a clarification to the cleanUrl property to set it false if the users intend to use docusaurus only offline.
close #1824 
Clarify specific use cases issues.
Yes.
Just text.

docs: add more info on cleanUrl siteconfig

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/Footer/index.js

If the target URL contains a slash at the end, the logo will not be displayed,
For example, the target URL is http://localhost:3000/blog/, then the logo URL will be http://localhost:3000/blog/img/logo.svg, not http://localhost:3000/img/logo.svg.
Yes.

fix(v2): fix link to logo in footer

---

CHANGELOG-2.x.md
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/bin/docusaurus.js
packages/docusaurus/src/commands/start.ts
website/docs/cli.md

When developing docs site (`docusaurus start` command), it can be very convenient to turn off auto page opening in a browser.
Yes.
- Run `yarn run start --disable-open-browser`

feat(v2): add ability disable to open page in browser when start command

---

website/docs/markdown-features.mdx

As discussed on Discord with @endiliey this PR:
Successfuly tested inside the `docusaurus` repository without problems. 
However, for new init-generated websites there is no `prismjs` directory inside `node_modules`, thus breaking this instruction. Reproduce by running:
```
npx @docusaurus/init@next init my-website classic 
ls my-website/node_modules/prismjs
```
**Question**: is this to be expected and if so, do we want users to `yarn install prismjs` themselves? If so, does that mean that "their" bundle size will increase significantly?

docs(v2): describe adding additional Prism syntax highlighting languages

---

website/docs/markdown-features.mdx

Also re-arranges the order the example so it matches the list with variables above it

docs(v2): clarify that front matter 'description' is used as a meta tag

---

CHANGELOG-2.x.md
packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/client/exports/ComponentCreator.js
packages/docusaurus/src/server/__tests__/__snapshots__/routes.test.ts.snap
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/routes.ts

Continuation from #1692. Use alias for generated metadata path in plugins
The benefit is pretty good, we shaved registry.js from 37kb to 29kb..
yes
- Locally navigate to all pages, still working fine
- Netlify
- CI

fix(v2): do not show plugin data path

---

docs/api-doc-markdown.md
docs/getting-started-installation.md
packages/docusaurus-1.x/lib/core/DocsLayout.js
packages/docusaurus-1.x/lib/server/readMetadata.js
website/docs/markdown-features.mdx

RN docs wanted to be able to explicitly specify the description in the front matter.
Yes
NA

feat(v1): allow specifying meta desc in front matter

---

docs/api-site-config.md

Added a piece of text from the set-up guide to enable Google Fonts.
Ensuring that users can find information on adding Google Fonts.
Yes
Fixes #1169

docs(v1): document how to include Google Fonts

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.js
packages/docusaurus-theme-classic/src/theme/Layout/index.js

It should be `<meta name="keywords">` instead of `<meta property="keywords">`.
Source: https://seo-hacker.com/what-are-meta-tags-and-why-are-they-important/
Yes

fix(v2): fix incorrect keywords meta tag

---

CHANGELOG-2.x.md
packages/docusaurus/package.json
packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/webpack/client.ts
packages/docusaurus/src/webpack/plugins/LogPlugin.js
packages/docusaurus/src/webpack/server.ts
yarn.lock

I don't want to maintain https://github.com/endiliey/webpack-nicelog#readme anymore. Its also based on webpackbar v2, now webpackbar is on v4 which is more stable and have new UI. 
Our current progress bar also has some weird problem due to webpack-dev-server showing additional info on startup (can't be disabled) which causes some UI glitch
See https://github.com/webpack/webpack-dev-server/pull/2235/files#r334830565 for more context
I think its better to move it to this repo so contributor can easily modify it.
In the future, we should try to use react-error-overlay for the error reporting like CRA
It also consumes less memory and is more accurate according to https://github.com/nuxt/webpackbar/releases/tag/v3.0.0
yes
New UI
Dev
Build

feat(v2): new ui progress bar

---

CHANGELOG-2.x.md
packages/docusaurus/src/webpack/base.ts
packages/docusaurus/src/webpack/plugins/LogPlugin.js
packages/docusaurus/src/webpack/utils.ts
website/docs/migrating-from-v1-to-v2.md
yarn.lock

Previously, there is an edge case bug in which if website path contains `docusaurus` in its name, all the node_modules js file will be transpiled.
Example: /mnt/c/Users/endij/Desktop/Linux/test/docusaurus_crash/website/node_modules/@docusaurus/core/node_modules/core-js/modules/_descriptors.js will match the regex
Due to babel smart polyfilling, transpiling files like above that uses commonjs will cause  https://github.com/webpack/webpack/issues/4039#issuecomment-477779322
```TypeError: Cannot assign to read only property 'exports' of object '#<Object>' ```
yes
Using regextester. Only docusaurus npm package that are transpiled.
Manually patch new inited site with `docusaurus` on its name

fix(v2): fix babel transpilation include/exclude logic

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/DocPage/index.js

Docusaurus may not have a sidebar, but in the second version an empty container is now displayed, it needs to be deleted (it creates an additional empty space).
Yes.
| ![image](https://user-images.githubusercontent.com/4408379/67349023-63f91300-f54f-11e9-8cf3-4389e2e448a8.png)| ![image](https://user-images.githubusercontent.com/4408379/67349032-69565d80-f54f-11e9-8351-40102da7e11b.png) |

fix(v2): remove empty doc sidebar container

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

Currently, there is a small bug on the desktop - when you put the focus on search input, and after you remove it (touch on the outside of search area), this focus will remain as it was - this is incorrect behavior.
Yes
| ![AwesomeScreenshot-2019-10-23-1571823548390](https://user-images.githubusercontent.com/4408379/67380971-d25fc480-f593-11e9-89a5-566d17c86f30.gif) | ![AwesomeScreenshot-2019-10-23-1571823268706](https://user-images.githubusercontent.com/4408379/67380979-d855a580-f593-11e9-967c-862a37178ef4.gif)|

fix(v2): fix search input blur on desktop

---

CHANGELOG-2.x.md
packages/docusaurus/src/webpack/utils.ts

By default postcss preset env use stage 2, i think its better to use stage 3 like CRA because stage 2 CSS is considered relatively unstable and subject to change while Stage 3 features will likely become a standard.
https://github.com/facebook/create-react-app/blob/9788522d8747b506f469d2fcb6ff696332271ab9/packages/react-scripts/config/webpack.config.js#L119
yes
- Manually navigate locally, page seems to be OK.
P.S Feel free to close this PR if we do want stage 2 features

feat(v2): postcss should only use stage 3 features instead of stage 2

---

CHANGELOG-2.x.md
packages/docusaurus/src/webpack/base.ts

Disable adding hashes to the generated class names of CSS modules in dev mode. Generating unique identifiers takes some time, which can be saved since including paths to files in class names is enough to avoid collisions.
Recommended by https://github.com/webpack-contrib/css-loader#localidentname
yes
Verify locally in dev

perf(v2): disable hash for css modules localident in dev

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/DocPage/index.js
packages/docusaurus-theme-classic/src/theme/Layout/index.js

Previously, the sticky stuff on the docs page might not play well with a Footer underneath so we chose to leave it out. But since #1855, it is now possible to have consistent look like v1.
See https://github.com/facebook/docusaurus/issues/1598
yes
[Imgur](https://imgur.com/y7tU7F8)
[Imgur](https://imgur.com/ypMb6QO)

feat(v2): display footer in docs page for consistency

---

website/docs/docusaurus-core.md

#1640 
yes
- Netlify
<a href="https://ibb.co/n0xk8nH"><img src="https://i.ibb.co/26GKYsD/aa.png" alt="aa" border="0"></a>

docs(v2): add docs on useful client api

---

website/docs/configuration.md
website/docs/docusaurus.config.js.md
website/docs/installation.md

Update docs to clarify certain stuff especially on configuration. A lot of people is confused on `baseUrl` and `url`. 
Made some example simpler
yes
- N/A

docs(v2): update config docs

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js

It happens that there is a category in the sidebar, but it does not have items (i.e., empty array). You can of course not skip such inputs and give the user an error (?), but this is not the best option, because in this way the user probably wants to hide the display of such a category (do not ask me why ¯\_(ツ)_/¯).
Yes, although the user can simply comment out such categories... In any case, this is the edge case that needs to be handled correctly - do not show categories like these. 
> For the record, in the first version, categories with empty items simply did not shown, so seems fair to bring back this behavior to the second version (see Test plan).
Yes
Let say we have this `sidebars.js` file: 
```diff
docs: {
Docusaurus: [
'introduction',
/*'motivation', */ …
```

fix(v2): do not show category with empty items

---

CHANGELOG-2.x.md
packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus/src/client/exports/ComponentCreator.js
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/routes.ts
packages/docusaurus/src/webpack/base.ts

I think it's quite straightforward that **SPEED** is everything in web development. Saving 0.3s or even 0.5s in page loading is **HUGE**.
This PR attempts to reduce our bundle size by changing the registry.js structure a little bit (using array instead of object) and using short alphanumeric id for our webpack chunk name in production.
So in development
```js
// registry.js
export default {
'component---site-src-pages-help-js-7-e-3-222': [() => import(/* webpackChunkName: 'component---site-src-pages-help-js-7-e-3-222' */ "@site/src/pages/help.js"), "@site/src/pages/help.js", require.resolveWeak("@site/src/pages/help.js")],
'component---site-src-pages-index-jsc-4-f-f99': [() => import(/* webpackChunkName: 'component---site-src-pages-index-jsc-4-f-f99' */ "@site/src/pages/index.js"), …
```

perf(v2): significantly reduce bundle size & initial html payload

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/hooks/theme.js
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus-theme-classic/src/theme/hooks/theme.js

Refactor dark toggle logic into a hook
Yes
test on preview that:
- dark toggle still works
- sets theme in local storage when toggling
- navigating and refreshing page picks up the theme properly

refactor(v2): refactor dark toggle into a hook

---

CHANGELOG-2.x.md
packages/docusaurus/package.json
packages/docusaurus/src/webpack/server.ts
yarn.lock

Hopefully this is the last perf optimization this month that i did before working on versioning plugin.
With this PR, docusaurus should be able to handle at least > 1,000 markdown files without memory allocation error (tested)
Anyway, this PR is very simple, upgrading static site generator webpack plugin to use my forked version https://github.com/endiliey/static-site-generator-webpack-plugin with improved test coverage (100% compared to original 90%+) and more up to date dependencies + performance. I can optimize more using jest-worker but thats kinda overkill now.
yes
Chrome dev tool + Nodejs debugger
Before
<a href="https://ibb.co/5vytgjc"><img src="https://i.ibb.co/tctkT2C/good.png" alt="good" border="0"></a>
After
<a href="https://ibb.co/sQg9gL4"><img …

perf(v2): reduce memory usage consumption

---

packages/docusaurus-1.x/lib/static/css/main.css

when element in side nav is hovered over the color changes.

misc(v1): use primary color for hovered items in table of contents

---

packages/docusaurus-1.x/lib/static/css/main.css

Resolves #254 
The thing was that the search input was sized differently on Mobile Safari / Chrome browsers which caused in a misalignment like described in the #254 bug report. I've unified the height of the input and aligned it properly, so it looks good on Chrome/Firefox as well as on Safari / Mobile Safari.
Yes.
I've tested locally on given browsers:

fix(v1): mobile safari search input misalignment in header

---

CHANGELOG-2.x.md
packages/docusaurus/src/commands/deploy.ts

Docusaurus 1.X treats any non-'true' value to be false, but Docusaurus 2.X currently treats any non-empty string to be truthy here. This change should unbreak projects that migrate from V1 to V2 with `USE_SSH=false` environment variables.
Yep!
eyes

misc(v2): v1 backward compatibility for USE_SSH env var

---

CHANGELOG-2.x.md
packages/docusaurus-init/templates/classic/docs/doc1.md
packages/docusaurus-init/templates/classic/src/css/custom.css
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js
website/docs/advanced-themes.md
website/docs/blog.md
website/docs/configuration.md
website/docs/deployment.md
website/docs/docusaurus-core.md
website/docs/lifecycle-apis.md
website/docs/markdown-features.mdx
website/docs/migrating-from-v1-to-v2.md
website/docs/presets.md
website/docs/search.md
website/docs/sidebar.md
website/docs/styling-layout.md
website/docs/using-plugins.md
website/docs/using-themes.md
website/src/css/custom.css

- Finish #1860 by @lex111 via adding docs and using it within D2 docs
- Also changed some of our code blocks to use the line highlighting feature
Yes
#1860

docs(v2): code block line highlighting

---

CHANGELOG-2.x.md
packages/docusaurus/src/webpack/base.ts

- Prioritize `@docusaurus/core` dependencies/ node_modules over user's node_modules. This fix a bug whereby if user has core-js@3 on its own node_modules but docusaurus depends on core-js@2, we previously encounter `Module not found: core-js/modules/xxxx` (because core-js@3 doesn't have that).
Another example is if user installed webpack@3 but docusaurus depends on webpack@4.
This is currently happening to docsearch. cc @s-pace
yes
Using newly init website, try to manually add core-js@3 on the site
Before
<a href="https://ibb.co/Mc2Sgwy"><img src="https://i.ibb.co/48mtFvw/core-js-wrong.png" alt="core-js-wrong" border="0"></a>
After
<a href="https://ibb.co/QjXjpV6"><img src="https://i.ibb.co/M595ZHR/prioritize-own-core-js.png" alt="prioritize-own-core-js" border="0"></a>

fix(v2): webpack modules resolve should prioritize @docusaurus/core own deps

---

CHANGELOG-2.x.md
packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-blog/src/types.ts
packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.js

Simplify blog metadata. Previously, accessing `/blog/post-xxx` will request for next and prev blog post metadata too aside from target post metadata. We should only request target post metadata
Since we only need `title` and `permalink`, why not just collocate it in current metadata instead of fetching whole next and prev metadata. Less request -> better. This also makes our routesChunkNames smaller. I saved ~0.3kb on main bundle size for our v2 website lol.
yes
- Updated blog tests pass
- Netlify, going to blogpost, prev and next button still working fine
- Check all blog functionality is OK

feat(v2): simplify blog metadata to minimize number of request

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/Footer/index.js

Often, the GitHub stars button is added to the footer, to do this in v2 you need to swizzle the Footer component, just to insert such a button. It seems to me that you can simplify this action by simply giving the opportunity to provide custom HTML for the link (see Test plan).
Yes.
In file `docusaurus.config.js`:
```js
// ...
scripts: ['https://buttons.github.io/buttons.js'],
// ...
footer: {
links: {
{
title: 'Social',
items: [
// ...
{
html:
'<a class="github-button" href="https://github.com/facebook/docusaurus" data-icon="octicon-star" data-show-count="true" aria-label="Star facebook/docusaurus on GitHub">Star</a>',
},
],
},    
}
}
//...
```
As result:
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and …

feat(v2): add ability to set custom HTML in footer items

---

website-1.x/data/users.js

The Docs URL has been changed at Configcat.
yepp
Just click the link within users page under ConfigCat.

docs: updating configcat user link

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
website/docs/search.md
website/docs/theme-classic.md
website/sidebars.js

Found a bug on our navbar code while documenting. -Previously, if `themeConfig.algolia` is not defined, the custom searchbar won't appear.
Also added WIP documentation on theme-classic configuration. Better than nothing.  cc @wgao19 
yes
1. Swizzle searchbar
2. Remove themeconfig.algolia
3. Custom searchbar does appear

fix(v2): custom searchbar should appear even if themeconfig.algolia is undefined

---

CHANGELOG-2.x.md
website/docs/docusaurus-core.md

Document @docusaurus/router `Redirect` component
yes
Netlify

docs(v2): Redirect component for easy redirect

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus/src/webpack/base.ts

Fix regression from #1907  
Accessing https://v2.docusaurus.io/docs/introduction won't make the current active navbar item to be highlighted
<a href="https://ibb.co/FBwS3s1"><img src="https://i.ibb.co/tbs7KZ6/image.png" alt="image" border="0"></a>
Instead of using `module.paths`, we should use just the `@docusaurus/core` hoisted node_modules.
Why ?
Because module.paths traverse up until the root, and this can cause picking the wrong dependencies.
Node_modules resolution is hard !!
Anyway, currently our modules resolve is this
```js
modules: [
// @docusaurus/core own node_modules
path.resolve(__dirname, '..', '..', 'node_modules'),
// two lines below is same as CRA, razzle, etc
'node_modules',
path.resolve(fs.realpathSync(process.cwd()), 'node_modules'),
],
```
yes
- NavLink is highlighted …

fix(v2): regression from prioritizing core node_modules logic

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/Heading/index.js

Fix MDX `@theme/Heading` component. If there is no id, it should not create anchor link.
yes
Before
After

fix(v2): @theme/heading should not create anchor if id is not defined

---

website/docs/configuration.md

This PR addresses #1640:  "Getting Started / Configurations → Themes, plugins, and presets configurations"
Yes
N/A
#1640

docs(v2): theme, plugin, and preset config

---

scripts/prerelease.sh

Using `/usr/bin/env bash` instead of `/usr/bin/bash` increases portability of the script, see e.g. [here](https://stackoverflow.com/questions/2429511/why-do-people-write-the-usr-bin-env-python-shebang-on-the-first-line-of-a-pyt) and [here](https://stackoverflow.com/questions/1352922/why-is-usr-bin-env-python-supposedly-more-correct-than-just-usr-bin-pyt) and probably countles more.
Yes.
N/A
N/A
Please review.

misc: use /usr/bin/env bash to increase portability

---

packages/docusaurus-theme-classic/src/theme/Footer/index.js

My fault, forgot to add this prop :man_facepalming: . _Since the associated change has not been released yet, there is no need to document it in the changelog_.
Yes
React warnings removed.

fix(v2): add missing key prop in footer items with HTML

---

website/src/components/BrowserWindow/styles.module.css

Probably some custom properties have been removed due to the Infima update, so the browser window lost the background on website of v2.
Yes
| ![image](https://user-images.githubusercontent.com/4408379/68094459-9e4ca380-feb1-11e9-8dca-2c833f7ade54.png) |  ![image](https://user-images.githubusercontent.com/4408379/68094458-9bea4980-feb1-11e9-8c45-ea22d5dac55e.png) |

fix(v2): fix browser window background

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.js

It was not possible to have tabs containing only one tab item, so the code below crashed
I want to have consistent code blocks around my docs (so that single-file code snippets have the same filename title as multi-file snippets).
Yes.
1) Build
2) Create a new `md` file
3) Use `Tabs` with single child.
```
<Tabs
defaultValue="SomeFile.js"
values={[
{ label: "SomeFile.js", value: "SomeFile.js" }
]}
>
<TabItem value="SomeFile.js">
Tab content
</TabItem>
</Tabs>
```

fix(v2): allows to create tabs with only one item

---

packages/docusaurus-init/templates/classic/package.json

As mentioned earlier in one of the migration, this script is not needed, so it is best to remove it.
Yes

fix(v2): remove redundant npm script in classic template

---

CHANGELOG-2.x.md
package.json
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus/src/commands/start.ts
yarn.lock

Chokidar uses glob pattern, and glob pattern must not contain window backslashes
yes
- Newly added tests pass.

fix(v2): fix chokidar/watcher does not trigger reload on windows

---

CHANGELOG-2.x.md
packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css

Hash link is cut off especially on left side. Not sure what's the best padding value should be. Or should we use margin instead ? Do we need to pad right too ?
yes
Mobile
Before vs After
Desktop
Before
After

fix(v2): hash-link should not be cut-off in doc container

---

CHANGELOG-2.x.md
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus/src/server/__tests__/__snapshots__/routes.test.ts.snap
packages/docusaurus/src/server/__tests__/routes.test.ts
packages/docusaurus/src/server/plugins/index.ts

Ensure routes config generation to be more consistent in ordering. Nested routes should have params and be placed last in routes.js. 
Consider a scenario of having a `src/pages/docs.js`. This means
Before
```js
// routes.js
export default [
{
path: "/docs",
component: ComponentCreator("/docs")
},
{
path: "/docs",
component: ComponentCreator("/docs"),
routes: [
{
path: "/docs/advanced-themes",
component: ComponentCreator("/docs/advanced-themes"),
exact: true
},
{
path: "/docs/advanced-plugins",
component: ComponentCreator("/docs/advanced-plugins"),
exact: true
},
]
},
{
path: "*",
component: ComponentCreator("*")
}
];
```
Component creator will be confused because `/docs` can resolve to `DocPage` and `src/pages/docs.js`. We should be using a `:` params instead as suggested in …

fix(v2): more consistent route config generation

---

CHANGELOG-2.x.md
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/start.ts

- Fix babel/env not picking the correct browserslist configuration during development. When running `docusaurus start`, process.env.NODE_ENV is now consistently set to `development`.
This should remove unnecessary transform in dev, which means faster dev :)
This should also fix some edge cases behavior reported on Discord if user set their own NODE_ENV environment variable to production when running `docusaurus start` (they shouldn't do that).
yes
Set babel/env options `debug` to true
Before. It uses production browserslist instead
After
PS: BABEL_ENV is also set. See https://github.com/facebook/create-react-app/pull/2382/

fix(v2): babel/env should pick correct browserslist config in dev

---

CHANGELOG-2.x.md
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/webpack/utils.ts

More efficient hot reload & consistent generated file
Note that I set `clientLogLevel` to `info` in devserver config.
Previously, if we start development server and go to home page. We can go to `src/pages/index.js` and just 'save' without changing anything
GIF Preview
Note that there are several files that got disposed by WDS. This is because our generated files (although we have caching in https://github.com/facebook/docusaurus/blob/87f864e5bafb25debc9aafbd16cb51e051ec7e4b/packages/docusaurus-utils/src/index.ts#L15-L32), is re-written due to different object keys ordering.
Explanation
```js
{
'a': 'foo',
'b': 'bar',
}
```
Is considered different from
```js
{
'b': 'bar',
'a': 'foo',
}
```
The generated files can be different because of async nature and keys ordering. We should always …

perf/fix(v2): more efficient hot reload & consistent filegen

---

CHANGELOG-2.x.md
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-docs/src/__tests__/lastUpdate.test.ts
packages/docusaurus-plugin-content-docs/src/lastUpdate.ts
packages/docusaurus-plugin-content-docs/src/metadata.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus/src/server/routes.ts
yarn.lock

- Skip fileHash caching on production calculation to improve build performance. The runtime cache is only useful in development.
- Obtain git timestamp for `showLastUpdateAuthor`/ `showLastUpdateTime` asynchronously instead of synchronously. 
Not sure why we did it synchronously previously, but since we are using child_process under the hood to actually do the git call, its better in async
P.S: We also use `execa` instead of `cross-spawn` because https://github.com/sindresorhus/execa has more stars (2.7k vs 600). It also strips the final newline from the output so you don't have to do stdout.trim(), Cleans up spawned processes when the parent process dies and have more descriptive errors.
yes
With fixtures of 1,026 docs and several runs
**Before -~89s**. 
**After ~~46s**
The git call is …

perf(v2): skip runtime fileHash cache in prod & get timestamp asynchronously

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js
website/docs/theme-classic.md

See https://github.com/T-Regx/T-Regx.github.io/pull/14#issuecomment-552154338
Yes
When `themeConfig.disableDarkMode = false`, dark mode toggle will not be rendered.

feat(v2): add ability hide dark mode toggle

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.js

TOC hooks is called inside each nested children previously. See gif below on how many `getActiveHeader` which leads to document query calls.
See recursive headings
https://github.com/facebook/docusaurus/blob/3be2e8654620c5d9d1b1f02c480966bcb9559096/packages/docusaurus-theme-classic/src/theme/DocItem/index.js#L22-L38
We should also do better in future by doing some throttling, but that's out of scope of this PR. 
We can also split RightTOC component as another `@theme/RightTOC` component so its swizzle-able if needed (but better in future PR so that lerna autogenerated changelog can pick it better)
yes
- Netlify
right toc still highlighted on scroll
- Less number of getActiveHeader calls

fix(v2): useTOC hooks should not be called in each nested children

---

packages/docusaurus-plugin-content-docs/src/__tests__/metadata.test.ts
packages/docusaurus-plugin-content-docs/src/metadata.ts
website/docs/advanced-plugins.md
website/docs/migrating-from-v1-to-v2.md
website/docusaurus.config.js

In v1, `editUrl` is pointing to `docsDir` and its always pointing to `next` for the edit.
Try https://docusaurus.io/docs/en/1.13.0/installation, notice the edit is for `next` docs only.
For example, if I renamed docs folder from `docs` to `document`. Before this PR i have to change the docs plugin path options from `docs` to `document` AND I HAVE to update my `editUrl` from https://github.com/facebook/docusaurus/edit/master/website/docs/ to https://github.com/facebook/docusaurus/edit/master/website/document/ as well. Double work.
After this PR, I only need to do it once
Since we can always resolve it based from website dir. Since we already have lot of aliasing through `@site`, it makes more sense to point it to `website` instead of `docsDir`.
yes
- Updated test passes
- Netlify editUrl …

breaking(v2): editUrl should point to website instead of docsDir

---

packages/docusaurus-theme-classic/src/theme/Layout/index.js

These two meta tags are already defined in the template:
https://github.com/facebook/docusaurus/blob/b027db1b346d928255d3f0205059f9cab10417b0/packages/docusaurus/src/client/templates/ssr.html.template.js#L12-L13
Yes
See build.

fix(v2): remove duplicate meta tags

---

packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.js
packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.js

If there is no previous or next post, then extra space appears due to vertical margins. The same goes for the container with tags and read more link.
Yes
Extra spaces when empty content:
No extra spaces:

fix(v2): remove empty containers when no data in blog pages

---

packages/docusaurus-theme-classic/src/theme/Footer/index.js
packages/docusaurus-theme-classic/src/theme/Footer/styles.module.css
website/docs/migrating-from-v1-to-v2.md

Often the logo in the footer points to the vendor of this site, so you need the ability to set a link. An example is React Native - https://facebook.github.io/react-native/
This PR implements the same behavior with opacity prop.
Yes
Set the external link in `themeConfig.footer.logo.href` and see that the logo has become clickable.

feat(v2): add ability specify link in footer logo

---

packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.js
packages/docusaurus-theme-classic/src/theme/BlogPostItem/styles.module.css

Just improving semantics, without changing UI.
Yes
See HTML code.

fix(v2): use tag time for showing post item date

---

packages/docusaurus-plugin-content-blog/src/blogUtils.ts

Simplify blog truncate function. This should be faster because we're passing `limit` to split function and less code to execute lol
yes
Edit blog file
With truncate marker, read more still showed
Without truncate marker, show all

refactor(v2): simplify blog truncate function

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js

Currently, because that all props are passed to `NavLink`, navigation links have two invalid attributes - `label` and `position`.
Yes
Before:
```html
<a class="navbar__item navbar__link" label="Docs" position="left" href="/docs/introduction">Docs</a>
```
After:
```html
<a class="navbar__item navbar__link" href="/docs/introduction">Docs</a>
```

fix(v2): remove invalid attributes of nav links

---

packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.js

Screen readers need a more descriptive link name.
Yes

feat(v2): add aria-label to read more links for a11y

---

website/docs/blog.md

I wanted to pick a simple change before adding more documentation. 
As suggested by @endiliey on discord
Yes I have
I made a document change and tested it by running the site locally. Also run prettier

docs(v2): Add section to blog document about feed location

---

packages/docusaurus/src/client/PendingNavigation.js
packages/docusaurus/src/client/docusaurus.js

Smaller bundle size while achieving same functionality. Avoiding cool syntax in main bundle like es6.string.includes (use indexOf instead) and es6.regexp.replace etc. This is because core-js and babel will try to polyfill.
yes
**Before 228.21kb**
**After 221.36kb**

perf(v2): reduce main bundle size ~7kbs by using es5 if possible

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.js

In terms of _semantics_, the `header` tag should be inside the `article` tag, rather not outside it.
Yes
See HTML markup, no UI changes.

fix(v2): move header inside article tag in doc page

---

packages/docusaurus-theme-classic/src/theme/Layout/index.js
packages/docusaurus-theme-classic/src/theme/Layout/styles.css

Now I just noticed that the `main` tag is already used in the [template](https://github.com/facebook/docusaurus/blob/7714afb00f837ebead0328526779bc20f3b6885f/packages/docusaurus-theme-classic/src/theme/DocPage/index.js), so it makes sense to replace it with a regular div.
Yes
See HTML markup, no changes UI.

fix(v2): use regular div instead of main tag for wrapper layout page

---

packages/docusaurus-theme-classic/src/theme/Footer/index.js

A continuation of #1974. This is relevant  only for external links.
Yes
Before:
```html
<a class="footer__link-item" label="Stack Overflow" href="https://stackoverflow.com/questions/tagged/docusaurus" target="_blank" rel="noopener noreferrer">Stack Overflow</a>
```
After (without `label`):
```html
<a class="footer__link-item" target="_blank" rel="noopener noreferrer" href="https://stackoverflow.com/questions/tagged/docusaurus">Stack Overflow</a>
```

fix(v2): remove invalid label attribute of footer links

---

packages/docusaurus-init/templates/classic/docusaurus.config.js
website/docusaurus.config.js

The main Docusaurus site as well as the template should demonstrate the basic functionality, so I consider it  rationale to add a recently added link field for the footer.
Yes
See footer.

feat(v2): add FB link to footer

---

website/src/pages/index.js
website/src/pages/styles.module.css

The `frameborder` and `scrolling` attributes on the `iframe` element is obsolete. Use CSS instead.
Yes
No UI changes.

fix(v2): remove obsolete iframe attributes

---

packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.js

A continuation of #1962. 
The `h1` tag should always be one on a page, so only `h2` should be used in posts lists.
Yes
See HTML markup, no UI changes.

refactor(v2): replace h1 tag with h2 in blog list pages

---

website/docs/blog.md
website/docs/markdown-features.mdx
website/docs/sidebar.md

Some blocks of code with YML are marked as Markdown-code, which is incorrect and needs to be fixed.
Yes

docs(v2): fix syntax highlighting for YML code blocks

---

packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/sidebars/sidebars-first-level-not-category.js
packages/docusaurus-plugin-content-docs/src/__tests__/sidebars.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars.ts

Close #1993
See that issue for more context
yes
- Newly added test passes

fix(v2): throw error if first level item of a sidebar is not category

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js

Currently, when you click on a category in the browser address bar, two characters "#!" (known as the hashbang) are added to the end of the URL. This is somewhat annoying and clogs the browser history.
Yes
1. Click on a category to expand it.
1. Look at the browser bar, the URL should **not** change

fix(v2): remove hashbang when click on category

---

packages/docusaurus-mdx-loader/src/remark/rightToc/__tests__/__snapshots__/index.test.js.snap
packages/docusaurus-mdx-loader/src/remark/rightToc/__tests__/fixtures/non-text-content.mdx
packages/docusaurus-mdx-loader/src/remark/rightToc/__tests__/index.test.js
packages/docusaurus-mdx-loader/src/remark/rightToc/search.js
packages/docusaurus-theme-classic/src/theme/DocItem/index.js

TOC always render as string. Never putting the html markup.
Previously, only the textual content of headings was used to generate the entries in the Table of Contents. This lead to a bug (or feature?) where HTML in headings made entries in the TOC appear with literal HTML.
Example:
```md
```
Will be rendered as literal
Other example is below. See that the right toc does not render the emphasis, etc
mdast has a concept of static phrasing content, which includes all the things that can appear in links. Instead of using just the textual content of a heading, this commit introduces a new behaviour where any static phrasing content, such as HTML, inline code, and emphasis, are copied over into the Table of Contents.
See test plan
yes
After. See that its rendered correctly now
- Newly added …

fix(v2): static phrasing content should be rendered correctly in TOC

---

packages/docusaurus-theme-classic/src/theme/Heading/index.js

> ARIA hidden element must not contain focusable elements
Stop hidden anchors from being keyboard accessible, because now control via Tab is not obvious, since the anchors are hidden.
Yes
Try switching to elements using Tab key, anchors should not get focus.

fix(v2): remove accessible anchors  via keyboard

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/styles.css

Minor UI corrections in the search bar - remove underline on hover, uniform background for the columns (always white), fix overlapping dropdown menu on search input in mobile. See test plan for details.
Yes
| ![image](https://user-images.githubusercontent.com/4408379/68995892-e9988600-08a3-11ea-877c-7c6b655fd468.png) | ![image](https://user-images.githubusercontent.com/4408379/68995867-9d4d4600-08a3-11ea-805a-c08749b2445b.png) |
| ![image](https://user-images.githubusercontent.com/4408379/68995876-b3f39d00-08a3-11ea-92b1-844d00f115e7.png) | ![image](https://user-images.githubusercontent.com/4408379/68995864-94f50b00-08a3-11ea-9bbe-37278552faca.png) |

fix(v2): improve UI of search

---

website/src/components/BrowserWindow/styles.module.css

On small screens (<360px), the browser window menu icon goes beyond the parent container.
Yes
| ![image](https://user-images.githubusercontent.com/4408379/68998113-0e4e2700-08bf-11ea-8adf-4dc26b77a540.png) | ![image](https://user-images.githubusercontent.com/4408379/68998094-d810a780-08be-11ea-8db8-74657ffad81c.png) |

fix(v2): fix browser window menu icon on smaller screen

---

packages/docusaurus-theme-classic/src/theme/Layout/styles.css

Currently, the same problem is observed as in [v1](https://github.com/facebook/docusaurus/pull/1869
) (take this opportunity, look at that PR and merge it please!). If during the search we click the page itself (i.e. first-level heading or h1), then we get a URL of the form https://v2.docusaurus.io/docs/introduction/#__docusaurus and the heading is incorrectly positioned (see Plan)
Yes
| ![image](https://user-images.githubusercontent.com/4408379/69006033-d4226b00-093a-11ea-8c69-232192859da1.png) | ![image](https://user-images.githubusercontent.com/4408379/69006040-e43a4a80-093a-11ea-874f-3431efba509d.png) |

fix(v2): adjust first-level heading offset

---

packages/docusaurus-theme-classic/src/theme/BlogListPage/index.js
packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.js
packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.js

Fully semantic layout of blog pages. Search robots will be satisfied :smiley: 
Yes
See HTML markup, no UI changes.

refactor(v2): improve semantic markup of blog

---

packages/docusaurus/src/webpack/base.ts

Close #2006 
See issue for reasoning
yes
- yarn build, only one css file is created
- netlify ???
- no css break on local build
caveat:
- dont know how big is our css 😭

feat(v2): only create one css file to avoid code-split css loading problem

---

website/docusaurus.config.js
website/src/pages/index.js
website/src/pages/styles.module.css

Fixes https://github.com/facebook/docusaurus/issues/1972. I think we need to separate the landing page's actual tagline from an SEO-friendly version. The page's tagline is meant for humans to read while the SEO-friendly version is for crawlers, and should be more explicit.
Yes
Netlify

misc(v2): branding update

---

website/docs/cli.md
website/docs/design-principles.md
website/docs/introduction.md
website/docs/lifecycle-apis.md
website/docs/styling-layout.md
website/docs/theme-classic.md

Misc updates I saw and fixed.
Yes
Netlify.

docs(v2): misc updates

---

packages/docusaurus-1.x/lib/core/Doc.js
packages/docusaurus-1.x/lib/static/css/main.css

When Algolia DocSearch query finds a match for a page's title, it attempts to generate
a permalink. Because the page title element (`h1`) does not have an `id`, Algolia
generates uses the `id` from closes parent element. Because of this, the page title
scrolls to a position that is slightly overlayed by the fixed top navigation bar.
This fix sets an `id` for the page title so that the search result is able to generate
a more accurate permalink.
closes #1828 
This is a wide-spread bug that is affecting everyone and the required change is relatively small.
Yes
The original issue is caused by algolia attempting to auto generate a permalink for the page title that does not actually have a specific `id`. That's why it's not possible to test this change locally and verify the fix. But, based on …

fix(v1): fix page title render issue when referred by search result

---

packages/docusaurus-plugin-content-docs/src/metadata.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.js
packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css
website/docs/markdown-features.mdx

I want to be able to hide the table of contents for Infima docs where the main content width is not wide enough. Example: https://facebookincubator.github.io/infima/docs/layout/grid
Yes

feat(v2): allow hiding docs table of contents

---

packages/docusaurus-init/templates/classic/blog/2019-05-28-hola.md
packages/docusaurus-init/templates/classic/blog/2019-05-29-hello-world.md
packages/docusaurus-init/templates/classic/blog/2019-05-30-welcome.md
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.js
website-1.x/blog/2017-12-14-introducing-docusaurus.md
website-1.x/blog/2018-04-30-How-I-Converted-Profilo-To-Docusaurus.md
website-1.x/blog/2018-12-14-Happy-First-Birthday-Slash.md
website/docs/blog.md
website/docs/migrating-from-v1-to-v2.md

Standardize our front matter. Front matter should be snake_case 🐍. I'm preserving the camelCase for legacy reasons, so users using the camelCase will still work.
Also, I'm removing two following fields:
- `authorFBID` - This is really unnecessary and we don't need it. People should just provide the FB Graph API image URL if they wanted a FB profile picture
- `authorTwitter`- This was never ported to D2, but is still in the template and examples
I'm not updating the docs and template yet because it should be done only after alpha.35 is published or else there will be a mismatch between the doc and latest version.
Yes
Blog loads.

misc(v2): change blog front matter to snake_case

---

packages/docusaurus/src/client/templates/index.html.template.ejs
packages/docusaurus/src/client/templates/ssr.html.template.js

Add meta generator tag according to HTML5 spec like v1
https://html.spec.whatwg.org/multipage/semantics.html#standard-metadata-names
Benefits:
- Wappalyzer chrome extension can detect us 
- You can search for popular website created with docusaurus easily
eg: https://publicwww.com/websites/%22%3Cmeta+name%3Dgenerator+content%3DDocusaurus%3E%22/
yes

feat(v2): add meta generator docusaurus

---

packages/docusaurus-1.x/lib/server/server.js

Close #2016 
yes
Follow instruction in #2016

fix(v1): docusaurus-start should work even if path contain 'pages' word

---

packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css

CSS Tweaks to be consistent like v1. see Test Plan. Feel free to close if its not a good idea
yes
Before
After

feat(v2): style right sidebar scrollbar when overflow

---

docs/getting-started-installation.md
packages/docusaurus-1.x/lib/core/__tests__/toc.test.js
packages/docusaurus-1.x/lib/core/toc.js
packages/docusaurus-1.x/package.json
yarn.lock

Close #2021 
Sort of continuation from #2019 but this is dealing with consistent rendered content. That PR is consistent hash-link and slug
yes
- Added test passes
- 
```md
```

fix(v1): markdown content and toc should render the same

---

packages/docusaurus-1.x/lib/core/DocsLayout.js
packages/docusaurus-1.x/lib/static/css/main.css

facebook/docusaurus#1869 added negative margins to all headings including those on the blog and it made the "Read more" links hidden behind the heading. Let's only target the headings on the docs and not the blog.
Yes
Can click on blog.

fix(v1): apply negative margin to docs heading only

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css

This is continuation from #2017 but for left sidebar. Feel free to close if you think it's not looking nice
yes
**Before**
**After**

feat(v2): style sidebar on overflow

---

packages/docusaurus/package.json
packages/docusaurus/src/webpack/utils.ts
yarn.lock

Utilize https://babeljs.io/docs/en/babel-plugin-transform-runtime/
WHY ? 
> Babel uses very small helpers for common functions such as _extend. By default this will be added to every file that requires it. This duplication is sometimes unnecessary, especially when your application is spread out over multiple files.
> This is where the @babel/plugin-transform-runtime plugin comes in: all of the helpers will reference the module @babel/runtime to avoid duplication across your compiled output. The runtime will be compiled into your build.
See https://babeljs.io/docs/en/babel-plugin-transform-runtime/#why for more details.
Also checked CRA, Razzle and Gatsby. They are using it too.
See test plan for benefits
yes
**Before**
Parsed Size: All 1.28mb main 221.62kb
Gzipped Size: All 409.58kb main …

perf(v2): use @babel/runtime plugin to reduce codesize

---

packages/docusaurus/src/client/serverEntry.js
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/webpack/client.ts
packages/docusaurus/src/webpack/plugins/ChunkManifestPlugin.js
packages/docusaurus/src/webpack/server.ts

chunk-map and client-manifest.json is actually not useful in build folder. We shouldn't put it in build folder, but put it in generated folder instead.
The benefit of this is that less space is used for build artifacts. (eg: if pushing to github pages or aws-bucket, these files are not uploaded)
yes
dev chunk map still working
its now moved to generated dir

refactor(v2): move unused generated files out from build folder

---

packages/docusaurus/src/server/index.ts

Rather than doing stringify for simple string like below
```js
const a = `test${JSON.stringify(word)}`;
```
Better do
```js
const a = `test"${word}"`;
```
https://jsperf.com/stringifyvsdirect/1
yes

perf(v2): replace unnecessary json stringify(string) with inline string

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.js
packages/docusaurus-theme-classic/src/theme/Tabs/styles.module.css

Tabs cannot be controlled from the keyboard at the moment, this is very bad for a11y.
This PR implements tab switching by Tab/Tab+Shift and arrow keys (left and right).
Yes
Additionally, I added an `onFocus` handler so as not to press the Enter button to open the content of the focusable tab. Because that the contents of all the tabs are already loaded, we can _immediately_ display the contents of focusable tab, it's very cool.
For comparison, an example without `onFocus`, where the user needs to press Enter to display the contents of focusable tab. I think in this case it is not very good for UX.

refactor(v2): make better a11y for tabs

---

website/docs/advanced-plugins.md
website/docs/cli.md
website/docs/deployment.md
website/docs/installation.md
website/docs/markdown-features.mdx
website/docs/migrating-from-v1-to-v2.md
website/docs/presets.md
website/docs/search.md
website/docs/using-plugins.md
website/docs/using-themes.md
website/docusaurus.config.js
website/src/plugins/remark-npm2yarn.js

Show npm and yarn command on website so our docs is more friendly to both package manager users.
I created a naive plugin to convert npm commands to yarn. Will never make it official because my solution to convert npm to yarn is naive. Making it official also means = more bug reports, i have to write tests, etc.
This is also not the best remark plugin in the world. Still fit our use case
yes

docs(v2): display yarn and npm command on website

---

website/docs/versioning.md
website/sidebars.js

Write documentation on versioning. Feel free to edit :)
Don't merge till #2030 is merged please, because versioning hasn't been released yet
yes
Use netlify

docs(v2): add documentation on versioning

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/server/routes.ts

Just fixing types to be more explicit and so we can remove typecast
yes

refactor(v2): stronger typing for route gen

---

packages/docusaurus/src/webpack/base.ts

Mini-css extract plugin complains if your css imports are not sorted.
In our use case, we have the order warning because in our `markdownfeatures.mdx`, we import `Tabs` and `BrowserWindows` which has a CSS modules inside of it.  
Quoting from https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250
- Sorting all imports (not just in files but in tree traversal import order is difficult to do in a large project, and impossible
- Consistent use of scoping or naming conventions in CSS makes the order of CSS import irrelevant, and this is a much more manageable strategy for a large project
yes
Before
After

fix(v2): remove css order warning if css imports are not sorted

---

website/src/pages/versions.js

Just adding a check before displaying the section with previous versions, since they are not there right now and therefore it makes no sense to show the corresponding section.
Yes
Only actual information now.

fix(v2): hide past versions if it does not exist

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocItem/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css

In v1, code blocks are displayed as is, without wrapping, in general, this is a very good UX, especially on mobile devices. This PR disables line wrapping instead of which scroll bar will be displayed.
Yes
Desktop:
Mobile:

fix(v2): remove auto wrap for code blocks

---

website/docusaurus.config.js
website/src/pages/index.js

Currently, the tagline is very long, it is in both the title and description metas, I do not think that this is normal.
> Google typically displays the first 50–60 characters of a title tag. If you keep your titles under 60 characters, our research suggests that you can expect about 90% of your titles to display properly.
Be that as it may, but for SEO such a long title (>160 chars) has a not good effect, and in general the headline should not be like that.
Yes
See browser window title and meta description.

fix(v2): make friendlier title on home page for SEO

---

packages/docusaurus-plugin-content-docs/src/metadata.ts

Await pauses the execution of current async function and waits for the passed Promise's resolution, and then resumes the async function's execution
In `metadata.ts`, we can actually increase the performance a little bit by making the readFile as promise, then continue resuming the function execution, only when we then really need the data. we await the promise.
I created a simple benchmark to sort of describe the situation
https://runkit.com/endiliey/await-readfile-vs-readfile-as-promise/1.0.0
Old approach is something like
```js
async function oldApproach(source) {
const {id, title} = await fakeReadFile(source);
const version = getVersion(source);
// do something else
return {
id,
title,
version,
}
}
```
Now it's like
```js
async function newApproach(source) {
const frontMatterPromise = …
```

perf(v2): unblock metadata processing when possible

---

packages/docusaurus/src/webpack/base.ts

Implement https://github.com/webpack/webpack/pull/8642 which is webpack@5 default behavior to emit assets.
Nextjs, nuxtjs set this option too for memory friendly performance.
Inspired from https://nextjs.org/blog/webpack-memory
yes
- [] Netlify
- [] CI

perf(v2): use webpack future version of asset emitting logic to free memory

---

packages/docusaurus/src/commands/build.ts

Fix from regression in #2033 
Because client and server compilation is async, sometimes we can mistakenly reuse the manifest from previous build, which is wrong.
Now i remember why I put it in `build` folder previously although its not used later on for end-user, because its cleaned up on every build
yes

fix(v2): clean generated manifest from previous build so we dont use the wrong one

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js

Close #2059 
For sidebar, we should pass `exact` to `Link` component so that it will only match if its exact
https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/NavLink.md#exact-bool
So if current page is `/blog/test`, it won't match `/blog`
yes
Before
After

fix(v2): fix docs sidebar highlighting if link is partially matched

---

packages/docusaurus-1.x/lib/static/js/codetabs.js
packages/docusaurus-1.x/lib/static/js/scrollSpy.js

Transpile static JavaScript files to IE 10 support so that they does not bail on IE 10.
This Babel REPL is [broken](https://github.com/babel/website/issues/1627#issuecomment-559115705) on IE 11 due to the client JavaScript requires ES6. 
Yep
Manually testing the generated website.

fix: transpile static js to IE 10

---

packages/docusaurus-theme-classic/src/theme/MDXComponents/index.js

See https://v2.docusaurus.io/feedback/p/ability-to-download-static-assets-such-as-pdfs
In v1 it was possible to link to pdfs and other non-img static files in markdown using the syntax [file name] (/path/to/asset.pdf). When the user would click this link, the browser would trigger a download. In v2, docusaurus routing does not allow this and results in a 404, even though hitting my-site.com/path/to/asset.pdf directly will download the file just fine.
It's because we replace all `a` in MDX with `Link`. But we should've checked if its a file first. 99.99% webpage url that links to file will have `.xxx` notation in last part of URL
There might be edge cases like where some bad user has a url like `/docs/docusaurus.png` in which its a valid internal URL (not a file), its still OK to use <a> …

fix(v2): markdown reference to file should not be page not found

---

packages/docusaurus-mdx-loader/package.json
packages/docusaurus-mdx-loader/src/remark/rightToc/__tests__/__snapshots__/index.test.js.snap
packages/docusaurus-mdx-loader/src/remark/rightToc/__tests__/fixtures/inline-code.md
packages/docusaurus-mdx-loader/src/remark/rightToc/__tests__/index.test.js
packages/docusaurus-mdx-loader/src/remark/rightToc/search.js
yarn.lock

Fix broken TOC if heading has html inside inline code.
Value need to be escaped inside inline code so that it wont be mistaken as html
yes
Before
After
Newly added test passes, previous snapshot tests for mdx-loader rightTOC does not change

fix(v2): toc should not be broken for heading with html inline code

---

packages/docusaurus-theme-classic/src/theme/Heading/index.js

refactor(v2): add title attribute to anchor link

---

packages/docusaurus-plugin-google-analytics/src/index.js
packages/docusaurus-plugin-google-gtag/src/index.js

This PR requires #2057 to be looked first It's a PR for a PR. Just so that lerna changelog can pick it up
https://css-tricks.com/using-relpreconnect-to-establish-network-connections-early-and-increase-performance/
As suggested by lighthouse, can save few seconds
yes

perf(v2): add link rel preconnect for GA & google tag plugin

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocItem/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css

As mentioned in https://github.com/facebook/docusaurus/pull/2056
and https://github.com/facebook/docusaurus/pull/2048#issuecomment-558557240
I think it might be best to revert #2048 first. If we want to attempt on removing the codeblock autowrap, we can do it in new PR. Lot of changes has been added since alpha.36 and I think it'd be best to release soon so we can dogfood versioning & lot of other critical bugfix can land.
Because I'm seeing some unpleasant layout that is kinda zoomed and cut off. Notice the scrollbar
https://v2.docusaurus.io/docs/next/lifecycle-apis/
https://v2.docusaurus.io/docs/next/markdown-features
yes
No longer zoomed

Revert "fix(v2): remove auto wrap for code blocks (#2048)"

---

.eslintignore
.gitignore
.prettierignore
packages/docusaurus-plugin-ideal-image/@types/react-ideal-image.d.ts
packages/docusaurus-plugin-ideal-image/package.json
packages/docusaurus-plugin-ideal-image/src/index.ts
packages/docusaurus-plugin-ideal-image/src/theme/IdealImage.tsx
packages/docusaurus-plugin-ideal-image/src/types.ts
packages/docusaurus-plugin-ideal-image/tsconfig.json

refactor @docusaurus/plugin-ideal-image
I want to refactor every plugin to typescript. It helps consistency and maintainability.
Yes
Compiling and testing are passed.
https://github.com/facebook/docusaurus/pull/1997

refactor(v2): convert `@docusaurus/plugin-ideal-image` to TypeScript

---

packages/docusaurus-plugin-google-analytics/src/analytics.js
packages/docusaurus-plugin-google-analytics/src/index.js
packages/docusaurus-plugin-google-gtag/src/gtag.js
packages/docusaurus-plugin-google-gtag/src/index.js

I merged https://github.com/facebook/docusaurus/pull/2062#issuecomment-559917005 to wrong branch. But anyway I added some more optimization here
**Gtag**
We use inject head html hooks, so that the script head is not appended after JS load. [Removing this code](https://github.com/facebook/docusaurus/blob/522dd2d206900c74cbae03cc03974a6652e19218/packages/docusaurus-plugin-google-gtag/src/gtag.js#L35)
We should move this https://github.com/facebook/docusaurus/blob/61551152805aa53b1a50abf307ed6491ff3ab742/packages/docusaurus-plugin-google-gtag/src/gtag.js#L40-L51 to head like what https://developers.google.com/analytics/devguides/collection/gtagjs/ recommend.
Doing it via client modules previously will put it in main bundle.
**Google analytics**
Instead of old …

perf(v2): more performant gtag and analytics plugin

---

packages/docusaurus-theme-classic/src/index.js
packages/docusaurus-theme-classic/src/theme/Toggle/index.js
packages/docusaurus-theme-classic/src/theme/Toggle/styles.module.css
packages/docusaurus/src/client/App.js
packages/docusaurus/src/server/html-tags/index.ts

Fix https://github.com/facebook/docusaurus/issues/1995
Before this PR, notice the FOUC
Also have prefer color scheme.
yes
- Build production locally
- Serve it locally
- Go dark mode and refresh
You can also try it on netlify :)
https://deploy-preview-2069--docusaurus-2.netlify.com/
cc @lex111 in case you want to give this a try. Seems that this should fit all of our use case
`isClient` context is needed because we need to do **two pass rendering**
Why do we need two pass rendering ? 
For full reasoning, please check the whole thread starting from this comment https://github.com/facebook/docusaurus/pull/2057#issuecomment-559137084
I tweaked the CSS such that it looks very perfect now.

feat(v2): support prefers-color-scheme & fix dark mode FOUC on refresh

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

Docsearch bundle size is a whooping 35kbs gzipped. That's huge ...
Trying to improve our TTI performance by only loading algolia when user interact with the search
yes
Still working ✌️ 
Notice how the bundle is only loaded when user interact with it
Benefit.
- Less bundle size shipped to user. 35kbs gzipped is huge. At first page load, our main thread is already busy parsing other javascript.
This increase our lighthouse TTI by 1s
After is 2.8s+
Before was 3.9s +
Slight caveat:
- There might be some kind of delay when user "search" with algolia for the first time since the JS is lazily loaded. Almost unnoticeable though, depends on internet speed. But since main thread is no longer busy, it will definitely be faster. see gif preview or try it on netlify

perf(v2): load algolia JS only when user interacts with search

---

packages/docusaurus/src/client/App.js
packages/docusaurus/src/server/index.ts

Move scripts/stylesheets siteConfig client side injection to server side using injectHtmlTag API
The benefit of this approach is that there won't be weird `data-helmet` attribute on the injected head tags and theoretically server side should be faster than react helmet.
yes
Nothing broke
Add random scripts and stylesheets into config
Deprecate scripts and stylesheets option ? But that would require v1 user migrating having to create a local plugin which can be slightly annoying

refactor(v2): move scripts/stylesheets injection to server side

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js

Use client side navigation, avoid full page refresh on algolia search result. The extra benefit is also pretty rad, local dev can work nicely now. Previously it will always go to v2.docusaurus.io/xxxx
yes
Before
Try https://v2.docusaurus.io/ and search anything. It will cause page refresh
After
Also still in localhost

perf(v2): algolia search result no longer cause full page refresh

---

packages/docusaurus-1.x/examples/basics/pages/en/index.js

refactor(v1): fix props for ProjectTitle

---

packages/docusaurus/src/server/index.ts

This reverts #2039 
yes
Previously registry.js will be like this on Windows. 
[Error in babel](
https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA28DeAoOOAcgGMIA7GYSgWjoCNMIBzGgJgHYBmGj5LogC44AbQAUASjgBeAHxwAlgFtIsMQHoAVHADuwemFQkA1gGEAFunLGAcqiXBhpClVoMmrTjz4C4m9XAARAACAM4KVOqMLAA6bAAMAIwAnDTxAKzsABw05hCYqAB0SggA_DBQViSoVAjSFejAgRIANEFhEcBRHnFJqRnZuflFJeWV5NW19ZVNbVDAAI7oCvOF86H5AG7AAOrAqMZiIeGR0cy9KWmZbDl5BcVlDRM1wHUNTRIAui14AL5AA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.7.4&externalPlugins=)
[After]( …

fix(v2): windows compatibility regression

---

packages/docusaurus-1.x/examples/versions/pages/en/versions.js

I noticed the v1 examples `versions.js` when calling `map` function does not provide a `key`.
So i added the `key` prop to ` packages/docusaurus-1.x/examples/versions/pages/en/versions.js`

fix(v1): add key to versions.map in versions.js

---

packages/docusaurus-utils/src/index.ts
website/docs/markdown-features.mdx

Cache-loader compares with [mtime](https://github.com/webpack-contrib/cache-loader/blob/3371562bc05c645dcd20e851ec6c0cc82387fd7f/src/index.js#L311-L313)
And currently, whenever we run new "docusaurus start", we always overwrite a lot of the generated files for the first time, invalidating cache. The next reload is fine, because we have runtime content hash cache.
We can do better by checking If file already exist but its not in runtime cache hash yet, then we try to calculate the content hash and then compare. This is to avoid unnecessary overwrite and we can reuse old file. Thus, cache-loader wont invalidate.
yes
Before ~7s
My next dev server (second run) went down to ~5s
This is minor improvement, but as more metadata is written, this is gonna improve a lot
(If this PR adds or changes …

perf(v2): improve dev build time by not overwriting file if possible

---

packages/docusaurus-plugin-content-blog/src/markdownLoader.ts
packages/docusaurus-plugin-content-docs/src/markdown/index.ts

If markdown file does not have an ending line, the metadata embed in content will error out due to MDX mistaking `export const metadata` as part of paragraph
Example:
This won't error
Error
So whats happening under the hood ?
The metadata is mistaken as part of paragraph
yes
No more error
#2088

fix(v2): metadata error if markdown does not have ending line

---

packages/docusaurus/src/server/routes.ts

Continuation from #2086 Still one part not yet stringified. Seems that I didn't push it to remote
Edit: maybe I need a break 😢 , silly mistake
Close #2098 
yes

fix(v2): escape import path on windows

---

.github/workflows/nodejs-windows.yml

Testing GitHub actions to build Windows for both v1 and v2 to prevent regression
all code is kinda self-made from reading https://help.github.com/en/actions/automating-your-workflow-with-github-actions
Seems to work well
yes
TBD. CI should appear ??

chore: docusaurus build on Windows with GitHub actions

---

docs/getting-started-publishing.md
website/docs/migrating-from-v1-to-v2.md

I've been receiving quite a number of questions regarding the Now deployment setup for Docusaurus v1 projects. It'll be helpful to mention that the `docs` have to be moved into `website`.
Yes
See Netlify.

docs: mention about moving docs directory into website

---

website/docs/migrating-from-v1-to-v2.md
website/docs/styling-layout.md
website/package.json
website/src/components/ColorGenerator/index.js
website/src/components/ColorGenerator/styles.module.css
yarn.lock

Make it easy for users to generator a color palette for their primary color.
Yes

feat(v2): add color generator for primary colors

---

website/src/components/ColorGenerator/index.js

CSS vars starts with two hyphens.
Yes

fix(v2): add missing hyphen in color generator

---

packages/docusaurus-theme-classic/src/theme/hooks/useTheme.js

Currently, automatic switching to a dark theme does not work if a dark theme is selected in the system (because even when there is no saved theme in local storage, we set (override init value with correct theme) the theme to `null` value which is cast to an empty string (i.e. light theme)). This PR solves this bug.
https://github.com/facebook/docusaurus/blob/ba7c38cf0fc3e384373e6da4147fb154a939279b/packages/docusaurus-theme-classic/src/index.js#L29-L30
Yes
1. Select a dark theme in your OS
1. Go to the docs site (after clearing localstorage), a dark theme should be enabled.

fix(v2): set stored theme only if it exists

---

package.json
website/docs/creating-pages.md

Simple docs change
yes
N/A - Netlify and CI only

docs(v2): fix pages routing inaccurate info

---

packages/docusaurus/src/webpack/utils.ts

See https://github.com/babel/babel/issues/10261 and https://github.com/babel/babel/issues/10261#issuecomment-520990162
By default transform-runtime assumes that @babel/runtime@7.0.0 is installed. If you have later versions of @babel/runtime but did not specify version, transform-runtime will only use the helper from 7.0.0 resulting in larger bundle size.
>In this case, it will assume you are using babel/helpers 7.0.0-beta.0, which means every helper introduced later than 7.0.0-beta.0 will be inlined instead of require. 
Better to be explicit
Inspired from https://github.com/facebook/create-react-app/pull/7726
yes
- Netlify should all pass
- CI

feat(v2): explicit babel/runtime version

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/styles.module.css
website/src/components/ColorGenerator/index.js

In addition to the syntax highlighting itself, which is important given the dark/light Prism theme (coming soon https://github.com/facebook/docusaurus/pull/1984), it is possible to copy CSS vars simply click button.
Yes

fix(v2): add syntax highlight to generated colors

---

packages/docusaurus-mdx-loader/README.md
packages/docusaurus-mdx-loader/package.json
packages/docusaurus-mdx-loader/src/index.js
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-blog/src/markdownLoader.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/markdown/index.ts
packages/docusaurus/src/commands/start.ts

Move metadata export after compiling the MDX to avoid weird MDX parsing error. 
Although we've fixed #2095 (MDX thinking that metadata was part of paragraph), there might be some other unexpected case.
For example:
This  will error out, because it is unclosed (funnily it thinks its unclosed because style must always have `</style>` counterpart. And MDX think metadata is part of the JSX
```mdx
<style dangerouslySetInnerHTML={{__html: `
.comparisonTable td {
width: 25%;
}
.comparisonTable .middle {
text-align: center;
vertical-align: middle;
}
.comparisonTable ul {
padding-left: 1em;
}
`}}/>
export const metadata = {
id: 'test'
}
```
https://mdxjs.com/playground
If its closed properly, it doesnt error. Now I'm pretty confused how they determine HTML or JSX
```mdx
<style …
```

fix(v2): move metadata export after compiling MDX to avoid weird MDX parsing error. 

---

packages/docusaurus/package.json
packages/docusaurus/src/client/serverEntry.js
yarn.lock

This is sort of continuation from #2115, but with several differences. Thank you @lex111 
**1. We minify the HTML instead of only the inlined JavaScript**
Smaller size of HTML
**2. The minifier is based on Terser, not babel-preset-minify**
As mentioned, Terser is the standard now and babel-preset-minify is no longer maintained and seems to have lot of problems (breaking code)
**3. No babel syntax transform, just pure minifying**
See this comment https://github.com/facebook/docusaurus/pull/2115#issuecomment-564378277 and also consider this scenario: What if user purposefully use es modules in the injected html ? we dont want to transform that with babel. Example:
```html
<script type="module">let foo = “test”;</script>
```
```html
<script nomodule>var foo = “test”<script>
```
The moment we …

feat(v2):  minify html

---

packages/docusaurus-theme-classic/src/index.js

We can change the theme on the website depending on the installed system theme in real time. That is, when a user changes the theme in their OS, it changes on the website (if at that moment a tab with the website is open!)
Important point - if the user has already selected a theme on website, we do not switch theme when system theme has been changed. 
Yes
1. Open website (clear local storage just in case) in new tab
1. Change the theme in your OS settings
1. Make sure that on the website (in the previously opened tab) the theme has also changed. For example, if a dark theme was selected on the OS, then exactly this theme should be selected on the website.

feat(v2): auto switch theme depending on the system theme

---

packages/docusaurus/src/client/serverEntry.js

Continuation #2116 
Tweak minify html to be safer.
1. Dont collapse whitespace
Why ?
```js
var input = '<div> <p>    foo </p>    </div>';
var output = minify(input, { collapseWhitespace: true });
output; // '<div><p>foo</p></div>'
```
This causes our SSR to be weird. Notice "optimizedwebsites" instead of "optimized websites" when javascript is disabled.
See http://perfectionkills.com/experimenting-with-html-minifier/#collapse_whitespace
yes
Rendered HTML should be fine now
- Netlify with JS disabled

fix(v2): dont collapse whitespace in minified html

---

docs/getting-started-installation.md
website-1.x/pages/en/index.js
website/docs/installation.md

I'm feeling lazy so I deleted the template. This PR is self-explanatory.

docs: promote Docusaurus 2 usage

---

packages/docusaurus-theme-classic/src/index.js
packages/docusaurus-theme-classic/src/theme/Navbar/index.js
packages/docusaurus-theme-classic/src/theme/hooks/useTheme.js
packages/docusaurus/src/client/exports/Link.js

Refactoring on `Navbar`
- Remove docusaurus/Head from it.
- Toggle data-theme is done in the hook instead
Refactoring on `Link`
- Use `useRef` so that boolean persist
use `document.documentElement` instead of `queryselector('html`). Its faster according to benchmark i run https://jsperf.com/documentelevsquery/1
Supported in all browsers https://developer.mozilla.org/en-US/docs/Web/API/document/documentElement
yes
There shouldn't be difference in expected behavior ?
Toggling fine

refactor(v2): toggle data-theme with vanilla js instead of react helmet

---

website-1.x/pages/en/index.js

Went to the Docusaurus homepage and noticed there was a missing space. Felt it would be a good place to open a PR.
Yes.
It's a simple space, so I don't think it requires special planning.

docs(v1): add space between "out" and "Docusaurus"

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.js

As a rule, it is customary to disable scrolling of body on the webpage when the mobile menu is open, since it itself may have scrolling.
Yes.
1. Open preview website on mobile
1. Click to sidebar button
1. Try scrolling the webpage

fix(v2): disable scroll while mobile menu open

---

packages/docusaurus-theme-classic/src/theme/Layout/index.js

For better accessibility, you must specify the lang attribute in the <html> element.
I don’t know if the functionality for translations will be available soon, therefore I just bring back the previous behavior - by default I set English.
Yes
See HTML markup.

fix(v2): add HTML lang attribute

---

packages/docusaurus/package.json
yarn.lock

Upgrade dependencies and lock down `style-loader` to `1.0.2` as there's a bug in `1.1.0` as mentioned in https://github.com/webpack-contrib/style-loader/issues/445

chore(v2): upgrade dependencies

---

packages/docusaurus/package.json
packages/docusaurus/src/webpack/utils.ts
yarn.lock

Close #2143 
Close #2141 
Remove `style-loader` and its annoying bug and use `MiniCssExtractPlugin` for both development and production environment.
The main reasons to use style-loader in development mode previously is to support hot module reloading but MiniCssExtractPlugin which is used for production build does support HMR feature since v0.6.0 (2019-04-10).
This ensures consistency
yes
Local hmr still working
Production build styles should work OK (Netlify)

fix(v2): remove style-loader, use minicssextract in both dev & prod

---

packages/docusaurus-mdx-loader/README.md
website/docusaurus.config.js

In order to get 1000 free build minutes for netlify instead of 300 using open source plan, we need to add netlify logo to our site. https://www.netlify.com/pricing/
Let me know if this is a good idea, otherwise we can move away from netlify ...
or we can move it to other places. Feel free to patch the PR
yes
See preview,. logo on footer

chore(v2): add netlify logo for open source plan

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js

Fixes #2149
Yes
1. Go to Netlify preview's /docs/introduction
2. Set to dark mode if it's not already dark mode
3. Refresh page, see code block syntax theme is dark
https://github.com/facebook/docusaurus/pull/1984

fix(v2): render correct syntax theme for current website theme

---

website/docs/lifecycle-apis.md

The code snippet used [here](https://v2.docusaurus.io/docs/lifecycle-apis#configurewebpackconfig-isserver-utils) is not working, using this format it returns a double `React` declaration. According to #2097 i've updated it with one of the two working formats.
yes

docs(v2): update custom webpack configuration snippet

---

packages/docusaurus-init/templates/facebook/.eslintrc.js
packages/docusaurus-init/templates/facebook/README.md
packages/docusaurus-init/templates/facebook/docusaurus.config.js
packages/docusaurus-init/templates/facebook/package.json
packages/docusaurus-init/templates/facebook/sidebars.js
packages/docusaurus-init/templates/facebook/src/css/custom.css
packages/docusaurus-init/templates/facebook/src/pages/index.js
packages/docusaurus-init/templates/facebook/src/pages/styles.module.css
yarn.lock

Make the Docusaurus website template for Facebook OSS projects use ESLint.
Yes
```
yarn ci
```
within the `docusaurus/packages/docusaurus-init/templates/facebook` directory.

feat(v2): add ESLint to Facebook template

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js
website/docs/markdown-features.mdx
website/docs/theme-classic.md
website/src/css/custom.css

1. Write docs for dark mode syntax highlighting
1. Fix a bug in the Prism theme logic for dark mode where it uses no highlighting instead if no `darkTheme` is specified 😱 
1. Make the line highlighting work for both light and dark modes
Yes
See Netlify

docs(v2): dark mode syntax highlighting

---

packages/docusaurus-theme-classic/src/index.js

> If your <script>…</script> blocks have no dependency on CSS, place them above your stylesheets.
According this [article](https://csswizardry.com/2018/11/css-and-network-performance/#dont-place-link-relstylesheet--before-async-snippets).
Yes
See Netlify.

refactor(v2): move no-flash script to head tag

---

packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js
packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css

Currently, when scrolling down, the sticky header is hiding and there is an empty space in the doc sidebar, so I figured out how to fill it in - put the logo and title there, as in navbar (see test plan or check out preview)!
Yes
| ![screencast-nimbus-capture-2019 12 30-02_12_27](https://user-images.githubusercontent.com/4408379/71564020-7bea9700-2aaa-11ea-88ef-80d60ca32b64.gif) | ![screencast-nimbus-capture-2019 12 30-02_13_31](https://user-images.githubusercontent.com/4408379/71564018-78571000-2aaa-11ea-9027-21441ddf4d27.gif) |

feat(v2): add logo and title in doc sidebar
