website/docs/introduction.md

Link of Docusaurus1 is already mentioned in the Header. [here](https://github.com/facebook/docusaurus/pull/4128/files#diff-0890f0ba3d12d890012a1b6135b69b25354212692889e02df86a130262bb3405L29)
Having it again in the bullet points looks unorganized. So removing it
Yes

docs(v2): remove duplicate link from docs about Docusaurus1

---

packages/docusaurus/src/server/routes.ts

Should fix #3963.
Yes
See To reproduce section in #3963.

fix(v2): escape apostrophes in route paths

---

website/docs/api/plugins/plugin-content-docs.md

Simple Typo Fix for word **version** in plugins Documentation
Yes

docs(v2): plugins docs typo fix

---

website/docs/guides/docs/sidebar.md

Fixing 2 typos in guide docs:
1. hierarchy
2. SidebarItem
Yes

docs(v2): guide docs typo fix

---

packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx

I think we'd better use a regular `div` instead of `section` tag for blog post content, as we currently have HTML error like this:
This is because `section` requires mandatory headings (`hX`). So therefore wise to opt out of using this tag as we cannot guarantee that this rule will be followed.
Yes
Validator's happy.

fix(v2): avoid misuse section tag in blog posts

---

packages/docusaurus/src/client/baseUrlIssueBanner/BaseUrlIssueBanner.tsx
website/dogfooding/clientModuleExample.ts

Follow-up of:
https://github.com/facebook/docusaurus/pull/4125
https://github.com/facebook/docusaurus/pull/4136
Change BaseUrl issue banner integration so that it's not indexed by SEO. 
Instead of trying to insert it, and then remove it, we now prevent it from being inserted in the first place for the optimistic case (React can hydrate successfully).
yes
SEO tools

fix(v2): BaseUrl issue banner insertion should be prevented if JS can load

---

.github/workflows/build-size.yml

Build size bot got broken by https://github.com/facebook/docusaurus/pull/3998
Note: we should likely figure out a way to output better chunk names as we have large bundles named "1" and "3" and even worst namings.
Probably worth investing in this after the Webpack 5 migration

fix(v2): fix build size bot monitoring of js/css assets

---

packages/docusaurus-theme-search-algolia/src/index.js
packages/docusaurus-theme-search-algolia/src/templates/opensearch.js

Fixes #4151.
Yes
Set `baseUrl` and check out opensearch.xml file.
Preview - https://deploy-preview-4154--docusaurus-2.netlify.app/classic/opensearch.xml

fix(v2): add base url to opensearch.xml

---

website/docs/guides/markdown-features/markdown-features-assets.mdx
website/docs/introduction.md
website/docs/static-assets.md
website/src/pages/index.js

It's not useful to use `useBaseUrl()` in many places anymore (links, markdown images/links...) but the doc does not really reflect that. 
This refreshes a bit the doc

docs(v2): improve bad static assets doc + remove some useless useBaseUrl usage

---

.github/workflows/build-size.yml

My test did not work so well, I just wanted to track the 1.hash.js file but tracked much more.
Revert to former config, we'll figure out how to monitor other files later

chore(v2): fix build size bot again

---

packages/docusaurus-theme-classic/src/theme/LayoutHead/index.tsx

According to SEO tools it seems we should rather use hreflang=en for the English / default pages of the doc.
And we can actually use both x-default + en
https://www.searchviu.com/en/multiple-hreflang-tags-one-url/
https://sitebulb.com/hints/international/hreflang-annotation-also-x-default/
yes
Ahrefs SEO tools

fix(v2): fix hreflang headers

---

packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx

Should fix #3917
Yes
Preview https://deploy-preview-4162--docusaurus-2.netlify.app/classic/

fix(v2): make more accessible skip link

---

packages/docusaurus-theme-classic/src/theme/TOCInline/styles.module.css
website/docs/configuration.md

Currently, when going on Configuration page in dv mode, we get a couple of warnings:
```
Warning: validateDOMNesting(...): <ul> cannot appear as a descendant of <p>.
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
```
This is because only inline elements should be inside the `p` tag. Unfortunately, this cannot be solved by anything other than placing the `TOCInline` component on a new line.
I also decided to restyle the inline TOC as a regular list because it doesn't look very good right now.
| ![image](https://user-images.githubusercontent.com/4408379/106732287-95510180-6621-11eb-8cc0-a82fe4076d2f.png) | ![image](https://user-images.githubusercontent.com/4408379/106732361-ab5ec200-6621-11eb-846d-3effa03ccbea.png …

fix(v2): fix warning and improve styling inline TOC

---

website/community/resources.md

We at Sauce Labs have build a plugin that allows our tech content team to reference code samples from actual code repositories where these can be tested and maintained.

docs(v2): Add docusaurus-theme-github-codeblock

---

website/versioned_docs/version-2.0.0-alpha.70/api/plugins/plugin-ideal-image.md

Add a note that images are not rendered on the development server
I spent more than an hour to finally find out that the images are not rendered on the development server. Although there is a message in the description saying "in the production builds." anyone can miss it easily.
yes

docs(v2): add a note for images not rendered on dev server

---

packages/docusaurus-plugin-ideal-image/src/index.ts

Follow-up on https://github.com/facebook/docusaurus/issues/3156
We want all static assets to be in ./assets and have hashes, so that users can leverage CDN caching more easily

fix(v2): ideal image assets should be served under ./assets

---

packages/docusaurus-theme-classic/src/theme/BlogListPaginator/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogPostPaginator/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPaginator/index.tsx
packages/docusaurus-theme-classic/src/theme/EditThisPage/index.tsx
packages/docusaurus-theme-classic/src/theme/NotFound.tsx
packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.js
packages/docusaurus/src/server/translations/__tests__/translationsExtractor.test.ts
packages/docusaurus/src/server/translations/translationsExtractor.ts
website/package.json

We want some theme hardcoded labels to be translated:
- "edit this page"
- pagination (next/previous, new post/old post...)
- code block copy/copied
- read more
- ...
This is not yet an exhaustive list, some labels remain to be translated but are more complicated to handle:
- labels  with interleaved variables like "{time} min read time" or "last updated by {author} on {date}"...
- date formatting
- tags (we'll translate these when we have tags on docs and we have factorized a bit the theme code => less future i18n breaking changes)
- ... probably others
- we probably want to translate all hardcoded aria labels as well
yes
tests + preview + i18n dogfooding

feat(v2): Extract/translate hardcoded labels from classic theme

---

website/docs/installation.md

As listed `yarn version` works but throws an error. This PR updates the command that checks the install to be `yarn --version` per the [Yarn docs](https://classic.yarnpkg.com/en/docs/install#mac-stable)

Update command to check yarn installation

---

packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css
packages/docusaurus-theme-classic/src/theme/Toggle/styles.module.css
website/src/pages/index.js
website/src/pages/styles.module.css

- Fix borders of collapse doc sidebar button
- Replace e-resize type with click when hover on expand sidebar button
|![image](https://user-images.githubusercontent.com/4408379/106787186-73c33a80-6660-11eb-9d9d-9b6973886c5e.png) | ![image](https://user-images.githubusercontent.com/4408379/106787224-82a9ed00-6660-11eb-9833-5c2c4007b993.png) |
- Add hover state for dark mode switcher
- Use Infima buttons on home page
| ![image](https://user-images.githubusercontent.com/4408379/106787434-be44b700-6660-11eb-8df6-ab578a91eac1.png) | ![image](https://user-images.githubusercontent.com/4408379/106787365-aec56e00-6660-11eb-9dfe-be69f95660c8.png) |
Yes
Preview
(If this PR adds or changes functionality, …

refactor(v2): minor styling improvements

---

website/docs/installation.md

Removing This double colon and making it single, looks like a simple typo
Yes

docs(v2): typo fixing double colon

---

website/docs/i18n/i18n-tutorial.md
website/static/_redirects

Hint user to localize his 404 pages, as it's not done by default with jamstack hosts

docs(v2): localize 404 page with Netlify + docs

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/LocaleDropdownNavbarItem.tsx

Locale dropdown is currently not available for keyboard navigation, to fix this we need to add a `href` attribute.
Yes
Preview.

fix(v2): make locale dropdown accessible from keyboard

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/styles.css

Should fix #4088.
For some unknown reason, on Safari (actual at least for 12.1, 13.1, 14 versions, tested with BrowserStack) after closing docsearch modal, current page automatically scrolls to the bottom. This is a very strange bug, specific only to Safari, and after all my unsuccessful efforts I could not determine the reason for this. However, I found out that where docsearch was added does really matter -- if it is added as the first body element then the scrolling issue is solved.
Until we figure out why this is happening, I think we can use this fix.
Yes
Check it out preview site on Safari.

fix(v2): prepend docsearch modal to body element

---

packages/docusaurus-theme-classic/src/theme/Navbar/styles.module.css
packages/docusaurus-theme-classic/src/theme/hooks/useHideableNavbar.ts

Animating the `top` property will have some graphics performance impacts, basically animating top will trigger the browser to [perform layout operations](https://csstriggers.com/top).
Instead use transform with translate3d so the operation can likely be [carried out by the compositor thread](https://csstriggers.com/transform) with the help of the GPU.
As result, we get smoother transition (navbar hide animation) on mobiles:
| ![ezgif com-gif-maker (15)](https://user-images.githubusercontent.com/4408379/107229800-4d6e1800-6a2f-11eb-8e0d-99a05057f482.gif) | ![ezgif com-gif-maker (16)](https://user-images.githubusercontent.com/4408379/107229773-46dfa080-6a2f-11eb-9950-614eba15e7fb.gif) |
UPD: As per the discussion in …

refactor(v2): use transform instead of top position for hideable navbar

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx

Because currently the Versions menu item cannot be expanded on mobiles.
Yes
Preview.

fix(v2): prevent click on item menu with children on mobiles

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx

After some research, I realized that the current implementation of the Tabs component is not entirely correct. We should better follow the WAI-ARIA Tabs Pattern, which is described at https://www.w3.org/TR/wai-aria-practices/#tabpanel.
The main difference is that pressing on tabs list with Tab key will not switch tab, but instead move focus to the corresponding tabpanel (if necessary). This is useful if the tab content contains a focusable element like a link.
References (with automatic activation):
- https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html 
- https://reakit.io/docs/tab
- https://react-bootstrap.github.io/components/tabs/#rb-docs-content
- https://reach.tech/tabs/
In addition, I also decided to refactor the code - when rendering each tab item, we use the …

refactor(v2): update tabs to follow WAI-ARIA spec

---

website-1.x/blog/2019-12-30-docusaurus-2019-recap.md

Fixing this broken link in Blog post. This link changed long after the blog was published.
Yes

docs(v1): fixing a broken link in blog posts

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.tsx
packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx
packages/docusaurus-theme-classic/src/theme/hooks/useHideableNavbar.ts

After merge #4162, our anchor links were broken. It also turned out that when we open any page with the hideable navbar enabled, one of `useEffect` hook is wrongly triggered.
Yes
Preview.

fix(v2): various minor bugs with location hash

---

packages/docusaurus/src/webpack/base.ts
packages/docusaurus/src/webpack/utils.ts

After upgrading css-loader here: https://github.com/facebook/docusaurus/pull/4081
The `url(/my/font.ttf)` are not  resolved by Webpack, while it was not the case before.
Exemple in:
```css
@font-face {
font-family: "Iran Sans";
font-style: normal;
font-weight: 100;
src: url("/fonts/IRANSans5.5/IRANSansWeb_UltraLight.eot"),
/* IE9 Compat Modes */
url("/fonts/IRANSans5.5/IRANSansWeb_UltraLight.eot?#iefix")
format("embedded-opentype"),
/* IE6-IE8 */ url("/fonts/IRANSans5.5/IRANSansWeb_UltraLight.woff2")
format("woff2"),
/* Super Modern Browsers */
url("/fonts/IRANSans5.5/IRANSansWeb_UltraLight.woff") format("woff"),
/* Modern Browsers */ url("/fonts/IRANSans5.5/IRANSansWeb_UltraLight.ttf")
format("truetype");
} 
```
The CSS above now fails to build, because …

feat(v2): add fonts loaders + webpack resolve.roots

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.tsx
packages/docusaurus-theme-classic/src/theme/Navbar/styles.module.css
packages/docusaurus-theme-classic/src/theme/NavbarItem/SearchNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/styles.module.css
packages/docusaurus-theme-classic/src/theme/SearchBar.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-classic/src/validateThemeConfig.js
packages/docusaurus-theme-common/src/utils/useThemeConfig.ts
website/docs/api/themes/theme-configuration.md

feat(v2): allow to change location of search bar

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/webpack/__tests__/utils.test.ts
packages/docusaurus/src/webpack/utils.ts
website/docs/lifecycle-apis.md

Preliminary implementation of a hook for quickly expanding the PostCSS loader (mainly for adding new PostCSS plugins).
Yes
Tests.

feat(v2): allow extend PostCSS config

---

website/src/data/users.js

I think these paragraphs will help tell people what sites we want to see in the showcase.
Yes
N/A.

misc: add requirements for sites being added to showcase

---

website/docusaurus.config.js

Translators should be able to preview their translation work.
Locales for which  translation work has started , but not enough is translated for production, will be visible at https://docusaurus-i18n-staging.netlify.app/

chore(v2): setup for i18n staging deployment

---

packages/docusaurus-theme-classic/codeTranslations/fr.json
packages/docusaurus-theme-classic/src/index.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus-utils/src/__tests__/__fixtures__/defaultCodeTranslations/en.json
packages/docusaurus-utils/src/__tests__/__fixtures__/defaultCodeTranslations/fr.json
packages/docusaurus-utils/src/__tests__/__fixtures__/defaultCodeTranslations/fr_FR.json
packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus/src/commands/writeTranslations.ts
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/translations/__tests__/translations.test.ts
packages/docusaurus/src/server/translations/translations.ts

For strings hardcoded in a theme (like "next"/"previous" pagination labels), we can pre-translate them in the current locale so that the user does not have to.
These "provided translation bundles" serve for 2 things:
- init the files with fallback messages when using `docusaurus write-translations --locale fr`
- fallback message values when running `docusaurus start --locale fr` even if `fr/code.json` does not exist
Tests

feat(v2): Add i18n default code translation bundles

---

website/docs/guides/markdown-features/markdown-features-assets.mdx
website/versioned_docs/version-2.0.0-alpha.70/markdown-features.mdx

Removing a wrong parenthesis on image variable.

docs(v2): Removing wrong parenthesis on image variable

---

packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-blog/src/types.ts
packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/docs.ts
packages/docusaurus-plugin-content-docs/src/types.ts
website/docs/api/plugins/plugin-content-blog.md
website/docs/api/plugins/plugin-content-docs.md

The `editUrl` fn should provide the user with the doc/blog permalink.
This is useful for future integrations with online editing sandboxes like StackBlitz and CodeSandbox, as it allows to load the site on the correct page by passing a querystring param.
cc @EricSimons
tests

feat(v2): editUrl functions should receive md doc permalink

---

website/versioned_docs/version-2.0.0-alpha.68/introduction.md
website/versioned_docs/version-2.0.0-alpha.69/introduction.md
website/versioned_docs/version-2.0.0-alpha.70/introduction.md

According to #4126, we shouldn't be using `baseUrl` for the images in markdowns. It also broke the image on the old versioned docs (You can also see this on https://v2.docusaurus.io/docs/):
I replaced the `img` tag with markdown image link, to make it consistent with the latest docs.
Yes
Now fixed:

docs(v2): Fix link to slash introduction svg

---

website/versioned_docs/version-2.0.0-alpha.70/typescript-support.md

The example was not working, because there was no extra `--` in front of `--typescript`
Yes
Testing is pretty simple: run the previous example on the command line which does not work as the `--typescript` is interpreted as part of the npm command, and run the new example with an extra `--` which does work as the `--typescript` is interpreted as an option for the docusaurus command.

docs(v2): fix npm/yarn command example for swizzling TypeScript theme components

---

website/docusaurus.config.js

As I introduced the `editUrl` fn, I didn't see I broke the fact that edit buttons should lead to the upstream docs, so we receive doc update PRs to update alpha 70 instead of the docs of the upcoming release.
We prefer to receive docs PR to upstream docs, because if the user does not modify the upstream docs, the update will be lost on next release.

fix(v2): website editUrl should target upstream docs

---

website/src/pages/versions.js

The current versions page is wrong:
This  is likely because we use a little trick in dev so what you see in dev and prod is not 100% identical:
`lastVersion: isDev ? 'current' : undefined,`
I've made it so that the versions page show decent infos in both cases.
Dev:
Prod:

fix(v2): fix website versions page

---

website/docs/migration/migration-manual.md
website/static/_redirects

When migrating to Docusaurus v2, v1 users should not lose their v1 RSS feed subscribers

docs(v2): v2 migration should mention RSS feed url change

---

packages/docusaurus-theme-classic/src/theme/BlogSidebar/styles.module.css
packages/docusaurus-theme-classic/src/theme/TOC/styles.module.css
packages/docusaurus-theme-classic/src/theme/TOCInline/index.tsx
packages/docusaurus-theme-classic/src/theme/Toggle/styles.module.css
packages/docusaurus-theme-classic/src/theme/hooks/useHideableNavbar.ts
packages/docusaurus-theme-classic/src/theme/hooks/useWindowSize.ts

Small minor fixes:
- Remove/optimize of redundant CSS properties.
- Remove non-working CSS class name
- Fix bug with hideable navbar (with multiple and fast scrolling at beginning of page, the navbar was incorrectly hidden)
Yes
Preview

refactor(v2): clean-ups and fixes

---

packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css

Fixes #3870
Closes #4235
Because the most correct solution in our case is to set the maximum width for the column with main content on desktop (except extra large screens).
Yes
Check it out Using React page on preview site as per instructions in #3870.

fix(v2): avoid horizontal scrolling when long lines of code

---

packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/Footer/index.tsx
packages/docusaurus-theme-classic/src/theme/Logo/index.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx

Remove manual setting of `target="_blank" rel="noreferrer noopener"` attributes for external links so that the built-in `Link` component does this.
Yes
Preview.

refactor(v2): use Link component for external links

---

packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css

PR #4241 was merged too quickly so I didn't have time to test it as it introduced a small regression for collapsible doc sidebar.
Yes
| Before   | After (centered)   |
| ![image](https://user-images.githubusercontent.com/4408379/108354089-0683dd80-71fa-11eb-9eca-ecb5b9c3f364.png) | ![image](https://user-images.githubusercontent.com/4408379/108354120-156a9000-71fa-11eb-9127-28ddd6cb84b6.png) |

fix(v2): make doc container full width when hidden sidebar

---

packages/docusaurus-cssnano-preset/index.js
packages/docusaurus-cssnano-preset/package.json
yarn.lock

Should fix #4231
At the moment, when we do not control the order of including CSS files, it is better to remove this plugin, because it raises more problems than it solved for us.
Yes
See reproducible section in #4231.

fix(v2): remove PostCSS plugin for combine duplicated selectors

---

.github/workflows/build-size.yml

Due to a bug in the GH action, we didn't get appropriate size diffs!
https://github.com/preactjs/compressed-size-action/issues/54
This is a workaround

chore(v2): Fix build size bot

---

packages/docusaurus-theme-classic/src/index.ts

`infima/packages/core/dist/css/default/default-rtl.css` is not a "reliable" path to check for the Infima CSS bundle.
On Infima repo, it broke because  Netlify fetches the Infima repo as `repo` (ie not `infima`) and the CSS file is at `/opt/build/repo/packages/core/dist/css/default/default-rtl.css`
This broke the RTL support on Infima website deploy preview: https://github.com/facebookincubator/infima/pull/84
The current method will be more reliable, as we are now comparing strictly 2 absolute file paths.

fix(v2): fix LTR PostCSS bug on Netlify and monorepo symlinks

---

website/community/resources.md

As a team developing a GraphQL gateway, we wanted to be able to have an easy way to discover and search through the API without having to explore it using GraphiQL. Since, we were already using Docusaurus as documentation portal, it seems to be a perfect fit for generating API documentation.
We have developed a small plugin that converts a GraphQL schema into hyperlinked markdown pages compatible with Docusaurus docs.
Yes
Tests can be found in https://github.com/edno/docusaurus2-graphql-doc-generator/tree/main/tests
None

docs(v2): Add docusaurus2-graphql-doc-generator to community resources

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css

I've noticed that many docs sites have external links in the sidebar that are visually different from the usual ones.
Typically an icon serves as a visual marker for external link, so I added one to the corresponding sidebar item type.
Yes
```js
{
type: 'link',
label: 'External link',
href: 'https://example.com',
},
```

feat(v2): add icon to generic sidebar link

---

website/docs/deployment.mdx

Since `npx docusaurus` uses the first version of docusaurus, this command doesn't work.
I've also changed the custom SSH key implementation to use a generic github action.
Yes.
Irrelevant, this is a docs fix.

docs(v2): remove npx and use github action to configure ssh key

---

packages/docusaurus/package.json
yarn.lock

Fixes the project on Yarn v2, because postcss-loader has a peer on postcss, but it isnt provided by docusaurus, only implied by postcss-preset-env, so it breaks.  
yes
Its just a lockfile change, shouldnt break anything

chore(v2): PostCSS peer dep fix

---

packages/docusaurus-theme-classic/src/validateThemeConfig.js

I want to make the category title in the footer links disappear. This is particularly useful when you do not have many links, so displaying category headings for the links isn't necessarily appropriate. Conveniently, the footer plugin already handles this by testing if the title is null and if so skipping writing the h4 section. Thus, the only change is to allow a null value for the title in the classic theme validation.
Yes
I have tested this change change by setting a footer title to both to null:
```
footer: {
style: 'dark',
copyright: `Copyright © ${new Date().getFullYear()}`,
links: [
{
title: null,
items: [
{
label: 'Some Page',
to: 'page',
},
],
},
],
}
```
and verifying that there are no error and that the title is not displayed.

fix(v2): Allow null as valid for title of item in footer links. 

---

packages/docusaurus-theme-classic/package.json

./lib-next is the JS you swizzle so it is better for the end user if it's run through prettier during the build process.
Currently, it's not prettified due to the .prettierignore at the root, but it's a mistake

fix(v2): theme classic should have lib-next prettified

---

packages/docusaurus/bin/docusaurus.js

According to[ this article](https://dev.to/wgao19/why-running-yarn-upgrade-does-not-update-my-package-json-3mon
), if the project has previously uses a package with caret version, then updating without specifying the version range will not update the `package.json` file.
Therefore, we need to explicitly specify the version in notifier message in order to update the core package correctly.
And since usually not only the core package is used, in the message I also included other packages from @docusaurus scope so that they are also upgraded.
Yes
With two basic packages:
With several packages:

refactor(v2): improve notifier message

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-live-codeblock/src/theme/Playground/styles.module.css

Code blocks should rather be LTR by default.
Using RTLCSS ignore directive to force the RTL style: https://rtlcss.com/learn/usage-guide/control-directives/
Not totally sure RTL code blocks make any sense, but asked a question here: https://github.com/shadeed/rtl-styling/issues/13
Added the language as className in case the user wants to override this on a per-language basis

fix(v2): Code blocks should be LTR by default

---

packages/docusaurus-mdx-loader/src/index.js
packages/docusaurus-mdx-loader/src/remark/unwrapMdxCodeBlocks/__tests__/__snapshots__/index.test.js.snap
packages/docusaurus-mdx-loader/src/remark/unwrapMdxCodeBlocks/__tests__/fixtures/has-mdx-code-blocks.mdx
packages/docusaurus-mdx-loader/src/remark/unwrapMdxCodeBlocks/__tests__/index.test.js
packages/docusaurus-mdx-loader/src/remark/unwrapMdxCodeBlocks/index.js
website/docs/deployment.mdx
website/docs/guides/markdown-features/markdown-features-assets.mdx
website/docs/guides/markdown-features/markdown-features-react.mdx
website/docs/i18n/i18n-crowdin.mdx
website/versioned_docs/version-2.0.0-alpha.69/deployment.mdx
website/versioned_docs/version-2.0.0-alpha.69/markdown-features.mdx
website/versioned_docs/version-2.0.0-alpha.70/deployment.mdx
website/versioned_docs/version-2.0.0-alpha.70/markdown-features.mdx

Crowdin just added support for the .mdx extension.
It is not real MDX support, but they now interpret .mdx files as md instead of plain text.
The problem is that external tools like Crowdin totally mess-up with the JSX when we download back the translations.
Simple JSX like `<UserName name="seb"/>` works (ie string props), but as soon as you start to use `prop={{x,y,z}}` it messes-up.
The idea:
- Ability to wrap problematic jsx fragments into a special code block
- Crowdin sees a code block on mdx source upload => leaves it untouched, does not try to parse it as html
- Add a remark plugin to "unwrap" the code blocks so that JSX fragments remains interpreted inside Docusaurus
Note wrapping in this escape code block is an escape hatch for the mdx + Crowdin (or maybe other saas?) …

feat(v2): ability to "escape" JSX in MDX files as code blocks

---

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
website/docs/guides/markdown-features/markdown-features-inline-toc.mdx
website/docs/guides/markdown-features/markdown-features-tabs.mdx
website/versioned_docs/version-2.0.0-alpha.69/markdown-features.mdx
website/versioned_docs/version-2.0.0-alpha.70/markdown-features.mdx

Follow-up of https://github.com/facebook/docusaurus/pull/4278 so that Crowdin does not mess-up with our JSX in mdx files.
It should fix the production site deployment for locales

docs(v2): escape more jsx in mdx files for Crowdin

---

website/docs/using-themes.md

Code examples fail without `import React from 'react';`
Yes
Tried implementing on my project with the copied code from docs. `yarn start` succeeded, but served blank screen.
Didn't find any.

docs(v2): Fix examples by importing React

---

.github/workflows/build-size.yml

After investigating a security issue using `pull_request_target`, we decided to finally keep build size bot but using `pull_request`.
It solves the security issue, but this means the build size bot won't be able to post a PR comment if the PR is from a fork.
See https://github.com/preactjs/compressed-size-action/issues/54
See https://securitylab.github.com/research/github-actions-preventing-pwn-requests

misc: restore build size bot

---

website/src/data/users.js

Fix tags introduced by https://github.com/facebook/docusaurus/pull/4331
And clarify showcase instructions regarding tags

docs(v2): update showcase instruction regarding tags + fix site tags

---

packages/docusaurus-theme-classic/codeTranslations/fr.json
packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.js

The french site should only retrieve french search results
Also fix React key warning

fix(v2): search page results localization

---

packages/docusaurus-theme-classic/src/theme/BlogListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.tsx

Prevent duplicate search results related to tags pages

fix(v2): prevent useless blog pages to be in search results

---

packages/docusaurus/src/commands/writeTranslations.ts
packages/docusaurus/src/server/translations/__tests__/translationsExtractor.test.ts
packages/docusaurus/src/server/translations/translationsExtractor.ts
website/src/components/TeamProfileCards/index.js

Translations should always be extracted from `website/src` as it's were most React components will end up.
Fixes https://github.com/facebook/docusaurus/issues/4341

fix(v2): always extract translations from site/src

---

packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css
packages/docusaurus-theme-classic/src/theme/Layout/styles.css

Remove the minimum doc sidebar height equal to the viewport (i.e. 100vh) to make visible footer in it if there is very small content on any doc page (see screenshots below).
Yes
Before:
The footer is not visible in viewport, although there is very little doc content. 
After:
The footer is visible on screen with small content area (no need to scroll the page for this).
```
---
id: empty
title: Empty page
---
```

fix(v2): fit footer in viewport when content area is too small

---

website-1.x/docs/tutorial-create-pages.md

According to the file directory shown on this tutorial page (https://docusaurus.io/docs/en/tutorial-create-new-site), both the `docs` directory and the `website` directory are in the same level. The page currently states "_The docs folder is in the root of your Docusaurus project, one level above website._"
Yes
NIL
(If this PR adds or changes functionality, please take some time to update the docs at 
https://github.com/facebook/docusaurus, and link to your PR here.)

docs(v1): update phrasing for website dir relative to docs dir

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx
packages/docusaurus-theme-classic/src/theme/Tabs/styles.module.css

Trying to fix #3728
Currently, the thing is if tab sync is enabled, and going to switch from long-content tab to short one, we will not see a new tab on the screen. This is confusing for users and they have to manually scroll to the desired tab.
I suggest avoiding this unpleasant action by automatically focusing on the tab, but __only__ if really necessary (when the new tab is outside the viewport).
I intentionally  didn't do this via the new prop because it's a useful UX improvement that anyone using the synching tabs feature will need.
To achieve this, we had to move hideable navbar state to the context provider (by analogy with the announcement bar).
Yes
| ![ezgif com-gif-maker (14)](https://user-images.githubusercontent.com/4408379/107401 …

feat(v2): auto focus to tab if it is outside viewport

---

packages/docusaurus-theme-live-codeblock/src/theme/CodeBlock/index.js
packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.js
website/src/pages/examples/markdownPageExample.md

Attempt to fix #2986 without much large changes.  
Yes
Page with demo example - https://deploy-preview-4318--docusaurus-2.netlify.app/classic/examples/markdownPageExample#test

fix(v2): evaluate code in live editor on client only

---

packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/docs.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/LastUpdated/index.tsx

Follow-up of #4344 
Yes
Preview.

refactor(v2): format last updated date using Intl

---

packages/docusaurus-theme-classic/codeTranslations/ja.json

Slightly improve the Japanese translation file by removing the extra English period in `theme.docs.versions.unreleasedVersionLabel` (and with two other minor modifications).
Yes.
N/A
- [#4303](https://github.com/facebook/docusaurus/pull/4303)
- [#4351](https://github.com/facebook/docusaurus/pull/4351)

polish(v2): [theme-classic] slightly improve Japanese translation

---

packages/docusaurus/package.json
yarn.lock

Remove dead or unnecessary dependencies, currently for unknown reason docosaurus requires core-js@2 and babel is configured to use core-js@3, this was not a big issue for end customer as core-js@3 is installed as dependency of dependency, but its still and issue
https://github.com/facebook/docusaurus/blob/9a6d6a9adc0bb4a3d10d53df3b5ff18b7c3d94e7/packages/docusaurus/src/babel/preset.ts#L30-L32
yes
#3055

fix(v2): align installed core-js version with babel config

---

packages/docusaurus-utils/package.json
yarn.lock

Fix annoying warning during install packages by downgrade to lower version of  intl-locales-supported package:
> warning workspace-aggregator-295e903f-3b6c-4230-89f2-58b73a706e74 > @docusaurus/utils > intl-locales-supported@1.8.12: bad publish
Yes
Try to install packages.

chore(v2): avoid bad publish of intl-locales-supported

---

packages/docusaurus-plugin-pwa/package.json
packages/docusaurus-plugin-pwa/src/pluginOptionSchema.js
packages/docusaurus-plugin-pwa/src/registerSw.js
packages/docusaurus-plugin-pwa/src/sw.js
website/docs/api/plugins/plugin-pwa.md
website/docusaurus.config.js
website/netlify.toml
website/static/manifest.json
yarn.lock

Fix PWA issues reported in Jest after installing a PWA on desktop/mobile.
Also affecting Docusaurus site and should fix #4291 
Should also fix #3208
Reason: I believe the Workbox v6 had an undocumented breaking change in PrecacheController, reported this here: https://github.com/GoogleChrome/workbox/issues/2774
--- 
Another issue: it seems the events beforeinstallprompt and appinstalled should not be used anymore 😅 yet we rely on this
https://developer.mozilla.org/en-US/docs/Web/API/Window/appinstalled_event
https://firt.dev/pwa-2021#pwa-installation-triggers
I added usage of a new API `navigator.getInstalledRelatedApps()` (which is also only in Chrome afaik...) and also added a new useful default strategy `standalone` which basically means that the PWA is running as an installed app. …

fix(v2): PWA issues + improve docs

---

packages/docusaurus-theme-classic/src/theme/hooks/useTheme.ts

Based on "bug report" from[ Discord chat](https://discord.com/channels/398180168688074762/567414046073159701/818516542806294588). 
Indeed, since the user defines site preferred color mode in config file, we can take this information to set the color mode (used by `useTheme`) during site build. 
Yes
Try use `colorMode.defaultMode` with `dark` value and build the site.

fix(v2): set theme color mode for SSR

---

.circleci/config.yml
website-1.x/blog/2021-03-09-releasing-docusaurus-i18n.md

The Docusaurus v1 site can't deploy currently for some weird CircleCI env variable reasons + users using pull-bot on forks.
See https://github.com/facebook/docusaurus/issues/4394 for more context

fix(v1): fix v1 site deploy issues

---

.circleci/config.yml

For some reasons the Crowdin cli refuse to upload 1.14.7 translations with an obscure error message, and prevents the v1 site to deploy.
I'm figuring this out with their support.
---
Yet the v1 project does not contain those files:
https://crowdin.com/project/docusaurus
---
Using a fail-safe translation upload so that the v1 site deployment is able to complete even if there are some crowdin errors

fix(v1): Temp fix v1 site deployment: fail-safe on Crowdin upload translations error

---

packages/docusaurus-theme-bootstrap/src/theme/MDXPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogListPaginator/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/Footer/index.tsx
packages/docusaurus-theme-classic/src/theme/IconArrow/index.tsx
packages/docusaurus-theme-classic/src/theme/IconEdit/index.tsx
packages/docusaurus-theme-classic/src/theme/IconLanguage/index.tsx
packages/docusaurus-theme-classic/src/theme/IconMenu/index.tsx
packages/docusaurus-theme-classic/src/theme/LastUpdated/index.tsx
packages/docusaurus-theme-classic/src/theme/LayoutProviders/index.tsx
packages/docusaurus-theme-classic/src/theme/SearchMetadatas/index.tsx
packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx
packages/docusaurus-theme-classic/src/theme/TOCInline/index.tsx
packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx
packages/docusaurus-theme-classic/src/theme/Toggle/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-common/src/utils/docsPreferredVersion/DocsPreferredVersionProvider.tsx

Improve types for `theme-classic`
yes
if compilation passes everything is fine
ref; #3424

refactor(v2): add missing theme-classic types

---

packages/docusaurus-plugin-client-redirects/src/writeRedirectFiles.ts
packages/docusaurus-plugin-content-docs/src/theme/hooks/useDocs.ts
packages/docusaurus-theme-common/src/utils/generalUtils.ts
packages/docusaurus-utils-validation/src/__tests__/validationSchemas.test.ts
packages/docusaurus-utils-validation/src/validationUtils.ts
packages/docusaurus/src/client/exports/useGlobalData.ts
packages/docusaurus/src/client/flat.ts
packages/docusaurus/src/commands/writeHeadingIds.ts
packages/docusaurus/src/server/translations/translationsExtractor.ts
packages/docusaurus/src/webpack/plugins/WaitPlugin.ts
packages/docusaurus/tsconfig.json

Fix some of simpler warnings reported by eslint
yes
ref; #3424

refactor(v2): correct some of type errors reported by eslint

---

packages/docusaurus-plugin-content-blog/src/__tests__/linkify.test.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-blog/src/markdownLoader.ts
packages/docusaurus-plugin-content-blog/src/types.ts
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/translations.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/translations.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/versions.test.ts
packages/docusaurus-plugin-content-docs/src/docs.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/markdown/__tests__/linkify.test.ts
packages/docusaurus-plugin-content-docs/src/markdown/linkify.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-plugin-content-docs/src/versions.ts
packages/docusaurus-utils/src/markdownLinks.ts

This PR is a continuation of work done in #4391 that aligns names of properties, 
i'm unsure what is a politic here on changes, that's why i prepared 2 separate PR's for this
yes
there is no change in functionality and all unit test should pass, linking still should work in docs and in blog, 
it can be tested by clicking in one of links in docs, eg. 
https://deploy-preview-4391--docusaurus-2.netlify.app/classic/docs/contributing#get-involved
#4391

refactor(v2): merge linkify function used in blog and docs and align properties

---

packages/docusaurus/src/server/__tests__/brokenLinks.test.ts
packages/docusaurus/src/server/brokenLinks.ts

I have a project in which I did not want the burden of updating the `sidebar.js` file to fall upon each contributor, nor did I want them to have to add frontmatter to their files. My solution to that was to export a JSON structure which is the result of `walk`ing the `docs` dir and using all located files and directories as the doc and category identifiers. This all works totally fine and users can happily add markdown files with any name and they will show up 1-to-1 on the generated site.
For example, they may want to have a folder/page called `Environment Setup/VS Code`, so they would create a file: `docs/Environment Setup/VS Code.md`.
**The problem:** When users want to link between pages, they create a link in the usual way:
```markdown
[FAQ](./FAQ)
```
But if the destination page has …

fix(v2): broken link checker should not report false positives when using encoded chars

---

packages/docusaurus-module-type-aliases/src/index.d.ts

add missing `ExecutionEnvironment`, `BrowserOnly`, `isInternalUrl` to known type aliases
if it compiles its working
ref; #3424

refactor(v2): add ExecutionEnvironment, BrowserOnly, isInternalUrl to type aliases

---

packages/docusaurus-theme-classic/package.json
yarn.lock

react-toggle@4.1.1 doesn't have React 17 as a peer dependency.
Yes
Not needed, it's a patch change on the library.

chore(v2): upgrade react-toggle to v4.1.2

---

packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx
website/src/pages/examples/markdownPageExample.md

In #4315 a small regression was made related with using of `<pre>` tag in Markdown markup. Usually it is not necessary to use this tag, but legacy content pages (e.g., when migrating from other platforms) can contains it.
However, when using pre in the MDX will be removed all line breaks (see https://github.com/mdx-js/mdx/issues/1095). So it shouldn't be used anyway and users will have to use triple backtick or CodeBlock component to proper formatting of code blocks.
Yes
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR …

fix(v2): allow using pre tag in Markdown directly

---

packages/docusaurus-plugin-pwa/package.json

Yup!
Adding
```yaml
packageExtensions:
"@docusaurus/plugin-pwa@*":
peerDependencies:
"@babel/core": "^7.0.0"
```
removes the warning
N/A

fix(v2): add missing peer dep on @babel/core

---

packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-pages/src/index.ts
packages/docusaurus-plugin-sitemap/src/index.ts
packages/docusaurus-theme-classic/src/index.ts
packages/docusaurus-types/package.json
packages/docusaurus-types/src/index.d.ts
packages/docusaurus-utils-validation/src/validationUtils.ts
packages/docusaurus/src/commands/swizzle.ts
packages/docusaurus/src/server/plugins/init.ts

Improve types in docusaurus, 
yes

refactor(v2): correct plugin types

---

packages/docusaurus/src/commands/writeHeadingIds.ts
packages/docusaurus/src/server/translations/translationsExtractor.ts
packages/docusaurus/src/server/utils.ts

the write-heading-ids cli did not work on Windows
Reported here: https://github.com/facebook/docusaurus/pull/4222#issuecomment-795517329

fix(v2): Fix writeHeadingIds on Windows due to non-posix paths

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/LocaleDropdownNavbarItem.tsx
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/package.json
packages/docusaurus/src/constants.ts
packages/docusaurus/src/server/__tests__/__snapshots__/i18n.test.ts.snap
packages/docusaurus/src/server/__tests__/i18n.test.ts
packages/docusaurus/src/server/i18n.ts
website/docs/i18n/i18n-tutorial.md
website/docusaurus.config.js
yarn.lock

In most situations, we shouldn't need to provide a `i18n.localeConfigs` because the locale direction and locale labels  can generally be inferred from the locale itself, considering it is compliant with BCP 47 locales and Node 14 Intl API is able to get language labels.
Also made it possible to run `yarn start --locale fa` even if `fa` is not in the config: it will just print a warning instead of throwing.
yes
tests and v2 site

feat(v2): infer default i18n locale config from locale code

---

packages/docusaurus-theme-classic/codeTranslations/ko.json
website/docusaurus.config.js

malformed json prevents usage of the korean locale
(+ make staging i18n faster by removing versioning)

fix(v2): Fix i18n staging deployment due to json typo

---

packages/docusaurus-theme-classic/codeTranslations/ko.json

commit typo: fb header should not be added to json files

chore: fb json header commit typo

---

packages/docusaurus-utils-validation/package.json
packages/docusaurus-utils-validation/src/Joi.ts
packages/docusaurus-utils-validation/src/__tests__/validationSchemas.test.ts
packages/docusaurus-utils-validation/src/validationSchemas.ts
packages/docusaurus-utils-validation/src/validationUtils.ts

`@docusaurus/utils-validation` depends on itself by mistake.
This removes the cyclic dependency warning:

chore(v2): Joi cyclic dep warning

---

.eslintrc.js
packages/docusaurus-module-type-aliases/package.json
packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus/src/client/exports/ComponentCreator.tsx
packages/docusaurus/src/client/exports/Head.tsx
packages/docusaurus/src/client/exports/Interpolate.tsx
packages/docusaurus/src/client/exports/Link.tsx
packages/docusaurus/src/client/exports/Translate.tsx
packages/docusaurus/src/client/exports/useBaseUrl.ts
yarn.lock

Improve types exposed to end user, 
This change has been extracted from #4433
yes

refactor(v2): correct client types and type aliases

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/update-code-translations.js
packages/docusaurus-theme-classic/update-code-translations.test.js
packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.js
packages/docusaurus/src/server/translations/translationsExtractor.ts

- Test to ensure that theme translations remains extractable over time
- Test to ensure the `update-code-translations` script is run after new translations are added to the theme code
- Fix Live code block theme code refactored, leading to unability to extract translations
- Fix ordering issue for the ___DESCRIPTION in generated `base.json` 
- Translate `Version: v1` label in theme

fix(v2): i18n fixes

---

packages/docusaurus-theme-classic/src/theme/hooks/useTheme.ts

refactor(v2): add missing types to theme-classic useTheme

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts

fixes #4465
yes
create md(x) file in project with
```jsx
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
<Tabs values={[ {label: 'Android', value: 'android'}, {label: 'iOS', value: 'ios'}, {label: 'Web', value: 'web'}, ]}>
<TabItem value="web">Web</TabItem>
<TabItem value="android">Android</TabItem>
<TabItem value="ios">iOS</TabItem>
</Tabs>
```
currently there is no component gallery or place where specific test can be added
simple regression test can be done by checking: https://deploy-preview-4468--docusaurus-2.netlify.app/docs/typescript-support

fix(v2): select correct tab when items are incorrectly ordered

---

website/docs/i18n/i18n-introduction.md
website/docs/lifecycle-apis.md
website/docs/migration/migration-overview.md
website/docs/migration/migration-translated-sites.md

Complete the i18n doc to cover everything that was implemented:
- Plugin lifecycle APIs for plugin authors
- Migration guide for Docusaurus v1 Crowdin users

docs(v2): Add missing i18n docs: API lifecycles + Crowdin migration guide

---

.github/workflows/lint.yml
package.json

With #4447 we now lint on Github Actions and also use setup-node actions, enabling GH actions "problem matchers".
The problem is that now each PR has a list of reported lint errors in the files tab, like here: https://github.com/facebook/docusaurus/pull/4468/files
This is distracting PR reviews, so I'm using eslint `--quiet` option to ensure we don't care about warnings in CI and they don't end up in the PR.
cc @SamChou19815 , any alternative to suggest?

chore: fix GH actions lint problem matchers issue in PR

---

website/docs/guides/docs/sidebar.md

The [Sidebar Object](https://v2.docusaurus.io/docs/sidebar#sidebar-object) Section contains a statement:  `greeting and doc1 are both sidebar item`.
Here the _sidebar item_ links to broken URL ie. https://v2.docusaurus.io/docs/sidebar#sidebar-item
Updated the link with https://v2.docusaurus.io/docs/sidebar#understanding-sidebar-items
Yes.

docs(v2): fixed broken link in sidebar documentation

---

examples/classic/README.md

A very small typo as found there https://gitlab.com/nomadic-labs/coq-tezos-of-ocaml/-/merge_requests/42#note_529524133

chore(v2): fix typo in classic init template

---

website/docs/guides/docs/docs-multi-instance.mdx

- resolve grammar issue in Setup heading and rephrase to (subjectively) more clear wording (L50, L55)
- more consistent wording in first line of Versioned paths heading (L143)
fix grammar issues and improve wording in https://v2.docusaurus.io/docs/docs-multi-instance
L50/55: grammar errors
L143: clarify each _plugin_ instance ...; doing so also matches the wording used under "Tagging new versions" (L167)
yes

docs(v2): fix grammar and improve wording

---

CHANGELOG.md
packages/docusaurus-migrate/README.md
packages/docusaurus-migrate/package.json
packages/docusaurus/src/server/__tests__/__snapshots__/brokenLinks.test.ts.snap
packages/docusaurus/src/server/brokenLinks.ts
website-1.x/docs/api-pages.md
website-1.x/versioned_docs/version-1.10.x/api-pages.md
website-1.x/versioned_docs/version-1.9.x/api-pages.md
website/community/resources.md
website/docs/migration/migration-automated.md
website/docs/migration/migration-translated-sites.md
website/docs/search.md
website/versioned_docs/version-2.0.0-alpha.71/search.md
website/versioned_docs/version-2.0.0-alpha.72/search.md

docs(v2): fixed typos

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/hooks/useHideableNavbar.ts
packages/docusaurus-theme-classic/src/theme/hooks/useScrollPosition.ts
packages/docusaurus-theme-classic/src/types.d.ts

This change limits amount of NavBar component updates by not updating it on every keyframe while user scroll through website
fixes #4454
<details>
<summary>Chrome</summary>
**New "performance"**
**Old "performance"**
</details>
<details>
<summary>Firefox</summary>
**New flame chart**
**Old flame chart**
</details>
yes
open website in browser and start scrolling

perf(v2): reduce amount of component updates while scrolling

---

website/docs/contributing.md

Links to Github templates do not work
Yes
Not applicable
Not applicable

docs: fix link to issue template

---

website/src/pages/versions.js

Add missing link to previous - legacy - v1 version of page in v2 docs
yes

docs(v2): add missing version link to legacy (v1) version of website

---

.github/workflows/lint.yml
.github/workflows/migration-cli.yml
.github/workflows/v1-tests-windows.yml
.github/workflows/v1-tests.yml
.github/workflows/v2-build-blog-only.yml
.github/workflows/v2-build-size-report.yml
.github/workflows/v2-tests-e2e.yml
.github/workflows/v2-tests-windows.yml
.github/workflows/v2-tests.yml

while working on #4404 i noticed that default timeout for github actions is set to 6h, in case of issues in webpack like here: https://github.com/facebook/docusaurus/runs/2181853194?check_suite_focus=true we can run into cases when job is never going to be finished.
default value is set to 360min (6h) and this change reduces it to 30min (no job for now is executed for longer than 12min on linux and 20min on windows)
ref: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
yes

ci: change default actions timeout from 6h to 30m

---

packages/docusaurus-utils/src/__tests__/__snapshots__/parseMarkdown.test.ts.snap
packages/docusaurus-utils/src/__tests__/parseMarkdown.test.ts
packages/docusaurus-utils/src/index.ts

remove invalid warning about duplicated title in pages
yes
unit tests should pass and warning for pages should disappear for src/pages/examples/markdownPageExample.md
#4485

fix(v2): do not warn about duplicated title for pages

---

website/docs/guides/markdown-features/markdown-features-headings.mdx

fix markdown headings level 4
Yes
Nope!
Nope!

docs(v2): fix markdown headings level 4

---

website/docs/search.md

This PR adds a section in the search docs on the additional configuration required when running your own DocSearch crawler.
Related: #454
Yes
N/A
N/A

docs(v2): config for self-hosted docsearch crawler

---

packages/docusaurus/package.json
website/docs/lifecycle-apis.md
yarn.lock

`postcss-present-env` is no longer used after changes done in #4355, this pr updates documentation and removes this package from dependencies
this change has been extracted from #4404
https://github.com/facebook/docusaurus/pull/4355/files#diff-0c33a9be9b9aca4b4536266cc9c2b8db8131f03a7bc2cec8c5ccf27ea63cbc82L76-R76
yes
#4355, #4404

fix(v2): remove no longer used postcss-present-env from dependencies

---

website/docs/cli.md

Minor run-on sentence in the docs under CLI commands on `swizzle`.
yes

docs(v2): fix run-on sentence

---

packages/docusaurus-init/templates/classic/docs/create-a-page.md

Improve the initial template
For now, if a new user creates the project using the CLI, it opens at http://localhost:3000.
It is convenience for the user to continue reading at the guide that already shows on http://localhost:3000.
But it's missing an" export" command on the guide and it makes the guide doesn't work.
This commit is consistent with the official guide at https://docusaurus.io/docs/creating-pages (current version: 2.0.0-alpha.72)
Yes
No
#4320

docs(v2): add a missing "export" from the initial template

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx

When you set an invalid `docId` inside `docusaurus.config.js`, the error message that's thrown by `DocNavbarItem` does not let you know the list of existing `docId`.
Yes.

fix: DocNavbarItem error message

---

packages/docusaurus-init/templates/classic/docs/create-a-blog-post.md

Improve the initial template. (`classic` template)
After creating the initial template, the guide shows on the http://localhost:3000/docs/create-a-blog-post
says the created blog will be available at http://localhost:3000/blog/greetings, but it's not, because of lacking of a `slug` config on the metadata of the md file.
This commit adds the missing slug config
Yes
#4320

docs(v2): add a missing slug from the initial template

---

website/docs/i18n/i18n-tutorial.md

Fixed broken link in `i18n-tutorial.md`
In [Translate JSON Files](https://docusaurus.io/docs/i18n/tutorial#translate-json-files) section.
Run the write-translations redirects to https://docusaurus.io/docs/cli#docusaurus-write-translations, which is broken
Instead it should redirect to https://docusaurus.io/docs/cli#docusaurus-write-translations-sitedir
Yes

docs(v2): fixed broken link in i18n-tutorial.md

---

packages/docusaurus/src/commands/build.ts

Typo in the build script makes Docusaurus bail-out of the build process too soon and it does not build all locales provided by the user.
Fixes #4567

fix(v2): fix i18n isLastLocale bug preventing docusaurus from building some locales

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/commands/__tests__/buildRemoteBranchUrl.test.ts
packages/docusaurus/src/commands/buildRemoteBranchUrl.ts
packages/docusaurus/src/commands/deploy.ts
website/docs/api/docusaurus.config.js.md
website/docs/deployment.mdx

To have a way to deploy it to a github which is not running under the port 22.

feat(v2): docusaurus deploy: ability to configure port in git url

---

packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/commands/writeTranslations.ts
packages/docusaurus/src/server/plugins/index.ts
website/docs/lifecycle-apis.md

i18n perf: the docs plugin read twice the markdown files, because it tries to load content again when trying to retrieve translation files to use.
Before, reloading the content that has already been loaded:
```js
async getTranslationFiles() {
return getLoadedContentTranslationFiles(await this.loadContent());
},
```
After: reusing the content that has already been loaded:
```js
async getTranslationFiles({content}) {
return getLoadedContentTranslationFiles(content);
},
```
yes
Not sure how. It's hard to prevent a plugin author to call `this.loadContent()` anywhere and have a perf issue, including maintainers in core plugins. It's not performant but it works.

fix(v2): i18n perf issue: getTranslationFile() should not load content again

---

website/community/resources.md

As a member of a team that works with Protobuf contracts, we have a need for developer-driven documentation that satisfies both the consumers and builders of APIs driven by these contracts. This documentation should be driven by the Protobuf contracts they document, while being extensible with human-provided context.
We already use Docusaurus at my organization for JSON APIs, but we lack the tooling required to document RPC services backed by Protobuf contracts. I've decided to leverage the Docusaurus plugin framework to provide this tooling.
[Protobuffet](https://protobuffet.com/) is a Docusaurus preset that generates doc files using Protobuf contracts. In this PR, I'm including this preset in the Community Plugins section of the docs. Check out the [Protobuffet …

docs(v2): Include docusaurus-protobuffet to community plugins

---

website/docusaurus.config.js

ko and zh-CN have enough translations on Crowdin (according to threshold we defined in https://github.com/facebook/docusaurus/issues/3526)
Let's enable those locales in production!

docs(v2): i18n site: enable ko + zh-CN locales

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx

Should fix #4589 
Currently we use the scroll event to adjust the correct height of the doc sidebar when displaying the announcement bar. To do this we toggle the class if the user scrolls to the top of a page, which in turn causes the while DocSidebar component to be re-rendered at this moment. Since only items in this component are the most memory-consuming elements, I propose to memoize them to mitigate that issue. 
https://github.com/facebook/docusaurus/blob/f12e8b596d7af688e1800bdcdcc8aa7ec30f9d4c/packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx#L199-L201
Yes
See To Reproduce section in #4589

perf(v2): avoid rerender of sidebar items while scrolling

---

packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx
website/src/pages/examples/markdownPageExample.md

Fixes #4534
Yes
Preview - https://deploy-preview-4598--docusaurus-2.netlify.app/examples/markdownPageExample#pipe

fix(v2): render escaped HTML entities inside code properly

---

packages/docusaurus-theme-classic/src/theme/LayoutHead/index.tsx
packages/docusaurus-theme-classic/src/theme/Seo/index.tsx
packages/docusaurus-theme-common/src/utils/useThemeConfig.ts

Fixes #4549
Yes
Try remove `title` prop from `Layout` component of any page and make sure that title from config has been used.

fix(v2): use page title from config if not set

---

website/docs/using-themes.md

Hi there,
It looks like there is a typo in the heading.
Reduction of the typo cardinality in the open source world.
Yes
None
None

docs(v2): heading typo

---

.github/workflows/v2-build-time-perf.yml

Since adding new ko + zh-CN locales, the GH workflow that monitors build times are under 10min is now above 10min and the CI fails constantly.
Let's only build English site in this workflow. 
We'll probably enable for all locales again once we have webpack5 caching system that works across multiple locales

chore(v2): CI: do not build all locales when monitoring build time perf

---

admin/scripts/test-release.sh

While working on https://github.com/facebook/docusaurus/pull/4582
I noticed a weird failure in the Yarn2 e2e test after I updated init template to use a newly created sidebar item:
https://github.com/facebook/docusaurus/runs/2334693775?check_suite_focus=true
The e2e workflow:
- build packages
- publish packages to verdaccio (self-hosted npm repo)
- init new site with published packages
- try to start/build the newly initialized site
When using Yarn2, it seems like for some weird reasons, it did not download the packages that were just published to Verdaccio, but another canary version from npm instead. Not sure what happens exactly but it seems to be the case for a while, and the CI is probably responsible for a lot of downloads on this particular canary release: …

chore(v2): fix yarn2 end2end test by using lerna publish --exact

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/Navbar/index.tsx
packages/docusaurus-theme-classic/src/theme/Toggle/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
yarn.lock

A lightweight and simplified alternative to react-toggle built on functional component/hooks instead on class as in original component. Also I deliberately not using [touch events](https://github.com/aaronshaf/react-toggle/blob/master/src/component/index.js#L146-L148), because I think a mobile user can just tap on toggle to switch mode ( not sure if someone used gestures for this).
As another advantage, we get rid of another external dependency and have more control over this component.
Yes
No breaking changes, CSS class names are same.

refactor(v2): replace react-toggle with own implementation

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx

The sidebar is a bit complex currently. 
I split it into multiple hooks and components, and apply `memo` around a new `DocSidebarItems` component.
This should not change any existing behavior
Related to https://github.com/facebook/docusaurus/issues/4589

refactor(v2): simplify and optimize sidebar

---

packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css
packages/docusaurus-theme-common/src/utils/ThemeClassNames.ts
website/docs/styling-layout.md

Make the docsc-wrapper global class name consistent with other wrapper classnames 
Follow up of https://github.com/facebook/docusaurus/pull/4511#discussion_r611264310)

refactor(v2): rename class main-docs-wrapper to docs-wrapper

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx

The toggle callback does not need to change (trigger useless sidebar re-renders) and can use the functional setState form

refactor(v2): toggleResponsiveSidebar => more stable callback

---

packages/docusaurus-utils/src/__tests__/markdownParser.test.ts
packages/docusaurus-utils/src/markdownParser.ts

Should fix #4634.
Yes
Suppose we have doc without defined title in frontmatter:
```
---
id: test
---
```
Results:
| ![image](https://user-images.githubusercontent.com/4408379/115155859-637d0200-a08a-11eb-9e13-c5b601787780.png) | ![image](https://user-images.githubusercontent.com/4408379/115155969-d71f0f00-a08a-11eb-9307-1ed2d5b57837.png) |

fix(v2): parse headings directly after h1 properly

---

packages/docusaurus-plugin-content-docs/src/__tests__/options.test.ts
packages/docusaurus-plugin-content-docs/src/options.ts

Validation error prevents disabling default admonitions as documented under <https://docusaurus.io/docs/presets#official-presets>.
Yes
Automated tests were added to check `false` is accepted, and `true` is rejected.

fix(v2): fix validation rejecting admonitions false

---

packages/docusaurus-utils/src/__tests__/markdownParser.test.ts
packages/docusaurus-utils/src/markdownParser.ts

Resolves #4635.
Yes
Suppose we have following doc:
```
---
id: test
---
import BrowserWindow from '@site/src/components/BrowserWindow';
```
Results:
| ![image](https://user-images.githubusercontent.com/4408379/115275899-0d23c800-a14b-11eb-9665-55a06698a5e9.png) | ![image](https://user-images.githubusercontent.com/4408379/115276019-347a9500-a14b-11eb-97f1-d01ccec20da3.png) |

fix(v2): ignore imports when h1 heading parsing

---

packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx
packages/docusaurus-theme-classic/src/theme/LayoutHead/index.tsx
packages/docusaurus-theme-classic/src/theme/Seo/index.tsx

Fix #4666.
The `Head` component of docusaurus is re-export of `Helmet`. According to Helmet docs, items rendered later in Head will override the ones rendered earlier. Currently, there are two places where title is changed when blog post is rendered: `<Layout>` and `<Seo>`, and `<Seo>` happens later than `<Layout>`.
When rendering a blog post page, it starts in `BlogPostPage`, which has the correct title:
https://github.com/SamChou19815/docusaurus/blob/d21444b6fb03db87796068fd476f1d10af986182/packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.tsx#L24-L29
Then it starts render `BlogPostItem`, which has a SEO component that will rerender header: https://github.com/SamChou19815/docusaurus/blob/792f4ac6fb8d7e1124f4b9f5151a827929e6dc50/packages/docusaurus-theme-classic/src/theme/Blo …

fix(v2): Unbreak blog post title by handling title fallback in `LayoutHead`

---

website/static/_redirects

SEO tools report we have a few external links targeting Docusaurus v1 URLs, but these links now show a v2 404 page.
We can:
- redirect those URLs to the v1.docusaurus.io subdomain (same page)
- redirect those URLs to the v2 homepage (v1 pages might not exist in v2) and try to pass the "SEO juice" to v2
I choose the first solution

chore: add some redirects to v1.docusaurus.io

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css

For design consistency, it is better to have the same external icon positioning in external doc links. Subjectively, it looks cleaner and neater.
Yes
Demo on https://mikro-orm.io/docs/installation/ site as example:
| ![image](https://user-images.githubusercontent.com/4408379/116004260-92efb980-a60a-11eb-9b7d-c26689813ed1.png) |  ![image](https://user-images.githubusercontent.com/4408379/116004272-9edb7b80-a60a-11eb-84ea-033ba51302fb.png) |

refactor(v2): align external icon on right

---

packages/docusaurus-plugin-content-docs/src/__tests__/docFrontMatter.test.ts
packages/docusaurus-plugin-content-docs/src/docFrontMatter.ts

We used to accept "" as valid custom_edit_url value before adding the frontmatter validation system.
Let's keep it this way to avoid annoying existing users (see https://github.com/demisto/content-docs/pull/616#issuecomment-827087566)
yes
test

fix(v2): accept empty/null custom_edit_url docs frontmatter for retrocompat

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/docs.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-utils/src/__tests__/markdownParser.test.ts
packages/docusaurus-utils/src/markdownParser.ts
packages/docusaurus/src/commands/__tests__/writeHeadingIds.test.ts
packages/docusaurus/src/commands/writeHeadingIds.ts

Fixes https://github.com/facebook/docusaurus/issues/4665#issuecomment-825831367 + handle fixed anchor syntax
Keep behavior we had before:
- `frontmatter.title` controls page meta in priority
- markdown `# title` controls page h1 heading in priority
We should rather not use fixed anchor ids syntax on top level h1 headings, as user should not use h1 headings in his doc normally anyway:
- `writeHeadingIds` cli will not write custom anchor ids for h1 md titles, and `# myTitle` remains untouched
- a markdown title as `# myTitle {#my-anchor}` will now parse correctly `title = myTitle`
yes
test

fix(v2): fix title logic (meta vs heading) + ignore fixed anchor id syntax

---

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx

Too often people ask about Java / PHP syntax highlighting being not supported out-of-box (cr #4535, #4720). Although this is already specified in the documentation, I guess we can benefit from some more emphasis.
Yes

docs(v2): emphasize subset of markdown supported languages

---

website/docs/api/plugins/plugin-google-analytics.md
website/docs/api/plugins/plugin-google-gtag.md

As noted in #4678 it was hard to notice that the google-analytics-related plugins were only able in production builds. Notes that clarify this have been added, following the style of the _ideal-image_ plugin. Additionally, a common misconception between Tracking IDs (UA-) and Measurement IDs (G-) has been explained, and [Google's Tag Assistant](https://tagassistant.google.com/) has been linked to aid developers in debugging.
Yes.

docs(v2): specify google-analytics and gtag plugins

---

packages/docusaurus-utils/src/__tests__/markdownParser.test.ts
packages/docusaurus-utils/src/markdownParser.ts

Fix #4726 (origin: #4713)
Yes.
1. Clone my prepared [repo](https://github.com/nam-hle/client-docusaurus) and install
2. Start. Everything should work well
3. Incremental uncomment import statements in docs/intro.md, the compilation time will increase exponentially from around 15 imported components.
4. Apply the changes in `packages/docusaurus-utils/src/markdownParser.ts` of this PR into the corresponding compiled file (at `client-docusaurus/node_modules/@docusaurus/utils/lib/markdownParser.js`) of my repo. 
5. Do the step 2-3 again to see the compile time improvement.
Please feel free to suggest any concrete performat tests that need to do.
N/A.

fix(v2): optimize markdown parser regex (fix #4726)

---

packages/docusaurus-utils/src/__tests__/markdownParser.test.ts
packages/docusaurus-utils/src/markdownParser.ts

Currently the markdown title can be parsed after some kind of import statements. For example:
```md
import Component1 from '@site/src/components/Component1';
import './styles.css';
Lorem Ipsum
```
This PR allow the most of import [syntaxes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import). 
```md
import DefaultComponent from '@site/src/components/Component1';
import DefaultComponent2 from '../relative/path/Component2';
import * as EntireComponent from './relative/path/Component3';
import { Component4 } from "double-quote-module-name";
import { Component6 as AliasComponent6 } from "module-name";
import DefaultComponent8, { DefaultComponent81 } from "module-name";
import DefaultComponent9, * as EntireComponent9 from "module-name";
import _ from …
```

fix(v2): markdown title parser should ignore all forms of MDX import statements 

---

website/package.json
website/waitForCrowdin.js
yarn.lock

Crowdin does not support concurrency well, and emit 409 errors in case of concurrent translation downloads
We have 2 Netlify deployments triggered on each PR merge: prod and i18n staging.
One of them often resulting in a 409 error.
And the prod website may not deploy immediately, which can be annoying after a new release (see https://github.com/facebook/docusaurus/discussions/4702)
Solution: a node script to wait for Crowdin API to report there is no build in progress (ie, it's safe to download the translations)
Note: I think concurrent uploads can also lead to 409 errors but it is less frequent (upload is generally faster)
yes
CI

chore(v2): Fix Crowdin 409 issues in CI

---

website/waitForCrowdin.js

Follow-up of https://github.com/facebook/docusaurus/pull/4739
Unfortunately, it did not work as the 2 deployments call the wait script at the exact same time.
Let's make prod deployment download Crowdin translations first, and then make i18n-staging wait until Crowdin can accept a new translation download

chore(v2): delay i18n-staging deployment to avoid Crowdin 409 errors

---

website/src/pages/examples/markdownPageExample.md

Relative Markdown image path used in dogfooding example page lead to prod deployment issues on localized sites.
Referencing assets in /static using a relative path is not good, as the assets are not uploaded to Crowdin and the localized doc can fail to resolve it

chore(v2): fix prod deployment due to bad image path

---

website/docs/i18n/i18n-git.md
website/docs/i18n/i18n-tutorial.md

Looks like legacy code from previous versions remains to be fixed
Yes.

docs(v2): fix i18n doc: bad i18n page plugin path in code sample

---

packages/docusaurus/src/webpack/base.ts

Some libs (many from Sindre Sorhus) use too recent ES syntax and should be transpiled with Babel
copy-text-to-clipboard contains `try {} catch {}` for example
Not doing this means we have some older browsers (like Edge 18 released in nov 2018) not supported while it could easily.
Noticed this while testing browser support of Docusaurus in https://github.com/facebook/docusaurus/pull/4766
yes
preview + inspecting JS output + testing on Edge 18

fix(v2): transpile libs with too recent syntax with babel

---

package.json

Canary versions are still named alpha

chore: fix canary version name

---

admin/verdaccio.yaml
packages/docusaurus-plugin-content-docs/src/theme/hooks/useDocs.ts
packages/docusaurus-theme-classic/src/theme/hooks/useDocs.ts
packages/docusaurus-theme-common/src/index.ts
tsconfig.json

It's safer to ensure that TS files can be transpiled independently.
Ie, transpiled by other tools like Babel or esbuild. 
We use esbuild-loader in https://github.com/facebook/docusaurus/issues/4765 on the Docusaurus website now, and it is a recommended option

chore(v2): TypeScript, use isolatedModules

---

packages/docusaurus-plugin-content-blog/src/__tests__/blogFrontMatter.test.ts
packages/docusaurus-plugin-content-blog/src/blogFrontMatter.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-utils-validation/src/__tests__/validationUtils.test.ts
packages/docusaurus-utils-validation/src/validationUtils.ts
website/docs/blog.md

From #4591.
* Complete the BlogPostFrontMatter typing and the corresponding Joi schema validator in _packages/docusaurus-plugin-content-blog/src/blogFrontMatter.ts_
* Add unit tests
* Display friendly messages for wrong schemas:
* @slorber: Can you explain the sentence: _"try to use the frontmatter TS types in the theme?"_ ?
I found the after parsing the frontmatter use `gray-matter` package, the `date` field will be converted to a `Date object`, not a raw string. But we are treating it as a string. Currently there is no problem about it, but maybe furture.
Yes
Unit test.

fix(v2): improve BlogPostFrontMatter schema validation

---

packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css

After collapsing of doc sidebar,  doc content container width should increase slightly. This is not happening now, probably because of this change in Infima https://github.com/facebookincubator/infima/pull/62
Yes
Try to collapse doc sidebar and make sure that width of doc content container has increased.

fix(v2): unbreak enhanced width of doc item wrapper

---

packages/docusaurus-theme-classic/src/theme/Layout/styles.css

Overall, this is bad approach. And in our case, it can cause lags when switching color mode (especially if there is lot of content on a page), see for example:
Yes
Preview.

refactor(v2): remove transition on body element

---

packages/docusaurus-theme-classic/src/theme/Footer/index.tsx

Actually it should have been done with the [last Infima update](https://github.com/facebook/docusaurus/pull/4689
), but I did not have time to mention it.
However we still have one a11y error (`h5`) related with headings -- I want to fix this in our fork of `remark-admonitions` (which will be placed in docusaurus organization, hopefully)
Yes
Preview - no visual changes.

fix(v2): fix minor a11y issue with headings

---

packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx
packages/docusaurus-theme-classic/src/theme/hooks/useHideableNavbar.ts
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/useChangeRoute.ts

Fixes #4794
Using more reliable logic to determine that the route has actually changed (currently, there are false positives on reloads of same page).
As a result, the scroll position is lost during hot reloading.
Yes
See To Reproduce section in #4794

fix(v2): do not focus on skip link if page refreshed

---

packages/docusaurus-plugin-content-blog/src/__tests__/blogFrontMatter.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/docFrontMatter.test.ts
packages/docusaurus-plugin-content-docs/src/docFrontMatter.ts

The continuation of #4591.
Yes.
Unit test.
#4759.

feat(v2): exhaustive docs frontmatter schema

---

packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/index.ts

We use `normalizeUrl` a lot, and currently, there is no known issue. But it's always the best practice to use the pure function.
I also add some code to keep the ts compiler silent in the test file. Please tell me if it's irrelevant, and I will remove it :)
Yes
Review

refactor(v2): purify normalizeUrl

---

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx

dark mode color seems to be missing in this css code sample:

docs(v2): fix css snipped with missing color

---

website/docs/guides/docs/sidebar.md

Fixed a typo on `highlight-start` in the section **Hideable sidebar**.

docs(v2): Fix typo in doc: sidebar.md

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-common/package.json
packages/docusaurus-theme-live-codeblock/package.json
yarn.lock

After modified GitHub theme has been reverted, I think we can safely use again caret version as it was originally.
https://github.com/FormidableLabs/prism-react-renderer/commit/0040cd472d20cb8863a1740ee88fd276e8497601
Yes
Preview

chore(v2): unlock prism-react-renderer version

---

website/community/2-resources.md

Added new option for PDF generation seeing as docusaurus-pdf doesn't work beyond 2.0.0.-alpha73, as establised in [bug #29](https://github.com/kohheepeace/docusaurus-pdf/issues/29).

docs(v2): add mr-pdf to resources

---

website/docusaurus.config.js

The Java syntax highlight is finally broken in [docusaurus.io](docusaurus.io). (Weird I say finally here, but [no-one had any idea why it worked before](https://github.com/facebook/docusaurus/issues/4720#issuecomment-831950301).) Now is good time to add `java` to `additionalLanguages` and make the site consistent with our documentation.
Fix #4845.
Yea

fix(v2): fix Java syntax highlight in website

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/SearchNavbarItem.tsx
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/styles.css
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/styles.module.css

Related to https://github.com/facebook/docusaurus/pull/4822#issuecomment-846927245
Since Infima v24 (#4855) from last navbar item has been removed _unnecessary_ padding-left, so we can fix the little bug shown in the screenshot below (in case of change search box location by user):
Yes
Preview

fix(v2): adjust padding when custom search box location

---

packages/docusaurus/src/commands/start.ts

At the moment, with each new incremental build, two messages are duplicated in console:
```
To use Docusaurus i18n, it is strongly advised to use NodeJS >= 14 (instead of 12)
Docusaurus website is running at: http://localhost:3000/
```
If output of the first message can be eliminated by using Node.js v14, then on the second one user can not affect. I propose displaying the URL where Docusaurus is running only if it is necessary, i.e. when the initial URL has changed.
Yes
Try to build site locally.

refactor(v2): output URL to console only if it has changed

---

website/docs/deployment.mdx
website/versioned_docs/version-2.0.0-alpha.73/deployment.mdx
website/versioned_docs/version-2.0.0-alpha.74/deployment.mdx
website/versioned_docs/version-2.0.0-alpha.75/deployment.mdx
website/versioned_docs/version-2.0.0-beta.0/deployment.mdx

Created a warning, asking users to replace email and name in the GitHub action with their email and name.
I ran into issues when setting up github actions.
Yes

docs(v2): update steps in the github-actions section

---

.github/ISSUE_TEMPLATE/bug.md

Come from https://github.com/facebook/docusaurus/issues/4853#issuecomment-848724840
Should help reduce unwanted bug reports. Or do we still need to mention about this in docs too?
Yes
N/A

misc: improve bug report issue template

---

website/docs/migration/migration-manual.md

Migration guide should explain better how to upgrade the Algolia index

docs(v2): v2 migration guide: mention Algolia config update

---

website/docs/guides/markdown-features/markdown-features-math-equations.mdx
website/docusaurus.config.js
website/package.json
website/sidebars.js
yarn.lock

Rendering LaTeX math equations is an important feature for many documentation sites. Although, it is possible to write math equations using Docusaurus, it is not documented in the Docs. 
Yes.
I have created a new file `website/docs/guides/markdown-features/markdown-features-math-equations.mdx`, and made changes to  the sidebar configuration (`website/sidebars.js`) to include it in the sidebar. I have tested the doc website locally, and it works properly.
- https://github.com/facebook/docusaurus/issues/4017

docs(v2): New doc page for math equations

---

packages/docusaurus/src/client/serverEntry.js
packages/docusaurus/src/commands/build.ts

A kind of continuation of #3609 created after #4836.
At the moment SSR errors are not very informative, we can give the user a tip on how to resolve most common error kind of "x is not defined". We will also print full stack trace to provide guidance in fixing other SSR errors. 
Yes
Add `console.log(document.title);` call to the `Home` component along path `src/page/index.js`
| ![image](https://user-images.githubusercontent.com/4408379/120219437-eb3a5c80-c243-11eb-894b-432169928fe5.png) | ![image](https://user-images.githubusercontent.com/4408379/120219311-b5957380-c243-11eb-914c-2057abda2b47.png) |
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your …

refactor(v2): make even better SSR error notify and add tip

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css
packages/docusaurus-theme-classic/src/theme/LastUpdated/index.tsx
packages/docusaurus-theme-classic/src/theme/LastUpdated/styles.module.css

Currently there is too much space between doc update details container, this is especially noticeable on mobiles. I suggest reducing the padding a bit, and left-aligning last updated date. 
Yes
| ![image](https://user-images.githubusercontent.com/4408379/120059847-bd46f380-c05c-11eb-8656-1ee5bbf56bfe.png) | ![image](https://user-images.githubusercontent.com/4408379/120059858-c9cb4c00-c05c-11eb-99f6-f14fe546f0e7.png) |

refactor(v2): make little better doc update block UI

---

packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/docs.ts
packages/docusaurus-plugin-content-docs/src/props.ts
packages/docusaurus-plugin-content-docs/src/types.ts

After merging #4495, all frontmatter fields became part of doc metadata, we have at least one redundant field -- sidebar_label. We can safely remove it from the current metadata, and get it from the `frontMatter` field instead.
Yes
Tests passed.

refactor(v2): remove sidebar_label filed from doc metadata file

---

packages/docusaurus-plugin-content-docs/src/cli.ts
packages/docusaurus-plugin-content-docs/src/sidebars.ts
packages/docusaurus-plugin-content-docs/src/versions.ts
website/docusaurus.config.js

Resolves #4844
Because we do not seem to have a strict requirement that the sidebar file path be absolute, currently users who use relative path in the `sidebarPath` field will get an error when creating new docs version.
Although after merging of #4775 `docs:versions` command will no longer fails, and just silently create empty sidebar file. However, this is not what the user expects - copy of current sidebar file in new docs folder.  So I think instead of forcing users to specify _only_ absolute path to the sidebar file, we can automatically resolve relative path to it when cutting new docs version.
Yes
Not sure if tests are needed here?
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR …

fix(v2): allow relative sidebar path resolution in docs:version command

---

packages/docusaurus-plugin-content-blog/src/index.ts

Resolves #4840
Yes
In the main.js file try searching for "blog-post-list-prop-default.json" (path must be with `~blog` alias)

refactor(v2): use aliased path for blog list sidebar file

---

website/docs/guides/markdown-features/markdown-features-assets.mdx

Currently, it links to https://docusaurus.io/docs/using-plugins#docusaurusplugin-ideal-image which have no `plugin-ideal-image` related contents available (presumably moved)
To correctly guide users to the contents the link should be at https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-ideal-image
Yes

Fix incorrect link to plugin-ideal-image

---

packages/docusaurus/package.json
packages/docusaurus/src/server/html-tags/__tests__/htmlTags.test.ts
packages/docusaurus/src/server/html-tags/htmlTags.ts

Resolves #4892
Yes
See To Reproduce section in #4892

fix(v2): escape HTML entities in user tags attributes

---

.github/workflows/lint.yml

TIL about `yarn install --immutable`, useful to fail the CI if an install requires updating yarn.lock

chore: fail CI if yarn.lock is modified on install

---

packages/docusaurus/bin/docusaurus.js

Related to #4844.
In fact, we have exception handler for internal commands, so I think it makes sense to do something similar for external commands.
Yes
Not yet possible

refactor(v2): add exception handling if external command is fails

---

packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css

Small fix to #4882: after putting content title under `div.markdown` element, subsequent headings will add unwanted margin, which is best reset as was before.
Yes
| ![image](https://user-images.githubusercontent.com/4408379/120683296-23d97080-c4a6-11eb-9310-a55170d6bbc4.png) | ![image](https://user-images.githubusercontent.com/4408379/120683350-32278c80-c4a6-11eb-8532-6c0ceada9e70.png) |

fix(v2): adjust margin after content title

---

website/docs/using-plugins.md

Fix "context" typo in Advanced Guides/plugins codeblock.

docs(v2): plugins: fix typo in code block

---

packages/docusaurus-plugin-ideal-image/package.json
yarn.lock

Resolves #4913
Fixes following warning during `@docusaurus/plugin-ideal-image` installing:
- npm WARN react-waypoint@9.0.3 requires a peer of react@^15.3.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
Yes
E2E test.

chore(v2): bump react-waypoint from 9.0.2 to 10.1.0

---

packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocVersionSuggestions/index.tsx
packages/docusaurus-theme-classic/src/theme/LastUpdated/index.tsx
packages/docusaurus-theme-classic/src/theme/Logo/index.tsx

Since we use boldface in UI components purely for decorative (visual) purposes, we are better off using the `b` tag rather than `strong` (which is intended to be used directly in text content for make higher emphasis).
Refs:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong#%3Cb%3E_vs._%3Cstrong%3E
- https://stackoverflow.com/questions/2243074/is-it-ok-to-use-strong-in-place-of-b-blindly
- https://stackoverflow.com/questions/271743/whats-the-difference-between-b-and-strong-i-and-em
Yes
No UI changes.

refactor(v2): replace strong with b in UI components

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css
packages/docusaurus-theme-classic/src/theme/IconExternalLink/index.tsx
packages/docusaurus-theme-classic/src/theme/IconExternalLink/styles.module.css

A more correct approach for placing external link icon, since this icon must be part (continuation) of link text (see screenshots below for better understanding).
Yes
| ![image](https://user-images.githubusercontent.com/4408379/120914428-ee4fa580-c6a6-11eb-88f9-ac836d6270da.png) | ![image](https://user-images.githubusercontent.com/4408379/120914456-f871a400-c6a6-11eb-91ab-01f7f90a0a1a.png) |
|  ![image](https://user-images.githubusercontent.com/4408379/120914477-22c36180-c6a7-11eb-87d2-d9db49042956.png) | ![image](https://user-images.githubusercontent.com/4408379/120914489-3078e700-c6a7-11eb-9f74-58adc9066918.png) |
(If this PR adds or changes functionality, please take some time to update the …

refactor(v2): use SVG for external link icon

---

packages/docusaurus-plugin-content-blog/src/__tests__/__snapshots__/generateBlogFeed.test.ts.snap
packages/docusaurus-plugin-content-blog/src/__tests__/generateBlogFeed.test.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-blog/src/index.ts

Currently, for sites that do not use a blog, RSS files are generated with an empty feed (e.g. https://www.graphql-code-generator.com/blog/rss.xml)
Most likely, we should avoid such behavior, it does not make sense at all.
Yes
Not sure if need to create another blog to test this?

refactor(v2): do not generate RSS files for empty feed

---

packages/docusaurus-theme-classic/src/theme/Toggle/index.tsx
website/src/components/showcase/ShowcaseCard/index.js
website/src/components/showcase/ShowcaseSelect/index.js
website/src/pages/showcase/index.js

Fix minor errors related with a11y which reported by Rocket Validator:
- The element “input” must not appear as a descendant of an element with the attribute “role=button” (Toggle)
- Possible misuse of “aria-label” (Showcase)
- Select element must have an accessible name (Showcase)
Yes
Preview.

fix(v2): fix minor a11y issues

---

packages/docusaurus/src/client/exports/BrowserOnly.tsx

Fixes #4934
Currently child elements inside `BrowserOnly` are rendered too early, before the client side is ready, because in some cases the final markup may break.
Yes
See To reproduce section in #4934 (eg. insert code below on index page).
```js
<BrowserOnly
fallback={
<div className="a">
<div className="b">Will be render during SSR</div>
</div>
}>
{() => (
<div className="a">
<div className="b">Will be render on client (i.e. replace SSR content above)</div>
</div>
)}
</BrowserOnly>
```

fix(v2): render children in BrowserOnly after client is ready

---

packages/docusaurus-theme-classic/src/index.ts
packages/docusaurus/src/client/templates/ssr.html.template.js
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/server/index.ts
website/docs/api/docusaurus.config.js.md
website/docs/guides/markdown-features/markdown-features-math-equations.mdx
website/docusaurus.config.js

These are completely unnecessary attributes that are actually already being removed by the minifier (terser), so we can remove them from the codebase itself.
> The default type for resources given by the stylesheet keyword is "text/css" (see w3.org/TR/html5/links.html#link-type-stylesheet)
> For scripts, default type is "text/javascript" (see http://www.w3.org/TR/html5/scripting-1.html#attr-script-type)
Yes
Preview

refactor(v2): remove type attribute from link and script tags

---

packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css
packages/docusaurus-theme-classic/src/theme/TOC/styles.module.css

At the moment, doc content is positioned bit lower compared to doc sidebar content, this inconsistency in these two columns is a bit disturbing to the eye. If you look at the blog layout, there is no such issue, so I suggest eliminating this visual discrepancy.
Yes
Before:
After:

refactor(v2): reduce vertical space in doc content container

---

website/docs/guides/markdown-features/markdown-features-tabs.mdx

The docs do not clearly mention the `defaultValue` prop available for Tabs, but I thought that we should for SEO reasons and to raise awareness about it.
Yes
Make sure the docs build.

docs: add info about `DefaultValue` prop in `Tabs`

---

packages/docusaurus-theme-classic/src/theme/MDXPage/index.tsx
packages/docusaurus-theme-classic/src/theme/MDXPage/styles.module.css

Quite strange looking now markdown page, I suppose it should be aligned to center like on all the other pages (see screenshots below).
Yes
| Before <br/> (https://docusaurus.io/examples/markdownPageExample)   | After <br/> (https://deploy-preview-4917--docusaurus-2.netlify.app/examples/markdownPageExample)    |
| ![image](https://user-images.githubusercontent.com/4408379/120924527-d72baa80-c6dc-11eb-8a38-f35b7cccddb7.png) | ![image](https://user-images.githubusercontent.com/4408379/120924924-c9772480-c6de-11eb-81d9-e9856b9e7df6.png) |

fix(v2): tidy up Markdown page layout

---

website/docusaurus.config.js

At the moment we see that the performance in new Lighthouse reports has decreased. This is because Netlify now automatically include their own widget (Netlify Drawer) into preview sites. They [promise to make it configurable](https://answers.netlify.com/t/netlify-github-app-permission-updates-with-collaborative-deploy-previews/37872/24), so for now I suggest disable the Google metrics from preview sites to slightly increase the current performance metrics.
Yes
Make sure that the preview is not using Google Analytics.

misc: disable google-gtag plugin in Netlify deploys

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/sidebars.ts

refactor(v2): include path in error about non-existent ids

---

website/docs/guides/markdown-features/markdown-features-react.mdx

The website has [a hidden Markdown page example](https://docusaurus.io/examples/markdownpageexample). It includes [an example of importing markdown](https://docusaurus.io/examples/markdownpageexample#import-mdx-and-md-files), which is not documented anywhere else on the website.
On Discord people often ask about reusing Markdown files, and I have to give them links to this hidden file. It would be great if it can be documented in the actual documentation.
I'm not sure if I'm putting this section in the right place...
Yep

docs(v2): add documentation about importing markdown

---

packages/docusaurus-init/templates/classic/docusaurus.config.js
packages/docusaurus-init/templates/classic/package.json
packages/docusaurus-init/templates/classic/src/css/custom.css

Fix #4812. This makes the initialized site more closely resemble the Docusaurus website, because currently the light theme for code blocks seems broken, causing quite some confusion.
Yep
The same configuration is used by the Docusaurus website, so it should be working.
The only thing I'm not sure of is that I had to `require` globally to silence ESLint errors, while for new users it might be more straightforward to `require` it within the object definition.

feat(v2): add code block theming in init template

---

packages/docusaurus-theme-classic/src/theme/IconExternalLink/index.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx
packages/docusaurus-theme-classic/src/types.d.ts
website/docusaurus.config.js

For more consistency, we should probably add icon for external links in the navbar too. This was previously done for sidebar links (see #4261).
Yes
Preview

feat(v2): add icon to external navbar links

---

website/docs/search.md

fixes https://github.com/facebook/docusaurus/issues/4975

docs(v2): mention to install the algolia package in search doc

---

packages/docusaurus-utils-validation/src/validationUtils.ts
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts

Related to https://github.com/facebook/docusaurus/issues/4925#issuecomment-856860604
We should make it clearer that user should not use a subpath in site URL config, and rather use the baseurl field:
```js
// docusarus.config.js
url: '<domain>/docs' // => BAD: emit a warning
}
```
In practice, it is an excuse to introduce a validation warning system for the site config, as we'll likely want to enforce stricter config over time, and emitting warning is a good way to progressively deprecate some bad config usage without annoying too much the users

polish(v2): url-subpath config validation warning

---

website/docs/guides/markdown-features/markdown-features-react.mdx

Resolve #4540. Yet another PR trying to migrate contents from the example MD page to the real documentation. I wonder what's the ["recipes section"](https://github.com/facebook/docusaurus/issues/4540#issuecomment-811391802) going to look like and whether I can help with that 🤔
I also did some minor editing to my previously written section. (#4958)
Yes

docs(v2): add documentation about importing code files

---

packages/docusaurus-init/templates/classic/docs/tutorial-basics/create-a-document.md
website/docs/api/plugins/plugin-ideal-image.md
website/docs/guides/docs/sidebar.md
website/docs/guides/markdown-features/markdown-features-math-equations.mdx

Resolve #4698. There are some `diff` code blocks with only `+` and no `-`. In this case using line highlight equally makes sense, with the additional merits of:
1. Not generating "confusing code" when using copy button;
2. Leverages syntax highlight to make the code block more visually appealing.
For the rest of the code blocks that have `-` as well, I kept them as-is.
Yep

docs(v2): replace `diff` codeblocks with line highlight

---

website/docs/api/plugins/plugin-content-blog.md
website/docs/api/plugins/plugin-content-docs.md
website/docs/api/themes/theme-configuration.md
website/docs/blog.md
website/docs/cli.md
website/docs/guides/docs/docs-create-doc.mdx
website/docs/guides/docs/docs-markdown-features.mdx
website/docs/guides/docs/sidebar.md
website/docs/guides/docs/versioning.md
website/docs/guides/markdown-features/markdown-features-assets.mdx
website/docs/guides/markdown-features/markdown-features-inline-toc.mdx
website/docs/guides/markdown-features/markdown-features-tabs.mdx
website/docs/lifecycle-apis.md
website/docs/presets.md

Simple improvements in the docs.
Yes
Preview

docs(v2): minor tweaks

---

packages/docusaurus-theme-classic/src/validateThemeConfig.js

Just to close #4363.
Perhaps someone uses this feature and specified string value to get around the validation error.
Yes
N/A

fix(v2): make proper data type for prependBaseUrlToHref field

---

packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx

When using a navbar doc item like:
```
{
type: 'doc',
docId: 'myDocId',
},
```
It was previously required that myDocId exist in ALL docs versions of the sites, so that we can always link to the currently active version.
This PR makes it more fail-safe, and falls-back to looking for the doc in lastVersion, so that older versions are not forced to contain a doc with `id: myDocId` (ie we can more easily introduce a navbar link to an existing versioned site)
Fix https://github.com/facebook/docusaurus/issues/4972
yes
local :'( we don't have much test infra on the theme code and no dogfooding possible

fix(v2): navbar doc item fallback: search doc in lastVersion

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx

Fix #4932
When the version dropdown contains a single version, it should transform to a regular button/link. It does not Desktop but didn't for mobile

fix(v2): fix UX for docsVersionDropdown on mobile for single version

---

website/community/3-contributing.md
website/community/4-canary.md
website/docs/installation.md

Document what are canary releases and how to use them.
Useful page to link to after merging a PR, improving the change to have feedback and catch potential bugs before the next releases

docs(v2): document canary releases

---

packages/docusaurus-plugin-content-blog/src/blogUtils.ts

Fix #4881. This issue contains two bugs, the first (wrong displayed date) is related to `formattedDate`, the second (wrong generated URL) is related to `toUrl`. By always dealing with the blog date object in the UTC timezone, both bugs should be fixed. (@josh-kaplan inspired me on how to fix the first one.)
Although in the documentation, it is suggested to use `YYYY-MM-DD` for the blog date, numbers without a preceding zero will not be rejected and will be correctly parsed. However, this causes the date to be treated as a local time object instead of a UTC one when creating the date object, [as documented](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date). By forcing the date object to be created in UTC, this problem is solved.
In `formattedDate`, …

fix(v2): always use UTC when dealing with blog dates

---

packages/docusaurus-plugin-client-redirects/package.json
packages/docusaurus-plugin-client-redirects/src/__tests__/__snapshots__/writeRedirectFiles.test.ts.snap
packages/docusaurus-plugin-client-redirects/src/__tests__/collectRedirects.test.ts
packages/docusaurus-plugin-client-redirects/src/__tests__/writeRedirectFiles.test.ts
packages/docusaurus-plugin-client-redirects/src/collectRedirects.ts
packages/docusaurus-plugin-client-redirects/src/index.ts
packages/docusaurus-plugin-client-redirects/src/writeRedirectFiles.ts
packages/docusaurus-utils-common/src/__tests__/applyTrailingSlash.test.ts
packages/docusaurus-utils-common/src/applyTrailingSlash.tsx
packages/docusaurus-utils/src/__tests__/getFilePathForRoutePath.test.ts
packages/docusaurus-utils/src/__tests__/index.test.ts
packages/docusaurus-utils/src/getFilePathForRoutePath.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus/src/server/plugins/applyRouteTrailingSlash.ts
website/docusaurus.config.js

The redirect plugin does not use the new `siteConfig.trailingSlash` config.
It should, and output different patterns of redirect files according to `trailingSlash`
Also, it should be more resilient: 
- user has `redirect.to=/abc` and user wants to use `trailingSlash=true`
- then `/abc` is not a valid path to redirect to anymore => it is now `/abc/`
- we should not need to ask the user to change its redirect config paths, we can consider that he now wants to redirect to `/abc/` automatically
- it becomes easier to test the `trailingSlash: true` without having to also update the redirect options
Also, it allows for easier `trailingSlash` dogfooding: we can now more easily change `trailingSlash` for our site prod/deployPreview without having to change redirect options (ie add/remove to …

fix(v2): redirect plugin should use siteConfig.trailingSlash

---

packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-docs/src/docs.ts
packages/docusaurus-plugin-content-docs/src/index.ts

When looping over docs/versions/blog, if one item triggers an error, the user should be able to figure out which one with a relevant log.
Unfortunately, JS does not have a good way to add context to an existing error (until this proposal is implemented: https://github.com/tc39/proposal-error-cause) so I just add a log for now.
Helpful to debug some problems reported by users for which the logs are not meaningful enough
yes
tests,  no behavior changed

refactor(v2): blog/docs: add more context in error messages

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx
packages/docusaurus-utils-common/src/__tests__/uniq.test.ts
packages/docusaurus-utils-common/src/index.ts
packages/docusaurus-utils-common/src/uniq.ts

Due to some weird reason, the array dedupication logic using `[...new Set()]` is badly processed and buggy in the production build. Switching to `Array.from(new Set())` fixes the problem.
https://github.com/facebook/docusaurus/issues/4972#issuecomment-863895061
yes
tests

fix(v2): fix theme array deduplication bug

---

packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css

Re-attempted to apply the changes from #4877.
Because of style minification the changes from that PR didn't apply (didn't notice it right away). So I decided to use the built-in Infima utility classes to achieve purpose of that PR.
Yes
Preview.

refactor(v2): reduce top padding in doc content container

---

website/docs/guides/docs/docs-create-doc.mdx
website/docs/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-2.0.0-beta.1/guides/docs/docs-create-doc.mdx
website/versioned_docs/version-2.0.0-beta.1/guides/markdown-features/markdown-features-react.mdx

Crowdin-related issues due to unescaped MDX usage, preventing the site to deploy: https://app.netlify.com/sites/docusaurus-2/deploys/60ccbb53d7e132000849fc0b
We should use ` ```mdx-code-block ` around JSX in md

docs(v2): wrap mdx usage in mdx-code-block

---

website/docs/api/plugins/plugin-content-docs.md
website/docs/api/plugins/plugin-content-pages.md
website/docs/api/themes/theme-configuration.md
website/docs/deployment.mdx
website/docs/docusaurus-core.md
website/docs/i18n/i18n-git.md
website/docs/i18n/i18n-introduction.md
website/versioned_docs/version-2.0.0-beta.0/api/plugins/plugin-content-docs.md
website/versioned_docs/version-2.0.0-beta.0/api/plugins/plugin-content-pages.md
website/versioned_docs/version-2.0.0-beta.0/api/themes/theme-configuration.md
website/versioned_docs/version-2.0.0-beta.0/deployment.mdx
website/versioned_docs/version-2.0.0-beta.0/docusaurus-core.md
website/versioned_docs/version-2.0.0-beta.0/i18n/i18n-git.md
website/versioned_docs/version-2.0.0-beta.0/i18n/i18n-introduction.md
website/versioned_docs/version-2.0.0-beta.1/api/plugins/plugin-content-docs.md
website/versioned_docs/version-2.0.0-beta.1/api/plugins/plugin-content-pages.md
website/versioned_docs/version-2.0.0-beta.1/api/themes/theme-configuration.md
website/versioned_docs/version-2.0.0-beta.1/deployment.mdx
website/versioned_docs/version-2.0.0-beta.1/docusaurus-core.md
website/versioned_docs/version-2.0.0-beta.1/i18n/i18n-git.md
website/versioned_docs/version-2.0.0-beta.1/i18n/i18n-introduction.md

This PR fixes one of the root causes of https://github.com/facebook/docusaurus/issues/5020 (See Demo 2)
Some anchor links are specified with the incorrect target, so this PR fixes these incorrect links
Yes
Manual testing using local dev server. We won't be able to use the netlify preview to test this because all cross-page anchor links are failing due to another root cause (see https://github.com/facebook/docusaurus/issues/5020). 
1. Temporarily change `useChangeRoute.ts` hook in `packages/docusaurus-theme-common/src/utils/useChangeRoute.ts` as follows:
2. Start the development server and go to localhost:3000/docs/deployment#self-hosting
3. Click on the `docusaurus serve` link
4. Should be redirected to the correct target header

docs(v2): fix incorrect anchor links in website

---

README.md

Following #4902, this PR removes the broken badge for V1 tests, which has already been removed.

chore(v2): remove badge for v1 tests

---

website/docs/deployment.mdx

Corrected a minor grammatical error.
I found this error while I was reading docs while developing a project.

docs(v2): typo in deployment.mdx

---

packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-blog/src/__tests__/blogFrontMatter.test.ts
packages/docusaurus-plugin-content-blog/src/blogFrontMatter.ts
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-docs/src/__tests__/docFrontMatter.test.ts
packages/docusaurus-plugin-content-docs/src/docFrontMatter.ts
packages/docusaurus-utils-validation/src/validationSchemas.ts

After the beta.1 release, it has been reported that the new frontmatter validation is a bit too strict, in particular for URIs in blog post image/author URL. This makes the validation less strict, and allows paths like `/x/y.png` as before
https://github.com/facebook/docusaurus/issues/5011
https://github.com/facebook/docusaurus/issues/5012
Note: Joi is really painful to work with, in particular for the uri() type which cannot accept an absolute path, and does not make it easy at all to have clean error messages when building custom validation logic.
yes
tests

fix(v2): less strict blog/docs uri frontmatter validation

---

packages/docusaurus/src/commands/deploy.ts
website/docs/deployment.mdx

Using the legacy `trailingSlash: undefined` behavior is not recommended with GH pages due to the reconfigurable behavior of GH pages to add a trailing slash with a server redirect. This is better to use set explicit value (either true or false) instead of using the legacy retrocompatible behavior.
Also adding a warning to the deploy script.
Note: later we may remove this because we could use `trailingSlash: false` as a default (after explicitly deprecating "undefined" legacy behavior). (but it might be a problem for deploying on Vercel without the cleanUrl option: see https://github.com/slorber/trailing-slash-guide/issues/1)

docs(v2): GH pages: recommend using trailingSlash

---

packages/docusaurus/src/webpack/base.ts

Add the css module filename to avoid potential dev classname collisions.
Fix https://github.com/facebook/docusaurus/issues/5018
If it's not enough we can also add the hash in dev
See doc: https://webpack.js.org/loaders/css-loader/#localidentname

fix(v2): dev css modules classnames should include filename

---

packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/server/html-tags/index.ts
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/plugins/index.ts
packages/docusaurus/src/webpack/__tests__/utils.test.ts
packages/docusaurus/src/webpack/utils.ts
website/docs/lifecycle-apis.md

Plugin lifecycles that are triggered after we loaded the plugin content should permit to access that plugin content.
The following should work:
```js
module.exports = function (context, options) {
return {
name: 'docusaurus-plugin',
loadContent: async () => {
return {remoteHeadTags: await fetchHeadTagsFromAPI()};
},
injectHtmlTags({content}) {
return {
headTags: content.remoteHeadTags,       
};
},
};
};
```
Also injecting the content in the `configureWebpack` lifecycle, as we compute the mdx/remark config by using the loaded content for resolving relative file path links to URLs. This permits to avoid an unelegant side-effect we previously had in `loadContent`:
```js
// TODO annoying side effect!
Object.values(docs).forEach((loadedDoc) => {
const {source, permalink} = loadedDoc; …
```

feat(v2): plugins injectHtmlTags + configureWebpack should receive content loaded

---

packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css

Fix some docs layout issues.
@covalentbond reported here that the TOC should take more space for medium size devices (ex: 1300px): https://github.com/facebook/docusaurus/pull/4995#issuecomment-864242680
Also fixing the collapsed sidebar icon appearing on mobile:
Also fixing the vertical scrollbar appearing for medium width when toc is large:
@lex111 any concern with those changes?

fix(v2): fix some docs container/sidebar layout issues

---

website/docs/introduction.md

Wrong name - **Docz** not **Dokz**.

docs(v2): Fix Gatsby theme name for docs site - Docz

---

packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx
packages/docusaurus-theme-classic/src/theme/SkipToContent/styles.module.css

Apparently, it is better to apply shadow to the skip link only on focusing to avoid its visibility in light mode.
Yes
Preview

fix(v2): add shadow to skip link on focus only

---

packages/docusaurus-plugin-content-docs/src/__tests__/lastUpdate.test.ts
packages/docusaurus-plugin-content-docs/src/lastUpdate.ts

My use case:
```
website/ # a repo
|   external/
|   |  repo-a/ # another repo, ignored by git at website/
|   |  repo-b/ # another repo, also ignored by git
```
With the current implementation, the `lastUpdate` won't return any data, as the files are unknown by Git when using `website` as the `cwd`. But if we call git in their own folders, git will be able to properly read the metadata.
Yes
I verified by replacing the content of `lastUpdate.js` in my `node_modules` folder, which worked. But if needed, I can find a way to record a video. I just didn't record yet because in my tests there are private data from my company.
The good news is that this change won't break any existing use case, it will just fix mine.
None

fix(v2): read last update from inner git repositories

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/versions.test.ts
packages/docusaurus-plugin-content-docs/src/client/__tests__/docsClientUtils.test.ts
packages/docusaurus-plugin-content-docs/src/client/docsClientUtils.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-docs/src/props.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-plugin-content-docs/src/versions.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocVersionBanner/index.tsx
website/docs/api/plugins/plugin-content-docs.md

**Breaking changes**: 
- `@theme/DocVersionSuggestions` component API modified, and component is renamed to `DocVersionBanner`. 
Fixes https://github.com/facebook/docusaurus/issues/3013
By default, we display a banner at the top of docs versions that are not the latest version, saying the version is either unreleased or unmaintained.
This is a problem for some sites that want to disable this banner. 
Currently, the only solution is swizzle the banner component, which is a bit annoying for users.
This PR adds a new version config option so that the banner can be customized/disabled per-version.
```js
const docsOptions = {
versions: {
current: {
banner: "none"
}
"1.0.0": {
banner: "none"
}
}
};
```
This may not be the best API in case you want to disable the site on ALL banners at once, but …

feat(v2): docs version banner configuration option

---

packages/docusaurus-plugin-content-docs/src/__tests__/options.test.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-docs/src/types.ts

**Breaking changes**:
- The `excludeNextVersionDocs` deprecated docs option will now be rejected with a validation error
The docs plugin option `excludeNextVersionDocs: true` has been deprecated with a warning for more than 6 months now, and replaced by `includeCurrentVersion: false`.
Let's do the cleanup and remove this useless code.

refactor(v2): remove deprecated docs option excludeNextVersionDocs

---

packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/server/__tests__/__snapshots__/config.test.ts.snap
packages/docusaurus/src/server/__tests__/__snapshots__/configValidation.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts
website/docs/api/docusaurus.config.js.md

Fix https://github.com/facebook/docusaurus/issues/4923
We should allow undefined as favicon so that users can add favicon themself
Also updated the favicon config doc: using a fully-qualified URL is not really recommended and would actually lead to a bad URL in the blog feed (as we add the site URL to it)
yes
tests

fix(v2): allow undefined favicon

---

packages/docusaurus/src/webpack/server.ts

Quite complicated to explain, fixes https://github.com/facebook/docusaurus/issues/4922 (including all the relevant details)
Not sure it's the perfect fix, but it looks to me we can pass any `__filename` value to unlock the situation, and it has no particular effect in practice apart preventing the eval error
yes
local test + feedback from Relay Compiler playground integration, using Rust/WASM compiler

fix(v2): fix webpack SSG plugin error thrown due to new URL() / __filename

---

packages/docusaurus-types/package.json
packages/docusaurus-types/src/index.d.ts
packages/docusaurus-types/tsconfig.json
yarn.lock

When building a Typescript project depending on `@docusaurus/types`, this error is raised:
Yes.
I have added a `tsconfig.json` file to `@docusaurus/types` and typescript as a dev dep. One can check those types now with
```bash
yarn workspace @docusaurus/types test
```
The test **now** passes:

fix(v2): fix bad @docusaurus/types Plugin type generics

---

packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css

After merging of #5035, the button to display responsive menu is no longer displayed. I just now noticed that :(
Yes
Preview

fix(v2): restore responsive menu

---

.github/workflows/lint.yml
packages/docusaurus-types/package.json
yarn.lock

CI does not catch unstable lockfile errors
Yarn v1 --frozen-lockfile is not strictly equivalent to Yarn v2 --immutable (it does not throw)
So move back to `git diff --exit-code` to detect a modified lockfile in CI

chore: unstable yarn.lock

---

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx

This PR adds few more heading to split the content to small topics.
This way users like me will be able to scroll directly to the specific section, instead of reading all the documentation.
I add to read the entire section because It was not divided into sections. Not a great user experience.

docs(v2:) Divide `markdown-features/code-blocks` to smaller sections

---

packages/docusaurus-plugin-content-docs/src/__tests__/docFrontMatter.test.ts
packages/docusaurus-plugin-content-docs/src/docFrontMatter.ts

In some cases, negative sidebar positions can be useful for reversing the sorting order with minimal maintenance overhead. For example, a docs folder with changelogs for historical versions should be sorted in reverse chronological order. This is easy to do for semantic version numbers by converting them into a negative numerical representation, e.g. 11.5.1 -> -110501.
The alternative is to make the first version start with a large position number (e.g. 9999) and decrement it for each version. However, this requires referring to older versions to get the current sequence number, thus increasing maintenance overhead. It also makes the number less intuitive and more prone to error.
Negative sidebar positions work great for this purpose, so make the front matter validator allow them again as …

fix(v2): allow negative sidebar positions

---

website/docs/installation.md

I was upgrading the docusaurus and saw that new release has been done, and i checked the installation is not updated
Yes

docs(v2): update installation docs

---

packages/docusaurus-plugin-sitemap/src/__tests__/createSitemap.test.ts
packages/docusaurus-plugin-sitemap/src/createSitemap.ts

Sitemap has a depricated option, `trailingSlash`. When used, URLs in the sitemap have trailing slashes, but you see a warning: 
> Option "trailingSlash" of the sitemap plugin is deprecated: Please use the new Docusaurus global trailingSlash config instead, and the sitemaps plugin will use it.
If you remove the `trailingSlash` option from the sitemap plugin, and instead have a global `trailingSlash` option set to `true`, the generated sitemap lacks trailing slashes.
This PR causes the sitemap plugin to respect the global `trailingSlash` option.
yes
Within `website` I explicitly set the global `trailingSlash` option to true, and then false, to verify that trailing slashes are generated (or not) respectively.

fix(v2): sitemap should respect the global trailingSlash config option.

---

packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx

Quick attempt to fix #5076
Currently, after changing the location, we focus on the skip link to focus on that link at first. However, this has the side effect that when the user clicks on the browser's back button, then the previous scroll position is lost. To avoid this we can focus on the skip link only when moving forward in browser history.
Yes
Scroll a bit on any doc page, then go to another page, then press on back button in the browser, as result is the previous scroll position should be preserved.

fix(v2): restore previous scroll position on back button click

---

packages/docusaurus-plugin-client-redirects/src/__tests__/extensionRedirects.test.ts
packages/docusaurus-plugin-client-redirects/src/extensionRedirects.ts
packages/docusaurus-plugin-client-redirects/src/index.ts

Follow-up of https://github.com/facebook/docusaurus/issues/5055#issuecomment-870951538
When using `trailingSlash: true`, the redirect plugin does not emit files for `fromExtensions: ['html']` because it ignorers all paths ending with `/`
If there's a path such as `/xyz/`, we should emit `/xyz.html/index.html`, otherwise deployments like Netlify wouldn't redirect when browsing `/xyz.html`, they would just serve the HTML file and it would lead to a 404 error due to the route not existing on the frontend router.
Also cleanup now useless warning since we reverted to emit `/xyz.html/index.html`, as the warning does not make sense anymore
yes
test + preview
This URL now works fine, while it used to display a frontend 404 error: https://deploy-preview-5093--docusaurus-2.netlify.app/docs/typescrip …

fix(v2): redirect from should work with trailingSlash: true

---

packages/docusaurus/src/commands/swizzle.ts

Bad regex prevent usage of `npm run swizzle @docusaurus/theme-classic ` when running outside our Docusaurus monorepo (when using `node_modules`)
Quick fix https://github.com/facebook/docusaurus/issues/5083
yes
none: the swizzle code is not testable and hard to maintain, all this should be rewritten someday

fix(v2): fix swizzle readComponent

---

packages/docusaurus-plugin-content-docs/src/theme/hooks/useDocs.ts

Infinite loop produced because we use an "unstable" empty object fallback when there is no docs global data available => triggers downstream useEffect re-executions because the unstable object is used in dependency array
Issue can be reproduced in blogOnly mode `yarn workspace docusaurus-2-website start:blogOnly`
Fix https://github.com/facebook/docusaurus/issues/5089
yes
none :( unfortunately this only happens on the client and the blogOnly CI action we have fails to catch this at build time

fix(v2): fix useEffect infinite loop in blogOnly mode

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx

Across the Classic Theme, there are two places where a link points to an anchor that does not exist on the page. This is for example problem for tools that try to verify the validity of links and if applicable their anchors. These tools are crucial in maintaining coherent documentations.
This PR fixes these links to be semantic correct and uses simple `#` instead.
Alternative to this change is to introduce `#main` anchor for the "Skip to main content" on the `main-wrapper` element. But not sure what would then be introduced for the Doc Sidebar.
Yes
None

fix(v2): classic theme - semantic correct anchors links

---

website/docs/guides/markdown-features/markdown-features-assets.mdx

Before it looked like we have two ways to display images, now it's three ways. Each syntax has a separate example.
This way it's clear, I see each method and the code example.
Before there were 2 methods in a single code block.

docs(v2): Rewrite markdown images section

---

packages/docusaurus-plugin-client-redirects/src/__tests__/writeRedirectFiles.test.ts
packages/docusaurus-plugin-client-redirects/src/writeRedirectFiles.ts

Our prod can't deploy: https://app.netlify.com/sites/docusaurus-2/deploys/60dc4c6287cf5600078e2098
> 12:55:12 PM: Error: Redirect file creation error for "/opt/build/repo/website/build/__docusaurus/debug.html/index.html" path: Error: EEXIST: file already exists, mkdir '/opt/build/repo/website/build/__docusaurus/debug.html'.
12:55:12 PM:     at writeRedirectFile (/opt/build/repo/packages/docusaurus-plugin-client-
We are trying to redirect path `/debug.html` to `/debug`
`/debug.html` is the content file for path `/debug`
The redirect file can't be:
- `/debug.html` because it would override the original content file (we should never do that)
- `/debug.html/index.html` because on Unix, it's not possible to create a folder with the same name as another file (the error we have here)
The only …

fix(v2): fix redirect plugin when trailingSlash=false for .html extension

---

packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx

SkipToContent programmatic focus should only happen when we navigate with a push action, and ignored for back/next (pop) or querystring updates (replace)
Fix https://github.com/facebook/docusaurus/issues/5100
yes
preview

fix(v2): fix SkipToContent programmatic focus when updating querystring

---

packages/docusaurus/bin/beforeCli.js
packages/docusaurus/bin/docusaurus.js

- Move notifier logic to separate file
- Fix code to make it check new version on first run
- Make it display notification consistently (not at most once per interval): https://github.com/yeoman/update-notifier/issues/209
- Reduce interval to 1h: it is a background check and does not slow-down the cli anyway so let's do it more
- Useful comments for later usage
Motived by this comment: https://github.com/facebook/docusaurus/issues/5105#issuecomment-871890235
yes
local tests

fix(v2): Fix update-notifier not run at first and not notifying consistently

---

.github/workflows/v2-build-size-report.yml

`globalData.json` is a file that should rather stay small over time as it's loaded for all pages of the site and can increase js processing time and delay hydration

misc: monitor site global data with build size bot

---

website/docs/api/plugins/plugin-content-docs.md

I tried to disable all "Edit this page" links using several ways and almost started to swizzle components when I found another PR that explained how to disable the edit links by omitting the `editURL` variable entirely. This small change will hopefully make it easier for future users.
Yes
This change does not require a test plan.
None.

docs(v2): clarify how to disable edit links entirely

---

packages/docusaurus-types/src/index.d.ts

This was likely a typo, and resulted in the following error when using Typescript strict mode:
> node_modules/@docusaurus/types/src/index.d.ts(250,14): error TS7031: Binding element 'Content' implicitly has an 'any' type.
I'd like my Typescript Docusaurus plugin to type-check without errors.
yes
The error is gone in my project :) Also, the code is now aligned with similar definitions, like the one for `getTranslationFiles` (a few lines down).
none

fix(v2): Invalid type definition for injectHtmlTags

---

packages/docusaurus/src/webpack/base.ts
website/docusaurus.config.js
website/dogfooding/docs-tests-symlink
website/dogfooding/docs-tests/index.md

remove `webpackConfig.resolve.symlinks: true`
This might not be intuitive, but to make Docusaurus work with symlinked folders, we have to use default/false instead.
Should fix https://github.com/facebook/docusaurus/issues/3272
yes
tests + preview

fix(v2): remove webpackConfig.resolve.symlinks: true

---

packages/docusaurus-theme-search-algolia/package.json
yarn.lock

Bump DocSearch version to the latest, which fixes https://github.com/facebook/docusaurus/issues/5031
**Summary**
Without query, recent searches and favorite searches, pressing <kbd>↑</kbd> crashes the website.
Yes
- Tests are at the underlying library level: https://github.com/algolia/autocomplete/pull/623
- Preview with `yarn start:v2`
https://user-images.githubusercontent.com/20689156/125099747-a4f4da80-e0d8-11eb-83c2-465e9f8f0cf9.mov

chore(v2): update @docsearch/react

---

package.json
yarn.lock

CI is failing to deploy due to a server error. Their support suggested to upgrade.
```
5:55:25 PM: ❌ Fetching project info
5:55:25 PM: ❌ Failed to collect project info. Please contact our support team for help
5:55:25 PM: ❌ Error from server: <Code: <empty_code>, Message: Unrecognized field "customSegmentation" (class com.crowdin.client.sourcefiles.model.OtherFileImportOptions), not marked as ignorable (one known property: "contentSegmentation"])
5:55:25 PM:  at [Source: (String)"{"contentSegmentation":true,"customSegmentation":false}"; line: 1, column: 55] (through reference chain: com.crowdin.client.sourcefiles.model.FileInfoResponseList["data"]->java.util.ArrayList[0]->com.crowdin.client.sourcefiles.model.FileResponseObject["data"]->com.crowdin.client.sourcefiles.model.File["importOptio …
```

chore: upgrade crowdin

---

website/docs/api/plugins/plugin-ideal-image.md

https://github.com/facebook/docusaurus/issues/2956
Please check the issue above.
GIF format is currently is not supported
Ideal image plugin does not support gif  
yes

docs(v2): GIF format is not suported

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx

We can now use the built-in `Collapsible` component for nav items on mobiles.
Yes
Preview.

refactor(v2): use Collapsible for mobile nav items

---

packages/docusaurus-theme-common/src/utils/useCollapsible.tsx

Currently, the `useCollapsible` hook does not respond well to multiple clicks, especially when the current transition has not yet completed.
This is especially noticeable on mobile devices: for example, transition for collapsed action is not smooth anymore, so that the content is hidden instantly.
| ![ezgif com-gif-maker (12)](https://user-images.githubusercontent.com/4408379/125249392-ddc1c900-e2fd-11eb-93f9-6b93f65d3a8d.gif) | ![ezgif com-gif-maker (11)](https://user-images.githubusercontent.com/4408379/125249415-e3b7aa00-e2fd-11eb-94fa-7b3261260b2f.gif) |
Moreover, you have to wait for the transition to finish before starting new one, otherwise there will also be "sharp" transition.
| …

fix(v2): improve work of useCollapsible hook with multiple clicks

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.tsx
packages/docusaurus-theme-classic/src/theme/Navbar/styles.module.css

Attempt to fix bug where the secondary menu is not consistently opened when it should
Reported here: https://github.com/facebook/docusaurus/pull/4273#issuecomment-877360318
Also refactor a bit the navbar desktop/mobile code, extract clean hooks and remove unused css !importants.
yes
preview
https://github.com/facebook/docusaurus/pull/4273

fix(v2): Fix navbar mobile sidebar secondary menu bugs + refactor navbar

---

packages/docusaurus-theme-classic/src/theme/DocSidebarItem/index.tsx

We need to disable the default behavior of the browser when click on a collapsible item in doc sidebar, otherwise we will end up at the top of current page after click with `#` in address bar.
Yes
Preview

fix(v2): disable default behavior when click on collapsible item

---

packages/docusaurus-theme-common/src/utils/useCollapsible.tsx

On the server rendering, the collapsible component is not collapsed properly when `props.collapsed=true`
This affects collapsible mobile TOC, not the navbar / sidebar items because they have extra CSS from Infima.
Can be seen with JS disabled:
This is because collapsed style is applied through JS only after hydration, so the collapsing happens with a little delay.
This PR make sure we apply collapsed style on the server to avoid that layout shift
yes
preview
https://github.com/facebook/docusaurus/pull/4273

fix(v2): Fix Collapsible hydration layout shift

---

packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/webpack/base.ts
website/docusaurus.config.js

Revert change made in https://github.com/facebook/docusaurus/pull/5126 => back to `webpack.resolve.symlinks = true`
We can't do this change because there's a bug in Webpack 5 cache when `resolve.symlinks = false`. 
Disabling the cache is really painful for the development experience.
More infos reported here: 
- https://github.com/facebook/docusaurus/issues/3272#issuecomment-879295056
- https://github.com/webpack/webpack/issues/11612#issuecomment-879259806
Also adding correct dev `watchOptions` so that it would work if we decide later to change to `resolve.symlinks = false` again, or if the user does this with custom Webpack config.
yes
preview
https://github.com/facebook/docusaurus/pull/5126

fix(v2): revert webpack.resolve.symlinks = false

---

package.json

Fix monorepo `yarn clear` command.
We run it before publishing and it did not clean-up the `lib-next` dist folders, so older/renamed comps remain available for swizzle in recent releases. This makes sure it does not happen again.

fix(v2): fix yarn clear command

---

website/docusaurus.config.js

Our site has a few console fetch errors due to using bad relative PWA URLs
Let's fix this and make them baseUrl insensitive too
yes
preview

fix(v2): fix website PWA icon hrefs

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DropdownNavbarItem.tsx
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/useLocalPathname.ts

Little UX detail reported here: https://github.com/facebook/docusaurus/pull/4273#issuecomment-877360318
The mobile sidebar dropdowns should auto-expand when they contain an active item (+ handle activeBaseRegex too)
yes
We don't really have the use-case on Docusaurus site so used another site/PR for tests: 
https://github.com/temporalio/documentation/pull/515

refactor(v2): mobile dropdown navbar: expand when subitem become active

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx

When a page has no heading (empty toc), we should not display the mobile collapsible toc button because it does not reveal any TOC.
Problem can be seen on:
- https://docusaurus.io/docs/create-doc
- https://docs.temporal.io/docs/glossary
yes
preview
https://github.com/facebook/docusaurus/pull/4273

fix(v2): hide mobile collapsible doc toc if no headings

---

README.md
website/docs/introduction.md
website/versioned_docs/version-2.0.0-beta.0/introduction.md
website/versioned_docs/version-2.0.0-beta.1/introduction.md
website/versioned_docs/version-2.0.0-beta.2/introduction.md
website/versioned_docs/version-2.0.0-beta.3/introduction.md

Tutorial in codesandbox is often 502
https://docusaurus.sse.codesandbox.io/ 
Moved to standalone deployment
=> https://tutorial.docusaurus.io

docs(v2): Update tutorial link

---

packages/docusaurus-plugin-pwa/package.json
packages/docusaurus-plugin-pwa/src/index.js
website/docusaurus.config.js

For more consistency, by analogy to other fields that take resource path, such as `favicon` or `themeConfig.image`, base URL should not be manually added by user to the head tags fields for PWA plugin.
Given other similar paths fields, it's reasonable for user to expect base URL to be automatically added to head tags related with PWA as well.
However, it will probably have to be marked as BC to notify users to remove `baseUrl` from their `headTags` of PWA config.
Yes
Preview

refactor(v2): automatically add base URL to PWA head tags

---

packages/docusaurus-theme-classic/src/types.d.ts

In #5072 I accidentally deleted the type import for `ReactNode`, causing the type of `NavLinkProps.label` to become `any`. This slipped past the review as well.
Yes

fix: fix type for navlink label

---

packages/docusaurus-plugin-pwa/src/index.js
website/docusaurus.config.js

Follow-up of #5169
According to RocketValidator, we have invalid meta tag `msapplication-TileImage` in which `href` attribute should be replaced by `content`. For that case, we should also adding base URL to `content` attribute in addition to current `href` attribute.
> Attribute “href” not allowed on element “meta” at this point.
Yes
Preview

fix(v2): add base URL to content attribute of head tags PWA

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DropdownNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts

After merging #5072 there is small regression where dropdown loses wrapper element `<li>`, which is bad for a11y.
> Element “a” not allowed as child of element “ul” in this context. (Suppressing further errors from this subtree.)
Yes
Preview

fix(v2): wrap dropdown item to missing li element + remove extra attributes

---

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx

if you add php language and don't restart your server, you will get an error like this
uncaught Error: Cannot find module './prism-php'
until you restart your server

docs: user should restart docusaurus after adding prism additionalLanguage

---

packages/docusaurus/bin/beforeCli.js

In Flipper, https://github.com/facebook/flipper/blob/master/website/package.json,  all our dependencies live in `devDependecies` of our `package.json`. As a result `dependencies` is not set, causing a crash when running `yarn start`:
```
/Users/mweststrate/fbsource/xplat/sonar/website/node_modules/@docusaurus/core/bin/docusaurus.js:50
const siteDocusaurusPackagesForUpdate = Object.keys(sitePkg.dependencies)
^
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at Object.<anonymous> (/Users/mweststrate/fbsource/xplat/sonar/website/node_modules/@docusaurus/core/bin/docusaurus.js:50:50)
at Module._compile (internal/modules/cjs/loader.js:955:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
at Module.load …
```

fix: cli upgrade helper fail when no `package.dependencies`

---

generateExamples.js

For Netlify deploy button, subfolders such as `examples/classic` won't work and we must have a real starter repository.
See https://github.com/jamstack/jamstack.org/pull/609
This little automation will permit to keep some starter repo/branch up-to-date:
- https://github.com/facebook/docusaurus/tree/starter
- https://github.com/slorber/docusaurus-starter
In the future having an i18n starter could also be helpful for users to inspect it easily.

misc: add script to keep starters branch/repos up-to-date

---

website/docs/guides/markdown-features/markdown-features-react.mdx

- Make it clear that one needs to install `raw-loader` before using it
- Removed the `;` after `CodeBlock` component, otherwise it will render the unintended semicolon after code block
- Added that one call pass the `title` prop to `CodeBlock` component as well.
Yes

docs(v2): Elaboration of raw-loader in markdown react component

---

website/docs/docusaurus-core.md

Fix https://github.com/facebook/docusaurus/issues/5209
Mention Link can be used for external links

docs: mention Link can be used for external links

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-live-codeblock/src/theme/Playground/styles.module.css

For consistency we should make the shadows consistent with each others.
Before:
After:
preview

refactor: make code block shadows consistent with new admonitions

---

website/src/pages/feedback/styles.module.css
website/src/pages/styles.module.css

It turns out that using `color-scheme` can lead to incorrect backgrounds in iframes on dark scheme. At least on our site:
Not sure if we should globally assign `color-scheme` to `auto` to avoid this issues on our client sites?
Yes

chore: fix iframe background color in dark mode

---

packages/docusaurus-theme-classic/src/theme/Details/index.tsx
packages/docusaurus-theme-classic/src/theme/Details/styles.module.css
packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-common/copyUntypedFiles.js
packages/docusaurus-theme-common/package.json
packages/docusaurus-theme-common/src/components/Collapsible/index.tsx
packages/docusaurus-theme-common/src/components/Details/index.tsx
packages/docusaurus-theme-common/src/components/Details/styles.module.css
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/useCollapsible.tsx
website/docs/guides/markdown-features/_markdown-partial-example.mdx
website/docs/guides/markdown-features/markdown-features-intro.mdx
website/docs/guides/markdown-features/markdown-features-react.mdx

Fix https://github.com/facebook/docusaurus/issues/2924
Instead of using the default rendering for details/summary, we should leverage summary to plug our own themed and animated details component.
Before: 
from https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components (using some additional custom CSS)
After:
If JS is disabled, this component should still work, falling back to default HTML behavior.
yes
https://deploy-preview-5216--docusaurus-2.netlify.app/docs/next/markdown-features

feat: details/summary theme / MDX component

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx

After we merged the new mobile UX, anchor links in headings broke. The reason for this is that during prerendering we render mobile TOC to avoid layout shift, but after hydration mobile TOC is removed from DOM on desktop. However, this is wrong because we hide mobile TOC on desktop with CSS. Therefore, we need to always render mobile TOC, then anchor links will work again and we still won't have FOUC.
Yes
Preview.
Test mobile TOC, then open any anchor link in new tab.

fix(v2): keep mobile TOC after hydration

---

packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css
packages/docusaurus-theme-classic/src/theme/TOCCollapsible/index.tsx
packages/docusaurus-theme-classic/src/theme/TOCCollapsible/styles.module.css

For example, if site does not use versioning, mobile TOC will be the first element in doc article section, and adding large and unnecessary margin at the top. I suggest removing top margin from first element inside article element as should be by design.
Yes
| ![image](https://user-images.githubusercontent.com/4408379/127242044-634430e9-334a-48e7-b627-bf4fb90e3fb3.png) |  ![image](https://user-images.githubusercontent.com/4408379/127242081-16af097e-7531-4b3f-b2b3-473ea16c30e5.png)|

fix(v2): remove top margin from first element inside doc article

---

packages/docusaurus-plugin-content-blog/src/blogUtils.ts

frontMatter date is string, cause build error
yes
the problem is obvious, cause error like this https://github.com/wenerme/wener/runs/3180667805#step:5:782

fix(v2): blog should parse frontMatter.date even when time is present

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/BackToTopButton/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx
packages/docusaurus-theme-classic/src/theme/TOC/index.tsx
packages/docusaurus-theme-classic/src/theme/TOCCollapsible/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-common/src/utils/announcementBarUtils.tsx
yarn.lock

Cleared 6 ESLint warnings. Also enforced typing variables and function params even when `noImplicitAny` is disabled in tsconfig. 
The only (comparatively) major change is regarding `CodeBlock`. Inferred from its use case, the children is actually not limited to `string` but can be JSX elements as well.
Yes
No functionality changes

refactor: reduce ESLint warnings / better typing

---

crowdin-v2.yaml

For languages such as `pt-BR` we want to keep the full locale to distinguish from `pt-PT` so let's add some custom mapping to download translations at `ì18n/pt-BR` instead of `i18n/pt` (site config is already correct)

fix: fix Crowdin mapping for pt-BR

---

website/community/2-resources.md

I found several PDF generation tools like mr-pdf can generate PDF for Docusaurus sites. But the output doesn't in good quality with some glitches:
- Doesn't work well with system Dark Mode. You will get a dark background in generated PDF. But it's not an issue in Ci/CD environments
- No Table of Contents support
- Based on Puppeteer make the text cannot be copied or searched correctly
- Link anchors (links start with `#`) not well handled
So I created a separate tool to generate PDF using Prince.
Yes
No tests required …

docs(v2): add docusaurus-prince-pdf to resources

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.tsx

A quick attempt to fix #5241 
Yes
Remove all navbar items in config file and go to docs page. Note that on regular pages such as homepage or blog pages, sidebar icon will not be displayed.

fix: show secondary menu if even there is no main one

---

packages/docusaurus/src/commands/swizzle.ts

The `.` should be escaped so it doesn't match any letter. Previously it would remove any `*ts` in the name, leading to some wrongly displayed names like `BlogTagsPoPage` and `MDXCompone`:
Yes
Verify by running `yarn swizzle @docusaurus/theme-classic` and see that the component names list is now displayed correctly.

fix: fix wrong regex that removes extra letters from swizzled component names

---

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
website/versioned_docs/version-2.0.0-beta.3/guides/markdown-features/markdown-features-code-blocks.mdx
website/versioned_docs/version-2.0.0-beta.4/guides/markdown-features/markdown-features-code-blocks.mdx

docs: fix broken link to syncing tab choices section

---

packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.js
packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-classic/src/validateThemeConfig.js
website/docs/api/themes/theme-configuration.md

- Remove `activeSidebarClassName` config, as it was probably never used by anyone and is confusing to use with Infima. Please let us know if you have a use-case for it, and we'll figure out a better api.
First of all, currently CSS class for active navbar item is duplicated, for example:
| Result   | Current HTML  | Expected HTML |
| -------- | -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/127777261-d02381b8-a294-430a-bd9c-710d2f9f3658.png) |  \<a aria-current="page" class="navbar__item navbar__link **navbar__link--active navbar__link--active**" href="/docs/next">Docs\</a>| \<a aria-current="page" class="navbar__item navbar__link **navbar__link--active**" href="/docs/next">Docs\</a> |
* * *
In addition to that, in mobile sidebar uses wrong …

fix: apply proper class for active doc item on mobiles + avoid duplicated classes

---

packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocVersionBanner/index.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/hooks/useContextualSearchFilters.ts
packages/docusaurus-theme-common/src/types.d.ts
packages/docusaurus-theme-common/src/utils/docsPreferredVersion/DocsPreferredVersionProvider.tsx
packages/docusaurus-theme-common/src/utils/docsPreferredVersion/useDocsPreferredVersion.ts

Remove the TODO & Reduce ESLint warnings about `no-explicit-any`. 
There were far more implicit `any`'s than captured by CI; for example, all the `useActivePlugin` hook usage was wrongly colored as green (for classes/types) rather than yellow (for functions) in my VSCode because the editor doesn't know what's the module `@theme/hooks/useDocs` at all.
Used some non-null assertions, but probably little side-effects (considering it's still an improvement from the previous `any`)
Yes
The build passes

refactor: properly type docs version

---

.github/workflows/canary-release.yml
package.json

Another attempt to fix the canary release naming convention to avoid `^2.0.0-beta.0a668366c2` picking up another version in lockfile after install.
The commit hash should rather not be used as a semver pre-release identifier because commit hashes won't be ordered properly in semver order. Adding the commit hash after the `+` is not used to determine precedence of the canary releases.
Also we can't use `2.0.0` prefix because non pre-release versions are picked up in priority over pre-release versions, so user might end-up with a stable release instead of a canary in the future. Switching to `0.0.0` makes sure that an user that really wants a canary will get a canary (assuming we'll never publish `0.0.0`)
https://semver.org/
Relevant spec paragraphs:
Useful for testing: …

fix: fix canary release versions

---

packages/docusaurus-theme-common/src/utils/docsPreferredVersion/useDocsPreferredVersion.ts

The only non-typing code change in #5284 caused `process` to be in client code bundle.
Realized that all the other code that use `@docusaurus/core/lib/constants` are server-side plugins, and turns out that requiring this module in `theme` would make the entire core bundle to appear in client... 
Yes
The preview should work as intended.

fix: fix constant value import

---

packages/docusaurus/package.json
packages/docusaurus/src/webpack/utils.ts
yarn.lock

Bumping version of clean-css because there was bug where spaces and line breaks were not removed around `var` calls (if any) in CSS code. This was fixed in 5.1.5, but `removeWhitespace` option in level 1 also needs to be enabled for correct work.
Yes
Preview
| ![image](https://user-images.githubusercontent.com/4408379/128487512-34f26489-f8b9-4737-a418-f59c5869d92d.png) | ![image](https://user-images.githubusercontent.com/4408379/128487582-854b856e-a461-4f3b-be09-c74c7f47ca2f.png) |

fix: remove unexpected whitespaces in CSS bundle

---

packages/docusaurus/src/commands/serve.ts

When I `docusaurus serve` when 3000 port is already used, I expect the modified port to be displayed on the console.
But the original port is displayed by mistake.
So I fixed this problem.
```
$ yarn build:package
$ python -m http.server 3000
$ docusaurus serve 
```

fix: docusaurus serve logs wrong port if 3000 is taken

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx

Just now noticed that in #5264 I broke highlighting of regular links, so I'm fixing that.  
Yes
On the preview site go to any non-doc link, such as "Showcase". In navbar, the corresponding navbar item should be highlighted.

fix: unbreak highlighting regular navbar links

---

website/docs/api/plugins/plugin-content-blog.md
website/docs/api/plugins/plugin-content-docs.md
website/docs/api/plugins/plugin-content-pages.md

Make it easier to understand that there are 2 ways to configure content plugins, and most users should use the preset config.
See confusion here: https://github.com/facebook/docusaurus/discussions/5246#discussioncomment-1087287
Preview: https://deploy-preview-5313--docusaurus-2.netlify.app/docs/next/api/plugins/@docusaurus/plugin-content-docs/

docs: try to make plugin/preset config less confusing

---

packages/docusaurus-theme-classic/src/theme/DocSidebarItem/index.tsx

Currently, unnecessary `active` CSS class (it's default class in [react-router](https://reactrouter.com/web/api/NavLink/activeclassname-string)) is added to active doc sidebar link. This happens because we use `NavLink`, which in this case we don't need, because we set our own logic to determine link activity.
Yes
Results on `docs/configuration` path:
| `<a class="menu__link menu__link--active active" tabindex="0" href="/docs/next/configuration" aria-current="page">Configuration</a>` | `<a class="menu__link menu__link--active" tabindex="0" href="/docs/configuration" aria-current="page">Configuration</a>` |
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link …

fix: avoid extra default active class on doc sidebar item

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx

fix: make proper highlighting doc link if no sidebar

---

CHANGELOG.md
website/community/5-changelog.md

Hack around the MDX import + TOC issue (https://github.com/facebook/docusaurus/issues/3915) to make sure this doc page displays a TOC.
Also, acts as a "proof of concept workaround" for this issue that others could try.
Having a very long TOC on this page is also helpful to test TOC-related edge-cases, such as https://github.com/facebook/docusaurus/issues/5318 . We can clearly see that there are some weird issues with our TOC highlighting.
https://deploy-preview-5331--docusaurus-2.netlify.app/community/changelog

docs: Changelog page should display TOC with releases

---

packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css

Fix small UI bug after #5230 because currently top margin is also removed in first element inside mobile TOC.
Yes
| ![image](https://user-images.githubusercontent.com/4408379/127444891-ec58ba0c-7649-4814-a94f-591b83b8185f.png) | ![image](https://user-images.githubusercontent.com/4408379/127444840-ce449294-3a72-416a-b01d-b265482f8134.png) |

fix: remove top margin only from directly first element

---

packages/docusaurus-plugin-ideal-image/src/index.ts

Hi! Following our discussion here (https://github.com/facebook/docusaurus/issues/5326), I wrote a PR to generate hash filename even in dev environnement.
I've run the test suites, linter & prettier and it seems fine. I've started the Docusaurus website locally as well.
I haven't found any tests for this plugin so I don't know if I should write some?
Yes

fix: plugin ideal-image should generate filename with a hash even in development 

---

packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogPostStructuredData/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts

This is an implementation of adding structured data support to blog posts, as discussed here: https://github.com/facebook/docusaurus/discussions/5321
The aim being to improve SEO of blog posts rendered with Docusaurus.
Yes
It doesn't look like there's any automated tests for this area, so let me show you what my manual testing resulted in.  With the change in place, blog posts have a new JSON-LD [structured data section](https://developers.google.com/search/docs/data-types/article#non-amp) of [`BlogPosting` type](https://schema.org/BlogPosting) appearing in the head which contains a subset of the frontmatter metadata:
```html
<script type="application/ld+json" data-react-helmet="true">
{
"@context":"https://schema.org",
"@type":"BlogPosting",
"headline":"Announcing Docusaurus 2 Beta", …
```

feat: structured data for blog posts

---

.eslintrc.js
packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
website/docs/guides/markdown-features/markdown-features-head-metadatas.mdx
website/sidebars.js

To give maximum control to the user, we should enable the user to declare page head metadatas on a per-md-file basis.
Fixes https://github.com/facebook/docusaurus/issues/2603
yes
dogfooding on our site
Preview: https://deploy-preview-5330--docusaurus-2.netlify.app/docs/next/markdown-features/head-metadatas/

feat: Markdown page-specific head metadatas

---

.github/workflows/v2-tests-e2e.yml
admin/scripts/test-release.sh

The Yarn 2 CI is failing for a while now and it's quite difficult to debug those Yarn 2/3 PnP-only issues.
For now, I'm reverting to node-modules linking, but would be happy to add another test with PnP mode if anyone is able to make it work.
CC @SamChou19815 in case you are interested to troubleshoot the issue. I was not able to do so (https://github.com/facebook/docusaurus/pull/5340).
Repro steps:
```js
rm -rf my-website-canary
npx @docusaurus/init@canary init my-website-canary classic --skip-install
cd my-website-canary
rm -rf node_modules yarn.lock .yarn .yarnrc.yml
yarn -v
yarn set version berry
yarn -v
yarn set version 2.4.2
yarn -v
yarn config set pnpMode loose
yarn config set enableGlobalCache true
yarn install
yarn start
```
Apart a few deps error, the main error is:
> Watchpack …

chore: fix e2e yarn berry tests

---

packages/docusaurus-theme-classic/src/theme/BlogPostStructuredData/index.tsx

Just small fixes in BlogPosting schema after merge #5322:
- Use author name instead of its title
- Use absolute URL for image instead of relative one
Results for `blog/2021/05/12/announcing-docusaurus-two-beta`:
```diff
- {"@context":"https://schema.org","@type":"BlogPosting","headline":"Announcing Docusaurus 2 Beta","description":"After a lengthy alpha stage in order to ensure feature parity and quality, we are excited to officially release the first Docusaurus 2 beta.","image":["/assets/images/social-card-414bbe5147ecc177bbe8d858616709c5.png"],"datePublished":"2021-05-12T00:00:00.000Z","author":{"@type":"Person","name":"Docusaurus maintainer","url":"https://sebastienlorber.com"}}
+ {"@context":"https://schema.org","@type":"BlogPosting","headline":"Announcing …
```

fix: author/image adjustments in BlogPosting schema

---

website/docs/styling-layout.md

The `docusaurus-plugin-sass` plugin has `sass` as a peer dependency, so you
need to install that package as well, as per their README.
Yes!
N/A (docs change)
N/A

docs: update `docusaurus-plugin-sass` instructions

---

website/docusaurus.config.js
website/src/css/custom.css

Add a link to Twitter account in the announcement bar.
I guess it can make sense to bump the version from time to time too to ensure that people subscribe for updates and "thank" Docusaurus.

docs(website): bump announcement bar + include Twitter link + refactor site colors

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css

Fix https://github.com/facebook/docusaurus/issues/5324

fix: code blocks should scroll in RTL direction

---

packages/docusaurus-theme-classic/src/theme/Heading/index.tsx
packages/docusaurus-theme-classic/src/theme/TOC/index.tsx
packages/docusaurus-theme-classic/src/theme/hooks/useTOCHighlight.ts
packages/docusaurus-theme-classic/src/types.d.ts

The TOC highlighting hook was quite messy and hard to understand
This is a total refactor with logic that is easier to reason about, and also solving some edge cases
Fix https://github.com/facebook/docusaurus/issues/5318 where the first anchor can highlighted even if it's way below the viewport.
Fix highlighting bugs due to not ignoring h4/h5/h6 headings
Fix unnecessary usage of state, leading to useless React re-renders on scroll
yes
preview

fix: refactor TOC highlighting + handle edge cases

---

packages/docusaurus-theme-common/src/components/Details/index.tsx

After merge #5341 our custom component for `details` element no longer work correctly, so this PR rolls back changes made in that PR.
Yes
Current state (https://docusaurus.io/docs/markdown-features#details):
Expected one - fixed (https://deploy-preview-5364--docusaurus-2.netlify.app/docs/markdown-features#details):

fix: unbreak Details component

---

packages/docusaurus-init/templates/classic-typescript/src/components/HomepageFeatures.tsx

Just noticed that the links to feature images are duplicated in classic-typescript.
Yes

fix(init): fix links to feature images in classic-typescript

---

website/docs/presets.md
website/versioned_docs/version-2.0.0-beta.3/presets.md
website/versioned_docs/version-2.0.0-beta.4/presets.md

Using a real existing preset name as an example seems less confusing for users.
Fix https://github.com/facebook/docusaurus/issues/5358

docs: remove docusaurus-preset-name from preset doc

---

packages/docusaurus/bin/beforeCli.js

Fix https://github.com/facebook/docusaurus/issues/5378
Only tested locally on a site using canary releases

fix: canary releases should ignore notifier updates

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/Heading/index.tsx
packages/docusaurus-theme-classic/src/theme/Heading/styles.module.css
yarn.lock

Instead of changing font size of main header via `font-size` property, it should only be possible to change related `--ifm-h1-font-size` CSS var. This is better approach also allows us to get rid of one extra class.
Yes
Preview (actually, there is no visible changes)

refactor: make main heading font size changeable via CSS var

---

packages/docusaurus/src/commands/writeTranslations.ts
packages/docusaurus/src/server/translations/translationsExtractor.ts

The `write-translations` cli is not able to extract theme-common translations, and we get a warning:
Instead of introducing a new plugin lifecycle just to extract from `theme-common`, I made a little hacky exception to solve this problem and automatically extract from this package that 99% of Docusaurus will use anyway.
yes
CI does not report the warning anymore

fix: fix write-translations warning for theme-common translations

---

website/static/_headers
website/static/_redirects

Some 404 pages are not properly localized: https://docusaurus.io/ko/xyz
We should apply ourselves patterns that we actually document in the i18n doc.
Also, we should cache `/assets` files aggressively because those are hashed by webpack and safe to cache. This will be documented later on a perf guide if successful.

fix: fix site unlocalized 404 pages + aggressive Netlify /assets caching

---

website/docs/deployment.mdx

Faced error @docusaurus/core@2.0.0-beta.4: The engine "node" is incompatible with this module. Expected version ">=12.13.0". Got "10.24.1"
(Write your motivation here.) I faced an error during TravisCI deployment. Build logs below
0.72s$ git clone --depth=50 --branch=master https://github.com/BattleOfPlassey/blogasaurus.git BattleOfPlassey/blogasaurus
0.01s
Setting environment variables from repository settings
$ export GH_TOKEN=[secure]
$ export GH_EMAIL=[secure]
$ export GH_NAME=[secure]
nvm.install
2.74s$ nvm install 10
cache.1
Setting up build cache
cache.yarn
cache.npm
$ node --version
v10.24.1
$ npm --version
6.14.12
$ nvm --version
0.38.0
$ yarn --version
1.22.4
21.14s$ yarn --frozen-lockfile
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
**error …

docs: specify proper min Node.js version for Travis CI example

---

website/docs/blog.mdx
website/docs/guides/docs/docs-create-doc.mdx

Resolve #5432. Also added `prettier-ignore` directives to prevent extra new-lines from being added.
Yes

docs: document doc tags + refinements

---

.github/workflows/v2-tests.yml
packages/docusaurus-init/templates/classic-typescript/package.json
packages/docusaurus-init/templates/classic-typescript/tsconfig.json
packages/docusaurus-mdx-loader/src/types.d.ts
packages/docusaurus-plugin-content-blog/index.d.ts
packages/docusaurus-plugin-content-docs/src/client/docsClientUtils.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/types.d.ts
website/package.json
website/tsconfig.json
yarn.lock

The TypeScript compiler screams at me again after bumping to `beta.5` when I ran `tsc` in my site repo. It turns out that CI checks fall short when it comes to the `.d.ts` files, so these mistakes tend to sneak in unnoticed.
Yes
```
cd website && yarn typecheck
```
This actually works well. Should we add it to the CI?

fix: fix a few TS errors

---

packages/docusaurus-theme-classic/src/theme/AnnouncementBar/index.tsx
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css

- Less code/complexity
- Better centered vertical alignment
|![before](https://user-images.githubusercontent.com/4408379/131104066-b6e2cd14-1225-4a0b-811c-13b53c51f1de.png) |  ![after](https://user-images.githubusercontent.com/4408379/131104081-e09cbc17-0cfb-4145-b68b-ffa3fa27e733.png) |
Yes
Preview.

refactor: switch to Flexbox in announcement bar

---

packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocItemFooter/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebarItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocTagDocListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocTagsListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocVersionBanner/index.tsx
packages/docusaurus-theme-classic/src/theme/EditThisPage/index.tsx
packages/docusaurus-theme-classic/src/theme/LastUpdated/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-common/src/utils/ThemeClassNames.ts

Start introducing some stable theme class names so that users can more easily target some components to customize with custom CSS selectors, ensuring those selectors don't break over time.
For now, we are just introducing some initial classNames, covering needs of the React-Native website, and we don't document this feature on purpose, so breaking changes can still happen.
If successful, we'll generalize and document this, and commit to avoid any undocumented breaking change.
Going to merge this now as I need it to make RN website more resilient, but feel free to comment if you have better ideas, naming convention, or whatever.
``
yes
preview

feat: Add docs-related stable classnames

---

packages/docusaurus-theme-classic/src/theme/AnnouncementBar/index.tsx
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css

The vertical centering of Unicode character is unstable, for example in Chrome on Linux, alignment of "x" char looks more or less ok, but in Chrome on Windows, it is much worse:
| Linux   | Windows |
| ![2021-08-31_10-40](https://user-images.githubusercontent.com/4408379/131463682-60f66f51-6c75-4a54-9e0d-b2ec0d3a567d.png) | ![2021-08-31_10-41](https://user-images.githubusercontent.com/4408379/131463678-aeff4a60-5ed5-4c25-9e7f-a86314deb98d.png) |
That's why I suggest using SVG icon to achieve uniform alignment in all browsers.
Yes
Preview

refactor: use SVG for closable button in announcement bar

---

.eslintrc.js
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/versions.test.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-docs/src/props.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-plugin-content-docs/src/versions.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
website/docs/api/plugins/plugin-content-docs.md
website/docusaurus.config.js

More customization options for docs versions:
- `badge` allows to show/hide the version badge on a per-version basis
- `className` allows to customize the rendering on a per-version basis. Class is applied to `<html>` so that users can even target layout elements (a good use-case is to hide some navbar elements on a per-version basis using CSS, potential workaround for https://github.com/facebook/docusaurus/issues/4389)
yes
tests

feat: new docs options: versions.{badge,className}

---

packages/docusaurus-init/templates/classic/docusaurus.config.js
packages/docusaurus-init/templates/facebook/docusaurus.config.js
packages/docusaurus-plugin-client-redirects/package.json
packages/docusaurus-plugin-client-redirects/src/plugin-client-redirects.d.ts
packages/docusaurus-plugin-content-blog/index.d.ts
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-blog/src/plugin-content-blog.d.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-pages/src/plugin-content-pages.d.ts
packages/docusaurus-plugin-content-pages/types.d.ts
packages/docusaurus-plugin-sitemap/package.json
packages/docusaurus-plugin-sitemap/src/plugin-sitemap.d.ts
packages/docusaurus-preset-classic/package.json
packages/docusaurus-preset-classic/src/index.js
packages/docusaurus-preset-classic/src/preset-classic.d.ts
packages/docusaurus-theme-bootstrap/package.json
packages/docusaurus-theme-classic/src/index.ts
packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
website/_dogfooding/dogfooding.config.js
website/docs/typescript-support.md
website/docusaurus.config.js
website/package.json

- Each TS plugin should expose  an `Options` type
- Each preset (only one actually) should re-expose underlying plugin options + `ThemeConfig`
- Site configs can consume those exported types for IDE auto-completion with JSDoc annotations
- Temporarily disable bootstrap theme integration / TS typechecking (we might even delete it someday?)
yes
IDE autocompletion works

feat: TypeScript presets/plugins should expose Options typing

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
website/docs/guides/markdown-features/markdown-features-tabs.mdx
website/src/components/BrowserWindow/styles.module.css
website/src/css/custom.css

Resolve #5441 
Yes
Preview: https://deploy-preview-5442--docusaurus-2.netlify.app/docs/next/markdown-features/tabs/

feat(theme-classic): allow passing tab label and default value through TabItem

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/index.tsx
packages/docusaurus-theme-classic/src/theme/IconClose/index.tsx
packages/docusaurus-theme-classic/src/theme/IconCloseThick/index.tsx
packages/docusaurus-theme-classic/src/theme/IconCloseThin/index.tsx
packages/docusaurus-theme-classic/src/theme/Navbar/index.tsx
packages/docusaurus-theme-classic/src/theme/Navbar/styles.module.css
packages/docusaurus-theme-classic/src/types.d.ts
yarn.lock

Add close button to navbar-sidebar
For consistency, reused the close button from the announcement bar 
(different stroke width compared to the hamburger but this doesn't feel like a big deal as buttons are in different places)
yes
preview
https://github.com/facebookincubator/infima/pull/174

feat: infima 33 + navbar-sidebar close button

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-plugin-debug/copyUntypedFiles.js
packages/docusaurus-plugin-debug/package.json
packages/docusaurus-plugin-debug/src/index.ts
packages/docusaurus-plugin-debug/src/theme/DebugConfig/index.tsx
packages/docusaurus-plugin-debug/src/theme/DebugContent/index.tsx
packages/docusaurus-plugin-debug/src/theme/DebugGlobalData/index.tsx
packages/docusaurus-plugin-debug/src/theme/DebugJsonView/index.tsx
packages/docusaurus-plugin-debug/src/theme/DebugLayout/index.tsx
packages/docusaurus-plugin-debug/src/theme/DebugRegistry/index.tsx
packages/docusaurus-plugin-debug/src/theme/DebugRoutes/index.tsx
packages/docusaurus-plugin-debug/src/theme/DebugSiteMetadata/index.tsx
packages/docusaurus-plugin-debug/src/types.d.ts

Another effort to get rid of AnyScript code in the repo.
Yes
Preview & CI

refactor(plugin-debug): migrate package to TypeScript

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.tsx
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/historyUtils.ts

Android users are used to using the hardware back button of their phone to close menus and drawers (cf Android apps, like Gmail)
Docusaurus users on Android might try that, and instead of closing the opened sidebar drawer, it would navigate to the previous page, potentially leaving the Docusaurus site. We should try to fix that UX issue.
Unfortunately, there's no browser API to easily detect or prevent backward navigation, and we have to use some tricks on top of the `history` package that offers a `block()` feature.
Still, it's not possible to distinguish easily between backward/forward navigation, so this remains a best effort. 
Closing the mobile sidebar on forward navigation is not an UX issue + the probably of an user using forward navigation on mobile with the drawer open is low, so …

feat: on back navigation, close mobile sidebar

---

packages/docusaurus-theme-classic/src/theme/Heading/index.tsx
packages/docusaurus-theme-classic/src/theme/Heading/styles.css
packages/docusaurus-theme-classic/src/theme/Heading/styles.module.css

Resolves https://github.com/facebook/docusaurus/discussions/5470
We have anchor link for headings without `href` attribute, which causes warning from Lighthouse https://developers.google.com/search/docs/advanced/guidelines/links-crawlable
But since we already use new `scroll-margin-top`, we can remove separate element for heading anchor, and instead just add this property on heading tag itself.
Yes
Preview + Lighthouse report

fix: use heading itself as anchor for better crawling

---

packages/docusaurus-plugin-content-blog/src/__tests__/blogFrontMatter.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/docFrontMatter.test.ts
packages/docusaurus-plugin-content-docs/src/docFrontMatter.ts
packages/docusaurus-utils-validation/src/validationSchemas.ts
website/docs/guides/docs/docs-create-doc.mdx

fix: add docs tag validation to solve #5478
nicer developer experience when people put in malformed tags, as suggested by @Josh-Cena  https://github.com/facebook/docusaurus/issues/5478#issuecomment-912118520
yes
i confess i did not test this one locally. hoping its a simple one.

fix: add docs tag validation to solve #5478

---

packages/docusaurus-theme-classic/src/theme/Navbar/index.tsx

Follow-up of https://github.com/facebook/docusaurus/pull/5462
Seems like people think it's better to prevent the navigation 
https://twitter.com/sebastienlorber/status/1433424873955610639
cc @lex111 
yes
preview

polish: prevent pop navigation on back if navbar sidebar is open

---

website/docs/deployment.mdx
website/versioned_docs/version-2.0.0-beta.5/deployment.mdx
website/versioned_docs/version-2.0.0-beta.6/deployment.mdx

Add some useful doc for v1 sites that upgraded and using Netlify, as it affected some FB Docusaurus sites

docs: mention Netlify ignore build setting

---

website/docs/guides/markdown-features/markdown-features-react.mdx

See https://github.com/facebook/docusaurus/issues/4029#issuecomment-920468413
Yes
Preview

docs: clarify MDX version used

---

README.md
admin/publish.md
website/docs/migration/migration-overview.md

Missed a few places in #5581 because I used case-sensitive global search🤦‍♂️
Yes

docs: fix more references to Discord channels

---

packages/docusaurus/src/client/App.tsx
packages/docusaurus/src/client/PendingNavigation.tsx
packages/docusaurus/src/client/normalizeLocation.ts

refactor(core): type improvements for `PendingNavigation`

---

packages/docusaurus-theme-classic/src/theme/BlogSidebar/styles.module.css

Fixes #5563
Because we use `restructureRules` option in clean-css, active item in a latest blog posts block on blog pages is not highlighted.
This bug is not reproduced on Docusaurus site because we have similar CSS selectors with the same declaration (`color: var(--ifm-color-primary)`), so we haven't noticed it.
Yes
Preview.

fix: highlight active item in recent post list

---

package.json
packages/docusaurus-mdx-loader/src/remark/headings/__tests__/index.test.ts
packages/docusaurus-mdx-loader/src/remark/transformLinks/index.ts
packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/sidebars.test.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-remark-plugin-npm2yarn/src/__tests__/index.test.js
packages/docusaurus-theme-bootstrap/src/types.d.ts
packages/docusaurus-theme-classic/src/theme/BlogArchivePage/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-classic/src/theme/Heading/index.tsx
packages/docusaurus-theme-classic/src/theme/TagsListInline/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-common/src/types.d.ts
packages/docusaurus-theme-common/src/utils/tagsUtils.ts
packages/docusaurus/src/client/docusaurus.ts
packages/docusaurus/src/client/types.d.ts
packages/docusaurus/src/server/routes.ts
packages/docusaurus/src/server/themes/index.ts
packages/docusaurus/src/server/types.d.ts
packages/docusaurus/src/webpack/utils.ts

Unused `eslint-disable` not only adds excess noise but also hides away future errors. Also a lot of the rules were simply disabled globally through `.eslintrc.js`, so the in-line disables are of no use.
We should enforce this by adding
```
eslint --cache "**/*.{js,jsx,ts,tsx} --report-unused-disable-directives
```
to the CI
Yes

polish: remove unused eslint-disable

---

packages/docusaurus-theme-live-codeblock/package.json
yarn.lock

Reported in #5555.
Since [latest minor version of react-live 2.3.0](https://github.com/FormidableLabs/react-live/releases/tag/v2.3.0) is built on hooks and not supports React v17, Docusaurus sites running through npm will not able use live code blocks because of error about React version mismatch (see https://github.com/FormidableLabs/react-live/issues/265#issuecomment-896702161). Of course, users can downgrade React version to make it work, or use webpack alias, but it would be better to handle this internally.
Therefore until react-live will not support React v17,  we should use its previous version of 2.2.0, which without hooks.
Yes
Test release
(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to …

fix: pin react-live due to possible mismatch React

---

packages/docusaurus-init/package.json
packages/docusaurus-init/src/index.ts
yarn.lock

Fix #5466 
Currently after #5233 merge dependencies are not install when initializing of new project via Yarn on Windows. This is probably because `FORCE_COLOR` environment variable is set  in command itself, but should be set in `env` object as second parameter in `shell.exec` call.
However just in case I use `supports-color` to make sure that terminal supports colorized output. 
Yes
Try initialize new Docusaurus project on Windows with Yarn using Command Prompt or Git Bash locally.

fix: install deps for new project via Yarn on Windows properly

---

packages/docusaurus-utils/src/__tests__/markdownParser.test.ts
packages/docusaurus-utils/src/markdownParser.ts

Resolves rather rare use case of improperly creating excerpt if multiline code block is at the beginning of MD document. For example, the React Native docs contains [the page](http://reactnative.dev/docs/usecolorscheme) with code block at first, which creates excerpt containing "`jsx" only.
Yes
Tests

fix: ignore code block lines when creating excerpt

---

packages/docusaurus-plugin-google-analytics/package.json
packages/docusaurus-plugin-google-analytics/src/analytics.ts
packages/docusaurus-plugin-google-analytics/src/index.ts
packages/docusaurus-plugin-google-analytics/src/plugin-google-analytics.d.ts
packages/docusaurus-plugin-google-analytics/src/types.d.ts
packages/docusaurus-plugin-google-analytics/tsconfig.json
packages/docusaurus-plugin-google-gtag/package.json
packages/docusaurus-plugin-google-gtag/src/gtag.ts
packages/docusaurus-plugin-google-gtag/src/index.ts
packages/docusaurus-plugin-google-gtag/src/plugin-google-gtag.d.ts
packages/docusaurus-plugin-google-gtag/src/types.d.ts
packages/docusaurus-plugin-google-gtag/tsconfig.json
packages/docusaurus-preset-classic/src/preset-classic.d.ts

More migration, also provided typings to their `ThemeConfig` fields.
Hopefully this makes refactoring the `themeConfig` options to plugin options more convenient
Yes

refactor(plugin-google-gtag, plugin-google-analytics): migrate packages to TS

---

packages/docusaurus-preset-classic/src/index.ts

Subsequent merge of https://github.com/facebook/docusaurus/pull/5579 + https://github.com/facebook/docusaurus/pull/5561 produced a TS issue:
This is a quick fix to make it work again in main, so I'll merge it asap
There may be a better solution, but not sure it's worth investing too much time on this.
cc @Josh-Cena

fix(preset-classic): fix TS build issue

---

website/docs/blog.mdx
website/docs/deployment.mdx
website/docs/guides/markdown-features/markdown-features-admonitions.mdx
website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
website/docs/guides/markdown-features/markdown-features-tabs.mdx
website/docs/i18n/i18n-crowdin.mdx

Since the new tabs API is probably less verbose, let's make it the encouraged behavior by using it _everywhere_.
Also documented the `npm2yarn` as a multi-language possibility, so that we can safely remove the `<MultiLanguageCode />` hint, since IMO we have already provided the right level of abstraction.
Yes

docs(website): document npm2yarn plugin + use new Tabs API everywhere

---

website/community/2-resources.md
website/docs/search.md

This PR is a follow-up to https://github.com/facebook/docusaurus/issues/5446#issuecomment-910164722.
The motivation behind this PR is to provide multiple options for a search bar for users, in addition to Algolia. To this end, I've updated the first section of the docs to list out all the options, I've then added a section about Typesense (linking to Typesense's documentation) and another section about local search plugins.
Yes.
I've already run this locally to make sure formatting is good, and that all links I added work fine.
None.

docs: add additional search options, typesense and local search

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/index.ts

Just fixes #5599.
Resolves
Preview (since we don't use tags, `/tags` should return 404 error)

fix(docs): create tags route if only tags exists

---

CHANGELOG.md

Currently, on changelog page there is a false call JSX-component `ColorGenerator`, which causes warning after building of site, and renders empty div instead text. 
```
Component ColorGenerator was not imported, exported, or provided by MDXProvider as global scope
```
Yes
Preview.

chore: fix warning after build

---

packages/docusaurus-theme-classic/src/theme/Heading/index.tsx
packages/docusaurus-theme-classic/src/theme/TOCInline/index.tsx
packages/docusaurus-theme-classic/src/theme/TOCItems/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-theme-common/src/utils/useTOCHighlight.ts

- Remove unnecessary heading level-specific classes (use `h` tags instead)
- Remove empty class attributes from final HTML markup
- Remove extra default values for props in child component (since parent one already passes them)
Yes
Preview

refactor: various TOC improvements

---

packages/docusaurus/src/client/serverEntry.js
website/_dogfooding/_pages tests/hydration-tests.js

Fix long-standing React hydration problem on text with links where links end-up with the wrong href after React hydration, due to mismatch between SSR HTML and client hydration.
Issue https://github.com/facebook/docusaurus/issues/5617 
(Also seen on React-Native and/or websites in the past)
Using `html-minifier-terser` `removeComments: true` is causing this hydration problem by turning this React SSR output:
```html
<div id="__docusaurus">
<span>
Built using the <a href="https://www.electronjs.org/" target="_blank">Electron</a> , 
based on <a href="https://www.chromium.org/" target="_blank">Chromium</a>
</span>
</div>
```
into this:
```html 
<div id="__docusaurus">
<span>Built using the <a href="https://www.electronjs.org/" target="_blank">Electron</a> , 
based on <a …
```

fix: text/link hydration bug

---

website/docs/search.md
website/docusaurus.config.js

Algolia is migrating to a new system where each app has an `appId` instead of all apps sharing the same `appId`
This allows them to provide a dashboard for each app, with access to the indice content, a query UI, the ability to trigger crawls manually... much helpful for users to debug their search issues
A progressive batched rollout has started, with the Docusaurus site as one of the first migrated site.
This PR is just some initial doc/config changes we can do today.
We'll write a blog post and update the doc later.
yes
preview

chore: prepare Algolia migration

---

packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css
packages/docusaurus-theme-classic/src/theme/BlogSidebar/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocItemFooter/styles.module.css
packages/docusaurus-theme-classic/src/theme/Navbar/styles.module.css
packages/docusaurus-theme-classic/src/theme/TOC/styles.module.css

For better minification of CSS bundle we should use the same media queries that will be consistent with all CSS code. In this case, that means getting rid of extra "only screen and" part.
Yes
Preview

refactor: standardize using media queries

---

packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/styles.css

Resolve https://github.com/facebook/docusaurus/issues/5409
Yes
I fixed displaying of the list 

fix(theme-classic): reset default style for task lists

---

.eslintrc.js
packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-plugin-content-blog/src/plugin-content-blog.d.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-pages/src/plugin-content-pages.d.ts
packages/docusaurus-plugin-debug/src/types.d.ts
packages/docusaurus-theme-classic/src/theme/DocTagDocListPage/index.tsx
packages/docusaurus-theme-classic/src/types.d.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/client/PendingNavigation.tsx
website/docs/lifecycle-apis.md

After swizzling, it's possible that users want additional props. This is impossible with `type Props` (at least without significant hacking), but because interface allows augmenting this becomes possible.
Yes

refactor: make all Props defined as interface + readonly

---

packages/docusaurus/src/server/plugins/__tests__/__snapshots__/init.test.ts.snap
packages/docusaurus/src/server/plugins/__tests__/init.test.ts
packages/docusaurus/src/server/plugins/index.ts

Should fix #3810
Yes
See snapshot.

fix: place root route at the end

---

packages/docusaurus-preset-classic/src/index.ts
website/docs/presets.md
website/versioned_docs/version-2.0.0-beta.7/presets.md
website/versioned_docs/version-2.0.0-beta.8/presets.md

Resolve #4239. After 8 months with no updates, let's do it ourselves
Yes
Add an unknown key in the website's config and `yarn start` fails
<details>
<summary>Error stack</summary>
```
$ docusaurus start
Starting the development server...
Error: Unrecognized keys badOption found in preset-classic configuration. The allowed keys are debug, docs, blog, pages, sitemap, theme. Check the documentation: https://docusaurus.io/docs/presets#docusauruspreset-classic for more information.
at preset (/Users/joshcena/Desktop/work/Tech/Projects/docusaurus/packages/docusaurus-preset-classic/lib/index.js:49:15)
at /Users/joshcena/Desktop/work/Tech/Projects/docusaurus/packages/docusaurus/lib/server/presets/index.js:32:62
at Array.forEach (<anonymous>)
at loadPresets …
```

feat(preset-classic): guard against unknown keys in options

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/commands/deploy.ts
packages/docusaurus/src/server/configValidation.ts
website/docs/api/docusaurus.config.js.md
website/docs/configuration.md
website/docs/deployment.mdx

Allows me to specify the deployment branch in docusaurus.config.js using a new `deploymentBranch` property, instead of having to use an environment variable. Deployment branch is usually static, so IMHO it should be stored inside docusaurus.config.js .
Yes
I used this on my own GitHub Pages site. The repo name is `wpyoga.github.io`, but I deploy to a `gh-pages` branch, instead of the usually-default `master` or `main` branch.
```shell-session
$ yarn add ../docusaurus_allow-deployment-branch-config/packages/docusaurus
$ yarn install
$ USE_SSH=true yarn deploy
```
If #5840 is merged, then no need to set USE_SSH=true when running `yarn deploy` on my local repo.

feat: allow user to specify deploymentBranch property in docusaurus.config.js

---

website/src/featureRequests/FeatureRequestsPlugin.js
website/static/_redirects

Fix #5553. Append base URL to routes so that i18n routes are created as well.
Yes
https://docusaurus.io/zh-CN//feature-requests

docs: fix i18n routes to feature requests

---

package.json

When I want to submit patches to docusaurus, I use a separate branch for each PR. I like to work in different git worktrees, so I can get a clean base repo for each patch to apply. What I like to do is use the format `docusaurus@branch-name` as the worktree directory name.
However, `@` is not a valid character in an npm package name, so `yarn install` will fail when calling `lerna bootstrap`. This patch allows this use case by adding a `"name": "root"` property to package.json. It's actually done by default by newer versions of lerna when we run `yarn lerna init`. This behaviour has been [observed here](https://github.com/lerna/lerna/issues/1835#issuecomment-955625905) (it's my own comment).
Yes
1. Clone docusaurus repo or make a worktree in a directory named …

misc: add "name" field for root package.json

---

packages/docusaurus-theme-live-codeblock/copyUntypedFiles.js
packages/docusaurus-theme-live-codeblock/package.json
packages/docusaurus-theme-live-codeblock/src/__tests__/validateThemeConfig.test.ts
packages/docusaurus-theme-live-codeblock/src/custom-buble.ts
packages/docusaurus-theme-live-codeblock/src/index.ts
packages/docusaurus-theme-live-codeblock/src/types.d.ts
packages/docusaurus-theme-live-codeblock/src/validateThemeConfig.ts
packages/docusaurus-theme-live-codeblock/tsconfig.json
yarn.lock

#5817
Yes
Build & deploy preview

refactor(live-codeblock): migrate package to TS

---

website/docs/guides/docs/versioning.md

Fix a typo
Yes
Not needed
None

docs: Fix a typo in versioning.md

---

website/docusaurus.config.js

Currently versions dropdown on the site is quite long, I propose to reduce its items by showing only the latest archived versions, since all available versions already renders on the "Versions" page.
Yes
Preview.

misc: show only latest archive alpha/beta versions dropdown

---

.eslintrc.js
packages/docusaurus-plugin-content-blog/src/authors.ts
packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/generator.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars/generator.ts
packages/docusaurus-theme-classic/update-code-translations.js
packages/docusaurus-utils/src/codeTranslationsUtils.ts
packages/docusaurus-utils/src/index.ts

YAML 1.2 has made YAML a strict superset of JSON, so we don't need `JSON.parse` anymore.
Yes
Tests that read JSON fixtures still pass

refactor: use js-yaml to parse both JSON and YAML

---

packages/docusaurus/src/commands/start.ts

Fixes #5863
Apparently, as often happens, we forgot to handle the base URL :see_no_evil: 
Yes
Set base url and try serve site.

fix: respect base URL when serving content by webpack dev server

---

website/docs/search.md

I notice there has one duplicated property called `appId`.
Yes
No
https://github.com/facebook/docusaurus/pull/5632

docs: remove duplicated appId property

---

README.md

* Commit 66771bd80d1fad1fe46cf79a4bd578dd90756f89 renames the file v2-tests.yml to tests.yml
in PR #5833 which broke the github actions test icon and link to the workflow.
Signed-off-by: Hemant Sachdeva <hemant.evolver@gmail.com>
Yes
I changed the icon which was not showing up correctly in README. After I made changes icon and link to the workflow works fine now. Commit and PR number is mentioned above who broke the icon.

chore(README): fix broken Github Actions Workflow Status icon

---

packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css

After merging this PR: https://github.com/facebook/docusaurus/pull/3104
The insertion order of CSS classes became different 🤷‍♂️ 
This is a temporary fix, the original problem looks related to https://github.com/facebook/docusaurus/issues/3678
yes
preview

fix(theme-classic): fix announcementBar css

---

packages/docusaurus/bin/beforeCli.js

fix(cli): update notifier should be shown if current is less than latest

---

website/docs/introduction.md
website/versioned_docs/version-2.0.0-beta.8/introduction.md
website/versioned_docs/version-2.0.0-beta.9/introduction.md

There is a typo or grammatical error in a few portions of the documentation, where people are invited to "read the 5 minutes tutorial" rather than the "5 minute tutorial".
Yes
Just a copy change, no test changes should be required.

docs: '5 minutes tutorial' -> '5-minute tutorial'

---

website-1.x/blog/2021-11-05-algolia-migration.md
website-1.x/siteConfig.js

Algolia Docsearch is migration to a new system.
Docusaurus v1 config must be updated to keep the search working.
Also added a v1 blog post so that v1 users that still visit it can be notified

fix: v1 Algolia DocSearch migration

---

website/docs/deployment.mdx

Following the deployment documentation at https://docusaurus.io/docs/deployment I noticed a couple of mistakes that I had to correct before I could do a successful deployment.
Yes
N/A (documentation only)
None that I could find.

docs: update GitHub deployment instructions

---

website/docs/guides/creating-pages.md
website/docs/guides/markdown-features/markdown-features-react.mdx

Complete #5200 because that can't be merged without CLA and doesn't look like the author is ever responding.
Yes

docs: document global variables in MDX scope

---

website/src/featureRequests/FeatureRequestsPage.tsx
website/src/featureRequests/FeatureRequestsPlugin.js

Pass the base route as props so that canny can handle the route correctly.
Yes
Tested locally with `yarn start --locale zh-Hans` and `https://localhost:3000/zh-Hans/feature-requests` is not redirected to `https://localhost:3000/feature-requests` after Canny loads.

fix(website): fix i18n routes for Canny board

---

website/docs/deployment.mdx

The deployed branch should be called deployment branch because our API is called `deploymentBranch`; "target" is also not specific enough.
Yes

docs: refer to deployed branch as deployment rather than target

---

packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-docs/src/__tests__/lastUpdate.test.ts
packages/docusaurus-plugin-content-docs/src/lastUpdate.ts

Resolve #4455. Up to this point, the only thing that we should fix is removing `execa` in favor of `shelljs`. Now, we only have `fs-extra` for FS operations and `shelljs` for "actual shell operations". `del` is used in a forked plugin which I think we shouldn't touch, `mkdirp` isn't used anymore.
Yes
Updated test cases a little bit; can also check preview that updated data is rendered correctly

refactor(content-docs): use shelljs instead of execa

---

packages/docusaurus-plugin-content-docs/src/lastUpdate.ts

In #5904 I forgot to inspect the log... `shell.exec` outputs the result to the console which isn't necessary.
Yes

fix(content-docs): do not echo git history to console

---

packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
packages/docusaurus-plugin-content-blog/src/types.ts
website/docs/api/plugins/plugin-content-blog.md

Solves #5692
Yes.
Regression tests for older relevant tests.
Created new test that sorts posts in reverse creation order and compare it to default option.

feat(content-blog): allow sorting posts in ascending order

---

packages/docusaurus/src/server/plugins/__tests__/__snapshots__/pluginIds.test.ts.snap
packages/docusaurus/src/server/plugins/pluginIds.ts

It has happened not a single time that a user enhanced a plugin and forgot to turn off the default plugin in the preset. I think we can benefit from some more hints on how to solve the error.
In the future we are to have a better middleware / enhancement system, and we can further mitigate the problem of duplicating IDs after enhancing.
Yes

feat(core): give more hints when plugins have duplicate IDs

---

.github/workflows/tests-e2e.yml

The E2E tests don't even involve the website — not running them saves bandwidth & review noise. Also made the job names more succinct.
Yes

misc(workflow): E2E tests should not be run with website changes

---

website/docs/api/plugins/plugin-content-blog.md
website/docs/api/plugins/plugin-content-docs.md
website/docs/api/plugins/plugin-content-pages.md
website/docs/api/themes/theme-configuration.md
website/src/components/APITable/index.tsx
website/src/components/APITable/styles.module.css
website/versioned_docs/version-2.0.0-beta.8/api/plugins/plugin-content-blog.md
website/versioned_docs/version-2.0.0-beta.8/api/plugins/plugin-content-docs.md
website/versioned_docs/version-2.0.0-beta.8/api/plugins/plugin-content-pages.md
website/versioned_docs/version-2.0.0-beta.8/api/themes/theme-configuration.md
website/versioned_docs/version-2.0.0-beta.9/api/plugins/plugin-content-blog.md
website/versioned_docs/version-2.0.0-beta.9/api/plugins/plugin-content-docs.md
website/versioned_docs/version-2.0.0-beta.9/api/plugins/plugin-content-pages.md
website/versioned_docs/version-2.0.0-beta.9/api/themes/theme-configuration.md

When giving instructions on how to enable a particular option, it usually is quite awkward to give a link to the entire API table instead of pointing them to a specific row.
This PR introduces a new `APITable` on the website which allows us to direct to a specific row through anchor links. When visitors click on that link, the respective entry will also be highlighted.
Yes
https://deploy-preview-5891--docusaurus-2.netlify.app/docs/api/plugins/@docusaurus/plugin-content-blog#archiveBasePath

docs: new APITable comp to render large tables

---

CHANGELOG.md
crowdin-v2.yaml

Hello,
I've found some minor typos in the documentation, solved with this PR.
Fix typo:
the the -> the

docs: fix a typo in CHANGELOG

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-common/package.json
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts

To make the diff in #5783 less confusing. Moved all highlight-related code to theme-common.
Not sure if we should be less opinionated and pass the directives as params instead of hard-coded? Is there a customization need here?
Yes
Preview; rendered result still the same.

refactor(theme-classic): move some logic of CodeBlock to theme-common

---

website/src/components/APITable/index.tsx

The anchor links are currently broken because `id` is not set to `anchor`.
Yes

fix(website): fix APITable anchor link

---

website/src/components/APITable/index.tsx

Anchors are still broken ㄟ(▔,▔)ㄏ
Yes

fix(website): fix APITable anchor ID having extra hash

---

packages/docusaurus-module-type-aliases/src/index.d.ts

Try to fix https://github.com/facebook/docusaurus/issues/3424#issuecomment-846462626 by adding module declarations in `packages/docusaurus-module-type-aliases/src/index.d.ts`:
Currently, if one uses `import` ending with `.module.scss`, `.scss`, `.svg` in a `.tsx` file, VSCode (ESLint) will display errors like:
```
Cannot find module '[some_file].module.scss' or its corresponding type declarations.
Cannot find module '[some_file].scss' or its corresponding type declarations.
Cannot find module '[some_file].svg' or its corresponding type declarations.
```
These errors don't appear in `.js` files.
Yes
Just tested with `yarn run start` (after `cd website`), `yarn prettier`, `yarn lint`, and `yarn test`.

fix(module-type-aliases): add svg declaration

---

website/docs/docusaurus-core.md
website/versioned_docs/version-2.0.0-beta.8/docusaurus-core.md
website/versioned_docs/version-2.0.0-beta.9/docusaurus-core.md

Missed return statement at BrowserOnly component
Yes
None
None

docs: fix BrowserOnly return statement

---

.eslintignore
packages/docusaurus-plugin-pwa/copyUntypedFiles.js
packages/docusaurus-plugin-pwa/package.json
packages/docusaurus-plugin-pwa/src/index.ts
packages/docusaurus-plugin-pwa/src/options.ts
packages/docusaurus-plugin-pwa/src/plugin-pwa.d.ts
packages/docusaurus-plugin-pwa/src/theme/PwaReloadPopup/index.tsx
packages/docusaurus-plugin-pwa/src/types.d.ts
packages/docusaurus-plugin-pwa/tsconfig.browser.json
packages/docusaurus-plugin-pwa/tsconfig.json
packages/docusaurus-plugin-pwa/tsconfig.server.json
packages/docusaurus-theme-classic/update-code-translations.js

refactor(plugin-pwa): migrate package to TS

---

packages/docusaurus-plugin-google-analytics/src/index.ts
packages/docusaurus-plugin-google-gtag/src/index.ts
packages/docusaurus-types/src/index.d.ts

refactor(types): correct HtmlTags types

---

packages/docusaurus-plugin-ideal-image/copyUntypedFiles.js
packages/docusaurus-plugin-ideal-image/package.json
packages/docusaurus-plugin-ideal-image/src/deps.d.ts
packages/docusaurus-plugin-ideal-image/src/plugin-ideal-image.d.ts
packages/docusaurus-plugin-ideal-image/src/theme/IdealImage/index.tsx
packages/docusaurus-plugin-ideal-image/tsconfig.browser.json
packages/docusaurus-plugin-ideal-image/tsconfig.json
packages/docusaurus-plugin-ideal-image/tsconfig.server.json

refactor(plugin-ideal-image): migrate package to TS

---

packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/versions.test.ts
packages/docusaurus-plugin-content-docs/src/docFrontMatter.ts
packages/docusaurus-plugin-content-docs/src/docs.ts
packages/docusaurus-plugin-content-docs/src/globalData.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/numberPrefix.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-docs/src/props.ts
packages/docusaurus-plugin-content-docs/src/sidebars/normalization.ts
packages/docusaurus-plugin-content-docs/src/sidebars/types.ts
packages/docusaurus-plugin-content-docs/src/sidebars/utils.ts
packages/docusaurus-plugin-content-docs/src/sidebars/validation.ts
packages/docusaurus-plugin-content-docs/src/slug.ts
packages/docusaurus-plugin-content-docs/src/tags.ts
packages/docusaurus-plugin-content-docs/src/translations.ts
packages/docusaurus-plugin-content-docs/src/versions.ts

Move isCategoriesShorthand from types to utils
Ensure that type imports are marked as such
yes
maybe we should consider enabling
```ts
{
files: ['*.ts', '*.tsx'],
rules: {
'@typescript-eslint/consistent-type-imports': [
ERROR,
{
prefer: 'type-imports',
disallowTypeAnnotations: false,
},
],
},
},
```

refactor(plugin-content-docs): move isCategoriesShorthand to utils

---

.github/workflows/tests.yml
website/_dogfooding/_pages tests/deep-file-path-test/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/foo/bar/test-file.md

Fix #5793. It would still be cool to verify that things do work, but generating the file during CI ensures Windows contributors don't get unnecessarily hindered by the extra configuration needed.
Yes
Windows tests

chore: generate dogfooding test for long pathname during CI

---

packages/docusaurus-plugin-pwa/package.json
yarn.lock

We already use core-js v3 in the actual code (in babel settings), but it's funny that we still declared core-js v2 in package.json. This hasn't caused much trouble so far because the core provides core-js v3.
We can't rid ourselves of core-js v2 entirely, however, because react-live@2.2.3 depends on it. react-live doesn't work with React v17 yet (#5556), and it's on my hate-list of dependencies😅 Users who use pwa but not live-codeblock may be able to get rid of core-js in their node_modules.
Yes
The PWA still works in deploy preview

chore(plugin-pwa): change core-js version in package.json to v3

---

packages/docusaurus-theme-classic/src/theme/Heading/styles.css

Fix #5990. I added an attribute about 'user-select' to the hash-link class. And it can help me to copy the text without worrying about ZWSP.
Yes
Manual verification.

fix: make hash link in heading not selectable

---

package.json
packages/docusaurus/package.json
packages/docusaurus/src/commands/start.ts
yarn.lock

See https://github.com/webpack/webpack-dev-server/releases/tag/v4.5.0
Yes
Try to run dev server locally.

chore: upgrade webpack-dev-server to v4.5.0

---

.github/workflows/showcase-test.yml

Tests are not run when only the website is changed—this rule will not be changed because there are far more cases where the tests are useless. Instead, I added another workflow specifically for showcase changes. Even better—if we figured out how to do #5980, we can add it here as another workflow.
Yes
We'll test with the badly configured #6001

chore(ci): add GitHub action for showcase testing

---

website/docs/deployment.mdx

Motivated by https://github.com/facebook/docusaurus/issues/6004 -> docs mention what to change when custom domain is used with github pages, but don't mention changing the `url`, which can be confusing (it was for me).

docs: improve explanation for url config in GH Pages

---

website/docs/search.md

The current version makes it look like you need to install `@docusaurus/theme-search-algolia` on top the classic version to work, but it already works with the classic version. Adding `@docusaurus/theme-search-algolia` on top leads to errors.

docs: improve algolia integration instructions

---

website/src/pages/showcase/_components/ShowcaseCard/index.tsx
website/src/pages/showcase/_components/ShowcaseCard/styles.module.css
website/src/pages/showcase/_components/ShowcaseFilterToggle/index.tsx
website/src/pages/showcase/_components/ShowcaseFilterToggle/styles.module.css
website/src/pages/showcase/_components/ShowcaseTagSelect/index.tsx
website/src/pages/showcase/_components/ShowcaseTagSelect/styles.module.css
website/src/pages/showcase/_components/ShowcaseTooltip/index.tsx
website/src/pages/showcase/_components/ShowcaseTooltip/styles.module.css
website/src/pages/showcase/index.tsx
website/src/pages/showcase/styles.module.css

- Fix HTML errors:
- The “aria-describedby” attribute must point to an element in the same document.
- Element “h2” not allowed as child of element “span” in this context. (Suppressing further errors from this subtree.)
- Fix underline of link (in case of multi-line text) 
- Remove redundant code (styles/attributes). Side-note:  `aria-describedby` should be used on interactive/focusable elements
- Use outline for focus state (for better a11y and consistency)
- Preserve scroll position after change filters for nicer UX
Yes
Preview

refactor(website): various fixes and improvements on Showcase page

---

website/docusaurus.config.js
website/src/components/APITable/index.tsx
website/src/data/__tests__/user.test.ts
website/src/pages/index.tsx
website/src/pages/showcase/_components/ShowcaseTagSelect/index.tsx
website/src/pages/showcase/_components/ShowcaseTooltip/index.tsx
website/src/pages/showcase/index.tsx
website/src/pages/versions.tsx
website/src/utils/jsUtils.ts
website/tsconfig.json

When working on #5997 I was a little confused by `undefined` and `null` not being caught by TS. Enabling `strict` helps catch type errors early and also helps us dogfood our typing better.
Yes
`cd website && tsc`

chore(website): enable strict compiler option

---

website/docs/deployment.mdx

Netlify now provides `*.netlify.app` subdomains instead of `*.netlify.com` for project sites. Redirects still work, so the current config option isn't wrong but it's a good idea to keep the docs up to date.
Yes!

docs: update Netlify url config option

---

admin/new.docusaurus.io/package.json
package.json
website/netlify.toml
yarn.lock

We use a _far_ outdated cli that triggers loads of deprecation warnings on install 🤦‍♂️ I know that these deprecations warnings usually mean nothing, but it also takes nothing to upgrade, since we just use `netlify dev` which is always supported. The major versions just drop node versions & renew deps, and we just need to use the latest node when deploying.
Yes
Deploy preview

chore: upgrade netlify-cli

---

packages/docusaurus-theme-common/src/utils/storageUtils.ts

Storage APIs must be considered as unreliable, and Docusaurus should keep working even if all storage apis throw errors.
See also https://github.com/facebook/docusaurus/issues/6036
yes
only tested locally by making lower-level apis throw => Docusaurus stays accessible

fix(v2): Browser storage (localStorage) is unreliable: api should fail-safe

---

.eslintrc.js
packages/docusaurus-theme-classic/src/index.ts
packages/docusaurus-theme-classic/src/translations.ts
packages/docusaurus-theme-search-algolia/src/theme-search-algolia.d.ts
packages/docusaurus-theme-translations/update.js
packages/docusaurus-theme-translations/update.test.js
packages/docusaurus-types/src/index.d.ts

- Fixed a few warnings.
- Removed two import resolver ignores because they are already ignored by type-only imports.
- Turned on [`@typescript-eslint/method-signature-style`](https://typescript-eslint.io/rules/method-signature-style), reason in that rule
Yes
Lint

refactor: minor ESLint improvements

---

packages/docusaurus-theme-classic/src/theme/Toggle/index.tsx
packages/docusaurus-theme-classic/src/theme/Toggle/styles.module.css
packages/docusaurus-theme-common/src/index.ts

Essentially `icons` prop is what's left of `react-toggle` we used earlier. So we don't need this one in our implementation at all, it just complicates the component code at this time.
Yes
Preview

refactor: simplify Toggle component

---

website/src/data/users.tsx

Change: `widely` -> `wisely`
```
Removed: // Please choose widely, we'll remove unappropriate tags
Changed: // Please choose wisely, we'll remove unappropriate tags
`` 
Very small nitpick. Thanks for reviewing it in advance

refactor(website): improve wording in comments of showcase data

---

packages/docusaurus-plugin-content-blog/src/__tests__/__snapshots__/feed.test.ts.snap
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
website/_dogfooding/_blog tests/2021-09-13-dup-title.md
website/_dogfooding/_blog tests/2021-11-13-dup-title.md

The blog posts' ID may have changed. Previously, they represented neither the slug nor the title: it was a weird mix of the two, which makes it pretty useless for rendering. Moreover, we discovered that this ID generation is not guaranteed to be unique either. Now, we have normalized all IDs into the posts' slugs. If you relied on the whacky IDs before in your swizzled component, consider using either `metadata.title` or `slug` instead.
Fix #6059
Added two dogfooding posts

fix(content-blog): make post ID unique

---

packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css
packages/docusaurus/src/client/App.tsx

Quick fix in place of #5987. This is much less risky than reordering all CSS.
Yes
The CSS errors are still gone

fix(core): fix error boundary import disrupting CSS order

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/LocaleDropdownNavbarItem/index.tsx
packages/docusaurus/src/server/__tests__/i18n.test.ts
packages/docusaurus/src/server/i18n.ts

Locale labels must be initially uppercased, because it is currently renders as lower-cased for active item in dropdown. 
Yes
| ![image](https://user-images.githubusercontent.com/4408379/144704215-0d3df612-8899-4d64-b64b-549488911c51.png) |![image](https://user-images.githubusercontent.com/4408379/144704304-0e750ecd-e614-428b-9e7a-7d620dc3a260.png) |

refactor: capitalize locales when creating i18n config

---

packages/docusaurus-theme-common/src/utils/useLocationChange.ts

Fix little issue reported by @lex111  here: https://github.com/facebook/docusaurus/pull/5714#discussion_r760685024
The `useLocationChange` always fires again on the very first re-render
yes
preview (tried to write tests but ReactRouter makes this quite hard, `<StaticRouter>` can't update location :s

fix(theme-common): useLocationChange fire un-necessarily twice

---

packages/docusaurus-plugin-client-redirects/package.json
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-pages/package.json
packages/docusaurus-plugin-debug/package.json
packages/docusaurus-plugin-google-analytics/package.json
packages/docusaurus-plugin-google-gtag/package.json
packages/docusaurus-plugin-ideal-image/package.json
packages/docusaurus-plugin-pwa/package.json
packages/docusaurus-plugin-sitemap/package.json
packages/docusaurus-preset-classic/package.json
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-common/package.json
packages/docusaurus-theme-live-codeblock/package.json
packages/docusaurus-theme-search-algolia/package.json

While upgrading to latest beta 10, it gives `@docusaurus/core` peer dependency error due to different versions required by `@docusaurus/preset-classic` and root `@docusaurus/core`. Current canary release seems broken as well because of this inconsistent requirements.
Trying to fix the peer dependency error while upgrading to the latest beta 10.
Details of error:
```
$ npm i @docusaurus/core@latest @docusaurus/preset-classic@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: XXXXXXXX@0.2.1
npm ERR! Found: @docusaurus/core@2.0.0-beta.10
npm ERR! node_modules/@docusaurus/core
npm ERR!   @docusaurus/core@"2.0.0-beta.10" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer …
```

fix: move docusaurus core back to hard dependencies

---

.github/workflows/tests-e2e.yml
admin/scripts/test-release.sh

After this peer dependency incident (and previously #5803), let's add NPM & PNPM to our E2E matrix.
Yes
CI

chore: add NPM and PNPM to E2E tests

---

packages/docusaurus-plugin-content-docs/src/docs.ts

Little retro compatibility issue after updating the sidebar versioning strategy (see also https://github.com/facebook/docusaurus/issues/6018)
Affecting the Jest website, which is not using `slug: /` unlike our website, so we didn't see this issue on our own website
yes
local only, it's code that we'll remove quite soon anyway (as part of https://github.com/facebook/docusaurus/issues/6018)

fix(content-docs): getMainDocId should return doc with both versioned or unversioned id

---

website/src/data/users.tsx

Something that a friend noticed when I was sharing screenshots of the preview deploy of #6090, figured I might as well fix it right away.
For the sake of explaining the change if at all necessary, here's a good StackExchange: https://english.stackexchange.com/a/47921. TL;DR is that it's "many more" with countable nouns, and pages are countable.
Yes
Yes
N.A.

docs(showcase): "much more pages" => "many more pages"

---

.github/workflows/tests-e2e.yml
packages/docusaurus-theme-classic/package.json
packages/docusaurus-utils-validation/package.json

https://github.com/facebook/docusaurus/pull/6047 made Docusaurus PnP strict mode compatible but by default PnP [still allows some fallbacks](https://yarnpkg.com/features/pnp/#fallback-mode), this PR disables that fallback in the e2e test and adds the remaining undeclared dependencies.
Yes
The e2e test passes

fix: declare missing dependencies

---

packages/create-docusaurus/src/index.ts

fix(create-docusaurus): give a clearer message when installation failed

---

packages/docusaurus/src/commands/start.ts

We never documented this, but with Webpack 4 there was the ability to just write `config.devServer`
Since Webpack 5, it does not work automatically anymore with the Node imperative API, and users can't customize easily the devServer.
Instead of adding a new API, I'm merging the user/plugin-provided devServer config to the default one to allow this niche use-case.
Note: Docusaurus users integrating with an API on another domain may find this useful to write a plugin such as:
```tsx
function ProxyPlugin(context) {
return {
name: 'proxy-plugin',
configureWebpack() {
return {
devServer: {
proxy: {
'/hey': {
target: 'https://google.com',
pathRewrite: {'^/hey': ''},
},
},
},
};
},
};
}
```
yes
local for now, but we should find a way to test the start/devServer workflow better
Fixes …

feat(core): allow plugins to customize/override Webpack devServer config

---

website/docs/guides/docs/sidebar.md
website/docusaurus.config.js
website/versioned_docs/version-2.0.0-beta.10/guides/docs/sidebar.md
website/versioned_docs/version-2.0.0-beta.13/guides/docs/sidebar.md

Motivated by #3212, there had been confusions in the past about doc edits not taking effect in deploy preview.
Yes

refactor(website): make deploy preview open next version docs by default

---

website/docs/guides/markdown-features/markdown-features-head-metadata.mdx
website/docs/seo.md

Inspired by #6108, it seems that sometimes users don't understand the right time to use this.
Yes

docs: mention that SEO through front matter is better than head tag

---

website/docusaurus.config.js

This fixes the `yarn build:website:fast` command that reports broken links atm, and revert a temporary change that we had to make temporarily (related to https://github.com/facebook/docusaurus/issues/6041)

fix(website): fix yarn build:website:fast

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css

Fixes #6077 
Yes.
Run `yarn start:website` and go to http://localhost:3000/docs/next/installation#scaffold-project-website. When focusing on the code block, it should like below:
Firefox
Chrome

fix(theme-classic): add outline to focused code blocks

---

packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/simple-site/docs/foo/bar.md
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/docs.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/docs.ts

Fix #6103 
Yes
Added one fixture test

fix(content-docs): restore behavior when pagination front matter is null

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-common/src/utils/ThemeClassNames.ts
website/docs/styling-layout.md

Requested here: https://github.com/typescript-eslint/typescript-eslint/pull/4324#discussion_r771776932
Yes

feat(theme-common): stable classname for code blocks

---

packages/docusaurus-plugin-content-blog/src/__tests__/__snapshots__/feed.test.ts.snap
packages/docusaurus-plugin-content-blog/src/__tests__/feed.test.ts
packages/docusaurus-plugin-content-blog/src/__tests__/pluginOptionSchema.test.ts
packages/docusaurus-plugin-content-blog/src/feed.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
packages/docusaurus-plugin-content-blog/src/types.ts
website/docs/api/plugins/plugin-content-blog.md
website/docs/blog.mdx

Support to generate [json feed](https://www.jsonfeed.org/2017/05/17/announcing-json-feed.html) of blog posts.
yes
Add test case for generating json feed. 
None

feat(content-blog): support json feed

---

packages/docusaurus-theme-classic/src/theme/Heading/index.tsx

Fix a11y issue with hash links reported by Rocket Validator, I keep forgetting that.
> ARIA hidden element must not contain focusable elements
Yes
Preview

fix: do not use aria-hidden in heading anchor links

---

website/docs/migration/migration-manual.md

The v2 migration documentation links to a README that does not exist:
https://docusaurus.io/docs/migration/manual#readme
In this section, this link throws a 404:
https://github.com/facebook/docusaurus/blob/main/packages/create-docusaurus/templates/classic/README.md
This PR introduces a README.md file at the desired location, referencing the other READMEs found in the `packages/create-docusaurus/templates/` directory.
Yes
Testing cannot take place until the README is merged into the main branch and the blob exists.

docs: update link to init template README.md

---

website/docs/blog.mdx
website/docs/guides/docs/docs-introduction.md

Love for opensource and trying out new things
Yes

docs: elaborate on "docs-only" and "blog-only"

---

website/docs/guides/markdown-features/markdown-features-admonitions.mdx

Some people at Meta were confused when they ran Prettier on their Markdown files and Prettier messed up their admonition syntax.
Yes
Netlify preview

docs: mention admonition quirks with Prettier

---

packages/docusaurus-theme-classic/src/__tests__/__snapshots__/translations.test.ts.snap
packages/docusaurus-theme-classic/src/__tests__/translations.test.ts
packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.js
packages/docusaurus-theme-classic/src/theme/Footer/index.tsx
packages/docusaurus-theme-classic/src/translations.ts
packages/docusaurus-theme-classic/src/validateThemeConfig.ts
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/useThemeConfig.ts
website/docs/api/themes/theme-configuration.md

Fixes #6101 
Yes.
I actually had some trouble verifying that the simple footer works, but the multi-column footer still seems to work when viewing `localhost:3000` without changing anything in `docusaurus.config.js`.
My trouble with simple footer was that I got the following error from `yarn start` when I changed the footer in `docusaurus.config.js` to only link items without titles:
```sh
A validation error occurred.
The validation system was added recently to Docusaurus as an attempt to avoid user configuration errors.
We may have made some mistakes.
If you think your configuration is valid and should keep working, please open a bug report.
ValidationError: "footer.links[0].label" is not allowed
```
It seems like this validation error is being thrown here: …

feat(theme-classic): new configuration syntax for a simple footer

---

packages/docusaurus-theme-classic/src/translations.ts
packages/docusaurus-theme-classic/src/validateThemeConfig.ts

Little bug in #6132 when footer contains no links. Surfaced because our blog-only test build has a footer without links.
Yes
Tested locally with `yarn workspace website build:blogOnly`

fix(theme-classic): fix translation when footer has no links

---

website/docs/api/plugin-methods/i18n-lifecycles.md
website/docs/api/plugins/plugin-content-blog.md
website/docs/api/plugins/plugin-content-docs.md
website/docs/api/plugins/plugin-content-pages.md
website/docs/api/themes/theme-configuration.md
website/docs/blog.mdx
website/docs/configuration.md
website/docs/docusaurus-core.md
website/docs/guides/creating-pages.md
website/docs/guides/docs/docs-multi-instance.mdx
website/docs/guides/docs/sidebar.md
website/docs/guides/docs/versioning.md
website/docs/i18n/i18n-crowdin.mdx
website/docs/i18n/i18n-introduction.md
website/docs/migration/migration-translated-sites.md
website/docs/seo.md

I chose square brackets as the choice for placeholders because:
- It's in line with the command line and webpack configuration conventions;
- It won't conflict with any other syntaxes (e.g. our interpolation syntax `{}`, JSX `<>`...) and looks natural enough
Yes

docs: normalize usage of placeholders

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/DocPaginator/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPaginator/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocPaginatorNavLink/index.tsx
yarn.lock

I'd like to stylize the DocPaginator so it looks like this:
The problem is that the arrows `»` are just inlined into the markup and cannot be hidden via CSS:
Not yet. 😊 
No plan so far, but I'd like to check with you if you agree that this change makes sense. I would refrain from swizzling currently, but I cannot.

feat(theme-classic): allow stylizing doc paginator arrows

---

packages/docusaurus-migrate/src/index.ts

fix(migrate): do not modify non-MD files

---

packages/docusaurus/src/server/__tests__/__fixtures__/configs/configAsync.config.js
packages/docusaurus/src/server/__tests__/__fixtures__/configs/createConfig.config.js
packages/docusaurus/src/server/__tests__/__fixtures__/configs/createConfigAsync.config.js
packages/docusaurus/src/server/__tests__/__snapshots__/config.test.ts.snap
packages/docusaurus/src/server/__tests__/config.test.ts
packages/docusaurus/src/server/config.ts
website/docs/api/docusaurus.config.js.md
website/docusaurus.config.js

Fixes https://github.com/facebook/docusaurus/issues/3791
We should be able to use async code to create the config.
Later: we'll try to also support ESM config + top-level await
Yes
tests + dogfood

feat(core): async docusaurus.config.js creator function

---

packages/docusaurus/package.json
packages/docusaurus/src/commands/start.ts
yarn.lock

Webpack just deprecated an option that we use `onBeforeSetupMiddleware ` and added a warning: https://github.com/webpack/webpack-dev-server/issues/4129
Fix https://github.com/facebook/docusaurus/issues/6167
yes
local, works without any warning

fix(core): update webpack-dev-server + fix deprecation warning

---

website/docs/guides/markdown-features/markdown-features-math-equations.mdx
website/docusaurus.config.js
website/package.json
yarn.lock

Bump `rehype-katex` to `v5` which does not seem to introduce any [breaking changes](https://github.com/remarkjs/remark-math/releases/tag/rehype-katex%405.0.0). `rehype-katex` requires `katex` `^0.13.0`, and latest of this series is `v0.13.24`, therefore also updated the corresponding stylesheet. Note that latest version of `rehype-katex` is `v6.0.2`, which is moved to [ESM](https://github.com/remarkjs/remark-math/releases/tag/rehype-katex%406.0.0) and might not play nice with other dependencies. 
Yes
Deploy preview: <https://deploy-preview-6172--docusaurus-2.netlify.app/docs/markdown-features/math-equations/>

chore: upgrade rehype-katex and katex stylesheet for website

---

website/docs/api/plugins/plugin-google-gtag.md

To make the gtag docs less confusing.
To quote the docs here: https://support.google.com/analytics/answer/9744165?hl=en-GB&utm_id=ad#use_existing_tags
> Make a note of your GA4 property's name so you can find it later. If your Universal Analytics property name is "Example property (UA-nnnnnnn)", your GA4 property name will be "Example property (xxxxxxx)", without a "UA-" prefix, and where xxxxxxx is a new property number. 
The docs as is suggest that gtag's should include "UA-" as universal analytics does.  This PR amends that to make it less confusing.
Yes
n/a

docs: remove mention of 'UA-' in gtag

---

generateExamples.js
packages/create-docusaurus/src/index.ts
packages/docusaurus/src/server/translations/translations.ts

Many people (unfortunately including me) configure their editors to add trailing new lines. Annoys me every time to fix translation files after running `write-translations`.
Yes

refactor: print trailing new line when outputting JSON

---

packages/docusaurus-mdx-loader/src/remark/transformImage/__tests__/index.test.ts
packages/docusaurus-mdx-loader/src/remark/transformLinks/__tests__/index.test.ts
packages/docusaurus-utils/src/escapePath.ts
packages/docusaurus-utils/src/posixPath.ts
packages/docusaurus-utils/src/webpackUtils.ts
packages/docusaurus/src/server/__tests__/__snapshots__/routes.test.ts.snap
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/routes.ts

Fix #6180. Also explained why `posixPath` doesn't transform non-ASCII paths.
Yes
This was not caught by our dogfooding cases because it only happens when the workspace root contains non-ASCII characters which the CI runner doesn't cover

fix(utils): properly escape Windows paths

---

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
website/src/theme/ReactLiveScope/components.tsx

The button is white throughout in dark mode because the text default color becomes white. Not nice.
Yes

docs: fix react live scope button color in dark mode

---

packages/docusaurus-plugin-ideal-image/package.json
packages/docusaurus-plugin-ideal-image/src/index.ts
packages/docusaurus-plugin-ideal-image/src/plugin-ideal-image.d.ts
website/docs/api/plugins/plugin-ideal-image.md
website/docusaurus.config.js

Added a new option `disableInDev` which defaults to `true` (previous behavior). Now you can test ideal image behavior in dev environment as well.
Yes
Turn the network preset in Chrome dev tools to "fast 3G". Now the placeholders show up and can be correctly loaded after clicking:
Turning off throttling and the images show up as usual.

feat(ideal-image): new option disableInDev

---

packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-blog/src/plugin-content-blog.d.ts
packages/docusaurus-plugin-content-blog/src/types.ts

In the spirit of plugin enhancement (#4492) we should allow users to declare additional server-side metadata through front matter. #4495 added the front matter to doc metadata; we should do the same for blog posts as well.
This has been requested on Discord.
Yes

feat(content-blog): include front matter in loaded content metadata

---

packages/docusaurus-utils/src/markdownLinks.ts
website/docs/docusaurus-core.md
website/docs/guides/markdown-features/markdown-features-code-blocks.mdx

There are also some hidden motivations:
- Metastring is not extensible if we decide to let users build their own magic comments (#5783)
- Metastring doesn't work if `MDXComponentProvider` is not wired (#6195). Well, highlighting comments don't work either, but they don't emit warnings.
I didn't change our own usage for dogfooding purposes. In the future, if we are to update those code blocks, we'll also convert them to highlighting with comments.
Yes

docs: recommend highlighting with comments than number range

---

website/docs/blog.mdx
website/docs/seo.md
website/docusaurus.config.js

See https://github.com/PrismJS/prism/issues/3283
Yes
Check out a page with markdown front matter in code blocks; they are now rendered properly.
| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/55398995/147530765-678f9ccc-8e61-4cb3-af45-10317d94ea7a.png) | ![image](https://user-images.githubusercontent.com/55398995/147530735-50c8b2fe-bde3-4dbf-b26f-0a00f0915054.png) |

docs: fix highlighting of YAML front matter

---

website/_dogfooding/_pages tests/code-block-tests.mdx
website/_dogfooding/_pages tests/index.md
website/_dogfooding/_pages tests/markdownPageTests.md
website/docs/guides/docs/docs-create-doc.mdx
website/docs/guides/markdown-features/markdown-features-admonitions.mdx
website/docs/guides/markdown-features/markdown-features-react.mdx
website/src/components/BrowserWindow/index.tsx

Make URL field default to `localhost:3000` so every window has a URL. Also did some other minor improvements.
Yes

docs: add default value for BrowserWindow URL field

---

website/docs/api/plugin-methods/extend-infrastructure.md
website/docs/api/plugin-methods/lifecycle-apis.md
website/docs/api/plugin-methods/static-methods.md
website/docs/api/themes/theme-live-codeblock.md
website/docs/blog.mdx
website/docs/browser-support.md
website/docs/deployment.mdx
website/docs/docusaurus-core.md
website/docs/guides/docs/versioning.md
website/docs/guides/markdown-features/markdown-features-assets.mdx
website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
website/docs/guides/markdown-features/markdown-features-plugins.mdx
website/docs/migration/migration-manual.md
website/docs/presets.md
website/docs/search.md
website/docs/styling-layout.md
website/docs/using-plugins.md
website/docs/using-themes.md

Remove a lot of highlight by metastring because we are already experiencing some shifts in the highlighted lines.
Yes

docs: normalize CodeBlock highlighting

---

packages/docusaurus-plugin-content-blog/src/blogUtils.ts

Fix #6241. Can't really test this because our CI is always UTC
Yes

fix(content-blog): always convert front matter date as UTC

---

packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.tsx

Remove a TODO. Actually the two should be identical because front matter is never applied default values / normalized (I think that rule would never be broken) and the client won't even be built if validation failed; but since we now have front matter in metadata, why not?
Yes

refactor(theme-classic): use front matter from metadata for BlogPostPage

---

packages/docusaurus-plugin-content-docs/src/categoryGeneratedIndex.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-docs/src/routes.ts
packages/docusaurus-plugin-content-docs/src/sidebars/types.ts
packages/docusaurus-plugin-content-docs/src/sidebars/validation.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/src/theme/DocCategoryGeneratedIndexPage/index.tsx
website/sidebars.js

feat(content-docs): allow SEO metadata for category index pages

---

website/docs/api/plugins/plugin-content-blog.md
website/docs/api/plugins/plugin-content-docs.md
website/docs/api/plugins/plugin-content-pages.md
website/docs/api/plugins/plugin-google-analytics.md
website/docs/api/plugins/plugin-google-gtag.md
website/docs/api/plugins/plugin-sitemap.md
website/src/remark/configTabs.js

Our build has been failing because once the config tabs are translated, the remark plugin fails to find relevant text. I made it more robust to translations, and even made the tab texts translatable.
Yes

fix(website): fix config-tabs breaking after translation

---

package.json
packages/docusaurus/src/commands/start.ts
yarn.lock

`@types/webpack-dev-server` is no longer needed, since WDS@>=4.7.0 provides types.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57808
maybe 🙂 
built locally
see motivation

refactor(core): use native types from webpack-dev-server

---

packages/docusaurus-plugin-google-analytics/src/index.ts
packages/docusaurus-plugin-google-gtag/src/index.ts
packages/docusaurus-preset-classic/src/index.ts
website/docusaurus.config.js

To prevent the legacy config from ever silently passing. Reported in https://github.com/facebook/docusaurus/pull/5832#issuecomment-1007122465.
Yes
Tested locally

fix(preset-classic): throw if preset finds GA options in theme config

---

.eslintrc.js
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/DocCategoryGeneratedIndexPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebarItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebarItems/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebarItems/styles.module.css
packages/docusaurus-theme-classic/src/theme/Heading/index.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DefaultNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocSidebarNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DropdownNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/NavbarNavLink.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/utils.ts
packages/docusaurus-theme-classic/src/theme/hooks/useDocs.ts

Theme components should only have a default export, it makes the `swizzle --wrap` possible
See also https://github.com/facebook/docusaurus/issues/5380#issuecomment-1006396888
same behavior as before, it should build and preview should look the same

refactor(theme-classic): apply import/no-named-export eslint rule

---

packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx

Even the _Skip to main content_ link on a page needs to be in a region per aXe.
Yes.
1. Visit a new Docusaurus site with the classic theme, such as today's https://typescript-eslint.io
2. Run aXe on it such as with the [aXe browser extensions](https://www.deque.com/axe/browser-extensions) and Settings > Enable Best Practices enabled
Fixes #6252

fix(theme-classic): add missing role=region to SkipToContent

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx

Fix #6309. #4986 is actually not very correct.
Yes

fix(theme-classic): fix mobile version dropdown label with only one version

---

packages/docusaurus-mdx-loader/src/index.ts
packages/docusaurus-mdx-loader/src/remark/transformImage/__tests__/__fixtures__/img.md
packages/docusaurus-mdx-loader/src/remark/transformImage/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-mdx-loader/src/remark/transformImage/__tests__/index.test.ts
packages/docusaurus-mdx-loader/src/remark/transformImage/index.ts
packages/docusaurus-mdx-loader/src/remark/transformLinks/index.ts
website/docs/guides/markdown-features/markdown-features-assets.mdx
website/src/css/custom.css

We need to pass the hash to the final output to support GH themed images. Also did some refactors to make the two remark plugins more aligned.
Apart from this, there's no significant behavior change.
Yes
Wrote docs; integration tests

feat(mdx-loader): preserve hash in image src; support GH themed images

---

website/docs/guides/markdown-features/markdown-features-math-equations.mdx
website/docs/guides/markdown-features/markdown-features-plugins.mdx
website/docusaurus.config.js
website/package.json
yarn.lock

Since Docusaurus now supports importing ESM modules dynamically, we can upgrade the `retype-katex` to the latest version. I have updated the related documentation and `docusaurus.confing.js` accordingly.
Yes.
Please see the deploy preview - <https://deploy-preview-6320--docusaurus-2.netlify.app/docs/markdown-features/math-equations/>

chore: upgrade rehype-katex with ESM support, update docs

---

website/docs/installation.md
website/src/components/UpgradeGuide/index.tsx
website/versioned_docs/version-2.0.0-beta.13/installation.md
website/versioned_docs/version-2.0.0-beta.14/installation.md

Less confusion.
Yes
Better test this in production, because we have different version configs in preview

docs: make upgrade guide always show the latest version

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus/src/client/exports/ErrorBoundary.tsx
website/_dogfooding/_pages tests/layout-no-children.tsx

Minor detail but something like `<Layout/>` should be allowed. 
Currently it crashes due to error boundary not allowing undefined children
see https://github.com/facebook/docusaurus/issues/6337#issuecomment-1012913647
yes
dogfood: https://deploy-preview-6338--docusaurus-2.netlify.app/tests/pages/layout-no-children

fix(core): error boundary should allow no children

---

website/docs/guides/markdown-features/markdown-features-math-equations.mdx

I guess this line (`return config;`) was left in the sample code by mistake while making modifications. The `createConfig` function is already returning the `config` as object.
Yes

docs: minor fix in the sample config for ESM

---

.github/dependabot.yml

As discussed in https://github.com/facebook/docusaurus/issues/3552
Maybe you want to go with Renovate Bot in the longer term, but at least this would get something going.
Kept updates to weekly to reduce some of the noise, but maybe you want to increase it to monthly and just use the manual trigger on the Insights tab to trigger manually
Yes
N/A

chore: add Dependabot for dependency updates

---

examples/classic-typescript/src/components/HomepageFeatures.tsx
packages/create-docusaurus/templates/classic-typescript/src/components/HomepageFeatures.tsx

This is already provided by the [classic template](https://github.com/facebook/docusaurus/blob/83e04132905dbef05b0553a700fcecec0235ba69/examples/classic/src/components/HomepageFeatures.js#L8) and in TypeScript template wasn't updated.
Based on the [documentation](https://docusaurus.io/docs/static-assets#examples) it is better to use `useBaseUrl` and I don't see the benefit of repeating the same function call in the `FeatureList` array.
Yes
Without this change it looks like this:
With the change applied the images load correctly:

fix(create-docusaurus): add useBaseUrl for image URLs

---

packages/docusaurus/src/webpack/utils.ts

Currently it logs `[object Object]`
Yes

fix(core): do not coerce webpack warning to string

---

packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/blog/2018-12-14-Happy-First-Birthday-Slash.md
packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/blog/complex-slug.md
packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/blog/date-matter.md
packages/docusaurus-plugin-content-blog/src/__tests__/__snapshots__/feed.test.ts.snap
packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/feed.ts

This allows people to build useful things, it seems. Good enough workaround if people don't want to enhance the content plugin.
@gouku FYI
Yes
Updated tests

feat(content-blog): include tags in feed

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-theme-classic/src/theme/LayoutHead/index.tsx
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/server/__tests__/i18n.test.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/server/i18n.ts

1. I'm in the middle of building [a website](https://interslavic.fun) for Interslavic language which is available in multiple locales and scripts. The problem is that Interslavic language has quite a long BCP-47 language tag: `art-x-interslv`.[^1]
Besides, since it supports equally the Latin and Cyrillic scripts, you ought[^2] to specify the script as well: `art-Latn-x-interslv` and `art-Cyrl-x-interslv` respectively. Also, the language has a for-internal-use script with extra etymological letters[^3], the so-called Etymological (or Scientific) alphabet, which we agreed to have under `art-Latn-x-interslv-etymolog`.
[^1]: See ConLang Code Registry: https://www.kreativekorp.com/clcr/
[^2]: See page 12: https://tools.ietf.org/search/bcp47
[^3]: …

feat(core, theme-classic): allow overriding htmlLang

---

packages/docusaurus/src/server/translations/__tests__/translationsExtractor.test.ts
packages/docusaurus/src/server/translations/translationsExtractor.ts

Allow importing with aliases (`translate as bar`) as well as escaping from translation extraction if no relevant import is present.
Also added more test cases.
Yes
All translation tests still pass

feat(core): check imported API name when extracting translations

---

packages/docusaurus-plugin-content-docs/src/client/__tests__/docsClientUtils.test.ts
packages/docusaurus-plugin-content-docs/src/client/docsClientUtils.ts

Fix #6434 
Yes
Added two tests

fix(content-docs): make getActivePlugin match plugin paths more exactly

---

package.json

This would fix the "no paths match..." error in lint-staged.
Yes

misc: fix stylelint erroring when lint-staged passed ignored file

---

packages/docusaurus-mdx-loader/src/index.ts
packages/docusaurus-mdx-loader/src/remark/transformImage/index.ts
packages/docusaurus-mdx-loader/src/remark/transformLinks/index.ts
website/docs/guides/markdown-features/markdown-features-plugins.mdx

Let's not pass it as options. Prerequisite of #4997. Also wrote some documentation.
Yes
Build succeeds.

refactor(mdx-loader): use vfile.path to access Markdown file path

---

website/src/theme/Toggle.tsx

An edge case where the colors have been hardcoded in the DOM but the other color mode doesn't exist yet (because right before merging #5822 we removed the effect that save both color modes during init). We should always use JS to manipulate styles provided JS is available—there isn't harm in doing so.
Yes

fix(website): update colors correctly when palette is only customized in one color mode

---

packages/docusaurus-theme-search-algolia/src/validateThemeConfig.ts
website/docs/search.md
website/docusaurus.config.js

- Default value change that might impact your site's search behavior, use `contextualSearch: false` to revert to previous behavior
Contextual Search has been widely used and makes sense for most sites
We can now safely turn this on by default (it has always been the long-term goal).
Fixes issues reported on versioned and i18n sites not enabling it. For example https://github.com/facebook/docusaurus/issues/5880
yes
dogfood

feat(search): enable contextual search by default

---

packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
packages/docusaurus-theme-common/src/utils/ThemeClassNames.ts

Currently styling the docs sidebar requires use of wildcard selectors to work with the generated id e.g:
```css
aside[class*='docSidebarContainer'] {
border-right: 1px dashed var(--ifm-toc-border-color);
}
```
Yes
Tested locally to ensure class applies. No linting errors introduced.
None/NA

feat(theme-classic): add stable class for DocSidebarContainer

---

.cspell.json
website/docs/guides/markdown-features/markdown-features-math-equations.mdx

See https://github.com/facebook/docusaurus/pull/6429#issuecomment-1021797291. I forgot to update the docs in that PR. Also tried to fix one spellcheck error.
Yes

docs: remove mention that CDN resources are cached cross-domain

---

website/src/components/TeamProfileCards/index.tsx
website/src/pages/versions.tsx

https://github.com/facebook/docusaurus/pull/6483 broke the versions page labels
https://docusaurus.io/versions
yes
preview

fix(website): bad translate tags without default translation

---

website/docs/guides/markdown-features/markdown-features-assets.mdx

There's a bit of confusion in #6403.
@slorber It's time for us to formalize the `pathname://` protocol. We have many, many users using it now. Probably #3309 can be closed as well?
The non-SPA redirect part of the `pathname://` usage will be documented in #6296.
Yes

docs: elaborate on Markdown asset linking; document pathname:// protocol

---

admin/new.docusaurus.io/functionUtils/playgroundUtils.ts
admin/publish.md

improves our release process:
- work around codesandbox syncing problem
- mention recover strategy for npm publish

chore: fix codesandbox example link + mention npm publish recovery

---

packages/docusaurus-utils/src/__tests__/markdownLinks.test.ts
packages/docusaurus-utils/src/markdownLinks.ts
website/docs/advanced/routing.md

Reported in https://github.com/facebook/docusaurus/pull/5782#issuecomment-1022808093. `@site` prefix _always_ indicates an asset.
Yes
Added a test case

fix(utils): do not resolve Markdown paths with @site prefix

---

website/docs/api/plugins/plugin-sitemap.md

So that users know where to locate their sitemaps
I didn't see the URL to the sitemap so I took a guess. For the other users who don't know where to locate the sitemap, this is handy.
Yes.
I did not made any code changes.

docs: mention where to find the sitemap

---

packages/docusaurus-theme-classic/src/index.ts
packages/docusaurus-theme-common/src/utils/colorModeUtils.tsx

Fix #6479.
We probably misunderstood the issue. The actual offending place is the media query listener. You can try with this minimal HTML:
```html
<body>
<script>
window.matchMedia('(prefers-color-scheme: dark)').addListener((e) => {
console.log('dark', e.matches);
console.log('print', window.matchMedia('print').matches);
});
</script>
</body>
```
When you press print, the PCS is coerced to light mode during printing, but then it was switched back to dark mode. This is because when printing, the browser wants the app to behave like it's in light mode. So the actual fix is to get rid of this fluctuation.
Problem is, which behavior do we actually prefer? Coercing the entire app to light mode when printing (and make the print result always look like light mode), or respect the current color …

fix(theme-classic): do not switch color modes when printing

---

packages/docusaurus/src/server/__tests__/__snapshots__/configValidation.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts

It is technically legal/valid and it works to provide a theme as an inline function instead of a module name
The validation was wrong, and will now accept such inline function
yes
tests

fix(core): configValidation should allow inline theme functions

---

packages/docusaurus-mdx-loader/package.json
packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-pages/package.json
packages/docusaurus-plugin-debug/package.json
packages/docusaurus-plugin-google-analytics/package.json
packages/docusaurus-plugin-google-gtag/package.json
packages/docusaurus-plugin-sitemap/package.json
packages/docusaurus-preset-classic/package.json
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-common/package.json
packages/docusaurus-theme-search-algolia/package.json
packages/docusaurus-utils-validation/package.json
packages/docusaurus-utils/package.json

Updating peerDependency fields to resolve all the warnings that the latest version of yarn outputs.
👍 
The following addition to my `.yarnrc.yml` file resolves all the warnings.
```yaml
packageExtensions:
"@docusaurus/mdx-loader@*":
peerDependencies:
"@babel/core": "*"
"@docusaurus/plugin-content-blog@*":
peerDependencies:
"@babel/core": "*"
"@docusaurus/plugin-content-docs@*":
peerDependencies:
"@babel/core": "*"
"@docusaurus/plugin-content-pages@*":
peerDependencies:
"@babel/core": "*"
"@docusaurus/plugin-debug@*":
peerDependencies:
"@babel/core": "*"
webpack: "*"
"@docusaurus/plugin-google-analytics@*":
peerDependencies:
"@babel/core": "*"
webpack: "*"
"@docusaurus/plugin-google-gtag@*":
peerDependencies:
"@babel/core": "*"
webpack: "*"
"@docusaurus/plugin-sitemap@*":
peerDependencies: …
```

fix: updating peerDependency fields for yarn berry

---

packages/docusaurus-theme-classic/src/theme/Footer/index.tsx

Fixes #6503 
Yes
I manually tested the `Footer` component using my local packages to ensure the `height` and `width` attributes were set on the logo image element with the following configuration:
```
footer: {
logo: {
alt: "Logo",
src: "img/logo.png",
height: 50,
width: 50,
}
}
```

fix(theme-classic): apply width/height for footer logos without href

---

.gitattributes
project-words.txt

As a final step of #5817, let's polish our language stats.
Yes

misc: configure linguist behavior to show better language stats

---

packages/docusaurus-theme-classic/src/theme/Footer/index.tsx

Fixes #6509 
Yes
Confirmed console error does not occur anymore

fix(theme-classic): add key prop for SimpleLinks map

---

.gitattributes
packages/docusaurus-migrate/src/index.ts
packages/docusaurus-plugin-content-docs/src/__tests__/cli.test.ts
packages/docusaurus-plugin-content-docs/src/cli.ts
packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars/index.ts
packages/docusaurus/src/commands/external.ts
packages/docusaurus/src/commands/swizzle.ts
packages/docusaurus/src/commands/writeHeadingIds.ts
packages/docusaurus/src/commands/writeTranslations.ts
packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/plugins/__tests__/init.test.ts
packages/docusaurus/src/server/plugins/init.ts
packages/docusaurus/src/server/presets/__tests__/index.test.ts
packages/docusaurus/src/server/presets/index.ts

Part of #6520. If we allow external modules (plugins, configs) to be ESM, they have to be imported asynchronously.
Yes

refactor: mark all functions that import external modules as async

---

.eslintrc.js
packages/docusaurus-theme-classic/src/theme/Tabs/__tests__/index.test.tsx

Suggested here: https://github.com/facebook/docusaurus/pull/6515#discussion_r797483773
It's turned off in the airbnb config: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/rules/react.js#L92-L95
Yes
Fixed another one, which is fortunately just a test

misc: enable jsx-key eslint rule

---

packages/docusaurus-plugin-content-docs/src/__tests__/lastUpdate.test.ts
packages/docusaurus-plugin-content-docs/src/lastUpdate.ts

This reapplies https://github.com/facebook/docusaurus/pull/5048, because it somehow got reverted during a refactoring (I believe).
To prevent it from happening again in future, I added a comment in the code.
This also:
- Expand `-1` into `--max-count=1` (long options are always preferred for better readability)
- Add `--` to prevent file names who looks like git options to clash
- Check if the file exists before issuing `git` and return a proper error message
- `git log` is known to return exit code 0 but no output in some cases, such as when using `--` and the file does not exist
- If preferred, I can instead check if stdout is empty rather than proactively checking the file

fix(content-docs): read last update from inner git repositories

---

website/docs/deployment.mdx
website/versioned_docs/version-2.0.0-beta.14/deployment.mdx

I've just automated the deployment of our implementation of docusaurus and stumbled upon some errors in the GH Actions files that were proposed in the website docs.
Yes 👍 
Only updated v. simple markdown, here are some screenshot previewing the markdown with a browser engine, unsure how to test deploy the website, but will try later tonight:
No related PRs found.

docs: improve Github Actions example jobs

---

packages/docusaurus-theme-classic/src/theme/LayoutHead/index.tsx
packages/docusaurus-theme-common/src/hooks/useKeyboardNavigation.ts
packages/docusaurus-theme-common/src/index.ts

Fix partially #6411. A better fix would be to use `:focus-visible` where available and only fall back to using JS when the former is not available, but can't be bothered now.
Yes
Turn off JS and use tabs to navigate the page. Compare the behavior to the prod website.

fix(theme-classic): make focused link outlined with JS disabled

---

packages/docusaurus-migrate/src/index.ts

refactor(migrate): change internal methods' parameter style

---

packages/docusaurus-theme-classic/src/theme/prism-include-languages.ts
website/_dogfooding/_pages tests/code-block-tests.mdx

Currently, the additional languages are only effective on the client side. It takes minimal effort to make it work in Node, though, as long as we use `globalThis`—the Prism components are nothing but IIFEs that expect a global called `Prism`. It will be properly shimmed in Webpack and the Node versions we support have this, so there won't be regressions.
Yes
https://deploy-preview-6612--docusaurus-2.netlify.app/tests/pages/code-block-tests/
(With Javascript disabled)
| Before | After |
|--------|-------|
| ![image](https://user-images.githubusercontent.com/55398995/152633712-9a180da2-341c-4ae9-8c77-a7dd2ee7b640.png) | ![image](https://user-images.githubusercontent.com/55398995/152633771-78c55910-bbb9-475f-ba2f-75ec32e632c7.png) |

fix(theme-classic): make Prism additional languages properly server-side rendered

---

packages/docusaurus-utils/src/__tests__/markdownLinks.test.ts
packages/docusaurus-utils/src/markdownLinks.ts

Fix #6616 
Yes
Added a test case

fix(utils): convert Markdown links in reference-style links with multiple spaces

---

packages/docusaurus-plugin-content-blog/src/plugin-content-blog.d.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-theme-classic/src/theme-classic.d.ts

Continuation of #6175. This fixes #6262 hopefully, and even if it doesn't, it's the best we can do. The theme aliases will be removed in the near future altogether, but for now, we will just put the components that the plugin directly references in the plugin typedef.
Yes

refactor: move module declarations for non-route components to theme-classic

---

packages/create-docusaurus/bin/index.js
packages/create-docusaurus/src/index.ts
website/docs/installation.md

As requested on Canny: https://docusaurus.canny.io/feature-requests/p/improve-template-cloning
This PR adds a customizable git clone strategy, allowing the user to use shallow, copy, or even bring in their own git clone options.
Yes
Tested locally

feat(create): allow specifying a git clone strategy

---

packages/docusaurus/src/commands/clear.ts

Currently, we only remove `node_modules/.cache`; however, if the user is using PnP, there's only the `.yarn` folder, and the cache folder is there.
In addition, the success message is now not shown if the folder doesn't exist at all, which should make the command less confusing.
Yes

fix(cli): make docusaurus clear also remove .yarn/.cache folder

---

packages/docusaurus-utils-validation/src/__tests__/__snapshots__/validationSchemas.test.ts.snap
packages/docusaurus-utils-validation/src/__tests__/validationSchemas.test.ts
packages/docusaurus-utils-validation/src/validationSchemas.ts
website/docs/using-plugins.md

example for id don't work with version 2.0.0-beta.15:
ValidationError: "id" with value "docs1" fails to match the required pattern: /^[a-zA-Z_-]+$/
Error: Process completed with exit code 1.
id given as example are wrong and break build
Sure why not
See example
None

feat: allow numbers in plugin ID

---

packages/docusaurus/src/client/exports/Link.tsx
website/_dogfooding/_pages tests/index.md
website/_dogfooding/_pages tests/link-tests.tsx

Make it possible to use `Link` component with 3rd party libraries that rely on forwarding `ref` when using it as the base:
```jsx
<Button component={Link} href="/me">Click me!</Button>
```
At the very least, it will be possible to call `ref.current.focus()` from under the parent component using `Link` as the base. This also eliminates console errors in the browser when using `Link` with 3rd party libraries as in the example above.
Yes

fix(core): forward ref to Link's anchor element

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-theme-common/src/utils/historyUtils.ts
packages/docusaurus-theme-common/src/utils/useLocationChange.ts
packages/docusaurus/src/client/PendingNavigation.tsx
packages/docusaurus/src/client/exports/router.ts
packages/docusaurus/src/client/normalizeLocation.ts

If you imported some undocumented member of `@docusaurus/router` (that's not one of `useLocation`, `useHistory`, `matchPath`, or `Redirect`), it is no longer be available. You need to import directly from `react-router-dom` instead.
1. This makes further refactors/upgrades less risky
2. We are going to do breaking changes with the React router v6 migration anyways, because the `useHistory` hook doens't exist: https://reactrouter.com/docs/en/v6/upgrading/v5#use-usenavigate-instead-of-usehistory
Yes

refactor: reduce exported members of docusaurus router

---

packages/create-docusaurus/templates/classic/src/css/custom.css
packages/create-docusaurus/templates/facebook/src/css/custom.css
packages/docusaurus-theme-classic/src/theme/DocCard/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css
packages/docusaurus-theme-classic/src/theme/ThemedImage/styles.module.css
website/docs/guides/markdown-features/markdown-features-assets.mdx
website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
website/docs/search.md
website/docs/styling-layout.md
website/src/components/BrowserWindow/styles.module.css
website/src/components/ColorGenerator/index.tsx
website/src/css/custom.css
website/src/pages/index.tsx
website/src/pages/showcase/_components/ShowcaseCard/styles.module.css
website/src/pages/styles.module.css
website/src/theme/Toggle.tsx
website/src/utils/colorUtils.ts

Selecting the scope without `html` means the user can locally apply alternative styles with a DOM attribute, without manually overriding the CSS. For example, our site's homepage banner can now be set to dark-mode only without duplicating CSS definitions.
Yes

refactor: recommend using data-theme without html element selector

---

packages/docusaurus-utils/src/__tests__/webpackUtils.test.ts
packages/docusaurus-utils/src/webpackUtils.ts

By default, SVGR removes the `<title>` tag from SVG inputs. This hinders a11y since "the `<title>` element provides an accessible, short-text description of any SVG container element or graphics element."
See: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title
The `<title>` tag can be set via the SVG React component's `title` prop, but it's unintuitive that existing `<title>` tags from the SVG files themselves get stripped beforehand.
This will not break behaviour for existing users since the `title` prop seems to override the image's default `<title>` tag if set according to the SVGR API docs:
> If titleProp is set to true and no title is provided (title={undefined}) at render time, this will fallback to an existing title element in the svg if exists.
See: …

fix(utils): make SVGO not remove title

---

packages/docusaurus-theme-search-algolia/src/index.ts
packages/docusaurus-theme-search-algolia/src/templates/opensearch.ts
packages/docusaurus-theme-search-algolia/src/theme-search-algolia.d.ts
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.tsx
packages/docusaurus-theme-search-algolia/src/validateThemeConfig.ts
website/docs/api/themes/theme-search-algolia.md
website/docs/search.md

As was rightly pointed out [earlier](https://github.com/facebook/docusaurus/pull/2756#issuecomment-1039456032), the search page from the Algolia theme should be disableable like as well as its default path should be changeable.
Yes
Try to set `false` value for `algolia.searchPage` to disable search page.

feat(search-algolia): allow disabling search page and configuring path

---

packages/docusaurus-theme-common/src/utils/useLocationChange.ts

Just noticed that we have the problem described in the issue again > https://github.com/facebook/docusaurus/issues/4794
This is still caused by the SkipContent component, but actually because the useLocationChange hook was triggered when it was not expected (changed doc -> hot reload -> re-render, but in fact the current location has not changed).
Yes
1. Start dev server
2. Go to any doc page and scroll it a bit
3. Edit any doc
4. The scroll position of the current doc page should same as before

fix(theme-common): do not run useLocationChange when hot reloading

---

website/docs/search.md

It is `algolia.searchParameters.facetFilters` and not `algolia.facetFilters`

docs(website): search doc typo searchParameters

---

website/docs/guides/docs/sidebar/items.md

Missing doc after https://github.com/facebook/docusaurus/pull/6239

docs: add doc for generated-index keyword/image metadata

---

packages/docusaurus/src/commands/serve.ts

Fix #6699. This should be more in line with almost every hosting provider.
Yes
Run `yarn serve` and go to http://localhost:3000/blog/2022. Before, it served
While now, it's the normal "page not found" page.

fix(cli): disable directory listing in serve

---

packages/docusaurus-mdx-loader/src/remark/utils/index.ts

Consider the heading ``#### [`guard-for-in`](https://eslint.org/docs/rules/guard-for-in)``. Right now, the inline code is dropped in the final ToC:
...because links aren't specially handled in the ToC, and everything in it gets simply formatted as plain string. However, it should be better formatted as `<code>method</code>`.
Yes

fix(mdx-loader): make headings containing links properly formatted in ToC

---

packages/docusaurus-plugin-content-docs/src/index.ts

fixes: #6718
create asstes for the frontmatter image in documentation (`plugin-content-docs`) aswell. The implementation is adapted from the [plugin-content-blog/src/index.ts#L477](https://github.com/facebook/docusaurus/blob/6996ed2f2ffe7a68a14f8b07d4674124163bbd7f/packages/docusaurus-plugin-content-blog/src/index.ts#L477)

fix(content-docs): create assets for frontmatter images

---

packages/docusaurus-module-type-aliases/package.json

Fix the last installation warning we have: `@docusaurus/module-type-aliases@npm:0.0.0-4615 doesn't provide react (peecbe), requested by react-helmet-async`
Yes

chore(module-type-aliases): add react as peer dependency

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/client/PendingNavigation.tsx
packages/docusaurus/src/client/client-lifecycles-dispatcher.ts

To make the diff of #6732 less confusing
Yes

refactor: improve client modules types

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus-utils-validation/src/index.ts
packages/docusaurus-utils-validation/src/validationUtils.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/webpack/utils.ts
website/docs/api/plugin-methods/lifecycle-apis.md
website/versioned_docs/version-2.0.0-beta.14/api/plugin-methods/lifecycle-apis.md
website/versioned_docs/version-2.0.0-beta.15/api/plugin-methods/lifecycle-apis.md

The webpack loaders don't do anything, and no-one has complained so far, so let's remove them.
The validation system is quite stable now (although we did have a few mistakes, but those are inevitable), so we can remove that long hint message and the escape hatch (since it isn't documented anyways)
Yes

refactor: remove deprecated Webpack utils & validation escape hatch

---

packages/docusaurus-theme-classic/src/theme/Toggle/index.tsx
packages/docusaurus-theme-common/src/utils/colorModeUtils.tsx

This is quite handy, especially when you have several tabs open from the same docs site. 
Also fixes #6733.
Yes
1. Open two tabs in the browser
2. On one of them switch the color theme
3. Make sure that on the second one the color theme was also automatically changed

feat: sync color mode between browser tabs

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-theme-classic/src/theme/DocBreadcrumbs/index.tsx
packages/docusaurus-theme-common/package.json
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/__tests__/routesUtils.test.ts
packages/docusaurus-theme-common/src/utils/routesUtils.ts

See also https://github.com/facebook/docusaurus/pull/6517#issuecomment-1048709116
Breadcrumbs link to the home by default:
Sometimes a site does not have a homepage, so it's not possible to link by default to `/` from the breadcrumbs home icon (lead to broken links error).
In such cases we can simply remove the home item from breadcrumbs, until we find a better solution (see suggestions in https://github.com/facebook/docusaurus/pull/6517#issuecomment-1048709116)
yes
unit tests + local tests without home page or with docs/blog-only-home

fix(theme-classic): fix breadcrumb home link bug with new useHomePageRoute() hook

---

packages/docusaurus-theme-common/src/utils/useTOCHighlight.ts

This change (https://github.com/facebook/docusaurus/pull/6317) led to issues, for which we don't have a perfect solution yet.
Let's disable this temporarily so that next release does not have the bugs, we'll reapply it properly later.
See 
- initial PR: https://github.com/facebook/docusaurus/pull/6317
- issue: https://github.com/facebook/docusaurus/issues/6620
- fix attempt: https://github.com/facebook/docusaurus/pull/6666
yes
preview, basic revert

fix(theme-classic): temporarily disable toc heading autoscrolling

---

packages/docusaurus-migrate/src/__tests__/__snapshots__/migration.test.ts.snap
packages/docusaurus-migrate/src/__tests__/migration.test.ts

After #6755, the migration test uses an FS mock snapshot to validate the _content_ of the migrated site, not just that it succeeds. However, because of paralleling FS ops, these calls can resolve in a random order, creating random CI failures. Sorting the calls by the file path should mitigate the issue.
Yes
Before merging, the Jest tests will be re-attempted for three times.

test: sort migration test FS mock calls

---

packages/docusaurus-theme-common/src/utils/__tests__/pathUtils.test.ts
packages/docusaurus-theme-common/src/utils/pathUtils.ts
website/_dogfooding/_docs tests/tests/Case-Sentitive-Doc.md

Sometimes the user has a filename like `Capitalized.md` leading to a slug with some uppercase chars such as `/docs/Capitalized`
But this URL is often normalized to `/docs/capitalized` by CDN/hosts and then when we try to match the 2 paths we consider they are different.
This leads to subtle UX issues such as:
- empty breadcrumb 
- bad navbar item highlighting
- bad sidebar category/items highlighting
The helper function `isSamePath` should be case-insensitive to fix it.
yes
tests + dogfood

fix(theme-common): isSamePath should be case-insensitive

---

website/docs/advanced/client.md
website/docs/api/docusaurus.config.js.md
website/docs/api/plugin-methods/lifecycle-apis.md

Since we are about to address #3399 in #6732, we can start by adding some basic docs. The lifecycles are not mentioned on purpose.
Yes

docs: add basic documentation about client modules

---

.github/workflows/tests-e2e.yml
admin/scripts/test-release.sh

After #6762, I think it's key that we also make sure the TypeScript template runs well. This could also help catch typing errors.
Yes
New test

test: add TypeScript template to E2E test matrix

---

website/docs/deployment.mdx

This PR solves the issue https://github.com/facebook/docusaurus/issues/6775.

docs: make GitHub actions explanation aligned with the code

---

packages/docusaurus-mdx-loader/src/remark/transformImage/__tests__/index.test.ts
packages/docusaurus-mdx-loader/src/remark/transformImage/index.ts

Fix #6774. Yarn PnP patches FS and generates a virtual file handle, but they forgot to map it back to the actual file handle when calling `stat()`. This makes `image-size` unhappy. More information in https://github.com/yarnpkg/berry/pull/3889#issuecomment-1034469784.
In addition, I've downgraded the error to a warning, hoping it would be less intimidating for users.
Yes

fix(mdx-loader): suppress image reading warning in Yarn PnP; log warning instead of error

---

packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx

Noticed this problem on our website: 
The `<a>` tag inside `<code>` makes the latter be translated to `CodeBlock`. However, it's possible to make it stay as `<code>` since `<a>` is inline.
Yes
The `<code>` works well on https://docusaurus.io/docs/api/themes/configuration#navbar-dropdown.  http://localhost:3000/tests/pages/code-block-tests#code doesn't regress either.

fix(theme-classic): allow code tags containing inline elements to stay inline

---

.eslintrc.js
packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/authorsMapFiles/authors.json
packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/authorsMapFiles/authors.yml
packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/blog/authors.yml
packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/i18n/en/docusaurus-plugin-content-blog/authors.yml
packages/docusaurus-plugin-content-blog/src/__tests__/__snapshots__/feed.test.ts.snap
packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/authors.ts
packages/docusaurus-plugin-content-blog/src/feed.ts
packages/docusaurus-plugin-content-blog/src/plugin-content-blog.d.ts
packages/docusaurus-theme-classic/src/theme/BlogPostAuthor/index.tsx
website/_dogfooding/_blog tests/2021-09-13-dup-title.md
website/blog/authors.yml
website/docs/blog.mdx

Currently, the authors don't appear in the RSS feed because they lack `email`. We can simply allow `email` in the metadata.
Yes
Updated test case

feat: allow blog authors email

---

packages/docusaurus-theme-common/src/utils/__tests__/routesUtils.test.ts
packages/docusaurus-theme-common/src/utils/routesUtils.ts
website/docusaurus.config.js

fix bug reported here: https://github.com/facebook/docusaurus/pull/6749#issuecomment-1051471026
yes
unit tests

fix(theme-common): docs breadcrumbs not working with baseUrl

---

website/blog/2022-01-24-docusaurus-2021-recap/index.md
website/docs/deployment.mdx
website/src/data/users.tsx

I recently crawled my website for broken links and I found it quite useful. 
Out of curiosity I did the docusaurus website and found errors, so I have fixed them. 
Yes
I'd also like to say that the following websites in the showcase don't seem to work:
https://www.amphoradata.com
https://developer.axioms.io
https://www.ocpeasy.org
https://developers.getwisdom.io

docs: fix broken links

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/docs.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts

Noticed in #6700 that the current one is actually buggy due to the async operations. While the actual inconsistency is fixed in that PR, this one makes the snapshot contain more info for easier debugging.
Yes

test(content-docs): refactor navigation test snapshot

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/docs.test.ts.snap
packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/generator.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars/generator.ts

fix(content-docs): always sort autogenerated sidebar items by file/folder name by default

---

README.md

When I was starting with docusaurus I had issues with npm and yarn. Having a one click button to install will make it easier for beginners to start. Netlify does have a one click button feature too however I don't think it supports monorepos. 
Yes

docs: add deploy with vercel button to README

---

packages/docusaurus-theme-classic/src/theme/SearchMetadata/index.tsx

In https://github.com/facebook/docusaurus/pull/6707 we replaced docusaurus_x meta by Algolia meta (biasing toward Algolia)
Unfortunately the former metas were actually used by some third-party search plugins: https://github.com/cmfcmf/docusaurus-search-local/issues/99
To avoid annoying anyone for now I'm duplicating the metadata
In the future I'd like to avoid doing so (as it slightly increase page size uselessly), but we'll figure this later
yes
preview

fix(theme-classic): restore docusaurus search meta

---

packages/create-docusaurus/templates/shared/docs/tutorial-basics/create-a-document.md

Sample code block could not be copy/pasted as the tutorial mentions with the lines that appear to be from a diff tool.
Yes! this is so small, wasn't sure if it should be an issue or a PR
None
None that I could find

docs: make tutorial code block directly copyable

---

.github/workflows/build-perf.yml
CHANGELOG.md
website/package.json

Will attempt to fix changelog bug happening after each new release: https://github.com/facebook/docusaurus/pull/6829#issuecomment-1058302603
yes
ci

fix(website): changelog plugin leads to CI bugs on release

---

.github/workflows/tests-e2e.yml

3.2 is released; the canary is no longer necessary.
Yes
Build

misc(test): make E2E test use stable Yarn berry

---

packages/docusaurus-theme-translations/locales/zh-Hans/theme-common.json
packages/docusaurus-theme-translations/locales/zh-Hant/theme-common.json

Before: {count} 篇文件帶有標籤 篇帶有標籤「{tagName}」
After: {count} 篇文件帶有標籤「{tagName}」

fix: minor Chinese translation fixes

---

packages/docusaurus/src/commands/__tests__/writeHeadingIds.test.ts
packages/docusaurus/src/commands/writeHeadingIds.ts

Complete a TODO. This probably doesn't happen a lot, but better fix the edge cases
Yes
The test case is updated

fix(cli): write-heading-id should not generate colliding slugs when not overwriting

---

packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/external.ts
packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/server/themes/index.ts

This should always work:
```js
function plugin() {
return {
foo() { console.log("Bar"); }
configureWebpack() { this.foo(); }
};
}
```
Unfortunately, it doesn't work if `configureWebpack` is unbound from the plugin instance. We should always bind the lifecycle so plugin authors can write code in the most intuitive way.
Yes

fix(core): make plugin lifecycles consistently bound to the plugin instance

---

packages/docusaurus/src/commands/swizzle/tables.ts

Fix swizzle status description typo.
Yep
```bash
yarn test packages/docusaurus/src/commands/swizzle
```
- Follows #6243 - @Josh-Cena thanks for implementing this feature, love the new DX!

fix(core): fix swizzle legend typo

---

packages/create-docusaurus/bin/index.js

Fix https://github.com/facebook/docusaurus/issues/6843
Imports are hoisted in ESM environment. [Are ES6 module imports hoisted?](https://stackoverflow.com/questions/29329662/are-es6-module-imports-hoisted)
So before version checking, the interpreter reads index.js and fails when it's an unsupported node version.
Using ESM dynamic import, I changed the order.
Additionally, I just refactored the error handling code refers to https://github.com/facebook/docusaurus/commit/85e87b560ea8bc7255942039b0dc87a30486e121
- AS IS
node v12.22
```
$ npx create-docusaurus
file:///Users/user/Desktop/docusaurus/packages/create-docusaurus/lib/index.js:36
return PackageManagersList.find((packageManager) => process.env.npm_config_user_agent?.startsWith(packageManager));
^
SyntaxError: Unexpected token '.'
at …
```

fix(create): load entry file after node version checking

---

packages/docusaurus/src/server/themes/alias.ts

The comparison function provided for themes is not [consistent](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-array.prototype.sort). The resulting array order is implementation-dependent, which means it could break between Node releases (unlikely, though) or if somebody tried to run this code in a browser somehow :grimacing: 
Yes
The only way to test this is by _not_ using V8:
Before:
```
[
'@theme/Navbar',
'@theme/NavbarItem',
'@theme/NavbarItem/DefaultNavbarItem',
].sort((a, b) => a.includes(`${b}/`) ? -1 : 0)
```
Chrome: `['@theme/Navbar', '@theme/NavbarItem/DefaultNavbarItem', '@theme/NavbarItem']`
Firefox: `[ "@theme/Navbar", "@theme/NavbarItem", "@theme/NavbarItem/DefaultNavbarItem"]`
After:
```
[
'@theme/Navbar',
'@theme/NavbarItem', …
```

fix(core): ensure stable webpack theme aliases sorting

---

packages/docusaurus-migrate/src/__tests__/__snapshots__/migration.test.ts.snap
packages/docusaurus-migrate/src/__tests__/migration.test.ts
packages/docusaurus-migrate/src/index.ts
packages/docusaurus-plugin-client-redirects/src/__tests__/writeRedirectFiles.test.ts
packages/docusaurus-plugin-client-redirects/src/writeRedirectFiles.ts
packages/docusaurus-plugin-content-blog/src/feed.ts
packages/docusaurus-plugin-content-docs/src/__tests__/cli.test.ts
packages/docusaurus-plugin-content-docs/src/cli.ts
packages/docusaurus-theme-translations/update.js
packages/docusaurus-utils/src/__tests__/emitUtils.test.ts
packages/docusaurus-utils/src/__tests__/jsUtils.test.ts
packages/docusaurus-utils/src/emitUtils.ts
packages/docusaurus/src/commands/swizzle/actions.ts
packages/docusaurus/src/server/translations/__tests__/translationsExtractor.test.ts
packages/docusaurus/src/server/translations/translations.ts

`fs.outputFile` is a quicker way to write a file while ensuring the directory exists. https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/outputFile.md
Yes

refactor: prefer fs.outputFile to ensureDir + writeFile

---

packages/docusaurus-types/src/index.d.ts
website/docs/api/plugin-methods/lifecycle-apis.md

This was added in #6109, and although `Configuration.devServer` is already a thing, I figured that mentioning in documentation is worthwhile.
Yes

docs: mention configureWebpack devServer return value

---

packages/docusaurus-theme-classic/src/theme/DocSidebarItem/index.tsx
packages/docusaurus-theme-classic/src/theme/Footer/index.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/NavbarNavLink.tsx

I'm constantly frustrated by the inconsistent DOM between internal and external links, because that means if I want to apply CSS to the text, I have to target both `a` and `a > span`.
Yes
Should have no layout changes

refactor(theme-classic): consistently add span wrapper for layout links

---

packages/docusaurus-theme-search-algolia/package.json

This throws an error in pnp:
```
Module not found: Error: Can't resolve '@docusaurus/plugin-content-docs/client' in './.yarn/__virtual__/@docusaurus-theme-search-algolia-virtual-8b78fceaa5/0/cache/@docusaurus-theme-search-algolia-npm-2.0.0-beta.17-609067fadc-8a603d743a.zip/node_modules/@docusaurus/theme-search-algolia/lib/theme/SearchPage'
```
Yes
Sadly our E2E test doesn't cover the search function

fix(theme-algolia): declare content-docs as dependency

---

packages/docusaurus-plugin-content-docs/src/sidebars/index.ts

Noted on Discord:
```
[INFO] Starting the development server...
[ERROR] Loading of version failed for version current
[ERROR] ValidationError: {
"type": "doc",
"id" [1]: ""
}
```
We could have added a pointer to the sidebar file.
Yes

fix(content-docs): give context about sidebar loading failure

---

project-words.txt
website/docs/cli.md
website/docs/installation.md

* https://github.com/facebook/docusaurus/issues/6865#issuecomment-1062930085
Yes.
* https://github.com/facebook/docusaurus/issues/6865

docs(cli): add info about development on github codespaces

---

website/docs/advanced/client.md
website/docs/guides/markdown-features/markdown-features-assets.mdx
website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
website/docs/guides/markdown-features/markdown-features-head-metadata.mdx
website/docs/guides/markdown-features/markdown-features-inline-toc.mdx
website/docs/guides/markdown-features/markdown-features-math-equations.mdx
website/docs/guides/markdown-features/markdown-features-tabs.mdx
website/docs/guides/whats-next.md
website/docs/installation.md
website/docs/styling-layout.md
website/docusaurus.config.js

A lot of really minor improvements
Yes

docs: editorial fixes

---

packages/docusaurus-theme-classic/src/theme/BackToTopButton/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx
packages/docusaurus-theme-classic/src/theme/ColorModeToggle/index.tsx
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
packages/docusaurus-theme-classic/src/theme/Heading/index.tsx
packages/docusaurus-theme-classic/src/theme/Navbar/index.tsx
packages/docusaurus-theme-classic/src/theme/TOCCollapsible/index.tsx
packages/docusaurus-theme-classic/src/theme/Tag/index.tsx
packages/docusaurus-theme-common/src/components/Details/index.tsx

I think this is a good enough compromise between readability and type strictness. Using ternaries and conditionals doesn't look any more obscure than class dictionaries.
Yes

refactor(theme-classic): avoid using clsx class dict with CSS modules

---

packages/docusaurus-theme-classic/src/theme/DocSidebarItem/index.tsx

feat(theme-classic): set aria-expanded on expandable sidebar categories

---

packages/docusaurus-plugin-content-blog/src/__tests__/__snapshots__/blogUtils.test.ts.snap
packages/docusaurus-plugin-content-blog/src/__tests__/blogUtils.test.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts

fix(content-blog): remove double leading slash in blog-only paginated view

---

website/docs/guides/docs/docs-introduction.md

As a new user it was unclear whether setting `slug` would change the URL relative to the root directory or relative to the docs directory. The example I added should make that clear without needing to test out the functionality in a Docusaurus instance (which is what I had to do).
Yes.
I tested out the sample code in a Docusaurus instance.
None.

docs: clarify the usage of slug

---

packages/docusaurus-theme-classic/src/theme/DocBreadcrumbs/index.tsx
packages/docusaurus-theme-classic/src/theme/DocBreadcrumbs/styles.module.css

- turn a last breadcrumb item into a text (see https://usersnap.com/blog/breadcrumbs/ or https://martech.org/breadcrumb-links-good-user-experience-yes/)
> Don’t link current page in breadcrumb navigation
The last item in the breadcrumb trail (current user’s location) is optional — if you want to display it, make sure that it’s not clickable or tappable. Since users are already on the page, it does not make any sense to add a link of the current page to the breadcrumb navigation.
- clean up CSS styles -- background for breadcrumb item is supposed to apply only to active state (hover or current item), now it looks weird, so I don't see the point in changing that default design.
Yes
Preview

refactor(theme-classic): little breadcrumbs improvements

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
packages/docusaurus-theme-classic/src/theme/Layout/index.tsx
packages/docusaurus-theme-classic/src/theme/LayoutProviders/index.tsx
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/metadataUtilsTemp.tsx
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/client/exports/ComponentCreator.tsx
packages/docusaurus/src/client/exports/useRouteContext.tsx
packages/docusaurus/src/client/routeContext.tsx
packages/docusaurus/src/server/plugins/index.ts
packages/docusaurus/src/webpack/__tests__/__snapshots__/base.test.ts.snap
project-words.txt

Add plugin name + plugin id + docs version + doc id to HTML classes, fixes https://github.com/facebook/docusaurus/issues/4280
Partial implementation for assigning a context to a route (https://github.com/facebook/docusaurus/issues/6885)
For now only plugins add basic data to this context, and it can be used through `useRouteContext()`. For now I keep this API undocumented until we have a full clean implementation. 
This partial implementation was necessary because there was no other easy way to assign pluginId/name to a given route apart from doing more annoying things like adding data to the generated route file.
Had to create a `HtmlClassNameProvider` wrapper because react-helmet does not "merge" classNames and deeply nested class override parent classes (see …

feat(core,theme): useRouteContext + HtmlClassNameProvider
