- packages/docusaurus-cssnano-preset/package.json
- packages/docusaurus/package.json
- yarn.lock
> chore(v2): bump cssnano packages

- website/docs/api/themes/theme-configuration.md
Improve API documentation
Yes
Minimal changes no need to deep tests
N/A
> docs(v2): fix missing closing bracket

- website/docs/guides/creating-pages.md
> docs(v2): fix grammar typo on Creating pages

- packages/docusaurus-theme-search-algolia/package.json
- packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js
- yarn.lock
Bump Algolia dep and little improvement layout for search bar.
Yes
Preview
> chore(v2): update @docsearch/react

- website/docs/migration/migration-overview.md
> docs(v2): grammar typo in migration-overview.md

- .github/ISSUE_TEMPLATE/config.yml
wrong link for the Discord chat :'(
> misc: issue template config typo

- website/sidebarsCommunity.js
By adding dogfood as proposed in https://github.com/facebook/docusaurus/pull/4682#issuecomment-827012579
Yes
Preview
> chore(v2): add external link to community sidebar

- website/docs/presets.md
Add introduction for Bootstrap present.
NA
> docs(v2): presets: fix typo in bootstrap preset

- packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.js
- packages/docusaurus-theme-search-algolia/src/theme/SearchPage/styles.module.css
- Use breadcrumbs from Infima
- Use more semantic markup
- Remove unnecessary styles and elements
Yes
Preview.
| ![image](https://user-images.githubusercontent.com/4408379/120997509-ef103680-c78f-11eb-8c73-09bf38d4b8e1.png) | ![image](https://user-images.githubusercontent.com/4408379/120997456-e0c21a80-c78f-11eb-9fa8-48be548209fd.png) |
> refactor(v2): improve markup and styling on search page

- packages/docusaurus-init/bin/index.js
- packages/docusaurus-migrate/bin/index.js
- packages/docusaurus/bin/docusaurus.js
- yarn.lock
Fix unstable lockfile after v1 cleanuup PR + upgrade deps
Had an ESLint issue (FB header in CLI with shebang: https://github.com/Stuk/eslint-plugin-header/issues/39). Disabled in 3 places, we'll see if we can re-enable this later
tests
> chore: lockfile cleanup

- website/src/data/users.js
We add i18n feature in Awe framework doc website
> docs(v2): update Awe framework site showcase

- packages/docusaurus-theme-classic/codeTranslations/ar.json
- packages/docusaurus-theme-classic/codeTranslations/base.json
- packages/docusaurus-theme-classic/codeTranslations/bn.json
- packages/docusaurus-theme-classic/codeTranslations/da.json
- packages/docusaurus-theme-classic/codeTranslations/de.json
- packages/docusaurus-theme-classic/codeTranslations/es.json
- packages/docusaurus-theme-classic/codeTranslations/fa.json
- packages/docusaurus-theme-classic/codeTranslations/fil.json
- packages/docusaurus-theme-classic/codeTranslations/fr.json
- packages/docusaurus-theme-classic/codeTranslations/he.json
- packages/docusaurus-theme-classic/codeTranslations/hi.json
- packages/docusaurus-theme-classic/codeTranslations/ja.json
- packages/docusaurus-theme-classic/codeTranslations/ko.json
- packages/docusaurus-theme-classic/codeTranslations/pl.json
- packages/docusaurus-theme-classic/codeTranslations/pt-BR.json
- packages/docusaurus-theme-classic/codeTranslations/pt-PT.json
- packages/docusaurus-theme-classic/codeTranslations/ru.json
- packages/docusaurus-theme-classic/codeTranslations/tr.json
- packages/docusaurus-theme-classic/codeTranslations/vi.json
- packages/docusaurus-theme-classic/codeTranslations/zh-Hans.json
- packages/docusaurus-theme-classic/codeTranslations/zh-Hant.json
- packages/docusaurus-theme-classic/src/theme/BlogListPage/index.tsx
- packages/docusaurus-theme-classic/src/theme/BlogPostPage/index.tsx
- packages/docusaurus-theme-classic/src/theme/BlogSidebar/index.tsx
- packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.tsx
- packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.tsx
Does the same thing as #4940, but for the blog sidebar.
Yes
Preview.
> refactor(v2): improve semantic blog sidebar markup

- packages/docusaurus-plugin-content-blog/src/__tests__/__snapshots__/generateBlogFeed.test.ts.snap
- packages/docusaurus-plugin-content-blog/src/__tests__/generateBlogFeed.test.ts
- packages/docusaurus-plugin-content-blog/src/blogUtils.ts
> fix(v2): respect base url in RSS feeds

- packages/docusaurus-theme-classic/src/theme/DocItem/styles.module.css
Refers to https://github.com/facebook/docusaurus/pull/4877#issuecomment-857736068
Also fixes #4946
Yes
Preview
> refactor(v2): remove extra padding from doc item container

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/proposal.md
- Replace old canny links: https://docusaurus-2.netlify.com/feedback/
- Github feature requests should be detailed and with a design proposal
- Canny features for basic ideas with no design proposal
- More attempts to protect maintainer's time in general 
yes
> misc: more issue template improvements

- packages/docusaurus-theme-classic/package.json
- packages/docusaurus-theme-classic/src/theme/AnnouncementBar/index.tsx
- packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css
- packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx
- packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
- packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
- packages/docusaurus-theme-classic/src/theme/Navbar/index.tsx
- packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx
- packages/docusaurus-theme-classic/src/theme/SkipToContent/styles.module.css
- website/src/components/showcase/ShowcaseCard/index.js
- website/src/pages/index.js
- yarn.lock
Resolves #3820 (in most cases this will be enough to fix this since we have truncated the navbar title and reduced spacing between navbar items).
Fixes #3937
Yes
Preview
> chore(v2): update Infima to alpha 26

- packages/docusaurus/src/commands/build.ts
Adding missing quotes. ;)
Yes.
No code changed.
None.
> fix(v2): add missing quote in build command output

- examples/bootstrap/blog/2019-05-29-hello-world.md
- examples/bootstrap/package.json
- examples/bootstrap/yarn.lock
- examples/classic/blog/2019-05-29-hello-world.md
- examples/classic/docs/tutorial-basics/create-a-document.md
- examples/classic/docusaurus.config.js
- examples/classic/package.json
- examples/classic/src/components/HomepageFeatures.js
- examples/classic/src/css/custom.css
- examples/classic/yarn.lock
- examples/facebook/blog/2019-05-29-hello-world.md
- examples/facebook/package.json
- examples/facebook/yarn.lock
> chore(v2): upgrade examples to beta.2

- website/docs/guides/docs/docs-introduction.md
> fix: correct typo

- packages/docusaurus-theme-classic/src/theme/Footer/index.tsx
At the moment we add the icon to external links in the navbar and doc sidebar, so it makes sense to add similar behavior to the footer links as well.
Yes
Preview
> feat(v2): add icon to external footer links

- packages/docusaurus/src/commands/swizzle.ts
> fix(v2): fix typos in swizzle command

- packages/docusaurus-types/src/index.d.ts
just a tiny lint error on master
> fix(v2): fix d.ts lint error

- packages/docusaurus-theme-classic/codeTranslations/fr.json
Docusaurus full in french !
Yes
Nope
Nope
> fix(v2): add missing french translations for mobile

- website/docs/deployment.mdx
Hard to understand without the indentation
Yes
> docs(v2): Indent code example to improve readability

- packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx
Fixes  #5180
Yes
See reproducible steps from  #5180
> fix(v2): pass all props to CodeBlock component

- website/docs/api/themes/theme-configuration.md
> docs: update API docs on navbar behavior

- packages/docusaurus-theme-search-algolia/package.json
- yarn.lock
Should fix layout shift on hydration.
https://github.com/algolia/docsearch/issues/1021
https://github.com/algolia/docsearch/pull/1033
yes
preview => https://deploy-preview-5214--docusaurus-2.netlify.app/
> fix: upgrade Docsearch to avoid layout shift

- packages/docusaurus-theme-classic/package.json
- website/src/pages/feedback/styles.module.css
- website/src/pages/styles.module.css
- yarn.lock
Just for fixing Iframe color-scheme
https://github.com/facebookincubator/infima/pull/158
https://github.com/facebook/docusaurus/pull/5223
yes
preview
> chore: Upgrade infima 29

- website/docusaurus.config.js
See https://github.com/facebook/docusaurus/issues/3526#issuecomment-888413518
cc @rafaelbmateus thanks :)
> chore: enable pt-BR i18n locale on staging

- website/community/2-resources.md
> docs: Fix typo `2-resources.md`

- packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
- packages/docusaurus-theme-classic/src/types.d.ts
- packages/docusaurus-types/src/index.d.ts
I am developing a TS plugin and `tsc` reports the following errors:
which are actually pretty minor errors yet weren't caught by the CI.
Yes
> fix: fix various TS errors

- packages/docusaurus-theme-classic/codeTranslations/fa.json
Improved default Farsi translations for the classic theme.
Yes
Run yarn run start:v2 and check that the page http://localhost:3000/ is rendered properly.
No
> refactor(v2): improved Farsi default translations

- packages/docusaurus-theme-search-algolia/src/index.js
- packages/docusaurus-theme-search-algolia/src/templates/opensearch.js
Should fix #5289
Yes
Remove `favicon` field from config file and try to build site.
> fix: make successful build if missing favicon

- website/community/4-canary.md
Doc commit missing from https://github.com/facebook/docusaurus/pull/5295
> docs: update canary doc

- website/community/5-changelog.md
Fix prod deployment stuck because of a relative import not working with i18n.
> fix: fix changelog page mdx import for i18n

- website/community/2-resources.md
Add link to mdx-mermaid package as suggested by @slorber [here](https://github.com/facebook/docusaurus/issues/1258#issuecomment-895909473)
Yes
N/A
Provides a solution to #1258
> docs(v2): add mdx-mermaid to resources

- packages/docusaurus-plugin-content-blog/src/index.ts
- packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
- packages/docusaurus-plugin-content-blog/src/types.ts
- website/docs/api/plugins/plugin-content-blog.md
- website/docs/blog.md
Resolve #5353.
Yes
Not sure how to dogfood it, but there's little reason it won't work anyways
> feat(plugin-blog): allow `'ALL'` as `postsPerPage` option value

- website/community/2-resources.md
Adding https://github.com/rohit-gohri/redocusaurus, an OpenAPI plugin I maintain, as a community plugin.
Yes
- https://github.com/facebook/docusaurus/issues/638#issuecomment-762502498
> docs: add Redocusaurus in community plugin list

- packages/docusaurus-theme-classic/package.json
- yarn.lock
Fix https://github.com/facebook/docusaurus/issues/5244
> fix: fix some theme UI issues (blockquotes, navbar-sidebar font) with Infima alpha.32

- website/docusaurus.config.js
> fix: website bad version name in docusaurus.config.js

- website/community/2-resources.md
Just adding `docusaurus-plugin-relative-paths` to the unofficial plugins list.
Yes.
Only md update.
No PR's are related. However, [here ](https://github.com/facebook/docusaurus/issues/3825#issuecomment-911665698) is the issue that started everything. 😅
> docs: Add docusaurus-plugin-relative-paths

- website/community/2-resources.md
Improved `docusaurus-plugin-relative-paths` description.
Yes.
No code changed, only .md files.
#5471
> docs: update docusaurus-plugin-relative-paths description

- .github/workflows/codeql-analysis.yml
> chore: set up CodeQL

- website/docs/typescript-support.md
It's just a small typo in the typescript-support section, but detracts from the readability of the docs.
Yes
> docs: minor grammatical correction

- website/docs/guides/creating-pages.md
As far as I could tell, the page you are told to edit is incorrect, so updated the parts to what I think is correct
> docs: fix code example

- README.md
This fixes a small grammatical error in the Readme.
Yes
n/a
n/a
> misc: fix ungrammatical sentence about 5-min tutorial

- CONTRIBUTING.md
- website/community/0-support.md
- website/community/3-contributing.md
- website/docs/introduction.md
After refactoring the Discord channels the references should be updated as well.
Yes
> docs(website): update all Discord links

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/proposal.md
Encourage people to self-service and highlight how contributions are handled.
Yes
> chore(issue templ): add "self service" section in templates

- website/docs/using-themes.md
Fix a typo
Yes
Not needed
None
> docs: fix a typo in using-themes.md

- website/docs/docusaurus-core.md
See the diff, the function in the example isn't returning anything
Partially
Not adjusted code/tests, I don't think the code examples in the documentation are tested, or else this fix wouldn't be needed ;-)
-
> docs: fix wrong code sample in docusaurus-core

- .eslintignore
- .eslintrc.js
- website/_dogfooding/_pages tests/error-boundary-tests.tsx
- website/_dogfooding/_pages tests/hydration-tests.tsx
- website/_dogfooding/clientModuleExample.ts
- website/_dogfooding/docs-tests-sidebars.js
- website/_dogfooding/dogfooding.config.js
- website/babel.config.js
- website/docusaurus.config.js
- website/package.json
- website/sidebars.js
- website/sidebarsCommunity.js
- website/src/components/BrowserWindow/index.tsx
- website/src/components/ColorGenerator/index.tsx
- website/src/components/ErrorBoundaryTestButton/index.tsx
- website/src/components/Playground/index.tsx
- website/src/components/TeamProfileCards/index.tsx
- website/src/components/showcase/ShowcaseCheckbox/index.tsx
- website/src/components/showcase/ShowcaseSelect/index.tsx
- website/src/data/users.tsx
- website/src/featureRequests/FeatureRequestsPage.tsx
- website/src/featureRequests/cannyScript.js
- website/src/pages/index.tsx
- website/src/pages/showcase/index.tsx
- website/src/pages/versions.tsx
- website/src/theme/ReactLiveScope/components.tsx
- website/src/types.d.ts
- website/src/utils/jsUtils.ts
- website/waitForCrowdin.js
Mostly to enforce headers; there are some other useful rules like `ref="noreferrer"` as well
Yes
> chore(website): enable eslint in website

- package.json
- website-1.x/blog/2021-11-05-algolia-migration.md
- website-1.x/siteConfig.js
- yarn.lock
Needed to unlock v1 site deployment
> fix: Docusaurus v1 site needs Crowdin npm upgrade

- packages/docusaurus-plugin-content-docs/src/__tests__/lastUpdate.test.ts
- packages/docusaurus-plugin-content-docs/src/lastUpdate.ts
Merged #5904 too quickly before Windows tests succeeded🌚
Yes
Wait for all the tests to pass!
> misc(plugin-docs): fix Windows test snapshot for git history retrieval

- website-1.x/blog/2021-11-05-algolia-migration.md
> docs: Docsearch blog post v1 fixes

- .github/CODEOWNERS
Let me be notified about code changes
Also made CODEOWNERS own all files so all PRs will have reviewers requested
Yes
> misc(codeowners): add @Josh-Cena to CODEOWNERS

- packages/docusaurus/src/webpack/__tests__/base.test.ts
- packages/docusaurus/src/webpack/base.ts
Missed this in #4095
Yes
N/A ¯\_(ツ)_/¯ Wonder how we should test this though
> fix(core): apply staticDirectories to base webpack config

- website/blog/2021-03-09-releasing-docusaurus-i18n.md
- website/docs/i18n/i18n-introduction.md
- website/docs/i18n/i18n-tutorial.md
- website/versioned_docs/version-2.0.0-beta.8/i18n/i18n-introduction.md
- website/versioned_docs/version-2.0.0-beta.8/i18n/i18n-tutorial.md
- website/versioned_docs/version-2.0.0-beta.9/i18n/i18n-introduction.md
- website/versioned_docs/version-2.0.0-beta.9/i18n/i18n-tutorial.md
A follow-up of #5849
Yes
Preview
> docs: update links to default translations dir

- website/docs/deployment.mdx
Close #2953.
Yes
Preview: https://deploy-preview-6026--docusaurus-2.netlify.app/docs/next/deployment/#choosing-a-hosting-provider
I think it may be a little longer than desired...
> docs(deployment): add cost-benefit analysis with different options

- packages/docusaurus-theme-translations/package.json
Fixes https://github.com/facebook/docusaurus/issues/6087
yes
next release
> fix(theme-translations): publish theme-translation lib, including typedef

- packages/docusaurus-plugin-google-analytics/package.json
- packages/docusaurus-plugin-google-gtag/package.json
- packages/docusaurus-plugin-pwa/package.json
- packages/docusaurus-remark-plugin-npm2yarn/package.json
- packages/docusaurus-theme-live-codeblock/package.json
- packages/docusaurus-theme-search-algolia/package.json
- packages/lqip-loader/package.json
Make the packages fully PnP compatible. Because the E2E tests don't use these package, the pnp test didn't fail. It was only caught when I was enabling PnP strict mode in my own site.
Yes
> fix: add missing dependencies on tslib

- packages/create-docusaurus/templates/classic/docusaurus.config.js
- packages/create-docusaurus/templates/facebook/docusaurus.config.js
> fix(create-docusaurus): make initial editUrl functional

- examples/README.md
- website/docs/styling-layout.md
- website/docs/using-themes.md
These docs have constantly confused me and other people. Time to make it more coherent as we try to also improve theming experience.
Yes
> docs: refactor styling/theming docs

- examples/classic-typescript/README.md
- examples/classic-typescript/docs/intro.md
- examples/classic-typescript/docusaurus.config.js
- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/README.md
- examples/classic/docs/intro.md
- examples/classic/docusaurus.config.js
- examples/classic/package.json
- examples/classic/yarn.lock
- examples/facebook/.eslintrc.js
- examples/facebook/README.md
- examples/facebook/docusaurus.config.js
- examples/facebook/package.json
- examples/facebook/yarn.lock
- generateExamples.js
chore(examples): update examples to 2.0.0-beta.14
> chore(examples): update examples to 2.0.0-beta.14

- website/docs/guides/markdown-features/markdown-features-admonitions.mdx
- website/versioned_docs/version-2.0.0-beta.14/guides/markdown-features/markdown-features-admonitions.mdx
> docs: fix import module name of theme/Admonition

- website/docs/deployment.mdx
> docs: add Layer0 to deployment guide

- packages/docusaurus/src/commands/deploy.ts
> fix(cli): quotify temp path in deploy command

- website/docs/static-assets.md
Demonstrated in #6208, our static asset resolution is still not clear enough.
Yes
> docs: elaborate on static asset resolution

- packages/docusaurus-theme-translations/update.js
Added:
- The ability to write a new base file if one doesn't exist (e.g. adding a new plugin translation as in #6173).
- Tally translation coverage.
Yes
> misc(theme-translations): multiple improvements to the update CLI

- website/docs/guides/markdown-features/markdown-features-admonitions.mdx
- website/docs/guides/markdown-features/markdown-features-assets.mdx
- website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
- website/docs/guides/markdown-features/markdown-features-inline-toc.mdx
- website/docs/guides/markdown-features/markdown-features-intro.mdx
- website/docs/guides/markdown-features/markdown-features-math-equations.mdx
- website/docs/guides/markdown-features/markdown-features-plugins.mdx
- website/docs/seo.md
- website/src/components/BrowserWindow/styles.module.css
> docs: use BrowserWindow for Markdown demos

- packages/docusaurus-theme-classic/src/theme-classic.d.ts
- packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
- packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts
- website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
- website/docs/guides/markdown-features/markdown-features-react.mdx
> feat(theme-classic): usable CodeBlock outside markdown

- packages/docusaurus-theme-translations/package.json
- packages/docusaurus-theme-translations/update.js
Now we don't need to do `-e require().run()` which looks inelegant
Yes
> refactor(theme-translations): improve typing for update script

- website/src/data/users.tsx
The project is no longer associated with a custom domain.
Yes.
@PatelN123 kindly informed us about the website appearing down at https://github.com/oxidizer-rs/website/issues/163, which is related to https://github.com/facebook/docusaurus/pull/6231.
> fix(docs): update oxidizer website url

- packages/docusaurus-plugin-sitemap/src/__tests__/createSitemap.test.ts
- packages/docusaurus-plugin-sitemap/src/__tests__/pluginOptionSchema.test.ts
- packages/docusaurus-plugin-sitemap/src/createSitemap.ts
- packages/docusaurus-plugin-sitemap/src/index.ts
- packages/docusaurus-plugin-sitemap/src/plugin-sitemap.d.ts
- packages/docusaurus-plugin-sitemap/src/pluginOptionSchema.ts
- website/docs/api/plugins/plugin-sitemap.md
Inspired by #6247. We probably won't properly solve that one until merging #5698, so this one doesn't add any new functionality.
Yes
Build
> feat(sitemap): remove trailingSlash option; respect noIndex config

- website/docs/typescript-support.md
Close #6262. This is actually because of bad type setup, but just removing this suffices to make typecheck pass.
Yes
Tested locally
> docs: make tsconfig work OOTB in typescript guide

- packages/docusaurus-migrate/src/__tests__/__fixtures__/expectedSiteConfig.js
- packages/docusaurus-migrate/src/index.ts
- packages/docusaurus-migrate/src/types.ts
- website/docs/migration/migration-manual.md
- website/versioned_docs/version-2.0.0-beta.14/migration/migration-manual.md
Reported in https://github.com/facebook/docusaurus/pull/5832#issuecomment-1006533756
Yes
Updated test case
> fix(migrate): migration CLI should correctly migrate gtag options

- packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
- packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
- packages/docusaurus-plugin-content-docs/src/__tests__/versions.test.ts
- packages/docusaurus-plugin-content-docs/src/index.ts
- packages/docusaurus-plugin-content-docs/src/versions.ts
Complete a TODO. Also helped me gain a better understanding of how doc versioning works (I like to refactor while reading code)
Yes
Modified tests
> refactor(content-docs): make readVersionsMetadata async

- website/docs/api/plugins/plugin-content-docs.md
- website/docs/guides/docs/versioning.md
- website/src/remark/configTabs.js
> docs: elaborate on doc versioning

- website/docs/installation.md
The documentation does not include about monorepos, this adds that and resolves #3463 
Yes
> docs: mention setup in monorepo

- website/docs/guides/markdown-features/markdown-features-react.mdx
- website/docs/guides/markdown-features/markdown-features-react.module.css
Had to explain this too many times. Since we aren't upgrading to MDX v2 for v2, it's time to put it down in the official docs.
Yes
> docs: document MD and JSX interoperability issues

- website/docs/guides/markdown-features/markdown-features-react.mdx
Translation failed. Let's see if it works this way
Yes
> fix(website): wrap details in mdx-code-block

- website/docs/api/plugin-methods/lifecycle-apis.md
- website/docs/api/themes/theme-configuration.md
Noticed this in #6317; also fixed another one
Yes
> fix(website): various anchor link fixes

- jest.config.mjs
- packages/docusaurus/package.json
- packages/docusaurus/src/client/exports/BrowserOnly.tsx
- packages/docusaurus/src/client/exports/__tests__/BrowserOnly.test.tsx
- website/docs/docusaurus-core.md
> feat(core): improve error message for BrowserOnly; better docs

- website/docs/guides/docs/sidebar.md
- website/versioned_docs/version-2.0.0-beta.14/guides/docs/sidebar.md
found unnecessary bracket in sidebar.md
yes
none
none
> docs: remove typo bracket

- .github/workflows/tests-e2e.yml
- .github/workflows/tests-windows.yml
This is already set as a default in the runners https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
Yes
N/A
> misc(ci): remove redundant "CI: true" env

- .github/workflows/lighthouse-report.yml
Believe there were some security related fixes in the Octokit library that was the reason for the major version bumps.
Current usage shouldn't be affected by the breaking changes https://github.com/actions/github-script#breaking-changes-in-v5
Yes
Will need to test after landing, since this action uses `pull_request_target`
> chore(ci): upgrade actions/github-script to v5

- website/src/components/ColorGenerator/index.tsx
Fixes #6343
The webpage [Styling and Layout | Docusaurus](https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima) crashes if we edit the input form "Primary Color" in the section "Styling your site with Infima".
Yes.
Edit the input form and assert that the page does not crash.
> fix(website): make ColorGenerator functional

- website/src/pages/showcase/_components/ShowcaseFilterToggle/index.tsx
- website/src/pages/showcase/index.tsx
- website/src/pages/showcase/styles.module.css
It's useful so I can directly show other people a particular site in the showcase; also a good replacement for <kbd>⌘</kbd> + <kbd>F</kbd>
Yes
> feat(website): search in showcase

- .github/workflows/lint.yml
- examples/facebook/.prettierrc
- package.json
- packages/create-docusaurus/templates/facebook/.prettierrc
- packages/create-docusaurus/templates/facebook/src/pages/index.js
- packages/docusaurus-plugin-debug/src/theme/DebugRoutes/styles.module.css
- packages/docusaurus-theme-classic/src/theme/Footer/styles.module.css
- website/_dogfooding/clientModuleCSS.css
- website/docs/guides/markdown-features/markdown-features-react.module.css
- website/docs/guides/markdown-features/markdown-features-tabs-styles.module.css
- website/src/css/custom.css
- website/src/pages/styles.module.css
- website/src/theme/Layout/styles.module.css
- website/versioned_docs/version-2.0.0-beta.14/guides/markdown-features/markdown-features-tabs-styles.module.css
- yarn.lock
- lint-staged to v12
- Update Prettier globs to run on all files so dropped extra scripts
- Add lint-staged hook for stylelint
Yes
N/A
> chore: upgrade lint-staged and globs

- .eslintrc.js
- examples/facebook/.eslintrc.js
- packages/create-docusaurus/templates/facebook/.eslintrc.js
This no longer appears to conflict with prettier
Yes
N/A
> chore: enable react/jsx-closing-bracket-location

- packages/docusaurus-mdx-loader/src/remark/transformImage/index.ts
- packages/docusaurus-mdx-loader/src/remark/transformLinks/index.ts
- packages/docusaurus-plugin-content-docs/src/sidebars/generator.ts
- packages/docusaurus-utils/src/__tests__/index.test.ts
- packages/docusaurus/src/server/moduleShorthand.ts
Remove a few eslint disables.
Yes
> refactor: use findAsyncSequential in a few places

- website/docs/styling-layout.md
I have answered several questions because the user doesn't know how to target CSS class names.
Yes
> docs: elaborate on different CSS class names

- packages/docusaurus-logger/src/__tests__/index.test.ts
- packages/docusaurus-logger/src/index.ts
- packages/docusaurus-utils/src/__tests__/index.test.ts
Still logging `[object Object]`... Need a better fix
Yes
TODO
> fix(logger): properly stringify objects for logging

- packages/docusaurus-theme-classic/src/index.ts
- packages/docusaurus-theme-classic/src/theme/prism-include-languages.ts
Make everything make more sense :)
Yes
No major code changes
> refactor(theme-classic): add comments to Prism setup; minor refactor

- packages/docusaurus-migrate/src/frontMatter.ts
- packages/docusaurus-module-type-aliases/src/index.d.ts
- packages/docusaurus-theme-classic/src/index.ts
- packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
- packages/docusaurus-theme-classic/src/theme/NavbarItem/index.tsx
- packages/docusaurus/src/commands/build.ts
- packages/docusaurus/src/server/__tests__/configValidation.test.ts
- packages/docusaurus/src/server/configValidation.ts
- packages/docusaurus/src/webpack/utils.ts
- website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
Some of the TODOs are no longer relevant, or quick fixes are readily available.
Yes
Tests
> refactor: clean up TODO comments

- website/static/_headers
Mentioned as one of the "issues" in the Lighthouse reports. These get unique names, so there shouldn't be a risk in a long cache life
> chore(website): set cache-control for static assets

- packages/docusaurus-plugin-content-pages/src/__tests__/__fixtures__/website/src/pages/hello/index.md
- packages/docusaurus-plugin-content-pages/src/__tests__/index.test.ts
- packages/docusaurus-plugin-content-pages/src/index.ts
- packages/docusaurus-plugin-content-pages/src/pageFrontMatter.ts
- packages/docusaurus-plugin-content-pages/src/plugin-content-pages.d.ts
- packages/docusaurus-plugin-content-pages/src/types.ts
- packages/docusaurus-theme-classic/src/theme/MDXPage/index.tsx
Complete a TODO.
Yes
Check test pages
> feat(content-pages): front matter validation, include front matter in metadata

- website/docs/search.md
> docs: update Algolia docs for new DocSearch infra

- website/docs/api/docusaurus.config.js.md
Document the functionality introduced by #6371. 
Yes.
CI checks should pass.
* #6371
> docs(i18n): amend PR #6371

- packages/docusaurus-plugin-content-pages/src/pageFrontMatter.ts
> fix(content-pages): declare hide_table_of_contents as boolean

- packages/docusaurus-plugin-content-blog/src/__tests__/blogUtils.test.ts
- packages/docusaurus-plugin-content-blog/src/blogUtils.ts
- website/_dogfooding/_blog tests/2021-08-22-no-author.md
- website/_dogfooding/_blog tests/demo/2020-08-03-second-blog-intro.md
- website/_dogfooding/dogfooding.config.js
- website/docs/blog.mdx
Fix #5554.
Yes
Unit test + dogfood
> feat(content-blog): parse date from middle of file path

- website/src/css/custom.css
git merge resulted in CSS in the wrong place in #5822 
Yes
Showcase page is working well again
> fix(website): restore some site CSS in light mode

- packages/docusaurus-plugin-content-blog/src/index.ts
- packages/docusaurus-plugin-content-blog/src/plugin-content-blog.d.ts
- packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
- website/docs/api/plugins/plugin-content-blog.md
It's not always useful to generate an archive, so we should allow opting out.
Yes
> feat(content-blog): allow disabling generating archive

- website/src/components/UpgradeGuide/index.tsx
minor issue preventing me from building the site with only 1 version and 1 language, useful for testing
> chore: fix yarn build:website:fast

- packages/docusaurus-theme-classic/src/theme/DocSidebarItem/index.tsx
> feat(theme-classic): add aria-current to sidebar category link

- website/docs/i18n/i18n-crowdin.mdx
- website/docs/i18n/i18n-git.md
- website/docs/i18n/i18n-introduction.md
- website/docs/i18n/i18n-tutorial.md
Tweaked a lot of confusing points from my memories of working on my own site's translations a year ago.
Yes
> docs: elaborate on i18n tutorial

- packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx
This was from a very legacy setup and doesn't really follow React best practices...
Yes
> refactor(theme-classic): render BlogPostItem as one JSX element

- .stylelintrc.js
- package.json
- packages/docusaurus-plugin-debug/src/theme/DebugLayout/styles.module.css
- packages/docusaurus-theme-classic/src/theme/BackToTopButton/styles.module.css
- packages/docusaurus-theme-classic/src/theme/BlogPostAuthors/styles.module.css
- packages/docusaurus-theme-classic/src/theme/BlogSidebar/styles.module.css
- packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
- packages/docusaurus-theme-classic/src/theme/DocCard/styles.module.css
- packages/docusaurus-theme-classic/src/theme/DocPage/styles.module.css
- packages/docusaurus-theme-classic/src/theme/DocSidebar/styles.module.css
- packages/docusaurus-theme-classic/src/theme/DocSidebarItem/styles.module.css
- packages/docusaurus-theme-classic/src/theme/DocSidebarItems/styles.module.css
- packages/docusaurus-theme-classic/src/theme/Heading/styles.css
- packages/docusaurus-theme-classic/src/theme/TOCCollapsible/styles.module.css
- packages/docusaurus-theme-classic/src/theme/Tag/styles.module.css
- packages/docusaurus-theme-classic/src/theme/Toggle/styles.module.css
- packages/docusaurus-theme-common/src/components/Details/styles.module.css
- packages/docusaurus-theme-live-codeblock/src/theme/Playground/styles.module.css
- packages/docusaurus-theme-search-algolia/src/theme/SearchPage/styles.module.css
- packages/docusaurus/src/client/nprogress.css
- website/docs/guides/markdown-features/markdown-features-tabs-styles.module.css
- website/src/components/APITable/styles.module.css
- website/src/components/BrowserWindow/styles.module.css
- website/src/css/custom.css
- website/src/pages/showcase/_components/ShowcaseFilterToggle/styles.module.css
- website/src/pages/showcase/_components/ShowcaseTagSelect/styles.module.css
- website/src/pages/showcase/styles.module.css
- website/src/pages/styles.module.css
- website/versioned_docs/version-2.0.0-beta.14/guides/markdown-features/markdown-features-tabs-styles.module.css
- yarn.lock
Continuation of #6372. Mostly just empty lines / color functions.
Yes
> chore: enable stylelint standard config

- website/docs/browser-support.md
- website/docs/guides/markdown-features/markdown-features-intro.mdx
- website/docs/guides/markdown-features/markdown-features-math-equations.mdx
- website/docs/guides/markdown-features/markdown-features-react.mdx
Address some confusions; also better formula formatting.
Yes
> docs: multiple doc improvements

- project-words.txt
- website/blog/2022-01-24-docusaurus-2021-recap/index.md
> chore: typo colocation -> collocation

- packages/create-docusaurus/.npmignore
- packages/create-docusaurus/src/index.ts
The cdpath is not consistent between the console output and the actual cd command.
Existing tests should handle the change. 
> fix(init): cd to correct path when installing

- packages/docusaurus-module-type-aliases/src/index.d.ts
> fix(module-type-aliases): fix type def for translate params

- packages/docusaurus-utils/src/__tests__/markdownLinks.test.ts
- packages/docusaurus-utils/src/markdownLinks.ts
> fix(utils): Markdown linkification match local paths beginning with http

- website/src/components/ColorGenerator/index.tsx
- website/src/components/Playground/index.tsx
- website/src/components/TeamProfileCards/index.tsx
- website/src/components/UpgradeGuide/index.tsx
- website/src/data/users.tsx
- website/src/pages/showcase/_components/ShowcaseCard/index.tsx
- website/src/pages/showcase/index.tsx
- website/src/pages/versions.tsx
Ensures all text in the website can be translated.
Yes
> docs: mark a lot of website texts as translatable

- website/docs/deployment.mdx
> docs: mention how env vars can be read

- packages/docusaurus-migrate/src/sanitizeMD.ts
- packages/docusaurus-migrate/src/transform.ts
- packages/docusaurus-theme-common/src/components/Details/index.tsx
We are now completely clear of ESLint warnings! 🎉
Yes
> refactor: fix all eslint warnings

- website/docs/deployment.mdx
- Cloudflare pages is a really good platform for static site deployment, I have added how to deploy a docusaurus website to cloudflare pages. 
- 
Yes.
> docs: add Cloudflare pages deployment guide

- packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
- packages/docusaurus-theme-common/src/utils/reactUtils.tsx
- packages/docusaurus-theme-search-algolia/src/deps.d.ts
- packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.tsx
- packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.tsx
- packages/docusaurus-types/src/index.d.ts
- packages/docusaurus-utils/src/urlUtils.ts
- packages/docusaurus/bin/beforeCli.js
- packages/docusaurus/bin/docusaurus.js
- packages/docusaurus/package.json
- packages/docusaurus/src/client/exports/ComponentCreator.tsx
- packages/docusaurus/src/commands/external.ts
- website/docs/cli.md
- yarn.lock
> refactor: improve internal typing

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Another attempt to make the contributing guideline more accessible.
Yes
> docs: clean up CONTRIBUTING

- packages/docusaurus-theme-classic/src/theme/DocSidebarItem/index.tsx
Should fix the issue https://github.com/facebookincubator/infima/issues/202 from Infima repo.
Closes https://github.com/facebookincubator/infima/issues/202
Yes
Preview
> fix(theme-classic): highlight active collapsible doc category properly

- .gitattributes
Last commit was still invalid and resulted in the fixtures being indexed. This one should be better
Yes
Tested locally with `github-linguist`
> misc: fix gitattributes for linguist configuration

- .gitattributes
Produced invalid syntax🤦‍♂️
Yes
> misc: fix git attributes syntax

- .cspell.json
- website/src/components/Tweet/index.tsx
- website/src/components/Tweet/styles.module.css
- website/src/data/tweets/index.tsx
- website/src/pages/index.tsx
- website/src/pages/styles.module.css
As part of revamping the homepage (#6386), we're add some testimonials.
Maybe we shouldn't be showing tweets from the core team? But I'm a user myself and I like it :S
Yes
> feat(website): add Tweets section

- packages/docusaurus-plugin-content-blog/src/index.ts
- packages/docusaurus-plugin-content-blog/src/plugin-content-blog.d.ts
- packages/docusaurus-plugin-content-blog/src/pluginOptionSchema.ts
- website/docs/api/plugins/plugin-content-blog.md
This component is still hardcoded in the code. Feels like a mistake.
Yes
> feat(content-blog): allow customizing blog archive component through option

- website/docs/deployment.mdx
> docs: fix bad anchor link syntax

- packages/create-docusaurus/templates/classic-typescript/package.json
- packages/create-docusaurus/templates/classic/package.json
- packages/create-docusaurus/templates/facebook/package.json
- packages/docusaurus-mdx-loader/package.json
- packages/docusaurus-plugin-client-redirects/package.json
- packages/docusaurus-plugin-content-blog/package.json
- packages/docusaurus-plugin-content-blog/src/index.ts
- packages/docusaurus-plugin-content-docs/package.json
- packages/docusaurus-plugin-content-pages/package.json
- packages/docusaurus-plugin-content-pages/src/index.ts
- packages/docusaurus-plugin-debug/package.json
- packages/docusaurus-plugin-google-analytics/package.json
- packages/docusaurus-plugin-google-gtag/package.json
- packages/docusaurus-plugin-ideal-image/src/index.ts
- packages/docusaurus-plugin-pwa/package.json
- packages/docusaurus-plugin-sitemap/package.json
- packages/docusaurus-preset-classic/package.json
- packages/docusaurus-theme-classic/package.json
- packages/docusaurus-theme-common/package.json
- packages/docusaurus-theme-search-algolia/package.json
- packages/docusaurus-utils-validation/package.json
- packages/docusaurus-utils/package.json
- packages/docusaurus-utils/src/deps.d.ts
- yarn.lock
Close #6613
Yes
Check the logs of Yarn PnP E2E test
> fix: remove more peer dependency warnings

- website/docs/guides/docs/docs-markdown-features.mdx
* Author meant to recommend the use of full paths rather than relative paths: Technical edit
* Revised intro to naturally introduce the benefits of this recommendation: Style edit
> docs: improve wording of using Markdown file paths

- packages/docusaurus-mdx-loader/src/remark/transformImage/__tests__/__snapshots__/index.test.ts.snap
- packages/docusaurus-mdx-loader/src/remark/transformLinks/__tests__/__snapshots__/index.test.ts.snap
- packages/docusaurus-utils/src/webpackUtils.ts
- packages/lqip-loader/README.md
This will:
1. Improve browser persistent caching
2. Possibly less build output changes across builds, allowing stuff to be cached
Yes
> refactor(utils): replace hash with contenthash for file loader

- packages/docusaurus-module-type-aliases/package.json
- packages/docusaurus-module-type-aliases/src/index.d.ts
- yarn.lock
Since we migrated to react-helmet-async, this is no longer necessary.
Yes
#6306
> refactor(module-aliases): remove react-helmet dependency

- website/src/pages/index.tsx
- website/src/pages/styles.module.css
Since the new YT video on the home page is currently breaking layout.
Yes
Preview (mobile)
> fix(website): make YT iframe responsive

- .cspell.json
- website/src/components/Tweet/index.tsx
- website/src/data/features.tsx
- website/src/data/quotes.tsx
- website/src/data/tweets.tsx
- website/src/pages/index.tsx
Part of #6386. This refactor should make further content editing easier.
Yes
DP
> refactor(website): extract homepage data from UI; feature text updates

- website/docs/blog.mdx
See https://github.com/facebook/docusaurus/issues/5692#issuecomment-1035726945
Yes
> docs: mention about blog date in front matter

- packages/docusaurus-plugin-pwa/package.json
Reported in https://github.com/facebook/docusaurus/issues/6613#issuecomment-1040349665
Yes
> fix(pwa): declare babel core as direct dependency

- website/docs/introduction.md
- website/src/css/custom.css
- website/src/pages/index.tsx
- website/src/pages/styles.module.css
Fix issue same as in #6667 was
Try browse preview site using smartphone
> docs(website): fix video responsiveness

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug.yml
With so many recent bug reports that are either unreproducible or simply user mistakes, I decided to emphasize more that the GitHub issue tracker is not a support forum. Also put even more emphasis on a reproduction.
Yes
> misc: improve bug report template

- packages/docusaurus-module-type-aliases/src/index.d.ts
- packages/docusaurus-plugin-ideal-image/src/plugin-ideal-image.d.ts
- packages/docusaurus-plugin-pwa/src/plugin-pwa.d.ts
- packages/docusaurus-plugin-pwa/src/theme/PwaReloadPopup/index.tsx
- packages/docusaurus-theme-classic/src/theme-classic.d.ts
- packages/docusaurus-theme-classic/src/theme/TOC/index.tsx
- packages/docusaurus-theme-classic/src/theme/TOCCollapsible/index.tsx
- packages/docusaurus-theme-classic/src/theme/TOCInline/index.tsx
- packages/docusaurus-theme-classic/src/theme/TOCItems/index.tsx
- packages/docusaurus/src/client/exports/Head.tsx
- packages/docusaurus/src/client/exports/Link.tsx
Deja vu... This may help with wrapping as well?
Yes
> refactor: declare all props as interfaces

- packages/docusaurus/src/commands/build.ts
- packages/docusaurus/src/server/__tests__/i18n.test.ts
- packages/docusaurus/src/server/i18n.ts
Noticed a few places that can be simplified.
Yes
> refactor(core): reduce code verbosity

- admin/scripts/test-release.sh
- packages/create-docusaurus/bin/index.js
- packages/create-docusaurus/src/index.ts
- website/docs/installation.md
> feat(create): new --package-manager option; interactive package manager selection

- packages/docusaurus/src/server/__tests__/testUtils.ts
- packages/docusaurus/src/webpack/__tests__/client.test.ts
- packages/docusaurus/src/webpack/__tests__/server.test.ts
Since we now exclude the `testUtils` from test, we can refactor the tests.
Yes
> refactor: move test utils into test folder

- website/src/data/users.tsx
We at Dyte finally got around to open-sourcing our documentation! 🎉
Yes
None
First added:
- https://github.com/facebook/docusaurus/pull/6274
> docs: mark dyte as opensource in showcase

- packages/docusaurus-theme-common/src/utils/__tests__/routesUtils.test.ts
- packages/docusaurus-theme-common/src/utils/routesUtils.ts
fix https://github.com/facebook/docusaurus/pull/6816#issuecomment-1057872695
yes
unit tests
> fix(theme-common): breadcrumbs home bug in docs-only

- packages/docusaurus-theme-common/src/index.ts
- packages/docusaurus-theme-common/src/utils/__tests__/docsUtils.test.tsx
- packages/docusaurus-theme-common/src/utils/announcementBarUtils.tsx
- packages/docusaurus-theme-common/src/utils/colorModeUtils.tsx
- packages/docusaurus-theme-common/src/utils/docSidebarItemsExpandedState.tsx
- packages/docusaurus-theme-common/src/utils/docsPreferredVersion/DocsPreferredVersionProvider.tsx
- packages/docusaurus-theme-common/src/utils/docsUtils.tsx
- packages/docusaurus-theme-common/src/utils/mobileSecondaryMenu.tsx
- packages/docusaurus-theme-common/src/utils/reactUtils.tsx
- packages/docusaurus-theme-common/src/utils/scrollUtils.tsx
- packages/docusaurus-theme-common/src/utils/tabGroupChoiceUtils.tsx
This slightly reduces the bundle size, in spirit of #6292. It also makes the behavior more aligned.
Yes
The error logs seem good:
> refactor(theme-common): unify missing context errors

- jest.config.mjs
- packages/docusaurus-plugin-ideal-image/src/index.ts
- packages/lqip-loader/src/__tests__/lqip.test.ts
- packages/lqip-loader/src/__tests__/utils.test.ts
- packages/lqip-loader/src/index.ts
> refactor(lqip-loader): split test files

- packages/create-docusaurus/package.json
- packages/create-docusaurus/tsconfig.build.json
- packages/create-docusaurus/tsconfig.json
- packages/docusaurus-migrate/bin/index.mjs
- packages/docusaurus-migrate/package.json
- packages/docusaurus-migrate/tsconfig.build.json
- packages/docusaurus-migrate/tsconfig.json
- packages/docusaurus/bin/docusaurus.mjs
- packages/docusaurus/package.json
- packages/docusaurus/tsconfig.json
- packages/docusaurus/tsconfig.server.json
Had enough with the red squiggly lines; here's an attempt to fix that.
Yes
> refactor: make JS executables included in the tsconfig for editor hints

- packages/docusaurus-plugin-pwa/src/index.ts
- packages/docusaurus-types/src/index.d.ts
- packages/docusaurus/src/client/preload.ts
- packages/docusaurus/src/webpack/utils.ts
Remove a lot of redundancy
Yes
> refactor: improve types

- website/src/data/users.tsx
Follow-up of https://github.com/facebook/docusaurus/pull/6862
Yes
> docs: mark clutch and gulp as open-source

- website/src/data/users.tsx
Update my repo `TRPG Engine`(https://trpgdoc.moonrailgun.com/) 's url
Yep
#6862
> docs: update TRPG Engine showcase

- packages/docusaurus/src/server/__tests__/__snapshots__/brokenLinks.test.ts.snap
- packages/docusaurus/src/server/__tests__/__snapshots__/duplicateRoutes.test.ts.snap
- packages/docusaurus/src/server/__tests__/brokenLinks.test.ts
- packages/docusaurus/src/server/__tests__/duplicateRoutes.test.ts
- packages/docusaurus/src/server/brokenLinks.ts
- packages/docusaurus/src/server/duplicateRoutes.ts
- packages/docusaurus/src/server/html-tags/index.ts
- packages/docusaurus/src/server/i18n.ts
- packages/docusaurus/src/server/plugins/__tests__/__fixtures__/site-with-plugin/docusaurus.config.js
- packages/docusaurus/src/server/plugins/__tests__/__fixtures__/site-with-plugin/preset.js
- packages/docusaurus/src/server/plugins/__tests__/init.test.ts
- packages/docusaurus/src/server/presets/index.ts
This makes three modules fully test-covered.
Yes
> test(core): improve test coverage

- .eslintrc.js
- jest/snapshotPathNormalizer.js
- package.json
- packages/docusaurus-migrate/src/frontMatter.ts
- packages/docusaurus-migrate/src/index.ts
- packages/docusaurus-plugin-content-docs/src/__tests__/cli.test.ts
- packages/docusaurus-plugin-content-docs/src/cli.ts
- packages/docusaurus-plugin-content-docs/src/numberPrefix.ts
- packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/generator.test.ts
- packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/index.test.ts
- packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts
- packages/docusaurus-utils-validation/src/validationSchemas.ts
- packages/docusaurus-utils/src/__tests__/jsUtils.test.ts
- packages/docusaurus-utils/src/__tests__/markdownParser.test.ts
- packages/docusaurus-utils/src/markdownLinks.ts
- packages/docusaurus-utils/src/markdownParser.ts
- packages/docusaurus-utils/src/urlUtils.ts
- packages/docusaurus/src/client/exports/Interpolate.tsx
- packages/docusaurus/src/commands/deploy.ts
- website/src/plugins/changelog/index.js
- website/src/remark/configTabs.mjs
- website/src/utils/colorUtils.ts
- yarn.lock
Significantly simplifies the regexes, without any behavior changes.
Yes
All unit tests
> refactor: install eslint-plugin-regexp

- packages/docusaurus-plugin-content-blog/src/__tests__/authors.test.ts
- packages/docusaurus-plugin-content-blog/src/authors.ts
Complete TODOs
Yes
Updated unit tests
> refactor(content-blog): improve error message of authors map validation

- jest.config.mjs
- jest/emptyModule.ts
- jest/snapshotPathNormalizer.ts
- website/src/data/__tests__/user.test.ts
Improve typings & TS coverage...
Yes
> refactor: convert Jest infrastructure to TS

- packages/docusaurus-plugin-client-redirects/src/__tests__/options.test.ts
- packages/docusaurus-plugin-client-redirects/src/createRedirectPageContent.ts
- packages/docusaurus-plugin-client-redirects/src/plugin-client-redirects.d.ts
- packages/docusaurus-plugin-client-redirects/src/types.ts
- packages/docusaurus-plugin-ideal-image/src/plugin-ideal-image.d.ts
- packages/docusaurus-plugin-ideal-image/src/theme/IdealImage/index.tsx
- packages/docusaurus-plugin-pwa/src/index.ts
- packages/docusaurus-plugin-pwa/src/plugin-pwa.d.ts
- packages/docusaurus-plugin-sitemap/src/index.ts
- packages/docusaurus-plugin-sitemap/src/plugin-sitemap.d.ts
- packages/docusaurus-plugin-sitemap/src/pluginOptionSchema.ts
> chore(pwa, sitemap, client-redirects, ideal-image): JSDoc for types

- packages/docusaurus-types/src/index.d.ts
- packages/docusaurus/src/server/brokenLinks.ts
- packages/docusaurus/src/server/routes.ts
Stronger types, cleaner comments/code.
Yes
> refactor(core): minor routes type improvement

- packages/docusaurus/src/client/exports/ComponentCreator.tsx
> fix: remove semicolon from HTML output

- packages/docusaurus-plugin-content-blog/src/index.ts
> fix(content-blog): only create archive route if there are blog posts

- packages/docusaurus-utils/src/__tests__/gitUtils.test.ts
- packages/docusaurus-utils/src/gitUtils.ts
https://github.com/facebook/docusaurus/pull/6949
Not the first time that Windows tests unexpectedly fail 🤦‍♂️
Yes
> test: fix Windows test for gitUtils

- packages/docusaurus-theme-classic/src/theme/DocSidebarItem/index.tsx
- packages/docusaurus-theme-classic/src/theme/Footer/LinkItem/index.tsx
- packages/docusaurus-theme-classic/src/theme/NavbarItem/NavbarNavLink.tsx
Applying changes from Infima - https://github.com/facebookincubator/infima/pull/214
Yes
Preview (`/tests` pages)
#6846
> refactor(theme-classic): remove span wrappers from layout links

- examples/classic-typescript/docs/tutorial-basics/create-a-document.md
- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/docs/tutorial-basics/create-a-document.md
- examples/classic/package.json
- examples/classic/yarn.lock
- examples/facebook/docs/tutorial-basics/create-a-document.md
- examples/facebook/package.json
- examples/facebook/yarn.lock
Follow-up of https://github.com/facebook/docusaurus/pull/7001, regen examples
> chore: regen examples for 2.0 beta.18

- packages/docusaurus-theme-classic/src/theme/BackToTopButton/index.tsx
- packages/docusaurus-theme-common/src/hooks/useBackToTopButton.ts
- packages/docusaurus-theme-common/src/hooks/useHideableNavbar.ts
- packages/docusaurus-theme-common/src/index.ts
- packages/docusaurus-theme-common/src/utils/scrollUtils.tsx
Extract common plumbing code and leave only theming code.
Yes
Still behaves the same
> refactor(theme): extract plumbing code of BTT button into theme-common

- packages/docusaurus-plugin-content-blog/src/feed.ts
- packages/docusaurus-plugin-content-docs/src/__tests__/cli.test.ts
- packages/docusaurus-plugin-content-docs/src/cli.ts
- packages/docusaurus-plugin-content-docs/src/sidebars/generator.ts
- packages/docusaurus-utils/src/dataFileUtils.ts
- packages/docusaurus/src/commands/serve.ts
- packages/docusaurus/src/server/translations/translations.ts
The actual error is found in the docs versioning CLI when an absolute path is used; fixed a few other places as well.
Yes
> refactor: fix a few places of path handling

- packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts
> fix(theme): only parse HTML- and JSX-style comments in MD code

- packages/docusaurus-module-type-aliases/src/index.d.ts
- packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
- packages/docusaurus-types/package.json
- packages/docusaurus-types/src/index.d.ts
> refactor: minor type improvements

- website/docs/guides/markdown-features/markdown-features-react.mdx
Reduce odds that React + TypeScript newbies like me file issues on your repo
:+1: 
None.
None.
> docs: add import React statement in JSX file example

- packages/docusaurus-module-type-aliases/src/index.d.ts
- packages/docusaurus-plugin-content-blog/src/index.ts
- packages/docusaurus-theme-common/src/utils/__tests__/routesUtils.test.ts
- packages/docusaurus-theme-common/src/utils/routesUtils.ts
- packages/docusaurus-types/src/index.d.ts
- packages/docusaurus-utils/src/__tests__/emitUtils.test.ts
- packages/docusaurus-utils/src/emitUtils.ts
- packages/docusaurus-utils/src/index.ts
- packages/docusaurus/src/client/docusaurus.ts
- packages/docusaurus/src/client/exports/ComponentCreator.tsx
- packages/docusaurus/src/client/flat.ts
- packages/docusaurus/src/server/__tests__/__snapshots__/routes.test.ts.snap
- packages/docusaurus/src/server/__tests__/routes.test.ts
- packages/docusaurus/src/server/plugins/index.ts
- packages/docusaurus/src/server/plugins/routeConfig.ts
- packages/docusaurus/src/server/routes.ts
- packages/docusaurus/src/webpack/__tests__/utils.test.ts
- packages/docusaurus/src/webpack/utils.ts
- website/docs/api/plugin-methods/lifecycle-apis.md
Refactored types, added lots of comments because this part is pretty confusing to everyone.
Yes
Test & build
> refactor(core): refactor routes generation logic

- website/community/2-resources.md
`docusaurus-plugin-typedoc` generates JSDoc comments to markdown files that are friendly with Docusaurus. This allows consumers to generate their API Documentation from their TypeScript source.
Yes
> docs: add docusaurus-plugin-typedoc to resources

- packages/docusaurus-theme-classic/src/theme-classic.d.ts
- packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx
- packages/docusaurus-theme-classic/src/theme/NavbarItem/DocSidebarNavbarItem.tsx
- packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx
- packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionNavbarItem.tsx
- packages/docusaurus-theme-classic/src/theme/NavbarItem/LocaleDropdownNavbarItem/index.tsx
- packages/docusaurus-theme-classic/src/theme/NavbarItem/utils.ts
- packages/docusaurus-theme-common/src/contexts/docsPreferredVersion.tsx
- packages/docusaurus-theme-common/src/index.ts
- packages/docusaurus-theme-common/src/utils/docsUtils.tsx
- packages/docusaurus-theme-common/src/utils/searchUtils.ts
In the spirit of hiding away plumbing code
> refactor(theme-classic): extract doc-related navbar items' logic to theme-common

- packages/docusaurus/src/client/exports/ComponentCreator.tsx
- packages/docusaurus/src/client/prefetch.ts
- packages/docusaurus/src/client/serverEntry.tsx
- packages/docusaurus/src/server/__tests__/__snapshots__/routes.test.ts.snap
- packages/docusaurus/src/server/plugins/index.ts
- packages/docusaurus/src/server/routes.ts
Added some explanation just so that we can replace it in the future...
Yes
> refactor(core): add comments for react-loadable logic

- packages/create-docusaurus/templates/classic/docusaurus.config.js
- packages/create-docusaurus/templates/classic/package.json
- packages/create-docusaurus/templates/facebook/docusaurus.config.js
- packages/docusaurus-types/package.json
Otherwise, the types aren't actually installed and we don't get autocomplete whatsoever.
Yes
> fix(create): install types for JS template as well

- website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
> docs: add a note about additional languages needing to be Prism component names

- packages/create-docusaurus/templates/classic/docusaurus.config.js
- packages/create-docusaurus/templates/facebook/docusaurus.config.js
This is the SINGLE MOST ASKED question on Discord. I feel like it should be more explicit.
Yes
> refactor(create): mention that the edit links can be removed

- website/docs/advanced/plugins.md
The file name inside the my-plugin folder is index.js .
> docs: correct plugin example filename

- website/docs/typescript-support.md
- website/docusaurus.config.js
- website/src/components/BrowserWindow/index.tsx
- website/src/components/BrowserWindow/styles.module.css
- website/src/components/Tweet/index.tsx
- website/src/components/Tweet/styles.module.css
- website/src/data/tweets.tsx
- website/src/pages/index.tsx
- website/src/pages/styles.module.css
- Fixes broken layout on mobiles related with BrowserWindow component
- Fix warning `The attributes width and height on <img> elements define the dimensions of the image in CSS pixels, and expect a non-negative integer`
- Adjust tweets card layout in according default card layout
- Fix logo sizing on landing page
Yes
Preview
> refactor(website): minor fixes and improvements

- website/src/data/__tests__/user.test.ts
- website/src/data/users.tsx
The showcase cards a bit misaligned, because some cards are too stretched due to the long description.
120 characters is roughly three lines, which should be enough for average descriptions.
Yes
> refactor(showcase): enforce descriptions with maximum length of 120 characters

- website/docs/advanced/routing.md
- website/docs/guides/creating-pages.md
- website/docs/guides/markdown-features/markdown-features-intro.mdx
- website/docs/using-plugins.md
After answering more questions on Discord, I've identified a few common misconceptions/ambiguities in our docs. Time to clean them up.
Yes
> docs: multiple documentation improvements

- .github/workflows/canary-release.yml
- .github/workflows/dependency-review.yml
Scan PR for potentially malicious deps upgrades
See https://github.blog/2022-04-06-prevent-introduction-known-vulnerabilities-into-your-code/
yes
ci
https://github.com/facebook/docusaurus/pull/6984
> misc: add CI actions/dependency-review-action for security

- .github/workflows/dependency-review.yml
cf CI error
https://github.com/facebook/docusaurus/actions/runs/2162580635
> chore: fix CI typo

- .github/workflows/build-blog-only.yml
- .github/workflows/build-perf.yml
- .github/workflows/canary-release.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-review.yml
- .github/workflows/lighthouse-report.yml
- .github/workflows/lint.yml
- .github/workflows/showcase-test.yml
- .github/workflows/tests-e2e.yml
- .github/workflows/tests-swizzle.yml
- .github/workflows/tests-windows.yml
- .github/workflows/tests.yml
Since we now have a long hash appended to each action, using the default name looks a bit too cumbersome. We should use a recognizable instead.
Yes
> misc: add a name to each GH action step

- packages/docusaurus-mdx-loader/src/deps.d.ts
- packages/docusaurus-plugin-content-blog/src/feed.ts
- packages/docusaurus-plugin-ideal-image/src/deps.d.ts
- packages/docusaurus-plugin-pwa/src/plugin-pwa.d.ts
- packages/docusaurus-theme-live-codeblock/src/types.d.ts
- packages/docusaurus/src/commands/build.ts
- packages/docusaurus/src/commands/deploy.ts
- packages/docusaurus/src/deps.d.ts
Turned off `skipLibCheck`, fixed some issues, then turned it back on.
It was easy to limit the scope of `skipLibCheck` so that most declaration files do get checked, but I decided to keep it on anyways, otherwise the performance is worse by 70%.
Yes
> fix: fix a few internal declaration semantic errors

- README.md
Seems it has been confusing for some folks (https://github.com/facebook/docusaurus/issues/7201). Let's keep it brief.
Yes
> docs: remove mention of "template" from README installation guide

- .github/workflows/codeql-analysis.yml
- .github/workflows/tests-e2e.yml
- .github/workflows/tests-windows.yml
- .github/workflows/tests.yml
Since Node 18 will be the next active LTS and Node 17 will soon be EOL, let's use 18 in tests.
Yes
> chore: replace node 17 with 18 in CI matrix

- packages/docusaurus-theme-translations/locales/cs/theme-search-algolia.json
Noticed in https://github.com/facebook/docusaurus/pull/7214#issuecomment-1104955246
This would currently log a warning because there are too many segments.
Yes
> fix(theme-translations): fix invalid pluralization in cs

- packages/docusaurus-theme-common/src/contexts/colorMode.tsx
> fix(theme-common): do not persist color mode for OS-triggered changes

- packages/create-docusaurus/templates/shared/docs/tutorial-basics/_category_.json
- packages/create-docusaurus/templates/shared/docs/tutorial-extras/_category_.json
IMHO this is great to add this for feature discoverability?
Looking for feedback on wording
yes
tested in examples
unfortunately, we don't have an easy way to test/start a template 😅 which might become a problem to solve
> refactor: use generated-index in init templates

- packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx
- packages/docusaurus-theme-common/src/index.ts
- packages/docusaurus-theme-common/src/utils/a11yUtils.ts
move useSkipToContent() technical code to theme-common
no change
> refactor: extract useSkipToContent()

- packages/docusaurus-theme-classic/src/theme-classic.d.ts
- packages/docusaurus-theme-classic/src/theme/TOCCollapsible/CollapseButton.module.css
- packages/docusaurus-theme-classic/src/theme/TOCCollapsible/CollapseButton.tsx
- packages/docusaurus-theme-classic/src/theme/TOCCollapsible/index.module.css
- packages/docusaurus-theme-classic/src/theme/TOCCollapsible/index.tsx
- packages/docusaurus-theme-classic/src/theme/TOCItems/Tree.tsx
- packages/docusaurus-theme-classic/src/theme/TOCItems/index.tsx
- Extract TOCItemTree
- Extract TOCCollapsible CollapseButton
- Better CSS split
preview exactly as before
> refactor(theme-classic): refactor TOC-related theme components

- website/versioned_docs/version-2.0.0-beta.19/guides/markdown-features/markdown-features-code-blocks.mdx
Follow-up on https://github.com/facebook/docusaurus/pull/7326
Fix versioned doc too
> chore: fix site deployment

- website/src/pages/showcase/index.tsx
> fix(website): restore showcase

- project-words.txt
- website/community/2-resources.md
Hello everyone 👋 
I created a plugin to connect Yandex Metrica to Docusaurus:
https://github.com/sgromkov/docusaurus-plugin-yandex-metrica
Yandex Metrica - it is a very popular in Russia web analytics tool. it's very similar to Google Analytics, and I was inspired by plugin-google-gtag while developing my own.
Typescript support will be in the next version of the plugin.
I am sure that many Russian Docusaurus users will find the plugin useful.
Deploy preview: https://deploy-preview-7340--docusaurus-2.netlify.app/community/resources
> docs: add Yandex Metrika plugin to community plugins

- website/docs/api/misc/create-docusaurus.md
- website/docs/api/misc/eslint-plugin/README.md
- website/docs/api/misc/logger.md
- website/docs/installation.md
Our create-docusaurus CLI is getting increasingly complex. Let's have a dedicated API documentation page for all options. This will also help us put less text in the installation guide, which is supposed to be brief.
Deploy preview: https://deploy-preview-7343--docusaurus-2.netlify.app/docs/api/misc/create-docusaurus/
> docs: add page for create-docusaurus API documentation

- website/community/Versions.tsx
Made a mistake in #7334: the last publish date could be a little more readable.
Deploy preview: https://deploy-preview-7367--docusaurus-2.netlify.app/community/canary/
> docs: display last canary publish date in human-readable format

- jest/snapshotPathNormalizer.ts
- packages/docusaurus-plugin-client-redirects/src/__tests__/writeRedirectFiles.test.ts
- packages/docusaurus-plugin-client-redirects/src/writeRedirectFiles.ts
- packages/docusaurus-plugin-content-blog/src/feed.ts
- packages/docusaurus-plugin-content-docs/src/cli.ts
- packages/docusaurus-plugin-sitemap/package.json
- packages/docusaurus-plugin-sitemap/src/index.ts
- packages/docusaurus/src/commands/swizzle/config.ts
- packages/docusaurus/src/webpack/__tests__/utils.test.ts
- packages/docusaurus/src/webpack/utils.ts
Enforce that every catch clause re-throws the error instead of wrapping it in a new error constructor. This way we can be safe even when the thing being caught is not an error, and also benefit from getting full stack traces.
> refactor: normalize error logging

- website/src/data/users.tsx
I have now changed the GeekyWeb's description (Showcase)
> docs: update GeekyWeb's showcase description

- website/docs/deployment.mdx
I've linked to the dev.to article (which is a timestamped stable version) - to be consistent with other deployment snippets.
The dev.to article references [this GitHub repo](https://github.com/fearlessly-dev/swa-demo-docusaurus) and  this[#30DaysOfSWA](https://www.azurestaticwebapps.dev/blog/build-with-docusaurus) site which was the inspiration for writing this article. The repo contains the code for the demo, and its README is the canonical source for the article, in case relevant.
> docs: add Azure as deployment option

- website/src/plugins/changelog/theme/ChangelogAuthors/styles.module.css
Infima variable changed; we need to update as well.
Deploy preview: https://deploy-preview-7431--docusaurus-2.netlify.app/changelog/
> fix(website): restore expand button style on changelog

- .gitattributes
Increases TypeScript coverage by 1.1%, and it probably shouldn't be in language stats anyways
> misc: add templates to github-linguist ignore list

- .gitattributes
- packages/docusaurus-plugin-pwa/src/sw.ts
- packages/docusaurus-plugin-pwa/tsconfig.json
- packages/docusaurus-plugin-pwa/tsconfig.worker.json
Now that we have project references, compiling a single file with a different environment becomes easier.
> refactor(pwa): migrate sw.js to TS

- packages/docusaurus-theme-translations/locales/zh-Hans/theme-common.json
- packages/docusaurus-theme-translations/locales/zh-Hant/theme-common.json
Noticed a missing translation.
> chore(theme-translations): complete zh translations

- website/docs/guides/markdown-features/markdown-features-react.mdx
- website/src/components/Highlight.tsx
- website/src/theme/MDXComponents.tsx
I have explained this many times on Discord. Worth making it into the documentation.
Deploy preview: https://deploy-preview-7503--docusaurus-2.netlify.app/docs/markdown-features/react/#mdx-component-scope
> docs: document MDXComponents scope

- website/src/data/tweets.tsx
> docs: update Kent C. Dodds Twitter avatar

- website/docs/advanced/ssg.md
- website/docs/api/docusaurus.config.js.md
- website/docs/blog.mdx
- website/docs/guides/docs/docs-create-doc.mdx
- website/docs/guides/docs/docs-introduction.md
- website/docs/guides/markdown-features/markdown-features-intro.mdx
Regular documentation improvement. Contains documentation requests from the past few weeks.
> docs: multiple documentation elaborations

- website/docs/blog.mdx
- website/docs/deployment.mdx
- website/docs/guides/markdown-features/markdown-features-admonitions.mdx
- website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
- website/docs/guides/markdown-features/markdown-features-react.mdx
- website/docs/swizzling.md
Crowdin still keeps messing up the MDX files when I'm trying to translate. I decided to fix it everywhere.
> docs: avoid using nested mdx-code-block

- website/docs/using-plugins.md
I just removed the parentheses (")")   😅 
Deploy preview: https://docusaurus.io/docs/using-plugins#installing-presets
> docs: remove extraneous bracket

- packages/docusaurus-theme-translations/locales/zh-Hans/theme-common.json
- packages/docusaurus-theme-translations/locales/zh-Hant/theme-common.json
Made a little mistake in #7556. I couldn't think of a word at that time and used the wrong one (oh well, it's supposed to be my mother tongue?😅).
> fix(theme-translations): improve zh translation

- packages/create-docusaurus/templates/shared/docs/tutorial-basics/create-a-page.md
- packages/docusaurus-remark-plugin-npm2yarn/README.md
- website/_dogfooding/_pages tests/markdownPageTests.md
- website/blog/2019-12-30-docusaurus-2019-recap.md
- website/blog/2021-01-19-docusaurus-2020-recap.md
- website/docs/advanced/routing.md
- website/docs/api/plugins/plugin-content-docs.md
- website/docs/api/plugins/plugin-pwa.md
- website/docs/api/themes/theme-configuration.md
- website/docs/blog.mdx
- website/docs/browser-support.md
- website/docs/deployment.mdx
- website/docs/guides/docs/docs-create-doc.mdx
- website/docs/guides/docs/docs-multi-instance.mdx
- website/docs/guides/docs/sidebar/index.md
- website/docs/guides/markdown-features/markdown-features-toc.mdx
- website/docs/migration/migration-manual.md
- website/docs/migration/migration-overview.md
- website/docs/migration/migration-translated-sites.md
- website/docs/migration/migration-versioned-sites.md
- website/docs/swizzling.md
- website/docs/using-plugins.md
A lot of subtle inconsistencies I caught when I was writing translations.
> docs: normalize capitalization

- website/src/data/users.tsx
> docs: mark Yeecord as opensource in showcase

- website/community/2-resources.md
As suggested by @Josh-Cena, I'd like to add a link to `awesome-docusaurus` on the community resources page.
The list adheres to the official standards of awesome lists.
The default deployment should show that the page works as expected.
> docs: add awesome-docusaurus resource

- packages/docusaurus/src/commands/deploy.ts
This allows users to maintain any specific git configuration settings that aren't global
I don't see any other tests for docusaurus commands like deploy. Please let me know if there's something I can do further to test this change.
> feat(deploy): copy local git config to tmp repo

- website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
> docs: swizzle react-live with eject

- packages/docusaurus-theme-classic/src/theme/Layout/styles.module.css
This fixes html and body tags height in Layout theme broken in the recent 2.0.0-beta.22 release
https://github.com/facebook/docusaurus/issues/7746
> fix(theme-classic):  fix Layout theme height CSS

- website/src/data/users.tsx
> docs: move Yeecord repo to organization

- packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.tsx
Replace condition canUseDOM to canUseIntersectionObserver as check is done for IntersectionObserver usage
Fix Observation EE check to a more accurate and grained variable usage.
Deploy preview: https://deploy-preview-7761--docusaurus-2.netlify.app/
Original issue : https://github.com/gama-platform/gama/issues/3457
Discord's discussion permalink : https://discord.com/channels/398180168688074762/867060369087922187/995895278643187742
> fix(algolia-search): test for canUseIntersectionObserver

- packages/docusaurus-theme-classic/src/theme/DocCategoryGeneratedIndexPage/index.tsx
> refactor(theme): fix duplicate page metadata usage

- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/package.json
- examples/classic/yarn.lock
- examples/facebook/package.json
- examples/facebook/yarn.lock
chore: regen v2.0.0-rc.1 examples
> chore: regen v2.0.0-rc.1 examples

- packages/docusaurus/bin/docusaurus.mjs
First try with this branch organization!
I added a little message, since in the future we'll have users on a variety of versions, and this will help with debugging. Node also has this feature.
> refactor(core): log Docusaurus & Node version before exiting

- website/netlify.toml
chore: add Netlify config for major version branch deploys (docusaurus-v2 branch)
> chore: add Netlify config for major version branch deploys (docusaurus-v2 branch)

- website/docs/deployment.mdx
There was a small typo in the deployment docs that kept the Powershell tab from rendering correctly.
> docs: fix typo in deployment

- website/src/data/users.tsx
> docs: update Bruce's Wiki website URL

- website/blog/2022-08-01-announcing-docusaurus-2.0/index.mdx
- website/docusaurus.config-blog-only.js
New post is using ideal image; need to include that in the test config.
> chore: fix blog-only test failures

- website/src/data/users.tsx
The link to the DocSearch website repository has changed.
> docs: update DocSearch showcase

- website/docs/i18n/i18n-crowdin.mdx
> docs: improve crowdin guide

- website/src/plugins/changelog/theme/ChangelogItem/Header/Authors/index.tsx
- website/src/plugins/changelog/theme/ChangelogItem/Header/index.tsx
The changelog authors display is wrong because it's importing the wrong component.
> chore: fix changelog plugin import path

- website/docs/guides/markdown-features/markdown-features-toc.mdx
> docs: add TOC heading level options to guide

- packages/create-docusaurus/templates/facebook/.eslintrc.js
- packages/create-docusaurus/templates/facebook/.stylelintrc.js
- packages/create-docusaurus/templates/facebook/babel.config.js
- packages/create-docusaurus/templates/facebook/docusaurus.config.js
- packages/create-docusaurus/templates/facebook/sidebars.js
- packages/create-docusaurus/templates/facebook/src/css/custom.css
- packages/create-docusaurus/templates/facebook/src/pages/index.js
- packages/create-docusaurus/templates/facebook/src/pages/styles.module.css
This reverts commit 9150c7aefc7bd871f449145bee5bc70767d09eca.
#7842 turned out to be the wrong thing to do. These copyright headers should only be for internal, not external. The current templates are fine.
N/A
> fix: revert "update FB template headers (#7842)"

- website/community/2-resources.md
- A CLI tool like [hexo](https://hexo.io/docs/writing.html)'s command: `hexo new [post name]`. Just try to make the writing experience with docusaurus more friendly. 
- A command line tool to let user create post file by a template quickly by the command like `yarn postgen new [template] [post_name]`
- https://github.com/moojing/docusaurus-post-generator
Deploy preview: https://deploy-preview-7955--docusaurus-2.netlify.app/
> docs: add docusaurus-post-generator to community resource list

- examples/classic-typescript/docs/tutorial-extras/translate-your-site.md
- packages/create-docusaurus/templates/shared/docs/tutorial-extras/translate-your-site.md
Corrected grammar
It didn't look good that such a nice tool has a grammar mistake in their preset 😅
Corrected grammar in translation docs page of classic-typescript preset.
Deploy preview: https://deploy-preview-7978--docusaurus-2.netlify.app/
None
> fix(create): bad grammar in template docs

- website/docs/swizzling.md
Just a small typo I found while reading the docs. It ain't much but it's honest work.
Netlify.
Deploy preview: https://deploy-preview-8025--docusaurus-2.netlify.app/
> docs: fix typo in swizzling.md

- .github/workflows/lighthouse-report.yml
Signed-off-by: sashashura <93376818+sashashura@users.noreply.github.com>
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an …
> chore(ci): GitHub Workflows security hardening

- website/src/data/users.tsx
Changed the company name starting with a lowercase letter.
> docs(showcase): fix daily.dev site name

- website/src/data/tweets.tsx
> docs: fix broken image

- website/versioned_docs/version-2.0.1/api/plugin-methods/lifecycle-apis.md
- website/versioned_docs/version-2.0.1/guides/markdown-features/markdown-features-react.mdx
- website/versioned_docs/version-2.0.1/guides/markdown-features/markdown-features-toc.mdx
- website/versioned_docs/version-2.0.1/i18n/i18n-crowdin.mdx
- website/versioned_docs/version-2.0.1/swizzling.md
- website/versioned_docs/version-2.0.1/typescript-support.md
- website/versioned_docs/version-2.1.0/api/plugin-methods/lifecycle-apis.md
- website/versioned_docs/version-2.1.0/guides/markdown-features/markdown-features-react.mdx
- website/versioned_docs/version-2.1.0/guides/markdown-features/markdown-features-toc.mdx
- website/versioned_docs/version-2.1.0/i18n/i18n-crowdin.mdx
- website/versioned_docs/version-2.1.0/swizzling.md
- website/versioned_docs/version-2.1.0/typescript-support.md
> docs: backport doc edits from future branch

- website/src/data/users.tsx
This is a simple string change for my name :)
> docs: fix Sunghyun Cho showcase info

- packages/docusaurus-logger/README.md
- website/docs/api/misc/logger/logger.md
- website/versioned_docs/version-2.0.1/api/misc/logger/logger.md
- website/versioned_docs/version-2.1.0/api/misc/logger/logger.md
website/docs/api/misc/logger/logger.md:32:45
Fixing typo
Manual test
Deploy preview: https://deploy-preview-8162--docusaurus-2.netlify.app/docs/api/misc/@docusaurus/logger/
> docs: fix typo

- website/community/2-resources.md
Removing docusaurus-plugin-relative-paths from resources since the plugin no longer exists.
> docs: removing community resource docusaurus-plugin-relative-paths

- CONTRIBUTING.md
- Removed redundant link from the Code of Conduct header
- Referenced the correct discord `#help-and-questions` channel link.
- Added note for important info.
- Fixed grammar
Improve the layout and content of the file.
Test plan not applicable for this PR. 😄
> docs: fix invalid link references & style the doc

- website/docs/api/plugins/plugin-pwa.md
- The sentence lacked a subject
- Changed the description of the problem slightly for clarity
> docs: fix incorrect grammar and improve clarity

- website/community/5-release-process.md
Removing extra hashtag
Preview
> docs: fix anchor link

- website/versioned_docs/version-2.0.1/api/plugins/plugin-google-gtag.md
- website/versioned_docs/version-2.1.0/api/plugins/plugin-google-gtag.md
- website/versioned_docs/version-2.2.0/api/plugins/plugin-google-gtag.md
Fixing up my mistaken committing of my gtag id to the Docusaurus repo. A follow on from https://github.com/facebook/docusaurus/pull/8313
Gosh my stats / SEO are such a mess now.
> docs: remove blog.johnnyreilly.com Google Analytics tag from docs part 2

- examples/classic-typescript/docusaurus.config.js
- examples/classic/docusaurus.config.js
- packages/create-docusaurus/templates/classic/docusaurus.config.js
> docs: fix typo 'internalization'

- website/docs/api/docusaurus.config.js.md
The handle is `customfields` at the moment, and a link in [deployment](https://docusaurus.io/docs/deployment#using-environment-variables) is broken because of this.
According to how other handles are made in the page `docusaurus-config` — like `staticDirectories` — camelCase seems to be the correct way
N/A
> docs: fix anchor link `#customFields`

- website/docs/guides/markdown-features/markdown-features-admonitions.mdx
Two code blocks were merged together because of errors with the three back ticks.
> docs: fix unclosed admonition code block

- CONTRIBUTING.md
> docs: point to where commit types are listed

- website/docs/i18n/i18n-introduction.md
Added direct link to the relevant section of `docusaurus.config.js`
> docs: add i18n guide doc should link to i18n core config doc

- website/docs/api/themes/theme-mermaid.md
Documentation for new theme introduced in 2.2.0.
> docs: document theme-mermaid in API sidebar

- website/docs/deployment.mdx
- website/versioned_docs/version-2.0.1/deployment.mdx
- website/versioned_docs/version-2.1.0/deployment.mdx
- website/versioned_docs/version-2.2.0/deployment.mdx
actions/checkout@v2 is deprecated because it depends on Node.js12, so it has been modified to v3.
> docs: changed actions/checkout version from 2 to 3

- packages/docusaurus-theme-translations/locales/vi/theme-common.json
Fix https://github.com/facebook/docusaurus/issues/8422
> fix(translations): typo in lastUpdatedAtBy Vietnamese translation

- website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
> docs: clarify additionalLanguages with custom language definitions.

- website/versioned_sidebars/version-2.2.0-sidebars.json
Adds the diagrams page to the sidebar for 2.2.0.
> docs: add diagrams page to 2.2.0 sidebar

- lerna.json
- package.json
- yarn.lock
- [na] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [na] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.
Bumps Lerna to latest v6 as a stepping stone for enabling Nx. Discussed with @yangshun and @slorber. See #8318
> chore: update lerna to v6.2.0

- website/docs/api/plugin-methods/lifecycle-apis.md
- website/versioned_docs/version-2.0.1/api/plugin-methods/lifecycle-apis.md
- website/versioned_docs/version-2.1.0/api/plugin-methods/lifecycle-apis.md
- website/versioned_docs/version-2.2.0/api/plugin-methods/lifecycle-apis.md
Tried to run docs example and found a failure in the basic implementation
N/A
N/A
N/A
> docs: fix example plugin implementation

- website/src/pages/index.tsx
> docs: fix front page video link label

- website/docs/guides/docs/docs-create-doc.mdx
- website/versioned_docs/version-2.0.1/guides/docs/docs-create-doc.mdx
- website/versioned_docs/version-2.1.0/guides/docs/docs-create-doc.mdx
- website/versioned_docs/version-2.2.0/guides/docs/docs-create-doc.mdx
> docs: fix link to docs only mode

- website/docs/using-plugins.md
> docs: `plugin-content-sitemap` -> `plugin-sitemap`

- website/netlify.toml
quick fix for blocked prod deployment
> fix(website): Netlify increase NODE_OPTIONS memory

- website/docs/api/plugin-methods/README.mdx
- website/docs/api/plugin-methods/static-methods.mdx
- website/versioned_docs/version-2.0.1/api/plugin-methods/README.mdx
- website/versioned_docs/version-2.0.1/api/plugin-methods/static-methods.mdx
- website/versioned_docs/version-2.1.0/api/plugin-methods/README.mdx
- website/versioned_docs/version-2.1.0/api/plugin-methods/static-methods.mdx
- website/versioned_docs/version-2.2.0/api/plugin-methods/README.mdx
- website/versioned_docs/version-2.2.0/api/plugin-methods/static-methods.mdx
Fix typos for example codes
- https://deploy-preview-8548--docusaurus-2.netlify.app/docs/api/plugin-methods/
- https://deploy-preview-8548--docusaurus-2.netlify.app/docs/api/plugin-methods/static-methods
N/A
> docs: fix typo 'validationOptions'

- website/docs/api/plugins/plugin-content-pages.mdx
Adds documentation for missing frontmatter property.
> docs: document plugin-content-pages wrapperClassName frontmatter.

- .github/dependabot.yml
Dependabot was not using the right label for security updates (https://github.com/facebook/docusaurus/pull/8610). This PR fixes it.
> misc: configure dependabot to use the right label

- packages/docusaurus-theme-common/src/utils/storageUtils.ts
Fix infinite loop reported in https://github.com/facebook/docusaurus/issues/8594
preview, use theme toggle and check no console error
Deploy preview: https://deploy-preview-8619--docusaurus-2.netlify.app/
Fix https://github.com/facebook/docusaurus/issues/8594
> fix(theme-common): localStorage utils dispatch too many storage events leading to infinite loop

- CONTRIBUTING.md
I found a very small error in the CONTRIBUTING.md file and fixed it
> docs: fix typo in CONTRIBUTING

- packages/docusaurus-plugin-ideal-image/README.md
It's just a simple PR to normalize the README of ideal-image plugin for consistency with other plugins.
https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-plugin-sitemap/README.md
> docs: normalize README for ideal-image plugin

- package.json
- packages/docusaurus-mdx-loader/package.json
- packages/docusaurus-mdx-loader/src/loader.ts
- packages/docusaurus-mdx-loader/src/remark/admonitions/index.ts
- packages/docusaurus-mdx-loader/src/remark/details/index.ts
- packages/docusaurus-mdx-loader/src/remark/head/index.ts
- packages/docusaurus-mdx-loader/src/remark/headings/index.ts
- packages/docusaurus-mdx-loader/src/remark/mdx1Compat/codeCompatPlugin.ts
- packages/docusaurus-mdx-loader/src/remark/mermaid/index.ts
- packages/docusaurus-mdx-loader/src/remark/toc/index.ts
- packages/docusaurus-mdx-loader/src/remark/transformImage/index.ts
- packages/docusaurus-mdx-loader/src/remark/transformLinks/index.ts
- packages/docusaurus-migrate/package.json
- packages/docusaurus-plugin-content-blog/src/remark/footnoteIDFixer.ts
- packages/docusaurus-remark-plugin-npm2yarn/src/index.ts
- yarn.lock
Correct invalid types exposed for mdx related plugins
additionally this PR aligns versions of `unified` used in project
https://github.com/facebook/docusaurus/pull/6567
https://github.com/facebook/docusaurus/pull/8288
> fix: correct MDXPlugin type 

- jest/vendor/unified@10.1.2.js
follow-up of https://github.com/facebook/docusaurus/pull/8515
goal: reduce diff of MDX 2 PR, making review easier: https://github.com/facebook/docusaurus/pull/8288
> chore: vendor MDX deps for Jest and the MDX 2 upgrade

- website/docusaurus.config.js
With MDX 2 (https://github.com/facebook/docusaurus/pull/8288) we will have even more async stuff in our config (math/katex plugins etc)
So I'd prefer to do this needed change right now.
It shouldn't change any behavior.
preview as before
Deploy preview: https://deploy-preview-8911--docusaurus-2.netlify.app/
> chore: migrate website config to createConfigAsync

- packages/docusaurus-theme-translations/locales/tr/theme-search-algolia.json
> fix(theme-translations): fix Turkish translation for aria label "Enter key"

- packages/docusaurus-plugin-ideal-image/README.md
- website/docs/api/plugins/plugin-ideal-image.mdx
Included information about changes to the types of imported support images
> docs(plugin-ideal-image): mention plugin changes type of imported images

- packages/docusaurus-theme-classic/src/theme/DocRoot/Layout/Sidebar/index.tsx
- packages/docusaurus-theme-common/src/components/Collapsible/index.tsx
- packages/docusaurus-theme-common/src/index.ts
- packages/docusaurus-theme-common/src/utils/accessibilityUtils.ts
Fix https://github.com/facebook/docusaurus/issues/8918
Preview with/without OS anims enabled
https://deploy-preview-8971--docusaurus-2.netlify.app/
> fix(theme): fix collapsible sidebar behavior when prefers-reduced-motion

- website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
Updated the link for default bundled languages
The link to the base set of bundled languages was broken. I got the new link from the [`prism-react-renderer` README page](https://github.com/FormidableLabs/prism-react-renderer#custom-language-support).
It's a permalink though, maybe we want to use the path instead (i.e.: https://github.com/FormidableLabs/prism-react-renderer/blob/master/packages/generate-prism-languages/index.ts#L9-L24)?
N/A
Old link: https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages
Deploy preview: https://deploy-preview-8975--docusaurus-2.netlify.app/docs/markdown-features/code-blocks/#supported-languages
https://github.com/facebook/docusaurus/pull/8976
> docs: update link in md code blocks section

- website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
I find this broken link while surfing docs and decided to correct it
I replaced the broken link with the one which is working I test the code by running it and verify by clicking on that link
Deploy preview: https://deploy-preview-8993--docusaurus-2.netlify.app/
> docs: fix broken link in code blocks docs

- website/docs/guides/markdown-features/markdown-features-plugins.mdx
I found that the link that should refer to the Rehype documentation was linking toward Remark. Therefore, I have modified the link to link toward Rehype.
1. Click the link
Deploy preview: https://deploy-preview-9018--docusaurus-2.netlify.app/docs/markdown-features/plugins#creating-new-rehyperemark-plugins
> docs: fix link to rehype

- examples/facebook/docusaurus.config.js
- packages/create-docusaurus/templates/facebook/docusaurus.config.js
- packages/docusaurus-theme-classic/src/__tests__/options.test.ts
- website/docusaurus.config.js
Data policy removed in Footer and wherever it used due to its wrongly redirecting to Privacy policy page
I've checked by seen the Footer, Now Data Policy removed from Footer and also wherever it's used
Deploy preview: https://deploy-preview-9024--docusaurus-2.netlify.app/
https://github.com/facebook/docusaurus/issues/9015
> docs: remove Meta Data Policy footer link on website

- website/docs/advanced/routing.mdx
I was reading the docs and caught a typo.
No tests required
Deploy preview: https://deploy-preview-9042--docusaurus-2.netlify.app/
> fix: typo in the sample site structure

- website/docs/swizzling.mdx
> docs: fix grammar typo in swizzling.mdx

- website/versioned_docs/version-2.0.1/api/themes/theme-configuration.mdx
- website/versioned_docs/version-2.0.1/guides/markdown-features/markdown-features-code-blocks.mdx
- website/versioned_docs/version-2.1.0/api/themes/theme-configuration.mdx
- website/versioned_docs/version-2.1.0/guides/markdown-features/markdown-features-code-blocks.mdx
- website/versioned_docs/version-2.2.0/api/themes/theme-configuration.mdx
- website/versioned_docs/version-2.2.0/guides/markdown-features/markdown-features-code-blocks.mdx
- website/versioned_docs/version-2.3.1/api/themes/theme-configuration.mdx
- website/versioned_docs/version-2.3.1/guides/markdown-features/markdown-features-code-blocks.mdx
- website/versioned_docs/version-2.4.1/api/themes/theme-configuration.mdx
- website/versioned_docs/version-2.4.1/guides/markdown-features/markdown-features-code-blocks.mdx
Found this broken link when go through code block docs
Replaced the broken link with the correct one
> docs: fix prism theme broken link in code blocks docs

- website/community/2-resources.mdx
Update the link and name of plugin `edno/docusaurus2-graphql-doc-generator` to `graphql-markdown/docusaurus` in the page [Awesome Resources](https://docusaurus.io/community/resources#features) .
The plugin (package) name and organization has been changed from `edno/docusaurus2-graphql-doc-generator` to `graphql-markdown/docusaurus`. This PR ensures that the page is up to date.
none
> docs: update info for community plugin docusaurus2-graphql-doc-generator

- project-words.txt
- website/community/2-resources.mdx
We have built a Docusaurus plugin to easily add LLM-powered search to a docs site, powered by [Markprompt](https://markprompt.com).
> docs: add @markprompt/docusaurus-theme-search

- website/src/data/users.tsx
The current link for the Homarr documentation source code is broken. Additionally, the webpage link is slightly outdated.
> docs: update outdated links in showcase

- CONTRIBUTING.md
The current opening sentence of the Contributing Guide could be clearer. Here's a comparison of the existing text and the proposed:
- **Existing:** Docusaurus is our way to hopefully help to create open source documentation easier.
- **Proposed:** Docusaurus is our way to hopefully help make open source documentation easier.
N/A (This is a doc update)
Deploy preview: https://deploy-preview-9177--docusaurus-2.netlify.app/
N/A
> docs: improve the opening sentence's clarity

- packages/docusaurus-theme-classic/src/theme/BlogLayout/index.tsx
- packages/docusaurus-theme-classic/src/theme/BlogPostItem/Container/index.tsx
fix https://github.com/facebook/docusaurus/issues/9181
> fix(theme): change schema.org itemType prop urls from http to https

- website/community/2-resources.mdx
This PR is to replace [mr-pdf](https://github.com/kohheepeace/mr-pdf) which is not maintained anymore for than a year by a fork up to date with the last dependencies & security fix and enriched with new features.
[docs-to-pdf](https://github.com/jean-humann/docs-to-pdf) Allow (as did mr-pdf) the users to generate PDF form docusaurus v1 or v2.
> docs(pdf): replace mr-pdf with maintained fork docs-to-pdf

- packages/docusaurus-theme-classic/src/getSwizzleConfig.ts
- [x ] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
> fix(theme): fix typo in swizzle component config

- packages/docusaurus-mdx-loader/src/processor.ts
- website/_dogfooding/_blog tests/2023-08-05.mdx
Fix https://github.com/facebook/docusaurus/issues/9194
Deploy preview: https://deploy-preview-9202--docusaurus-2.netlify.app/tests/blog/2023/08/05/
https://github.com/facebook/docusaurus/issues/9194
> fix(mdx-loader): ensure heading anchor slugs respect GitHub emoji behavior

- website/src/pages/showcase/_components/ShowcaseFilterToggle/index.tsx
Hii @Josh-Cena  I have added the clear all #9224  feature pls check and merge my pr.
fix #9224
> docs(website): Add a "clearAll" button to site showcase

- website/docs/installation.mdx
I was reading through this page and noticed a minor grammatical error. The semicolon between "instead of depending on a released version" and "your contributors can also conveniently update the docs as they implement features" is grammatically incorrect because the two clauses are not independent. This rewrites the sentence to be more clear without the grammatical error.
No code changed, so not tested on local device.
Current docs:
https://docusaurus.io/docs/installation#monorepos
Deploy preview: https://deploy-preview-9223--docusaurus-2.netlify.app/docs/installation/#monorepos
> docs: fix grammatical error, rewrite sentence to make clearer

- .github/workflows/argos.yml
This should give you a speed boost of 30-40 seconds.
> ci: only install Chromium for Playwright Argos tests

- packages/docusaurus-theme-translations/locales/zh-Hant/theme-common.json
> chore(theme-translations): complete zh-Hant translations

- packages/docusaurus-theme-translations/locales/ja/theme-common.json
The new admonition label "warning" hasn't been translated to Japanese yet.
#9308
> fix(theme-translations): add Japanese translation for "warning"

- website/docusaurus.config.js
Fix i18n staging deployment error, see https://github.com/facebook/docusaurus/issues/3526#issuecomment-1741778296
tested locally
> chore: fix i18n staging deployment error

- website/docs/search.mdx
- website/versioned_docs/version-3.0.0-beta.0/search.mdx
Link in v3 docs targets Docusaurus v2 algolia crawler template
> docs: fix algolia crowler config template link for v3

- website/docs/i18n/i18n-git.mdx
> docs: fix typos in website/docs/i18n/i18n-git.mdx

- .github/workflows/lighthouserc.json
Reporting is too verbose atm, so let's disable what I enabled in https://github.com/facebook/docusaurus/pull/9447
| URL | Performance | Accessibility | Best Practices | SEO | PWA | Report |
|---|---|---|---|---|---|---|
| [/](http://localhost:3000/) | 🟠 66 | 🟢 97 | 🟢 92 | 🟢 100 | 🟠 89 | [Report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1698228361860-4550.report.html) |
| [/](http://localhost:3000/) | 🟠 82 | 🟢 97 | 🟢 92 | 🟢 100 | 🟠 89 | [Report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1698228361860-4550.report.html) |
| [/](http://localhost:3000/) | 🟠 76 | 🟢 97 | 🟢 92 | 🟢 100 | 🟠 89 | [Report](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1698228361860-4550.report.html) |
| …
> chore: revert Lighthouse numberOfRuns due to bad/verbose reporting

- website/docusaurus.config.ts
> fix(website): Fix typo in announcement bar

- examples/classic-typescript/README.md
- examples/classic/README.md
- packages/create-docusaurus/templates/shared/README.md
readme shouldn't mention docusaurus v2
> fix(create-docusaurus): fix readme docusaurus 2 ref

- website/docs/migration/v3.mdx
This fixes incorrect package name for `remark-emoji` section where it says `prism-react-renderer` instead.
> docs: fix incorrect package name for remark-emoji in migration guide

- packages/docusaurus-plugin-pwa/package.json
- packages/docusaurus/package.json
- yarn.lock
Babel <v7.23.2 contains vulnerability `CVE-2023-45133` https://security.snyk.io/vuln/SNYK-JS-BABELTRAVERSE-5962462
Deploy preview: https://deploy-preview-9529--docusaurus-2.netlify.app/
> chore: ugrade babel dependencies to v7.23.3

- website/blog/releases/3.0/index.mdx
- website/docs/migration/v3.mdx
- website/versioned_docs/version-3.0.0/migration/v3.mdx
The missing comma in package.json is invalid json.
If you copy the example from the docs it will result in an error.
> docs: add missing comma

- README.md
- it closes an issue: https://github.com/facebook/docusaurus/issues/9465
- https://github.com/facebook/docusaurus/issues/9465
> chore: remove CI Score badge

- packages/create-docusaurus/templates/classic-typescript/package.json
- packages/create-docusaurus/templates/classic/package.json
- packages/docusaurus-theme-classic/package.json
- packages/docusaurus-theme-common/package.json
- website/_dogfooding/_pages tests/code-block-tests.mdx
- yarn.lock
fix https://github.com/facebook/docusaurus/issues/9517
Also upgrades the dependency for our own website and force users to upgrade as well
preview
https://deploy-preview-9567--docusaurus-2.netlify.app/tests/pages/code-block-tests#html---script--style-highlighting
> fix(theme): upgrade prism-react-renderer, fix html script and style tag highlighting

- README.md
In README.md file if you hover over "Docusaurus" there is a bug with an anchor tag which you can see here:
Here you can see how it should look like (fixed in PR):
> docs: Anchor Tag fixed in README.md Header

- website/community/2-resources.mdx
- N/A **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- N/A **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.
easyops-cn/docusarus-search-local has Docusaurus v3 support, so this updates the documentation to reflect that.
Source: https://github.com/easyops-cn/docusaurus-search-local#easyops-cndocusaurus-search-local
N/A
Deploy preview: https://deploy-preview-9583--docusaurus-2.netlify.app/community/resources#search
N/A
> docs: easyops-cn/docusarus-search-local v3 support

- website/docs/migration/v3.mdx
> docs: update guide to mdx v3 typo

- project-words.txt
- website/community/2-resources.mdx
Provide a search alternative to built-in Algolia search.
Deploy preview: https://deploy-preview-9594--docusaurus-2.netlify.app/community/resources/#search
Live preview: https://tauri.app/
meilisearch has [deprecated their official frontend repo](https://github.com/meilisearch/docs-searchbar.js/pull/801) and suggests [`meilisearch-docsearch`](https://github.com/tauri-apps/meilisearch-docsearch).
> docs: add meilisearch-docsearch to resources

- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/package.json
- examples/classic/yarn.lock
Examples for Docusaurus 3.0.1
- Release PR: https://github.com/facebook/docusaurus/pull/9596
- Docs PR: https://github.com/facebook/docusaurus/pull/9597
- Examples PR: https://github.com/facebook/docusaurus/pull/9599
- Blog post: N/A
- Release notes: https://github.com/facebook/docusaurus/releases/tag/v3.0.1
- Release discussion: https://github.com/facebook/docusaurus/discussions/9598
> chore: examples for Docusaurus 3.0.#

- website/docs/migration/v3.mdx
First, congrats on the release of Docusaurus 3 :partying_face: 
Because docusaurus.io itself uses `mdx1Compat.admonitions` equal to `true`, `:::note Your Title` is replaced by `:::note[Your Title]`, which renders the migration guide difficult to understand (both syntax looks identical):
Replacing the regular space that is between `:::note` and `Your Title` by a non-breaking space prevents this replacement:
N/A
Compare the original page: https://docusaurus.io/docs/migration/v3#admonitions-option
with the page fixed: https://deploy-preview-9574--docusaurus-2.netlify.app/docs/migration/v3/#admonitions-option
N/A
> docs: fix v2 admonitions syntax being replaced in migration guide

- website/docs/docusaurus-core.mdx
> docs: fix docusaurus-core.mdx typo on useGlobalData

- packages/docusaurus-plugin-pwa/package.json
- website/package.json
- yarn.lock
The `6.6.1` version Docusaurus depends on is deprecated: https://www.npmjs.com/package/workbox-build/v/6.6.1
v7 is just minimum node v16, and Docusaurus is already on minimum v18.
https://github.com/GoogleChrome/workbox/releases/tag/v7.0.0
(I'm _guessing_ that's the breaking change they accidentally released in `6.6.1`)
Not sure
> fix(pwa-plugin): upgrade workbox

- website/versioned_docs/version-3.0.1/migration/v3.mdx
In the 3.0.1 migration guide, under the `remark-emoji` section, it incorrectly references `prism-react-renderer`.
N/A
Deploy preview: https://deploy-preview-9677--docusaurus-2.netlify.app/
N/A
> docs: fix remark-emoji name in 3.0.1 migration guide

- README.md
- website/docusaurus.config.ts
Just some badges to say that it's covered by [Argos](https://argos-ci.com).
> docs: add Argos badge

- website/docs/cli.mdx
The CLI documentation has outdated CLI command options. This PR updates them.
Deploy preview: https://deploy-preview-9690--docusaurus-2.netlify.app/docs/cli
> docs: update CLI command options

- website/docs/migration/v3.mdx
There are some use cases where “warning” is too strong. This PR provides how to refactor `:::caution` with its title kept as is.
#9307
> docs: add guide to keep title of caution admonitions

- website/docs/api/plugins/plugin-content-docs.mdx
Fix doc to reflect new Docusaurus v3 apis
Supersed https://github.com/facebook/docusaurus/pull/9678
> docs: replace docLayoutComponent by new Docusaurus v3 options

- examples/classic-typescript/docs/tutorial-basics/markdown-features.mdx
- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/docs/tutorial-basics/markdown-features.mdx
- examples/classic/package.json
- examples/classic/yarn.lock
update examples for Docusaurus v3.1
- Blog post: https://docusaurus.io/blog/releases/3.1
- GitHub release PR: https://github.com/facebook/docusaurus/pull/9705
- GitHub release notes: https://github.com/facebook/docusaurus/releases/tag/v3.1.0
- GitHub release discussion: https://github.com/facebook/docusaurus/discussions/9708
- Docs + changelog + blog post PR: https://github.com/facebook/docusaurus/pull/9706
- Examples PR: https://github.com/facebook/docusaurus/pull/9707
> chore: Docusaurus v3.1 examples

- website/docs/api/plugins/plugin-content-docs.mdx
Documenting per discussion at https://github.com/facebook/docusaurus/discussions/9734
This requirement isn't clearly documented, but comes up from time to time (e.g. https://github.com/facebook/docusaurus/discussions/9734).
Deploy preview: https://deploy-preview-9784--docusaurus-2.netlify.app/docs/api/plugins/@docusaurus/plugin-content-docs/#showLastUpdateTime (direct link to change)
N/A
> docs: Note `showLastUpdateTime` requires complete checkout

- website/docs/search.mdx
fixing a typo in [Search docs](https://docusaurus.io/docs/search#using-your-own-search). 
I ran it and found the inconsistency and it's also referenced [here](https://docusaurus.io/docs/swizzling#overview)
> docs: fix documented path of swizzled component

- examples/classic-typescript/docs/tutorial-basics/create-a-blog-post.md
- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/docs/tutorial-basics/create-a-blog-post.md
- examples/classic/package.json
- examples/classic/yarn.lock
Release links:
- Release PR: https://github.com/facebook/docusaurus/pull/9793
- Docs PR: https://github.com/facebook/docusaurus/pull/9794
- Examples PR: https://github.com/facebook/docusaurus/pull/9797
- Release notes: https://github.com/facebook/docusaurus/releases/tag/v3.1.1
- Blog post: N/A
> chore: release Docusaurus 3.1.1 examples

- website/docs/styling-layout.mdx
resolves https://github.com/facebook/docusaurus/issues/9622
> docs: add "TypeScript support" section in the "Modules using Sass/SCSS" section

- website/docs/api/plugins/plugin-vercel-analytics.mdx
Fix typo
Deploy preview
Deploy preview: https://deploy-preview-9845--docusaurus-2.netlify.app/
#9687
> docs: typo

- website/package.json
- yarn.lock
Resolve this security alert - https://security.snyk.io/vuln/SNYK-JS-AXIOS-6144788
crowdin-api-client has updated axios in later versions.
Ran through the build, test and start scripts.  All passed.
> chore(website): update @crowdin/crowdin-api-client

- website/src/data/users.tsx
Fix #9921
Deploy preview: https://deploy-preview-9929--docusaurus-2.netlify.app/showcase?name=bruce
#9921
> docs(showcase): update link

- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/package.json
- examples/classic/yarn.lock
Follow-up of https://github.com/facebook/docusaurus/pull/10000
> chore: update examples to v3.2.0

- website/docs/seo.mdx
- website/versioned_docs/version-3.0.1/seo.mdx
- website/versioned_docs/version-3.1.1/seo.mdx
- website/versioned_docs/version-3.2.0/seo.mdx
Head tags should not be defined in theme config
Preview
Deploy preview: 
https://deploy-preview-10014--docusaurus-2.netlify.app/docs/seo/
https://deploy-preview-10014--docusaurus-2.netlify.app/docs/3.2.0/seo/
https://deploy-preview-10014--docusaurus-2.netlify.app/docs/3.1.1/seo/
#9991
fix #9792
> docs(website): fix SEO docs headTags example

- project-words.txt
- website/community/2-resources.mdx
Adds Orama search plugin for Docusaurus v2 and v3
No code changes. Only documentation.
Deploy preview: https://deploy-preview-10030--docusaurus-2.netlify.app/
- [Page changed](https://deploy-preview-10030--docusaurus-2.netlify.app/community/resources/#search)
N/A
> docs(website): add @orama/plugin-docusaurus* search plugins

- packages/docusaurus-theme-translations/locales/it/theme-common.json
I've noticed the translation in italian for the Tip admonition is wrong, probably due to a lack of context when translating, as "tip" is more like a suggestion, a hint, instead of a tip for the waiter.
No tests changes.
Deploy preview: https://deploy-preview-10051--docusaurus-2.netlify.app/
No.
> fix(theme-translations): correct label for tip admonition in italian

- website/static/manifest.json
Updated the "name" field to v3 instead of v2
Docusaurus is not in v2 anymore.
N/A
N/A
> fix(website): fix website manifest.json name "Docusaurus v2" to just "Docusaurus"

- website/docs/guides/markdown-features/markdown-features-assets.mdx
It would be great if the simple examples are Copy@Pasteable to work. No big deal to look up the import statement for the missing `useBaseUrl`, but i think it would be handy to have it there.
> docs: make `ThemedImage` example work out of the box

- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/package.json
- examples/classic/yarn.lock
Follow-up of 3.3.2 release: https://github.com/facebook/docusaurus/pull/10101
> chore: update examples for Docusaurus 3.3.2

- argos/tests/screenshot.spec.ts
Argos/Playwrite CI is stuck on main due to some hydration errors that remain to be fixed
For now I ignore the errors that already existed before, but we'll have to fix those at some point
CI
> chore: Ignore more playwright console errors

- packages/docusaurus/src/server/__tests__/brokenLinks.test.ts
- packages/docusaurus/src/server/brokenLinks.ts
Fix https://github.com/facebook/docusaurus/issues/10116
unit tests
> fix(core): the broken anchor checker should not be sensitive pathname trailing slashes

- packages/docusaurus/src/commands/serve.ts
Handle this comment: 
https://github.com/facebook/docusaurus/pull/10142#pullrequestreview-2060664595
local
> fix(core): fix serve workaround regexp

- .github/workflows/build-hash-router.yml
> chore: fix invalid CI workflow build-hash-router.yml

- .github/workflows/build-hash-router.yml
> chore: fix ci? 

- website/community/2-resources.mdx
Migrate a Gatsby website to Docusaurus. There was a graphview plugin there that was needed for the current website. I created a plugin similar for docusaurus. Link: [docusaurus-graph](https://github.com/Arsero/docusaurus-graph)
Deploy preview: https://deploy-preview-10176--docusaurus-2.netlify.app/community/resources/#features
> docs: add community plugin docusaurus-graph

- examples/classic-typescript/blog/tags.yml
- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/blog/tags.yml
- examples/classic/package.json
- examples/classic/yarn.lock
Follow-up of release https://github.com/facebook/docusaurus/pull/10186
> chore: update examples for v3.4.0

- website/blog/releases/3.4/index.mdx
I saw a missing backtick and I couldn't help myself
With this we now have:
instead of:
Deploy preview: https://deploy-preview-10194--docusaurus-2.netlify.app/blog/releases/3.4/
> docs: fix missing `

- packages/docusaurus-utils/src/__tests__/markdownUtils.test.ts
- packages/docusaurus-utils/src/markdownUtils.ts
Fix https://github.com/facebook/docusaurus/issues/10220
Unit tests
> fix(markdown): mdx-code-block should support intentation

- website/docs/introduction.mdx
I have OCD and one of them was missing an emoji.
Not required for a PR of this capacity.
N/A
N/A
> docs: add emoji for consistency

- admin/scripts/formatLighthouseReport.js
See https://developer.chrome.com/blog/update-install-criteria
> chore: lighthouse report has no PWA section anymore

- .github/workflows/lint.yml
- package.json
- yarn.lock
Prevent possible lock file supply chain attacks
See this local test: https://github.com/facebook/docusaurus/pull/10267#issuecomment-2217973995
See https://github.com/facebook/docusaurus/pull/10266 for the original motivation
> chore: add lockfile-lint to CI

- packages/docusaurus-theme-classic/package.json
- yarn.lock
Test links
addresses https://github.com/facebookincubator/infima/issues/306
> chore(deps): update infima npm dependency to version 0.2.0-alpha.44

- examples/classic-typescript/blog/authors.yml
- examples/classic-typescript/docusaurus.config.ts
- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/blog/authors.yml
- examples/classic/docusaurus.config.js
- examples/classic/package.json
- examples/classic/yarn.lock
update examples for v3.5 after release: https://github.com/facebook/docusaurus/pull/10379
> chore: update examples for v3.5

- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/package.json
- examples/classic/yarn.lock
Update examples after patch release
> chore: update examples for v3.5.1

- examples/classic-typescript/blog/2019-05-28-first-blog-post.md
- examples/classic-typescript/blog/2019-05-29-long-blog-post.md
- examples/classic-typescript/blog/2021-08-01-mdx-blog-post.mdx
- examples/classic-typescript/blog/2021-08-26-welcome/index.md
- examples/classic-typescript/blog/authors.yml
- examples/classic-typescript/blog/tags.yml
- examples/classic-typescript/docusaurus.config.ts
- examples/classic-typescript/package.json
- examples/classic-typescript/yarn.lock
- examples/classic/blog/2019-05-28-first-blog-post.md
- examples/classic/blog/2019-05-29-long-blog-post.md
- examples/classic/blog/2021-08-01-mdx-blog-post.mdx
- examples/classic/blog/2021-08-26-welcome/index.md
- examples/classic/blog/authors.yml
- examples/classic/blog/tags.yml
- examples/classic/docusaurus.config.js
- examples/classic/package.json
- examples/classic/yarn.lock
> chore: update examples for v3.5.2

- website/blog/releases/3.5/index.mdx
> docs(website): small spellfix on 3.5 update notes

- website/docs/search.mdx
Typo
While reading the documentation, this typo caught my attention.
NA
> docs: corrected typo in search.mdx

- README.md
> docs: fix Twitter => X link in repo README

- website/blog/releases/3.5/index.mdx
#10325 is Indonesian, not Estonian
N/A
Deploy preview: https://deploy-preview-10437--docusaurus-2.netlify.app/blog/releases/3.5/#translations
> docs: Fix typo on changelog

- packages/docusaurus-theme-classic/package.json
- yarn.lock
Integrates Infima 45 with fix https://github.com/facebookincubator/infima/pull/311
Fix https://github.com/facebook/docusaurus/issues/10436
CI
https://deploy-preview-10439--docusaurus-2.netlify.app/
> fix(theme): upgrade infima, fix footer link width bug

- README.md
> docs: Update README.md twitter links

- website/docs/deployment.mdx
- website/versioned_docs/version-2.x/deployment.mdx
- website/versioned_docs/version-3.0.1/deployment.mdx
- website/versioned_docs/version-3.1.1/deployment.mdx
- website/versioned_docs/version-3.2.1/deployment.mdx
- website/versioned_docs/version-3.3.2/deployment.mdx
- website/versioned_docs/version-3.4.0/deployment.mdx
- website/versioned_docs/version-3.5.2/deployment.mdx
The GitHub docs link to [Configuring a Workflow File](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#creating-a-workflow-file) now leads to a 404 HTTP response. This PR replaces the link with the GitHub Use Case page on [Creating an Example Workflow](https://docs.github.com/en/actions/use-cases-and-examples/creating-an-example-workflow) shows information relevant to creating the workflow file.
N/A
https://deploy-preview-10498--docusaurus-2.netlify.app/docs/deployment#triggering-deployment-with-github-actions
(Select the "Remote" tab)
> docs: Fix link to GitHub workflow file docs

- website/blog/2017/12-14-introducing-docusaurus.mdx
> docs: Update twitter links in introducing-docusaurus blog post

- website/docs/introduction.mdx
> docs: update twitter link in introduction docs

- packages/docusaurus-bundler/package.json
- packages/docusaurus-plugin-pwa/package.json
- packages/docusaurus-plugin-pwa/src/index.ts
- packages/docusaurus-types/package.json
- packages/docusaurus/package.json
- packages/docusaurus/src/webpack/client.ts
- packages/docusaurus/src/webpack/server.ts
- website/package.json
- yarn.lock
New version has some interesting type fixes for us and simplifies a bit our code.
https://github.com/webpack/webpack/releases/tag/v5.95.0
CI
https://deploy-preview-10548--docusaurus-2.netlify.app/
> chore: upgrade Webpack to 5.95 and related deps

- website/docs/api/plugins/plugin-google-analytics.mdx
Changed the deprecation message for the plugin from future to past tense, reflecting that the plugin became useless on July 1, 2023
> docs: update google analytics plugin message to past tense

- website/community/2-resources.mdx
> docs: resource add docusaurus-i18n

- .github/workflows/build-perf.yml
> chore: fix ci typo in build-perf.yml

- packages/docusaurus-bundler/src/minifyHtml.ts
- packages/docusaurus-faster/package.json
- yarn.lock
Upgrade deps of `@docusaurus/faster`
CI
https://deploy-preview-10609--docusaurus-2.netlify.app/
> chore: upgrade faster packages

- packages/docusaurus-bundler/src/importFaster.ts
Clearer error message + color package name
> fix(faster): fix error message typo + add color

- packages/docusaurus-faster/package.json
This lib is required for using the package with Yarn PnP
none 😅
> fix(faster): add missing tslib dependency

- website/docs/api/plugins/plugin-content-blog.mdx
Just a quick fix in the doc for a description which was probably forgotten after being copy-pasted.
> docs: fix description of `feedOptions.xslt`

- package.json
- website/_dogfooding/_pages tests/crashTest.tsx
- yarn.lock
TS 5.7 + minor type fix due to stricter checking
> chore: upgrade to TS 5.7

- website/src/data/users.tsx
The project was archived on GitHub and the domain expired
> docs: Removed AgileTs from the Showcase

- website/docs/guides/docs/sidebar/index.mdx
Removed at its crux because this phrase confuses the users who are not native speakers. The phrase "at its crux" means "at its core" or "at its essence." It doesn't provide the useful information for this sentence, so can be removed.
> docs: simplify sidebar description

- examples/classic-typescript/package.json
- examples/classic-typescript/src/components/HomepageFeatures/index.tsx
- examples/classic-typescript/src/pages/index.tsx
- examples/classic-typescript/tsconfig.json
- examples/classic-typescript/yarn.lock
- examples/classic/package.json
- examples/classic/yarn.lock
> chore: update examples for v3.7.0

- website/docs/api/themes/theme-live-codeblock.mdx
Links out directly to package so consumers can find it easily.
Check link resolves
Deploy preview: https://deploy-preview-10874--docusaurus-2.netlify.app/docs/api/themes/@docusaurus/theme-live-codeblock/
> docs(theme-live-codeblock): update theme-live-codeblock.mdx to include link to react-live

- website/src/data/users.tsx
wasp-lang.dev is now wasp.sh
Wasp has moved their domain, and I wanted to reflect that change.
> docs: updating showcase site link

- packages/create-docusaurus/templates/shared/blog/authors.yml
- website/blog/authors.yml
> misc(blog): Update Yangshun bio

- website/versioned_docs/version-2.x/migration/migration-manual.mdx
This pull request contains changes to improve clarity, correctness and structure.
> docs: typo in documentation files

- examples/README.md
- examples/classic-typescript/README.md
- examples/classic/README.md
- packages/create-docusaurus/templates/shared/README.md
- packages/docusaurus-theme-translations/README.md
- packages/lqip-loader/README.md
Some bash scripts don't have [code block language](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) like the below.
````
```
$ yarn
```
````
Then I added the [bash language](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) name to them.
````
```bash
$ yarn
```
````
It's changes the color and style of source code to make it easier to read.
N/A
N/A
N/A
> docs: add missing code block language to README.md

- website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
The [current link](https://github.com/mdx-js/specification) to MDX specification is stale
> This repo is archived. Up-to-date info is now in other places.
> Allmost all info is now on the website: [mdxjs.com](https://mdxjs.com/).
The link is updated to [MDX's doc](https://mdxjs.com/docs/) in `docs/guides/markdown-features/markdown-features-code-blocks.mdx` file.
- [ø] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ø] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.
Having an appropriate link to MDX documentation.
ø
Deploy preview: https://deploy-preview-10981--docusaurus-2.netlify.app/docs/markdown-features/code-blo …
> docs: update external link to MDX reference

- packages/docusaurus-plugin-ideal-image/src/theme/IdealImageLegacy/components/IdealImage/waypoint.tsx
fix https://github.com/facebook/docusaurus/issues/11018
Bug introduced in https://github.com/facebook/docusaurus/pull/11014 where I removed some delaying logic based on `setTimeout`. 
Unfortunately this prevents React from seeing state updates due to batching. `queueMicrotask` is a more accurate version of what the author originally tried to achieve.
preview
https://deploy-preview-11026--docusaurus-2.netlify.app/
Page causing problems: https://deploy-preview-11026--docusaurus-2.netlify.app/docs/playground
> fix(ideal-image): fix waypoint initial scroll bug

- packages/docusaurus-theme-translations/locales/ja/theme-common.json
Adds a missing Japanese translation.
System ← <span lang="ja">システム</span>
Mode ← <span lang="ja">モード</span>
#10987
> fix(theme-translation): add missing Japanese translation for System Mode

- packages/docusaurus-theme-mermaid/package.json
- yarn.lock
Fix https://github.com/facebook/docusaurus/issues/11064
Looks like a temporary buggy mermaid release that prevents labels from displaying.
Since we use a semver range, site owners can upgrade themselves, so it's mostly a fix for our own website
preview
https://deploy-preview-11066--docusaurus-2.netlify.app/tests/pages/diagrams
> chore: upgrade mermaid, fix diagram labels bug

- packages/docusaurus-faster/package.json
- yarn.lock
Try to fix Rust panic error in dev, see https://github.com/web-infra-dev/rspack/issues/9834#issuecomment-2786085142
local
> chore: upgrade Rspack 1.3.3

- website/docs/deployment.mdx
Seems like [layer0](https://www.layer0.co/) already shutdown, i couldn't find any information about them on the internet, so I removed it from the document.
> docs(deploy): remove `layer0` from deployment docs

- packages/create-docusaurus/templates/shared/README.md
The `create-docusaurus` CLI tool generates a readme file that is incompatible with certain assistive technology. This update aims to provide a slightly more user-friendly starting point for new Docusaurus users.
> fix(create-docusaurus): Improve init template README, fix headings and remove $ in bash code blocks

- website/docs/api/plugins/plugin-ideal-image.mdx
- website/versioned_docs/version-3.7.0/api/plugins/plugin-ideal-image.mdx
Fix https://github.com/facebook/docusaurus/issues/11173
> docs(ideal-image): Add warning for pnpm 10+ and `sharp` install script

- packages/docusaurus-plugin-content-docs/src/sidebars/utils.ts
- packages/docusaurus-plugin-ideal-image/src/theme/IdealImageLegacy/components/helpers.js
- packages/docusaurus-theme-common/src/utils/useThemeConfig.ts
- Optional chaining should be preferred
- <https://next.sonarqube.com/sonarqube/coding_rules?open=typescript%3AS6582&rule_key=typescript%3AS6582>
- Optional property declarations should not use both '?' and 'undefined' syntax
- <https://next.sonarqube.com/sonarqube/coding_rules?open=typescript%3AS4782&rule_key=typescript%3AS4782>
no
> refactor: remove unnecessary undefined & use optional chain

- website/blog/releases/3.8/index.mdx
- website/src/css/custom.css
Because site deploy is stuck due to i18n/Crowdin
> chore: Add missing v3.8 blog post mdx-code-block

- .gitignore
- package.json
- packages/docusaurus-bundler/src/currentBundler.ts
- project-words.txt
- yarn.lock
Upgrade Rspack to v1.4 RC to fix our own website localized builds (fix https://github.com/facebook/docusaurus/issues/11240)
Fix Rspack tracing after breaking change: https://github.com/web-infra-dev/rspack/pull/10549
local + CI
> chore: upgrade website to Rspack 1.4 + fix Rspack internal performance tracing

- package.json
- packages/docusaurus-faster/package.json
- packages/docusaurus/src/webpack/base.ts
- yarn.lock
Upgrade to stable Rspack 1.4 for all users so that they don't encounter this bug: https://github.com/facebook/docusaurus/issues/11240
Also, rewire a bit how we define Rspack experiments. `incremental` is enabled by default now, and I'd like to test locally `lazyCompilation` to see if it works well.
CI
> feat(faster): Upgrade to Rspack 1.4

- README.md
We're providing weekly accessibility reports on the site. This PR adds a direct link to a page with the latest validation stats and reports so devs can quickly find accessibility and HTML issues to fix.
Click the added link in the README, check it gets you to the Rocket Validator stats for Docusaurus.io
> docs: adds link to latest accessibility stats and reports in Rocket Validator

- website/docs/api/plugins/overview.mdx
Found a small typo while reading the documentation - there was a stray 'u' character after the CSS cascade layers plugin link in the plugin overview page.
This is a simple typo fix in the documentation.
> docs: remove stray character in plugin overview page

- website/src/data/users.tsx
In the search result, search the word "Docusaurus" and conincidently saw this. Bloga and Doca rhyme that is why does not actually feel like a mistake.
> fix(website): showcase spelling mistake of the word docusaurus in user desc
