facebook/docusaurus

packages/docusaurus/src/client/exports/ComponentCreator.tsx

refactor(core): improve error message when a page has no default-export

---

.cspell.json
.devcontainer/devcontainer.json
.eslintrc.js
jest.config.mjs
package.json
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-docs/src/__tests__/lastUpdate.test.ts
packages/docusaurus-plugin-content-docs/src/lastUpdate.ts
packages/docusaurus-utils/src/gitUtils.ts
packages/docusaurus-utils/src/index.ts
project-words.txt

Refs https://github.com/cardano-foundation/developer-portal/pull/557
Refs https://github.com/facebook/docusaurus/pull/6593

fix(content-docs): warn when files are not tracked

---

packages/docusaurus-plugin-content-docs/src/lastUpdate.ts
packages/docusaurus-utils/src/__tests__/gitUtils.test.ts
packages/docusaurus-utils/src/gitUtils.ts

Added some basic tests so this file is at least test-covered.
Yes

test: add tests for gitUtils

---

packages/docusaurus-types/package.json
yarn.lock

chore(types): remove querystring from dependencies

---

packages/stylelint-copyright/package.json

Not sure to remember why exactly (was related to canary releases and Docusaurus v1) but publish of stylelint-copyright has been disabled
I guess we can safely re-enable it now that v1 is not part of the main branch anymore? 🤷‍♂️ 
yes
CI

chore: publish stylelint-copyright again

---

.eslintrc.js
jest.config.mjs
jest/utils/git.ts
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/temp/.gitignore
packages/docusaurus-plugin-content-docs/src/__tests__/lastUpdate.test.ts
packages/docusaurus-plugin-content-docs/src/lastUpdate.ts
packages/docusaurus-utils/src/__tests__/gitUtils.test.ts

https://github.com/facebook/docusaurus/pull/6937#discussion_r833133765
I wrote tests.
https://github.com/facebook/docusaurus/pull/6937
https://github.com/cardano-foundation/developer-portal/pull/557

fix(content-docs): suppress git error on multiple occurrences

---

packages/docusaurus-utils-validation/src/__tests__/__snapshots__/validationSchemas.test.ts.snap
packages/docusaurus-utils-validation/src/__tests__/validationSchemas.test.ts
packages/docusaurus-utils-validation/src/validationSchemas.ts

Remark and Rehype plugins allow having options as a non-object type, such as a string.
For instance, the official MDX docs even have an example of this:
> ```js
> import {compile} from '@mdx-js/mdx'
> // ...
> import remarkFrontmatter from 'remark-frontmatter'
> // ...
> const file = '# hi'
> // ...
> // A plugin with options:
> await compile(file, {remarkPlugins: [[remarkFrontmatter, 'toml']]})
> ```
>
> Copied from https://mdxjs.com/docs/extending-mdx/#using-plugins
>
> This describes an official remarkjs plugin: [remarkjs/remark-frontmatter](https://github.com/remarkjs/remark-frontmatter), which allows passing a string (e.g. `"toml"`) as the options arg, instead of an object.
Apparently it may also be possible for a unified plugin to have multiple option parameters ([see …

fix(validation): allow non-object params to remark/rehype plugins

---

website/docs/typescript-support.md

According to the page generated from website/docs/typescript-support.md, you should run `npm run tsc` to run `tsc` to do a type check. However, in the package.json file for Docusaurus version 2.0.0-beta.17 the command is actually `npm run typecheck`, which runs `tsc`.
This update only replaces `tsc` with `typecheck` so the npm script will run correctly.
This is a very small but inconvenient typo. I wanted to save others the trouble of the docs having a wrong command.
This typo does not appear to be corrected in the next version of the documentation website either.
I have read the community guidelines on pull requests. I hope I have followed them correctly for what I hope is a simple fix.
There should not need to be a test plan since this is a documentation change of a single word on a …

docs: npm run tsc -> npx tsc

---

packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/CodeBlock/CopyButton/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/CopyButton/styles.module.css
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css

I have long noticed that many docs sites use icons instead of text in for copy code buttons. I would call this a modern style that makes sense for us to follow it. Besides better design, icons are shorter than text, for example text of "Copy" in Russian will look long (compared to English one) -- "Copy" vs "Скопировать"
Also you can see in the screenshot that the default colors don't meet to the WCAG contrast requirement https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=ACADAF
Also, since a clipboard icon turns out to be smaller in size, we can display it in UI with small opacity to demonstrate that the code can be copied. Probably not a big deal but it makes the UI cleaner and more transparent.
Pages/alternative demos for reference/inspiration which uses copy code button …

refactor: replace text-based copy code button with icons

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/DocSidebarItem/index.tsx
yarn.lock

Bump Infima to fix Docusaurus search issue described in https://github.com/facebookincubator/infima/pull/227
Search is a bit broken on all categories linking to a doc or a generated index
yes
preview works + search works in prod after crawler runs

fix(search): bump Infima, fix Docusaurus search issue due to broken CSS selector

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/CopyButton/index.tsx

- Reduced the timeout to 1s which seems more sensible
- Clean up the timeout before unmount because state is mutated in the timeout:
I also think that the button is only ever reset to the original state after the timeout, so even when the cursor leaves the code block, the button stays as a tick, which seems a little weird. But changing that requires moving state management up to `CodeBlock` which seems too much trouble.
Yes

fix(theme-classic): minor code copy button improvements

---

packages/docusaurus-theme-classic/src/getSwizzleConfig.ts
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/MDXComponents/A.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/Code.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/Details.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/Head.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/Heading.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/Img.module.css
packages/docusaurus-theme-classic/src/theme/MDXComponents/Img.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/Pre.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/Ul.module.css
packages/docusaurus-theme-classic/src/theme/MDXComponents/Ul.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx
project-words.txt
website/docs/introduction.md

Breaking change:
- `ul.contains-task-list` CSS is now locally scoped instead of applied globally
- `<img>` outside of markdown documents won't be auto-applied with `height: auto`: it is your responsibility to apply this in images of your Docusaurus pages if you want that CSS rule again, or to apply it back with a global CSS rule
Make it easy to swizzle one specific component used to render MDX elements
yes
preview

refactor: extract MDX components

---

website/docs/guides/markdown-features/markdown-features-admonitions.mdx

`::: info` should be `:::info` or else Docusaurus does not render it as an admonition.

docs: fix example admonition syntax

---

packages/docusaurus/src/client/exports/__tests__/useBaseUrl.test.tsx
packages/docusaurus/src/client/exports/useBaseUrl.ts

Fix #6315. It's a pretty trivial fix; not sure if a better solution exists. Since we have this duplicate base URL detection anyways, this fix only exists to make the behavior more consistent. Related to #6294
Yes
Added two tests

fix(core): prevent useBaseUrl returning /base/base when on /base

---

packages/docusaurus-theme-classic/src/theme/DocSidebarItem/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebarItem/styles.module.css
packages/docusaurus-theme-classic/src/theme/IconExternalLink/styles.module.css

The relative positioning of external link icons was originally needed for sidebar items, but it has been applied inside other elements. Therefore, it is better to align that icon only within the doc sidebar items.
Yes
Preview

refactor: better external link icon positioning

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/CopyButton/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css

Just small cleanups in the code.
Yes
Preview (tests pages)

refactor(theme-classic): cleanup of code blocks

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DropdownNavbarItem.tsx

Better identification of dropdown menus for screen readers and slightly improvement of UX when navigating from the keyboard on navbar menu items from dropdown items.
Yes

refactor: improve a11y of dropdown menu

---

packages/docusaurus-plugin-content-docs/src/__tests__/options.test.ts
packages/docusaurus-utils-validation/src/__tests__/__snapshots__/validationSchemas.test.ts.snap
packages/docusaurus-utils-validation/src/validationSchemas.ts
packages/docusaurus/src/server/__tests__/__snapshots__/configValidation.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts

Fix #4412
Yes
Updated snapshots

fix(validation): improve error messages for a few schemas

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/__snapshots__/generator.test.ts.snap
packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/generator.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars/generator.ts
packages/docusaurus-plugin-content-docs/src/sidebars/processor.ts
packages/docusaurus-plugin-content-docs/src/sidebars/types.ts
website/docs/api/plugins/plugin-content-docs.md
website/docs/guides/docs/sidebar/autogenerated.md

The sidebar labels may have changed if you previously relied on a folder's name as category label. The index doc's title will be used instead. To restore the old behavior, simply add a `label` field in your `_category_.json`.
Close #6254. Supercedes #6249
Yes
Added a test case
In these pages: https://deploy-preview-6859--docusaurus-2.netlify.app/tests/docs/tests/category-links/custom-index-convention/intro/ the category labels are now the docs' titles instead of the folder names

feat(content-docs): autogenerate category with linked doc metadata as fallback

---

website/docs/guides/markdown-features/markdown-features-inline-toc.mdx

The semicolon after the TOCInline component is unnecessary and actually gets rendered on screen.

docs: remove unnecessary semicolon

---

packages/docusaurus-types/package.json
yarn.lock

Previously threw an error with yarn pnp and tsc
```
.yarn/cache/@docusaurus-types-npm-2.0.0-beta.18-43e5218138-5e0652360d.zip/node_modules/@docusaurus/types/src/index.d.ts:14:29 - error TS2307: Cannot find module 'history' or its corresponding type declarations.
14 import type {Location} from 'history';
~~~~~~~~~
.yarn/cache/@docusaurus-types-npm-2.0.0-beta.18-43e5218138-5e0652360d.zip/node_modules/@docusaurus/types/src/index.d.ts:15:27 - error TS2307: Cannot find module 'react-loadable' or its corresponding type declarations.
15 import type Loadable from 'react-loadable';
~~~~~~~~~~~~~~~~
Found 2 errors in the same file, starting at: .yarn/cache/@docusaurus-types-npm-2.0.0-beta.18-43e5218138-5e0652360d.zip/node_modules/@docusaurus/types/src/index.d.ts:14
```
Yes
Typechecking is not done …

fix(types): declare history and react-loadable as dependencies

---

packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Category.tsx

A caret is added for even non-collapsible categories:
Yes
https://github.com/facebook/docusaurus/pull/6983

fix(theme-classic): do not add caret for non-collapsible categories

---

packages/docusaurus/src/commands/swizzle/__tests__/__fixtures__/theme/ComponentInFolder/index.css
packages/docusaurus/src/commands/swizzle/__tests__/__fixtures__/theme/ComponentInFolder/index.tsx
packages/docusaurus/src/commands/swizzle/__tests__/__fixtures__/theme/FirstLevelComponent.css
packages/docusaurus/src/commands/swizzle/__tests__/__fixtures__/theme/FirstLevelComponent.tsx
packages/docusaurus/src/commands/swizzle/actions.ts

The standard Facebook copyright comment in completely swizzled components would be nice to remove (just like they are not in swizzled wrappers), as users often have to do this manually. Similar to how init site templates do not have any copyright comments, they should not appear after swizzling of components. 
Yes
Snapshots are same after adding copyright comment in fixtures.

refactor: remove copyright comment from swizzled components

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css

Changed a `border-radius` on code-block container in order for it to match the inner code element, this way `box-shadow` outlines the code-block properly.
The code-block looked broken
Now it's fine
Yes
Served the app locally and checked it manually

fix(theme-classic): adjust shadow on code block

---

website/docs/guides/docs/versioning.md
website/docs/installation.md
website/versioned_docs/version-2.0.0-beta.17/guides/docs/versioning.md
website/versioned_docs/version-2.0.0-beta.17/installation.md
website/versioned_docs/version-2.0.0-beta.18/guides/docs/versioning.md
website/versioned_docs/version-2.0.0-beta.18/installation.md

sidebar.js should be modified to sidebars.js in some files
Yes!

docs: consistently use sidebars.js filename

---

packages/create-docusaurus/src/index.ts
packages/docusaurus-logger/README.md
packages/docusaurus-logger/src/__tests__/index.test.ts
packages/docusaurus-logger/src/index.ts
packages/docusaurus-plugin-content-docs/src/sidebars/normalization.ts
packages/docusaurus/src/client/serverEntry.tsx
packages/docusaurus/src/server/plugins/index.ts

The paths in a command output are better placed in quotes, they were correctly identified as paths. For example, if there is a "dot" at the end of line with path, VS Code will not find that path if you click by it from output:
```
[INFO] 158 translations will be written at i18n/fr/code.json.
[INFO] 6 translations will be written at i18n/fr/docusaurus-theme-classic/navbar.json.
```
Also, quoted paths  make it easier to copy-pasting from terminal, for example currently when trying to copy the path below, a "dot" char will also be selected:
After:
Try to run cli command contains paths in the output, eg `yarn run write-translations -- --locale fr`

feat(logger): new "url" format, add double quotes around paths

---

packages/docusaurus-theme-classic/src/theme/DocPage/Layout/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/Layout/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx

Fixes #7018, broken as result changes in https://github.com/facebook/docusaurus/pull/6925/files#diff-efc286976b85125e3056044ed1ef259e5794477ab266e4c6207a68d795f76b4a
Note: this bug will be noticeable if the content area column on the right is smaller by height than the sidebar.
I had to add back the `docs-wrapper` class as it was before, since I guess that's the only available way to make things work. 
Yes
Create empty Markdown page or via dev tools try to empty content area on any existent page -- the sidebar should be stretched to the footer.

fix: make docs page wrapper take full height

---

packages/docusaurus-theme-classic/src/theme/DocPage/Layout/styles.module.css

In  #7025  I forgot to check the doc layout for mobiles, which resulted in horizontal scrolling on small screens.
Yes
Preview

fix: expand doc main container to full width on mobiles

---

packages/docusaurus-utils/src/__tests__/markdownUtils.test.ts
packages/docusaurus-utils/src/markdownUtils.ts

fix(utils): parse Markdown headings with CRLF line break

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DropdownNavbarItem.tsx

After merging of #6983, the caret icon on collapsible dropdown is no longer displayed on mobiles
Yes

fix(theme-classic): add caret for dropdown on mobile

---

packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts
website/docs/guides/docs/sidebar/autogenerated.md

Currently the code block in https://docusaurus.io/docs/sidebar/autogenerated#autogenerated-sidebar-metadata uses the wrong comment delimiter (`#`) for code highlighting - while it is highlighting YAML frontmatter, the code block language is `md`, which is used to determine the valid comment delimiters for highlighting (https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts). This changes those comments to use `//` instead.
yes
edit and check the website

fix(theme): add bash style to Markdown comment styles

---

packages/docusaurus-theme-common/src/utils/scrollUtils.tsx

Part of the changes in #6666 
Yes
Add `scroll-behavior: smooth` to the root selector
| Before | After |
|--------|-------|
| ![Test](https://user-images.githubusercontent.com/55398995/160586672-9eedd2de-6e18-4f70-9898-31663a1eb7ec.gif) | ![Test2](https://user-images.githubusercontent.com/55398995/160586707-545b5023-a8a8-459d-a47a-600c8d555dc8.gif) |

fix(theme-common): use native scrolling when smooth behavior set in CSS

---

packages/docusaurus/src/server/index.ts
packages/docusaurus/src/server/plugins/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus/src/server/plugins/index.ts

Just realized our later lifecycles like `configureWebpack` and `postBuild` don't receive the translated content. Probably doesn't matter much but would be cool to have anyways

fix(core): all plugin lifecycles should receive translated content

---

packages/docusaurus/src/client/exports/Interpolate.tsx
packages/docusaurus/src/client/exports/__tests__/Interpolate.test.tsx
packages/docusaurus/src/client/exports/__tests__/__snapshots__/Interpolate.test.tsx.snap
website/_dogfooding/_pages tests/error-boundary-tests.tsx

While our `Interpolate` is "functionally" fine, it's semantically incorrect. Each element will be wrapped in a React fragment, and things like `null` will be converted to a literal `"null"` instead of an actual `null` children.
Yes
Updated tests

fix(core): preserve Interpolate children semantics

---

packages/docusaurus-plugin-sitemap/src/__tests__/createSitemap.test.ts
packages/docusaurus-plugin-sitemap/src/__tests__/options.test.ts
packages/docusaurus-plugin-sitemap/src/createSitemap.ts
packages/docusaurus-plugin-sitemap/src/index.ts
packages/docusaurus-plugin-sitemap/src/options.ts
packages/docusaurus-plugin-sitemap/src/plugin-sitemap.d.ts
packages/docusaurus-utils/src/globUtils.ts
website/docs/api/plugins/plugin-sitemap.md
website/docusaurus.config.js

When I generate a sitemap, I want to ignore some paths, such as the path starting with `/tags`, so I add an option named `ignorePatterns` to `plugin-sitemap`, which accepts an array of regular expressions and allows users to ignore some paths that do not need to appear in the sitemap.
Yes.
I've added several test cases in the following files.
- `packages/docusaurus-plugin-sitemap/src/__tests__/createSitemap.test.ts`
- `packages/docusaurus-plugin-sitemap/src/__tests__/options.test.ts`.
No other PRs related to this request as far as I could find.

feat(sitemap): add ignorePatterns option

---

packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.ts
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/NavbarItem/NavbarNavLink.tsx
packages/docusaurus-theme-classic/src/validateThemeConfig.ts
website/docs/api/themes/theme-configuration.md

Although a new `html` type for navbar items is coming soon, it does not solve the issue of having to use HTML as label for a navbar link. It can be useful to style text content of a link or add an SVG icon inside it without using custom CSS. 
Yes
See tests as examples. Is it worth to use the option on the website as applying of dogfooding approach?

feat: allow using pure HTML as label in navbar links

---

packages/docusaurus-plugin-debug/src/index.ts
packages/docusaurus-plugin-debug/src/plugin-debug.d.ts
packages/docusaurus-preset-classic/src/index.ts

If it is now possible to exclude certain pages from generated sitemap file, let's remove the pages related with debugging. 
Yes
See sitemap file on preview site.

feat(preset-classic): exclude debug plugin routes from sitemap

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/server/plugins/__tests__/__fixtures__/presets/preset-mixed.js
packages/docusaurus/src/server/plugins/__tests__/__snapshots__/presets.test.ts.snap
packages/docusaurus/src/server/plugins/configs.ts
packages/docusaurus/src/server/plugins/presets.ts

With this PR the values of `false` and `null` will be properly recognized in types and code, allowing people to write
```ts
plugins: [
isProd && "sitemap",
buildFast ? null : "typedoc",
],
```
instead of having to dynamically push values.
Our validation currently allows `false`, but this isn't really filtered out and leads to bugs in later stages. Moreover this is a type-checking error.
Yes

feat(core): allow plugin/preset config to contain false/null

---

packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/BlogLayout/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogSidebar/Desktop/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogSidebar/Desktop/styles.module.css
packages/docusaurus-theme-classic/src/theme/BlogSidebar/Mobile/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogSidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogSidebar/styles.module.css

Fix the double-scrolling problem reported.
@lex111 also wants to change the font, but I'm not quite sure if that's beneficial in the long term.
Yes

refactor(theme-classic): blog mobile secondary menu use consistent styles

---

packages/docusaurus-plugin-content-blog/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-blog/src/blogUtils.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-blog/src/plugin-content-blog.d.ts
packages/docusaurus-plugin-content-blog/src/types.ts
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/props.test.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-docs/src/props.ts
packages/docusaurus-plugin-content-docs/src/types.ts
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/BlogTagsListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogTagsPostsPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocTagDocListPage/index.tsx
packages/docusaurus-theme-classic/src/theme/Tag/index.tsx
packages/docusaurus-theme-classic/src/theme/TagsListInline/index.tsx
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/__tests__/tagUtils.test.ts
packages/docusaurus-theme-common/src/utils/tagsUtils.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus-utils-validation/src/validationSchemas.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus-utils/src/tags.ts

Tags-related theme components have their props changed. Most notably, `name` has been renamed as `label` to align with its server-side metadata.
We have a lot of duplicated types that only differ slightly. I take this chance to make the tags-related data structures more re-used and more unified between the blog and docs.
Yes
All pages still behave as before

refactor(content-{blog,docs}): unify handling of tags

---

packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/normalization.test.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/server/__tests__/__snapshots__/routes.test.ts.snap
packages/docusaurus/src/server/__tests__/routes.test.ts
packages/docusaurus/src/server/plugins/index.ts
packages/docusaurus/src/server/routes.ts

Complete the TODO. Honestly I'm not too sure what we should put here, so I didn't modify the content plugins yet. We already have front matter duplicated twice (once in `metadata.frontMatter`, once as separate `frontMatter` injected from MDX loader), I don't really want to duplicate it a third time as that would be disastrous for bundle size.
Yes
Builds same as before

feat(core): allow plugins to declare custom route context

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-plugin-content-docs/src/client/docsClientUtils.ts
packages/docusaurus-plugin-content-docs/src/client/index.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/client/exports/__tests__/useGlobalData.test.tsx
packages/docusaurus/src/client/exports/useGlobalData.ts
website/docs/docusaurus-core.md

The docs plugin hook can't use fail-fast because "it's used on non-doc pages" (but I think that's probably not the case anymore). But anyways, to avoid refactor hazards I just added a `failfast` option so we can take advantage of the `useAllPluginInstancesData` hook.
Yes
Build

feat(core): fail-safe global data fetching

---

packages/docusaurus-theme-classic/src/theme/DocSidebar/Desktop/Content/styles.module.css

Fix https://github.com/facebook/docusaurus/issues/5254
`scrollbar-gutter` property support has significantly increased since last time we checked: https://caniuse.com/mdn-css_properties_scrollbar-gutter
Even if support is not perfect, it can already be used as a progressive enhancement thanks to `@supports` mediaquery
yes
preview layout shifts are fixed in all browsers supporting `scrollbar-gutter`
other browsers (Safari) should keep working the same
---
Other related issue: https://github.com/facebook/docusaurus/issues/7130

fix(theme-classic): fix docs sidebar layout shifts when expanding categories

---

packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/Details/index.tsx
packages/docusaurus-theme-common/Details.d.ts
packages/docusaurus-theme-common/package.json
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/tsconfig.json
packages/docusaurus-theme-live-codeblock/package.json
packages/docusaurus-theme-search-algolia/package.json
packages/docusaurus-utils-common/package.json

Instant bundle size optimization⚡️
I did not mark core as side-effect-free, though, because there are a few side-effects there (mostly importing non-module CSS), and it's quite tedious trying to filter out everything.
Yes
Page builds fine

refactor: mark a few client-side packages as side-effect-free

---

packages/docusaurus-theme-classic/src/theme/DocCategoryGeneratedIndexPage/styles.module.css

In #7129 I forgot to take into account that on mobile  margin of generated card items needs to be reset a little differently.
Yes
Preview

fix: proper spacing between generated card items on mobiles

---

packages/docusaurus/src/client/App.tsx
packages/docusaurus/src/client/PendingNavigation.tsx
packages/docusaurus/src/client/clientEntry.tsx
packages/docusaurus/src/client/docusaurus.ts
packages/docusaurus/src/client/preload.ts
packages/docusaurus/src/client/serverEntry.tsx

I was looking at React-router v6 migration again (#6037). Unsurprisingly, the `withRouter` HOC is gone in favor of `useLocation`. However, our `PendingNavigation` is quite hard to refactor into a functional component (due to comparing and setting states in `shouldComponentUpdate`), so to make it easier, I simply moved the fetching of location up to `App.tsx` and pass it into `PendingNavigation` as prop. This brings the additional benefit that `normalizeLocation` can now be called at the top instead of being scattered among the `PendingNavigation` code.
Furthermore, I decided to import `@generated/routes` within `preload`, so that we don't pass the route config object around. This should make the code clearer about which components actually make use of the route config object, which can …

refactor(core): minor PendingNavigation refactor

---

packages/docusaurus/src/client/App.tsx
packages/docusaurus/src/client/PendingNavigation.tsx

Close #6290. Because `react-loadable` sets a default timeout of 200ms, I think this makes more sense. I would agree that `1s` sometimes looks like the page is lagging.
Yes

refactor(core): lower timeout before rendering progress bar to 200ms

---

packages/docusaurus-mdx-loader/src/mdx-loader.d.ts
packages/docusaurus-plugin-content-blog/src/plugin-content-blog.d.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-pages/src/plugin-content-pages.d.ts

The MDX content shape is defined by the MDX loader, so the type should also be exported from there. This makes the types less duplicated.
Yes

refactor: unify how MDX content types are represented

---

website/package.json
website/tsconfig.json
yarn.lock

I mistakenly enabled `skipLibCheck` in the website in #7138. This is dangerous because there's no E2E tests for the type declarations. This is a quickfix, after https://github.com/rpearce/image-zoom/pull/303 has been merged. Luckily no bugs have been introduced so far.
Yes

fix(website): remove skipLibCheck

---

packages/docusaurus-theme-translations/src/__tests__/index.test.ts
packages/docusaurus-theme-translations/src/index.ts

I've seen people trying to use `zh-cn` as locale name, but resolution fails, because `localesToTry` would be `["zh-cn", "zh"]` in this case, neither of which are existent.
I think this is a perfectly valid use-case, so we should try all of {original locale, locale-by-region, locale-by-script, bare language}.
Yes
Added a test

fix(theme-translations): always try all possible locale resolutions

---

.github/workflows/build-blog-only.yml
.github/workflows/build-perf.yml
.github/workflows/canary-release.yml
.github/workflows/codeql-analysis.yml
.github/workflows/lighthouse-report.yml
.github/workflows/lint.yml
.github/workflows/showcase-test.yml
.github/workflows/tests-e2e.yml
.github/workflows/tests-swizzle.yml
.github/workflows/tests-windows.yml
.github/workflows/tests.yml

- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also, dependabot supports upgrading based on SHA.
Signed-off-by: naveensrinivasan …

misc: pin actions to a full-length commit SHA

---

packages/docusaurus-plugin-debug/src/index.ts
packages/docusaurus-plugin-debug/src/plugin-debug.d.ts
packages/docusaurus-plugin-debug/src/theme/DebugLayout/index.tsx
packages/docusaurus-plugin-sitemap/src/__tests__/createSitemap.test.ts
packages/docusaurus-plugin-sitemap/src/createSitemap.ts
packages/docusaurus-plugin-sitemap/src/index.ts
packages/docusaurus-preset-classic/src/index.ts
packages/docusaurus-types/package.json
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/client/serverEntry.tsx
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/deps.d.ts
packages/docusaurus/src/webpack/server.ts

fix #6247. I'm not sure if providing the entire helmet state would be too big as part of the plugin API, but currently it's the only way to get structured data about the head state. Otherwise, we can only export a string and then parse it again in `postBuild`, which sounds like too much overhead.
Yes
I reverted #7122 and added `<meta name="robots" content="noindex" />` to the debug layout. It turns out that these routes are still not included in the sitemap.

fix(sitemap): exclude pages with robots noindex from sitemap

---

packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.ts
packages/docusaurus-theme-classic/src/theme/CodeBlock/CopyButton/styles.module.css
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/styles.module.css
packages/docusaurus-theme-classic/src/validateThemeConfig.ts
packages/docusaurus-theme-common/src/contexts/colorMode.tsx
packages/docusaurus-theme-common/src/hooks/usePrismTheme.ts
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts
packages/docusaurus-theme-common/src/utils/useThemeConfig.ts

My recent PR #7007 broke applying proper background of Prism theme to code blocks (it is especially noticeable when dark mode is on). Unfortunately, inheritance when used with CSS vars works unexpected from it way. Also, as I mentioned earlier https://github.com/facebook/docusaurus/pull/7036/files/ebb2d9e303eeb5978ffcf6573b0162b27868ba43#r845543297 to group the code buttons would require adding `style` attributes coming from Prism on each button.
Overall, the code complexity increases and with it,  increasingly difficult to ensure proper styling of block codes with all use cases in mind.
So I propose to dynamically create two CSS vars corresponding to the current Prism color theme. This way we can avoid overusing of `style` attribute on many elements and it is just a predictable way to …

refactor: control base styling of code blocks via CSS vars

---

packages/docusaurus-theme-classic/src/admonitions.css

Currently `text-transform: uppercase` is set for `.admonition h5`. This makes all texts uppercased even when wrapped by `<code />`.
```mdx
:::tip This is a `code`
:::
```
Yes
After changes are made, codes are no longer uppercased as shown in the screenshot below.

fix(theme-classic): admonition title: disable text-transform on inline code blocks

---

packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/CodeBlock/Container/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/Container/styles.module.css
packages/docusaurus-theme-classic/src/theme/CodeBlock/Content/Element.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/Content/String.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/Content/styles.module.css
packages/docusaurus-theme-classic/src/theme/CodeBlock/Line/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/Line/styles.module.css
packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx
packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts

Preliminary refactor before extracting new theme components meant to be swizzled
yes
Preview tests should be exactly as before
- https://docusaurus.io/tests/pages/code-block-tests
- https://deploy-preview-7175--docusaurus-2.netlify.app/tests/pages/code-block-tests

refactor(theme-classic): split CodeBlock

---

packages/docusaurus-theme-classic/src/theme/DocBreadcrumbs/index.tsx

Fix #7135 
cc @kotryna-k
Yes
Tested on Rich Results.
Last item no longer has `id`.

fix(theme-classic): do not add microdata item prop to trailing breadcrumb

---

__tests__/validate-package-json.test.ts
admin/scripts/generateExamples.mjs
packages/create-docusaurus/src/index.ts
packages/docusaurus-migrate/src/index.ts
packages/docusaurus-theme-translations/locales/__tests__/locales.test.ts
packages/docusaurus-theme-translations/src/index.ts
packages/docusaurus-theme-translations/update.mjs
packages/docusaurus/src/client/serverEntry.tsx
packages/docusaurus/src/server/translations/translations.ts

Makes the code more semantic.
Yes

refactor: prefer fs.readJSON over readFile.then(JSON.parse)

---

packages/docusaurus-theme-classic/src/theme/DocBreadcrumbs/styles.module.css
packages/docusaurus-theme-classic/src/theme/IconHome/index.tsx

Slight optimization for new Home icon, as well as a slight increase in its size to better fit with font-size of text.
Yes
Preview

refactor: improve IconHome icon

---

admin/new.docusaurus.io/package.json
package.json
website/package.json
yarn.lock

Netlify-cli has an incredible bundle size bloat: https://twitter.com/SidaChen63/status/1512969887274004482
Furthermore, it pulls in `typescript@3.9` which under circumstances gets hoisted to the root and results in build errors. I hope this would fix it.
Yes
Ran the `npx -p netlify-cli netlify dev` script locally; still works

chore: remove netlify-cli from dependencies

---

packages/docusaurus/bin/docusaurus.mjs

Currently, all build-time errors don't show proper stack traces because we only log the error itself, which serializes to the message. We should log the full stack instead.
Yes
Throw an error from `lib/commands/build.js`.
Before:
After:

fix(cli): always show error stack to unhandled rejection

---

.github/workflows/build-blog-only.yml
.github/workflows/build-perf.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependency-review.yml
.github/workflows/lighthouse-report.yml
.github/workflows/lint.yml
.github/workflows/showcase-test.yml
.github/workflows/tests-e2e.yml
.github/workflows/tests-swizzle.yml
.github/workflows/tests-windows.yml
.github/workflows/tests.yml

Save CI resources for consecutive commits
Inspired by https://github.com/nodejs/node/pull/42017
Doc: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
yes
CI after merging?

chore: GitHub Actions cancel-in-progress

---

packages/docusaurus/src/commands/swizzle/__tests__/__fixtures__/theme/NoIndex/NoIndexComp1.css
packages/docusaurus/src/commands/swizzle/__tests__/__fixtures__/theme/NoIndex/NoIndexComp1.tsx
packages/docusaurus/src/commands/swizzle/__tests__/__fixtures__/theme/NoIndex/NoIndexComp2.tsx
packages/docusaurus/src/commands/swizzle/__tests__/__fixtures__/theme/NoIndex/NoIndexSub/NoIndexSubComp.tsx
packages/docusaurus/src/commands/swizzle/__tests__/components.test.ts
packages/docusaurus/src/commands/swizzle/__tests__/testUtils.ts
packages/docusaurus/src/commands/swizzle/components.ts
packages/docusaurus/src/commands/swizzle/config.ts

We should be able to swizzle a parent folder of any component to be able to eject the whole folder at once
See also https://github.com/facebook/docusaurus/pull/7175#issuecomment-1103757218
It's currently not possible to eject `CodeBlock/Content` because it has no index and is not appearing in the list:
This now works:
```bash
yarn workspace website docusaurus swizzle @docusaurus/theme-classic CodeBlock/Content --eject --danger
```
yes
tests

fix: allow swizzling a component's parent folder

---

website/docs/i18n/i18n-tutorial.md

There are probably very few people that fully understand how the plural forms work. Let's write some basic explanation.
Yes

docs: add documentation about pluralization

---

packages/docusaurus-theme-classic/src/theme/DocCardList/index.tsx
packages/docusaurus-theme-classic/src/theme/DocCategoryGeneratedIndexPage/index.tsx
website/docs/introduction.md
website/src/pages/index.tsx
website/versioned_docs/version-2.0.0-beta.17/introduction.md
website/versioned_docs/version-2.0.0-beta.18/introduction.md

Did some HTML validation. The most alerting issue is "`<main>` cannot be nested" and "one page should only have one `<main>`".
In addition, I've marked one text as translatable, and removed the deprecated `frameBorder` attribute.
Yes

refactor: semantic markup improvement, fix validation warnings

---

website/src/plugins/changelog/theme/ChangelogPage/index.tsx
website/src/plugins/changelog/theme/ChangelogPaginator/index.tsx
website/src/plugins/changelog/theme/types.d.ts

POC for #7250. It's also been something I wanted to do. 
cc @wgruszczyk
Yes

docs: change changelog paginator label

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/globalData.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/globalData.test.ts
packages/docusaurus-plugin-content-docs/src/globalData.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/routes.ts
packages/docusaurus-plugin-content-docs/src/types.ts

Reported in https://github.com/facebook/docusaurus/issues/4542#issuecomment-1107411164
This PR enforces single source of truth for the docs content. We no longer derive some content fields from other content fields, so that we don't accidentally forget some translations.
Yes
Tested locally with `yarn write-translations -l zh-CN` and translating some descriptions.

fix(content-docs): make category index text translatable

---

website/docs/api/plugins/plugin-google-gtag.md

This PR is a follow on from https://github.com/facebook/docusaurus/pull/6184 which I mean to improve the docs for GA4 but actually didn't.  This was discussed in https://github.com/facebook/docusaurus/issues/7221
The change made in this PR reflects the format required for GA4 properties which I'm successfully using here: https://github.com/johnnyreilly/blog.johnnyreilly.com/blob/4e824dc2172efca72c075f1dbc3a39a92fd22064/blog-website/docusaurus.config.js#L35
Yes
No test - it's docs 
See above

docs: update gtag docs to reflect what a GA4 tag looks like

---

packages/docusaurus-plugin-ideal-image/tsconfig.json
packages/docusaurus-plugin-pwa/tsconfig.json
packages/docusaurus-theme-classic/tsconfig.json
packages/docusaurus-theme-search-algolia/tsconfig.json

The `baseUrl` is actually a config option that informs TS about path-mapping. Because we don't have any path-mapping, this is useless and leads to problems if you try to import something in node_modules, because it will import the file with the same name in `src` in priority.
Yes

chore: remove baseUrl from tsconfig

---

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx

docs: wrap code block demos in mdx-code-block

---

website/docs/installation.md

I believe the current version of Docusaurus requires node 16.  With 14 I get:
```
import {program} from 'commander';
^^^^^^^
SyntaxError: The requested module 'commander' does not provide an export named 'program'
at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
at async Loader.import (internal/modules/esm/loader.js:179:24)
```

docs: specify Node version requirement to a minor

---

.github/workflows/build-blog-only.yml
.github/workflows/build-perf.yml
.github/workflows/tests-e2e.yml
.github/workflows/tests-windows.yml
.github/workflows/tests.yml

The test actions trigger too frequently, even for root files like `project-words.txt` that don't actually impact users. I decided to confine everything to `packages/**` only.

misc: tighten CI trigger conditions

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus/src/client/PendingNavigation.tsx
packages/docusaurus/src/client/docusaurus.ts
packages/docusaurus/src/client/exports/Link.tsx
packages/docusaurus/src/client/flat.ts
packages/docusaurus/src/client/prefetch.ts

With this change:
- We are using `Set` instead of an object as the memoization layer, which should be more performant & has better semantics.
- The duplicated `prefetch` memoization has been deduplicated. `prefetchHelper` now does not memoize on itself; only `window.docusaurus.prefetch` does. This is fine, because we don't call `prefetchHelper` directly anywhere else.
- `window.docusaurus.preload` and `window.docusaurus.prefetch` now return `Promise<void[]>` instead of `true`, which can allow external callers to wait for them instead of having floating promises.
Prefetching work the same. You can confirm by scrolling down a page and see the network cascade expanding whenever a new link is in viewport.

refactor(core): prefetch/preload refactor

---

.github/workflows/tests-e2e.yml

Due to https://github.com/pnpm/pnpm/pull/4427, our pnpm action has been failing. I hope this is sufficient to fix it. I'm curious why the Yarn one works, even with `pnpFallbackMode none`, though!
The E2E test is now triggered when the action file changes, so we can preview the effect.

chore: fix pnpm E2E test to work on pnpm v7

---

project-words.txt
website/docs/advanced/client.md
website/docs/advanced/ssg.md

docs: add a paragraph about SSR as an optimization technique

---

packages/docusaurus/src/commands/build.ts
website/docusaurus.config.js

- I _really_ want to add tests but I don't know how to persist it, so see test plan below
It turns out that simply `ensureDir` is not sufficient to make build succeed with an empty static folder. To reproduce, do `mkdir website/_dogfooding/emptyStaticDir`, and add `_dogfooding/emptyStaticDir` to the `staticDirectories` list, then run `yarn build -l en`. Server build errors with:
```
unable to locate '/.../docusaurus/website/_dogfooding/emptyStaticDir/**/*' glob
```
This seems to be a bad thing to happen for a glob pattern, but just in case, I've simply filtered out all non-existent directories instead of creating empty ones. This also means the user doesn't magically have a static folder created after every build.
Tested locally with the above reproduction. I don't really know how to add …

fix(core): allow empty static directories

---

.github/workflows/lint.yml
package.json
packages/docusaurus-plugin-debug/src/theme/DebugJsonView/index.tsx
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/server/configValidation.ts
website/docs/api/docusaurus.config.js.md
website/docs/api/plugins/plugin-sitemap.md
website/docs/deployment.mdx
website/docs/guides/markdown-features/markdown-features-links.md

More JSDoc for better DX. Made some necessary doc changes to make the two in sync, also reordered the types a bit so they appear in a more logical order.
Deploy preview: https://deploy-preview-7291--docusaurus-2.netlify.app/docs/api/docusaurus-config/

refactor(types): JSDoc for docusaurus config fields

---

packages/docusaurus-logger/src/index.ts
packages/docusaurus-remark-plugin-npm2yarn/src/__tests__/index.test.ts

We previously had some hack around `module.exports` to support importing these packages in both ESM and CJS, because `export default` will be compiled to `module.exports.default = `, which will work in neither ESM nor CJS (only in TypeScript, where it knows how to handle `default`). This turns out to be no longer necessary now, because we use SWC instead of Babel, which supports `export = ` OOTB, without bringing some extra plugins.
Everything still works

refactor: use export = syntax for Node utility packages

---

website/docs/guides/markdown-features/markdown-features-react.mdx
website/docs/guides/markdown-features/markdown-features-tabs.mdx
website/versioned_docs/version-2.0.0-beta.17/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-2.0.0-beta.17/guides/markdown-features/markdown-features-tabs.mdx
website/versioned_docs/version-2.0.0-beta.18/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-2.0.0-beta.18/guides/markdown-features/markdown-features-tabs.mdx

These tags were there because the browser window didn't have good margins. After #7119, this is no longer necessary.

docs: remove extraneous line break tags

---

packages/docusaurus-theme-classic/src/__tests__/__snapshots__/translations.test.ts.snap
packages/docusaurus-theme-classic/src/__tests__/translations.test.ts
packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.ts
packages/docusaurus-theme-classic/src/theme/DocSidebar/Desktop/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Category.tsx
packages/docusaurus-theme-classic/src/validateThemeConfig.ts
packages/docusaurus-theme-common/src/utils/useThemeConfig.ts
website/docs/api/docusaurus.config.js.md
website/docs/guides/docs/sidebar/index.md
website/docusaurus.config.js

We are having more and more theme config options that are at the root. To make things more scalable in the future, I propose to namespace them all under `docs.sidebar`.
Added two tests to verify that validation schema works.

refactor(theme-classic): move all sidebar-related config under themeConfig.docs.sidebar

---

packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/server/plugins/index.ts

Close #3918. After 1 year and a half, we only had one user complaining, and there's no follow-up. I can only assume that this is going to impact no-one.
#3918 mentioned search plugins as a use-case. We now have many successful search plugins that read the routes data through `postBuild`, so I believe there's no valid use-case of this lifecycle anymore.
Yes

refactor: remove long-deprecated routesLoaded lifecycle

---

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx

The Netlify deployment is failing again. Let's see if adding `mdx-code-block` fixes it. Also addresses a suggestion at https://github.com/facebook/docusaurus/pull/7178#discussion_r864691253
Cross our fingers

docs: add mdx-code-block around tabs; use JS example for magic comments

---

.github/workflows/lighthouse-report.yml
.github/workflows/scripts/format-lighthouse-score.js

Since the doc page represents the main functionality of Docusaurus, Lighthouse should check it instead of the landing page. For example, the a11y error with the home page in the breadcrumbs could have been detected earlier.

misc: check doc page by Lighthouse CI

---

.github/workflows/lighthouserc.json

This should not prevent the creating of a comment with the report in case of insufficient score (see https://github.com/facebook/docusaurus/runs/6289742244?check_suite_focus=true)

misc: run Lighthouse CI without assertions

---

lerna.json

Following discussions on Discord, we agreed to rename "Internal" to "Maintenance", and reserve "Internal" for those tags that will not be added to the changelog.

chore: use "Maintenance" instead of "Internal" in changelog

---

.github/dependabot.yml

Followup of #7309. Let's make all PR tags begin with "tag: "

chore: make dependabot use tag: dependencies tag

---

packages/create-docusaurus/templates/classic/docusaurus.config.js

I've noticed a lot of non-English sites not changing their language correctly—this is bad for both SEO and accessibility. Putting it in the init template should allow better visibility.

refactor(create): add i18n config in init template

---

.github/dependabot.yml

I'm now doing weekly dependency upgrades myself, there's no need to continue using dependabot. It's still nice to upgrade GitHub actions, but for npm it's too much noise.

chore: remove dependabot from upgrading npm dependencies

---

packages/docusaurus-theme-classic/src/theme/DocBreadcrumbs/index.tsx
project-words.txt

This has caused too much confusion, both on Discord and on the issue tracker (#7303, #7241). Even when I tend to think it's working as intended, let's remove it from the default theme to conform to the one and only truth™ in search engines.
Tested on rich results; it's valid now.

fix(theme-classic): remove breadcrumb items without href from microdata

---

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx

The site can't deploy due to MDX and too many code block backticks, messing up with Crowdin translations
Not sure it's the best way to fix it but it works better at least 🤷‍♂️ 
local + preview
https://github.com/facebook/docusaurus/pull/7307

chore: fix site deployment Crowdin issue

---

website/docs/guides/docs/versioning.md

This PR attempts to add a bit of clarity around the source folders & web URLs for versioning behavior.
I was trying to understand how Docusaurus itself handles versions, as [our Camunda docs](https://docs.camunda.io/) handle it slightly differently, and I struggled a bit trying to connect all the dots for these lines. This is a very minor docs update, but I thought specifying the source folders & web URLs for both described versions would add clarity. 
I chose to not add the changes to older versioned docs because it was so minor. 
No test plan for this minor update to doc verbiage. 
Deploy preview: https://deploy-preview-7327--docusaurus-2.netlify.app/docs/versioning/#configuring-versioning-behavior
None that I could find.

docs: add clarity to versioning behavior

---

admin/scripts/format-lighthouse-score.mjs
website/src/css/custom.css
website/src/utils/prismLight.mjs

The lighthouse report is reporting a11y problems on the doc page because the breadcrumb active item doesn't have enough contrast. I've darkened it a bit.
No more a11y warnings.

fix(website): fix multiple accessibility issues around color contrast

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/Line/styles.module.css

Noticed that the code block number highlighting is not properly applied. This PR fixes it.
Deploy preview: https://deploy-preview-7341--docusaurus-2.netlify.app/docs/markdown-features/code-blocks/#line-numbering
#7178

fix(theme-classic): properly highlight code block line numbers

---

packages/docusaurus/src/client/ClientLifecyclesDispatcher.tsx

Fix regression of https://github.com/facebook/docusaurus/pull/6732
On page refresh, we scroll to top for a while instead of keeping previous scroll position
The code that scrolls to top/anchor after a navigation should not be executed on first page load (like it used to be)
preview does not
https://github.com/facebook/docusaurus/pull/6732

fix: avoid flash of page scrolling to top on refresh

---

website/community/4-canary.md
website/community/Versions.tsx
website/docusaurus.config.js

The canary release page has always been a bit inconvenient to use, because it only displays an example. With this PR, we can try our best to display an actually functional name.
Deploy preview: https://deploy-preview-7334--docusaurus-2.netlify.app/community/canary/

feat(website): make canary release page display actual canary version name

---

packages/docusaurus-types/package.json

I added some missing dependencies requested by react-helmet-async in @docusaurus/types. The missing dependencies are react and react-dom.
Installing @docusaurus/types triggers warnings about peer dependencies that are not provided. To fix these warnings, I added the peerDependencies to the @docusaurus/types package.
No code change, no test.
No test link.
No known related issues/PRs.

fix(types): declare missing peerDependencies

---

packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts

This fixes a tiny configuration setting validation bug #7359
Set the githubPort config in a docusaurus.config.js and run deploy command

fix(core): allow githubPort in config validation

---

packages/docusaurus-theme-classic/src/index.ts
website/docusaurus.config.js

Because after #6921, relative paths from plugins are resolved relative to the plugin entry point, specifying relative CSS paths no longer works. (I don't know if it worked before; never tried. It's highly possible that it didn't either.) Anyways, `./src/css/custom.css` should definitely work.
Used a relative path in our own config.

fix(theme-classic): resolve customCss from site dir

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus/src/client/exports/ErrorBoundary.tsx
website/docs/docusaurus-core.md

I realized we made a wild mistake: we should _render_ the component instead of _call_ it. The semantics of this prop is very unclear: we said in the docs that it's a callback and we also call it like `fallback({...})`, but the `DefaultFallback` and what's actually passed in in our internal usage are both components.
As a general principle, components should not be called directly, because (a) it may be a class and (b) it may contain hooks. This aims to make the semantics of this prop clearer by making it receive an actual component.
Testing is a bit hard :(

fix(core): make error boundary fallback a component instead of a callback

---

packages/docusaurus/src/commands/swizzle/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus/src/commands/swizzle/__tests__/actions.test.ts
packages/docusaurus/src/commands/swizzle/actions.ts

Currently, when running `yarn swizzle @docusaurus/theme-classic NavbarItem/DropdownNavbarItem --eject --danger`, it outputs `src/theme/DropdownNavbarItem.js` without the `NavbarItem` folder. This PR fixes it.
Added a test case

fix(cli): output correct path when swizzling bare-file component in subfolder

---

packages/create-docusaurus/src/index.ts

The create-docusaurus code is super messy, and because it's highly async and imperative, it's quite hard to refactor. Therefore, this refactor probably doesn't make the code any cleaner (😅), however, it aims to make the code more _correct_.
We get our input from two sources: CLI args, or prompt results. What happens when part of the arguments are provided from CLI, but we are missing information and need to prompt them? (e.g. `yarn create docusaurus --git-strategy shallow`) This PR will standardize the behavior in this case. (Previously, we would still prompt for the template, and would even accept `classic`—but in this case, we should really only accept a git repo URL)
What happens when you use a local template, and the local template contains a lockfile? We should definitely use the …

refactor(create): clean up logic when prompting for unspecified arguments

---

packages/docusaurus-mdx-loader/src/loader.ts
website/_dogfooding/_pages tests/markdownPageTests.md

Regression introduced by https://github.com/facebook/docusaurus/pull/4997
I'm not sure where `mdx.Fragment` comes from—possibly from MDX v2? But I've simply reverted to the behavior before when we had no pragma.
Deploy preview: https://deploy-preview-7392--docusaurus-2.netlify.app/tests/pages/markdownPageTests/#details

fix(mdx-loader): use React.Fragment as fragment factory

---

.github/dependabot.yml
admin/publish.md
lerna.json

The name "tag:" is a bit confusing, because "tag" also refers to the git tags for each release. Using "pr:" eliminates the ambiguity.
I've also elaborated in the release docs about how labeling should happen.

chore: use "pr:" prefix for changelog labels; elaborate on labeling process

---

website/docs/api/docusaurus.config.js.md

To improve the docs quality for translation.

docs: fix translation config example

---

packages/docusaurus/src/client/exports/ComponentCreator.tsx

While debugging https://github.com/facebook/docusaurus/issues/7238, I noticed our 404 page is not code-splitted properly. Although I think it's still does its work, let's make it more correct.
This still does not fix that issue though, I will need to look deeper into it.
Deploy preview: https://deploy-preview-7405--docusaurus-2.netlify.app/foo

refactor(core): properly code-split NotFound page

---

packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Category.tsx

Auto collapse sidebar categories when navigating via paginator. Trying to fix https://github.com/facebook/docusaurus/issues/7387
Deploy preview: https://deploy-preview-7411--docusaurus-2.netlify.app/
https://github.com/facebook/docusaurus/issues/7387

fix(theme-classic): autocollapse sidebar categories when navigating with paginator

---

packages/docusaurus-plugin-pwa/src/registerSw.ts
packages/docusaurus-plugin-pwa/src/renderReloadPopup.tsx
packages/docusaurus-plugin-pwa/tsconfig.browser.json
packages/docusaurus-plugin-pwa/tsconfig.server.json

#5817
No code changes; only fixed a few little bugs

refactor(pwa): migrate client modules to TS

---

packages/docusaurus/package.json
packages/docusaurus/src/client/serverEntry.tsx

fix(core): avoid using logger and fs.readJSON in SSR

---

packages/docusaurus-utils/src/__tests__/__snapshots__/markdownLinks.test.ts.snap
packages/docusaurus-utils/src/__tests__/markdownLinks.test.ts
packages/docusaurus-utils/src/markdownLinks.ts

Fix problem reported by @nikitavoloboev on Discord.
Added a test

fix(utils): avoid replacing Markdown links missing the directly next link

---

packages/docusaurus-utils/src/__tests__/__snapshots__/markdownLinks.test.ts.snap
packages/docusaurus-utils/src/__tests__/markdownLinks.test.ts
packages/docusaurus-utils/src/markdownLinks.ts

Fix a long-standing edge case.

fix(utils): fix Markdown link replacement when link text is same as href

---

admin/scripts/formatLighthouseReport.js
packages/create-docusaurus/tsconfig.json
packages/docusaurus-migrate/tsconfig.json
packages/docusaurus-plugin-content-docs/src/client/index.ts
packages/docusaurus-plugin-pwa/src/registerSw.ts
packages/docusaurus-theme-translations/tsconfig.json
packages/docusaurus/tsconfig.json
tsconfig.json
website/community/4-canary/Versions.tsx
website/docusaurus.config.js
website/src/components/APITable/index.tsx
website/src/components/ColorGenerator/index.tsx
website/src/components/UpgradeGuide/index.tsx
website/src/pages/index.tsx
website/src/theme/theme.d.ts
website/src/utils/colorUtils.ts
website/tsconfig.json

Again, using type-aware linting requires the root tsconfig to include all files (else we would need to create a TS Program for every package, which absolutely OOMs). However, the website folder uses a different tsconfig that doesn't extend the root. In this case, I've separated the website project out so it's type-checked alone, unaffected by the root.
The `__tests__` files still don't typecheck. However, now when you exclude them from the root tsconfig, there aren't any type errors when you run `yarn tsc` at the root, only a few reports about `export =`, because in this single-run tsc, `module` is set to `esnext`.

refactor: make entire project typecheck with root tsconfig

---

jest/deps.d.ts
packages/docusaurus-cssnano-preset/src/remove-overridden-custom-properties/__tests__/index.test.ts
packages/docusaurus-migrate/src/index.ts
packages/docusaurus-migrate/src/types.ts
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-theme-common/src/utils/reactUtils.tsx
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.tsx
packages/docusaurus-utils-validation/src/__tests__/validationUtils.test.ts
packages/docusaurus/src/client/PendingNavigation.tsx
packages/docusaurus/src/commands/deploy.ts
packages/docusaurus/src/commands/swizzle/__tests__/index.test.ts
packages/docusaurus/src/server/plugins/__tests__/index.test.ts
website/docs/api/plugins/plugin-content-docs.md
website/docs/api/plugins/plugin-pwa.md
website/docs/guides/markdown-features/markdown-features-toc.mdx

Reduce number of implicit `any`'s. Final one from the last 5 PRs.

test: strengthen internal types

---

packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.ts
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/Navbar/Content/index.tsx
packages/docusaurus-theme-classic/src/theme/Navbar/Search/index.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/SearchNavbarItem.tsx
packages/docusaurus-theme-classic/src/validateThemeConfig.ts
website/docs/api/themes/theme-configuration.md

- Could not find any tests for these changes. Please correct me if I am wrong.
Please refer to this issue comment
https://github.com/facebook/docusaurus/pull/7164#issuecomment-1118221792
I tried to use `yarn lerna link` and linked it in a new setup project but still got `[ERROR] ValidationError: "navbar.items[0].className" is not allowed` although it has been added to the Joi validation schema. I might need help on this part (cc: @slorber)
Deploy preview: https://deploy-preview-7357--docusaurus-2.netlify.app/
New changes: https://deploy-preview-7357--docusaurus-2.netlify.app/docs/api/themes/configuration#navbar-search

feat(theme-classic): allow className as option for type: "search"

---

website/_dogfooding/README.md
website/_dogfooding/docs-tests-symlink
website/_dogfooding/dogfooding.config.js

fixes `yarn start`, from @Josh-Cena

misc: avoid using fs.realpathSync in website

---

packages/docusaurus/src/commands/serve.ts
packages/docusaurus/src/commands/start.ts

When you type `npm run serve`, Docusaurus will output the following text to your terminal:
```
[SUCCESS] Serving "docs" directory at http://localhost:3000/.
```
The next step at this point is to copy the text from the terminal, and then paste it into your browser.
However, the trailing period interferes with this, as it is not part of the URL. and makes it difficult to properly copy the intended text. Thus, this PR.
Related:
When doing `npm run start`, the page automatically opens in your browser, which is helpful.
Why doesn't this behavior also apply to `npm run serve`?

fix: avoid printing period after localhost URL

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-theme-classic/src/theme/Layout/index.tsx
packages/docusaurus/src/client/App.tsx
packages/docusaurus/src/client/exports/ErrorBoundary.tsx
website/docs/docusaurus-core.md

Re-do #7368, after @slorber pointed out about performance issues.
The problem still stands: we needs to be clear whether the prop is a callback to be called, or a component to be rendered with JSX. We cannot have a mix of both.

fix(core): always treat error boundary fallback as a callback

---

packages/create-docusaurus/package.json
packages/create-docusaurus/src/index.ts
packages/docusaurus-utils/src/__tests__/shellUtils.test.ts
packages/docusaurus-utils/src/gitUtils.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus-utils/src/shellUtils.ts
project-words.txt

ShellJS args must be escaped to prevent possible malicious command injections in create-docusaurus
unit + locally
These 3 should work fine:
```sh
rm -rf website/build/test && yarn create-docusaurus website/build/test https://github.com/slorber/docusaurus-starter
rm -rf website/build/test && yarn create-docusaurus website/build/test 'https://github.com/slorber/docusaurus-starter'
rm -rf website/build/test && yarn create-docusaurus 'website/build/test' 'https://github.com/slorber/docusaurus-starter'
```
But these should not allow executing malicious input:
```sh
rm -rf website/build/test && yarn create-docusaurus 'website/build/test$(say hello)' https://github.com/slorber/docusaurus-starter
rm -rf website/build/test && yarn create-docusaurus website/build/test …
```

fix(create-docusaurus): potential security issue with command injection

---

packages/docusaurus-plugin-pwa/src/index.ts
packages/docusaurus-plugin-pwa/src/options.ts
packages/docusaurus-plugin-pwa/src/plugin-pwa.d.ts
packages/docusaurus-plugin-pwa/src/registerSw.ts
packages/docusaurus-plugin-pwa/src/renderReloadPopup.tsx
website/docs/api/plugins/plugin-pwa.md

The `reloadPopup` option of the PWA plugin is removed. If you are using a custom component, consider swizzling `@theme/PwaReloadPopup` instead. If you set it to `false`, consider returning `null` from your component.
The dynamic import used to import the reload popup component has caused problems with server-side rendering due to how Babel/SWC compiles it. See https://github.com/facebook/docusaurus/pull/3742 and https://github.com/facebook/docusaurus/pull/7329 for some struggles. I propose to simply remove this option, because we can leverage swizzling to achieve the same effect.

refactor(pwa): remove reloadPopup option in favor of swizzling

---

packages/docusaurus-plugin-sitemap/src/index.ts
packages/docusaurus-plugin-sitemap/src/options.ts
website/docs/api/plugins/plugin-sitemap.md

See https://docusaurus.canny.io/feature-requests/p/support-multi-instance-sitemaps-plugins
Since sitemap files can be manually uploaded/checked-in, the name is mostly irrelevant.
We don't have tests for this...
Deploy preview: https://deploy-preview-7469--docusaurus-2.netlify.app/docs/api/plugins/@docusaurus/plugin-sitemap/

feat(sitemap): allow customizing the output name

---

packages/docusaurus-plugin-google-gtag/src/gtag.ts
website/_dogfooding/clientModuleExample.ts

Fix https://github.com/facebook/docusaurus/issues/7420
I manually tested it with the [reproduction environment on stackblitz](https://stackblitz.com/edit/github-fab3de?file=plugin%2Fclient-module.js).
I also have on my private project repo this implementation fix of the gtag plugin that I deployed and debuged using GA debug tools.
It can be clearly seen in the logs and in GA debug panel that the correct title is used now.
https://stackblitz.com/edit/github-fab3de?file=plugin%2Fclient-module.js
Deploy preview: https://deploy-preview-7424--docusaurus-2.netlify.app/

fix(gtag): send the newly rendered page's title instead of the old one's

---

packages/create-docusaurus/templates/classic-typescript/package.json
packages/create-docusaurus/templates/classic/package.json
packages/create-docusaurus/templates/facebook/package.json

See #7517 - having the `engines` explicitly stated in the `package.json` rather than a transitive dependency allows tooling like Oryx to install the required minimum node version. See also https://github.com/johnnyreilly/blog.johnnyreilly.com/pull/228 and https://blog.johnnyreilly.com/2022/05/28/azure-static-web-apps-node-16-oryx
See the linked PR moving from failed builds to passing builds as this change is applied.
https://blog.johnnyreilly.com/2022/05/28/azure-static-web-apps-node-16-oryx
See links above

feat: add engines field to templates' package.json

---

packages/docusaurus/package.json
packages/docusaurus/src/deps.d.ts
packages/docusaurus/src/webpack/server.ts
yarn.lock

Upgrade the dependency `@slorber/static-site-generator-webpack-plugin` after some cleanup and a few PRs merged
New `concurrency` option added with env variable. Not documented for now, looking for feedback before.
site builds fine, not slower than before
https://github.com/slorber/static-site-generator-webpack-plugin/pull/2
https://github.com/slorber/static-site-generator-webpack-plugin/pull/3

chore: update static-site-generator-webpack-plugin

---

packages/docusaurus-plugin-google-analytics/src/analytics.ts
packages/docusaurus-plugin-google-gtag/src/gtag.ts

This change will allow page transitions (i.e. changes to the query string and bookmark hash) to be sent to Google Analytics
Ran `yarn serve:website` and verified that GA events are being sent

feat(analytics): allow query/hash changes to be sent to GA

---

package.json
packages/docusaurus/README.md

temp workaround for https://github.com/npm/cli/issues/4619 until we use a newer node/npm version in CI matrix without this bug
Already attempted in https://github.com/facebook/docusaurus/pull/7167 : we can now try again thanks to Node 16 upgrade

chore: use npx --yes

---

.github/workflows/build-perf.yml
.github/workflows/tests-e2e.yml
.github/workflows/tests-windows.yml
.github/workflows/tests.yml

CI not triggering when it should
See also https://github.com/facebook/docusaurus/pull/7549#issuecomment-1144746590

chore: update CI trigger paths

---

packages/docusaurus-theme-classic/src/__tests__/validateThemeConfig.test.ts
packages/docusaurus-theme-classic/src/theme/Footer/Logo/index.tsx
packages/docusaurus-theme-classic/src/validateThemeConfig.ts
packages/docusaurus-theme-common/src/utils/useThemeConfig.ts

In the current documentation, it says **_Customization of the logo object. See [Navbar logo](https://docusaurus.io/docs/api/themes/configuration#navbar-logo) for details_**, but it's not allowed to add a footer logo target. 
This issue has been raised before in this PR #2344, it's available to specify a target only for the navbar logo. 
It would be great if it works for the footer logo as well. 
- Set the external link for the `footer.logo.href` property, and set the `footer.logo.target` property to "_self" - make sure that the external link opens in the current tab. This use case is the main goal of PR.
- #2344

feat: allow specifying custom target for FooterLogo

---

website/docs/advanced/ssg.md
website/docs/api/plugins/plugin-debug.md
website/docs/guides/docs/sidebar/items.md
website/docs/guides/docs/versioning.md
website/docs/guides/markdown-features/markdown-features-assets.mdx
website/docs/guides/markdown-features/markdown-features-code-blocks.mdx
website/docs/i18n/i18n-tutorial.md

If we don't do this, we can't translate the tab headings because they aren't visible on Crowdin.

docs: wrap more JSX in mdx-code-block

---

.eslintrc.js
packages/docusaurus-mdx-loader/src/remark/admonitions/index.ts
packages/docusaurus-mdx-loader/src/remark/transformImage/index.ts
packages/docusaurus-mdx-loader/src/remark/transformLinks/index.ts
packages/docusaurus-migrate/bin/index.mjs
packages/docusaurus-plugin-content-docs/src/__tests__/lastUpdate.test.ts
packages/docusaurus-plugin-content-docs/src/lastUpdate.ts
packages/docusaurus-plugin-pwa/src/registerSw.ts
packages/docusaurus-plugin-pwa/src/renderReloadPopup.tsx
packages/docusaurus-theme-classic/src/theme/Admonition/index.tsx
packages/docusaurus/bin/docusaurus.mjs
website/_dogfooding/clientModuleExample.ts
website/docs/api/plugins/plugin-pwa.md
website/src/components/Versions.tsx

Before we aggressively bump our browserslist to _only_ support modern browsers, or before IE11 dies out from the default browserslist inclusion, we must not use async-await in the client bundle to reduce bundle size.
Floating promises are a problem if async-await is not used; however, this can be greatly remedied by using TS-ESLint's `no-floating-promises` rule. We are still not ready to enable type-aware lint rules in CI, but I'm already working with it locally.
As a side-fix, I've fixed some new ESLint errors as they emerged after the recent code changes.

refactor(pwa): simplify registerSW code, fix ESLint errors

---

packages/docusaurus/src/client/PendingNavigation.tsx

Fixes #7599 
1. Build the site
2. Do `yarn run serve`
3. Load https://localhost:3000
4. Kill the server
5. Try to navigate, the page will immediately refresh and show the browser's error page. Previously it won't because we're using client-side navigation and just fail silently with an infinite loading bar

fix: force refresh on chunk preload error

---

packages/create-docusaurus/templates/shared/docs/intro.md
website/docs/deployment.mdx

Node 14 is definitely not good, and let's just go with Node 18. If we can—why not? 

docs: advise using Node 18 in deployment

---

packages/docusaurus/src/client/serverEntry.tsx
website/docs/cli.md

The current build process is "optimizing" the HTML in a way that breaks bootstrap. More specifically, it removes some "worthless" attributes (such as `type="text"` from `input` fields), which breaks Bootstrap's `[type="text"]` selectors (probably selectors of other css frameworks aswell).
This change will allow users to specify the exact options that they want to be passed to the minifier. It won't introduce any breaking changes since it's merging the existing opts with any user-provided opts.
N/A
* https://deploy-preview-7581--docusaurus-2.netlify.app/docs/api/docusaurus-config/#buildConfig
N/A

feat(core): allow opting out of HTML minification

---

packages/docusaurus/bin/docusaurus.mjs
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/clear.ts
packages/docusaurus/src/commands/deploy.ts
packages/docusaurus/src/commands/external.ts
packages/docusaurus/src/commands/serve.ts
packages/docusaurus/src/commands/start.ts
packages/docusaurus/src/commands/swizzle/__tests__/index.test.ts
packages/docusaurus/src/commands/swizzle/index.ts
packages/docusaurus/src/commands/writeHeadingIds.ts
packages/docusaurus/src/commands/writeTranslations.ts

The reason is because the commander functions are very weakly typed: basically `action(fn: (...args: any[]) => void | Promise<void>)`. This makes TS-ESLint whine about unsafe arguments when we pass these `any` into our actual function, even when it's actually safe.
This also means people who try to use these functions on Node side do not immediately get feature parity with the CLI: they have to resolve site directory, they have to apply default values (see also #7220), they have to even change the order of parameters.
We should just handle these ourselves. The CLI is just a very thin wrapper that automatically invokes these functions. Now users can do `await docusaurus.build();` without passing any arguments.

refactor(cli): make the CLI an even thinner wrapper around command functions

---

packages/docusaurus-utils/src/__tests__/markdownUtils.test.ts
packages/docusaurus-utils/src/markdownUtils.ts
website/_dogfooding/_pages tests/markdownPageTests.md

fix(utils): allow any non-boundary characters in Markdown heading ID

---

packages/docusaurus-theme-classic/src/theme/MDXPage/index.tsx

When I create a simple page according to [this](https://docusaurus.io/docs/creating-pages), the content is not wrapped in an `<article>` tag... therefore it's also not indexed through the [default configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/docusaurus-2.json) that I've found.

fix(content-pages): add article wrapper around MDXContent

---

packages/docusaurus-logger/README.md
packages/docusaurus-logger/src/__tests__/index.test.ts
packages/docusaurus-logger/src/index.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus-utils/src/__tests__/jsUtils.test.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus-utils/src/jsUtils.ts
packages/docusaurus/src/server/__tests__/__snapshots__/configValidation.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/brokenLinks.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/server/routes.ts
website/docs/api/docusaurus.config.js.md
website/docs/api/misc/logger/logger.md

- "error" reporting level is removed in favor of "throw"
- the `reportMessage` API (internal but maybe used by some?) has been moved/renamed
As discussed in https://github.com/facebook/docusaurus/issues/7615, removing the "error" reporting severity to avoid confusion for the users. I've actually been asked similar questions on Discord...
I took this chance to move `reportMessage` to `logger`, to make it appear more uniform, and also to take advantage of the interpolate function.

refactor: remove "error" reporting level, move reportMessage to logger

---

packages/docusaurus-theme-common/src/utils/__tests__/reactUtils.test.ts
packages/docusaurus-theme-common/src/utils/reactUtils.tsx

Complete a TODO.
Added a few more tests.

fix(theme-common): make useShallowMemoObject key-order-insensitive

---

packages/docusaurus-plugin-client-redirects/src/__tests__/collectRedirects.test.ts
packages/docusaurus-plugin-client-redirects/src/collectRedirects.ts
packages/docusaurus-plugin-client-redirects/src/index.ts
packages/docusaurus-plugin-client-redirects/src/types.ts
website/docs/api/plugins/plugin-client-redirects.md

feat(client-redirects): make plugin respect onDuplicateRoutes config

---

packages/docusaurus-theme-classic/src/theme/Logo/index.tsx
website/docusaurus.config.js

Resolves #7658
Allowing users to supply `alt=""` (distinct from _no_ alt/undefined alt) for their navbar brand link logos can enable users to reduce clutter in screenreader announcements. However, as it currently stands, when an empty string is provided for a logo alt, Docusaurus falls back to the provided navbar title or the site title.
This pull request ensures that if a Docusaurus config provides `alt: ''` for a logo, that empty string is respected, so Docusaurus users can confidently mark their logos as decorative and reduce duplicated announcements.
Create a fresh Docusaurus site. In the Docusaurus config, update the `navbar.logo.alt` config to be an empty string. Build the site. Verify that the logo element has `alt=""` (may show up as simply `alt` in some browser devtools). …

fix: expose empty string alt text in navbar logos

---

.gitignore
.vscode/extensions.json
project-words.txt

I've found it hugely helpful when some repos share their `extensions.json` so that first-time contributors can quickly set up a decent development environment. I've added a few for now, but I think people can feel free to add things to this list over time.
Ideally, we would share `settings.json` and `launch.json` as well, but I don't have those configured myself, so deferring to the future.

misc: share .vscode/extensions.json

---

packages/docusaurus-theme-common/src/hooks/useMutationObserver.ts
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/historyUtils.ts
packages/docusaurus-theme-common/src/utils/reactUtils.tsx
packages/docusaurus-theme-common/src/utils/scrollUtils.tsx
packages/docusaurus-theme-common/src/utils/useLocationChange.ts
packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.tsx

Follow-up of https://github.com/facebook/docusaurus/pull/7660
Rename useDynamicCallback to useEvent as it's more likely to be named that way in React core (see https://github.com/reactjs/rfcs/pull/220)
Not considering this as a breaking change considering we just created the public API surface (+ it's mostly used internally in theme-common)

refactor(theme-common): rename useDynamicCallback to useEvent

---

project-words.txt
website/docs/deployment.mdx

Reading the guide on setting up a cross-repo deployment with Github Action is missing some key information to be successful.
This PR is adding the relevant information and the steps of the things you need to do where you have to do them.
Also changed `xclip` command to `pbcopy` which is more popular, simpler and reflects what GitHub's documentation is recommending.

docs: add more info on github cross repo deployment

---

packages/docusaurus-theme-classic/src/index.ts
packages/docusaurus/src/client/BaseUrlIssueBanner/index.tsx

Permits to get syntax highlighting in Intellij on some strings containing code.
This is proprietary and not ideal, afaik not supported by VSCode with this syntax (see also https://github.com/0x00000001A/es6-string-html/issues/49)

misc: add IDE language annotation comments

---

jest.config.mjs
package.json
packages/docusaurus-logger/package.json
packages/docusaurus-logger/src/__tests__/index.test.ts
yarn.lock

I noticed that ansi escape sequences are included in snapshots of `@docusaurus/logger` tests. Recently I wrote a [snapshot serializer](https://github.com/mrazauskas/jest-serializer-ansi-escapes) which is replacing the sequences with human readable strings. For example, `'\u001b[3;32mSuccess!\u001b[0m'` gets snapshotted as `'<italic, green>Success!</>'`.
Just though – perhaps you will find it useful? After using the plugin in a couple of projects, it felt to me that the improved readability helps to maintain snapshots. Of course, in the end the same output is snapshotted.
---
`jest-serializer-ansi-escapes` is inspired by [`ConvertAnsi`](https://github.com/facebook/jest/blob/main/packages/pretty-format/src/plugins/ConvertAnsi.ts) plugin which ships with `pretty-format` and is bundled with …

test(logger): use `jest-serializer-ansi-escapes`

---

packages/docusaurus-theme-translations/locales/vi/plugin-ideal-image.json

fix(theme-translations): typo in vi locale

---

website/docs/guides/markdown-features/markdown-features-react.mdx

Fix #7698
Deploy preview: https://deploy-preview-7705--docusaurus-2.netlify.app/docs/markdown-features/react/#mdx-component-scope

docs: mention MDXContent

---

website/docs/deployment.mdx

Deploying to GitHub pages is so popular, yet there are so many pitfalls to avoid. Adding a troubleshooting guide helps save my time as a helper.

docs: add GitHub pages deployment troubleshooting guide

---

.devcontainer/devcontainer.json

I decited to bump this version because I've tried to open this repo in a Remote-Container in vscode and got the error that you need at least NodeJS 16.
I've rebuilded the devcontainer and it worked without any errors.
Deploy preview: https://deploy-preview-7726--docusaurus-2.netlify.app/

chore: bump devcontainer to node 18

---

packages/docusaurus-theme-classic/src/theme/BlogPostItem/index.tsx

I was investigating why I didn't get the `EditThisPost` link. I figured that it was because by default the button renders when it's either truncated or one or more tag exists. However, when `editUrl` is set, the button should render even when post is not truncated nor there is no tags.
None

fix(theme): show blog post edit link even when no tag & not truncated

---

packages/docusaurus/src/client/exports/ExecutionEnvironment.ts

This is better because the `has` check may be proxified differently from a `get` check. We should always use `has` for existence.

refactor(core): use has instead of get to test for existence in ExecEnv

---

packages/docusaurus-theme-classic/src/__tests__/options.test.ts
packages/docusaurus-theme-classic/src/index.ts
packages/docusaurus-theme-classic/src/options.ts
packages/docusaurus-theme-classic/src/theme-classic.d.ts
website/docs/api/themes/theme-classic.md

I realized we have never been validating the theme options all this time...

fix(theme-classic): validate options properly

---

packages/docusaurus/src/commands/deploy.ts

This reverts commit ee376d19f6c5f2dd714c94941901665d2ce174a5.
All git config fields can be set via the GIT_CONFIG_KEY_<n> and GIT_CONFIG_VALUE_<n> env vars.
Ref: https://git-scm.com/docs/git-config#Documentation/git-config.txt-GITCONFIGCOUNT
Alternatively, you can also use the conditional includes feature of git config.
Ref: https://git-scm.com/docs/git-config#_conditional_includes
closes #7744

fix(deploy): revert "feat(deploy): copy local git config to tmp repo (#7702)"

---

packages/docusaurus-theme-classic/package.json
yarn.lock

Fix https://github.com/facebook/docusaurus/issues/7748
See also https://github.com/facebookincubator/infima/pull/268

chore: bump Infima to 0.2.0-alpha.42, fix a:hover link bug

---

packages/docusaurus-plugin-sitemap/src/__tests__/createSitemap.test.ts
packages/docusaurus-plugin-sitemap/src/createSitemap.ts
packages/docusaurus-plugin-sitemap/src/index.ts

fix(sitemap): complete gracefully when all pages have noIndex meta

---

.github/workflows/build-blog-only.yml
.github/workflows/build-perf.yml
.github/workflows/canary-release.yml
.github/workflows/codeql-analysis.yml
.github/workflows/lighthouse-report.yml
.github/workflows/lint.yml
.github/workflows/showcase-test.yml
.github/workflows/tests-e2e.yml
.github/workflows/tests-swizzle.yml
.github/workflows/tests-windows.yml
.github/workflows/tests.yml

chore: ci tests should run on version branches "docusaurus-vX"

chore: ci tests should run on version branches "docusaurus-vX"

---

packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Category/index.tsx

When clicking on first section other section will not collapse.
`expandedItem` when it is equal to `0` is a falsy value. Therefore that `useEffect` will not produce any effect. I've changed it to checking of `expandedItem != null` in order to ensure that effect will not happen only when expanded item is `null` or `undefined.` 
There is none

fix: collapse siblings when first category is selected

---

website/docs/deployment.mdx
website/versioned_docs/version-2.0.0-beta.22/deployment.mdx
website/versioned_docs/version-2.0.0-rc.1/deployment.mdx

To keep consistency with the UI in Netlify:
- modify `build directory` to `publish directory`
- modify `Build and deploy` to `Build & deploy`
Deploy preview: https://deploy-preview-7796--docusaurus-2.netlify.app/

docs: modify the description of deploying to Netlify

---

website/community/5-release-process.md
website/docs/deployment.mdx

The link to the public API surface had an erroneous extra # in the link
preventing it from linking correctly.
- [/] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [/] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [/] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.
Fix a bug in the docs
View /community/release-process#major-versions and attempt to follow the link in the first admonition to the "Public API surface"
- https://docusaurus.io/community/release-process#major-versions
- Deploy preview: …

docs: fix anchor link

---

admin/scripts/resizeImage.js
website/src/data/users.tsx
website/src/pages/showcase/index.tsx

We are changing the way showcase sites are submitted: instead of users submitting a PR themselves, we just ask them to post a GitHub comment in https://github.com/facebook/docusaurus/discussions/7826
This have several benefits:
- it makes it easier for site owners to get their site added, 
- it does not require signing the Facebook CLA (which may sometimes be more complicated for companies)
- it avoids the creation of too many PRs not directly related to Docusaurus changes
- it saves a lot of time for the Docusaurus maintainers

misc: change showcase submission process, use GitHub discussion

---

packages/create-docusaurus/templates/facebook/.eslintrc.js
packages/create-docusaurus/templates/facebook/.stylelintrc.js
packages/create-docusaurus/templates/facebook/babel.config.js
packages/create-docusaurus/templates/facebook/docusaurus.config.js
packages/create-docusaurus/templates/facebook/sidebars.js
packages/create-docusaurus/templates/facebook/src/css/custom.css
packages/create-docusaurus/templates/facebook/src/pages/index.js
packages/create-docusaurus/templates/facebook/src/pages/styles.module.css

Our internal copyright header requirements have changed.
Run Eslint in the facebook template

chore: update FB template headers

---

.eslintrc.js
packages/docusaurus-theme-classic/src/nprogress.ts
packages/docusaurus-theme-classic/src/theme/DocCard/index.tsx
packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.tsx
packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.tsx
packages/stylelint-copyright/src/index.ts
project-words.txt
website/src/pages/index.tsx

In previous PR #7849, I found there is a bug when importing a `CSS` file after importing a type from `@docusaurus/type`.
At first, we (with the maintainer) are guessing the problem is caused by my system environment. But later I did a lot of checks, and came to realize that it's not.
Just adding one extra ruler in order to force CSS to be imported at last:
```js
// .eslintrc.js
{
pattern: '*.css', // or '*.+(css|sass|less|scss|pcss|styl)' for general match
patternOptions: {matchBase: true},
group: 'unknown',
position: 'after',
}
```
I'd think it unnecessary although it may work well using an extra plugin of [`eslint-plugin-css-import-order`](https://www.npmjs.com/package/eslint-plugin-css-import-order).
As mentioned from #7849, we can do a simple test.
TIPS:
- `grep -irE "import.*\.css" …

chore: fix CSS import order ESLint rule

---

website/docs/api/plugins/plugin-pwa.md
website/versioned_docs/version-2.0.0-beta.22/api/plugins/plugin-pwa.md

updated link does not show reference to workbox
Old Link: https://developer.chrome.com/docs/workbox/reference/#.injectManifest
New Link: https://developer.chrome.com/docs/workbox/reference/workbox-webpack-plugin/#type-InjectManifest

docs: update workbox doc link

---

packages/docusaurus-utils/src/__tests__/globUtils.test.ts
packages/docusaurus-utils/src/globUtils.ts
packages/docusaurus-utils/src/jsUtils.ts
packages/docusaurus-utils/src/pathUtils.ts
packages/docusaurus-utils/src/urlUtils.ts

Issue surfaced in https://github.com/facebook/docusaurus/pull/7862

fix(utils): always match exclusion root dirs as complete folder paths

---

website/blog/2022-08-01-announcing-docusaurus-2.0/index.mdx
website/src/components/HackerNewsIcon.tsx
website/src/pages/index.tsx

Update links for the launch
Linking to index page gives a better scoring per upvote but we are already underperforming on HN so let's link directly to the item otherwise users won't find the entry.

docs: update Hacker News + Product Hunt links

---

website/docs/typescript-support.md

Without base url, TS errors appear such as `Cannot find module '@site/src/components/...`

docs: add baseUrl to example tsconfig

---

packages/docusaurus-theme-classic/src/theme/Tag/styles.module.css

The tag content was visually offset which looked out of place. This fixes it.
Manually verified.
| Before | After |
| --- | --- |
| ![Screenshot 2022-08-01 at 15 36 46](https://user-images.githubusercontent.com/6379824/182160364-267e96ac-4ff5-4023-814f-cc2dcabd0111.png) | ![Screenshot 2022-08-01 at 15 36 35](https://user-images.githubusercontent.com/6379824/182160402-24df2a3b-4260-4987-b953-52aad11b4658.png) |

refactor(theme-classic): make tag text visually certered

---

packages/docusaurus-mdx-loader/src/remark/admonitions/README.md

readme link targets the wrong repo

chore: bad remark-admonition readme link

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/LocaleDropdownNavbarItem/index.tsx
packages/docusaurus-types/src/i18n.d.ts
website/docs/api/docusaurus.config.js.md

Apparently, this improves accessibility a bit, and also helps SEO crawlers
https://twitter.com/mgechev/status/1518447256034238464
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang
https://www.w3schools.com/tags/att_global_lang.asp
---
Note: wonder if we shouldn't also use it for localized sites where some docs are not translated yet 🤷‍♂️ I guess the lang of a doc in such case is not the lang of the i18n site (as the doc is actually not translated) but the default locale instead

feat(theme-classic): use lang attribute in navbar locale dropdown items

---

packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/CloseButton/index.tsx
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/CloseButton/styles.module.css
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/Content/index.tsx
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/Content/styles.module.css
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/index.tsx
packages/docusaurus-theme-classic/src/theme/AnnouncementBar/styles.module.css

- Split theme AnnouncementBar component: extract CloseButton + Content.
- Use z-index to make it render just above the navbar
- Use shadow instead of border-bottom (requiring the z-index change to work)
Note: I didn't extract a Layout/Container component as it wasn't very easy to design those properly without introducing some extra dom nodes. 
preview vs prod (almost not visible in dark mode), subtle changes only: shadow instead of border + 1px additional space.
Before:
After:
Deploy preview: https://deploy-preview-7940--docusaurus-2.netlify.app/
https://github.com/facebook/docusaurus/discussions/7827

refactor(theme-classic): split AnnouncementBar, increase z-index, use shadow

---

packages/docusaurus-plugin-sitemap/src/__tests__/createSitemap.test.ts
packages/docusaurus-plugin-sitemap/src/createSitemap.ts
website/docs/seo.md
website/src/pages/examples/noIndex.md

Bug: 
This page meta leads to the page being filtered correctly from sitemap.xml:
```html
<head>
<meta name="robots" content="noindex" />
</head>
```
But with this page meta, the page stays in sitemap.xml
```html
<head>
<meta name="robots" content="noindex, nofollow" />
</head>
```
Both pages should be filtered consistently.
Also Robots meta directives are case insensitive (https://developers.google.com/search/docs/advanced/robots/robots_meta_tag#directives)
Adding an example and improving our SEO doc a little
unit tests
Compared preview sitemap with a previous preview sitemap and didn't notice anything wrong
Deploy preview: 
- https://deploy-preview-7964--docusaurus-2.netlify.app/sitemap.xml
- https://deploy-preview-7964--docusaurus-2.netlify.app/examples/noIndex
- …

fix(sitemap): filter all routes with robots meta containing noindex

---

packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/options.test.ts
packages/docusaurus-plugin-content-docs/src/options.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-docs/src/props.ts
packages/docusaurus-plugin-content-docs/src/versions/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/versions/index.ts
packages/docusaurus-theme-classic/src/theme/DocPage/index.tsx
website/_dogfooding/dogfooding.config.js
website/docs/api/plugins/plugin-content-docs.md
website/docusaurus.config.js

You might want to prevent crawlers and google to index older versions of your docs
See also https://github.com/facebook/docusaurus/discussions/7960
unit tests + local tests + dogfood on test docs instance (as it's not really useful to index it)
Deploy preview: 
- https://deploy-preview-7963--docusaurus-2.netlify.app/tests/docs
- https://deploy-preview-7963--docusaurus-2.netlify.app/sitemap.xml
---
Limitation: the versioned docs tag pages won't be noIndexed. But a further refactor will fix it soon.

feat(docs): allow to configure noIndex per doc version

---

packages/docusaurus-plugin-content-docs/package.json

I hope that is OK that I deleted half of the template, as it would mostly duplicate #7961. 
---
@Josh-Cena This would be out of scope of this PR, but I noticed that there are `exports` in `theme-common` and `theme-search-algolia` as well, to make it consistent should we add this line there as well?

chore(plugin-docs): expose all lib files through exports

---

.github/workflows/tests-e2e.yml
admin/verdaccio.yaml

I've notice master fails with `E503 one of the uplinks is down, refuse to publish`, this happens because on publish first check on internet if the version of this package exist, for E2E this should not be required. I'm trying to improve the master branch builds.
By adding a new block for `@docusaurus/*` avoid check any uplink and also the property `allow_offline` avoid any check with internet on publish (this is handy if the connection is dropped so avoid network issues)
> I had to add an additional block for `@docusaurus/react-loadable` because this package is not part of this monorepo, while the order in the `packages` section matters, should be on the top of `@docusaurus/*`.
The CI build: https://github.com/facebook/docusaurus/runs/7881520546?check_suite_focus=true
```
lerna notice …
```

test: improve e2e verdaccio configuration

---

packages/docusaurus/src/commands/start.ts

See https://github.com/facebook/docusaurus/issues/7912 for explanation as to how these changes fix the problem. This does not have any side effects that I am aware of.
Closes https://github.com/facebook/docusaurus/issues/7912

fix(core): make webpack HMR always listen to current location

---

packages/docusaurus-theme-classic/src/theme/SkipToContent/index.tsx

fixes https://github.com/facebook/docusaurus/issues/7981

fix(theme): add aria-label to skip to content link region

---

packages/docusaurus/src/client/preload.ts

Similar to https://github.com/facebook/docusaurus/pull/4407, when containing encoded chars (like whitespace, cn) "preload" won't work, and thus the page will blink (first render as static html, then empty, then after js loaded async render page again), and break the behavior that jumping to doc content with url hash  `#`.
Wish to provide unit test, but stuck during initializing dev env. The code is simple, and is tested in my own repo.
A playground to show the problem: https://codesandbox.io/s/frosty-curran-rsoubc?file=/docs/%E5%85%A5%E9%97%A8%E4%BB%8B%E7%BB%8D.md. Visit `/docs/入门介绍` and debug `client/preload.js` file. `preload` func won't match the extract route.
Deploy preview: https://deploy-preview-7977--docusaurus-2.netlify.app/
https://github.com/facebook/docusaurus/pull/4407

fix(core): preload should support encoded page links

---

website/src/data/__tests__/user.test.ts
website/src/data/users.tsx
website/src/pages/showcase/_components/ShowcaseCard/index.tsx

Add all new showcase submissions above comment https://github.com/facebook/docusaurus/discussions/7826#discussioncomment-3483070
---
FYI we are moving site screenshots to a serverless screenshot service.
```
https://slorber-api-screenshot.netlify.app/<siteUrl>/showcase
```
For example: [https://slorber-api-screenshot.netlify.app/https%3A%2F%2Fdocusaurus.io%2F/showcase](https://slorber-api-screenshot.netlify.app/https%3A%2F%2Fdocusaurus.io%2F/showcase)
Will render:
We know about some limitations of the screenshot service:
- render unwanted announcement bars, cookie banners
- render spinners, does not wait for some elements to load
- fails to render emojis
- respect or not dark mode
- ...
We are going to ship it as is for now, and improve it over time so that all sites in our showcase …

docs(showcase): add 74 new showcase sites

---

packages/docusaurus-preset-classic/src/index.ts

By running docusaurus with unrecognized keys inside the preset classic configuration, an error is displayed with a link to the documentation:
The provided link ([https://docusaurus.io/docs/presets#docusauruspreset-classic](https://docusaurus.io/docs/presets#docusauruspreset-classic)) leads to a `Page not Found` on the documentation: 
As the `preset` page doesn't exist anymore, it would make sense to replace the previous link with this one: [https://docusaurus.io/docs/using-plugins#docusauruspreset-classic](https://docusaurus.io/docs/using-plugins#docusauruspreset-classic)
Deploy preview: https://deploy-preview-8029--docusaurus-2.netlify.app/

fix(preset-classic): broken link in "unrecognized keys" error message

---

packages/docusaurus/src/server/routes.ts

refactor(core): detect if codegen should quote property without using eval()

---

website/docs/guides/markdown-features/markdown-features-react.mdx

Seems like there is one unnecessary semicolon in MDX and React documentation page. I was copy-pasting that example and saw the semicolon rendered in a page.
By the way, very cool feature!
This change makes the example copy-pastable.
I was copy-pasting code from the example and saw an extra semicolon rendered in a page. Removing it from MD file solved the issue.

docs: delete extra semicolon in MDX and React page

---

packages/docusaurus-logger/README.md
website/blog/2017-12-14-introducing-docusaurus.md
website/blog/2018-04-30-How-I-Converted-Profilo-To-Docusaurus.md
website/blog/2018-12-14-Happy-First-Birthday-Slash.md
website/blog/2020-01-07-tribute-to-endi.md
website/blog/2021-01-19-docusaurus-2020-recap.md
website/blog/2021-03-09-releasing-docusaurus-i18n.md
website/blog/2021-05-12-announcing-docusaurus-two-beta/index.md
website/blog/2021-11-21-algolia-docsearch-migration/index.md
website/blog/2022-01-24-docusaurus-2021-recap/index.md
website/docs/api/docusaurus.config.js.md
website/docs/api/misc/logger/logger.md
website/docs/api/plugins/plugin-pwa.md
website/docs/introduction.md
website/versioned_docs/version-2.0.1/api/docusaurus.config.js.md
website/versioned_docs/version-2.0.1/api/misc/logger/logger.md
website/versioned_docs/version-2.0.1/api/plugins/plugin-pwa.md
website/versioned_docs/version-2.0.1/introduction.md
website/versioned_docs/version-2.1.0/api/docusaurus.config.js.md
website/versioned_docs/version-2.1.0/api/misc/logger/logger.md
website/versioned_docs/version-2.1.0/api/plugins/plugin-pwa.md
website/versioned_docs/version-2.1.0/introduction.md

I was working on MDN's image alts, and I was greatly inspired. The idea is that it should fully describe what the image is about to someone who can't see the image — imagine you don't have internet. See https://github.com/mdn/mdn-community/discussions/168
Also, decorative images should not have alt texts at all.

docs: improve alt messages

---

website/docs/api/plugins/plugin-content-docs.md

Documents null value behaviour for `custom_edit_url` frontmatter.
N/A Docs Only

docs: document usage of docs `frontMatter.custom_edit_url: null`

---

website/docs/api/plugin-methods/lifecycle-apis.md

Grammatical change on line 14
`For example, this plugin below returns a random integer between 1 and 10 as content.`
I wanted to fix a small typo while reading through the docusaurus documentation
N/A
Link to documentation:
https://docusaurus.io/docs/api/plugin-methods/lifecycle-apis#loadContent
Deploy preview: https://deploy-preview-8055--docusaurus-2.netlify.app/docs/api/plugin-methods/lifecycle-apis#loadContent
N/A

docs(content-docs): updates typo in lifecycle-apis.md

---

website/docusaurus.config.js

I broke our website admonitions 😅 
preview
Deploy preview: https://deploy-preview-8060--docusaurus-2.netlify.app/
https://github.com/facebook/docusaurus/pull/7945

fix(website): add website admonitions extendDefaults: true

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/LocaleDropdownNavbarItem/index.tsx
packages/docusaurus-theme-common/src/hooks/useHideableNavbar.ts

`?search#hash` shouldn't be lost when switchiung version or locale through the navbar dropdowns.
A querystring/hash may be used to enable some page-specific behavior that we want to preserve:
- linking to a specific heading
- integration with hash-based routing libs (see https://github.com/facebook/docusaurus/discussions/8057#discussioncomment-3586194)
- opening a specific tab (see https://github.com/facebook/docusaurus/issues/7008)
- other behaviors
preview / dogfood
Deploy preview: 
- https://deploy-preview-8059--docusaurus-2.netlify.app/docs/installation
- https://deploy-preview-8059--docusaurus-2.netlify.app/docs/installation?qs=true
- https://deploy-preview-8059--docusaurus-2.netlify.app/docs/installation?qs=true#build
- https://deploy-preview-8059--docusaurus-2.netlify.app/docs/insta …

fix(theme): preserve url ?search#hash on navbar version/locale dropdowns navigations

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/Line/index.tsx

bug still appears if showLineNumbers is true
#5663 #5668

fix(theme): preserve line breaks when copying code with showLineNumbers in Firefox

---

packages/docusaurus-plugin-client-redirects/src/__tests__/__snapshots__/collectRedirects.test.ts.snap
packages/docusaurus-plugin-client-redirects/src/__tests__/collectRedirects.test.ts
packages/docusaurus-plugin-client-redirects/src/collectRedirects.ts

fix(redirect): tolerate trailing slash difference if config is undefined

---

packages/docusaurus-utils-validation/src/validationSchemas.ts
packages/docusaurus/src/server/__tests__/__snapshots__/configValidation.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts

Testing the `SiteMetadata` is a bit unwieldy atm, so I only wrote validation tests.

fix(core): normalize slashes for url/baseUrl instead of throwing

---

packages/docusaurus-theme-classic/src/theme/Tag/styles.module.css

.tagRegular has a fixed 0.5REM border radius - it's the only place I've found that doesn't inherit from `--ifm-global-radius` without a good reason.
Default behaviour here will be no change unless `--ifm-global-radius` is customised in which case tag elements will now inherit.

refactor(theme): remove hard-coded tag border-radius

---

website/docs/i18n/i18n-tutorial.md
website/versioned_docs/version-2.0.1/i18n/i18n-tutorial.md
website/versioned_docs/version-2.1.0/i18n/i18n-tutorial.md

Brought up in https://github.com/facebook/docusaurus/issues/8104. I think this can be explicitly spelled out.

docs: add caveat about using Translate in string contexts

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx

Improve a11y for Tabs component.
manual - Voiceover on MacOS.
https://user-images.githubusercontent.com/64769322/193444240-0a71828b-c56c-4cc7-9fdc-f3e9191c8257.mov
Tab content is only shown after selection (hitting enter).
Compare:
- https://docusaurus.io/docs/markdown-features/tabs
- https://deploy-preview-8161--docusaurus-2.netlify.app/docs/markdown-features/tabs
Closes #8063

fix(theme): do not show tab content when tabbing over it; show after selection only

---

packages/docusaurus-utils/src/__tests__/__fixtures__/build-snap/htmlFile.html
packages/docusaurus-utils/src/__tests__/__fixtures__/build-snap/weird.html.folder/nestedHtmlFile.html
packages/docusaurus-utils/src/__tests__/emitUtils.test.ts
packages/docusaurus-utils/src/emitUtils.ts
website/_dogfooding/_blog tests/2022-10-02-html-slug.md

Before this commit, adding slugs ending in .html to the frontmatter blogs resulted in the build process breaking. This PR fixes this issue
Added Tests for the emitUtils.readOutputHTMLFile function in which the changes were to be made. Sample file also has been added in website/_dogfooding
Deploy preview: https://deploy-preview-8158--docusaurus-2.netlify.app/
Closes #8139

fix(content-blog): make RSS feed generation work with slugs with .html extension

---

packages/docusaurus-utils/src/__tests__/pathUtils.test.ts
packages/docusaurus-utils/src/pathUtils.ts
website/_dogfooding/_docs tests/tests/ascii/folder/æøå.md
website/_dogfooding/_docs tests/tests/ascii/æøå/index.md

Fixes https://github.com/facebook/docusaurus/issues/8124
The issue specifically pertains to index file detection for paths that contain non-ASCII letters (e.g. "æ"). This failed previously, due to a test for non-ASCII characters when normalizing file paths. This test originated in the sindresorhus/slash package, and was copied over when the code was integrated into docusaurus - but doesn't appear to match how Windows works.
See that issue for further discussion, or https://github.com/sindresorhus/slash/issues/19 for discussion on limitation in the originating package. The limitation was removed in the originating package in https://github.com/sindresorhus/slash/pull/20
Updated tests in this repo, and verified by modifying `node_modules` directly in …

fix(utils): remove non-ASCII limitation for path normalization

---

packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts

Currently, a warning is displayed when the URL contains a sub-path but as mentioned at the end of #8159, it makes more sense to display an error. So, I updated the code to display an error instead of a warning. 
I updated unit tests to verify my code.
Related to https://github.com/facebook/docusaurus/pull/8159 and https://github.com/facebook/docusaurus/issues/8116

fix(core): throw error for invalid URL in config file

---

packages/docusaurus/bin/docusaurus.mjs
packages/docusaurus/src/commands/swizzle/common.ts
packages/docusaurus/src/commands/swizzle/context.ts
packages/docusaurus/src/commands/swizzle/index.ts
website/docs/cli.md

My Docusaurus site uses a non-default config location and I am unable to use swizzle.
Because swizzle is not currently working out of the box on main, I've applied [this additional diff](https://gist.github.com/e-im/78a6043393ba43ca0bd0622f90cc77c1) for the sake of the test.
1. Move `website/docusaurus.config.js` to `website/cfg.js`.
2. Run `yarn swizzle --config cfg.js`.
3. See that swizzle works as intended.
N/A

feat(core): add --config param to swizzle command

---

packages/docusaurus/package.json
yarn.lock

Freeze fast-folder-file to 1.6.1 because newer versions changed from ISC license to Anti-war ISC
fix https://github.com/facebook/docusaurus/issues/8247

chore: fix tree-node-cli license

---

packages/docusaurus-plugin-ideal-image/src/theme/IdealImage/index.tsx

Screenshot below speaks for itself:
Preview

fix(ideal-image): do not pass down `img` prop

---

website/docs/guides/markdown-features/markdown-features-diagrams.mdx
website/versioned_docs/version-2.2.0/guides/markdown-features/markdown-features-diagrams.mdx

According to the types here https://github.com/facebook/docusaurus/blob/9c92a79d23533a61f3ad1bf3ea4d0889f0e2710f/packages/docusaurus-theme-mermaid/src/theme-mermaid.d.ts as well as runtime validation by myself - it should options not mermaidOptions.
Docs are misleading
Set some options using this method and they applied

docs: fix mermaid theme options typo

---

website/docs/api/plugin-methods/lifecycle-apis.md

Clarifies currently undocumented behaviour of the tag types.

docs: document tag types for insertHtmlContent

---

website/community/2-resources.md
website/docs/api/plugins/plugin-google-gtag.md

I'm really pleased that I migrated from Blogger to Docusaurus. But it wasn't straightforward. I want to make it easier for others to follow the same journey.
Also, it turns out people have been copy / pasting the example GTAG config from the docs which features my Google Analytics tag: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag#ex-config 
As a consequence, these websites are sending traffic to my Google Analytics property.  My life is now spent sending PRs like this:
- https://github.com/novuhq/novu/pull/1992
- https://github.com/undistro/undistro.io/pull/80
- https://github.com/dgiot/dgiot_doc/pull/74
I'd like to make it less likely that others make the same mistake.
If you're curious how I realised: https://twitter.com/johnny_reilly/status/1590585546451333120 …

docs: link to migration guide from Blogger to Docusaurus / remove blog.johnnyreilly.com Google Analytics tag from docs

---

packages/docusaurus-mdx-loader/package.json
packages/docusaurus-theme-mermaid/package.json
packages/docusaurus-theme-mermaid/src/client/index.ts
packages/docusaurus-theme-mermaid/src/validateThemeConfig.ts
packages/docusaurus-theme-mermaid/tsconfig.client.json
packages/docusaurus-theme-mermaid/tsconfig.json
yarn.lock

Upgrading for 9.1.7 to 9.2 makes the Mermaid theme compilation fails
Unfortunately users are upgraded automatically due to using the semver range `^9.1`, and it also fails at runtime for these users that should force v9.1.7 (last version that works) 
See:
- fix https://github.com/facebook/docusaurus/issues/8274
- https://github.com/mermaid-js/mermaid/issues/3747
Current PR is a draft, still unsolved 😅 
---
Probably unrelated to the issue (according to my local tests) but the theme/client Mermaid apis were not compiled with the correct TS options (ie outputs CJS instead of ESM), so I'm also fixing that here.

fix(mermaid): fix Mermaid integration for v9.2 release

---

packages/docusaurus-theme-classic/src/theme/DocCard/index.tsx
packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Category/index.tsx
packages/docusaurus-theme-common/src/internal.ts
packages/docusaurus-theme-common/src/utils/__tests__/docsUtils.test.tsx
packages/docusaurus-theme-common/src/utils/docsUtils.tsx
website/_dogfooding/_docs tests/tests/visibility/index.md
website/_dogfooding/_docs tests/tests/visibility/only-drafts/draft-subcategory/index.md
website/_dogfooding/_docs tests/tests/visibility/only-unlisteds/unlisted-subcategory/index.md
website/_dogfooding/_docs tests/tests/visibility/some-drafts/draft-subcategory/index.md
website/_dogfooding/_docs tests/tests/visibility/some-unlisteds/unlisted-subcategory/index.md

Fix https://github.com/facebook/docusaurus/issues/8301
The auto-generated category index should not present content with `unlisted: true` frontmatter in production mode.
Unit tests
Dogfood: `SIMULATE_PRODUCTION_VISIBILITY=true yarn start:website`
- https://deploy-preview-8319--docusaurus-2.netlify.app/tests/docs/tests/visibility => should show 2 subcategories instead of 4 (draft-only + unlisted-only categories are now both filtered)
- https://deploy-preview-8319--docusaurus-2.netlify.app/tests/docs/tests/visibility/some-unlisteds/unlisted-subcategory/ => should show a single listed doc instead of 2
Missing edge case from https://github.com/facebook/docusaurus/pull/8004

fix(docs,theme): auto-generated category index should not display unlisted content

---

packages/docusaurus-theme-classic/src/theme/Heading/index.tsx

- ~[ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.~
See #8327.
Apologies for taking a `good first issue` after I've already sent a couple PRs to this repo. I just was excited about this one 😄 
I tried this out locally on the https://github.com/typescript-eslint/typescript-eslint/pull/5951 PR and it worked. 
I don't see any existing tests for this. What would you like me to do?
Fixes #8327.

fix(theme): forward className prop in theme-classic's Heading

---

packages/docusaurus-utils/src/__tests__/markdownUtils.test.ts
packages/docusaurus-utils/src/markdownUtils.ts

See https://github.com/facebook/docusaurus/discussions/8294 - I want h1s with inline code please 😄 
I ... don't have one beyond unit tests.
https://github.com/facebook/docusaurus/discussions/8294 - would you like me to file an issue? Or can someone convert that to one?

fix(utils): allow partially backticked markdown h1 contentTitles

---

packages/docusaurus-plugin-content-docs/src/index.ts

If you have multi-instances and versioning and you're trying to import partial MDX to a file from cut version, you'll get console error. This happens because a paths to the directory with the next version docs and directory with docs for some version starts with the same, i.e "\*\*/instance" and "\*\*/instance_versioned_docs/\*\*". So, isMDXPartial() uses wrong directory as a root directory as a root. We need to append slashes to contentDirs, so that "\*\*/instance/\*\*"(slash added) will not mix up with "\*\*/instance_versioned_docs/\*\*"
Example:
In my docs folder I have a folder "_includes" with MDX partials. I use multi-instances, "instance" is a name of one of the instances. I import partials like that:
`import Partial from '@site/instance/_includes/_partial.mdx'; `
Then I cut a new …

fix(content-docs): add trailing slash to contentDirs, before passing it to isMDXPartial

---

website/docs/guides/markdown-features/markdown-features-react.mdx

Currently the documentation at https://docusaurus.io/docs/markdown-features/react#markdown-and-jsx-interoperability offers a workaround to the issue "A paragraph starting with a JSX tag will be seen entirely as a JSX string", but the demo of the workaround is using actual HTML instead of markdown. This change actually makes the demo show what it's claiming :)
https://deploy-preview-8352--docusaurus-2.netlify.app/docs/markdown-features/react#markdown-and-jsx-interoperability
Before:
After:

docs: actually demo the zero-width space workaround in MDX

---

packages/docusaurus-theme-classic/src/theme/DocRoot/Layout/Sidebar/ExpandButton/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocRoot/Layout/Sidebar/index.tsx
packages/docusaurus-theme-classic/src/theme/DocRoot/Layout/Sidebar/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocSidebar/Desktop/styles.module.css

This change is to address #4415 
https://user-images.githubusercontent.com/8978815/201485920-dc0eb99b-8564-4b3e-90bf-58afb4d49022.mp4
Deploy preview: https://deploy-preview-8328--docusaurus-2.netlify.app/tests/docs
Same page on prod: https://docusaurus.io/tests/docs
#4415

fix(theme): preserve sidebar height on collapse

---

packages/docusaurus/src/commands/deploy.ts

A minor simplification/optimization in the way the repo source url is determined during deployment.
Instead of directly extracting the raw value from config, use the more idiomatic, built-in command:
```
git remote get-url origin
```
It has the added benefit that a potential `insteadOf` configuration is also taken into account.
See [git remote man page](https://git-scm.com/docs/git-remote.html#Documentation/git-remote.txt-emget-urlem) for additional details.

feat(core): deploy CLI - add support for git url "insteadOf": use 'remote get-url' to determine source repo url

---

project-words.txt
website/docs/deployment.mdx

It adds a small guide about how to deploy Docusaurus on Kinsta Application Hosting.
Deploy preview: https://deploy-preview-8375--docusaurus-2.netlify.app/

docs: add Kinsta to deployment page

---

website/docs/guides/markdown-features/markdown-features-plugins.mdx

The links to the remark and rehype plugin creation documentation are broken.
The links to the github documentation that describes plugin creation for remark and rehype are wrong.

docs: fix links to external plugin description

---

packages/eslint-plugin/src/index.ts
website/docs/api/misc/eslint-plugin/README.md

See #8280 for details
Change to config might require a minor version change.
- [Deploy Preview](https://deploy-preview-8281--docusaurus-2.netlify.app)
- [Updated ESLint Plugin Documentation](https://deploy-preview-8281--docusaurus-2.netlify.app/docs/api/misc/@docusaurus/eslint-plugin/#usage)
Closes #8280

feat(eslint-plugin): add plugin to exported configs

---

package.json
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/Tabs/__tests__/index.test.tsx
packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx
packages/docusaurus-theme-common/src/contexts/tabGroupChoice.tsx
packages/docusaurus/src/client/ClientLifecyclesDispatcher.tsx
website/docs/guides/markdown-features/markdown-features-tabs.mdx

* Selection stored according to [this comment](https://github.com/facebook/docusaurus/issues/7008#issuecomment-1152540679) - serialized JSON with group ids as keys and `__noGroup__` constant key for tabs that do not belong to any group. Downsides:
* Ugly links - http://localhost:3000/docs/markdown-features/tabs?tabs=%7B%22__noGroup__%22%3A%22banana%22%2C%22operating-systems%22%3A%22win%22%7D
* In case of multiple tabs that do not belong to any group and have different tab item keys, this solution would only work for the last selected tab.
* Selected key priority: search query > local storage > defaultValue prop > 1st tab with default specified > 1st tab.
* @slorber can you please provide further explanation for [this comment](https://github.com/facebook/docusaurus/issues/7008#issuecomment- …

feat(theme-classic): store selected tab in query string.

---

packages/docusaurus-theme-translations/locales/zh-Hans/theme-common.json

Completed untranslated portion

fix(translations): complete Chinese theme translations

---

website/docs/search.md
website/versioned_docs/version-2.2.0/search.md

Those looking to evaluate Docusaurus's [search capabilities](https://docusaurus.io/docs/search), won't be familiar with swizzling.

docs: add hyperlink to swizzling in Search page

---

website/src/components/Tweet/index.tsx
website/src/data/tweets.tsx

As @slorber mentioned in issue #8436 , we can fix the broken link issue by adding a new prop `githubUsername` and GitHub has a defined image URL, which will always work but that will be passed as a fallback URL. The priority image will be fetched from the user's Twitter account using unavatar.io and the fallback would be the GitHub profile picture in case twitter image fails to load.
I tried adding a broken twitter account username in the `handle` parameter and it still loads the image from GitHub's profile picture.
Deploy preview: https://deploy-preview-8443--docusaurus-2.netlify.app/
#8436

docs: fix website home testimonials broken image URLs

---

packages/docusaurus-theme-translations/locales/vi/theme-common.json
packages/docusaurus-theme-translations/locales/vi/theme-search-algolia.json

fix(theme-translations): complete Vietnamese theme translations

---

website/src/data/users.tsx

I have been using Docusaurus a lot for a personal project(I also submitted an issue which was fixed recently) and I was going through a lot of design and code inspirations for software tools when I noticed tooljet website's intro section has been moved. 
I ran the website locally and it worked fine. SInce it's just a URL swap, no further tests are required.
Deploy preview: https://deploy-preview-8454--docusaurus-2.netlify.app

fix(docs): Update link for tooljet website(broken)

---

packages/docusaurus-theme-classic/src/theme/DocRoot/Layout/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocSidebar/Desktop/CollapseButton/styles.module.css
packages/docusaurus-theme-classic/src/theme/Layout/styles.module.css

1. CollapseButton margin style set zero locally #8426 
2. docusaurus-theme-classic/Layout set flex style for grow #8369
fix #8369 
fix #8426  for CollapseButton

fix(theme-classic): content container grow to take all the available space

---

packages/docusaurus/src/commands/build.ts

Since it's my first PR here, I am not sure about the process.
And we be pleased to have some guidance.
I have a project where the convention is using bracket [] in folder name.
The actual version of docusaurus if failing at build stage when there is a folder with bracket in the name.
After some investigation, I found that the issue is coming from the `copy-webpack-plugin`.
It actually report the folder has a file.
> /packages/docusaurus/src/commands/build.ts line 199
```ts
serverConfig = merge(serverConfig, {
plugins: [
new CopyWebpackPlugin({
patterns: staticDirectories.map((dir) => ({from: dir, to: outDir})),
}),
],
});
```
Since outDir is of course always a dir we can set the `toType` option to `dir` to solve this issue, this actually solve the false report of the outdir has a file by …

fix(core): explicitly define CopyWebpackPlugin toType: 'dir'

---

.cspell.json
.eslintignore
.prettierignore
jest/vendor/@mdx-js__mdx@2.1.5.js
jest/vendor/estree-util-value-to-estree@2.1.0.js
jest/vendor/mdast-util-to-string@3.1.0.js
jest/vendor/remark-directive@2.0.1.js
jest/vendor/remark-gfm@3.0.1.js
jest/vendor/remark-mdx@2.1.5.js
jest/vendor/remark@14.0.2.js

MDX 2 deps only support ESM so we need to vendor them as CJS to make them work in Jest unit tests.
This was initially made as part of the MDX 2 PR here: https://github.com/facebook/docusaurus/pull/8288
But I'm moving this in this separate PR and merging it earlier because otherwise, the MDX 2 PR (https://github.com/facebook/docusaurus/pull/8288/files) becomes hard to review (too much noise, GitHub review UI freezing...)

chore: vendor MDX deps for Jest and the MDX 2 upgrade

---

packages/docusaurus/src/server/__tests__/routes.test.ts
packages/docusaurus/src/server/routes.ts

Added a unit test that didn't pass on master. Ideally we would have dogfooding as well, but this is hard because we have to make sure that (1) two blog posts have the same chunk name (2) they appear on the same page in the paginated view. It's possible if we create another blog plugin solely for this test, but that doesn't seem worthwhile.

fix(core): avoid hash collision when generating chunk names

---

packages/docusaurus-theme-common/src/hooks/useSearchPage.ts

fix(algolia): make search footer respect searchPagePath

---

website/docs/docusaurus-core.mdx

Unsure on placement on this within the doc.

docs: add link to pluralization docs

---

packages/docusaurus-preset-classic/src/index.ts

Fix the issue reported here: https://canary.discord.com/channels/398180168688074762/867060369087922187/1068803004389654559
It's telling `trackID` is required because the wrong plugin is installed.

fix(preset-classic): install the right plugin for googleTagManager

---

packages/docusaurus-utils/src/__tests__/markdownUtils.test.ts
packages/docusaurus-utils/src/markdownUtils.ts

- [NA] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.
On Windows, when CRLF line endings are used, there is an issue when parsing Markdown. More specifically, the generated excerpt might be empty when the Markdown content starts with some `import`.
I added a unit tests that demonstrates what the issue was, and shows that it is now fixed with the change.
Deploy preview: https://deploy-preview-8606--docusaurus-2.netlify.app/
None

fix(utils): handle CRLF when parsing MDX imports

---

packages/docusaurus-theme-classic/src/theme/Tabs/__tests__/index.test.tsx
packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx
packages/docusaurus-theme-common/src/utils/tabsUtils.tsx

fix(theme-classic): allow rendering single tab item

---

packages/docusaurus-theme-common/src/utils/historyUtils.ts

Under React 18 SSR, it will be required to provide `getServerSnapshot()` callback to `useSyncExternalStore`
Apparently, some users already run Docusaurus on React 18, and `useSyncExternalStore` throw more aggressively than the shim.
We don't officially support React 18 yet and don't recommend using it, but this fix should make it possible to use it if you really want to, at your own risk.
Fix https://github.com/facebook/docusaurus/issues/8592

fix(theme-common): prepare usage of useSyncExternalStore compatibility with React 18 

---

packages/docusaurus-plugin-google-gtag/src/__tests__/options.test.ts
packages/docusaurus-plugin-google-gtag/src/index.ts
packages/docusaurus-plugin-google-gtag/src/options.ts
packages/docusaurus-plugin-google-gtag/tsconfig.client.json
website/docs/api/plugins/plugin-google-gtag.mdx
website/docusaurus.config.js

Feature useful for a smooth transition of Docusaurus sites from Universal Analytics to Google Analytics 4.
Universal Analytics is deprecated by google and will become readonly in June 2023. 
The analytics data can't be migrated so for a smooth transition it's useful to collect analytics for both old (UA) and new (GA4) properties at the same time, as documented here: https://developers.google.com/tag-platform/gtagjs/install#add-products.
As an example, we are also using a brand new GA4 tracking id on our own website, and keep collecting data for our old UA tracking id.
The preview should successfully collect for both GA properties in network logs and I should see data in GA dashboards.
https://deploy-preview-8620--docusaurus-2.netlify.app/docs/api/plugins/@docusaurus/plugin-google-gtag/ …

feat(gtag-plugin): gtag should support multiple tracking ids, notably for the UA => GA4 transition

---

lerna.json

Our changelog does not include some deps upgrades currently, I think it's useful to have these entries:
---
* `docusaurus-plugin-client-redirects`, `docusaurus-theme-search-algolia`, `docusaurus`
* [#8610](https://github.com/facebook/docusaurus/pull/8610) chore(deps): bump eta from 1.12.3 to 2.0.0 ([@dependabot[bot]](https://github.com/apps/dependabot))

chore: add "pr: dependencies" to lerna changelog labels

---

packages/docusaurus-theme-common/src/utils/scrollUtils.tsx
packages/docusaurus-theme-common/src/utils/tabsUtils.tsx
website/_dogfooding/_pages tests/tabs-tests.mdx

Fix https://github.com/facebook/docusaurus/issues/8625
preview
https://deploy-preview-8628--docusaurus-2.netlify.app/tests/pages/tabs-tests

fix(theme-common): fix issue in tab scroll position restoration on tab click

---

examples/classic-typescript/package.json
examples/classic-typescript/yarn.lock
examples/classic/package.json
examples/classic/yarn.lock
examples/facebook/package.json
examples/facebook/yarn.lock

chore: update examples to Docusaurus 2.3.1
---
- [code backport PR](https://github.com/facebook/docusaurus/pull/8621) 
- [docs backport PR](https://github.com/facebook/docusaurus/pull/8627) 
- [examples PR](https://github.com/facebook/docusaurus/pull/8629)

chore: update examples to Docusaurus 2.3.1

---

website/docs/guides/markdown-features/markdown-features-tabs.mdx

Clarifies description of tab query string behaviour.

docs: clarify query string behavior

---

packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-classic/src/theme/CodeBlock/Content/styles.module.css
packages/docusaurus-theme-classic/src/theme/CodeBlock/CopyButton/styles.module.css
packages/docusaurus-theme-common/src/components/Collapsible/index.tsx
yarn.lock

Upgrade Infima version to alpha.43, now respecting the user intent of reducing browser motions through their OS / accessibility settings.
Docusaurus should respect that as well and automatically disable most of its animated transitions.
Other animations disabled on the Docusaurus side:
- Collasible animations (JS-based, affects sidebar categories, mobile TOC, details/summary...)
- Code block buttons animations
Browse preview with reduced motions
Deploy preview: https://deploy-preview-8674--docusaurus-2.netlify.app/
https://github.com/facebookincubator/infima/pull/281

feat(theme-classic): respect `prefers-reduced-motion: reduce` mediaquery, bump Infima to alpha.43

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DropdownNavbarItem.tsx
website/_dogfooding/_pages tests/navbar-dropdown-tests.mdx
website/_dogfooding/dogfooding.css

Fixed #8697 bug.
It only worked if the dropdown was immediately followed by an `a` element, so I changed the implementation to use the `focusin` event so that it would also work with the `button` element.
Pressing the `Tab` key on the last item will cause it to lose focus.
https://user-images.githubusercontent.com/34136752/220811162-3790ddd0-af7c-494f-a6e8-c78b55a73bbb.mp4
Pressing the `Tab` key on the last item shifts focus to the theme switcher button.
https://user-images.githubusercontent.com/34136752/220811194-75ec8619-de1f-4900-9163-361e36fe13ad.mp4
Deploy preview: https://deploy-preview-8699--docusaurus-2.netlify.app/tests/pages/navbar-dropdown-tests
Fixed #8697

fix(theme-classic): fix tab focus bug in dropdown (#8697)

---

.cspell.json
packages/docusaurus/bin/docusaurus.mjs
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/start.ts
website/docusaurus.config.js
website/docusaurus.config.localized.json

All Docusaurus scripts should fallback to "development" env:
```js
process.env.BABEL_ENV ??= 'development';
process.env.NODE_ENV ??= 'development';
```
It should remain possible to run something like `NODE_ENV=production docusaurus swizzle`, although I'm not sure why someone would want to do that, it could make sense for some plugin script use cases we didn't think of? 🤷‍♂️ 
`docusaurus build` should override those defaults and have:
```js
process.env.BABEL_ENV = 'production';
process.env.NODE_ENV = 'production';
```
---
When starting/building the site for a given locale, we should set a `process.env.DOCUSAURUS_CURRENT_LOCALE` variable.
It is a temporary flexible workaround to solve the inability to translate site config attributes (https://github.com/facebook/docusaurus/issues/4542). …

feat(core): add script env variables: NODE_ENV + BABEL_ENV + DOCUSAURUS_CURRENT_LOCALE (temporary i18n workaround)

---

packages/docusaurus-theme-classic/src/theme/DocPage/Layout/styles.module.css

Little layout bug reported here, only affecting v2.x (already fixed in 3.x but not backportable)
https://github.com/facebook/docusaurus/issues/8369#issuecomment-1426838764
preview
https://deploy-preview-8707--docusaurus-2.netlify.app/tests/docs/more-test
https://github.com/facebook/docusaurus/issues/8369

fix(theme-classic): fix docs layout issue

---

admin/new.docusaurus.io/functionUtils/playgroundUtils.ts
admin/new.docusaurus.io/functions/codesandbox-ts.ts
admin/new.docusaurus.io/functions/stackblitz-ts.ts
website/src/components/Playground/index.tsx

It should be easy to try Docusaurus with TypeScript in a code playground
preview
https://deploy-preview-8723--docusaurus-2.netlify.app/docs/playground
Fix https://github.com/facebook/docusaurus/issues/8685

docs: add TypeScript playgrounds to docusaurus.new + Playground page

---

admin/new.docusaurus.io/netlify.toml

Missing serverless setup for https://github.com/facebook/docusaurus/pull/8723 to work as it should
These URLs should work:
- https://docusaurus.new/codesandbox-ts
- https://docusaurus.new/stackblitz-ts

fix: bad routing for docusaurus.new ts functions

---

packages/docusaurus-theme-classic/src/index.ts
website/_dogfooding/_pages tests/embeds.tsx
website/_dogfooding/_pages tests/index.mdx
website/docs/styling-layout.mdx
website/src/components/BrowserWindow/index.tsx

We should be able to force start a Docusaurus site on a given theme through a query-string param.
Examples:
- https://docusaurus.io/?docusaurus-theme=dark
- https://docusaurus.io/docs/configuration?docusaurus-theme=light
This is notably useful for embedding Docusaurus inside another system (WebView, iframe, Electron...) and ensuring the the Docusaurus theme matches the host theme (see https://github.com/facebook/docusaurus/issues/8672)
preview
https://deploy-preview-8708--docusaurus-2.netlify.app/tests/pages/embeds
fix https://github.com/facebook/docusaurus/issues/8672

feat(theme): allow to load a Docusaurus page with theme from query-string: ?docusaurus-theme=dark

---

packages/docusaurus-theme-classic/src/theme/ErrorPageContent.tsx
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/errorBoundaryUtils.module.css
packages/docusaurus-theme-common/src/utils/errorBoundaryUtils.tsx
packages/docusaurus/src/client/theme-fallback/Error/index.tsx
website/src/components/ErrorBoundaryTestButton/index.tsx
website/testCSSOrder.mjs

The ErrorDisplay in its original state was a bit tough to digest when the text occupied 100% of the viewport width. It also overflowed the viewport at smaller screen heights due to the `height: 50vh` declaration. My proposed changes ensure the ErrorDisplay styling is a bit more responsive and resembles how the Docusaurus [404 pages](https://docusaurus.io/docs/api/themes/configuration/foo) look. Totally an optional change!
Deploy preview: https://deploy-preview-8736--docusaurus-2.netlify.app/
Somewhat related to conversation around improving error messages in https://github.com/facebook/docusaurus/issues/8696

polish(core): better styling for error screens

---

packages/docusaurus-theme-common/src/hooks/useSearchPage.ts
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/internal.ts
packages/docusaurus-theme-common/src/utils/historyUtils.ts
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.tsx
packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.tsx

The search page results do no React do external querystring changes (ie `history.replaceState`) but only to local setState calls because the state is somehow duplicated and not synchronized properly.
Using the new common hook utils based on `useSyncExternalStore` make it easier to deal with synchronization by avoiding duplicating state in the first place: we should use them more.
I also did some cleanup and split an awkward larger `useSearchPage` hook into 2 more specific hooks.
The SearchPage remains a quite messy page that we'll have to refactor someday, but that will not be in this PR.
preview
https://deploy-preview-8757--docusaurus-2.netlify.app/search?q=docs
fix https://github.com/facebook/docusaurus/issues/8755

fix(search): search page should react to querystring changes + cleanup/refactor

---

website/docs/api/themes/theme-configuration.mdx
website/versioned_docs/version-2.0.1/api/themes/theme-configuration.mdx
website/versioned_docs/version-2.1.0/api/themes/theme-configuration.mdx
website/versioned_docs/version-2.2.0/api/themes/theme-configuration.mdx
website/versioned_docs/version-2.3.1/api/themes/theme-configuration.mdx

I want to configure copyright text to have some links, and via `packages/docusaurus-theme-classic/src/theme/Footer/Copyright/index.tsx` knew copyright supports the custom HTML, hope to add this description for docs.
And I had checked copyright alreadly supports the custom HTML in old version.
Deploy preview: https://deploy-preview-8761--docusaurus-2.netlify.app/

docs: add description for themeConfig.footer fields copyright

---

website/docs/guides/markdown-features/markdown-features-react.mdx
website/src/theme/MDXComponents.tsx
website/versioned_docs/version-2.0.1/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-2.1.0/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-2.2.0/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-2.3.1/guides/markdown-features/markdown-features-react.mdx

In MDX v2, lower-case elements can't be replaced by custom components anymore. Only the upper-case components can.
The following will stop working in Docusaurus v3, so we should start encouraging users to not use lower-case tag names for custom MDX components, even if it still temporarily works
Also did some cleanup that was related to prepare for MDX 2 (for example there's no more `MDXComponents/Head` component)
preview
https://deploy-preview-8779--docusaurus-2.netlify.app/docs/markdown-features/react#mdx-component-scope
MDX 2 PR: https://github.com/facebook/docusaurus/pull/8288

docs: v2 docs should discourage the usage of a lower-case MDX component (will not work in v3)

---

website/docs/installation.mdx
website/versioned_docs/version-2.0.1/installation.mdx
website/versioned_docs/version-2.1.0/installation.mdx
website/versioned_docs/version-2.2.0/installation.mdx
website/versioned_docs/version-2.3.1/installation.mdx

Minor docs change because my new visual diff toy reports a diff in the MDX 2 PR (https://github.com/facebook/docusaurus/pull/8288)
This change permits me to avoid excluding the whole `/docs/installation` URL from the visual diff
MDX 2 + GFM will autolink while MDX 1 does not.
https://app.argos-ci.com/slorber/docusaurus-visual-tests/builds/10/40206528

docs: fix localhost url without link

---

examples/facebook/docusaurus.config.js
packages/create-docusaurus/templates/classic/docusaurus.config.js
packages/create-docusaurus/templates/facebook/docusaurus.config.js

Fix https://github.com/facebook/docusaurus/issues/8696
Using a docSidebar item is less fragile for new Docusaurus users: they can delete/rename the intro doc without having an immediate error because the sidebar still exists
locally + CI
Deploy preview: https://deploy-preview-8712--docusaurus-2.netlify.app/

polish(create-docusaurus): the starter template should use a navbar item "docSidebar" instead of "doc" (less fragile on updates)

---

website/docs/guides/docs/docs-create-doc.mdx
website/versioned_docs/version-2.0.1/guides/docs/docs-create-doc.mdx
website/versioned_docs/version-2.1.0/guides/docs/docs-create-doc.mdx
website/versioned_docs/version-2.2.0/guides/docs/docs-create-doc.mdx
website/versioned_docs/version-2.3.1/guides/docs/docs-create-doc.mdx

For MDX 2 (https://github.com/facebook/docusaurus/pull/8288) we have to apply a pre-processing step to escape heading ids so that it is valid MDX 2:
```diff
-## Custom ID headers {#custom-id}
+## Custom ID headers \{#custom-id}
```
This usually works fine but when this is found inside a Markdown code block then it should probably be escaped. 
It's possible to hack around this pre-processing by using JSX (or to fix the pre-processing but it would become less efficient). 
Instead I choose to simply remove this special anchor id doc from the example here, considering it's already documented here: https://docusaurus.io/docs/markdown-features/toc#heading-ids
We can reintroduce this later if needed but for now it's simpler to remove it.
Removed in main so that my visual diff tool does not …

docs: remove problematic mdx2 anchor id docs for MDX 2 migration

---

packages/docusaurus-theme-classic/src/theme/Tabs/__tests__/index.test.tsx
packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx
packages/docusaurus-theme-common/src/utils/tabsUtils.tsx

https://deploy-preview-8801--docusaurus-2.netlify.app/docs/markdown-features/tabs/

fix(theme): allow tabs children to be falsy

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/Content/String.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/Content/styles.module.css

The codeblock on RTL locale puts copy button on the left while code is also on the left. Therefore added one more class in `docusaurus-theme-classic` package to solve this issue. Now the code is on left and copy button is on the right side.
[#8792](https://github.com/facebook/docusaurus/issues/8792)

fix(theme): codeblock buttons should be kept on the right when using RTL locale

---

website/docs/api/plugins/plugin-pwa.mdx
website/versioned_docs/version-2.0.1/api/plugins/plugin-pwa.mdx
website/versioned_docs/version-2.1.0/api/plugins/plugin-pwa.mdx
website/versioned_docs/version-2.2.0/api/plugins/plugin-pwa.mdx
website/versioned_docs/version-2.3.1/api/plugins/plugin-pwa.mdx

Goal is to fix our website prod deployment due to Crowdin unability to understand MDX well + previous page link was broken/redirected
https://app.netlify.com/sites/docusaurus-2/deploys/641b45d5d6f0f10008edad8d
https://crowdin.com/translate/docusaurus-v2/16353/en-fr?filter=basic&value=0

chore: fix workbox precaching page link + weird mdx structure breaking Crowdin

---

examples/classic-typescript/docusaurus.config.js
examples/classic-typescript/package.json
examples/classic-typescript/yarn.lock
examples/classic/docusaurus.config.js
examples/classic/package.json
examples/classic/yarn.lock
examples/facebook/docusaurus.config.js
examples/facebook/package.json
examples/facebook/yarn.lock

update examples to Docusaurus 2.4.0
- [code backport PR](https://github.com/facebook/docusaurus/pull/8809) 
- [docs backport PR](https://github.com/facebook/docusaurus/pull/8811)
- [examples PR](https://github.com/facebook/docusaurus/pull/8815)

chore: update examples to Docusaurus 2.4.0

---

package.json

Crowdin should download:
- pt-BR instead of pt-PT
- ja for our i18n staging env: https://docusaurus-i18n-staging.netlify.app/

chore: Crowdin download languages pt-BR + ja

---

packages/create-docusaurus/src/index.ts

The error in this function is that validateSiteName is an asynchronous function, so it returns a promise. However, in the getSiteName function, the returned value of validateSiteName is not being awaited, and instead, it's being treated as a synchronous value. This can cause unexpected behavior and errors.
To fix this error, you need to await the result of validateSiteName using the await keyword, like this:

fix(create): add missing await

---

website/docs/guides/markdown-features/markdown-features-diagrams.mdx

As discussed in https://github.com/facebook/docusaurus/discussions/8806, the current link to the Mermaid docs website offers incomplete information.
This PR adds a link to the Mermaid config types, which makes it super clear what configuration options are available in Mermaid.

docs: link to mermaid config types

---

website/docs/cli.mdx

I came across a small grammatical error in the API documentation when looking into another issue. I've changed the existing wording from 'Do not open automatically the page in the browser' to 'Do not open **the page** automatically in the browser'.
Thanks!

docs: correct small grammar error

---

website/src/css/custom.css
website/src/plugins/featureRequests/FeatureRequestsPage.tsx

https://developers.canny.io/install/widget/web / https://feedback.canny.io/feature-requests/p/widget-dark-theme
Canny just added dark mode support to their widget. I figure setting it from "light" to "auto" is a good default for now - we could set it to switch explicitly using `useColorMode` if we wanted - valid values are `light` / `dark` and `auto`
https://deploy-preview-8846--docusaurus-2.netlify.app/feature-requests/

fix: add auto theme switch to the Canny widget

---

packages/docusaurus-theme-classic/src/theme/DocPaginator/index.tsx
packages/docusaurus-theme-translations/locales/ar/theme-common.json
packages/docusaurus-theme-translations/locales/base/theme-common.json
packages/docusaurus-theme-translations/locales/bn/theme-common.json
packages/docusaurus-theme-translations/locales/cs/theme-common.json
packages/docusaurus-theme-translations/locales/da/theme-common.json
packages/docusaurus-theme-translations/locales/de/theme-common.json
packages/docusaurus-theme-translations/locales/es/theme-common.json
packages/docusaurus-theme-translations/locales/fa/theme-common.json
packages/docusaurus-theme-translations/locales/fil/theme-common.json
packages/docusaurus-theme-translations/locales/fr/theme-common.json
packages/docusaurus-theme-translations/locales/hi/theme-common.json
packages/docusaurus-theme-translations/locales/hu/theme-common.json
packages/docusaurus-theme-translations/locales/it/theme-common.json
packages/docusaurus-theme-translations/locales/ja/theme-common.json
packages/docusaurus-theme-translations/locales/ko/theme-common.json
packages/docusaurus-theme-translations/locales/nb/theme-common.json
packages/docusaurus-theme-translations/locales/nl/theme-common.json
packages/docusaurus-theme-translations/locales/pl/theme-common.json
packages/docusaurus-theme-translations/locales/pt-BR/theme-common.json
packages/docusaurus-theme-translations/locales/pt-PT/theme-common.json
packages/docusaurus-theme-translations/locales/ru/theme-common.json
packages/docusaurus-theme-translations/locales/sl/theme-common.json
packages/docusaurus-theme-translations/locales/sr/theme-common.json
packages/docusaurus-theme-translations/locales/sv/theme-common.json
packages/docusaurus-theme-translations/locales/tr/theme-common.json
packages/docusaurus-theme-translations/locales/uk/theme-common.json
packages/docusaurus-theme-translations/locales/vi/theme-common.json
packages/docusaurus-theme-translations/locales/zh-Hans/theme-common.json
packages/docusaurus-theme-translations/locales/zh-Hant/theme-common.json

Closes #8834
Tested using a screen reader
#8834

fix(theme-translations): remove redundant navigation text in aria label

---

packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/CodeBlock/CopyButton/index.tsx
packages/docusaurus-theme-classic/src/theme/CodeBlock/WordWrapButton/index.tsx
packages/docusaurus-theme-classic/src/theme/Icon/Copy/index.tsx
packages/docusaurus-theme-classic/src/theme/Icon/Success/index.tsx
packages/docusaurus-theme-classic/src/theme/Icon/WordWrap/index.tsx

I'd like to reuse thos eicons without in playground of typescript-eslint, as for now i had to make a copy
https://typescript-eslint.io/play/
https://deploy-preview-6728--typescript-eslint.netlify.app/play/#showAST=es
https://docusaurus.io/docs/cli/
https://deploy-preview-8862--docusaurus-2.netlify.app/docs/cli/
https://github.com/typescript-eslint/typescript-eslint/pull/6728

refactor(theme): expose copy, success and word-wrap icons as standalone components

---

website/docs/deployment.mdx

docs: add "permissions.content: write" to GH workflow examples

---

packages/docusaurus-theme-classic/src/theme/ThemedImage/index.tsx
packages/docusaurus-theme-common/src/components/ThemedComponent/index.tsx
packages/docusaurus-theme-common/src/components/ThemedComponent/styles.module.css
packages/docusaurus-theme-common/src/index.ts

See https://github.com/facebook/docusaurus/discussions/8001#discussioncomment-5604260
We want to make it easier to build themed components, when using CSS is not a great fit. 
For example when rendering React SVGs (`.svg` extensions are converted to React components through SVGR).
We should be able to do this:
```tsx
import {ThemedComponent} from '@docusaurus/theme-common';
import LogoLight from "./assets/logo_light.svg";
import LogoDark from "./assets/logo_dark.svg";
function MyThemedLogo(): JSX.Element {
return (
<ThemedComponent className="my-logo">
{({theme, className}) => {
const LogoComponent = theme === "dark" ? LogoDark : LogoLight;
return <LogoComponent className={className}/>
})}
</ThemedComponent>
);
}
```
Note it's a new feature in theme-common but …

feat(theme): create more generic ThemedComponent util from ThemedImage

---

packages/docusaurus-theme-common/src/utils/docsUtils.tsx

The error message when user provides a bad navbar sidebar id is wrong, it displays indices (0, 1...) instead of actual sidebar names.
Now it will print the sidebar names:
local

fix(theme-common): fix confusing theme error message: bad sidebar id suggestions

---

packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts
website/_dogfooding/_pages tests/code-block-tests.mdx

Add support for Lua, haskell, SQL and wasm comment style for MagicComments. Related #8859 
https://deploy-preview-8870--docusaurus-2.netlify.app/tests/pages/code-block-tests
https://github.com/facebook/docusaurus/issues/8859

feat(theme-common): code block MagicComments support for Lua/Haskell -- and WebAssembly ;;

---

website/docs/swizzling.mdx
website/versioned_docs/version-2.0.1/swizzling.mdx
website/versioned_docs/version-2.1.0/swizzling.mdx
website/versioned_docs/version-2.2.0/swizzling.mdx
website/versioned_docs/version-2.3.1/swizzling.mdx
website/versioned_docs/version-2.4.0/swizzling.mdx

I saw a spelling mistake and I'm just submitting a fix for it.
Not needed as this is just a docs change.
Not needed as this is just a docs change.

docs: changing shopping card to shopping cart

---

packages/docusaurus-theme-common/src/components/Collapsible/index.tsx

Bug better described here: https://github.com/facebook/docusaurus/discussions/8905#discussioncomment-5663928
When using `prefers-reduced-motion` in OS settings, nested collapsible does not work well because the `onTransitionEnd` callback does not fire. 
We rely on it to notably let the parent know that a child has changed size and recompute its height, because the event bubbles up. We can see it in action with nested details elements where the child was expanded, but the parent collapsible didn't adjust its own size and truncates the child.
Workaround: using an animation of 1ms fixes the problem. Not sure how to fix it otherwise but it looks good enough to me 🤷‍♂️.  
We still see the animation a bit which is annoying, but it's better than having the collapsible not uncollapsing and the UI …

fix(theme-common): fix collapsible component with prefers-reduced-motion

---

packages/docusaurus/bin/beforeCli.mjs

- [Y] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [N] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [N/A] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.
Incorrect notice on upgrade with unclear error message in yarn 2+.
Note: There are also incorrect messges in the installation.mdx files, and likely from. npmToYarn (which doesn't support yarn2+ yet) so I haven't done anything about these yet without a clear indication of direction.
- Check out an older docusaurus project and copy the file in place.
- Install the …

fix(core): Correct yarn upgrade command for yarn 2.x

---

packages/docusaurus-theme-classic/src/options.ts
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/NavbarItem/LocaleDropdownNavbarItem/index.tsx
website/docs/api/themes/theme-configuration.mdx
website/docs/i18n/i18n-tutorial.mdx

This PR adds a `queryString` option to the `localeDropdown` considering @slorber's review for https://github.com/facebook/docusaurus/pull/5890
@slorber mentioned we should dogfood it but I wasn't sure how do it. I can think of two ways for dogfooding it:
1. Full integration test that sets the `queryString` option and uses [Netlify Edge Functions](https://docs.netlify.com/edge-functions/overview/) to set a cookie to remember a user's preference.
2. A simpler test to check if the `queryString` is properly appended to the URL.
I manually tested the following cases:
I'm happy to write tests for those cases (and additional ones I didn't think of) but I'll need some pointers on how to get started.
Deploy preview: https://deploy-preview-8915--docusaurus-2.netlify.app/ …

feat(theme): add queryString option to localeDropdown

---

website/docs/guides/markdown-features/markdown-features-react.mdx

docs: mdx-js is using v2 for next edition

---

website/docs/blog.mdx
website/versioned_docs/version-2.0.1/blog.mdx
website/versioned_docs/version-2.1.0/blog.mdx
website/versioned_docs/version-2.2.0/blog.mdx
website/versioned_docs/version-2.3.1/blog.mdx
website/versioned_docs/version-2.4.0/blog.mdx

This is a documentation change for https://docusaurus.io/docs/blog#blog-list that closes #8653. These changes have been made to all previous versions of the blog page as well :) 
(I have read the contributing guidelines but I'm not sure how to mark it off on the checkbox, whoops)

docs: mention blog truncating marker edge case

---

packages/create-docusaurus/templates/classic/docusaurus.config.js

Fixes #8925 - Docusaurus config is confusing: const config vs module.exports
#8925

polish(create-docusaurus): add comment in config to mention different ways to declare config + doc link

---

project-words.txt
website/docs/api/docusaurus.config.js.mdx
website/docs/configuration.mdx

Fixes part of #8925
https://deploy-preview-8950--docusaurus-2.netlify.app/docs/api/docusaurus-config/
https://deploy-preview-8950--docusaurus-2.netlify.app/docs/configuration/
#8925

docs: bidirectional link between api config and guide config

---

website/docs/api/docusaurus.config.js.mdx
website/docs/configuration.mdx

Fixes part of #8925
https://deploy-preview-8951--docusaurus-2.netlify.app/docs/configuration/#syntax-to-declare-docusaurus-config
https://deploy-preview-8951--docusaurus-2.netlify.app/docs/api/docusaurus-config/
#8925

docs: mention equivalent config syntaxes

---

jest/deps.d.ts
packages/docusaurus-mdx-loader/package.json
packages/docusaurus-mdx-loader/src/__tests__/format.test.ts
packages/docusaurus-mdx-loader/src/__tests__/processor.test.ts
packages/docusaurus-mdx-loader/src/format.ts
packages/docusaurus-mdx-loader/src/index.ts
packages/docusaurus-mdx-loader/src/loader.ts
packages/docusaurus-mdx-loader/src/processor.ts
website/_dogfooding/_pages tests/markdown-tests-md.md
website/_dogfooding/_pages tests/markdown-tests-mdx.mdx
yarn.lock

Current MDX 2 setup does not allow arbitrary HTML elements when using format `md` (ie when using `.md` file extension)
Related: I am contributing new useful options to the MDX playground because otherwise this is not simple to debug how this new md format works: https://github.com/mdx-js/mdx/pull/2295
Note: this PR refactors many things to cleanup our MDX setup, but overall the solution to this specific html embed problem was:
```js
[
rehypeRaw,
{
passThrough: [
'mdxFlowExpression',
'mdxJsxFlowElement',
'mdxJsxTextElement',
'mdxTextExpression',
'mdxjsEsm',
],
},
];
```
preview should render fine
https://deploy-preview-8960--docusaurus-2.netlify.app/tests/pages/markdown-tests-md
https://github.com/facebook/docusaurus/discussions/8469#discussioncomment-5804253

fix: allow html syntax in MDX v2 with format md

---

website/docs/guides/markdown-features/markdown-features-code-blocks.mdx

I found a broken link, and I am making a pull request to fix it.
Just click on the new link.  
Here is [the broken link](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js) and here is [the new corresponding link](https://github.com/FormidableLabs/prism-react-renderer/blob/master/packages/generate-prism-languages/index.ts) .
Not needed as this is just a docs change.
None

docs: fix broken link to Prism includeLangs.js default list of languages

---

packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-pages/src/index.ts
packages/docusaurus/src/server/plugins/synthetic.ts
website/src/plugins/changelog/index.js

It is not needed to put a js-loader (Babel/SWC) on top of the mdx compiler.
The output of MDX is already good to be run directly since MDX v2 and does not need any extra transpilation step (the JSX is now transpiled, unlike in MDX v1 output)
I run some basic local tests by building our website locally. 
Unfortunately, the impact of this perf improvement is not as significant as I hoped it to be.
Still, we see some improvement for the Docusaurus site when running on the default Babel JS Loader. 
For SWC users, the impact is even smaller.
Before + Babel
- 92s
- 96s
- 95s
- 97s
Before + SWC
- 87s
- 85s
- 81s
- 86s
After + Babel
- 90s
- 90s
- 91s
- 91s
After + SWC
- 84s
- 85s
- 84s
- 83s
Preview builds and run as before + unit tests …

fix: remove useless js-loader in front of mdx-loader

---

website/docs/api/themes/theme-configuration.mdx

Updated broken links on [this page](https://docusaurus.io/docs/api/themes/configuration#theme).
Same question as in [this other PR](https://github.com/facebook/docusaurus/pull/8975) I just made, do we want to use links to the current master branch instead of permalinks?
N/A
Old link: https://docusaurus.io/docs/api/themes/configuration#theme
Deploy preview: https://deploy-preview-8976--docusaurus-2.netlify.app/docs/api/themes/configuration/#theme
Related PR: https://github.com/facebook/docusaurus/pull/8975
Closes: https://github.com/facebook/docusaurus/issues/8968

docs: update broken links theme configuration page

---

examples/classic-typescript/package.json
examples/classic-typescript/yarn.lock
examples/classic/package.json
examples/classic/yarn.lock
examples/facebook/package.json
examples/facebook/yarn.lock

update examples to Docusaurus 2.4.1
- [code PR](https://github.com/facebook/docusaurus/pull/8979) 
- [docs PR](https://github.com/facebook/docusaurus/pull/8980) 
- [examples PR](https://github.com/facebook/docusaurus/pull/8981)

chore: update examples to Docusaurus 2.4.1

---

packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts
website/_dogfooding/_pages tests/code-block-tests.mdx

I could not see an open issue for it but I would like to be able to use the magic comments feature in Matlab code blocks. This isn't currently supported due to Matlab's way of commenting, therefore I have added this capability in this PR.
- I have added a Matlab code snippet in the
dogfooding page which verifies the functionality.
- I ran a local instance of the site and verified that the lines were not highlighted by the magic comments
- I did the implementation and restarted the server and verified that the lines were highlighted
before
after
Deploy preview: https://deploy-preview-8982--docusaurus-2.netlify.app/tests/pages/code-block-tests/#magic-comments-tests

feat(theme-common): code block MagicComments support for TeX/LaTeX/Matlab

---

packages/docusaurus-theme-translations/locales/sv/theme-common.json

I just noticed this spelling error when I enabled the "show last updated" feature and it bugged me! 😃  
Looks like a search and replace miss to me. 
Google Translate proof of translation:
If I can switch to Swedish in the PR preview env I'll test it there.
Edit: I could not and can't be bothered to switch language to Swedish. Hope that is ok!
Deploy preview: https://deploy-preview-9021--docusaurus-2.netlify.app/
Didn't find any issue for this.

fix(theme-transalations): fix Swedish translation of "last updated"

---

packages/docusaurus/bin/beforeCli.mjs
packages/docusaurus/package.json

I've checked PR #8908.
Great idea to check which Yarn verison is being used.
However, the presence of a `.yarnrc.yml` file alone is not a definitive indicator of Yarn 2+ being used, as this file can be used by Yarn 1.x as well.
Check out the capture image below
This can be happened when you change Yarn 2+ -> Yarn 1
```bash
yarn set version 1
```
So, I think we should check `yarnPath` value (by using `js-yaml`),
to make sure what Yarn version is being used.
- Check out an older docusaurus project and copy the file in place.
- Install the project with `npm`
- Run a `npm run start`
- Close and run it again
- Confirm the notice had an appropriate `npm i` command
- `rm -rf node_modules`
- Install with yarn classic
- Run` yarn start`
- Close and run it again
- Confirm the notice had an …

fix(core): docusaurus CLI should detect the correct yarn version when suggesting upgrades

---

packages/docusaurus-theme-classic/src/index.ts
website/docs/styling-layout.mdx
website/src/css/custom.css

We should be able to use `/docs/someDoc?docusaurus-data-mode=iframe` and then provide alternate styling for iframe/embedded rendering mode
```css
html[data-mode='iframe'] .navbar {
display: none;
}
html[data-mode='iframe'] .footer {
display: none;
}
```
The system implemented allows you to inject arbitrary data-attribute values in the HTML, inlined (no FOUC / layout shifts expected), as long as they follow the `?docusaurus-data-<key>=<value>` pattern (value can be omitted)
Note: it was chosen to allow injecting data attributes over classes because classes would solve the same use case and class injection was more complicated to implement (React-Helmet would erase the injected classes after React hydration).
Preview + CI
The docs dogfood the feature: …

feat(theme): add ability to inject data attributes from query-string - possibility to create an iframe/embed variant of a page

---

packages/create-docusaurus/README.md
packages/create-docusaurus/templates/classic-typescript/package.json
packages/create-docusaurus/templates/classic-typescript/src/components/HomepageFeatures/index.tsx
packages/create-docusaurus/templates/classic-typescript/src/pages/index.tsx
packages/create-docusaurus/templates/classic-typescript/tsconfig.json
packages/create-docusaurus/templates/classic/src/components/HomepageFeatures/index.js
packages/create-docusaurus/templates/classic/src/pages/index.js
packages/docusaurus-tsconfig/package.json
packages/docusaurus-tsconfig/tsconfig.json
website/docs/typescript-support.mdx
website/package.json
website/tsconfig.json
yarn.lock

The old external [`@tsconfig/docusaurus`](https://www.npmjs.com/package/@tsconfig/docusaurus) package is now deprecated and you should use our new official versioned package `@docusaurus/tsconfig`.
Follow-up of the React 18 upgrade (https://github.com/facebook/docusaurus/pull/8961) including the usage of the automatic JSX runtime: we should now use `jsx: "preserve"` in our base default TS config
As discussed in the past: our base TS config should evolve alongside the codebase and be versioned (cf https://github.com/tsconfig/bases/pull/122)
website + dogfood + CI
Automatic JSX runtime needs use to change the config to `jsx: "preserve"` instead of `jsx: "react"`.
See also:
- …

feat: create official TypeScript base config @docusaurus/tsconfig

---

website/versioned_docs/version-2.0.1/guides/markdown-features/markdown-features-code-blocks.mdx
website/versioned_docs/version-2.1.0/guides/markdown-features/markdown-features-code-blocks.mdx
website/versioned_docs/version-2.2.0/guides/markdown-features/markdown-features-code-blocks.mdx
website/versioned_docs/version-2.3.1/guides/markdown-features/markdown-features-code-blocks.mdx
website/versioned_docs/version-2.4.1/guides/markdown-features/markdown-features-code-blocks.mdx

The link to  [commonly used languages](https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages) was broken.
Closes #9062
I found new link for supported languages from here https://github.com/FormidableLabs/prism-react-renderer#installation:~:text=includes%20a%20base%20set%20of%20languages
Affected Supported Lang Docs Page https://docusaurus.io/docs/markdown-features/code-blocks#supported-languages
Deploy preview: https://deploy-preview-9065--docusaurus-2.netlify.app/
#9062

docs: update link for commonly used languages

---

packages/docusaurus-mdx-loader/src/loader.ts

When MDX throws a regular JS error without extra useful attributes, the error message is not really helpful because the stacktrace is not included.
In these cases we want the stacktrace to be printed as well to troubleshoot the problem.
Note, for now this only works in the Webpack dev server:
The console (start+build) will print an unhelpful stacktrace:
This is very likely related to this issue: https://github.com/facebook/docusaurus/issues/9023
local only 😓

fix(mdx-loader): loader error message should display stacktrace if no extra MDX details

---

packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx
website/_dogfooding/_pages tests/markdown-tests-md.md
website/_dogfooding/_pages tests/markdown-tests-mdx.mdx
website/docusaurus.config.js

Having similar tests for md/mdx modes ensure we offer a consistent experience to our users.
Currently, those tests show it's not the case, see problems reported here: https://github.com/facebook/docusaurus/issues/9092
Also add better tests for html comments support, cf edge case bug reported here: https://github.com/facebook/docusaurus/issues/9084
This PR is also a mini fix adding support for summary/details in CommonMark mode, see https://github.com/facebook/docusaurus/issues/9092#issuecomment-1602902274
preview
https://deploy-preview-9093--docusaurus-2.netlify.app/tests/pages/markdown-tests-md
https://deploy-preview-9093--docusaurus-2.netlify.app/tests/pages/markdown-tests-mdx

fix(theme): support details/summary in CommonMark + add md dogfood test cases

---

packages/docusaurus-theme-classic/src/theme/BlogPostItem/Container/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogPostItem/Header/Author/index.tsx

We're trying to improve SEO on our site and have implemented a similar change by swizzling the `BlogPostItem/Container` component.
Just thought it would be nice to get this minor change added to the official theme component for the benefit of all :)
Implemented on another Docusaurus site and verified with [Google's schema markup testing tools](https://developers.google.com/search/docs/appearance/structured-data).
Deploy preview: https://deploy-preview-9108--docusaurus-2.netlify.app/blog

feat(theme-classic): add description & keywords microdata to blog posts

---

packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/__snapshots__/generator.test.ts.snap
packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/generator.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars/generator.ts

While customizing the sidebar generator behavior for a Docusaurus site I maintain, I discovered that `customProps` was missing on non-category sidebar items.
Added a custom prop to an existing test and regenerated the snapshot.

fix(content-docs): sidebar generator should return customProps for doc items

---

packages/docusaurus-theme-classic/src/theme/MDXComponents/Ul/index.tsx

Fix #9098
Deploy preview: https://deploy-preview-9099--docusaurus-2.netlify.app/

fix(theme): only set classname on ul elements if they have an existing class

---

packages/docusaurus/src/webpack/plugins/CleanWebpackPlugin.ts

Fix https://github.com/facebook/docusaurus/issues/9110
local tests
Deploy preview: https://deploy-preview-9112--docusaurus-2.netlify.app/

fix(core): throw error if build folder already exists on initial clean

---

.github/workflows/argos.yml

Argos visual diffing CI is heavy to run, and in many cases we don't need to run it.
Let's run it more responsibly, only when we add an Argos label to the PRs that need it.
This also permits to dogfood a responsible setup that I plan to recommend to the community, so that they can stay under free quote (Hobby plan) or Fair-use (Open source)
CI

chore: optimize Argos CI setup

---

packages/docusaurus-plugin-debug/package.json
packages/docusaurus-plugin-debug/src/theme/DebugJsonView/index.tsx
project-words.txt
website/docusaurus.config.js
yarn.lock

Fix https://github.com/facebook/docusaurus/issues/9105
Need to replace the unmaintained JSON viewer lib in our debug plugin.
Also added a navbar button to easily navigate to the debug view in dev.
For reference, I choose to use the [fork from `@microlink`](https://www.npmjs.com/package/@microlink/react-json-view) because other projects were not immediate project forks and more alternative libs. Also, we already depend on other projects from the same author, such as [unavatar](https://github.com/microlinkhq/unavatar). It does not feel necessary to create/maintain our own fork for now, but time will tell.
I'm open to replacing it with another different lib later. But for now this fix is good enough.
ci
Deploy preview: https://deploy-preview-9116--docusaurus-2.netlify.app/

fix(debug-plugin): upgrade react-json-view to maintained React-18 compatible fork

---

packages/docusaurus/src/commands/deploy.ts
website/docs/deployment.mdx

feat(cli): deploy command should allow customizing git config user.name / user.email in deployment branch (#9101)

---

website/docs/installation.mdx

```bash
#> yarn upgrade
Usage Error: Couldn't find a script named "upgrade".
$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
```
Instead use `yarn add` to update to the latest version. Also don't add @latest, because that will put the @latest constraint in package.json, which can cause silent major upgrades, as it's a rolling tag.
It's this page: [https://docusaurus.io/docs/installation](https://docusaurus.io/docs/installation)
None

docs: improve yarn deps upgrade command

---

packages/docusaurus-utils/src/pathUtils.ts
packages/docusaurus/src/server/index.ts
website/_dogfooding/_docs tests/beginner's guide.mdx

fix(core): handle single quotes inside file paths

---

packages/docusaurus-theme-classic/src/theme/SiteMetadata/index.tsx
packages/docusaurus-theme-common/src/utils/useAlternatePageUtils.ts

**I'm not really sure how to test it but we have it on every page of the site so I guess we can say there is a dogfooding...**
See #9128
Visit a page on the website with a trailing slash in the URL and inspect the canonical link using dev tools.
Then navigate to the same page without a trailing slash and inspect the canonical link using dev tools again.
If both versions of the page have the same URL then the bug is fixed.
https://github.com/facebook/docusaurus/assets/12466863/9e5dcd95-7c7f-4be9-87d4-4b6c8f566a1a
Deploy preview: https://deploy-preview-9130--docusaurus-2.netlify.app/
Closes #9128

fix(theme): canonical url should be not change after hydration if url accessed with/without trailing slash

---

packages/docusaurus-plugin-client-redirects/src/__tests__/__snapshots__/collectRedirects.test.ts.snap
packages/docusaurus-plugin-client-redirects/src/__tests__/__snapshots__/redirectValidation.test.ts.snap
packages/docusaurus-plugin-client-redirects/src/__tests__/__snapshots__/writeRedirectFiles.test.ts.snap
packages/docusaurus-plugin-client-redirects/src/__tests__/collectRedirects.test.ts
packages/docusaurus-plugin-client-redirects/src/__tests__/redirectValidation.test.ts
packages/docusaurus-plugin-client-redirects/src/__tests__/writeRedirectFiles.test.ts
packages/docusaurus-plugin-client-redirects/src/collectRedirects.ts
packages/docusaurus-plugin-client-redirects/src/createRedirectPageContent.ts
packages/docusaurus-plugin-client-redirects/src/index.ts
packages/docusaurus-plugin-client-redirects/src/options.ts
packages/docusaurus-plugin-client-redirects/src/redirectValidation.ts
packages/docusaurus-plugin-client-redirects/src/templates/redirectPage.template.html.ts
packages/docusaurus-plugin-client-redirects/src/writeRedirectFiles.ts
packages/docusaurus-utils-validation/src/__tests__/__snapshots__/validationSchemas.test.ts.snap
packages/docusaurus-utils-validation/src/validationSchemas.ts
website/_dogfooding/dogfooding.config.js
website/docusaurus.config.js

Fix https://github.com/facebook/docusaurus/issues/6845
The client redirect plugins should allow redirecting to:
- fully resolved URIs
- URLs with querystring and/or hash (fully resolved / absolute / relative)
The validation has been related to any string, because if we support full/absolute/relative almost all strings are valid candidates, and creating a robust validator for that is quite hard. 
Historically the redirects forwarded the `?search#anchor` from the redirect source. Now if the destination/target URL has a qs/hash, we don't do this forwarding anymore and consider the destination URL provided by the user is in its final form. We could improve that logic later if needed but that seems good enough for now.
Note: I'm not 100% sure this is perfectly retro-compatible,  some …

feat(client-redirects-plugin): support fully qualified urls and querystring/hash in destination/to url

---

website/docs/advanced/client.mdx

The `import type {Location} from 'history'` statement in the `myClientModule.js` snippet causes JavaScript to throw an error because an `import type` declaration works only in TypeScript files—not JavaScript.
So, I propose removing the declaration from the doc example to prevent confusing users.
```diff
- import type {Location} from 'history';
export function onRouteDidUpdate({location, previousLocation}) {
// Don't execute if we are still on the same page; the lifecycle may be fired
// because the hash changes (e.g. when navigating between headings)
if (location.pathname !== previousLocation?.pathname) {
const title = document.getElementsByTagName('h1')[0];
if (title) {
title.innerText += '❤️';
}
}
}
export function onRouteUpdate({location, previousLocation}) {
if (location.pathname !== …
```

docs: remove 'import type' declaration in javascript snippet

---

packages/docusaurus-theme-classic/src/theme/SiteMetadata/index.tsx
packages/docusaurus/src/client/SiteMetadataDefaults.tsx

Fixes issue #8887 by adding og locale and alternates
Tested locally in browser with suggested config
Deploy preview: https://deploy-preview-9152--docusaurus-2.netlify.app/
issue #8887

feat(theme): add support for meta og locale and alternates

---

packages/docusaurus-logger/README.md
website/docs/api/misc/logger/logger.mdx

Add the missing statement so the example is more self-contained.
@zenahr thanks for the issue, and FYI, the docs already start with this:
> It exports a single object as default export: `logger`. `logger` has the following properties:
Which means it should be default-imported (and of course, with TS downleveling; it doesn't work with native ESM default importing).

docs: add the missing import logger statement

---

argos/tests/screenshot.css

Argos tests report false positives because last-update dates between prod / pr produce a different layout (1 line vs 2 lines) depending on that update date.

test(argos): fix Argos visual tests flakiness, hide docs last-update element

---

packages/docusaurus-theme-common/src/components/ThemedComponent/styles.module.css

`<ThemedComponent/>` and `<ThemedIImage/>` should always display something for progressive enhancement reasons, even if `data-theme` is not set (JS disabled)
Currently it displays nothing:
Note: this is not an ideal solution but good enough for now.
In the future we should let the theme-classic "register" to core a default value for `data-theme` so that a fallback can be set without using any JS.
Currently with JS disabled the theme is always "light" even if the default colormode is dark.
Not a big deal for most users because people are more likely to have network issues than disabling JS, but this little issue led to flakiness in Argos/Playwright visual tests due to screenshots being taken before `data-theme` is set.
preview …

fix(theme-common): ThemedComponent should display something when JS is disabled

---

website/docs/swizzling.mdx

This sentence contrasts authoring React with authoring CSS. The previous version did this in a way that makes the React authoring seem like a more advanced activity (“actual (…) code”), and authoring CSS the less advanced (described as “playing with”). The rewording tries to address that.
Deploy preview: https://deploy-preview-9247--docusaurus-2.netlify.app/docs/swizzling/
Fixes #9246

docs: Reword comparison between React authoring and CSS authoring

---

packages/create-docusaurus/bin/index.js
packages/create-docusaurus/src/index.ts
project-words.txt
website/docs/api/misc/create-docusaurus.mdx

Detect usage of the `bun` package manager when executing the `create-docusaurus` CLI.
I couldn't find tests for the other package manager detection logic. Below are some successful run on my local machine.
With `npm_config_user_agent` set appropriately:
```sh
$ npm_config_user_agent=bun/1.0 node bin/index.js
✔ What should we name this site? … mysite
✔ Select a template below... › classic (recommended)
✔ This template is available in TypeScript. Do you want to use the TS variant? … yes
[INFO] Creating new Docusaurus project...
[INFO] Installing dependencies with bun...
bun install v0.7.4 (f74585ff)
Saved lockfile
+ @docusaurus/module-type-aliases@3.0.0-alpha.0
+ @docusaurus/tsconfig@3.0.0-alpha.0
+ @docusaurus/core@3.0.0-alpha.0
+ @docusaurus/preset-classic@3.0.0-alpha.0
+ …
```

feat: support bun package manager in `create-docusaurus`

---

.devcontainer/devcontainer.json

Cloning Docusaurus into a dev container volume ([explained in greater detail here](https://code.visualstudio.com/docs/devcontainers/containers#_quick-start-open-a-git-repository-or-github-pr-in-an-isolated-container-volume)) failed on arm64 devices like my Apple Silicon Mac:
```log
Error fetching image details: No manifest found for mcr.microsoft.com/vscode/devcontainers/base:ubuntu-20.04.
Start: Run: docker pull mcr.microsoft.com/vscode/devcontainers/base:ubuntu-20.04
Looking up Docker credential helper for 'mcr.microsoft.com'.
ubuntu-20.04: Pulling from vscode/devcontainers/base
no matching manifest for linux/arm64/v8 in the manifest list entries
```
This chore updates the dev container config to 22.04 for arm64 support and switches to the new [devcontainers …

chore: bump devcontainer to Ubuntu 22.04 to resolve arm64 incompatibility

---

argos/tests/screenshot.css
argos/tests/screenshot.spec.ts
packages/create-docusaurus/templates/classic-typescript/package.json
packages/docusaurus/src/client/App.tsx
packages/docusaurus/src/client/hasHydratedDataAttribute.tsx
yarn.lock

Fix Argos visual test flakiness found in https://app.argos-ci.com/meta-open-source/docusaurus/builds/186/56059354
I think it's related to anything that runs in `useEffect` instead of `useLayoutEffect`.
Let's introduce a `<html data-has-hydrated="true">` to be able to wait for `BrowserOnly` and other useEffect components to run.
Unfortunately it kind of requires merging to test and see if it works.
---
The Algolia keyboard shortcuts do not appear immediately and can create some flakiness:
---
Mermaid diagrams can lead to layout shifts leading to the end of the page being cropped
(related to https://github.com/microsoft/playwright/issues/620#issuecomment-1691403070)
---
There's also one related to the TOC highlighting:
We'll see if the data-attribute fixes it

test: fix flaky screenshots, add html data-has-hydrated attribute

---

argos/tests/screenshot.css

This CSS is not useful anymore, as since the MDX v2 upgrade it doesn't generate any Argos visual diff between main/PR

chore: remove useless Argos screenshot css

---

website/docs/guides/docs/docs-create-doc.mdx
website/versioned_docs/version-2.0.1/guides/docs/docs-create-doc.mdx
website/versioned_docs/version-2.1.0/guides/docs/docs-create-doc.mdx
website/versioned_docs/version-2.2.0/guides/docs/docs-create-doc.mdx
website/versioned_docs/version-2.3.1/guides/docs/docs-create-doc.mdx
website/versioned_docs/version-2.4.1/guides/docs/docs-create-doc.mdx
website/versioned_docs/version-3.0.0-alpha.0/guides/docs/docs-create-doc.mdx

Fix bad link for create doc
Nope

docs: fix bad link for create doc

---

website/src/pages/showcase/index.tsx

fix #9248 
Hii @slorber please  look into this.

fix(website): fix showcase search input

---

.cspell.json
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/errorBoundaryUtils.module.css
packages/docusaurus-theme-common/src/utils/errorBoundaryUtils.tsx
packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.tsx
packages/docusaurus-theme-live-codeblock/src/theme/Playground/styles.module.css
packages/docusaurus-theme-mermaid/package.json
packages/docusaurus-theme-mermaid/src/client/index.ts
packages/docusaurus-theme-mermaid/src/theme/Mermaid/index.tsx
website/_dogfooding/_pages tests/diagrams.mdx
yarn.lock

We upgrade Mermaid v9 to v10. Like all major version upgrades, Mermaid v10+ comes with its own breaking changes documented here:
- https://github.com/mermaid-js/mermaid/issues/4103
- https://github.com/mermaid-js/mermaid/releases/tag/v10.0.0
- https://github.com/mermaid-js/mermaid/blob/master/CHANGELOG.md#1000
The Docusaurus code has also evolved to adapt for those breaking changes, notably the fact `Mermaid.render` is async now.
In theory most Docusaurus Mermaid users shouldn't be affected by those changes that are handled internally in our Mermaid theme. But we can't be 100% sure, so make sure to read the full v10 changelog.
Fix https://github.com/facebook/docusaurus/issues/9032
Mermaid v10.4 comes with a few features that have been requested by Docusaurus users, notably:
- Mindmap: …

feat(theme-mermaid): upgrade Mermaid to v10.4 - handle async rendering

---

packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/versioned-site/community_versioned_sidebars/version-1.0.0-sidebars.json
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/versioned-site/versioned_sidebars/version-1.0.0-sidebars.json
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/versioned-site/versioned_sidebars/version-1.0.1-sidebars.json
packages/docusaurus-plugin-content-docs/src/__tests__/__fixtures__/versioned-site/versioned_sidebars/version-withSlugs-sidebars.json
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/__snapshots__/translations.test.ts.snap
packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/globalData.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/props.test.ts
packages/docusaurus-plugin-content-docs/src/__tests__/translations.test.ts
packages/docusaurus-plugin-content-docs/src/docs.ts
packages/docusaurus-plugin-content-docs/src/globalData.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/plugin-content-docs.d.ts
packages/docusaurus-plugin-content-docs/src/props.ts
packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/generator.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/postProcessor.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/utils.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars/postProcessor.ts
packages/docusaurus-plugin-content-docs/src/sidebars/processor.ts
packages/docusaurus-plugin-content-docs/src/sidebars/types.ts
packages/docusaurus-plugin-content-docs/src/sidebars/utils.ts
packages/docusaurus-plugin-content-docs/src/translations.ts
packages/docusaurus-theme-classic/src/theme/DocItem/index.tsx

Docusaurus v3 does not support anymore the legacy versioned sidebar files that add a versioned prefix to all doc ids and sidebar names.
For example, this versioned sidebar file is now invalid. 
```json
{
"version-v2.0.0/docs":[
"version-v2.0.0/introduction-to-relay",
"version-v2.0.0/prerequisites",
]
}
``` 
The fix is simple: remove the `version-v2.0.0/` prefix everywhere
Fix https://github.com/facebook/docusaurus/issues/6018
Very early Docusaurus v2 versions used to create versioned sidebar files with useless "versioned prefixes.
Example from an older version of the Relay website: https://github.com/facebook/relay/blob/main/website/versioned_sidebars/version-v2.0.0-sidebars.json
```json
{
"version-v2.0.0/docs":[
{
"type":"category",
"label":"Introduction",
"items":[
{
"type":"doc", …
```

chore(plugin-docs): remove legacy versioned prefix on doc ids and sidebar names in versioned sidebars

---

packages/docusaurus/bin/beforeCli.mjs

Fixes #9239. This is a really small modification. I just added a custom `borderStyle` to `boxenOptions`.
I changed `notifier` in `beforeCli` in `beforeCli.mjs` to:
```
updateNotifier({
pkg: {
"docusaurus",
version: '2.4.0',
},
// Check is in background so it's fine to use a small value like 1h
// Use 0 for debugging
updateCheckInterval: 0,
});
```
Screenshot ran in WebStorm with zsh:
#9239

fix(cli): disable vertical borders of the update notification

---

packages/docusaurus-theme-search-algolia/package.json
website/package.json
yarn.lock

Follow-up of https://github.com/facebook/docusaurus/pull/9148
Revert downgrade of Algolia DocSearch package after type issue being fixed in v3.5.2 (https://github.com/algolia/docsearch/pull/2007)
CI
Deploy preview: https://deploy-preview-9320--docusaurus-2.netlify.app/

chore(theme-search-algolia): revert docsearch package range downgrade after bugfix release

---

packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/__snapshots__/generator.test.ts.snap
packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/generator.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars/generator.ts
packages/docusaurus-theme-classic/src/theme/BlogPostItem/Container/index.tsx
packages/docusaurus-theme-classic/src/theme/BlogPostItem/Header/Author/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPage/Layout/styles.module.css
packages/docusaurus-theme-classic/src/theme/MDXComponents/Ul/index.tsx
packages/docusaurus-theme-classic/src/theme/SiteMetadata/index.tsx
packages/docusaurus-theme-common/src/utils/useAlternatePageUtils.ts
packages/docusaurus/src/client/App.tsx
packages/docusaurus/src/client/hasHydratedDataAttribute.tsx

chore: backport retro compatible commits for the Docusaurus v2.4.2 release
Deploy preview: https://deploy-preview-9324--docusaurus-2.netlify.app/
---
- [code PR](https://github.com/facebook/docusaurus/pull/9324) 
- [docs PR](https://github.com/facebook/docusaurus/pull/9325)

chore: backport retro compatible commits for the Docusaurus v2.4.2 release

---

website/docusaurus.config.js

i18n / Crowdin is often a reason why the production website build fails.
And Markdown broken links is a good subset of those i18n errors.
Example: https://app.netlify.com/sites/docusaurus-2/deploys/650db064f9a39f1221ed9487
Failing the prod build due to community translations is annoying, so let's only warn for localized broken links. 
Those broken links in i18n sites are less important and can be fixed in batch.

chore: do not fail the build if a localized site has a broken link

---

website/docusaurus.config.js

Broken link checker report errors due to blog post linking to 3.0 beta paths.
Follow-up of https://github.com/facebook/docusaurus/pull/9363 and https://github.com/facebook/docusaurus/pull/9374
local

chore: disable broken links check for i18n staging

---

packages/docusaurus-mdx-loader/src/loader.ts
packages/docusaurus-utils/src/webpackUtils.ts

This prevents `og:image` from being inserted directly into the page as base64 data, which prevents them from being visible on Twitter, Slack, Signal, etc. More details at https://github.com/facebook/docusaurus/issues/9345.
Simply build the main website and notice the new `build/assets/assets` folder.
Deploy preview: https://deploy-preview-9369--docusaurus-2.netlify.app/
- https://github.com/facebook/docusaurus/issues/9345

fix(mdx-loader): prevent Open Graph images from being inserted as base64

---

website/versioned_docs/version-2.4.3/deployment.mdx

this is already documented in the latest version by commit 35183d7d87df4935101a6bf62c98cb9cb7d7711b
See also #8877
This is also working for v2.4.3 and needed for using GitHub Pages and Actions with the default setting for the action's automatic GITHUB_TOKEN
Since v2.4.3 is the current version, which is shown by default, doc readers should also see the permission config, so they don't run into permission issues.
no code change, only mdx
Scroll down to `Triggering deployment with GitHub Actions`
* Tab `Same` -> Expander `GitHub action files` -> Code box `.github/workflows/deploy.yml`
* Tab `Remote` -> Expander `GitHub action files` -> Code box `.github/workflows/deploy.yml`
Deploy preview: https://deploy-preview-9377--docusaurus-2.netlify.app/docs/deployment#triggering-deployment-with-github …

docs(deployment): add permissions config to github action file in v2.4.3

---

website/docusaurus.config.js

The UA tracking id is now useless.
We can see in practice no data is collected anymore by this tracker:
See also https://github.com/facebook/docusaurus/issues/7221
[Google Analytics 4 has replaced Universal Analytics](https://support.google.com/analytics/answer/11583528)
> [Google Analytics 4](https://support.google.com/analytics/answer/10089681) is our next-generation measurement solution, and it has replaced Universal Analytics. Starting on July 1, 2023, standard Universal Analytics properties stopped processing new data. To maintain your website measurement, you'll need a Google Analytics 4 property. [Learn how to make the switch to Google Analytics 4](https://support.google.com/analytics/answer/10759417)
local (analytics are disabled in previews) …

chore: remove deprecated Google UA tracking id

---

packages/docusaurus-theme-classic/src/theme/Navbar/Search/index.tsx
packages/docusaurus-theme-classic/src/theme/Navbar/Search/styles.module.css

If a site has no search plugin, we shouldn't display the navbar search container container. 
It adds useless paddings and shifts the other navbar items.
Not an ideal solution but at least it works. CSS `:has` is going to be cross-browser supported very soon.
fix https://github.com/facebook/docusaurus/pull/7990
fix https://github.com/facebook/docusaurus/issues/8889
local only

fix(theme): avoid rendering empty search container if site has no search plugin

---

packages/docusaurus/src/client/clientEntry.tsx

See https://github.com/facebook/docusaurus/issues/9379
I hope to use this to diagose https://github.com/facebook/docusaurus/issues/9379
See https://github.com/facebook/docusaurus/issues/9379

fix(core): log missing errorInfo in React 18 onRecoverableError callback

---

.github/workflows/lighthouse-report.yml

I'm trying to make https://github.com/facebook/docusaurus/issues/9379 more visible.  This PR adds the blog URL of the Docusaurus website to the evalutated URLs.
If this surfaces console errors in lighthouse then it demostrates it's an underlying issue with the Docusaurus blog section - though weirdly one that only seems to surface on Ubuntu
https://github.com/facebook/docusaurus/issues/9379

chore: point lighthouse to blog to reproduce https://github.com/facebook/docusaurus/issues/9379

---

website/docs/migration/migration-manual.mdx

docs: fix typos in website/docs/migration/migration-manual.mdx

---

.github/workflows/argos.yml
argos/package.json
argos/playwright.config.ts
package.json
yarn.lock

Upgrade Argos experience.
Check Argos build.

chore(ci): use new Argos playwright integration

---

packages/docusaurus-theme-classic/src/theme/BlogArchivePage/index.tsx

Chronological ordering is confusing.
v3 is the best time to do this change. 
I'm considering it as an UX improvement, not a breaking change.
preview
https://deploy-preview-9438--docusaurus-2.netlify.app/blog/archive
https://github.com/johnnyreilly/blog.johnnyreilly.com/issues/327
https://github.com/facebook/docusaurus/pull/5428

refactor(blog-plugin): blog archive reverse ordering of posts

---

packages/docusaurus-theme-common/src/hooks/useWindowSize.ts

Fix https://github.com/facebook/docusaurus/issues/9379
CI does not report hydration issues
https://deploy-preview-9446--docusaurus-2.netlify.app/

fix(theme): fix useWindowSize React hydration issue

---

website/docs/migration/v3.mdx

Forgot to mention mdx v1 compat options
preview
https://deploy-preview-9452--docusaurus-2.netlify.app/docs/migration/v3

docs: v3 upgrade guide should mention MDX v1 compat options

---

packages/docusaurus-theme-classic/src/theme/Navbar/Search/styles.module.css

Bug introduced in https://github.com/facebook/docusaurus/pull/9385 by using CSS `:has()`
Prod build minifies/merge CSS rules, but lack of `:has` support in Firefox (coming soon in v121) prevents other CSS rules from being applied, leading to various bugs.
Using `@supports` prevent this from happening (see also https://www.bram.us/2023/01/04/css-has-feature-detection-with-supportsselector-you-want-has-not-has/#:~:text=To%20feature%20detect%20browser%20support,used%20in%20a%20feature%20query%20.)
More details in https://github.com/facebook/docusaurus/issues/9493
Fix https://github.com/facebook/docusaurus/issues/9493
Fix https://github.com/facebook/docusaurus/issues/9527
Fix https://github.com/facebook/docusaurus/issues/9525
Preview
https://deploy-preview-9530--docusaurus-2.netlify.app/

fix(theme): fix firefox CSS :has() support bug

---

packages/docusaurus-theme-common/src/utils/docsUtils.tsx

Bug introduced with the `frontMatter.unlisted` feature.
Docs sidebar items of types !== "link" or "category" shouldn't not be filtered out and hidden by default
Fix https://github.com/facebook/docusaurus/issues/9483
preview
Deploy preview: https://deploy-preview-9531--docusaurus-2.netlify.app/tests/docs
(we'll enable Argos visual regression tests on `/tests/` pages to catch this kind of bugs in the future)

fix(theme): docs html sidebar items should always be visible

---

packages/docusaurus-utils/src/__tests__/markdownUtils.test.ts
packages/docusaurus-utils/src/markdownUtils.ts
website/_dogfooding/_docs tests/tests/admonitions.mdx

Fix https://github.com/facebook/docusaurus/issues/9507
unit tests + preview
https://deploy-preview-9535--docusaurus-2.netlify.app/tests/docs/tests/admonitions#indented-admonitions

fix: v3 admonitions should support v2 title syntax for nested admonitions

---

website/blog/2023-09-29-preparing-your-site-for-docusaurus-v3/index.mdx
website/docs/migration/v3.mdx
website/versioned_docs/version-3.0.0/migration/v3.mdx

Make example code syntactically accurate.
```diff
- <div><p>Some <strong>Markdown</strong> content</p></div></div>
+ <div><p>Some <strong>Markdown</strong> content</p></div>
```
N/A (This is a doc update)
Deploy preview: https://deploy-preview-9545--docusaurus-2.netlify.app/
N/A

docs: delete duplicate closing div tag

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DropdownNavbarItem.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DropdownNavbarItem/index.tsx
packages/docusaurus-theme-classic/src/theme/NavbarItem/DropdownNavbarItem/styles.module.css

Fixed the issue where wrong cursor was displaying when hovering over any dropdown menu present in the navbar, when the screen size is small
Incorrect cursor:
Correct cursor:
#8485

fix(theme-classic): fixed wrong cursor on dropdown menu in navbar, when window is small

---

website/docs/api/plugins/plugin-content-blog.mdx
website/docs/api/plugins/plugin-content-docs.mdx
website/docs/api/plugins/plugin-content-pages.mdx

The motivation for this update is to address a common confusion regarding the use of the image in the documentation. Currently, the image specified is not displayed on the page itself but is crucial for the image meta tag, prominently used in link previews on social sharing platforms. This distinction is not explicitly clear in the existing documentation, leading to misunderstandings about the image's purpose and usage. The proposed changes aim to clarify this functionality, akin to how the description front matter is presently described.
This update is related to the issue raised in [facebook/docusaurus#9515](https://github.com/facebook/docusaurus/issues/9515), which discusses the need for clearer documentation regarding the role of the image in the Open Graph (OG) meta tag and its …

docs: enhance og image tag description in documentation

---

packages/docusaurus-utils/src/__tests__/markdownUtils.test.ts
packages/docusaurus-utils/src/markdownUtils.ts
website/_dogfooding/_docs tests/tests/admonitions.mdx

Docusaurus v3 regression reported in https://github.com/facebook/docusaurus/discussions/9336#discussioncomment-7630794
Follow-up of https://github.com/facebook/docusaurus/pull/9535
unit tests + preview
https://deploy-preview-9570--docusaurus-2.netlify.app/tests/docs/tests/admonitions#quoted-admonitions

fix: add v2 retrocompatible support for quoted admonitions

---

packages/create-docusaurus/templates/classic-typescript/package.json
packages/create-docusaurus/templates/classic/package.json
packages/docusaurus-theme-classic/package.json
packages/docusaurus-theme-common/package.json
yarn.lock

Address double clsx lib issue. See https://github.com/facebook/docusaurus/pull/9464#issuecomment-1821458197
Deploy preview: https://deploy-preview-9572--docusaurus-2.netlify.app/

chore: upgrade prism-react-renderer to 2.3.0 to avoid older clsx

---

website/blog/releases/3.0/index.mdx

Link is missing `/` at the beginning resulting in a broken link
Local build fixed the error
[Deploy preview page](https://deploy-preview-9573--docusaurus-2.netlify.app/blog/releases/3.0/#code-blocks)
Deploy preview: https://deploy-preview-9573--docusaurus-2.netlify.app/

docs: broken link in release 3.0 page

---

website/docs/guides/markdown-features/markdown-features-react.mdx
website/docs/migration/v3.mdx

docs: add heads up for Prettier users

---

README.md

fix https://github.com/facebook/docusaurus/issues/9590
we don't need that text anymore and it's probably useless to replace it with something else

docs: remove legacy useless readme section

---

website/docs/guides/creating-pages.mdx

People at Meta wanted to know it's possible to configure this behavior and eventually fail-fast, but couldn't find the info

docs: add link to onDuplicateRoutes page

---

packages/docusaurus-plugin-content-blog/src/__tests__/authors.test.ts
packages/docusaurus-plugin-content-blog/src/authors.ts
packages/docusaurus-plugin-content-blog/src/blogUtils.ts

Fix: #9577 
Local builds & unit tests 
Deploy preview: https://deploy-preview-9581--docusaurus-2.netlify.app/
#9577

fix(content-blog): add baseUrl for author.image_url

---

packages/docusaurus-module-type-aliases/src/index.d.ts

This PR would make TypeScript server stop complaining should one decide to use the "title" prop in imported inline SVG elements
fix https://github.com/facebook/docusaurus/issues/9609; this PR changes typing interface to adapt webpack behaviour.
0. Open up `docusaurus.new` and `yarn install` this change
1. In `src/components/HomePageFeatures` (or any other place), do 
```ts
import Mountain from '@site/static/img/undraw_docusaurus_mountain.svg';
const test = (): JSX.Element => (
<>
<Mountain role="img" />
<Mountain role="img" title="Wow cool dinosaur" />
</>);
```
2. Run `yarn typecheck`
3. Confirm that `tsc` does not complain
https://stackblitz.com/edit/github-sdux4y?file=src%2Fcomponents%2FHomepageFeatures%2Findex.tsx&view=editor …

fix(type-aliases): add `title` prop for imported inline SVG React components

---

packages/docusaurus-utils/src/__tests__/__snapshots__/markdownLinks.test.ts.snap
packages/docusaurus-utils/src/__tests__/markdownLinks.test.ts
packages/docusaurus-utils/src/markdownLinks.ts

We are once again complicating this algorithm 😅 It's because we cannot make `<>` get matched by the non-spaced link syntax.
@slorber Do you know if the write access is renewed automatically or if you have to poke someone again?

fix(utils): Markdown link replacement with <> but no spaces

---

packages/docusaurus-utils/src/constants.ts
packages/docusaurus/src/server/getHostPort.ts

Fix #8681 
Local test
Deploy preview: https://deploy-preview-9610--docusaurus-2.netlify.app/
#8681

feat(core): enable port configuration via environment variable

---

project-words.txt
website/docs/i18n/i18n-crowdin.mdx

Warning about a recent change in the Crowdin tag handling that will break docusaurus <-> Crowdin <-> MT workflow.
I've been bitten by a change in the Crowdin+MT behavior and I want to make sure other Docusaurus users know about it.
100% doc change
https://github.com/facebook/docusaurus/discussions/4052#discussioncomment-7796917

docs: Crowdin + MT issue

---

packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.tsx

Passing an inline unstable callback leads to a weird edge case of react-live out of sync editor/preview on theme change
It's likely a bug in react-live, but let's stabilize as a workaround anyway, it can also optimize a bit.
Fix https://github.com/facebook/docusaurus/issues/9630
preview
https://deploy-preview-9631--docusaurus-2.netlify.app/docs/markdown-features/code-blocks#interactive-code-editor

fix(live-codeblock): stabilize react-live transformCode callback, fix editor/preview desync

---

.github/workflows/lint-autofix.yml

Follow-up of https://github.com/facebook/docusaurus/pull/9604 which doesn't work yet
I'm not super confident this fix will work either unfortunately 😅 
See https://github.com/stefanzweifel/git-auto-commit-action/issues/211
This probably requires the usage unsafe of `pull_request_target`
See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

chore: attempt fo fix Lint Autofix workflow

---

packages/docusaurus/bin/docusaurus.mjs

- Delete `website/docusaurus.config.ts`
- Run `yarn docusaurus --help`
- See that it now outputs help instead of erroring
I'm not sure if this is a good solution, and I added a few TODOs.

fix(cli): output help when no conventional config + no subcommand

---

website/docs/guides/markdown-features/markdown-features-math-equations.mdx

Use a list of steps as the standard way to give instructions. 
Improve SEO for the `configuring` section.

docs(math): use list of steps for clearer guidance

---

packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts
project-words.txt
website/_dogfooding/_pages tests/code-block-tests.mdx

Add support for more comment style for MagicComments:
- (Visual) Basic (including .NET / for Applications)
- CMD (Batch)
- ML
- SML
- OCaml
- F#
- Fortran (90 or later & free format)
- COBOL (free format)
https://deploy-preview-9671--docusaurus-2.netlify.app/tests/pages/code-block-tests#magic-comments-tests
#8859
#8870

feat(theme-common): code block MagicComments support for (Visual) Basic/Batch/Fortran/COBOL/ML

---

website/docs/search.mdx

The previous documentation of the free Algolia DocSearch program only mentions open-source projects. At first this led me to believe I couldn't use it for our developer docs at Prefab (https://docs.prefab.cloud).
However, my understanding from reading https://docsearch.algolia.com/docs/who-can-apply/ is that DocSearch is free for **all** developer documentation, including commercial projects.
My change uses the same language as the above linked Algolia page for clarity and consistency.
N/A, this is only a documentation change.
Link to the changed page:
https://docusaurus.io/docs/search#using-algolia-docsearch
N/A

docs: Updates the Algolia DocSearch eligibility description to match DocSearch page

---

packages/create-docusaurus/README.md
packages/create-docusaurus/templates/shared/docs/tutorial-basics/markdown-features.mdx

The init template has problems we didn't notice when upgrading MDX, since MDX v2+ does not support indented code blocks anymore:
Fix problem reported in https://github.com/facebook/docusaurus/pull/9694 (+ other little improvements)
local
https://deploy-preview-9696--docusaurus-2.netlify.app/

fix(create-docusaurus): fix init template code blocks, and little improvements

---

packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/CodeInline/index.tsx
packages/docusaurus-theme-classic/src/theme/MDXComponents/Code.tsx
packages/docusaurus-theme-live-codeblock/src/theme-live-codeblock.d.ts
packages/docusaurus-theme-live-codeblock/src/theme/Playground/index.tsx
website/_dogfooding/_pages tests/code-block-tests.mdx

An empty code block should render as a code block, not an inline code block
An empty code block can be a live playground
Fix https://github.com/facebook/docusaurus/issues/9699
Note: MDX will emit no children prop if the code block is empty or has a single line, which is kind-of surprising but we'll handle it.
Also extracts `CodeInline` to make it easier to swizzle and customize without ejecting `<MDXCode/>` (the RN website does that)
(MDX v1 used to have a spacial `inlineCode` component but it was removed in v2: https://mdxjs.com/migrating/v2/)
dogfood + deploy preview
https://deploy-preview-9704--docusaurus-2.netlify.app/tests/pages/code-block-tests#empty-code-blocks-edge-cases

fix(theme): allow empty code blocks and live playgrounds

---

.cspell.json

Typos in MDX files are not checked in VS Code even if we have installed the cspell extension. It works only for JS/TS and vanilla Markdowns.
1. Install and enable [the cspell extension for VS Code](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
2. Open `README.md` in VS Code and add a typo there (still warned & don't save and just discard the change)
3. Open some other MDX files and add a typo there (now warned & don't save and just discard the change)
Note: content has not been changed
https://github.com/streetsidesoftware/vscode-spell-checker/issues/657

chore: check MDX even by VS Code cspell extension

---

website/docs/deployment.mdx
website/versioned_docs/version-3.1.0/deployment.mdx

Not having fetch-depth: 0 will lead to a bad "docs last update" date being rendered.
Also upgrading documented actions to newer versions
Fix https://github.com/facebook/docusaurus/issues/2798
https://deploy-preview-9759--docusaurus-2.netlify.app/docs/deployment#triggering-deployment-with-github-actions

docs: GitHub actions deployment should use fetch-depth: 0 + actions upgrades

---

website/docs/migration/v3.mdx

`**` in `**重要的中文。**其他的中文。` and `**重要な日本語の文。**別の日本語の文。` will not treated as `<strong>` due to a regression in CommonMark spec 0.14+.
MDX v2+ strictly follow CM and have this regression.
https://github.com/commonmark/commonmark-spec/issues/650
https://deploy-preview-9692--docusaurus-2.netlify.app/docs/migration/v3/#other-markdown-incompatibilities
https://github.com/commonmark/commonmark-spec/issues/650

docs: add admonition for incompatibility with `*` and `**` in Chinese and Japanese in MDX v2+

---

website/versioned_docs/version-3.1.1/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-3.1.1/migration/v3.mdx

The changes by those PRs are only applied in Canary and has not been read by many people.
Compare versions between Canary and 3.1.1
https://deploy-preview-9804--docusaurus-2.netlify.app/docs/migration/v3/
https://deploy-preview-9804--docusaurus-2.netlify.app/docs/3.1.1/migration/v3/
https://deploy-preview-9804--docusaurus-2.netlify.app/docs/markdown-features/react/
https://deploy-preview-9804--docusaurus-2.netlify.app/docs/3.1.1/markdown-features/react/
Deploy preview: https://deploy-preview-9804--docusaurus-2.netlify.app
#9471, #9692, and #9695

docs: backport #9471, #9692, and #9695 changes in v3.1.1 docs

---

website/docs/guides/markdown-features/markdown-features-diagrams.mdx
website/versioned_docs/version-3.1.1/guides/markdown-features/markdown-features-diagrams.mdx

Add docs for `<Mermaid />`
- https://github.com/facebook/docusaurus/issues/9815

docs: Add docs for Mermaid Component

---

website/docs/deployment.mdx

docs: fix typos in deployment.mdx

---

argos/package.json
argos/tests/screenshot.spec.ts
yarn.lock

Fix https://github.com/facebook/docusaurus/issues/9805

fix(argos): waiting for images decoding

---

project-words.txt
website/src/components/TeamProfileCards/index.tsx

Add new active members and move unactive member to honorary alumni team
Build & preview
Deploy preview: https://deploy-preview-9893--docusaurus-2.netlify.app/community/team

docs(team): update active docusaurus team member

---

website/src/components/TeamProfileCards/index.tsx

Wrong description on the production site
I don't know how translation id works, maybe its related to crowdin and not directly in source code ?
Deploy doesn't seem to be useful with the translate so I don't know
Deploy preview: https://deploy-preview-9946--docusaurus-2.netlify.app/community/team
#9893 deploy correctly shows the description but once deployed its replaced

docs(website): update wrong translate id

---

website/docs/introduction.mdx

Fix #9969.
Changed Vuepress to Vitepress under "Comparisons with other tools" in the introduction since it's a spiritual successor to Vuepress and also changed the link to direct it to the site
Deploy preview: https://deploy-preview-9971--docusaurus-2.netlify.app/

docs: replace VuePress by VitePress on tool comparison section

---

website/docs/deployment.mdx

Update Github Actions deployment instructions to use the more Github way of doing things, and remove dependency on third party actions. 
See this repo for an example successful run of the new instructions: https://github.com/vlad-nestorov/vlad-nestorov.github.io/actions/runs/8224051582/workflow
https://deploy-preview-9937--docusaurus-2.netlify.app/docs/deployment#triggering-deployment-with-github-actions

docs: use official GitHub Action to deploy to GitHub Pages

---

website/blog/releases/3.2/index.mdx

Headings in https://github.com/facebook/docusaurus/pull/10000 are not good

docs: fix 3.2 blog post headings

---

admin/new.docusaurus.io/functionUtils/playgroundUtils.ts

CodeSandbox repros we receive lately are private by default, which is annoying:
Apparently, new query string options have been implemented to prevent this, so let's figure what is the best for our use case.
https://twitter.com/CompuIves/status/1773028692752539825

chore: fix codesandbox default privacy

---

website/docusaurus.config.ts
website/src/pages/index.tsx

Change homepage and announcement bar to announce more easily new Docusaurus versions

docs(website): Announce v3.2 on website/homepage

---

website/docs/deployment.mdx

We changed GitHub action in #9937 and now the GitHub action doesn't use `gh_pages` branch anymore
Maybe we can add a new description like this :
> When triggered by a push to the main branch, the workflow builds a Docusaurus site, creates artifacts of that build, and deploys them to GitHub Pages.
Deploy
[Deployment](https://deploy-preview-9980--docusaurus-2.netlify.app/docs/deployment#triggering-deployment-with-github-actions)
#9937

docs: remove old github action description

---

packages/docusaurus-utils/src/gitUtils.ts

When the user shows signatures by default in his config (`git config log.showSignature true`), `getFileCommitDate` fails to parse the result because of the extra lines being printed, and the regexp to extract it not being able to process the command output due to the signature lines.
Problem reported here: https://github.com/facebook/docusaurus/pull/9954#issuecomment-2033742153
I'm now adding a `RESULT:` prefix so that we only attempt to parse the correct lines, ignore all the others.
Also, we don't need signatures to get the result, so I'm also passing `git -c log.showSignature=false log` as an option so that the command can execute faster. If users have signatures turned on, we don't want this function to be 3x slower.
```bash
hyperfine --runs 50 'git -c log.showSignature=true log …
```

fix(utils): getFileCommitDate should support `log.showSignature=true`

---

website/docs/advanced/routing.mdx
website/versioned_docs/version-2.x/advanced/routing.mdx
website/versioned_docs/version-3.0.1/advanced/routing.mdx
website/versioned_docs/version-3.1.1/advanced/routing.mdx
website/versioned_docs/version-3.2.1/advanced/routing.mdx

The example path in docs is incorrect. This PR fixes it. :)
```
markdown-features.mdx           # -> /docs/tutorial-basics/congratulations
```
should be
```
markdown-features.mdx           # -> /docs/tutorial-basics/markdown-features
```

docs: Fix wrong path example

---

website/docs/guides/markdown-features/markdown-features-plugins.mdx

[source](https://github.com/syntax-tree/unist-util-visit/blob/main/index.js)

docs: visit is a named export of unist-util-visit

---

packages/docusaurus-plugin-content-docs/src/sidebars/__tests__/utils.test.ts
packages/docusaurus-plugin-content-docs/src/sidebars/utils.ts

…file name as pagination label rather than the sidebar 'label' defined through item definition
Fixes #9781
Bug fix
Ran local tests which passed and compiled the demo website to ensure that it runs and the bug is fixed. 
Sample Doc file used without H1 or Title:
```md
test
```
Properties set in sidebar:
```js
{
type: 'doc',
label: 'Quick Start test',
id: 'test',
}
```
Results (2nd screenshot is of page before test, so see the next button to view updated pagination label):
Deploy preview: https://deploy-preview-10025--docusaurus-2.netlify.app/
#9781

fix(docs): sidebar item label impact the pagination label of docs

---

packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus/src/server/plugins/__tests__/routeConfig.test.ts
packages/docusaurus/src/server/plugins/plugins.ts
packages/docusaurus/src/server/plugins/routeConfig.ts

Fix https://github.com/facebook/docusaurus/issues/10052
Before:
```ts
export function sortRoutes(
routeConfigs: RouteConfig[],
baseUrl: string = '/',
): void
```
After:
```ts
export function sortRoutes(
routeConfigs: RouteConfig[],
baseUrl: string,
): void
```
The `baseUrl` should always be explicitly provided, otherwise if we forget it, we have route ordering bugs
unit tests

fix(core): sortRoutes shouldn't have a default baseUrl value, this led to a bug

---

.github/workflows/tests-e2e.yml
.github/workflows/tests-windows.yml
.github/workflows/tests.yml
website/docs/migration/v3.mdx
website/docs/typescript-support.mdx
website/versioned_docs/version-3.0.1/migration/v3.mdx
website/versioned_docs/version-3.0.1/typescript-support.mdx
website/versioned_docs/version-3.1.1/migration/v3.mdx
website/versioned_docs/version-3.1.1/typescript-support.mdx
website/versioned_docs/version-3.2.1/migration/v3.mdx
website/versioned_docs/version-3.2.1/typescript-support.mdx

We have no tests covering that we keep supporting older versions of TypeScript.
As we upgrade TypeScript on our monorepo, it's easy to be misled and release some libs that are incompatible with former TS versions.
Now we ensure that our website + starter remains compatible with TS 5.1
Note, although v3.0 is supposed to support TS 5.0, I think it never actually worked in practice. I can't get it working and get errors such as:
I suspect this is a bug related to the newly released v5.0 moduleResolution "bundler", but can't be sure. Starting v5.1 it works fine.
Also I think it's not a bad idea to require TS 5.1 in Docusaurus v3, because it permits to use ReactNode instead of `JSX.Element`: 
https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#decoupled-type-checking-between-js …

test(e2e): TypeCheck website/starter in min/max range of TS versions

---

package.json
yarn.lock

Upgrade to latest TS stable version
Note: I'm not yet using mode-resolution (ttps://github.com/microsoft/TypeScript/issues/49721) (TS 5.3) because:
- I need to check if it impacts user min TS version, it might be a breaking change
- Our version of Prettier does not support import attributes yet, we need to upgrade it first
```ts
import type {Transformer} from 'unified' with {"resolution-mode": "import"};
```
CI + min/max range tests (see https://github.com/facebook/docusaurus/pull/10063)
https://deploy-preview-10076--docusaurus-2.netlify.app/

chore: Upgrade to TypeScript 5.4

---

website/docs/api/docusaurus.config.js.mdx

docs: add note regarding ts extension for config file.

---

packages/docusaurus/src/commands/serve.ts

Fix https://github.com/facebook/docusaurus/issues/10078
`docusaurus serve` depends on [vercel/serve-handler](https://github.com/vercel/serve-handler)
This package is not super maintained and quite annoying to work with, particularly when we need to serve a static deployment under a baseUrl.
We can't do a rewrite from `/baseUrl/:path` to `/:path`, all requests end up as 404. I think the destination path must be an existing HTML files, not just a pathname.
Historically we have worked around that limitation thanks to the following hack:
```js
// Remove baseUrl before calling serveHandler, because /baseUrl/ should
// serve /build/index.html, not /build/baseUrl/index.html (does not exist)
req.url = req.url.replace(baseUrl, '/');
```
But the problem is that when the server handler is called …

fix(core): `docusaurus serve` redirects should include the site `/baseUrl/` prefix 

---

packages/docusaurus-theme-classic/src/theme/Admonition/Layout/index.tsx
website/_dogfooding/_pages tests/markdown-tests-mdx.mdx

closes #8568 
https://deploy-preview-10080--docusaurus-2.netlify.app/tests/pages/markdown-tests-mdx/#admonitions

fix(theme): `<Admonition>` should render properly without heading/icon

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx

By switching the priority of inner properties (`...tabs`) with input properties (`...props`), we allow the users to control the `selectedValue` (i.e. switch tabs), as well as to pass a hook `selectValue` to act on a tab switch.
This is a minor change that should improve UX while not changing anything else.
Existing tests should suffice, since no major change was introduced, only the place of the variables was swapped to give higher priority to the input props  
https://deploy-preview-10091--docusaurus-2.netlify.app/docs/markdown-features/tabs/
Related to this feature request: https://docusaurus.io/feature-requests/p/pass-active-attribute-to-tab-children

fix(theme): `<Tabs>` props should allow overriding defaults

---

packages/docusaurus-plugin-sitemap/src/__tests__/createSitemap.test.ts
packages/docusaurus-plugin-sitemap/src/__tests__/options.test.ts
packages/docusaurus-plugin-sitemap/src/createSitemap.ts
packages/docusaurus-plugin-sitemap/src/head.ts
packages/docusaurus-plugin-sitemap/src/options.ts
packages/docusaurus-plugin-sitemap/src/types.ts
website/docs/api/plugins/plugin-sitemap.mdx
website/docusaurus.config.ts

I presently mutate my sitemap manually on each build as a post processing step.  I've written about it [here](https://johnnyreilly.com/xml-read-and-write-with-node-js) and I have historically done this for two reasons:
1. To add `lastmod` to sitemap entries (something that is [no longer necessary as of 3.2](https://docusaurus.io/blog/releases/3.2#sitemap-lastmod))
2. To trim pagination, tags pages and programmatically determined canonicals from the sitemap - this is still necessary
If there was a hook that allowed control of the sitemap, I would no longer need to do 2 as a separate post processing step
Automated tests, plus look at the generated sitemap for the preview site: https://deploy-preview-10083--docusaurus-2.netlify.app/sitemap.xml
The screenshot below was taken from the current …

feat: add createSitemapItems hook

---

website/docs/search.mdx

Fixes some dead Typesense links that were pointing to `docs/latest/guide/foo` which does not redirect to a live page.
Deploy preview: https://deploy-preview-10093--docusaurus-2.netlify.app/

docs: Fix dead Typesense links

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus/src/client/clientEntry.tsx
packages/docusaurus/src/client/docusaurus.ts
project-words.txt

Fix React 18 hot reloading warning:
Initially reported here: https://github.com/facebook/docusaurus/issues/10099#issuecomment-2092738192
> Warning: You are calling ReactDOMClient.createRoot() on a container that has already been passed to createRoot() before. Instead, call root.render() on the existing root instead if you want to update it.
Note: this is not a React v18.3 warning, we can also have it in v18.2.
Note: Docusaurus does not have React Fast Refresh support, but we probably should have that. It [doesn't look super easy to support](https://github.com/facebook/react/issues/16604#issuecomment-528663101) 😅
CI + Tests
Local dev, hot reload works for both MD and JS files
https://deploy-preview-10103--docusaurus-2.netlify.app/

fix(core): do not recreate ReactDOM Root, fix React warning on hot reload

---

packages/docusaurus-theme-classic/src/theme/DocCard/index.tsx
packages/docusaurus-theme-translations/locales/base/theme-common.json
packages/docusaurus-theme-translations/locales/bn/theme-common.json
packages/docusaurus-theme-translations/locales/cs/theme-common.json
packages/docusaurus-theme-translations/locales/da/theme-common.json
packages/docusaurus-theme-translations/locales/de/theme-common.json
packages/docusaurus-theme-translations/locales/es/theme-common.json
packages/docusaurus-theme-translations/locales/fil/theme-common.json
packages/docusaurus-theme-translations/locales/fr/theme-common.json
packages/docusaurus-theme-translations/locales/he/theme-common.json
packages/docusaurus-theme-translations/locales/hi/theme-common.json
packages/docusaurus-theme-translations/locales/hu/theme-common.json
packages/docusaurus-theme-translations/locales/it/theme-common.json
packages/docusaurus-theme-translations/locales/nb/theme-common.json
packages/docusaurus-theme-translations/locales/nl/theme-common.json
packages/docusaurus-theme-translations/locales/pl/theme-common.json
packages/docusaurus-theme-translations/locales/pt-BR/theme-common.json
packages/docusaurus-theme-translations/locales/pt-PT/theme-common.json
packages/docusaurus-theme-translations/locales/sl/theme-common.json
packages/docusaurus-theme-translations/locales/sr/theme-common.json
packages/docusaurus-theme-translations/locales/sv/theme-common.json
packages/docusaurus-theme-translations/locales/tr/theme-common.json

Fix https://github.com/facebook/docusaurus/issues/10098
Category card description label should display "1 item" and not "1 items"
I tried to fix many languages as well using google translate, but there could be mistakes.
I have no idea how to translate ar/fa so left them untouched.
Note I choose to not use "One item" because it does not seem better for the UX, and I'm not sure how capitalization works for each locale.
preview
https://deploy-preview-10118--docusaurus-2.netlify.app/tests/docs/category/tests

fix(theme-translations): fix missing pluralization for label DocCard.categoryDescription.plurals

---

packages/docusaurus-module-type-aliases/src/index.d.ts
packages/docusaurus-theme-classic/src/index.ts
packages/docusaurus-theme-common/src/utils/storageUtils.ts
packages/docusaurus-types/src/config.d.ts
packages/docusaurus-types/src/context.d.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/src/server/__tests__/__snapshots__/config.test.ts.snap
packages/docusaurus/src/server/__tests__/__snapshots__/site.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/__tests__/site.test.ts
packages/docusaurus/src/server/__tests__/storage.test.ts
packages/docusaurus/src/server/codegen/codegen.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/server/site.ts
packages/docusaurus/src/server/storage.ts
website/_dogfooding/dogfooding.config.ts
website/_dogfooding/migrateStorageNamespace.ts
website/community/5-release-process.mdx
website/docs/api/docusaurus.config.js.mdx
website/docusaurus.config.ts

This introduces new site config options to let users control the default browser storage behavior of a Docusaurus site. 
Note: our themes respect that config, but third-party themes are not forced to, and it's only a default that can be ignored on a case-by-case basis.
It is useful to apply a namespace to browser storage keys, to avoid storage key conflicts on the same domain:
- Docusaurus devs might work on multiple sites locally (all under `http://localhost:3000`)
- Docusaurus sites might be hosted on the same domain using `/baseUrl/` (`https://example.com/site1/` + `https://example.com/site2/`). This is notably the case at Meta.
While we work on this, it's also a good opportunity to let users decide between `localStorage` or `sessionStorage` for browser persistence.
For …

feat(core): site storage config options (experimental)

---

website/blog/releases/3.3/index.mdx

chore: fix v3.3 blog post

---

packages/docusaurus/src/server/i18n.ts

Problem noticed in https://github.com/facebook/docusaurus/pull/10119
Note: we are not yet using Node v22 in the CI due to a v8 bug.
Unit tests do not pass under Node v22 due to a Intl behavior change. I don't know if it's a bug or if it's due to respecting the spec more strictly.
I fix this issue here, so that I can still use Node 22 locally.
unit tests

refactor: fix i18n bug in node v22

---

packages/docusaurus-utils/src/__tests__/hashUtils.test.ts
packages/docusaurus-utils/src/hashUtils.ts
packages/docusaurus/src/server/codegen/__tests__/codegenRoutes.test.ts
packages/docusaurus/src/server/codegen/codegenRoutes.ts

Fix https://github.com/facebook/docusaurus/issues/10125
When using docs `routeBasePath: '/'` and a category with `slug: '/'`, we end up with 2 prop module files named `index.json` in the plugin props dir, and one overrides the other leading to issues.
To solve this, we now always append a hash (previously there was an exception for path `/` returning `index`) that depends on both the route path but also the component name. It makes it much less likely to have a filename conflict.
Note: it's still technically possible to have a conflict. A more robust solution could be to hash the props object content, but it's slower. The current solution is good enough and fast.
Unit test 
Plus local test on the bug repro works:

fix(core): codegen should generate unique route prop filenames

---

packages/docusaurus/src/commands/serve.ts

Fix https://github.com/facebook/docusaurus/issues/10139
The workaround applied in https://github.com/facebook/docusaurus/pull/10090 lead to a regression for serving assets. I'm now applying this workaround more defensively.
The workaround impl is not 100% robust but should work fine for 99.9% of websites and only applies to sites using `docusauris serve` with a baseurl + trailingSlash.
no 😅 it works locally

fix(core): fix `docusaurus serve` broken for assets when using trailingSlash

---

website/docs/migration/v3.mdx
website/versioned_docs/version-3.3.2/migration/v3.mdx

Docusaurus v3 doesn't depend on `hast-util-is-element` unlike v2.
v2: https://docusaurus.io/docs/2.x/markdown-features/math-equations#configuration
v3: https://docusaurus.io/docs/markdown-features/math-equations#configuration
We probably can remove it when upgrading Docusaurus from v2 to v3.
https://docusaurus.io/docs/migration/v3#upgrading-math-packages

docs: recommend users to remove hast-util-is-element in migration to v3

---

.github/workflows/build-hash-router.yml

typo prevents workflow to run on main

chore: fix build-hash-router.yml workflow to trigger on main

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.tsx

The Algolia search container does not need to be added/removed constantly. This lead to a bug where `onOpen` would recreate it but `onInput` wouldn't so the modal does not actually show when typing chars while the Algolia button is focused.
Fix https://github.com/facebook/docusaurus/issues/10162
https://deploy-preview-10164--docusaurus-2.netlify.app/

fix(search): fix algolia search container bug

---

website/docs/guides/markdown-features/markdown-features-intro.mdx

The current example for `<details>` is not ideal one.
- There are extra `<div>` elements, which confuse readers (You don't have to use them; they. They're just optional and not mandatory)
- The contents in `<div>` confuse the block and inline notations
Block notation:
```mdx
<div>
paragraph inside `<div>` element
</div>
```
Inline notation:
```mdx
<div>no paragraphs in this line</div>
```
https://deploy-preview-10173--docusaurus-2.netlify.app/docs/markdown-features#details
https://deploy-preview-10173--docusaurus-2.netlify.app/docs/3.3.2/markdown-features#details
Deploy preview: https://deploy-preview-10173--docusaurus-2.netlify.app/

docs: improve how to use `<details>`

---

packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.tsx

Getting the Search page working for anyone without facets configured on Algolia index.
[#3805](https://github.com/facebook/docusaurus/issues/3805)

fix(theme): SearchPage should respect `contextualSearch: false` setting

---

website/docusaurus.config.ts

i18n site should be less strict in terms of `onInlineTags` setting otherwise our current site can't build due to existing front matter tags being translated and not appearing in `tags.yml`
It is a temporary solution and would be better to translate the tags file instead of the tags front matter in the future.
Site deploy works
https://deploy-preview-10191--docusaurus-2.netlify.app/
https://github.com/facebook/docusaurus/pull/10137

chore: unlock site deploy for i18n with onInlineTags warn

---

packages/docusaurus/src/webpack/client.ts

A site should be able to start/build without a `/static` dir
Fix https://github.com/facebook/docusaurus/issues/10212
Fix regression introduced with refactor in https://github.com/facebook/docusaurus/pull/9859
local test 😅

fix(core): fix sites unable to start/build without a static dir

---

packages/docusaurus-theme-classic/src/theme/Tabs/index.tsx
website/_dogfooding/_pages tests/tabs-tests.mdx

fix(theme): ignored className attribute on lazy loaded TabItem

---

website/docs/search.mdx
website/versioned_docs/version-2.x/search.mdx
website/versioned_docs/version-3.0.1/search.mdx
website/versioned_docs/version-3.1.1/search.mdx
website/versioned_docs/version-3.2.1/search.mdx
website/versioned_docs/version-3.3.2/search.mdx
website/versioned_docs/version-3.4.0/search.mdx

Hi docusaurus team, here's a small doc PR which replaces the temporary link to the DocSearch API reference with the proper one.
N/A
Deploy preview: https://deploy-preview-10233--docusaurus-2.netlify.app/docs/search/#customizing-the-algolia-search-behavior
None

docs(search): update docsearch api url

---

packages/docusaurus-plugin-client-redirects/src/index.ts
packages/docusaurus-plugin-google-analytics/src/index.ts
packages/docusaurus-plugin-google-gtag/src/index.ts
packages/docusaurus-plugin-google-tag-manager/src/index.ts
packages/docusaurus-plugin-pwa/src/index.ts
packages/docusaurus-plugin-sitemap/src/index.ts
packages/docusaurus-plugin-vercel-analytics/src/index.ts
packages/docusaurus-types/src/plugin.d.ts
packages/docusaurus/src/commands/swizzle/context.ts
packages/docusaurus/src/server/plugins/__tests__/__fixtures__/site-with-undefined-plugin/docusaurus.config.js
packages/docusaurus/src/server/plugins/__tests__/init.test.ts
packages/docusaurus/src/server/plugins/init.ts

A plugin should be able to self-disable depending on context/options by returning `null`
We actually need this for our own plugins:
```ts
export default function pluginPWA(
context: LoadContext,
options: PluginOptions,
): Plugin<void> | null {
if (process.env.NODE_ENV !== 'production') {
return null;
}
if (context.siteConfig.future.experimental_router === 'hash') {
logger.warn(
`${PluginName} does not support the Hash Router and will be disabled.`,
);
return null;
}
return {
name: PluginName, 
// rest of plugin here...
}
}
```
See also https://github.com/facebook/docusaurus/issues/10228#issuecomment-2217854540
unit tests
https://deploy-preview-10286--docusaurus-2.netlify.app/

feat(core): allow plugins to self-disable by returning null

---

packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx

Fix https://github.com/facebook/docusaurus/issues/10206
This ensures that the version dropdown "button" and the list item element are consistent and link to the same URL (the current doc, in that version)
Previously, the "button" would link to the root of the docs while the list item would link to the doc.
preview
https://deploy-preview-10288--docusaurus-2.netlify.app/

fix(theme): fix DocsVersionDropdownNavbarItem version link target

---

website/docs/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-3.2.1/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-3.3.2/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-3.4.0/guides/markdown-features/markdown-features-react.mdx

Warning is now useless because we fixed the limitation
replaces https://github.com/facebook/docusaurus/pull/10306

docs: remove deprecated partial toc warning

---

.github/workflows/tests-e2e.yml
.github/workflows/tests-windows.yml
.github/workflows/tests.yml

Temporary CI fix for https://github.com/nodejs/node/issues/53902 until Node 22.5.1 gets released

chore: fix CI, use Node 22.4 instead of 22.*

---

.github/workflows/build-perf.yml
packages/docusaurus/src/client/exports/Link.tsx
packages/docusaurus/src/client/exports/__tests__/Link.test.tsx

Revert anchor link change from https://github.com/facebook/docusaurus/pull/9859
Anchors should use regular `<a>` tag and not React Router links, like it used to be. Using React Router would "resolve" the anchors and add a `/pathname#anchor` instead of just `#anchor`.
I don't remember why I did that change in the first place. It is not wrong but produces unwanted bugs in community packages (see https://github.com/gabrielcsapo/docusaurus-plugin-search-local/issues/82#issuecomment-2236539091)
---
Edit: I remember now why I made the chang. The [new v3.4 hash router](https://docusaurus.io/blog/releases/3.4#hash-router---experimental) can't use a regular `<a href="#anchor">` tag because the target page is not `#anchor` but `/#/pathname#anchor`: we need to use React Router link in this case. …

fix(core): revert wrong anchor link implementation change

---

packages/docusaurus-plugin-google-gtag/src/index.ts
website/docs/api/plugins/plugin-google-gtag.mdx
website/versioned_docs/version-2.x/api/plugins/plugin-google-gtag.mdx
website/versioned_docs/version-3.0.1/api/plugins/plugin-google-gtag.mdx
website/versioned_docs/version-3.1.1/api/plugins/plugin-google-gtag.mdx
website/versioned_docs/version-3.2.1/api/plugins/plugin-google-gtag.mdx
website/versioned_docs/version-3.3.2/api/plugins/plugin-google-gtag.mdx
website/versioned_docs/version-3.4.0/api/plugins/plugin-google-gtag.mdx

[plugin-google-gtag](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag) has a broken link in its documentation:
* Current (broken): https://developers.google.com/analytics/devguides/collection/gtagjs/
* Fix: https://developers.google.com/tag-platform/gtagjs
This PR fixes the links for all versions.
\+ Also removing a redundant comment with invalid link from the source. https://github.com/facebook/docusaurus/pull/10338#discussion_r1690729118
> plugin-google-analytics has broken links as well, but I left it unchanged since the plugin is deprecated. See https://github.com/facebook/docusaurus/issues/10332#issuecomment-2245200880
Please refer to https://github.com/facebook/docusaurus/issues/10332#issuecomment-2245268943.

docs(plugin-google-gtag): replace the broken Google Developers links with valid ones

---

argos/tests/screenshot.spec.ts
packages/docusaurus-mdx-loader/src/remark/contentTitle/__tests__/index.test.ts
packages/docusaurus-mdx-loader/src/remark/contentTitle/index.ts
packages/docusaurus-mdx-loader/src/remark/head/index.ts

Fix #8476
For consistency, we want to wrap it all h1 in a `<header>` tag, for both of these cases:
- using `title: Title` front matter (already wrapped in `<header>`
- using `# Title` in the MDX doc (previously not wrapped in `<header>`, now fixed)
CI & argos
https://deploy-preview-10335--docusaurus-2.netlify.app/docs
We now have `<header><h1>` and not just `<h1>`
Argos reports small visual changes on `# Title` immediately followed by `## Section`, but in practice this is an improvement, consistent with front matter title behavior (less spacing)

feat(mdx-loader): wrap mdx content title (`# Title`) in `<header>` for concistency

---

project-words.txt
website/community/2-resources.mdx

Add `@getcanary/docusaurus-pagefind` in docs.
This is useful for users who 
1. want to use `Pagefind` as search index. 
2. want customizable search UI
None
None
None

docs: Add @getcanary/docusaurus-pagefind in docs

---

packages/docusaurus/bin/docusaurus.mjs

Fix https://github.com/facebook/docusaurus/issues/10367
- `docusaurus -h/--help` should exit with status code 0 instead of 1
- `docusaurus -V/--version` should print the version and not the help, and should exit with status code 0 instead of 1
This lets Commander handle version/help properly, and remove useless workaround code
local test by @slorber 
```bash
yarn workspace website docusaurus
yarn workspace website docusaurus --version
yarn workspace website docusaurus -V
yarn workspace website docusaurus -h
yarn workspace website docusaurus --help
yarn workspace website docusaurus start
yarn workspace website docusaurus build
yarn workspace website docusaurus docs:version myVersion
yarn workspace website docusaurus badCommand
yarn workspace website docusaurus --badOption
```

fix(cli): Fix bad docusaurus CLI behavior on for --version, -V, --help, -h

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.tsx

This fixes a UX bug. Ideally it gets fixed [upstream](https://github.com/algolia/docsearch/blob/3067715a6b9e10f3daf3275b620e9a82c02aade6/packages/docsearch-react/src/useDocSearchKeyboardEvents.ts#L60) I believe, for now I add the downstream hack.
See the testplan in https://github.com/facebook/docusaurus/issues/10333#issuecomment-2245764216.
Deploy preview: https://deploy-preview-10342--docusaurus-2.netlify.app/
Fixes https://github.com/facebook/docusaurus/issues/10333

fix(search): fix algolia search ignore ctrl + F in search input

---

packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-theme-search-algolia/src/client/useAlgoliaContextualFacetFilters.ts
yarn.lock

v3.5 is broken due to a bad import after refactoring.
https://github.com/facebook/docusaurus/pull/10382 probably fixes it but it's still not the public import for this API, so let's fix it properly.
CI
https://deploy-preview-10384--docusaurus-2.netlify.app/
Refactor that broke the import: https://github.com/facebook/docusaurus/pull/10316

fix(core): algolia context import

---

packages/docusaurus-theme-classic/src/theme/Blog/Components/Author/styles.module.css

As mentioned in https://github.com/facebook/docusaurus/issues/10389, this PR fixes an issue with descenders in lowercase letters (`g`, `j`, `p`, `q`, and `y`) in author titles being cut off.
> [!IMPORTANT]
>
> I tried to find all places where the styles needed to be changed, but please correct me if I missed any places or if the styles need to be adjusted elsewhere or in a different way🙇🏻‍♂️
Confirmed my changes appear as expected locally.
> [!NOTE]
>
> For problematic screenshots that show the issue, see https://github.com/facebook/docusaurus/issues/10389.
Deploy preview: https://deploy-preview-10390--docusaurus-2.netlify.app/
- https://github.com/facebook/docusaurus/issues/10389

fix(theme): Adjust blog authors line height to show descenders in lowercase letters (`g`, `j`, `p`, `q`, and `y`)

---

packages/create-docusaurus/templates/classic-typescript/docusaurus.config.ts
packages/create-docusaurus/templates/classic/docusaurus.config.js
packages/create-docusaurus/templates/shared/blog/2019-05-28-first-blog-post.md
packages/create-docusaurus/templates/shared/blog/2019-05-29-long-blog-post.md
packages/create-docusaurus/templates/shared/blog/2021-08-01-mdx-blog-post.mdx
packages/create-docusaurus/templates/shared/blog/2021-08-26-welcome/index.md
packages/create-docusaurus/templates/shared/blog/authors.yml
packages/create-docusaurus/templates/shared/blog/tags.yml
packages/docusaurus-plugin-content-blog/src/options.ts
project-words.txt

v3.5 templates do not lead to a great DX, printing the [2 new warnings](https://docusaurus.io/blog/releases/3.5#blog-consistency-options) we introduced recently:
This PR improves the templates and other little things:
- Add truncation marker to all posts, with HTML + MDX comment
- Replace inline author with global author
- Add authors pages for all the global authors, one having a custom URL
- Add consistency options to the blog config by default so that it's easier for users to turn them off
local, there's no way to test this in CI currently :/
https://deploy-preview-10392--docusaurus-2.netlify.app/

fix(create-docusaurus): Improve init templates blog setup + fix warnings

---

admin/test-bad-package/README.mdx
admin/test-bad-package/package.json
package.json
packages/docusaurus/package.json
packages/docusaurus/src/webpack/__tests__/__snapshots__/base.test.ts.snap
packages/docusaurus/src/webpack/base.ts
project-words.txt
website/_dogfooding/_docs tests/tests/import-bad-package.mdx
yarn.lock

This implements the suggestion here: https://github.com/facebook/docusaurus/issues/9027#issuecomment-2280046045
Using aliases ensures that when importing MDX partials from anywhere, React will always resolve to the site version instead of the local version.
```js
const ReactAliases = !!process.env.DOCUSAURUS_NO_REACT_ALIASES
? {}
: {
react: path.dirname(require.resolve('react/package.json')),
'react-dom': path.dirname(require.resolve('react-dom/package.json')),
};
```
Maybe it will cause problems for some sites so I'm including a secret env variable to disable this behavior, just in case. If you use it, please let us know why.
Dogfood test:
- fails before aliasing
- works after aliasing
https://deploy-preview-10391--docusaurus-2.netlify.app/tests/docs/tests/import-bad-package

fix(core): always alias React/ReactDOM to site dependency so that importing MDX from anywhere works

---

website/src/data/users.tsx

This PR addresses the issue of non-compliant entries in the `users.tsx` file by removing links that are not using Docusaurus.
Twelve non-compliant entries were identified and removed.
I am aware of the ongoing PR adding a showcase plugin to check links, but as of now, there are incorrect links in the showcase, including some that direct to sites with potential malware. 
I can address additional links problems in this PR if it's okay for you.
The changes were tested by verifying that each removed link no longer appears in the `users.tsx` file. 
Additionally, I've ensured that the remaining links are correctly listed.
#9967 
| URL                                       | Issue                                    |
| ----------------------------------------- | …

docs(showcase): remove sites not using Docusaurus anymore

---

packages/docusaurus-theme-common/src/index.ts

Restore theme-common API that we consider public.
This reverts an inadvertent breaking change I did while refactoring (https://github.com/facebook/docusaurus/pull/10316)
This breaking change breaks a local search plugin: https://github.com/cmfcmf/docusaurus-search-local/issues/217
This will be released as v3.5.2
local
https://deploy-preview-10397--docusaurus-2.netlify.app/

fix(theme-common): restore useContextualSearchFilters public API for retrocompatibility

---

packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/deploy.ts
packages/docusaurus/src/commands/serve.ts

Calling `exit(0)` this way at the end of the build is annoying for various reasons:
- it prevents adding custom bundle analyzer plugins, and any other thing that should keep the process alive
- it hides potential problems and memory leaks
It was introduced a long time ago in https://github.com/facebook/docusaurus/pull/2443 due to the build being stuck. I believe the underlying problem has been solved now. 
And if user code does a weird thing that gets the build stuck, they should rather know about it.
We'll see if that cause troubles in practice but I'd like to take my bet a remove this code for now. We'll eventually find an alternative solution if this becomes a problem.
CI
https://deploy-preview-10410--docusaurus-2.netlify.app/

refactor(core): remove useless build forceTerminate exit

---

packages/docusaurus-theme-translations/locales/es/theme-common.json

Improve spanish translations to keep the software understandable for all.
The previous translation was correct but it was too literal (spanish people would not understand what "Migas de pan" is in a website. Even developers). By using "Rastro de navegación" people would understand better the concept.
This does not fix any issue nor bug.
Spanish speakers can verify that the new translation is better to understand.
Deploy preview: https://deploy-preview-10413--docusaurus-2.netlify.app/

fix(translations): fix Spanish translation for "breadcrumbs"

---

packages/docusaurus-types/src/plugin.d.ts
packages/docusaurus/src/server/__tests__/__snapshots__/configValidation.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts

We should be able to write:
```tsx
async function plugin() {
return Math.random() > 0.5 ? null : {name: 'plugin'};
}
```
This requires changing the type from:
```tsx
Promise<Plugin<Content> | Promise<Plugin<null>
```
to 
```tsx
Promise<Plugin<Content> | null>
```
(also refactoring configValidation tests to make them more maintainable, no behavior change)
CI + new unit tests

fix(types): fix type of PluginModule

---

packages/docusaurus-mdx-loader/src/loader.ts
packages/docusaurus-mdx-loader/src/processor.ts

Webpack doc says about `this.query`: https://webpack.js.org/api/loaders/#thisquery
> If the loader was configured with an [options](https://webpack.js.org/configuration/module/#useentry) object, this will point to that object.
> If the loader has no options, but was invoked with a query string, this will be a string starting with ?.
This API we historically use is a bit confusing, and since mdx loader always has options, it always gives us the same as `this.getOptions()`. Let's only use once of these 2 APIs instead of a mix of both.
CI keeps working
Tested locally that mdx processor caching still works as expected
https://deploy-preview-_____--docusaurus-2.netlify.app/

refactor(mdx-loader): remove useless usage of mdx loader this.query

---

packages/docusaurus-types/src/plugin.d.ts
project-words.txt
website/docusaurus.config.ts
website/package.json
website/src/plugins/rsdoctor/RsdoctorPlugin.ts
yarn.lock

This plugin is quite useful for checking bundler performance. 
It was originally created for Rspack but can also work with Webpack so let's add it now to our website and use it to find out low hanging fruits we could optimize before upgrading to Rspack (see https://github.com/facebook/docusaurus/pull/10402)
CI keeps working
Local test of the plugin
https://deploy-preview-10418--docusaurus-2.netlify.app/

chore(website): add Rsdoctor plugin

---

.gitignore
package.json
packages/docusaurus-mdx-loader/src/loader.ts
packages/docusaurus-mdx-loader/src/remark/transformImage/index.ts
packages/docusaurus-mdx-loader/src/remark/transformLinks/index.ts
packages/docusaurus-utils/src/webpackUtils.ts
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/webpack/base.ts
packages/docusaurus/src/webpack/server.ts
website/package.json

While working on this PR, I discovered a few surprising facts so far:
- server compilation emits file-loader assets (so, they are emitted by both server/client compilations)
- server bundle is unexpectedly code split (chunks created in `website/build/server/assets/js`) and chunks were not removed from production deployments
Changes I made:
- Move server bundle generation to `website/build/server/*` instead of `website/build/*`
- Add a secret env variable to not delete it for inspection purposes
- Do not emit file-loader assets in server compilation (yes we did that, but it didn't cause problems nor real perf issues)
CI keeps working as before
No perf regression
`DOCUSAURUS_KEEP_SERVER_BUNDLE=true yarn build:website:fast` works locally and keeps the `website/build/server` folder
So far it …

refactor(core): improve handling of server bundle 

---

packages/docusaurus/src/webpack/base.ts
website/docs/styling-layout.mdx

For CSS modules, using clean class names in dev and hash in prod is confusing.
Users write CSS locally with selectors that only break after they deploy to production.
I believe it's better to have hashed class names in both environments to avoid this issue.
I consider this as a bugfix and an implementation detail.
CI + Argos
https://deploy-preview-10423--docusaurus-2.netlify.app/

fix(core): always use hash for CSS module class names

---

.github/workflows/argos.yml
.github/workflows/build-blog-only.yml
.github/workflows/build-hash-router.yml
.github/workflows/build-perf.yml
.github/workflows/canary-release.yml
.github/workflows/continuous-releases.yml
.github/workflows/lighthouse-report.yml
.github/workflows/lint.yml
.github/workflows/showcase-test.yml
.github/workflows/tests-e2e.yml
.github/workflows/tests-windows.yml
.github/workflows/tests.yml

- fix continous-release not using setup-node, using Node 18 instead of Node 22
- consistently use lts everywhere when we don't care
- e2e matrix: restore usage of node 22 instead of 22.4 (due to 22.5.0 bug)
CI
https://deploy-preview-10438--docusaurus-2.netlify.app/

chore(ci): fix setup-node, use LTS by default

---

packages/docusaurus-faster/src/index.ts
packages/docusaurus-types/src/config.d.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus/package.json
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/start/webpack.ts
packages/docusaurus/src/faster.ts
packages/docusaurus/src/server/__tests__/__snapshots__/config.test.ts.snap
packages/docusaurus/src/server/__tests__/__snapshots__/site.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/webpack/__tests__/base.test.ts
packages/docusaurus/src/webpack/base.ts
packages/docusaurus/src/webpack/client.ts
packages/docusaurus/src/webpack/minification.ts
packages/docusaurus/src/webpack/server.ts
packages/docusaurus/src/webpack/utils.ts
website/docs/api/docusaurus.config.js.mdx
yarn.lock

Docusaurus Faster project - part 2 - faster js minifier
(see [part 1](https://github.com/facebook/docusaurus/pull/10435))
Add experimental swcJsMinimizer option to make js minification faster.
It turns out `terser-webpack-plugin` default minimizer is slow and a real bottleneck representing 20-30% of total build time! 
The plugin offers an option to use a swc-based minimizer instead, which you can now toggle thanks to a new feature flag `siteConfig.future.experimental_faster.swcJsMinimizer`
Time to minimize JS on our website:
- Before: 18s
- After: 3s 🔥
I'm not sure the options are ideal, but I was conservative and only used a different tool with similar options, instead of fine-tuning the existing options. We
Note: in the future we'll be able to use the built-in [Rspack swc minimizer …

feat(core): faster JS minimizer - `siteConfig.future.experimental_faster.swcJsMinimizer`

---

packages/docusaurus/package.json
packages/docusaurus/src/webpack/utils.ts
yarn.lock

Before [migrating to Webpack 5](https://github.com/facebook/docusaurus/pull/4089), we used `null-loader` to ignore CSS files on the server.
Technically `null-loader` is deprecated as Webpack 5 recommends using `resolve.alias.pkgName = false` to ignore a dependency, our migrated code did not "ignore" the CSS files on the server like before. Unfortunately, I don't see how we could use `resolve.alias` to express what we want: we want to process `.module.css` files on the server (so that we inject a `styles` object into JS files, but ignore regular CSS imports (which we don't do anymore after the Webpack 5 upgrade).
Restoring `null-loader` permits restoring the former (Docusaurus Webpack 4) behavior and ignores regular CSS on the server to only consider CSS modules. 
It shouldn't change …

refactor(core): Restore null-loader

---

packages/docusaurus-mdx-loader/src/createMDXLoader.ts
packages/docusaurus-mdx-loader/src/index.ts
packages/docusaurus-mdx-loader/src/loader.ts
packages/docusaurus-mdx-loader/src/processor.ts
packages/docusaurus-mdx-loader/src/utils.ts
packages/docusaurus-plugin-content-blog/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-blog/src/index.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-pages/src/__tests__/index.test.ts
packages/docusaurus-plugin-content-pages/src/index.ts
packages/docusaurus/src/server/plugins/__tests__/plugins.test.ts
packages/docusaurus/src/server/plugins/plugins.ts
packages/docusaurus/src/server/plugins/synthetic.ts

Refactors mdx-loader
- improve `loader.ts` readability, extract support code to `utils.ts`
- expose async `createMDXLoader{Item,Rule}` APIs and use them in plugins
- fix processors caching system that does not work with Rsdoctor 
Note: `createMDXLoaderItem` APIs will be useful for upcoming encapsulation and perf optimizations
CI + preview
Behavior should be similar to before
https://deploy-preview-10450--docusaurus-2.netlify.app/

refactor(mdx-loader): refactor mdx-loader, expose loader creation utils

---

packages/docusaurus-remark-plugin-npm2yarn/package.json
yarn.lock

The upgrade should be retrocompatible and permit users to benefit from new `npx` conversions ([feature PR](https://github.com/nebrelbug/npm-to-yarn/pull/53))
Note: we won't use it on the Docusaurus website because `yarn dlx` is not supported by Yarn v1 😅 and there are too many Yarn 1 users (including ourselves). I think it's better to stick to `npx` for now.
CI + argos
https://deploy-preview-10454--docusaurus-2.netlify.app/

chore: upgrade npm-to-yarn to v3

---

website/blog/releases/3.5/index.mdx

Fix blog post typo, the plugin option ends with `s`

docs: fix v3.5 blog post typo - `onUntruncatedBlogPosts`

---

packages/docusaurus-plugin-content-docs/src/__tests__/index.test.ts
packages/docusaurus-types/src/bundler.d.ts
packages/docusaurus-types/src/config.d.ts
packages/docusaurus-types/src/index.d.ts
packages/docusaurus-types/src/plugin.d.ts
packages/docusaurus/src/commands/build.ts
packages/docusaurus/src/commands/start/webpack.ts
packages/docusaurus/src/server/__tests__/__snapshots__/config.test.ts.snap
packages/docusaurus/src/server/__tests__/__snapshots__/site.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/webpack/__tests__/base.test.ts
packages/docusaurus/src/webpack/__tests__/client.test.ts
packages/docusaurus/src/webpack/__tests__/configure.test.ts
packages/docusaurus/src/webpack/__tests__/server.test.ts
packages/docusaurus/src/webpack/base.ts
packages/docusaurus/src/webpack/client.ts
packages/docusaurus/src/webpack/configure.ts
packages/docusaurus/src/webpack/currentBundler.ts
packages/docusaurus/src/webpack/plugins/StaticDirectoriesCopyPlugin.ts
packages/docusaurus/src/webpack/server.ts
packages/docusaurus/src/webpack/utils.ts
project-words.txt
yarn.lock

Preliminary refactor that implements the boilerplate needed for adding experimental Rspack support as a config flag.
The real support will be added later here: https://github.com/facebook/docusaurus/pull/10402/files
CI
https://deploy-preview-10497--docusaurus-2.netlify.app/

refactor(core): prepare codebase for swappable bundler

---

admin/scripts/formatLighthouseReport.js

Google won't store Lighthouse reports anymore (temporarily or definitively? 🤷‍♂️ ) leading to the `links` parameter being always empty `{}`.
I refactored the Markdown comment formatting function so that it can handle that case and temporarily fix the CI until we know more about Google plans
See:
- https://github.com/treosh/lighthouse-ci-action/issues/144
- https://github.com/GoogleChrome/lighthouse-ci/issues/1072
- https://github.com/GoogleChrome/lighthouse-ci/issues/1073
CI
https://deploy-preview-10527--docusaurus-2.netlify.app/

chore: fix formatLighthouseReport() CI

---

admin/scripts/formatLighthouseReport.js

Fix little typo in https://github.com/facebook/docusaurus/pull/10527
The condition is interverted 😅

chore: fix interverted condition in formatLighthouseReport.js

---

admin/scripts/formatLighthouseReport.js
packages/docusaurus-bundler/src/importFaster.ts
packages/docusaurus-bundler/src/minification.ts
packages/docusaurus-faster/package.json
packages/docusaurus-faster/src/index.ts
packages/docusaurus-types/src/config.d.ts
packages/docusaurus/src/server/__tests__/__snapshots__/config.test.ts.snap
packages/docusaurus/src/server/__tests__/__snapshots__/site.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/configValidation.ts
project-words.txt
website/testCSSOrder.mjs
yarn.lock

Docusaurus Faster project - part 3 - faster CSS minimizer using LightningCSS
(see [part 1](https://github.com/facebook/docusaurus/pull/10435), [part2](https://github.com/facebook/docusaurus/pull/10441))
[LightningCSS](https://lightningcss.dev/) is built in Rust and a much faster alternative to many tools we use today: PostCSS, cssnano...
I don't expect CSS minification to be a major bottleneck in terms of build time, but as part of [adding Rspack support](https://github.com/facebook/docusaurus/pull/10402) it will become even faster by using Rust tooling for the whole CSS chain, using a built-in lightningCSS integration.
Also, I'm adding this option so that users can turn LightningCSS on independently from Rspack. It's possible that depending on feedback we'll activate Lightning CSS as a …

feat(core): faster CSS minimizer - `siteConfig.future.experimental_faster.lightningCssMinimizer`

---

website/docs/installation.mdx

Attempt to minimise support requests asking if the reported `npm install` vulnerabilities are harmful.
Feel free to adjust the message if necessary.
- https://github.com/facebook/docusaurus/discussions/10525#discussioncomment-10775852

docs: add tip about harmless vulnerabilities

---

website/src/components/APITable/index.tsx
website/src/components/APITable/styles.module.css

While reading at [`API` section](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-content-docs#configuration) I intent to highlighting `name` of the API to copy, but the row keep moving to top.
This PR add support for user to highlighted text while keeping the table to focus on top when clicked.
preview
https://deploy-preview-10534--docusaurus-2.netlify.app/docs/api/plugins/@docusaurus/plugin-content-docs#configuration

fix(website): APITable component should navigate to anchor less agressively

---

packages/docusaurus-mdx-loader/src/createMDXLoader.ts
packages/docusaurus-mdx-loader/src/loader.ts
packages/docusaurus-mdx-loader/src/options.ts
packages/docusaurus-mdx-loader/src/remark/unusedDirectives/index.ts
packages/docusaurus-mdx-loader/src/utils.ts

Fix https://github.com/facebook/docusaurus/issues/10544
The MDX cross-compiler cache is an experimental feature introduced in https://github.com/facebook/docusaurus/pull/10479
It permits us to avoid transforming twice the same MD/MDX source file for both client/server environments.
It takes the assumption that both environments will compile exactly the same. This is mostly true, apart from a tiny detail that led to broken images in productions: inline file loaders.
Since the MDX compilation for both envs is run in parallel, a file might be compiled in client or server mode depending on which env compilation started first and got cached. This leads to some image inline loaders to have `?emit=true` or `?emit=false` randomly for the client-side app, while we always want it to have …

fix(mdx-loader): fix cross-compiler cache randomly loading mdx with client/server envs

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Facebook is officially called Meta now, so I thought it's worth changing the important Markdown documents to reflect this update - I didn't want to mess with the actual code too much as I'm not very experienced.
N/A
Deploy preview: https://deploy-preview-10566--docusaurus-2.netlify.app/
N/A

docs: rename Facebook to Meta in GitHub-related Markdowns

---

packages/docusaurus-bundler/package.json
packages/docusaurus/package.json

`@docusaurus/faster` was supposed to be optional, but it was not due to my mistake after extracting the `@docusaurus/bundler` package.
CI

fix(core): move @docusaurus/faster to bundler peerDeps

---

packages/docusaurus-bundler/src/minifyHtml.ts
packages/docusaurus/src/ssg.ts

The HTML SWC minifier diagnostic errors are too aggressive to throw
When we collect errors, we emit them as warnings with the ability to disable that warning, considering those markup errors existed before and are non-critical.
I created a troubleshooting guide for users looking to fix these warnings here: https://github.com/facebook/docusaurus/discussions/10580
CI + local tests
https://deploy-preview-_____--docusaurus-2.netlify.app/

fix(core): fix handling of Swc html minifier warnings

---

.github/workflows/lint.yml
admin/verdaccio.yaml
packages/docusaurus/package.json
yarn.lock

We forked the lib to fix annoying Node 22 punycode warning: 
- https://github.com/facebook/docusaurus/pull/10442
- https://github.com/vercel/serve-handler/issues/204#issuecomment-2307892921
Now a Vercel maintainer has taken over the maintenance of the lib and just published a fix:
https://github.com/vercel/serve-handler/releases/tag/6.1.6
We can move back to the official dependency
CI

refactor(core): replace serve-handler fork by official deps

---

.github/workflows/tests-e2e.yml
.github/workflows/tests.yml
packages/docusaurus-logger/src/logger.ts
packages/docusaurus-logger/src/perfLogger.ts

Related to https://github.com/facebook/docusaurus/issues/4765
Follow-up of https://github.com/facebook/docusaurus/pull/9975
This enhance the `DOCUSAURUS_PERF_LOGGER=true` env variable described in https://github.com/facebook/docusaurus/issues/4765#issuecomment-2066227919
Our infrastructure should make it easy to figure out which step consumes Node.js heap memory:
For now, it only logs before/after memory, but we could enhance this later with sampling and add an average memory consumption for each recorded step.
Note I'd also like to wire all this to our CI in the future so that PRs can report memory usage regressions, similar to what Astro is doing here:
- https://github.com/withastro/astro/pull/9603#issuecomment-1876740130
- https://github.com/withastro/astro/blob/main/.github/workflows/b …

feat(core): add Node.js memory perf logging

---

packages/docusaurus-theme-classic/src/theme/ColorModeToggle/index.tsx

- [X ] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
yarn start
open webpage and use nvda to test that the aria-pressed is saying if the button is pressed or if the button is not pressed
https://deploy-preview-10585--docusaurus-2.netlify.app/

fix(theme): light & dark mode checkbox doesn't announce state switches

---

.gitignore
packages/docusaurus/src/client/serverEntry.tsx
packages/docusaurus/src/commands/build/build.ts
packages/docusaurus/src/commands/build/buildLocale.ts
packages/docusaurus/src/commands/deploy.ts
packages/docusaurus/src/commands/serve.ts
packages/docusaurus/src/common.d.ts
packages/docusaurus/src/index.ts
packages/docusaurus/src/ssg/ssg.ts
packages/docusaurus/src/ssg/ssgNodeRequire.ts
project-words.txt

When building a localized Docusaurus site, the memory would keep growing as we iterate sequentially over the locales to build. This can lead to potential out-of-memory errors for locales at the end.
Each localized site would keep a lot of strings in memory, related to the server bundle modules. This is because we run SSG using [node-eval](https://github.com/pierrec/node-eval) which is a tiny wrapper around `vm.Script`. 
Unfortunately, `vm.Script` doesn't really isolate memory like workers or subprocesses. At the end of the SSG process, many strings remain retained in memory related to the localized server-side JS modules loaded during the SSG process.
When we run SSG, the `require()` calls in the server bundle are using the `createRequire(serverBundlePath)` we provide to globals. The …

fix(core): fix i18n sites SSG memory leak - require.cache

---

packages/docusaurus/bin/docusaurus.mjs
packages/docusaurus/src/commands/build/build.ts
packages/docusaurus/src/commands/build/buildLocale.ts
packages/docusaurus/src/commands/deploy.ts
packages/docusaurus/src/server/i18n.ts
website/docs/cli.mdx

We already support:
- `docusaurus build` (all locales)
- `docusaurus build --locale fr` (single locale)
This adds support for:
- `docusaurus build --locale fr --locale en`
Same for `docusaurus deploy`
Note: we don't plan to support this for other commands like `docusaurus start` due to technical limitations.
local test only 😅 
https://deploy-preview-10600--docusaurus-2.netlify.app/

feat(cli): build/deploy should allow multiple `--locale` options

---

.github/workflows/build-perf.yml
.github/workflows/tests-e2e.yml
.github/workflows/tests.yml

Add CI checks to ensure that the perf gains from [Docusaurus Faster](https://github.com/facebook/docusaurus/issues/10556) remain permanent.
This notably ensures that:
- We track build sizes for both faster/slower builds (Webpack/Rspack) because both setups can regress
- Rspack is fast even in cold builds
- Building 2 locales in a row doesn't leak memory (see https://github.com/facebook/docusaurus/pull/10599)
CI
https://deploy-preview-10601--docusaurus-2.netlify.app/

perf(ci): Add CI checks to prevent memory, build-time and build-size regressions

---

packages/docusaurus-bundler/src/importFaster.ts
packages/docusaurus-bundler/src/loaders/jsLoader.ts
packages/docusaurus-bundler/src/minification.ts
packages/docusaurus-faster/src/index.ts

Ensure SWC loader options are consistent for the SWC one and the Rspack built-in one.
Ensures SWC loader respects browserslist config like Babel does.
CI

fix(core): Use proper swc loader options

---

.github/workflows/canary-release.yml

Canary workflow didn't trigger after https://github.com/facebook/docusaurus/pull/10612
Let's fix that + allow manual trigger if needed

chore: fix canary trigger

---

packages/docusaurus-theme-classic/src/theme/prism-include-languages.ts

While trying to upgrade Redocusaurus to Docusaurus Faster (https://github.com/rohit-gohri/redocusaurus/pull/385) I have weird SSG errors after trying to build with swc instead of babel-loader.
Redoc also uses Prism and those errors go away if we restore the Prism global namespace pollution after the prism-react-renderer init. This code should rather keep the pollution in place if something else is working with Prism.
Not sure how to test this 😅 
https://deploy-preview-10618--docusaurus-2.netlify.app/
---
For context, those SSG errors were:
```bash
[PERF] Build > en > SSG > Generate static files > Load App renderer - 39.85 ms - (169mb -> 180mb)
[PERF][KO] Build > en > SSG > Generate static files - 369.23 ms - (169mb -> 187mb)
[PERF][KO] Build > en > SSG - 369.75 ms - (169mb -> 187mb) …
```

fix(theme): Restore former globalThis.Prism

---

packages/docusaurus-bundler/src/loaders/jsLoader.ts

Rspack + babel-loader works fine, I tested this localy.
This is not a config we'd recommend, but remains useful for troubleshooting purpose and incremental adoption.
No 😅 it's expensive to create CIs for all possible permutations of faster options 😅

fix(faster): allow Rspack + babel-loader

---

website/docs/api/docusaurus.config.js.mdx

Those [Docusaurus Faster](https://github.com/facebook/docusaurus/issues/10556) options are ready to release so let's write a bit more docs since I didn't while iterating.
https://deploy-preview-10630--docusaurus-2.netlify.app/docs/api/docusaurus-config#future

docs: Add missing API ref docs for Docusaurus Faster options

---

website/docs/guides/markdown-features/markdown-features-intro.mdx
website/docs/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-3.0.1/guides/markdown-features/markdown-features-intro.mdx
website/versioned_docs/version-3.0.1/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-3.1.1/guides/markdown-features/markdown-features-intro.mdx
website/versioned_docs/version-3.1.1/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-3.2.1/guides/markdown-features/markdown-features-intro.mdx
website/versioned_docs/version-3.2.1/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-3.3.2/guides/markdown-features/markdown-features-intro.mdx
website/versioned_docs/version-3.3.2/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-3.4.0/guides/markdown-features/markdown-features-intro.mdx
website/versioned_docs/version-3.4.0/guides/markdown-features/markdown-features-react.mdx
website/versioned_docs/version-3.5.2/guides/markdown-features/markdown-features-intro.mdx
website/versioned_docs/version-3.5.2/guides/markdown-features/markdown-features-react.mdx

Current doc was wrong, it's `frontMatter.mdx.format` and not `frontMatter.format`.
Fix https://github.com/facebook/docusaurus/issues/10628
Also edited all the related GitHub issues to not mislead anyone.

docs: fix frontMatter.mdx.format docs

---

packages/docusaurus-bundler/src/currentBundler.ts
packages/docusaurus/src/webpack/client.ts

Adjust code so that Rspack compilation progress bars can have same colors as before.
Unfortunately, their underlying Rust lib [indicatif](https://github.com/console-rs/indicatif) doesn't have the exact same interface as webpackbar, but the `template` option permits to restore former colors.
See also https://rspack.dev/plugins/webpack/progress-plugin for available Rspack options.
---
Also there's a bug in Rspack integration of Indicatif: when using multiple compiler configs (client/server) the progress bars do not look that great and are somehow merged in a weird way. 
This issue won't fix that problem, we need Rspack to use Indicatif [MultiProgress](https://docs.rs/indicatif/latest/indicatif/struct.MultiProgress.html) in that case.
See also …

fix(core): restore Rspack ProgressBar colors

---

packages/docusaurus-bundler/package.json
packages/docusaurus-faster/package.json
packages/docusaurus-utils-common/package.json
packages/docusaurus-utils/package.json

Fix `@docusaurus/faster` peerDependency not using `*` range. For some reason when publishing, the version is not bumped, see https://github.com/facebook/docusaurus/discussions/10641#discussioncomment-11153736
Also removed `@docusaurus/types` from peerDependency. It's unclear why it has a peerDep for some packages and not others in the first place.
CI
https://deploy-preview-10649--docusaurus-2.netlify.app/

fix(faster,utils): fix faster/types peerDependencies

---

packages/docusaurus-mdx-loader/src/remark/admonitions/index.ts
packages/docusaurus-mdx-loader/src/remark/contentTitle/index.ts
packages/docusaurus-mdx-loader/src/remark/details/index.ts
packages/docusaurus-mdx-loader/src/remark/head/index.ts
packages/docusaurus-mdx-loader/src/remark/headings/index.ts
packages/docusaurus-mdx-loader/src/remark/mdx1Compat/codeCompatPlugin.ts
packages/docusaurus-mdx-loader/src/remark/mermaid/index.ts
packages/docusaurus-mdx-loader/src/remark/resolveMarkdownLinks/index.ts
packages/docusaurus-mdx-loader/src/remark/toc/index.ts
packages/docusaurus-mdx-loader/src/remark/transformImage/index.ts
packages/docusaurus-mdx-loader/src/remark/transformLinks/index.ts
packages/docusaurus-mdx-loader/src/remark/unusedDirectives/index.ts

I wrote a remark plugin and was not sure how i have to type the plugins correctly. So i checked with docusaurus' default plugins and saw that they are not properly typed aswell and that the structure between the remark-plugins is not really streamlined.
In my research i found the solution: type the plugins with `Plugin<PluginOptions[], Root>` and let them return a `Transformer<Root>` (instead of `Transformer` only). Like that, TS can infer the types directly:
```ts
const plugin: Plugin<PluginOptions[], Root> = function plugin(
options,
): Transformer<Root> {
return async (root, vfile) => {
const {visit} = await import('unist-util-visit');
visit(root, 'link', (node, index, parent) => {
// link is now known to be of type Link
// parent is of type `Parent | undefined`  and index: `number | …
```

refactor(mdx-loader): streamline typescript usage for remark plugin types

---

packages/docusaurus-bundler/src/loaders/__tests__/jsLoader.test.ts
packages/docusaurus-bundler/src/loaders/jsLoader.ts
packages/docusaurus-types/src/config.d.ts
packages/docusaurus/src/server/__tests__/__fixtures__/siteMessages/siteWithBabelConfigFile/babel.config.js
packages/docusaurus/src/server/__tests__/siteMessages.test.ts
packages/docusaurus/src/server/site.ts
packages/docusaurus/src/server/siteMessages.ts

We want to:
- prevent usage of both `webpack.jsLoader` and `faster.swcJsLoader` at the same time to avoid ambiguity (easy to forget to delete `webpack.jsLoader`, see https://github.com/remotion-dev/remotion/pull/4460#discussion_r1827947848)
- encourage users to delete the useless `babel.config.js` file once Docusaurus Faster is enabled
CI
https://deploy-preview-10655--docusaurus-2.netlify.app/

refactor(faster,bundler,core): improve js loader DX

---

argos/tests/screenshot.spec.ts

Argos screenshot fails due to expected console errors
We don't need to screenshot that page anyway

test(argos): skip screenshot for /tests/pages/react-18

---

website/docs/styling-layout.mdx
website/versioned_docs/version-3.2.1/styling-layout.mdx
website/versioned_docs/version-3.3.2/styling-layout.mdx
website/versioned_docs/version-3.4.0/styling-layout.mdx
website/versioned_docs/version-3.5.2/styling-layout.mdx
website/versioned_docs/version-3.6.0/styling-layout.mdx

A docs page references the wrong/old base TS config to extend.
We have our own `@docusaurus/tsconfig` now

docs: fix old base ts config ref

---

.eslintignore
.prettierignore
.stylelintignore
packages/docusaurus/src/webpack/plugins/StaticDirectoriesCopyPlugin.ts
website/_dogfooding/_asset-tests/badSyntax.css
website/_dogfooding/_asset-tests/badSyntax.js
website/tsconfig.json

We are using Webpack [copy-webpack-plugin](https://webpack.js.org/plugins/copy-webpack-plugin/) to expose static assets from the `website/static` dir.
These files are supposed to be exposed as-is, not being modified.
Unfortunately, we had a regression in Docusaurus v3.4 and the css/js minimizes started to be applied to these files as well. This is because I moved the copy plugin from webpack server config (minimizers disabled) to the client config (minimizers enabled): 
https://github.com/facebook/docusaurus/commit/17f3e02a4244b1893b7624ec3c948bfa926feacd
(there are good reasons to do so, in particular now that the server is built into a `__server` subfolder)
CI + added a dogfood test to prevent regressions (site failed to build before I apply the fix) …

fix(core): bundler should not minimize static assets

---

website/docs/configuration.mdx
website/versioned_docs/version-3.6.1/configuration.mdx

The documentation for [customizing the babel config](https://docusaurus.io/docs/configuration#customizing-babel-configuration) says to install `@docusaurus/theme-live-codeblock`, then use the `@docusaurus/babel/preset` in the config file. This should tell the user to install `@docusaurus/babel` instead. 
N/A
Deploy preview: https://deploy-preview-10666--docusaurus-2.netlify.app/
N/A

docs: fix package name in babel config docs

---

packages/create-docusaurus/templates/classic-typescript/tsconfig.json

TypeScript should not try to typecheck the `.docusaurus` and `build` folders. It can slow TS down after a site build.
For now I'm adding this to our init template TS config.
(note, I already did that on our own website)
The plan is to move this to our base preset, but this requires using TS 5.5+ configDir variable placeholder:
https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#the-configdir-template-variable-for-configuration-files
CI

fix(create-docusaurus): add ts exclude to TS init template

---

website/src/data/tweets.tsx

I was browsing the [Docusaurus](https://docusaurus.io/) homepage and spotted a few typos. so, I cloned the repo to fix those, and while I was at it, I noticed a few other things to update like switching links to https and refreshing twitter handles.
`-`
`-`
`-`

fix(homepage): typo corrections and updated twitter handles

---

.github/workflows/argos.yml
.github/workflows/build-blog-only.yml
.github/workflows/build-hash-router.yml
.github/workflows/build-perf.yml
.github/workflows/canary-release.yml
.github/workflows/continuous-releases.yml
.github/workflows/lighthouse-report.yml
.github/workflows/lint-autofix.yml
.github/workflows/lint.yml
.github/workflows/showcase-test.yml
.github/workflows/tests-e2e.yml
.github/workflows/tests-swizzle.yml
.github/workflows/tests-windows.yml
.github/workflows/tests.yml

CI jobs often fail due to random network errors/timeouts.
See https://x.com/sebastienlorber/status/1857356618314502149
> sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-linux-x64.tar.br
> sharp: Installation error: connect ETIMEDOUT 140.82.114.3:443
There are many other cases like https://github.com/facebook/docusaurus/actions/runs/11312636188/job/31460294187
It's annoying to restart them manually, so let's add 3 retry. We already had retries like this for Windows workflows, let's normalize this practice.
CI

chore(ci): retry `yarn install` to ignore temporary network errors

---

packages/docusaurus-theme-live-codeblock/src/theme/Playground/styles.module.css

Infima applies `border-radius` by default to `pre` elements, leading to unexpected radius here:
See https://github.com/facebook/docusaurus/issues/6032#issuecomment-2481803877
CI + argos
https://deploy-preview-10689--docusaurus-2.netlify.app/

fix(theme-live-codeblock): fix live editor border-radius

---

packages/docusaurus-module-type-aliases/src/index.d.ts
website/_dogfooding/_pages tests/embeds.tsx

Fix https://github.com/facebook/docusaurus/issues/10640
This should type check by default without any error:
```tsx
import Partial from './_partial.mdx';
export default function MyPage() {
return <Partial/>
}
```
CI + dogfood
https://deploy-preview-10693--docusaurus-2.netlify.app/

fix(types): add missing ambiant TS declarations for .md / .mdx partials

---

.github/workflows/tests-e2e.yml
packages/docusaurus-tsconfig/tsconfig.json

Surprisingly, our e2e test suite only runs TS type-check for yarn berry (node linker only).
CI e2e tests should type-check the newly initialized sites to ensure no site is initialized with any TS errors
Fix https://github.com/facebook/docusaurus/issues/9080
CI

fix(create-docusaurus): Fix TS issues on newly initialized sites

---

packages/docusaurus/src/webpack/base.ts

Fix https://github.com/facebook/docusaurus/issues/10646
See https://github.com/facebook/docusaurus/issues/10646#issuecomment-2490675451, Rspack `experiments.incremental = true` in dev lead to HMR bugs.
Let's disable it for now, we may try to turn this on later once it's more stable. Eventually, add a Docusaurus Faster flag for it.
nop 😅

fix(core): disable Rspack incremental in dev

---

website/docs/migration/v2/migration-versioned-sites.mdx

the example  of "Convert style attributes to style objects in MDX" using &lt;pre&gt; tag but missing “&lt;” and fix it
create a new website using docusaurus and try the example with `pre style={{background: 'black'}}>zzz</pre>` i got error, add "&lt;" solved the error.
just start docusaurus and see the doc content

docs: fix example typo for migration-versioned-sites.mdx

---

packages/docusaurus/src/server/codegen/__tests__/codegenRoutes.test.ts
packages/docusaurus/src/server/codegen/codegenRoutes.ts

Fix https://github.com/facebook/docusaurus/issues/10718
In rare cases (1/1000), sites can encounter an object key / hash collision that breaks sites. 
This has probably never been reported before because the collision self-resolves when you edit the site a bit. But it's still annoying.
The problem is documented here: https://github.com/facebook/docusaurus/issues/10718#issuecomment-2507635907
Note the implemented solution is not ideal but will be much less likely to create collisions and it will fail with a clearer error message when the case occurs.
unit tests + CI
https://deploy-preview-10727--docusaurus-2.netlify.app/

fix(core): fix codegen routesChunkName possible hash collision 

---

packages/docusaurus-theme-common/src/utils/storageUtils.ts

This workaround shouldn't be needed anymore since we use React 18
CI
https://deploy-preview-10728--docusaurus-2.netlify.app/

refactor(theme-common): change storageUtils useSyncExternalCode getSnapshot workaround

---

packages/docusaurus-plugin-content-blog/src/__tests__/frontMatter.test.ts
packages/docusaurus-plugin-content-blog/src/__tests__/props.test.ts
packages/docusaurus-plugin-content-blog/src/frontMatter.ts
packages/docusaurus-plugin-content-blog/src/plugin-content-blog.d.ts
packages/docusaurus-plugin-content-blog/src/props.ts
website/_dogfooding/_blog tests/2023-08-05.mdx
website/docs/api/plugins/plugin-content-blog.mdx

New useful front matter to customize how blog posts are displayed in the blog sidebar, as requested here: 
https://github.com/facebook/docusaurus/pull/10586#issuecomment-2459170155
Note we already have the same option for docs already.
CI + dogfood
https://deploy-preview-10729--docusaurus-2.netlify.app/tests/blog/2023/08/05

feat(blog): Add `frontMatter.sidebar_label` 

---

website/docs/installation.mdx
website/docs/typescript-support.mdx
website/docusaurus.config.ts

I came across an older project that still referenced the `docusaurus-init` package, which has been converted into `create-docusaurus` in #5635. I had a hard time figuring this out because the current docs don't make any mention of this, and the [npm page for the old package](https://www.npmjs.com/package/@docusaurus/init) doesn't indicate that it's been replaced either.
So I added links from the current initial setup docs to the page describing `create-docusaurus`, as well as a redirect from 'docusaurus-init' to 'create-docusaurus', so that people can still find the current page even when searching for the old name.
Direct links to affected pages:
- [/docs/installation](https://deploy-preview-10740--docusaurus-2.netlify.app/docs/installation)
- …

docs: Link initialization docs together

---

packages/docusaurus/src/commands/swizzle/__tests__/__snapshots__/actions.test.ts.snap
packages/docusaurus/src/commands/swizzle/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus/src/commands/swizzle/actions.ts

`docusaurus swizzle` TS wrapper should use `ReactNode` instead of `JSX.Element` improving React 19 compatibility
Follow-up of: https://github.com/facebook/docusaurus/pull/10746
Related to: https://github.com/facebook/docusaurus/pull/10745
CI has swizzle wrap ts workflows

refactor(core): swizzle wrap should use ReactNode instead of JSX.Element

---

packages/docusaurus-plugin-content-docs/src/client/__tests__/docsUtils.test.tsx
packages/docusaurus-plugin-content-docs/src/client/docsUtils.tsx
website/_dogfooding/_docs tests/tests/visibility/some-unlisteds/subcategory-with-listed-index/index.mdx
website/_dogfooding/_docs tests/tests/visibility/some-unlisteds/subcategory-with-listed-index/unlisted1.mdx
website/_dogfooding/_docs tests/tests/visibility/some-unlisteds/subcategory-with-listed-index/unlisted2.mdx

Fix bug where category with listed doc index is hidden instead of staying visible
Fix https://github.com/facebook/docusaurus/issues/10749
Unit tests + dogfood
https://deploy-preview-10754--docusaurus-2.netlify.app/tests/docs/tests/visibility
https://deploy-preview-10754--docusaurus-2.netlify.app/tests/docs/tests/visibility/some-unlisteds/subcategory-with-listed-index

fix(docs): fix sidebar item visibility bug for category index

---

website/docs/swizzling.mdx

While customizing the theme, I noticed there is very limited guidance on how to remove swizzled components. The only mention I found was in the "Which component should I swizzle?" section, which states: "Don't forget to unswizzle the rest by deleting the files after you've found the correct one, so you don't maintain too many components." 
As a junior developer, I found this explanation insufficient for understanding the exact steps needed to properly remove swizzled elements. Therefore, I decided to add a more explicit tip. I hope this addition will help other developers—especially those who are new to Docusaurus or not yet confident in their development skills—use the tool more effectively.
```
:::tip Removing Unneeded Swizzled Components
If you decide that a previously swizzled …
```

docs: add swizzle delete tip

---

website/blog/2022/08-01-announcing-docusaurus-2.0/ShowcaseCarousel.module.css
website/blog/2022/08-01-announcing-docusaurus-2.0/ShowcaseCarousel.tsx
website/package.json
yarn.lock

On our v2 release blog post we have image carousels:
https://docusaurus.io/blog/2022/08/01/announcing-docusaurus-2.0
The implementation depends on a `react-pure-carousel` lib that is only used on this single page.
This is causing troubles in our CI when trying to upgrade to React 19
(see https://github.com/express-labs/pure-react-carousel/issues/476)
So I'm getting rid of the library in favor of a simpler custom carousel implementation.
This is a website-only refactor that doesn't affect any Docusaurus user apart us. Also this page is old and does not really receive traffic so it's not a big deal if the new carousel is not perfect. We only keep it for historical reasons.
preview
https://deploy-preview-10784--docusaurus-2.netlify.app/blog/2022/08/01/announcing-docusaurus-2.0
Failing React …

refactor(website): remove pure-react-carousel

---

packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts
website/_dogfooding/_pages tests/code-block-tests.mdx

- [ x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
Code block magic comments should support SQL block comments `/* comment */`
Dogfood / preview
https://deploy-preview-10782--docusaurus-2.netlify.app/tests/pages/code-block-tests#magic-comments-tests
Fix #10748

fix(theme-common): code block magic comments should support SQL block comments

---

packages/docusaurus-theme-classic/src/options.ts
packages/docusaurus-theme-classic/src/theme/Footer/LinkItem/index.tsx
packages/docusaurus-theme-classic/src/theme/Footer/Links/MultiColumn/index.tsx
packages/docusaurus-theme-classic/src/theme/Footer/Links/Simple/index.tsx
packages/docusaurus-theme-common/src/utils/useThemeConfig.ts
website/docusaurus.config.ts

We should be able to assign `className` to footer columns/items
The className should be merged to the default class instead of overriding it, for consistency with the behavior of navbar items, as suggested here: https://github.com/facebook/docusaurus/issues/10785#issuecomment-2558135890
```tsx
{
footer: {
style: 'dark',
links: [
{
title: 'Legal',
className: 'footer-column-legal',
items: [
{
label: 'Privacy',
className: 'footer-item-privacy',
href: 'https://opensource.facebook.com/legal/privacy/',
},
],
},
],
},
}
```
CI + dogfood on preview site footer
https://deploy-preview-10796--docusaurus-2.netlify.app/

fix(theme): Footer Column/Link should merge provided className

---

packages/docusaurus-theme-search-algolia/src/theme-search-algolia.d.ts
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.tsx
website/docusaurus.config.ts

Although placeholder/button/modal translations are provided through our i18n support (`docusaurus write-translations`), it should be possible for non-localized sites to provide labels through `themeConfig.algolia` since it's more convenient.
Fix https://github.com/facebook/docusaurus/issues/10774
Dogfood locally:
```ts
algolia: {
appId: 'X1Z85QJPUV',
apiKey: 'bf7211c161e8205da2f933a02534105a',
indexName: 'docusaurus-2',
placeholder: 'TEST',
translations: {
button: {
buttonText: 'BUT',
},
},
```
Before dogfood revert: 
https://676d73221292100008784f50--docusaurus-2.netlify.app/
PR:
https://deploy-preview-10799--docusaurus-2.netlify.app/

fix(algolia): properly forward placeholder/translations to DocSearch components

---

packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.tsx

This historical component is quite a mess
Let's extract custom hooks for related things to see clearer and group related code to separate functions
CI + preview, it should work as before
Deploy preview: https://deploy-preview-10801--docusaurus-2.netlify.app/

refactor(algolia): simplify SearchBar component

---

.devcontainer/devcontainer.json

Upgrades Dev Container to Ubuntu 24.04 base and Node 22 (latest LTS)
Also migrates VSCode configuration/settings to correct place in schema
Adds a fairly hacky workaround for #10769 where if the `start` or `serve` commands are ran within Remote Containers it will default to `127.0.0.1` instead of `localhost`. Ideally this would have been a cleaner refactor, or fixed somewhere upstream (ie vscode forwards port correctly, or webpack dev server support dual-stack binding)
#10769

chore: Devcontainer upgrade to Ubuntu Noble & Node 22

---

packages/docusaurus-remark-plugin-npm2yarn/README.md
packages/docusaurus-remark-plugin-npm2yarn/src/__tests__/__snapshots__/index.test.ts.snap
packages/docusaurus-remark-plugin-npm2yarn/src/__tests__/index.test.ts
packages/docusaurus-remark-plugin-npm2yarn/src/index.ts

Hi there 👋
This PR enables passing `bun` to the `npm2yarn` converter. The option is already available to the underlying [`npm-to-yarn` package](https://github.com/nebrelbug/npm-to-yarn) since [v2.1.0](https://github.com/nebrelbug/npm-to-yarn/releases/tag/v2.1.0) (and we are already using v3.0.0).
Deploy preview: https://deploy-preview-10803--docusaurus-2.netlify.app/

fix(npm-to-yarn): add missing npm-to-yarn converter for Bun

---

package.json

Include the packageManager field in package.json to specify the version of Yarn used for the project.
Corepack will use the specified version to ensure consistency across environments.
https://nodejs.org/api/corepack.html
Deploy preview: https://deploy-preview-10807--docusaurus-2.netlify.app/

chore: specify package manager version in package.json

---

packages/docusaurus-faster/package.json
packages/docusaurus/src/webpack/base.ts
project-words.txt
yarn.lock

This tries again to turn on Rspack incremental rebuilds:
https://rspack.dev/blog/announcing-1-1#new-incremental-rebuild
We initially shipped in v3.6, this but encountered issues and had to revert:
https://github.com/facebook/docusaurus/issues/10646#issuecomment-2487310052
https://github.com/facebook/docusaurus/pull/10712
@hardfist advised us:
> incremental flags is still in early experimental stage, we may consider enable it by default for rspress users first when we think it's stable enough, and when it's stable in rspress and then progressively enable it by default in rsbuild and rspress.
we don't have stats how many users encounter this bug compared to users enable it cause we don't do telemetry in rspack now.
As far as I understand, incremental has been released in Rspress v1.38 2 …

feat(core): Turn Rspack incremental on by default (again)

---

packages/docusaurus-logger/src/perfLogger.ts

This is mostly internal code but my perflogger start/end system wasn't working properly due to bad assumption I had of how `performance.measure()` works. It was only visible when building with the hash router because most code is using `perflogger.async()` instead of `start() / end()`
local 😅

fix: perflogger mark detail bug

---

packages/docusaurus-plugin-debug/package.json
packages/docusaurus-plugin-debug/src/theme/DebugJsonView/index.tsx
packages/docusaurus-plugin-debug/src/theme/DebugJsonView/styles.module.css
yarn.lock

React 19 support is expected to be released in the next v2.x of that lib. 
It just a peerDeps declaration normally: https://github.com/AnyRoad/react-json-view-lite/pull/43
So let's upgrade to v2 so that we'll benefit from the React support once it's released. There shouldn't be any side effects since v2 only bumps React to v18+ which we already run on.
I'll consider it resolved from our side, although users can track the external issue to know when the peerDeps problem is fixed: https://github.com/AnyRoad/react-json-view-lite/issues/34. Will eventually reopen if the lib doesn't ship v2.x with React 19 support.
fix https://github.com/facebook/docusaurus/issues/10817
CI + preview
https://deploy-preview-10819--docusaurus-2.netlify.app/__docusaurus/debug

chore(plugin-debug): upgrade react-json-view-lite to v2, prepare for React 19

---

packages/docusaurus-plugin-svgr/src/index.ts
packages/docusaurus-plugin-svgr/src/svgrLoader.ts
packages/docusaurus-types/src/plugin.d.ts
packages/docusaurus-utils/src/webpackUtils.ts
packages/docusaurus/src/webpack/base.ts
project-words.txt
website/_dogfooding/dogfooding.css
website/_dogfooding/red.svg

When I extracted our v3.7 SVGR plugin from Docusaurus core (https://github.com/facebook/docusaurus/pull/10677), I also removed default support for SVG file loaders.
Users rely on it to reference local SVG files from CSS:
https://github.com/facebook/docusaurus/pull/10677#issuecomment-2572243680
Although the v3.7.0 SVGR plugin brings that support, it's not really its responsibility to do so.
This PR restores file-loader support for SVGs, even if sites do not use the SVGR plugin (which is included by default in our preset). Asking sites not using SVGR to use the SVGR plugin so that they benefit from SVG file-loader would be a bit awkward.
Unfortunately, the underlying solution is not super elegant due to how Webpack rules work, and registering a second svg rule will not "override" the first, …

fix(core): restore core svg file-loader

---

website/docs/introduction.mdx

Adds comparison to rspress, helping other developers get a clearer view of the differences
preview
https://deploy-preview-10822--docusaurus-2.netlify.app/docs/#rspress
Closes #10732

docs(website): Comparison with Rspress

---

packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/CodeBlock/Content/String.tsx
packages/docusaurus-theme-common/src/internal.ts
packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts
website/docs/guides/markdown-features/markdown-features-code-blocks.mdx

We should be able to provide the "counter start" for code block line numbering:
See also https://github.com/facebook/docusaurus/discussions/8858
Preview + dogfood + argos
https://deploy-preview-10846--docusaurus-2.netlify.app/docs/markdown-features/code-blocks#line-numbering

feat(theme): code block showLineNumbers=start metastring

---

packages/docusaurus-plugin-content-docs/src/client/__tests__/docsUtils.test.tsx
packages/docusaurus-plugin-content-docs/src/client/docsUtils.tsx
packages/docusaurus-plugin-content-docs/src/client/index.ts
packages/docusaurus-theme-classic/src/theme/DocCardList/index.tsx
website/_dogfooding/_docs tests/index.mdx

It was previously impossible to use this component (at least without providing an explicit `items` prop) for documents at the root of the sidebar. 
Bug reported here: 
- https://github.com/facebook/docusaurus/discussions/9923
- https://github.com/facebook/docusaurus/discussions/10828
This only worked by default if the docs were inside a category.
CI + dogfood + unit test + argos
https://deploy-preview-10847--docusaurus-2.netlify.app/tests/docs/

fix(theme): Fix `<DocCardList>` usage on docs at root of a sidebar

---

packages/create-docusaurus/templates/classic-typescript/docusaurus.config.ts
packages/create-docusaurus/templates/classic/docusaurus.config.js

We want newly initialized sites to be compatible with Docusaurus v4 by default.
Adding the future flag v4 permits to ensure those sites do not introduce any incompatibility.
CI
https://deploy-preview-10871--docusaurus-2.netlify.app/
https://github.com/facebook/docusaurus/pull/10850

refactor(create-docusaurus): add `future.v4` flag to init templates

---

packages/docusaurus-theme-classic/src/__tests__/options.test.ts
packages/docusaurus-theme-classic/src/options.ts
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx
website/docs/api/themes/theme-configuration.mdx
website/docs/guides/docs/versioning.mdx

Fix https://github.com/facebook/docusaurus/issues/10833
The `docsVersionDropdown` navbar item supports a new `versions` attribute to filter/whitelist displayed versions. Only the provided versions will be displayed.
Example:
```js
{
type: 'docsVersionDropdown',
versions: ['1.0.1', '2.1.1']
},
```
Also gives the ability to override version attributes (for now, only display `label`) by providing an object.
```js
{
type: 'docsVersionDropdown',
versions: {
'1.0.1': {label: '1.x'},
'2.1.1': {label: '2.x'},
},
```
1. Go to the [deploy preview](https://gp-temp-docusaurus-app1.netlify.app/eazfuscator.net) website
2. Locate the docs version dropdown in the upper part of the website
3. Click on the dropdown
4. Notice how the version titles are customized
5. Notice how the list of versions are …

feat(theme): add `versions` attribute to `docsVersionDropdown` navbar item

---

packages/docusaurus-theme-classic/src/theme/CodeBlock/Content/String.tsx

Right now, code block “wrap” and “copy” buttons will show up in RSS feeds, and (as far as I’m aware) can’t be omitted using any feed config or existing settings.
Depending on the feed reader or the service consuming the feed, these empty `<button>` elements will still be treated as part of the content, alongside the code blocks.
Since these buttons don’t have any purpose outside of a browser-based context anyway, this PR removes those buttons unless they are being displayed in the browser.
Thanks!
I’m sending my RSS feed to an email newsletter service, which imports the content.
Since the buttons are currently part of the feed content, it is trying to import that too.
Deploy preview: https://deploy-preview-10866--docusaurus-2.netlify.app/

fix(theme): Hide code block buttons before React hydration 

---

packages/docusaurus-theme-translations/locales/pl/theme-common.json

fix(theme-translations): Add missing Polish (pl) theme translations

---

packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/DocCard/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocCardList/index.tsx
packages/docusaurus-theme-classic/src/theme/DocCardList/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocCategoryGeneratedIndexPage/index.tsx
packages/docusaurus-theme-classic/src/theme/DocCategoryGeneratedIndexPage/styles.module.css
packages/docusaurus-theme-classic/src/theme/DocItem/Paginator/index.tsx
packages/docusaurus-theme-classic/src/theme/DocPaginator/index.tsx

Ensure that the `<DocCard>` component maintains full height in its styles for better layout consistency.
before
after
Deploy preview: https://deploy-preview-10849--docusaurus-2.netlify.app/
Test links:
- https://deploy-preview-10849--docusaurus-2.netlify.app/tests/docs
- https://deploy-preview-10849--docusaurus-2.netlify.app/tests/docs/category/tests

fix(theme): fix `<DocCard>` height inconsistency

---

website/docs/guides/markdown-features/markdown-features-math-equations.mdx

Typically installation instructions come before usage instructions. The fact that usage section is placed at the top is justified as this may serve as a quick reference to those who have already used the feature before, but a quick note linking to the installation/configuration section will help those who are reading about this for the first time follow the steps in the proper order. This PR adds such a note in a nonintrusive way that doesn't affect the flow of the existing text.
Deploy preview: https://deploy-preview-10894--docusaurus-2.netlify.app/docs/markdown-features/math-equations

docs: Clarify how to enable math equations

---

website/docs/migration/v3.mdx
website/versioned_docs/version-3.7.0/migration/v3.mdx

It requires a lot of effort to ensure to replace all `*` and `**` not recognized as emphasis markers by CommonMark/MDXv2+ with `<em>` and `<strong>` in large CJK documents. I think they cannot be found by a simple regex. It is much easier to depend on [`remark-cjk-friendly` remark plugin](https://www.npmjs.com/package/remark-cjk-friendly) for CJK documents.
Check the changed page and confirm it looks great
Deploy preview: https://deploy-preview-10892--docusaurus-2.netlify.app/docs/migration/v3/#emphasis-starting-or-ending-with-a-space-or-a-punctuation
- #9692
- #9804
- https://github.com/commonmark/commonmark-spec/issues/650

docs: Suggest `remark-cjk-friendly` in migration guide

---

website/versioned_docs/version-2.x/api/themes/theme-live-codeblock.mdx
website/versioned_docs/version-3.0.1/api/themes/theme-live-codeblock.mdx
website/versioned_docs/version-3.1.1/api/themes/theme-live-codeblock.mdx
website/versioned_docs/version-3.2.1/api/themes/theme-live-codeblock.mdx
website/versioned_docs/version-3.3.2/api/themes/theme-live-codeblock.mdx
website/versioned_docs/version-3.4.0/api/themes/theme-live-codeblock.mdx
website/versioned_docs/version-3.5.2/api/themes/theme-live-codeblock.mdx
website/versioned_docs/version-3.6.3/api/themes/theme-live-codeblock.mdx
website/versioned_docs/version-3.7.0/api/themes/theme-live-codeblock.mdx

Original [PR](#10874) left out versioned docs. This PR updates these docs with the same change.
> Links out directly to package so consumers can find it easily.
Check links work from doc site
Deploy preview (versions): 
- 3.7.0: https://deploy-preview-10902--docusaurus-2.netlify.app/docs/3.7.0/api/themes/@docusaurus/theme-live-codeblock/
- 3.6.3: https://deploy-preview-10902--docusaurus-2.netlify.app/docs/3.6.3/api/themes/@docusaurus/theme-live-codeblock/
- Related to PR: #10874

docs(theme-live-codeblock): update versioned docs to include link to react-live

---

packages/docusaurus-plugin-debug/package.json
yarn.lock

React 19 was added as a peer dependency for `react-json-view-lite` in https://github.com/AnyRoad/react-json-view-lite/releases/tag/2.2.0, so updating this lib to better support react 19.
CI & Preview

chore(plugin-debug): upgrade react-json-view-lite to v2.3.0 for react 19

---

packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Category/index.tsx
packages/docusaurus-theme-common/src/components/Collapsible/index.tsx
packages/docusaurus-theme-common/src/components/Details/index.tsx

Fix https://github.com/facebook/docusaurus/issues/10854
Also, remove some `getSSRStyle` logic that messes up with initial animation and doesn't seem useful.
preview
https://deploy-preview-10886--docusaurus-2.netlify.app/docs

fix(theme): collapse doc sidebar category on label click if active

---

packages/docusaurus-plugin-content-blog/package.json
packages/docusaurus-plugin-content-docs/package.json
packages/docusaurus-plugin-content-docs/src/client/index.ts
packages/docusaurus-plugin-content-docs/src/client/structuredDataUtils.ts
packages/docusaurus-theme-classic/src/theme-classic.d.ts
packages/docusaurus-theme-classic/src/theme/DocBreadcrumbs/StructuredData/index.tsx
packages/docusaurus-theme-classic/src/theme/DocBreadcrumbs/index.tsx
packages/docusaurus-theme-common/package.json

There seem to be some failing tests, but as far as I can tell these are not related to my changes.
To have the structured data approach favoured by Google (JSON-LD) and also consistency.
Deploy preview: https://deploy-preview-10888--docusaurus-2.netlify.app/docs/configuration/
#9319

fix(seo): docs breadcrumb structured data should use JSON-LD and filter unliked categories

---

packages/docusaurus-mdx-loader/src/loader.ts
packages/docusaurus-mdx-loader/src/options.ts
packages/docusaurus-plugin-content-docs/src/index.ts

We have a bundler cache invalidation problem, that I discovered while working on https://github.com/facebook/docusaurus/pull/10931
The following works:
```bash
DOCUSAURUS_SLOWER=true 
yarn clear:website
yarn build:website --locale en
yarn build:website --locale en
yarn clear:website
yarn build:website:fast
yarn build:website:fast
```
But the following fails with broken link errors:
```bash
DOCUSAURUS_SLOWER=true 
yarn clear:website
yarn build:website --locale en
yarn build:website:fast
```
```bash
Exhaustive list of all broken links found:
- Broken link on source page path = /docs:
-> linking to /docs/next/migration
- Broken link on source page path = /docs/advanced:
-> linking to /docs/next/api/plugin-methods
- Broken link on source page path = /docs/advanced/architecture:
-> linking to …
```

fix(docs): fix mdx loader cache invalidation bug on versions changes

---

website/docs/api/plugins/plugin-debug.mdx

Documentation says[^1]
- https://github.com/facebook/docusaurus/blob/0a89f48fcc632e7583025fc778fc821b846d2362/website/docs/api/plugins/plugin-debug.mdx?plain=1#L13-L21
But code snippet does the opposite. This change updates code snippet to disable plugin in production by default.
[^1]: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-debug

docs: disable `plugin-debug` in production by default

---

packages/docusaurus-theme-search-algolia/package.json
yarn.lock

Not strictly needed but this should ensure that we support this new version by dogfooding on our own website, remove a warning on our website, and also ensure that users upgrading Docusaurus will automatically get a React 19 compatible version
See also https://github.com/facebook/docusaurus/issues/10817#issuecomment-2670989511
CI + Argos
https://deploy-preview-10941--docusaurus-2.netlify.app/

chore(algolia): bump docsearch dependency to v3.9

---

packages/docusaurus-theme-classic/src/theme/AnnouncementBar/index.tsx
packages/docusaurus-theme-classic/src/theme/Footer/Layout/index.tsx
packages/docusaurus-theme-classic/src/theme/Footer/Links/MultiColumn/index.tsx
packages/docusaurus-theme-classic/src/theme/Layout/index.tsx
packages/docusaurus-theme-classic/src/theme/Navbar/Content/index.tsx
packages/docusaurus-theme-classic/src/theme/Navbar/Layout/index.tsx
packages/docusaurus-theme-classic/src/theme/Navbar/MobileSidebar/Layout/index.tsx
packages/docusaurus-theme-common/src/utils/ThemeClassNames.ts

Adding stable classes to main theme layout elements is helpful for users to write reliable CSS selectors.
We'd prefer users to avoid using Infima class names whenever possible, this is important is we want to support Tailwind for example, and still allow users to write selectors. 
This is a first step in that direction, but is not exhaustive
Supersede https://github.com/facebook/docusaurus/pull/10843
CI + Argos + preview review
https://deploy-preview-10945--docusaurus-2.netlify.app/

feat(theme): add theme layout stable CSS classes

---

packages/docusaurus-theme-classic/src/theme/Layout/index.tsx

Fix a typo introduced by https://github.com/facebook/docusaurus/pull/10945. We are passing a key-value pair to clsx whose value is truthy, so its key, `container`, gets used as the class, which happens to be a valid class with its own properties 😅
This is causing rendering anomalies in prod:

fix(theme-classic): fix ThemeClassName reference

---

packages/docusaurus-theme-common/src/contexts/colorMode.tsx
packages/docusaurus-theme-common/src/utils/useThemeConfig.ts

It's not safe to init `useState(getPersistedColorModeIfBrowser())`, and can lead to React hydration mismatches.
We notably had one visible in `docusaurus build --dev` when loading a page in dark mode:
```bash
ColorModeToggle
+                               title="Switch between dark and light mode (currently dark mode)"
-                               title="Switch between dark and light mode (currently light mode)"
+                               aria-label="Switch between dark and light mode (currently dark mode)"
-                               aria-label="Switch between dark and light mode (currently light mode)"
aria-live="polite"
+                               aria-pressed="true"
-                               aria-pressed="false"
```
Using this code is safe and prevents hydration …

fix(theme): fix `useColorMode().colorMode` leading to React hydration mismatches

---

.github/workflows/build-perf.yml
package.json
packages/docusaurus-cssnano-preset/src/index.ts
packages/docusaurus-mdx-loader/src/processor.ts
packages/docusaurus-mdx-loader/src/remark/admonitions/index.ts
packages/docusaurus-mdx-loader/src/remark/contentTitle/index.ts
packages/docusaurus-mdx-loader/src/remark/details/index.ts
packages/docusaurus-mdx-loader/src/remark/head/index.ts
packages/docusaurus-mdx-loader/src/remark/headings/index.ts
packages/docusaurus-mdx-loader/src/remark/mdx1Compat/codeCompatPlugin.ts
packages/docusaurus-mdx-loader/src/remark/mermaid/index.ts
packages/docusaurus-mdx-loader/src/remark/resolveMarkdownLinks/index.ts
packages/docusaurus-mdx-loader/src/remark/toc/index.ts
packages/docusaurus-mdx-loader/src/remark/toc/utils.ts
packages/docusaurus-mdx-loader/src/remark/transformImage/index.ts
packages/docusaurus-mdx-loader/src/remark/transformLinks/index.ts
packages/docusaurus-mdx-loader/src/remark/unusedDirectives/index.ts
packages/docusaurus-mdx-loader/src/remark/utils/index.ts
packages/docusaurus-plugin-content-blog/src/remark/footnoteIDFixer.ts
packages/docusaurus-remark-plugin-npm2yarn/src/index.ts
packages/eslint-plugin/src/index.ts
packages/stylelint-copyright/src/index.ts
tsconfig.base.json
yarn.lock

See https://devblogs.microsoft.com/typescript/announcing-typescript-5-8/
Looks like we can get rid of various TS errors related to importing ESM types from CJS modules (mostly in the MDX loader)
Also enables the new `erasableSyntaxOnly` for possible future native TS usage
CI
https://deploy-preview-10966--docusaurus-2.netlify.app/

chore: upgrade monorepo to TS 5.8

---

.eslintrc.js
package.json
packages/docusaurus-theme-classic/src/theme/CodeBlock/Line/index.tsx
packages/docusaurus-theme-common/src/components/Collapsible/index.tsx
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/reactUtils.tsx
packages/docusaurus-theme-common/src/utils/scrollUtils.tsx
packages/docusaurus-theme-common/src/utils/storageUtils.ts
packages/docusaurus-theme-mermaid/src/client/index.ts
packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.tsx
packages/docusaurus-theme-search-algolia/src/theme/SearchPage/index.tsx
yarn.lock

In the future, we might want to pre-compile our React code with the compiler
This PR fixes some issues that could prevent us from adopting the compiler in the future.
Some harder issues have been ignored for now but can be worked on incrementally.
More importantly, we now forbid introducing code that the compiler won't like
CI lint

chore: add `eslint-plugin-react-compiler`

---

packages/docusaurus-theme-common/src/contexts/navbarMobileSidebar.tsx
website/_dogfooding/_pages tests/history-tests.tsx
website/_dogfooding/_pages tests/index.mdx

`history.block()` supports only a single blocker "prompt" at a time.
Rendering the mobile drawer history blocker even when our mobile drawer is not displayed means that users can't use `history.block()` reliably anywhere in their React code.
To work around this issue, let's render our mobile drawer history blocker conditionally.
This is a workaround for https://github.com/facebook/docusaurus/issues/10988, not a completely accurate fix but probably good enough until we figure things out.
Dogfood test page works after the change, fails before (doesn't print the alert).
https://deploy-preview-10989--docusaurus-2.netlify.app/tests/pages/, then navigate to "history-tests", then press back button
https://github.com/facebook/docusaurus/issues/10988

fix(theme): mobile drawer history blocker should be rendered conditionally (workaround)

---

packages/docusaurus-theme-classic/src/theme-classic.d.ts
website/_dogfooding/_pages tests/code-block-tests.mdx

The `CodeBlock` component is a nice component that can be reused consistently through all the docs. To allow more customization, it would be nice to pass `ReactNodes` instead of plain strings to the `title` container.  This is already possible and works by passing in `ReactNodes` and casting them `as any`:
```tsx
<CodeBlock
language="yaml"
title={
(<div
style={{
display: 'flex',
justifyContent: 'space-between',
alignItems: 'center',
}}>
<span>
<code>ReactNode</code> title
</span>{' '}
<span className="badge badge--primary">YAML</span>
</div>) as any
}>
{`link:
title: front page
path: /docs/`}
</CodeBlock>
```
This PR fixes the types and adds a dogfood example.
```tsx
<CodeBlock
language="yaml"
title={
<div
style={{
display: 'flex',
justifyContent: 'space-between',
alignItems: 'center', …
```

fix(theme): CodeBlock should accept `title` of `ReactNode` type

---

packages/docusaurus-module-type-aliases/package.json

Fixes warning when installing dependencies. 
Yarn warns:
```sh
warning Pattern ["react-helmet-async@npm:@slorber/react-helmet-async@*"] is trying to unpack in the same destination "/home/.cache/yarn/v6/npm-react-helmet-async-1.3.0-11fbc6094605cf60aa04a28c17e0aab894b4ecff-integrity/node_modules/react-helmet-async" as pattern ["react-helmet-async@npm:@slorber/react-helmet-async@1.3.0"]. This could result in non-deterministic behavior, skipping.
```
Check that there is no warning during yarn install https://app.netlify.com/sites/docusaurus-2/deploys/67d56f144b21080008ab6517#L149
Deploy preview: https://deploy-preview-10998--docusaurus-2.netlify.app/
#10997

fix(module-type-aliases): pin react-helmet-async to  @slorber/react-helmet-async@1.3.0

---

packages/docusaurus-mdx-loader/src/remark/toc/__tests__/utils.test.ts
packages/docusaurus-mdx-loader/src/remark/toc/utils.ts
packages/docusaurus-mdx-loader/src/remark/utils/index.ts

Fix https://github.com/facebook/docusaurus/issues/11003
The previous implementation creates empty img tags, leading to minification errors
```tsx
it('converts a heading with img tag', async () => {
const heading: Heading = {
type: 'heading',
depth: 2,
children: [
{
type: 'mdxJsxTextElement',
name: 'img',
attributes: [
{
type: 'mdxJsxAttribute',
name: 'src',
value: '/img/slash-introducing.svg',
},
{
type: 'mdxJsxAttribute',
name: 'height',
value: '32',
},
{
type: 'mdxJsxAttribute',
name: 'alt',
value: 'test',
},
],
children: [],
},
{
type: 'text',
value: ' Some title',
},
],
};
await expect(convert(heading)).resolves.toMatchInlineSnapshot(
`"<img></img> Some title"`,
);
});
```

fix(mdx-loader): refactor and fix heading to toc html value serialization

---

.gitignore
package.json
packages/docusaurus-faster/src/index.ts
packages/docusaurus/src/commands/start/start.ts
packages/docusaurus/src/webpack/base.ts
packages/docusaurus/src/webpack/plugins/BundlerCPUProfilerPlugin.ts

Inspired by a PR from the Rspack team (https://github.com/jerrykingxyz/docusaurus/pull/1), let's add useful profiling/tracing tools to Docusaurus core.
For now, we consider it an internal feature, and we may eventually document that in the future if it works well for us and could benefit the community. Note that we already have an Rsdoctor plugin as part of our public API.
Secret env variables to toggle:
```bash
DOCUSAURUS_BUNDLER_CPU_PROFILE=true # produce bundler-cpu-profile.json - open in speedscope.app
DOCUSAURUS_RSPACK_TRACE=true # produce rspack-tracing.json - open in ui.perfetto.dev
```
More details here: https://rspack.dev/contribute/development/profiling
local test only

feat(core): Add bundler tracing/profiling

---

packages/docusaurus/src/commands/utils/openBrowser/openBrowser.ts

See https://github.com/jerrykingxyz/docusaurus/pull/1
The Rspack team helped us identify that the `openBrowser()` util we copied from Create-React-App is not optimized: 
https://github.com/facebook/create-react-app/blob/main/packages/react-dev-utils/openBrowser.js#L76
The Rspack compilation is delayed because it uses blocking `execSync` calls on macOS only. 
In this env, the util tries to run an AppleScript so that we "reuse" an existing chromium tab using `https://localhost:3000` instead of opening a new one. 
```js
execSync('ps cax | grep "' + chromiumBrowser + '"');
execSync(
'osascript openChrome.applescript "' +
encodeURI(url) +
'" "' +
chromiumBrowser +
'"',
{
cwd: __dirname,
stdio: 'ignore',
}
);
```
We'd like to keep this, since it's better DX, but not at the cost of slowing down …

perf(core): Optimize `docusaurus start/serve`, fix `openBrowser()` perf issue on macOS

---

packages/docusaurus-utils/src/__tests__/globUtils.test.ts
packages/docusaurus-utils/src/globUtils.ts

The Docusaurus CLI `docusaurus write-translations` is trying to extract translations from `.d.ts` files, leading to errors.
Reported by @tats-u here https://github.com/facebook/docusaurus/issues/3526#issuecomment-2747942435
CI / unit tests

fix(cli): fix CLI write-translation bug

---

packages/docusaurus-theme-common/src/utils/__tests__/__snapshots__/codeBlockUtils.test.ts.snap
packages/docusaurus-theme-common/src/utils/__tests__/codeBlockUtils.test.ts

This PR is part of a series related to #11008 and it superceeds https://github.com/facebook/docusaurus/pull/11011 in the goal to splitup the work into more isolated refactoring/feature parts. 
Step 1 (this PR): Splitup current parseLines logic
Step 2 (#11019): Parse metastring into metaOptions and use it across components.
Step 3 (#11021): Add parsing of any options specified in the metastring.
Step 4 (#11022): Add CodeBlockToken component to customize DOM of highlighted tokens. 
Step 5 (#11023): Pass `metaOptions` to whole codeblock component tree.
The motivation of this part ~~is~~ was to prepare the codebase for the upcoming extensions and adaptions. Initially step 2 had the parsing added to `parseLines` so splitting things up and defining types was a good preparation for extension. …

test(theme-common): Add tests for getLineNumbersStart

---

packages/docusaurus-theme-common/src/utils/__tests__/__snapshots__/codeBlockUtils.test.ts.snap
packages/docusaurus-theme-common/src/utils/__tests__/codeBlockUtils.test.ts
packages/docusaurus-theme-common/src/utils/codeBlockUtils.ts

fix: with CRLF line breaks, an extra empty line was rendered with // highlight-end at end of code blocks
See: #11036

fix(theme): Fix code block magic comments with CRLF line breaks bug

---

packages/docusaurus-faster/package.json
packages/docusaurus/src/webpack/base.ts
yarn.lock

See https://rspack.dev/blog/announcing-1-3
Useful for parallel code splitting, but also support for browserslist/output.environment to reduce output size.
CI
https://deploy-preview-11039--docusaurus-2.netlify.app/
Note, I think there's a perf regression between 1.2.5 - 1.2.8, and 1.3 improves things a bit with parallel code splitting.
Doesn't seem big deal to force upgrade to v1.3 though, but I'll try to see why this happens
hyperfine --prepare 'yarn clear:website' --runs 5 'yarn build:website:fast'
Benchmark 1: yarn build:website:fast
Time (mean ± σ):     17.849 s ±  0.254 s    [User: 60.544 s, System: 9.482 s]
Range (min … max):   17.474 s … 18.152 s    5 runs
hyperfine --prepare 'yarn clear:website' --runs 5 'yarn build:website:fast'
Benchmark 1: yarn build:website:fast
Time (mean ± …

chore: use rspack 1.3.0

---

packages/docusaurus/src/webpack/base.ts

Re-enable Rspack `parallelCodeSplitting`, coming with v1.3 by default
It was disabled in https://github.com/facebook/docusaurus/pull/11039 due to a possible Rspack bug: https://github.com/web-infra-dev/rspack/issues/9834
But it turns out it's our fault, due to using `optimization.removeAvailableModules: false`:
- 2019 PR, I'm not sure it was really a good change: https://github.com/facebook/docusaurus/pull/1711: 
- Doc: https://webpack.js.org/configuration/optimization/#optimizationremoveavailablemodules
CI + build size report
https://deploy-preview-11067--docusaurus-2.netlify.app/

feat(core): enable Rspack `parallelCodeSplitting`

---

packages/docusaurus-plugin-content-blog/assets/atom.xsl

Fix https://github.com/facebook/docusaurus/issues/11060
The XSL wasn't correct and wouldn't produce the right link href
Preview / manual, not sure how to automate this kind of test 😅 
https://deploy-preview-11068--docusaurus-2.netlify.app/blog/atom.xml

fix(blog): fix blog Atom feed item url / XSL bug

---

website/docs/deployment.mdx

Linter is unhappy about https://github.com/facebook/docusaurus/pull/11145 and tries to reformat yaml code blocks

fix: fix docs lint issue

---

packages/docusaurus-theme-common/src/internal.ts
packages/docusaurus-theme-common/src/utils/codeBlockUtils.tsx
website/docs/deployment.mdx

It's preferable to keep retro-compatibility on these APIs even if they are not officially public API surface.
Various sites swizzled the code block components and would have to upgrade.
We also have third-party plugins using these APIs, for example:
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/blob/main/packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/ApiCodeBlock/Content/String.tsx
```ts
import {
parseCodeBlockTitle,
parseLanguage,
parseLines,
containsLineNumbers,
useCodeWordWrap,
} from "@docusaurus/theme-common/internal";
```
Will test on third-party sites / canary

fix(theme): restore former code block theme-common internal APIs

---

packages/docusaurus-logger/src/perfLogger.ts
packages/docusaurus/src/client/serverEntry.tsx
packages/docusaurus/src/client/serverHelmetUtils.tsx
packages/docusaurus/src/common.d.ts
packages/docusaurus/src/ssg/ssgExecutor.ts
packages/docusaurus/src/ssg/ssgRenderer.ts

This is a fix for my https://github.com/facebook/docusaurus/issues/11161 about heavy collected data memory usage.
Some data is collected and is only useful during the SSG phase.
Once the HTML file is written, we'd like to release that now useless data asap on the worker thread before sending the result to the parent thread. This reduces aggregated site data in memory, and also reduces the size of the worker thread payloads.
```bash
yarn clear:website && NODE_OPTIONS="--max-old-space-size=400 --expose-gc" yarn build:website --locale en
```
I didn't do a proper benchmark, but from simple logs we can see it improves both memory and time to execute.
Before:
```bash
[PERF] Build > en > SSG > Thread pool - 13.55 seconds! - (Heap 151mb -> 161mb / Total 209mb)
```
After:
```bash
[PERF] Build > en …
```

perf(core): optimize SSG collected data memory and worker thread communication

---

packages/docusaurus-utils/package.json
packages/docusaurus-utils/src/gitUtils.ts
packages/docusaurus/src/commands/build/buildLocale.ts
yarn.lock

Fix https://github.com/facebook/docusaurus/issues/10348
Avoids Node.js EBADF error on large Docusaurus sites due to running too many concurrent Git commands.
I choose `os.availableParallelism() * 4;` as an arbitrary default concurrency value. It's high on purpose to be conservative with the former behavior, which was Infinity. As my local benchmark shows, between 4 and Infinity, the performance impact is quite low anyway.
It's hard to provide the perfect default value, but we can see on my Mac M3 Pro that:
- Concurrency 1 is the slowest
- Concurrency 0 (= Infinity) is slower than any concurrency > 4
- On my computer (12 cores), the sweet spot seems to be in between concurrency 10 -> 100
```bash
hyperfine --runs 4 \
'DOCUSAURUS_GIT_COMMAND_CONCURRENCY=0 yarn build:website --locale en' \ …
```

perf(utils): implement git command queue

---

packages/docusaurus/src/ssg/ssgEnv.ts
packages/docusaurus/src/ssg/ssgExecutor.ts

See issue https://github.com/facebook/docusaurus/issues/11161
During SSG, for large sites, the memory keeps growing.
Note:
- There's a separate heap for the parent thread, and each worker thread
- Each worker inherits the heap size from its parent (for example using `NODE_OPTIONS="--max-old-space-size=5000"`), and for some reason I couldn't figure out how to allocate a different heap size for a specific worker (see https://x.com/sebastienlorber/status/1920781195618513143)
If the main process is given 5gb and we have 5 workers each using up to 5gb too, that means potentially 30gb of memory, and the app is likely to swap, in particular if memory in workers keep growing and can't be collected. When this happens, SSG times increase significantly. Also, the user doesn't expect that Docusaurus …

feat(core): expose opt-in env variable for SSG thread recycling

---

.github/workflows/argos.yml
.github/workflows/lighthouse-report.yml
.github/workflows/tests-e2e.yml
.github/workflows/tests-windows.yml
.github/workflows/tests.yml
packages/docusaurus-mdx-loader/src/remark/transformImage/index.ts
packages/docusaurus-mdx-loader/src/remark/transformLinks/index.ts
packages/docusaurus-utils/src/urlUtils.ts

We'll upgrade to Node >= 24 for Docusaurus v4 so now is a good time to see if we are compatible
Also fix a `url.parse` deprecation warning, see also https://github.com/nodejs/node/pull/55017#issuecomment-2867085793
CI
https://deploy-preview-11168--docusaurus-2.netlify.app/

chore: add Node 24 to CI + fix deprecation warnings

---

packages/docusaurus-bundler/src/currentBundler.ts
packages/docusaurus-bundler/src/index.ts
packages/docusaurus-faster/package.json
packages/docusaurus-faster/src/index.ts
packages/docusaurus/src/commands/build/buildLocale.ts
packages/docusaurus/src/webpack/base.ts
website/docusaurus.config.ts
yarn.lock

On a large [11k docs Docusaurus site](https://github.com/facebook/docusaurus/discussions/11140), we noticed that the build times are particularly long, in particular the bundling that takes 20 minutes and doesn't really decrease on rebuilds with persistent caching.
To investigate the bundling perf issue, I slimmed down the Rspack config to focus only on the server config build with persistent cache disabled. This config takes ~10min to build, 6m+ of them are related to module concatenation:
If we disable this `concatenateModules` optimization, the bundling is much faster:
This `concatenateModules` optimization is quite expensive, and it's useless to run it on the server bundler. For the client bundle, it saves ~3% of total JS size on the site `build/assets/js` folder:
```bash
du -sk …
```

perf(bundler): fine-tuning of Webpack/Rspack optimizations

---

packages/docusaurus-plugin-content-docs/src/index.ts

Supersede https://github.com/facebook/docusaurus/pull/11114 after Rspack fixed the cache issue in Rspack 1.3.6
This MDX dependency file permits to invalidate the mdx loader cache entries when anything inside that file changes.
It probably doesn't cover all the possible edge cases, but already better than what we have before: stale cache issues leading to unexpected bundling output.
CI + local

fix(mdx-loader): remove opt-in for mdx dependency file

---

project-words.txt
website/blog/releases/3.0/index.mdx
website/community/4-canary.mdx
website/community/5-release-process.mdx
website/src/components/Versions.tsx

Fix https://github.com/facebook/docusaurus/issues/11159
The previously described process (next version on main, always using backports for stable releases minor versions) has been abandoned a long time ago in favor of a simpler process where we only release from the main branch and limit backports to critical security fixes.

docs: adjust the Docusaurus release process documentation to our new simpler process

---

packages/docusaurus/src/commands/utils/openBrowser/openBrowser.ts

Fix https://github.com/facebook/docusaurus/issues/11204
grep returns exit code 1 by default when the no match found, leading to an error for macOS users that have no Chromium-based browser installed
Local only 😅 
This reverts to what CRA used to do before my change: swallow errors
See also PR introducing the bug: https://github.com/facebook/docusaurus/pull/11007

fix(core): fix `docusaurus start` error for macOS users with no Chromium-based browser

---

website/_dogfooding/dogfooding.config.ts
website/docusaurus.config.ts

Related to:
- https://github.com/facebook/docusaurus/issues/11208
- https://github.com/facebook/docusaurus/pull/11211
Running useless `git log` commands for our localized sites significantly slows them down.
Until we find a general way to solve this problem for all sites, this temporary trick permits us to optimize our own website deployment.
Before:
```bash
[PERF] Build > fr > Load site - 7.92 seconds!
```
After:
```bash
[PERF] Build > fr > Load site - 1.15 seconds!
```
Local + our CI
https://deploy-preview-11214--docusaurus-2.netlify.app/

perf(website): optimize website i18n build time by removing useless git log calls

---

packages/docusaurus/src/commands/utils/openBrowser/openBrowser.ts

[**Arc**](https://arc.net/) is based on Chromium [...]. It supports Google Chrome's browser extensions [...].
> Source: [en.wikipedia.org/wiki/Arc_(web_browser)](https://en.wikipedia.org/wiki/Arc_(web_browser))
> [!NOTE]
> I don't see this change as a `feat`, so I opted for `fix` based on a patch _semver_. Feel free to change it if the _PR_ is approved 🙋🏻‍♂️
I couldn't find a tests for the `tryOpenWithAppleScript` method. I'm open to contributing to this if needed.
About the grep name match:
> <img width="182" alt="Screenshot 2025-05-28 at 04 47 00" src="https://github.com/user-attachments/assets/cf4ffd22-005d-41f0-ba90-f5318f1bc69d" />
`...`
Deploy preview: https://deploy-preview-11217--docusaurus-2.netlify.app/
About the changed code comment:
- …

fix: include Arc to supported Chromium Browsers

---

website/src/plugins/featureRequests/FeatureRequestsPage.tsx

If a user lands on the feature request community page with the theme set to dark the canny widget is rendered twice, first light and then dark. The first call with the light theme takes effect as the widget has not yet loaded and the widget shows in light theme. Adding a small delay prevents the first render with the wrong theme.
Deploy preview: https://deploy-preview-11224--docusaurus-2.netlify.app/

fix(website): ensure feedback widget renders with correct theme

---

packages/docusaurus-plugin-content-docs/src/__tests__/docs.test.ts
packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/server-export.ts
packages/docusaurus-plugin-content-docs/src/versions/__tests__/__fixtures__/minimal-site/docs/hello.md
packages/docusaurus-plugin-content-docs/src/versions/__tests__/__snapshots__/loadVersion.test.ts.snap
packages/docusaurus-plugin-content-docs/src/versions/__tests__/loadVersion.test.ts
packages/docusaurus-plugin-content-docs/src/versions/__tests__/version.test.ts
packages/docusaurus-plugin-content-docs/src/versions/files.ts
packages/docusaurus-plugin-content-docs/src/versions/loadVersion.ts
packages/docusaurus-plugin-content-docs/src/versions/version.ts

We want to make it easier to write unit tests for docs `loadContent()` lifecycle
This PR only moves code around, doesn't change any behavior, and add an example unit test that is simpler than what we had to do before (instanciate a full docs plugin)
This will help write a unit test for solving this bug: https://github.com/facebook/docusaurus/issues/11136
CI
https://deploy-preview-11230--docusaurus-2.netlify.app/

refactor(docs): extract `loadVersion()` without changing the behavior

---

website/src/css/custom.css

https://github.com/facebook/docusaurus/pull/10945 changed the class for the announcement bar, which broke the current CSS selector.
Before [http://docusaurus.io/](http://docusaurus.io/):
After [https://deploy-preview-11262--docusaurus-2.netlify.app/](https://deploy-preview-11262--docusaurus-2.netlify.app/):
Visit the links above to test the change.
https://deploy-preview-11262--docusaurus-2.netlify.app/

docs: fix announcement bar css selector

---

packages/docusaurus-theme-common/src/index.ts

Export FooterColumnItem type from utils/useThemeConfig.
I'm trying to create presets for footer section where i have multiple docusaurus.config.ts files for each deployment environment. I wanted to add `FooterColumnItem` type to each footer column preset for type safety and noticed that `FooterLinkItem` is exported but column item was not. 
I've not written any tests for this, advice welcome if it's needed.
I don't believe this is related to any issues or pre/existing PR's.

fix(theme-common): Export FooterColumnItem type

---

packages/docusaurus-plugin-content-docs/src/index.ts
packages/docusaurus-plugin-content-docs/src/versions/loadVersion.ts

Solving 2 cases annoying me:
- Infinite test watch loop due to creating an MDX dependency file
- Non-deterministic snapshot due to non-deterministic docs order returned by Globby (https://github.com/sindresorhus/globby/issues/131)
This shouldn't have any significant impact on anything apart from making my life easier
CI + local

test(docs): fix docs tests issues

---

packages/docusaurus/src/commands/utils/openBrowser/openBrowser.ts
yarn.lock

Fix little docusaurus start issue reported here by also catching synchronous errors that execPromise might throw
https://github.com/facebook/docusaurus/issues/11204#issuecomment-3073480330
hard to reproduce and test even locally 😓

fix(core): Fix docusaurus start on macOS when exec throws a synchronous error

---

.eslintrc.js
packages/docusaurus-plugin-pwa/src/registerSw.ts
packages/docusaurus-theme-classic/src/theme/NavbarItem/LocaleDropdownNavbarItem/index.tsx
packages/docusaurus-theme-common/package.json
packages/docusaurus-theme-common/src/index.ts
packages/docusaurus-theme-common/src/utils/__tests__/historyUtils.test.ts
packages/docusaurus-theme-common/src/utils/__tests__/useAlternatePageUtils.test.tsx
packages/docusaurus-theme-common/src/utils/historyUtils.ts
packages/docusaurus-theme-common/src/utils/useAlternatePageUtils.ts
packages/docusaurus-types/src/i18n.d.ts
packages/docusaurus-utils/src/__tests__/i18nUtils.test.ts
packages/docusaurus-utils/src/i18nUtils.ts
packages/docusaurus-utils/src/index.ts
packages/docusaurus/src/client/exports/ComponentCreator.tsx
packages/docusaurus/src/commands/build/build.ts
packages/docusaurus/src/commands/build/buildLocale.ts
packages/docusaurus/src/commands/build/buildUtils.ts
packages/docusaurus/src/commands/start/utils.ts
packages/docusaurus/src/server/__tests__/__snapshots__/configValidation.test.ts.snap
packages/docusaurus/src/server/__tests__/__snapshots__/site.test.ts.snap
packages/docusaurus/src/server/__tests__/configValidation.test.ts
packages/docusaurus/src/server/__tests__/i18n.test.ts
packages/docusaurus/src/server/__tests__/site.test.ts
packages/docusaurus/src/server/configValidation.ts
packages/docusaurus/src/server/i18n.ts
packages/docusaurus/src/server/site.ts
project-words.txt
website/docs/api/docusaurus.config.js.mdx
website/docs/i18n/i18n-tutorial.mdx

Fix https://github.com/facebook/docusaurus/issues/4723
Fix https://github.com/facebook/docusaurus/issues/6462
Fix https://github.com/facebook/docusaurus/issues/6075#issuecomment-991202081
Supersede https://github.com/facebook/docusaurus/pull/6731
This PR permits improving the i18n support for deploying an i18n site, in particular in more complex and multi-domain deployments.
We already had these:
- `url`: The url/domain of your site
- `baseUrl`: The baseUrl of your site's main locale, also used as a base for localized sites hosted under subpaths like `/<baseUrl>/<locale>/`
This introduces:
- `i18n.localeConfigs[locale].url`: The url/domain of your site for a given locale
- `i18n.localeConfigs[locale].baseUrl`: The baseUrl of your site for a given locale
Until now, Docusaurus had …

feat(core): Add `i18n.localeConfigs[locale].{url,baseUrl}` config options

---

packages/docusaurus-theme-classic/src/theme/Blog/Components/Author/index.tsx
packages/docusaurus-theme-classic/src/theme/Heading/index.tsx

Try to fix google auto-translate
Fix https://github.com/facebook/docusaurus/issues/11358
See also https://www.stefanjudis.com/today-i-learned/non-translatable-html-elements/
preview
https://deploy-preview-11360--docusaurus-2.netlify.app/

fix(theme): Add translate no to heading anchors and blog authors

---

packages/docusaurus-bundler/src/minifyHtml.ts
packages/docusaurus-faster/package.json
yarn.lock

SWC Html minifier automatically removes `<head>` tags since they are not strictly mandatory. However this cause troubles for LinkedIn crawlers to find social images based on `og:image` meta. 
We now use the new option to preserve `<head>` tags and avoid this kind of issue, fixing LinkedIn social images and maybe other services too?
Fix issue reported by @ramnivas here: https://github.com/facebook/docusaurus/issues/10556#issuecomment-3152116127
- Before: https://www.linkedin.com/post-inspector/inspect/docusaurus.io
- After: https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fdeploy-preview-11383--docusaurus-2.netlify.app%2F
https://deploy-preview-11383--docusaurus-2.netlify.app/
SWC issue: https://github.com/swc-project/swc/issues/10994

fix(ssg): HTML minifier should preserve `<head>` for `og:image` crawlers

---

packages/docusaurus-theme-mermaid/src/client/index.ts
packages/docusaurus-theme-mermaid/src/client/loadMermaid.ts
project-words.txt

I noticed that the Mermaid lib is heavy and is loaded eagerly.
It is only called in `useEffect`, so it's fine to defer the loading.
It doesn't impact all pages, but for some of them (in particular docs page not using diagrams), the amount of JS loaded can be quite significantly reduced, with one large chunk becoming much smaller. 
The mermaid code has probably been split by the bundler into another chunk that will not load on docs page without diagrams, and will load later, after hydration on docs pages using diagrams.
CI + preview
Deploy preview: https://deploy-preview-11438--docusaurus-2.netlify.app/

perf(theme-mermaid): lazy load the Mermaid library
